<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'Agent_Performance_Report_calldate',
'Agent_Performance_Report_callStatus',
'Agent_Performance_Report_dialerCampaign',
'Agent_Performance_Report_dialerList',
'Agent_Performance_Report_dialerAgent',
'Agent_Performance_Report_dialerPhone' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'Agent_Performance_Report_calldate' => array( 'integrated_search_field',
'search_field_label',
'search_field_options',
'search_field_between' ),
'Agent_Performance_Report_callStatus' => array( 'integrated_search_field1',
'search_field_label1',
'search_field_options1',
'search_field_between1' ),
'Agent_Performance_Report_dialerCampaign' => array( 'integrated_search_field2',
'search_field_label2',
'search_field_options2',
'search_field_between2' ),
'Agent_Performance_Report_dialerList' => array( 'integrated_search_field3',
'search_field_label3',
'search_field_options3',
'search_field_between3' ),
'Agent_Performance_Report_dialerAgent' => array( 'integrated_search_field4',
'search_field_label4',
'search_field_options4',
'search_field_between4' ),
'Agent_Performance_Report_dialerPhone' => array( 'integrated_search_field5',
'search_field_label5',
'search_field_options5',
'search_field_between5' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array( 'logo',
'menu',
'loginform_login',
'username_button' ),
'top' => array( 'search_header' ),
'above-grid' => array(  ),
'below-grid' => array( 'search_search',
'search_reset',
'search_back_list',
'search_cancel' ),
'grid' => array( 'search_field_label',
'search_field_options',
'integrated_search_field',
'search_field_between',
'search_field_label1',
'search_field_options1',
'integrated_search_field1',
'search_field_between1',
'search_field_label2',
'search_field_options2',
'integrated_search_field2',
'search_field_between2',
'search_field_label3',
'search_field_options3',
'integrated_search_field3',
'search_field_between3',
'search_field_label4',
'search_field_options4',
'integrated_search_field4',
'search_field_between4',
'search_field_label5',
'search_field_options5',
'integrated_search_field5',
'search_field_between5' ) ),
'formXtTags' => array( 'above-grid' => array(  ) ),
'itemForms' => array( 'logo' => 'supertop',
'menu' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'search_header' => 'top',
'search_search' => 'below-grid',
'search_reset' => 'below-grid',
'search_back_list' => 'below-grid',
'search_cancel' => 'below-grid',
'search_field_label' => 'grid',
'search_field_options' => 'grid',
'integrated_search_field' => 'grid',
'search_field_between' => 'grid',
'search_field_label1' => 'grid',
'search_field_options1' => 'grid',
'integrated_search_field1' => 'grid',
'search_field_between1' => 'grid',
'search_field_label2' => 'grid',
'search_field_options2' => 'grid',
'integrated_search_field2' => 'grid',
'search_field_between2' => 'grid',
'search_field_label3' => 'grid',
'search_field_options3' => 'grid',
'integrated_search_field3' => 'grid',
'search_field_between3' => 'grid',
'search_field_label4' => 'grid',
'search_field_options4' => 'grid',
'integrated_search_field4' => 'grid',
'search_field_between4' => 'grid',
'search_field_label5' => 'grid',
'search_field_options5' => 'grid',
'integrated_search_field5' => 'grid',
'search_field_between5' => 'grid' ),
'itemLocations' => array( 'search_field_label' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'search_field_options' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'search_field_between' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'search_field_label1' => array( 'location' => 'grid',
'cellId' => 'c' ),
'search_field_options1' => array( 'location' => 'grid',
'cellId' => 'c' ),
'integrated_search_field1' => array( 'location' => 'grid',
'cellId' => 'c' ),
'search_field_between1' => array( 'location' => 'grid',
'cellId' => 'c' ),
'search_field_label2' => array( 'location' => 'grid',
'cellId' => 'c2' ),
'search_field_options2' => array( 'location' => 'grid',
'cellId' => 'c2' ),
'integrated_search_field2' => array( 'location' => 'grid',
'cellId' => 'c2' ),
'search_field_between2' => array( 'location' => 'grid',
'cellId' => 'c2' ),
'search_field_label3' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'search_field_options3' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field3' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'search_field_between3' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'search_field_label4' => array( 'location' => 'grid',
'cellId' => 'c4' ),
'search_field_options4' => array( 'location' => 'grid',
'cellId' => 'c4' ),
'integrated_search_field4' => array( 'location' => 'grid',
'cellId' => 'c4' ),
'search_field_between4' => array( 'location' => 'grid',
'cellId' => 'c4' ),
'search_field_label5' => array( 'location' => 'grid',
'cellId' => 'c5' ),
'search_field_options5' => array( 'location' => 'grid',
'cellId' => 'c5' ),
'integrated_search_field5' => array( 'location' => 'grid',
'cellId' => 'c5' ),
'search_field_between5' => array( 'location' => 'grid',
'cellId' => 'c5' ) ),
'itemVisiblity' => array( 'menu' => 3,
'loginform_login' => 3,
'username_button' => 3 ) ),
'itemsByType' => array( 'search_header' => array( 'search_header' ),
'search_reset' => array( 'search_reset' ),
'search_back_list' => array( 'search_back_list' ),
'search_search' => array( 'search_search' ),
'search_cancel' => array( 'search_cancel' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'logout_link' => array( 'logout_link' ),
'adminarea_link' => array( 'adminarea_link' ),
'search_field' => array( 'integrated_search_field',
'integrated_search_field1',
'integrated_search_field2',
'integrated_search_field3',
'integrated_search_field4',
'integrated_search_field5' ),
'search_field_label' => array( 'search_field_label',
'search_field_label1',
'search_field_label2',
'search_field_label3',
'search_field_label4',
'search_field_label5' ),
'search_field_options' => array( 'search_field_options',
'search_field_options1',
'search_field_options2',
'search_field_options3',
'search_field_options4',
'search_field_options5' ),
'search_field_between' => array( 'search_field_between',
'search_field_between1',
'search_field_between2',
'search_field_between3',
'search_field_between4',
'search_field_between5' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'search_field_label',
'search_field_options',
'integrated_search_field',
'search_field_between' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'search_field_label1',
'search_field_options1',
'integrated_search_field1',
'search_field_between1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'search_field_label2',
'search_field_options2',
'integrated_search_field2',
'search_field_between2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'search_field_label3',
'search_field_options3',
'integrated_search_field3',
'search_field_between3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 0 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'search_field_label4',
'search_field_options4',
'integrated_search_field4',
'search_field_between4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 0 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'search_field_label5',
'search_field_options5',
'integrated_search_field5',
'search_field_between5' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 6 ) ) ),
'loginForm' => array( 'loginForm' => 1 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'search',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'search',
'type' => 'search',
'layoutId' => 'topbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'topbar-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ),
array( 'cell' => 'c3' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'logo' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'menu' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c3' => array( 'model' => 'c3',
'items' => array( 'loginform_login',
'username_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'search-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'search_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'search-above-grid',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'search-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'search_search',
'search_reset',
'search_back_list',
'search_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-search',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c3' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c4' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c5' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c5',
'items' => array( 'search_field_label',
'search_field_options',
'integrated_search_field',
'search_field_between' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'orientation' => 'vertical',
'align' => 'left' ),
'c' => array( 'model' => 'c5',
'items' => array( 'search_field_label1',
'search_field_options1',
'integrated_search_field1',
'search_field_between1' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'orientation' => 'vertical',
'align' => 'left' ),
'c2' => array( 'model' => 'c5',
'items' => array( 'search_field_label2',
'search_field_options2',
'integrated_search_field2',
'search_field_between2' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'orientation' => 'vertical',
'align' => 'left' ),
'c3' => array( 'model' => 'c5',
'items' => array( 'search_field_label3',
'search_field_options3',
'integrated_search_field3',
'search_field_between3' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'orientation' => 'vertical',
'align' => 'left' ),
'c4' => array( 'model' => 'c5',
'items' => array( 'search_field_label4',
'search_field_options4',
'integrated_search_field4',
'search_field_between4' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'orientation' => 'vertical',
'align' => 'left' ),
'c5' => array( 'model' => 'c5',
'items' => array( 'search_field_label5',
'search_field_options5',
'integrated_search_field5',
'search_field_between5' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'orientation' => 'vertical',
'align' => 'left' ) ),
'deferredItems' => array(  ),
'separateLabels' => false ) ),
'items' => array( 'search_header' => array( 'type' => 'search_header' ),
'search_reset' => array( 'type' => 'search_reset' ),
'search_back_list' => array( 'type' => 'search_back_list' ),
'search_search' => array( 'type' => 'search_search' ),
'search_cancel' => array( 'type' => 'search_cancel' ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'logout_link',
'adminarea_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => true ),
'logout_link' => array( 'type' => 'logout_link' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'integrated_search_field' => array( 'field' => 'Agent_Performance_Report_calldate',
'type' => 'search_field',
'orientation' => 0,
'joined' => false,
'separated' => true ),
'integrated_search_field1' => array( 'field' => 'Agent_Performance_Report_callStatus',
'type' => 'search_field',
'orientation' => 0,
'joined' => false,
'separated' => true ),
'integrated_search_field2' => array( 'field' => 'Agent_Performance_Report_dialerCampaign',
'type' => 'search_field',
'orientation' => 0,
'joined' => false,
'separated' => true ),
'integrated_search_field3' => array( 'field' => 'Agent_Performance_Report_dialerList',
'type' => 'search_field',
'orientation' => 0,
'joined' => false,
'separated' => true ),
'integrated_search_field4' => array( 'field' => 'Agent_Performance_Report_dialerAgent',
'type' => 'search_field',
'orientation' => 0,
'joined' => false,
'separated' => true ),
'integrated_search_field5' => array( 'field' => 'Agent_Performance_Report_dialerPhone',
'type' => 'search_field',
'orientation' => 0,
'joined' => false,
'separated' => true ),
'search_field_label' => array( 'type' => 'search_field_label',
'field' => 'Agent_Performance_Report_calldate',
'separated' => true ),
'search_field_options' => array( 'type' => 'search_field_options',
'field' => 'Agent_Performance_Report_calldate',
'separated' => true ),
'search_field_between' => array( 'type' => 'search_field_between',
'field' => 'Agent_Performance_Report_calldate',
'separated' => true ),
'search_field_label1' => array( 'type' => 'search_field_label',
'field' => 'Agent_Performance_Report_callStatus',
'separated' => true ),
'search_field_options1' => array( 'type' => 'search_field_options',
'field' => 'Agent_Performance_Report_callStatus',
'separated' => true ),
'search_field_between1' => array( 'type' => 'search_field_between',
'field' => 'Agent_Performance_Report_callStatus',
'separated' => true ),
'search_field_label2' => array( 'type' => 'search_field_label',
'field' => 'Agent_Performance_Report_dialerCampaign',
'separated' => true ),
'search_field_options2' => array( 'type' => 'search_field_options',
'field' => 'Agent_Performance_Report_dialerCampaign',
'separated' => true ),
'search_field_between2' => array( 'type' => 'search_field_between',
'field' => 'Agent_Performance_Report_dialerCampaign',
'separated' => true ),
'search_field_label3' => array( 'type' => 'search_field_label',
'field' => 'Agent_Performance_Report_dialerList',
'separated' => true ),
'search_field_options3' => array( 'type' => 'search_field_options',
'field' => 'Agent_Performance_Report_dialerList',
'separated' => true ),
'search_field_between3' => array( 'type' => 'search_field_between',
'field' => 'Agent_Performance_Report_dialerList',
'separated' => true ),
'search_field_label4' => array( 'type' => 'search_field_label',
'field' => 'Agent_Performance_Report_dialerAgent',
'separated' => true ),
'search_field_options4' => array( 'type' => 'search_field_options',
'field' => 'Agent_Performance_Report_dialerAgent',
'separated' => true ),
'search_field_between4' => array( 'type' => 'search_field_between',
'field' => 'Agent_Performance_Report_dialerAgent',
'separated' => true ),
'search_field_label5' => array( 'type' => 'search_field_label',
'field' => 'Agent_Performance_Report_dialerPhone',
'separated' => true ),
'search_field_options5' => array( 'type' => 'search_field_options',
'field' => 'Agent_Performance_Report_dialerPhone',
'separated' => true ),
'search_field_between5' => array( 'type' => 'search_field_between',
'field' => 'Agent_Performance_Report_dialerPhone',
'separated' => true ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>