<?php
			$optionsArray = array( 'pdf' => array( 'pdfView' => false ),
'listSearch' => array( 'alwaysOnPanelFields' => array(  ),
'searchPanel' => true,
'fixedSearchPanel' => false,
'simpleSearchOptions' => false,
'searchSaving' => false ),
'fields' => array( 'gridFields' => array( 'callsPcnt',
'perStatusCallsCount',
'totalCallsCount',
'totalTimePcnt',
'perStatusTotalTime',
'typingTimePcnt',
'perStatusTypingTime',
'talkTimePcnt',
'perStatusTalkTime' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array( 'dialerAgent',
'callsPcnt',
'perStatusCallsCount',
'totalCallsCount',
'totalTimePcnt',
'perStatusTotalTime',
'totalTotalTime',
'typingTimePcnt',
'perStatusTypingTime',
'totalTypingTime',
'talkTimePcnt',
'perStatusTalkTime',
'totalTalkTime',
'callStatus',
'callDate' ),
'filterFields' => array(  ),
'fieldItems' => array( 'callDate' => array( 'report_group_field' ),
'callsPcnt' => array( 'report_grid_field13' ),
'perStatusCallsCount' => array( 'report_grid_field12' ),
'totalCallsCount' => array( 'report_grid_field11' ),
'totalTimePcnt' => array( 'report_grid_field10' ),
'perStatusTotalTime' => array( 'report_grid_field9' ),
'typingTimePcnt' => array( 'report_grid_field7' ),
'perStatusTypingTime' => array( 'report_grid_field6' ),
'talkTimePcnt' => array( 'report_grid_field4' ),
'perStatusTalkTime' => array( 'report_grid_field3' ),
'dialerAgent' => array( 'report_group_field2' ),
'callStatus' => array( 'report_group_field1' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array( 'logo',
'menu',
'simple_search',
'list_options',
'loginform_login',
'username_button' ),
'left' => array( 'search_panel' ),
'top' => array( 'breadcrumb' ),
'above-grid' => array( 'details_found',
'page_size',
'print_panel' ),
'below-grid' => array( 'pagination' ),
'grid' => array( 'report_group_field',
'report_group_field1',
'report_group_field2',
'report_grid_field3',
'report_grid_field4',
'report_grid_field6',
'report_grid_field7',
'report_grid_field9',
'report_grid_field10',
'report_grid_field11',
'report_grid_field12',
'report_grid_field13' ) ),
'formXtTags' => array( 'top' => array( 'breadcrumb' ),
'above-grid' => array( 'details_found',
'grpsPerPage',
'print_friendly' ),
'below-grid' => array( 'pagination' ) ),
'itemForms' => array( 'logo' => 'supertop',
'menu' => 'supertop',
'simple_search' => 'supertop',
'list_options' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'search_panel' => 'left',
'breadcrumb' => 'top',
'details_found' => 'above-grid',
'page_size' => 'above-grid',
'print_panel' => 'above-grid',
'pagination' => 'below-grid',
'report_group_field' => 'grid',
'report_group_field1' => 'grid',
'report_group_field2' => 'grid',
'report_grid_field3' => 'grid',
'report_grid_field4' => 'grid',
'report_grid_field6' => 'grid',
'report_grid_field7' => 'grid',
'report_grid_field9' => 'grid',
'report_grid_field10' => 'grid',
'report_grid_field11' => 'grid',
'report_grid_field12' => 'grid',
'report_grid_field13' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array( 'menu' => 3,
'simple_search' => 3,
'list_options' => 3,
'loginform_login' => 3,
'username_button' => 3,
'search_panel' => 5,
'print_panel' => 5 ) ),
'itemsByType' => array( 'page_size' => array( 'page_size' ),
'details_found' => array( 'details_found' ),
'breadcrumb' => array( 'breadcrumb' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'simple_search' => array( 'simple_search' ),
'pagination' => array( 'pagination' ),
'list_options' => array( 'list_options' ),
'export_report_excel' => array( 'export_report_excel' ),
'export_report_word' => array( 'export_report_word' ),
'hide_search_panel' => array( 'hide_search_panel' ),
'show_search_panel' => array( 'show_search_panel' ),
'-' => array( '-',
'-1' ),
'search_panel' => array( 'search_panel' ),
'report_group_field' => array( 'report_group_field',
'report_group_field2',
'report_group_field1' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'logout_link' => array( 'logout_link' ),
'adminarea_link' => array( 'adminarea_link' ),
'print_panel' => array( 'print_panel' ),
'print_scope' => array( 'print_scope' ),
'print_button' => array( 'print_button' ),
'print_records' => array( 'print_records' ),
'advsearch_link' => array( 'advsearch_link' ),
'search_panel_field' => array( 'search_panel_field13',
'search_panel_field12',
'search_panel_field11',
'search_panel_field25',
'search_panel_field10',
'search_panel_field9',
'search_panel_field8',
'search_panel_field7',
'search_panel_field6',
'search_panel_field5',
'search_panel_field4',
'search_panel_field3',
'search_panel_field2',
'search_panel_field1',
'search_panel_field' ),
'report_grid_field' => array( 'report_grid_field13',
'report_grid_field12',
'report_grid_field11',
'report_grid_field10',
'report_grid_field9',
'report_grid_field7',
'report_grid_field6',
'report_grid_field4',
'report_grid_field3' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 1 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array( 'details_found' => array( 'tag' => 'DISPLAYING',
'type' => 2 ) ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'report',
'breadcrumb' => true ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'report',
'type' => 'report',
'layoutId' => 'topbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'topbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'logo',
'menu' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'simple_search',
'list_options',
'loginform_login',
'username_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'list-vbar',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'search_panel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'list-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'breadcrumb' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'report-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'details_found',
'page_size',
'print_panel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'report-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'pagination' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'report-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'report_group_field',
'report_group_field1',
'report_group_field2' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'report_grid_field3',
'report_grid_field4',
'report_grid_field6',
'report_grid_field7',
'report_grid_field9',
'report_grid_field10',
'report_grid_field11',
'report_grid_field12',
'report_grid_field13' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'page_size' => array( 'type' => 'page_size' ),
'details_found' => array( 'type' => 'details_found' ),
'breadcrumb' => array( 'type' => 'breadcrumb' ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu' ),
'simple_search' => array( 'type' => 'simple_search' ),
'pagination' => array( 'type' => 'pagination' ),
'list_options' => array( 'type' => 'list_options',
'items' => array( 'advsearch_link',
'show_search_panel',
'hide_search_panel',
'-1',
'export_report_excel',
'export_report_word' ) ),
'export_report_excel' => array( 'type' => 'export_report_excel' ),
'export_report_word' => array( 'type' => 'export_report_word' ),
'hide_search_panel' => array( 'type' => 'hide_search_panel' ),
'show_search_panel' => array( 'type' => 'show_search_panel' ),
'-' => array( 'type' => '-' ),
'search_panel' => array( 'type' => 'search_panel',
'items' => array( 'search_panel_field25',
'search_panel_field13',
'search_panel_field12',
'search_panel_field11',
'search_panel_field10',
'search_panel_field9',
'search_panel_field8',
'search_panel_field7',
'search_panel_field6',
'search_panel_field5',
'search_panel_field4',
'search_panel_field3',
'search_panel_field2',
'search_panel_field1',
'search_panel_field' ),
'_flexiblePanel' => true ),
'report_group_field' => array( 'field' => 'callDate',
'type' => 'report_group_field' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'logout_link',
'adminarea_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => true ),
'logout_link' => array( 'type' => 'logout_link' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'print_panel' => array( 'type' => 'print_panel',
'items' => array( 'print_scope',
'print_records',
'print_button' ) ),
'print_scope' => array( 'type' => 'print_scope' ),
'print_button' => array( 'type' => 'print_button' ),
'print_records' => array( 'type' => 'print_records' ),
'-1' => array( 'type' => '-' ),
'advsearch_link' => array( 'type' => 'advsearch_link' ),
'search_panel_field13' => array( 'field' => 'callsPcnt',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'report_grid_field13' => array( 'field' => 'callsPcnt',
'type' => 'report_grid_field' ),
'search_panel_field12' => array( 'field' => 'perStatusCallsCount',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'report_grid_field12' => array( 'field' => 'perStatusCallsCount',
'type' => 'report_grid_field' ),
'search_panel_field11' => array( 'field' => 'totalCallsCount',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field25' => array( 'field' => 'dialerAgent',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'report_grid_field11' => array( 'field' => 'totalCallsCount',
'type' => 'report_grid_field' ),
'search_panel_field10' => array( 'field' => 'totalTimePcnt',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'report_grid_field10' => array( 'field' => 'totalTimePcnt',
'type' => 'report_grid_field' ),
'search_panel_field9' => array( 'field' => 'perStatusTotalTime',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'report_grid_field9' => array( 'field' => 'perStatusTotalTime',
'type' => 'report_grid_field' ),
'search_panel_field8' => array( 'field' => 'totalTotalTime',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field7' => array( 'field' => 'typingTimePcnt',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'report_grid_field7' => array( 'field' => 'typingTimePcnt',
'type' => 'report_grid_field' ),
'search_panel_field6' => array( 'field' => 'perStatusTypingTime',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'report_grid_field6' => array( 'field' => 'perStatusTypingTime',
'type' => 'report_grid_field' ),
'search_panel_field5' => array( 'field' => 'totalTypingTime',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field4' => array( 'field' => 'talkTimePcnt',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'report_grid_field4' => array( 'field' => 'talkTimePcnt',
'type' => 'report_grid_field' ),
'search_panel_field3' => array( 'field' => 'perStatusTalkTime',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'report_grid_field3' => array( 'field' => 'perStatusTalkTime',
'type' => 'report_grid_field' ),
'search_panel_field2' => array( 'field' => 'totalTalkTime',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field1' => array( 'field' => 'callStatus',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'report_group_field2' => array( 'field' => 'dialerAgent',
'type' => 'report_group_field' ),
'search_panel_field' => array( 'field' => 'callDate',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'report_group_field1' => array( 'field' => 'callStatus',
'type' => 'report_group_field' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>