<?php
			$optionsArray = array( 'details' => array( 'dbo.internalComments' => array( 'displayPreview' => 1,
'previewPageId' => 'list' ),
'dbo.novaApplications' => array( 'displayPreview' => 1,
'previewPageId' => 'novaInlineAddList' ),
'dbo.voltonApplications' => array( 'displayPreview' => 1,
'previewPageId' => 'voltonInDetailAddList' ) ),
'captcha' => array( 'captcha' => false ),
'fields' => array( 'gridFields' => array( 'remarks',
'callStatusId',
'callDenialReasonID',
'redialDate',
'redialComments',
'dialerPhone',
'redialIsPrivate',
'callSubClassificationID',
'callClassificationID',
'callComments',
'totalCallTime',
'contactId',
'dialerAgent',
'callHangup',
'callStart',
'talkTime',
'typingTime',
'callEnd',
'tvchannel',
'broadcast',
'seller',
'dialerCampaign',
'dialerList',
'dialerRecording',
'dialerLeadID',
'dialerCallEpoch',
'pauseAfterCall' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'updateOnEditFields' => array( 'remarks',
'callStatusId',
'callDenialReasonID',
'redialDate',
'redialComments',
'dialerPhone',
'redialIsPrivate',
'callSubClassificationID',
'callClassificationID',
'callComments',
'totalCallTime',
'contactId',
'dialerAgent' ),
'fieldItems' => array( 'remarks' => array( 'integrated_edit_field9' ),
'callStatusId' => array( 'integrated_edit_field7' ),
'callDenialReasonID' => array( 'integrated_edit_field2' ),
'redialDate' => array( 'integrated_edit_field11' ),
'redialComments' => array( 'integrated_edit_field6' ),
'dialerPhone' => array( 'integrated_edit_field' ),
'redialIsPrivate' => array( 'integrated_edit_field12' ),
'callSubClassificationID' => array( 'integrated_edit_field8' ),
'callClassificationID' => array( 'integrated_edit_field3' ),
'callComments' => array( 'integrated_edit_field18' ),
'totalCallTime' => array( 'integrated_edit_field32',
'edit_field_label5' ),
'contactId' => array( 'integrated_edit_field22' ),
'dialerAgent' => array( 'integrated_edit_field17' ),
'callHangup' => array( 'integrated_edit_field1',
'edit_field_label1' ),
'callStart' => array( 'integrated_edit_field4',
'edit_field_label',
'edit_field' ),
'talkTime' => array( 'integrated_edit_field5',
'edit_field_label3' ),
'typingTime' => array( 'integrated_edit_field10',
'edit_field_label4' ),
'callEnd' => array( 'integrated_edit_field13',
'edit_field_label2' ),
'tvchannel' => array( 'integrated_edit_field14',
'edit_field_label8' ),
'broadcast' => array( 'integrated_edit_field15',
'edit_field_label6' ),
'seller' => array( 'integrated_edit_field16',
'edit_field_label7' ),
'dialerCampaign' => array( 'integrated_edit_field19' ),
'dialerList' => array( 'integrated_edit_field20' ),
'dialerRecording' => array( 'integrated_edit_field21' ),
'dialerLeadID' => array( 'integrated_edit_field23' ),
'dialerCallEpoch' => array( 'integrated_edit_field24' ),
'pauseAfterCall' => array( 'integrated_edit_field25' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => true,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array( 'logo',
'menu',
'loginform_login',
'username_button' ),
'top' => array( 'edit_header' ),
'above-grid' => array( 'edit_message' ),
'below-grid' => array( 'edit_save',
'update_records',
'edit_back_list',
'edit_close',
'hamburger' ),
'grid' => array( 'section2',
'section9',
'section3',
'section7',
'section' ),
'section6' => array( 'integrated_edit_field22' ),
'section5' => array( 'details_preview3' ),
'section2' => array( 'integrated_edit_field9',
'integrated_edit_field7',
'integrated_edit_field2',
'integrated_edit_field11',
'integrated_edit_field6',
'integrated_edit_field',
'integrated_edit_field12',
'section5',
'section4',
'section1',
'section8',
'section6',
'integrated_edit_field18',
'integrated_edit_field3',
'integrated_edit_field8',
'integrated_edit_field17',
'edit_field' ),
'section4' => array( 'edit_field_label8',
'integrated_edit_field14',
'edit_field_label7',
'integrated_edit_field16',
'integrated_edit_field15',
'edit_field_label6' ),
'section1' => array(  ),
'section' => array(  ),
'section3' => array( 'integrated_edit_field19',
'integrated_edit_field20',
'integrated_edit_field21',
'integrated_edit_field23',
'integrated_edit_field24',
'integrated_edit_field25' ),
'section7' => array( 'details_preview2' ),
'section8' => array( 'edit_field_label',
'edit_field_label2',
'edit_field_label1',
'integrated_edit_field5',
'integrated_edit_field10',
'integrated_edit_field32',
'edit_field_label3',
'edit_field_label4',
'edit_field_label5',
'integrated_edit_field4',
'integrated_edit_field1',
'integrated_edit_field13' ),
'section9' => array( 'details_preview1' ) ),
'formXtTags' => array( 'above-grid' => array( 'message_block' ) ),
'itemForms' => array( 'logo' => 'supertop',
'menu' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'edit_header' => 'top',
'edit_message' => 'above-grid',
'edit_save' => 'below-grid',
'update_records' => 'below-grid',
'edit_back_list' => 'below-grid',
'edit_close' => 'below-grid',
'hamburger' => 'below-grid',
'section2' => 'grid',
'section9' => 'grid',
'section3' => 'grid',
'section7' => 'grid',
'section' => 'grid',
'integrated_edit_field22' => 'section6',
'details_preview3' => 'section5',
'integrated_edit_field9' => 'section2',
'integrated_edit_field7' => 'section2',
'integrated_edit_field2' => 'section2',
'integrated_edit_field11' => 'section2',
'integrated_edit_field6' => 'section2',
'integrated_edit_field' => 'section2',
'integrated_edit_field12' => 'section2',
'section5' => 'section2',
'section4' => 'section2',
'section1' => 'section2',
'section8' => 'section2',
'section6' => 'section2',
'integrated_edit_field18' => 'section2',
'integrated_edit_field3' => 'section2',
'integrated_edit_field8' => 'section2',
'integrated_edit_field17' => 'section2',
'edit_field' => 'section2',
'edit_field_label8' => 'section4',
'integrated_edit_field14' => 'section4',
'edit_field_label7' => 'section4',
'integrated_edit_field16' => 'section4',
'integrated_edit_field15' => 'section4',
'edit_field_label6' => 'section4',
'integrated_edit_field19' => 'section3',
'integrated_edit_field20' => 'section3',
'integrated_edit_field21' => 'section3',
'integrated_edit_field23' => 'section3',
'integrated_edit_field24' => 'section3',
'integrated_edit_field25' => 'section3',
'details_preview2' => 'section7',
'edit_field_label' => 'section8',
'edit_field_label2' => 'section8',
'edit_field_label1' => 'section8',
'integrated_edit_field5' => 'section8',
'integrated_edit_field10' => 'section8',
'integrated_edit_field32' => 'section8',
'edit_field_label3' => 'section8',
'edit_field_label4' => 'section8',
'edit_field_label5' => 'section8',
'integrated_edit_field4' => 'section8',
'integrated_edit_field1' => 'section8',
'integrated_edit_field13' => 'section8',
'details_preview1' => 'section9' ),
'itemLocations' => array( 'section2' => array( 'location' => 'grid',
'cellId' => 'c5' ),
'section9' => array( 'location' => 'grid',
'cellId' => 'c5' ),
'section3' => array( 'location' => 'grid',
'cellId' => 'c5' ),
'section7' => array( 'location' => 'grid',
'cellId' => 'c5' ),
'section' => array( 'location' => 'grid',
'cellId' => 'c8' ),
'integrated_edit_field22' => array( 'location' => 'section6',
'cellId' => 'c3' ),
'details_preview3' => array( 'location' => 'section5',
'cellId' => 'c1' ),
'integrated_edit_field9' => array( 'location' => 'section2',
'cellId' => 'c52' ),
'integrated_edit_field7' => array( 'location' => 'section2',
'cellId' => 'c47' ),
'integrated_edit_field2' => array( 'location' => 'section2',
'cellId' => 'c49' ),
'integrated_edit_field11' => array( 'location' => 'section2',
'cellId' => 'c53' ),
'integrated_edit_field6' => array( 'location' => 'section2',
'cellId' => 'c56' ),
'integrated_edit_field' => array( 'location' => 'section2',
'cellId' => 'c7' ),
'integrated_edit_field12' => array( 'location' => 'section2',
'cellId' => 'c11' ),
'section5' => array( 'location' => 'section2',
'cellId' => 'c' ),
'section4' => array( 'location' => 'section2',
'cellId' => 'c' ),
'section1' => array( 'location' => 'section2',
'cellId' => 'c' ),
'section8' => array( 'location' => 'section2',
'cellId' => 'c' ),
'section6' => array( 'location' => 'section2',
'cellId' => 'c' ),
'integrated_edit_field18' => array( 'location' => 'section2',
'cellId' => 'c57' ),
'integrated_edit_field3' => array( 'location' => 'section2',
'cellId' => 'c16' ),
'integrated_edit_field8' => array( 'location' => 'section2',
'cellId' => 'c17' ),
'integrated_edit_field17' => array( 'location' => 'section2',
'cellId' => 'c15' ),
'edit_field' => array( 'location' => 'section2',
'cellId' => 'c20' ),
'edit_field_label8' => array( 'location' => 'section4',
'cellId' => 'c3' ),
'integrated_edit_field14' => array( 'location' => 'section4',
'cellId' => 'c2' ),
'edit_field_label7' => array( 'location' => 'section4',
'cellId' => 'c7' ),
'integrated_edit_field16' => array( 'location' => 'section4',
'cellId' => 'c8' ),
'integrated_edit_field15' => array( 'location' => 'section4',
'cellId' => 'c9' ),
'edit_field_label6' => array( 'location' => 'section4',
'cellId' => 'c10' ),
'integrated_edit_field19' => array( 'location' => 'section3',
'cellId' => 'c' ),
'integrated_edit_field20' => array( 'location' => 'section3',
'cellId' => 'c' ),
'integrated_edit_field21' => array( 'location' => 'section3',
'cellId' => 'c' ),
'integrated_edit_field23' => array( 'location' => 'section3',
'cellId' => 'c' ),
'integrated_edit_field24' => array( 'location' => 'section3',
'cellId' => 'c' ),
'integrated_edit_field25' => array( 'location' => 'section3',
'cellId' => 'c' ),
'details_preview2' => array( 'location' => 'section7',
'cellId' => 'c1' ),
'edit_field_label' => array( 'location' => 'section8',
'cellId' => 'c6' ),
'edit_field_label2' => array( 'location' => 'section8',
'cellId' => 'c7' ),
'edit_field_label1' => array( 'location' => 'section8',
'cellId' => 'c8' ),
'integrated_edit_field5' => array( 'location' => 'section8',
'cellId' => 'c10' ),
'integrated_edit_field10' => array( 'location' => 'section8',
'cellId' => 'c11' ),
'integrated_edit_field32' => array( 'location' => 'section8',
'cellId' => 'c12' ),
'edit_field_label3' => array( 'location' => 'section8',
'cellId' => 'c17' ),
'edit_field_label4' => array( 'location' => 'section8',
'cellId' => 'c18' ),
'edit_field_label5' => array( 'location' => 'section8',
'cellId' => 'c19' ),
'integrated_edit_field4' => array( 'location' => 'section8',
'cellId' => 'c24' ),
'integrated_edit_field1' => array( 'location' => 'section8',
'cellId' => 'c25' ),
'integrated_edit_field13' => array( 'location' => 'section8',
'cellId' => 'c26' ),
'details_preview1' => array( 'location' => 'section9',
'cellId' => 'c1' ) ),
'itemVisiblity' => array( 'menu' => 3,
'loginform_login' => 3,
'username_button' => 3 ) ),
'itemsByType' => array( 'edit_header' => array( 'edit_header' ),
'hamburger' => array( 'hamburger' ),
'edit_reset' => array( 'edit_reset' ),
'edit_message' => array( 'edit_message' ),
'edit_save' => array( 'edit_save' ),
'edit_back_list' => array( 'edit_back_list' ),
'edit_close' => array( 'edit_close' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'integrated_edit_field' => array( 'integrated_edit_field9',
'integrated_edit_field7',
'integrated_edit_field2',
'integrated_edit_field11',
'integrated_edit_field6',
'integrated_edit_field',
'integrated_edit_field12',
'integrated_edit_field8',
'integrated_edit_field3',
'integrated_edit_field18',
'integrated_edit_field22',
'integrated_edit_field17',
'integrated_edit_field19',
'integrated_edit_field20',
'integrated_edit_field21',
'integrated_edit_field23',
'integrated_edit_field24',
'integrated_edit_field25',
'edit_field' ),
'section' => array( 'section3',
'section2',
'section',
'section5',
'section4',
'section1',
'section7',
'section6',
'section8',
'section9' ),
'details_preview' => array( 'details_preview2',
'details_preview1',
'details_preview3' ),
'edit_view' => array( 'edit_view' ),
'edit_field' => array( 'integrated_edit_field32',
'integrated_edit_field1',
'integrated_edit_field4',
'integrated_edit_field5',
'integrated_edit_field10',
'integrated_edit_field13',
'integrated_edit_field14',
'integrated_edit_field15',
'integrated_edit_field16' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'logout_link' => array( 'logout_link' ),
'adminarea_link' => array( 'adminarea_link' ),
'update_records' => array( 'update_records' ),
'edit_field_label' => array( 'edit_field_label',
'edit_field_label1',
'edit_field_label2',
'edit_field_label3',
'edit_field_label4',
'edit_field_label5',
'edit_field_label6',
'edit_field_label7',
'edit_field_label8' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c8' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'section' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c5' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'section2',
'section9',
'section3',
'section7' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 3 ),
'section6' => array( 'cells' => array( 'c3' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field22' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c25' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c26' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c27' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c28' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 4,
'height' => 2 ),
'section5' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'details_preview3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section2' => array( 'cells' => array( 'c15' => array( 'cols' => array( 0,
1,
2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field17' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c20' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'edit_field' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c21' => array( 'cols' => array( 4 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 0,
1,
2 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c16' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c17' => array( 'cols' => array( 4 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field8' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c47' => array( 'cols' => array( 0,
1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c' => array( 'cols' => array( 2,
3,
4 ),
'rows' => array( 2,
3,
4,
5,
6,
7 ),
'tags' => array(  ),
'items' => array( 'section5',
'section4',
'section1',
'section8',
'section6' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c49' => array( 'cols' => array( 0,
1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c52' => array( 'cols' => array( 0,
1 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c53' => array( 'cols' => array( 0 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c11' => array( 'cols' => array( 1 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c56' => array( 'cols' => array( 0,
1 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c57' => array( 'cols' => array( 0,
1 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ) ),
'width' => 5,
'height' => 8 ),
'section4' => array( 'cells' => array( 'c3' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array( 'tvchannel_fieldblock' ),
'items' => array( 'edit_field_label8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field14' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c10' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'broadcast_fieldblock' ),
'items' => array( 'edit_field_label6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c9' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field15' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array( 'seller_fieldblock' ),
'items' => array( 'edit_field_label7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field16' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 3 ),
'section1' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section3' => array( 'cells' => array( 'c' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field19',
'integrated_edit_field20',
'integrated_edit_field21',
'integrated_edit_field23',
'integrated_edit_field24',
'integrated_edit_field25' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section7' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'details_preview2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section8' => array( 'cells' => array( 'c6' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array( 'callStart_fieldblock' ),
'items' => array( 'edit_field_label' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c24' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c17' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array( 'talkTime_fieldblock' ),
'items' => array( 'edit_field_label3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c10' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field5' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'callHangup_fieldblock' ),
'items' => array( 'edit_field_label1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c25' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c18' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array( 'typingTime_fieldblock' ),
'items' => array( 'edit_field_label4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c11' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field10' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array( 'callEnd_fieldblock' ),
'items' => array( 'edit_field_label2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c26' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field13' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c19' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array( 'totalCallTime_fieldblock' ),
'items' => array( 'edit_field_label5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c12' => array( 'cols' => array( 3 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field32' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c9' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c27' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c20' => array( 'cols' => array( 2 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c13' => array( 'cols' => array( 3 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 4,
'height' => 4 ),
'section9' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'details_preview1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ) ) ),
'loginForm' => array( 'loginForm' => 1 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array( 'update_records' => array( 'tag' => 'UPDATE_N_RECORDS',
'type' => 2 ) ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'edit',
'breadcrumb' => false,
'nextPrev' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'edit' => array( 'updateSelected' => true ) );
			$pageArray = array( 'id' => 'edit',
'type' => 'edit',
'layoutId' => 'topbar',
'disabled' => 0,
'default' => 1,
'forms' => array( 'supertop' => array( 'modelId' => 'topbar-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ),
array( 'cell' => 'c3' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'logo' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'menu' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c3' => array( 'model' => 'c3',
'items' => array( 'loginform_login',
'username_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'edit-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'edit-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_message' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'edit-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_save',
'update_records',
'edit_back_list',
'edit_close' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'hamburger' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c8',
'colspan' => 1 ) ) ),
array( 'cells' => array( array( 'cell' => 'c4',
'colspan' => 1 ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c5',
'colspan' => 1 ) ) ) ),
'cells' => array( 'c4' => array( 'model' => 'c3',
'items' => array(  ),
'width' => '80%',
'persistent' => true ),
'c5' => array( 'model' => 'c3',
'items' => array( 'section2',
'section9',
'section3',
'section7' ) ),
'c8' => array( 'model' => 'c3',
'items' => array( 'section' ),
'background' => '#ffe6ad' ) ),
'deferredItems' => array(  ),
'columnCount' => 3,
'inlineLabels' => true,
'separateLabels' => false ),
'section6' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c3' ),
array( 'cell' => 'c' ),
array( 'cell' => 'c4' ),
array( 'cell' => 'c5' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c25' ),
array( 'cell' => 'c26' ),
array( 'cell' => 'c27' ),
array( 'cell' => 'c28' ) ) ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field22' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c3',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c4' => array( 'model' => 'c3',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c5' => array( 'model' => 'c3',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c25' => array( 'model' => 'c3',
'items' => array(  ) ),
'c26' => array( 'model' => 'c3',
'items' => array(  ) ),
'c27' => array( 'model' => 'c3',
'items' => array(  ) ),
'c28' => array( 'model' => 'c3',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'columnCount' => 4,
'inlineLabels' => false,
'separateLabels' => false ),
'section5' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'details_preview3' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section2' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c15',
'colspan' => 3 ),
array( 'cell' => 'c20' ),
array( 'cell' => 'c21' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c7',
'colspan' => 3 ),
array( 'cell' => 'c16' ),
array( 'cell' => 'c17' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c47',
'colspan' => 2 ),
array( 'cell' => 'c',
'colspan' => 3,
'rowspan' => 6 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c49',
'colspan' => 2 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c52',
'colspan' => 2 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c53' ),
array( 'cell' => 'c11' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c56',
'colspan' => 2 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c57',
'colspan' => 2 ) ) ) ),
'cells' => array( 'c52' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field9' ),
'width' => '18%',
'persistent' => true,
'orientation' => 'horizontal' ),
'c47' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field7' ),
'width' => '18%',
'persistent' => true,
'orientation' => 'horizontal' ),
'c49' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field2' ),
'width' => '18%',
'persistent' => true,
'orientation' => 'horizontal' ),
'c53' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field11' ),
'width' => '18%',
'persistent' => true ),
'c56' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field6' ),
'width' => '18%',
'persistent' => true ),
'c7' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field' ),
'orientation' => 'vertical',
'align' => 'left' ),
'c11' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field12' ),
'width' => '20%',
'persistent' => true,
'align' => 'center' ),
'c' => array( 'model' => 'c1',
'items' => array( 'section5',
'section4',
'section1',
'section8',
'section6' ),
'padding' => array( 'left' => '5px' ),
'background' => '#fdffe7',
'width' => '25%' ),
'c57' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field18' ),
'width' => '18%',
'persistent' => true ),
'c16' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field3' ),
'orientation' => 'horizontal' ),
'c17' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field8' ),
'orientation' => 'horizontal' ),
'c15' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field17' ),
'orientation' => 'vertical',
'align' => 'left' ),
'c20' => array( 'model' => 'c1',
'items' => array( 'edit_field' ) ),
'c21' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section4' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c3' ),
array( 'cell' => 'c2' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c10' ),
array( 'cell' => 'c9' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c7' ),
array( 'cell' => 'c8' ) ) ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array( 'edit_field_label8' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'width' => '30%',
'background' => '#effffe' ),
'c2' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field14' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'orientation' => 'vertical',
'background' => '#effffe' ),
'c7' => array( 'model' => 'c3',
'items' => array( 'edit_field_label7' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'width' => '30%',
'background' => '#effffe' ),
'c8' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field16' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'orientation' => 'vertical',
'background' => '#effffe' ),
'c9' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field15' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'orientation' => 'vertical',
'background' => '#effffe' ),
'c10' => array( 'model' => 'c3',
'items' => array( 'edit_field_label6' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'width' => '30%',
'background' => '#effffe' ) ),
'deferredItems' => array(  ),
'columnCount' => 2,
'inlineLabels' => false,
'separateLabels' => false ),
'section1' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'background' => '#effffe' ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'background' => '#effffe' ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section3' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c',
'colspan' => 1 ) ),
'section' => '' ) ),
'cells' => array( 'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field19',
'integrated_edit_field20',
'integrated_edit_field21',
'integrated_edit_field23',
'integrated_edit_field24',
'integrated_edit_field25' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'width' => '25%' ) ),
'deferredItems' => array(  ),
'columnCount' => 2,
'inlineLabels' => false,
'separateLabels' => false ),
'section7' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'details_preview2' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section8' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c6',
'colspan' => 1 ),
array( 'cell' => 'c24' ),
array( 'cell' => 'c17' ),
array( 'cell' => 'c10' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c8' ),
array( 'cell' => 'c25' ),
array( 'cell' => 'c18' ),
array( 'cell' => 'c11' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c7' ),
array( 'cell' => 'c26' ),
array( 'cell' => 'c19' ),
array( 'cell' => 'c12' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c9' ),
array( 'cell' => 'c27' ),
array( 'cell' => 'c20' ),
array( 'cell' => 'c13' ) ) ) ),
'cells' => array( 'c6' => array( 'model' => 'c2',
'items' => array( 'edit_field_label' ),
'align' => 'right' ),
'c7' => array( 'model' => 'c2',
'items' => array( 'edit_field_label2' ),
'align' => 'right' ),
'c8' => array( 'model' => 'c2',
'items' => array( 'edit_field_label1' ),
'align' => 'right' ),
'c9' => array( 'model' => 'c3',
'items' => array(  ),
'align' => 'center' ),
'c10' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field5' ) ),
'c11' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field10' ) ),
'c12' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field32' ) ),
'c13' => array( 'model' => 'c3',
'items' => array(  ) ),
'c17' => array( 'model' => 'c2',
'items' => array( 'edit_field_label3' ),
'align' => 'right' ),
'c18' => array( 'model' => 'c2',
'items' => array( 'edit_field_label4' ),
'align' => 'right' ),
'c19' => array( 'model' => 'c3',
'items' => array( 'edit_field_label5' ),
'align' => 'right' ),
'c20' => array( 'model' => 'c3',
'items' => array(  ) ),
'c24' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field4' ) ),
'c25' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field1' ) ),
'c26' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field13' ) ),
'c27' => array( 'model' => 'c3',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'columnCount' => 4,
'inlineLabels' => false,
'separateLabels' => false ),
'section9' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'details_preview1' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'edit_header' => array( 'type' => 'edit_header' ),
'hamburger' => array( 'type' => 'hamburger',
'items' => array( 'edit_reset',
'edit_view' ) ),
'edit_reset' => array( 'type' => 'edit_reset' ),
'edit_message' => array( 'type' => 'edit_message' ),
'edit_save' => array( 'type' => 'edit_save' ),
'edit_back_list' => array( 'type' => 'edit_back_list' ),
'edit_close' => array( 'type' => 'edit_close' ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu' ),
'integrated_edit_field9' => array( 'field' => 'remarks',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'remarks',
'table' => 'dbo.Calls',
'type' => 3 ),
'nowrap' => false,
'updateOnEdit' => true ),
'section3' => array( 'type' => 'section',
'title' => array( 'text' => 'Παραγγελία Προϊόντων',
'type' => 0 ),
'location' => 'section6',
'initiallyClosed' => true ),
'section2' => array( 'type' => 'section',
'title' => array( 'text' => 'Αιτήσεις Volton',
'type' => 0 ),
'location' => 'section5',
'initiallyClosed' => true ),
'section' => array( 'type' => 'section',
'title' => array( 'text' => 'Στοιχεία Κλήσης',
'type' => 0 ),
'location' => 'section2',
'mobileDisplay' => '' ),
'integrated_edit_field7' => array( 'field' => 'callStatusId',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field2' => array( 'field' => 'callDenialReasonID',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field11' => array( 'field' => 'redialDate',
'type' => 'integrated_edit_field',
'orientation' => 0,
'nowrap' => true,
'updateOnEdit' => true ),
'integrated_edit_field6' => array( 'field' => 'redialComments',
'type' => 'integrated_edit_field',
'orientation' => 0,
'nowrap' => false,
'joined' => true,
'separated' => false,
'width' => '100%',
'updateOnEdit' => true ),
'integrated_edit_field' => array( 'field' => 'dialerPhone',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'dialerPhone',
'table' => 'dbo.Calls',
'type' => 3 ),
'nowrap' => true,
'updateOnEdit' => true ),
'integrated_edit_field12' => array( 'field' => 'redialIsPrivate',
'type' => 'integrated_edit_field',
'orientation' => 0,
'nowrap' => true,
'updateOnEdit' => true ),
'section5' => array( 'type' => 'section',
'title' => array( 'text' => 'Αγορές Πελάτη',
'type' => 0 ),
'location' => 'section1',
'initiallyClosed' => true ),
'section4' => array( 'type' => 'section',
'title' => array( 'text' => 'Εικόνα Πελάτη',
'type' => 0 ),
'location' => 'section',
'initiallyClosed' => true ),
'section1' => array( 'type' => 'section',
'title' => array( 'text' => 'Πληροφορίες Κλήσης',
'type' => 0 ),
'location' => 'section4',
'initiallyClosed' => true ),
'details_preview2' => array( 'type' => 'details_preview',
'table' => 'dbo.internalComments',
'items' => array(  ),
'popup' => false,
'pageId' => 'list' ),
'section7' => array( 'type' => 'section',
'title' => array( 'text' => 'Εσωτερική Επικοινωνία',
'type' => 0 ),
'location' => 'section7',
'initiallyClosed' => true ),
'edit_view' => array( 'type' => 'edit_view' ),
'integrated_edit_field8' => array( 'field' => 'callSubClassificationID',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'callSubClassificationID',
'table' => 'dbo.Calls',
'type' => 3 ),
'updateOnEdit' => true ),
'integrated_edit_field3' => array( 'field' => 'callClassificationID',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'callClassificationID',
'table' => 'dbo.Calls',
'type' => 3 ),
'updateOnEdit' => true ),
'integrated_edit_field18' => array( 'field' => 'callComments',
'type' => 'integrated_edit_field',
'orientation' => 0,
'nowrap' => false,
'updateOnEdit' => true ),
'section6' => array( 'type' => 'section',
'title' => array( 'text' => 'Dialer Data',
'type' => 0 ),
'location' => 'section3',
'initiallyClosed' => true ),
'integrated_edit_field32' => array( 'field' => 'totalCallTime',
'type' => 'edit_field',
'orientation' => 0,
'bold' => true,
'updateOnEdit' => true,
'joined' => false,
'separated' => true ),
'section8' => array( 'type' => 'section',
'title' => array( 'text' => 'Χρόνοι',
'type' => 0 ),
'location' => 'section8',
'initiallyClosed' => true ),
'integrated_edit_field22' => array( 'field' => 'contactId',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'logout_link',
'adminarea_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => true ),
'logout_link' => array( 'type' => 'logout_link' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'integrated_edit_field17' => array( 'field' => 'dialerAgent',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'update_records' => array( 'type' => 'update_records' ),
'details_preview1' => array( 'type' => 'details_preview',
'table' => 'dbo.novaApplications',
'items' => array(  ),
'popup' => false,
'pageId' => 'novaInlineAddList' ),
'details_preview3' => array( 'type' => 'details_preview',
'table' => 'dbo.voltonApplications',
'items' => array(  ),
'popup' => false,
'pageId' => 'voltonInDetailAddList' ),
'integrated_edit_field1' => array( 'field' => 'callHangup',
'type' => 'edit_field',
'orientation' => 1,
'joined' => false,
'separated' => true,
'updateOnEdit' => false ),
'integrated_edit_field4' => array( 'field' => 'callStart',
'type' => 'edit_field',
'orientation' => 1,
'joined' => false,
'separated' => true,
'updateOnEdit' => false ),
'integrated_edit_field5' => array( 'field' => 'talkTime',
'type' => 'edit_field',
'orientation' => 1,
'joined' => false,
'separated' => true,
'updateOnEdit' => false ),
'integrated_edit_field10' => array( 'field' => 'typingTime',
'type' => 'edit_field',
'orientation' => 1,
'joined' => false,
'separated' => true,
'updateOnEdit' => false ),
'integrated_edit_field13' => array( 'field' => 'callEnd',
'type' => 'edit_field',
'orientation' => 1,
'joined' => false,
'separated' => true,
'updateOnEdit' => false ),
'edit_field_label' => array( 'type' => 'edit_field_label',
'field' => 'callStart',
'separated' => true ),
'edit_field_label1' => array( 'type' => 'edit_field_label',
'field' => 'callHangup',
'separated' => true ),
'edit_field_label2' => array( 'type' => 'edit_field_label',
'field' => 'callEnd',
'separated' => true ),
'edit_field_label3' => array( 'type' => 'edit_field_label',
'field' => 'talkTime',
'separated' => true ),
'edit_field_label4' => array( 'type' => 'edit_field_label',
'field' => 'typingTime',
'separated' => true ),
'edit_field_label5' => array( 'type' => 'edit_field_label',
'field' => 'totalCallTime',
'separated' => true ),
'integrated_edit_field14' => array( 'field' => 'tvchannel',
'type' => 'edit_field',
'orientation' => 1,
'joined' => false,
'separated' => true ),
'integrated_edit_field15' => array( 'field' => 'broadcast',
'type' => 'edit_field',
'orientation' => 1,
'joined' => false,
'separated' => true ),
'integrated_edit_field16' => array( 'field' => 'seller',
'type' => 'edit_field',
'orientation' => 1,
'joined' => false,
'separated' => true ),
'edit_field_label6' => array( 'type' => 'edit_field_label',
'field' => 'broadcast',
'separated' => true ),
'edit_field_label7' => array( 'type' => 'edit_field_label',
'field' => 'seller',
'separated' => true ),
'edit_field_label8' => array( 'type' => 'edit_field_label',
'field' => 'tvchannel',
'separated' => true ),
'integrated_edit_field19' => array( 'field' => 'dialerCampaign',
'type' => 'integrated_edit_field',
'orientation' => 1,
'updateOnEdit' => false ),
'integrated_edit_field20' => array( 'field' => 'dialerList',
'type' => 'integrated_edit_field',
'orientation' => 1,
'updateOnEdit' => false ),
'integrated_edit_field21' => array( 'field' => 'dialerRecording',
'type' => 'integrated_edit_field',
'orientation' => 1,
'updateOnEdit' => false ),
'integrated_edit_field23' => array( 'field' => 'dialerLeadID',
'type' => 'integrated_edit_field',
'orientation' => 1,
'updateOnEdit' => false ),
'integrated_edit_field24' => array( 'field' => 'dialerCallEpoch',
'type' => 'integrated_edit_field',
'orientation' => 1,
'updateOnEdit' => false ),
'integrated_edit_field25' => array( 'field' => 'pauseAfterCall',
'type' => 'integrated_edit_field',
'orientation' => 1,
'updateOnEdit' => false ),
'edit_field' => array( 'field' => 'callStart',
'type' => 'integrated_edit_field',
'orientation' => 0,
'joined' => true,
'separated' => false,
'updateOnEdit' => false ),
'section9' => array( 'type' => 'section',
'title' => array( 'text' => 'Αιτήσεις Nova',
'type' => 0 ),
'location' => 'section9',
'initiallyClosed' => true ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>