<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'broadcast',
'tvchannel',
'seller',
'callStatusId',
'remarks',
'redialDate',
'redialComments',
'redialIsPrivate',
'redialDone',
'contactMethod',
'courier',
'courierDeliveryDate',
'courierTimeFrom',
'courierTimeTo',
'contactId',
'dialerRecording',
'dialerCampaign',
'dialerList',
'dialerLeadID',
'dialerAgent',
'callDenialReasonID',
'callClassificationID',
'callSubClassificationID',
'dialerPhone',
'dialerCallEpoch',
'callStart',
'callHangup',
'callEnd',
'talkTime',
'typingTime',
'totalCallTime',
'productFamilyId',
'orderShipCompany',
'orderInvoiceRequired',
'internalCommunication',
'deliveryComments',
'callComments',
'callGdprAcceptance',
'callGdprRecordingAcceptance',
'orderPaymentMethod',
'contactName',
'contactZipCode',
'contactCity',
'ContactArea',
'contactGender',
'callDate',
'callTime',
'contactAge',
'crmUser',
'pauseAfterCall' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'broadcast' => array( 'simple_grid_field5',
'simple_grid_field50' ),
'tvchannel' => array( 'simple_grid_field6',
'simple_grid_field51' ),
'seller' => array( 'simple_grid_field7',
'simple_grid_field52' ),
'callStatusId' => array( 'simple_grid_field8',
'simple_grid_field53' ),
'remarks' => array( 'simple_grid_field10',
'simple_grid_field54' ),
'redialDate' => array( 'simple_grid_field12',
'simple_grid_field55' ),
'redialComments' => array( 'simple_grid_field13',
'simple_grid_field56' ),
'redialIsPrivate' => array( 'simple_grid_field14',
'simple_grid_field57' ),
'redialDone' => array( 'simple_grid_field15',
'simple_grid_field58' ),
'contactMethod' => array( 'simple_grid_field16',
'simple_grid_field59' ),
'courier' => array( 'simple_grid_field17',
'simple_grid_field60' ),
'courierDeliveryDate' => array( 'simple_grid_field20',
'simple_grid_field61' ),
'courierTimeFrom' => array( 'simple_grid_field21',
'simple_grid_field62' ),
'courierTimeTo' => array( 'simple_grid_field22',
'simple_grid_field63' ),
'contactId' => array( 'simple_grid_field23',
'simple_grid_field64' ),
'dialerRecording' => array( 'simple_grid_field25',
'simple_grid_field65' ),
'dialerCampaign' => array( 'simple_grid_field29',
'simple_grid_field66' ),
'dialerList' => array( 'simple_grid_field31',
'simple_grid_field67' ),
'dialerLeadID' => array( 'simple_grid_field32',
'simple_grid_field68' ),
'dialerAgent' => array( 'simple_grid_field33',
'simple_grid_field69' ),
'callDenialReasonID' => array( 'simple_grid_field9',
'simple_grid_field70' ),
'callClassificationID' => array( 'simple_grid_field30',
'simple_grid_field71' ),
'callSubClassificationID' => array( 'simple_grid_field34',
'simple_grid_field72' ),
'dialerPhone' => array( 'simple_grid_field1',
'simple_grid_field73' ),
'dialerCallEpoch' => array( 'simple_grid_field3',
'simple_grid_field74' ),
'callStart' => array( 'simple_grid_field2',
'simple_grid_field75' ),
'callHangup' => array( 'simple_grid_field4',
'simple_grid_field76' ),
'callEnd' => array( 'simple_grid_field24',
'simple_grid_field77' ),
'talkTime' => array( 'simple_grid_field26',
'simple_grid_field78' ),
'typingTime' => array( 'simple_grid_field27',
'simple_grid_field79' ),
'totalCallTime' => array( 'simple_grid_field28',
'simple_grid_field80' ),
'productFamilyId' => array( 'simple_grid_field38',
'simple_grid_field81' ),
'orderShipCompany' => array( 'simple_grid_field39',
'simple_grid_field82' ),
'orderInvoiceRequired' => array( 'simple_grid_field40',
'simple_grid_field83' ),
'internalCommunication' => array( 'simple_grid_field41',
'simple_grid_field84' ),
'deliveryComments' => array( 'simple_grid_field11',
'simple_grid_field85' ),
'callComments' => array( 'simple_grid_field19',
'simple_grid_field86' ),
'callGdprAcceptance' => array( 'simple_grid_field42',
'simple_grid_field87' ),
'callGdprRecordingAcceptance' => array( 'simple_grid_field43',
'simple_grid_field88' ),
'orderPaymentMethod' => array( 'simple_grid_field',
'simple_grid_field89' ),
'contactName' => array( 'simple_grid_field35',
'simple_grid_field90' ),
'contactZipCode' => array( 'simple_grid_field36',
'simple_grid_field91' ),
'contactCity' => array( 'simple_grid_field37',
'simple_grid_field92' ),
'ContactArea' => array( 'simple_grid_field44',
'simple_grid_field93' ),
'contactGender' => array( 'simple_grid_field45',
'simple_grid_field94' ),
'callDate' => array( 'simple_grid_field18',
'simple_grid_field95' ),
'callTime' => array( 'simple_grid_field46',
'simple_grid_field96' ),
'contactAge' => array( 'simple_grid_field47',
'simple_grid_field97' ),
'crmUser' => array( 'simple_grid_field48',
'simple_grid_field98' ),
'pauseAfterCall' => array( 'simple_grid_field49',
'simple_grid_field99' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'top' => array( 'masterprint_header' ),
'above-grid' => array( 'inline_add' ),
'below-grid' => array(  ),
'grid' => array( 'simple_grid_field50',
'simple_grid_field5',
'simple_grid_field51',
'simple_grid_field6',
'simple_grid_field52',
'simple_grid_field7',
'simple_grid_field53',
'simple_grid_field8',
'simple_grid_field54',
'simple_grid_field10',
'simple_grid_field55',
'simple_grid_field12',
'simple_grid_field56',
'simple_grid_field13',
'simple_grid_field57',
'simple_grid_field14',
'simple_grid_field58',
'simple_grid_field15',
'simple_grid_field59',
'simple_grid_field16',
'simple_grid_field60',
'simple_grid_field17',
'simple_grid_field61',
'simple_grid_field20',
'simple_grid_field62',
'simple_grid_field21',
'simple_grid_field63',
'simple_grid_field22',
'simple_grid_field64',
'simple_grid_field23',
'simple_grid_field65',
'simple_grid_field25',
'simple_grid_field66',
'simple_grid_field29',
'simple_grid_field67',
'simple_grid_field31',
'simple_grid_field68',
'simple_grid_field32',
'simple_grid_field69',
'simple_grid_field33',
'simple_grid_field70',
'simple_grid_field9',
'simple_grid_field71',
'simple_grid_field30',
'simple_grid_field72',
'simple_grid_field34',
'simple_grid_field73',
'simple_grid_field1',
'simple_grid_field74',
'simple_grid_field3',
'simple_grid_field75',
'simple_grid_field2',
'simple_grid_field76',
'simple_grid_field4',
'simple_grid_field77',
'simple_grid_field24',
'simple_grid_field78',
'simple_grid_field26',
'simple_grid_field79',
'simple_grid_field27',
'simple_grid_field80',
'simple_grid_field28',
'simple_grid_field81',
'simple_grid_field38',
'simple_grid_field82',
'simple_grid_field39',
'simple_grid_field83',
'simple_grid_field40',
'simple_grid_field84',
'simple_grid_field41',
'simple_grid_field85',
'simple_grid_field11',
'simple_grid_field86',
'simple_grid_field19',
'simple_grid_field87',
'simple_grid_field42',
'simple_grid_field88',
'simple_grid_field43',
'simple_grid_field89',
'simple_grid_field',
'simple_grid_field90',
'simple_grid_field35',
'simple_grid_field91',
'simple_grid_field36',
'simple_grid_field92',
'simple_grid_field37',
'simple_grid_field93',
'simple_grid_field44',
'simple_grid_field94',
'simple_grid_field45',
'simple_grid_field95',
'simple_grid_field18',
'simple_grid_field96',
'simple_grid_field46',
'simple_grid_field97',
'simple_grid_field47',
'simple_grid_field98',
'simple_grid_field48',
'simple_grid_field99',
'simple_grid_field49',
'grid_inline_cancel' ) ),
'formXtTags' => array( 'above-grid' => array( 'inlineadd_link' ),
'below-grid' => array(  ) ),
'itemForms' => array( 'masterprint_header' => 'top',
'inline_add' => 'above-grid',
'simple_grid_field50' => 'grid',
'simple_grid_field5' => 'grid',
'simple_grid_field51' => 'grid',
'simple_grid_field6' => 'grid',
'simple_grid_field52' => 'grid',
'simple_grid_field7' => 'grid',
'simple_grid_field53' => 'grid',
'simple_grid_field8' => 'grid',
'simple_grid_field54' => 'grid',
'simple_grid_field10' => 'grid',
'simple_grid_field55' => 'grid',
'simple_grid_field12' => 'grid',
'simple_grid_field56' => 'grid',
'simple_grid_field13' => 'grid',
'simple_grid_field57' => 'grid',
'simple_grid_field14' => 'grid',
'simple_grid_field58' => 'grid',
'simple_grid_field15' => 'grid',
'simple_grid_field59' => 'grid',
'simple_grid_field16' => 'grid',
'simple_grid_field60' => 'grid',
'simple_grid_field17' => 'grid',
'simple_grid_field61' => 'grid',
'simple_grid_field20' => 'grid',
'simple_grid_field62' => 'grid',
'simple_grid_field21' => 'grid',
'simple_grid_field63' => 'grid',
'simple_grid_field22' => 'grid',
'simple_grid_field64' => 'grid',
'simple_grid_field23' => 'grid',
'simple_grid_field65' => 'grid',
'simple_grid_field25' => 'grid',
'simple_grid_field66' => 'grid',
'simple_grid_field29' => 'grid',
'simple_grid_field67' => 'grid',
'simple_grid_field31' => 'grid',
'simple_grid_field68' => 'grid',
'simple_grid_field32' => 'grid',
'simple_grid_field69' => 'grid',
'simple_grid_field33' => 'grid',
'simple_grid_field70' => 'grid',
'simple_grid_field9' => 'grid',
'simple_grid_field71' => 'grid',
'simple_grid_field30' => 'grid',
'simple_grid_field72' => 'grid',
'simple_grid_field34' => 'grid',
'simple_grid_field73' => 'grid',
'simple_grid_field1' => 'grid',
'simple_grid_field74' => 'grid',
'simple_grid_field3' => 'grid',
'simple_grid_field75' => 'grid',
'simple_grid_field2' => 'grid',
'simple_grid_field76' => 'grid',
'simple_grid_field4' => 'grid',
'simple_grid_field77' => 'grid',
'simple_grid_field24' => 'grid',
'simple_grid_field78' => 'grid',
'simple_grid_field26' => 'grid',
'simple_grid_field79' => 'grid',
'simple_grid_field27' => 'grid',
'simple_grid_field80' => 'grid',
'simple_grid_field28' => 'grid',
'simple_grid_field81' => 'grid',
'simple_grid_field38' => 'grid',
'simple_grid_field82' => 'grid',
'simple_grid_field39' => 'grid',
'simple_grid_field83' => 'grid',
'simple_grid_field40' => 'grid',
'simple_grid_field84' => 'grid',
'simple_grid_field41' => 'grid',
'simple_grid_field85' => 'grid',
'simple_grid_field11' => 'grid',
'simple_grid_field86' => 'grid',
'simple_grid_field19' => 'grid',
'simple_grid_field87' => 'grid',
'simple_grid_field42' => 'grid',
'simple_grid_field88' => 'grid',
'simple_grid_field43' => 'grid',
'simple_grid_field89' => 'grid',
'simple_grid_field' => 'grid',
'simple_grid_field90' => 'grid',
'simple_grid_field35' => 'grid',
'simple_grid_field91' => 'grid',
'simple_grid_field36' => 'grid',
'simple_grid_field92' => 'grid',
'simple_grid_field37' => 'grid',
'simple_grid_field93' => 'grid',
'simple_grid_field44' => 'grid',
'simple_grid_field94' => 'grid',
'simple_grid_field45' => 'grid',
'simple_grid_field95' => 'grid',
'simple_grid_field18' => 'grid',
'simple_grid_field96' => 'grid',
'simple_grid_field46' => 'grid',
'simple_grid_field97' => 'grid',
'simple_grid_field47' => 'grid',
'simple_grid_field98' => 'grid',
'simple_grid_field48' => 'grid',
'simple_grid_field99' => 'grid',
'simple_grid_field49' => 'grid',
'grid_inline_cancel' => 'grid' ),
'itemLocations' => array( 'simple_grid_field50' => array( 'location' => 'grid',
'cellId' => 'headcell_field' ),
'simple_grid_field5' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'simple_grid_field51' => array( 'location' => 'grid',
'cellId' => 'headcell_field1' ),
'simple_grid_field6' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'simple_grid_field52' => array( 'location' => 'grid',
'cellId' => 'headcell_field2' ),
'simple_grid_field7' => array( 'location' => 'grid',
'cellId' => 'cell_field2' ),
'simple_grid_field53' => array( 'location' => 'grid',
'cellId' => 'headcell_field3' ),
'simple_grid_field8' => array( 'location' => 'grid',
'cellId' => 'cell_field3' ),
'simple_grid_field54' => array( 'location' => 'grid',
'cellId' => 'headcell_field4' ),
'simple_grid_field10' => array( 'location' => 'grid',
'cellId' => 'cell_field4' ),
'simple_grid_field55' => array( 'location' => 'grid',
'cellId' => 'headcell_field5' ),
'simple_grid_field12' => array( 'location' => 'grid',
'cellId' => 'cell_field5' ),
'simple_grid_field56' => array( 'location' => 'grid',
'cellId' => 'headcell_field6' ),
'simple_grid_field13' => array( 'location' => 'grid',
'cellId' => 'cell_field6' ),
'simple_grid_field57' => array( 'location' => 'grid',
'cellId' => 'headcell_field7' ),
'simple_grid_field14' => array( 'location' => 'grid',
'cellId' => 'cell_field7' ),
'simple_grid_field58' => array( 'location' => 'grid',
'cellId' => 'headcell_field8' ),
'simple_grid_field15' => array( 'location' => 'grid',
'cellId' => 'cell_field8' ),
'simple_grid_field59' => array( 'location' => 'grid',
'cellId' => 'headcell_field9' ),
'simple_grid_field16' => array( 'location' => 'grid',
'cellId' => 'cell_field9' ),
'simple_grid_field60' => array( 'location' => 'grid',
'cellId' => 'headcell_field10' ),
'simple_grid_field17' => array( 'location' => 'grid',
'cellId' => 'cell_field10' ),
'simple_grid_field61' => array( 'location' => 'grid',
'cellId' => 'headcell_field11' ),
'simple_grid_field20' => array( 'location' => 'grid',
'cellId' => 'cell_field11' ),
'simple_grid_field62' => array( 'location' => 'grid',
'cellId' => 'headcell_field12' ),
'simple_grid_field21' => array( 'location' => 'grid',
'cellId' => 'cell_field12' ),
'simple_grid_field63' => array( 'location' => 'grid',
'cellId' => 'headcell_field13' ),
'simple_grid_field22' => array( 'location' => 'grid',
'cellId' => 'cell_field13' ),
'simple_grid_field64' => array( 'location' => 'grid',
'cellId' => 'headcell_field14' ),
'simple_grid_field23' => array( 'location' => 'grid',
'cellId' => 'cell_field14' ),
'simple_grid_field65' => array( 'location' => 'grid',
'cellId' => 'headcell_field15' ),
'simple_grid_field25' => array( 'location' => 'grid',
'cellId' => 'cell_field15' ),
'simple_grid_field66' => array( 'location' => 'grid',
'cellId' => 'headcell_field16' ),
'simple_grid_field29' => array( 'location' => 'grid',
'cellId' => 'cell_field16' ),
'simple_grid_field67' => array( 'location' => 'grid',
'cellId' => 'headcell_field17' ),
'simple_grid_field31' => array( 'location' => 'grid',
'cellId' => 'cell_field17' ),
'simple_grid_field68' => array( 'location' => 'grid',
'cellId' => 'headcell_field18' ),
'simple_grid_field32' => array( 'location' => 'grid',
'cellId' => 'cell_field18' ),
'simple_grid_field69' => array( 'location' => 'grid',
'cellId' => 'headcell_field19' ),
'simple_grid_field33' => array( 'location' => 'grid',
'cellId' => 'cell_field19' ),
'simple_grid_field70' => array( 'location' => 'grid',
'cellId' => 'headcell_field20' ),
'simple_grid_field9' => array( 'location' => 'grid',
'cellId' => 'cell_field20' ),
'simple_grid_field71' => array( 'location' => 'grid',
'cellId' => 'headcell_field21' ),
'simple_grid_field30' => array( 'location' => 'grid',
'cellId' => 'cell_field21' ),
'simple_grid_field72' => array( 'location' => 'grid',
'cellId' => 'headcell_field22' ),
'simple_grid_field34' => array( 'location' => 'grid',
'cellId' => 'cell_field22' ),
'simple_grid_field73' => array( 'location' => 'grid',
'cellId' => 'headcell_field23' ),
'simple_grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field23' ),
'simple_grid_field74' => array( 'location' => 'grid',
'cellId' => 'headcell_field24' ),
'simple_grid_field3' => array( 'location' => 'grid',
'cellId' => 'cell_field24' ),
'simple_grid_field75' => array( 'location' => 'grid',
'cellId' => 'headcell_field25' ),
'simple_grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field25' ),
'simple_grid_field76' => array( 'location' => 'grid',
'cellId' => 'headcell_field26' ),
'simple_grid_field4' => array( 'location' => 'grid',
'cellId' => 'cell_field26' ),
'simple_grid_field77' => array( 'location' => 'grid',
'cellId' => 'headcell_field27' ),
'simple_grid_field24' => array( 'location' => 'grid',
'cellId' => 'cell_field27' ),
'simple_grid_field78' => array( 'location' => 'grid',
'cellId' => 'headcell_field28' ),
'simple_grid_field26' => array( 'location' => 'grid',
'cellId' => 'cell_field28' ),
'simple_grid_field79' => array( 'location' => 'grid',
'cellId' => 'headcell_field29' ),
'simple_grid_field27' => array( 'location' => 'grid',
'cellId' => 'cell_field29' ),
'simple_grid_field80' => array( 'location' => 'grid',
'cellId' => 'headcell_field30' ),
'simple_grid_field28' => array( 'location' => 'grid',
'cellId' => 'cell_field30' ),
'simple_grid_field81' => array( 'location' => 'grid',
'cellId' => 'headcell_field31' ),
'simple_grid_field38' => array( 'location' => 'grid',
'cellId' => 'cell_field31' ),
'simple_grid_field82' => array( 'location' => 'grid',
'cellId' => 'headcell_field32' ),
'simple_grid_field39' => array( 'location' => 'grid',
'cellId' => 'cell_field32' ),
'simple_grid_field83' => array( 'location' => 'grid',
'cellId' => 'headcell_field33' ),
'simple_grid_field40' => array( 'location' => 'grid',
'cellId' => 'cell_field33' ),
'simple_grid_field84' => array( 'location' => 'grid',
'cellId' => 'headcell_field34' ),
'simple_grid_field41' => array( 'location' => 'grid',
'cellId' => 'cell_field34' ),
'simple_grid_field85' => array( 'location' => 'grid',
'cellId' => 'headcell_field35' ),
'simple_grid_field11' => array( 'location' => 'grid',
'cellId' => 'cell_field35' ),
'simple_grid_field86' => array( 'location' => 'grid',
'cellId' => 'headcell_field36' ),
'simple_grid_field19' => array( 'location' => 'grid',
'cellId' => 'cell_field36' ),
'simple_grid_field87' => array( 'location' => 'grid',
'cellId' => 'headcell_field37' ),
'simple_grid_field42' => array( 'location' => 'grid',
'cellId' => 'cell_field37' ),
'simple_grid_field88' => array( 'location' => 'grid',
'cellId' => 'headcell_field38' ),
'simple_grid_field43' => array( 'location' => 'grid',
'cellId' => 'cell_field38' ),
'simple_grid_field89' => array( 'location' => 'grid',
'cellId' => 'headcell_field39' ),
'simple_grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field39' ),
'simple_grid_field90' => array( 'location' => 'grid',
'cellId' => 'headcell_field40' ),
'simple_grid_field35' => array( 'location' => 'grid',
'cellId' => 'cell_field40' ),
'simple_grid_field91' => array( 'location' => 'grid',
'cellId' => 'headcell_field41' ),
'simple_grid_field36' => array( 'location' => 'grid',
'cellId' => 'cell_field41' ),
'simple_grid_field92' => array( 'location' => 'grid',
'cellId' => 'headcell_field42' ),
'simple_grid_field37' => array( 'location' => 'grid',
'cellId' => 'cell_field42' ),
'simple_grid_field93' => array( 'location' => 'grid',
'cellId' => 'headcell_field43' ),
'simple_grid_field44' => array( 'location' => 'grid',
'cellId' => 'cell_field43' ),
'simple_grid_field94' => array( 'location' => 'grid',
'cellId' => 'headcell_field44' ),
'simple_grid_field45' => array( 'location' => 'grid',
'cellId' => 'cell_field44' ),
'simple_grid_field95' => array( 'location' => 'grid',
'cellId' => 'headcell_field45' ),
'simple_grid_field18' => array( 'location' => 'grid',
'cellId' => 'cell_field45' ),
'simple_grid_field96' => array( 'location' => 'grid',
'cellId' => 'headcell_field46' ),
'simple_grid_field46' => array( 'location' => 'grid',
'cellId' => 'cell_field46' ),
'simple_grid_field97' => array( 'location' => 'grid',
'cellId' => 'headcell_field47' ),
'simple_grid_field47' => array( 'location' => 'grid',
'cellId' => 'cell_field47' ),
'simple_grid_field98' => array( 'location' => 'grid',
'cellId' => 'headcell_field48' ),
'simple_grid_field48' => array( 'location' => 'grid',
'cellId' => 'cell_field48' ),
'simple_grid_field99' => array( 'location' => 'grid',
'cellId' => 'headcell_field49' ),
'simple_grid_field49' => array( 'location' => 'grid',
'cellId' => 'cell_field49' ),
'grid_inline_cancel' => array( 'location' => 'grid',
'cellId' => 'cell_icons' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'masterprint_header' => array( 'masterprint_header' ),
'grid_field' => array( 'simple_grid_field5',
'simple_grid_field6',
'simple_grid_field7',
'simple_grid_field8',
'simple_grid_field10',
'simple_grid_field12',
'simple_grid_field13',
'simple_grid_field14',
'simple_grid_field15',
'simple_grid_field16',
'simple_grid_field17',
'simple_grid_field20',
'simple_grid_field21',
'simple_grid_field22',
'simple_grid_field23',
'simple_grid_field25',
'simple_grid_field29',
'simple_grid_field31',
'simple_grid_field32',
'simple_grid_field33',
'simple_grid_field9',
'simple_grid_field30',
'simple_grid_field34',
'simple_grid_field1',
'simple_grid_field3',
'simple_grid_field2',
'simple_grid_field4',
'simple_grid_field24',
'simple_grid_field26',
'simple_grid_field27',
'simple_grid_field28',
'simple_grid_field38',
'simple_grid_field39',
'simple_grid_field40',
'simple_grid_field41',
'simple_grid_field11',
'simple_grid_field19',
'simple_grid_field42',
'simple_grid_field43',
'simple_grid_field',
'simple_grid_field35',
'simple_grid_field36',
'simple_grid_field37',
'simple_grid_field44',
'simple_grid_field45',
'simple_grid_field18',
'simple_grid_field46',
'simple_grid_field47',
'simple_grid_field48',
'simple_grid_field49' ),
'grid_field_label' => array( 'simple_grid_field50',
'simple_grid_field51',
'simple_grid_field52',
'simple_grid_field53',
'simple_grid_field54',
'simple_grid_field55',
'simple_grid_field56',
'simple_grid_field57',
'simple_grid_field58',
'simple_grid_field59',
'simple_grid_field60',
'simple_grid_field61',
'simple_grid_field62',
'simple_grid_field63',
'simple_grid_field64',
'simple_grid_field65',
'simple_grid_field66',
'simple_grid_field67',
'simple_grid_field68',
'simple_grid_field69',
'simple_grid_field70',
'simple_grid_field71',
'simple_grid_field72',
'simple_grid_field73',
'simple_grid_field74',
'simple_grid_field75',
'simple_grid_field76',
'simple_grid_field77',
'simple_grid_field78',
'simple_grid_field79',
'simple_grid_field80',
'simple_grid_field81',
'simple_grid_field82',
'simple_grid_field83',
'simple_grid_field84',
'simple_grid_field85',
'simple_grid_field86',
'simple_grid_field87',
'simple_grid_field88',
'simple_grid_field89',
'simple_grid_field90',
'simple_grid_field91',
'simple_grid_field92',
'simple_grid_field93',
'simple_grid_field94',
'simple_grid_field95',
'simple_grid_field96',
'simple_grid_field97',
'simple_grid_field98',
'simple_grid_field99' ),
'inline_add' => array( 'inline_add' ),
'grid_inline_cancel' => array( 'grid_inline_cancel' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'headcell_icons' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array( 'broadcast_fieldheadercolumn' ),
'items' => array( 'simple_grid_field50' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field1' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array( 'tvchannel_fieldheadercolumn' ),
'items' => array( 'simple_grid_field51' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field2' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array( 'seller_fieldheadercolumn' ),
'items' => array( 'simple_grid_field52' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field3' => array( 'cols' => array( 4 ),
'rows' => array( 0 ),
'tags' => array( 'callStatusId_fieldheadercolumn' ),
'items' => array( 'simple_grid_field53' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field4' => array( 'cols' => array( 5 ),
'rows' => array( 0 ),
'tags' => array( 'remarks_fieldheadercolumn' ),
'items' => array( 'simple_grid_field54' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field5' => array( 'cols' => array( 6 ),
'rows' => array( 0 ),
'tags' => array( 'redialDate_fieldheadercolumn' ),
'items' => array( 'simple_grid_field55' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field6' => array( 'cols' => array( 7 ),
'rows' => array( 0 ),
'tags' => array( 'redialComments_fieldheadercolumn' ),
'items' => array( 'simple_grid_field56' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field7' => array( 'cols' => array( 8 ),
'rows' => array( 0 ),
'tags' => array( 'redialIsPrivate_fieldheadercolumn' ),
'items' => array( 'simple_grid_field57' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field8' => array( 'cols' => array( 9 ),
'rows' => array( 0 ),
'tags' => array( 'redialDone_fieldheadercolumn' ),
'items' => array( 'simple_grid_field58' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field9' => array( 'cols' => array( 10 ),
'rows' => array( 0 ),
'tags' => array( 'contactMethod_fieldheadercolumn' ),
'items' => array( 'simple_grid_field59' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field10' => array( 'cols' => array( 11 ),
'rows' => array( 0 ),
'tags' => array( 'courier_fieldheadercolumn' ),
'items' => array( 'simple_grid_field60' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field11' => array( 'cols' => array( 12 ),
'rows' => array( 0 ),
'tags' => array( 'courierDeliveryDate_fieldheadercolumn' ),
'items' => array( 'simple_grid_field61' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field12' => array( 'cols' => array( 13 ),
'rows' => array( 0 ),
'tags' => array( 'courierTimeFrom_fieldheadercolumn' ),
'items' => array( 'simple_grid_field62' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field13' => array( 'cols' => array( 14 ),
'rows' => array( 0 ),
'tags' => array( 'courierTimeTo_fieldheadercolumn' ),
'items' => array( 'simple_grid_field63' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field14' => array( 'cols' => array( 15 ),
'rows' => array( 0 ),
'tags' => array( 'contactId_fieldheadercolumn' ),
'items' => array( 'simple_grid_field64' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field15' => array( 'cols' => array( 16 ),
'rows' => array( 0 ),
'tags' => array( 'dialerRecording_fieldheadercolumn' ),
'items' => array( 'simple_grid_field65' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field16' => array( 'cols' => array( 17 ),
'rows' => array( 0 ),
'tags' => array( 'dialerCampaign_fieldheadercolumn' ),
'items' => array( 'simple_grid_field66' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field17' => array( 'cols' => array( 18 ),
'rows' => array( 0 ),
'tags' => array( 'dialerList_fieldheadercolumn' ),
'items' => array( 'simple_grid_field67' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field18' => array( 'cols' => array( 19 ),
'rows' => array( 0 ),
'tags' => array( 'dialerLeadID_fieldheadercolumn' ),
'items' => array( 'simple_grid_field68' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field19' => array( 'cols' => array( 20 ),
'rows' => array( 0 ),
'tags' => array( 'dialerAgent_fieldheadercolumn' ),
'items' => array( 'simple_grid_field69' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field20' => array( 'cols' => array( 21 ),
'rows' => array( 0 ),
'tags' => array( 'callDenialReasonID_fieldheadercolumn' ),
'items' => array( 'simple_grid_field70' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field21' => array( 'cols' => array( 22 ),
'rows' => array( 0 ),
'tags' => array( 'callClassificationID_fieldheadercolumn' ),
'items' => array( 'simple_grid_field71' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field22' => array( 'cols' => array( 23 ),
'rows' => array( 0 ),
'tags' => array( 'callSubClassificationID_fieldheadercolumn' ),
'items' => array( 'simple_grid_field72' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field23' => array( 'cols' => array( 24 ),
'rows' => array( 0 ),
'tags' => array( 'dialerPhone_fieldheadercolumn' ),
'items' => array( 'simple_grid_field73' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field24' => array( 'cols' => array( 25 ),
'rows' => array( 0 ),
'tags' => array( 'dialerCallEpoch_fieldheadercolumn' ),
'items' => array( 'simple_grid_field74' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field25' => array( 'cols' => array( 26 ),
'rows' => array( 0 ),
'tags' => array( 'callStart_fieldheadercolumn' ),
'items' => array( 'simple_grid_field75' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field26' => array( 'cols' => array( 27 ),
'rows' => array( 0 ),
'tags' => array( 'callHangup_fieldheadercolumn' ),
'items' => array( 'simple_grid_field76' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field27' => array( 'cols' => array( 28 ),
'rows' => array( 0 ),
'tags' => array( 'callEnd_fieldheadercolumn' ),
'items' => array( 'simple_grid_field77' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field28' => array( 'cols' => array( 29 ),
'rows' => array( 0 ),
'tags' => array( 'talkTime_fieldheadercolumn' ),
'items' => array( 'simple_grid_field78' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field29' => array( 'cols' => array( 30 ),
'rows' => array( 0 ),
'tags' => array( 'typingTime_fieldheadercolumn' ),
'items' => array( 'simple_grid_field79' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field30' => array( 'cols' => array( 31 ),
'rows' => array( 0 ),
'tags' => array( 'totalCallTime_fieldheadercolumn' ),
'items' => array( 'simple_grid_field80' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field31' => array( 'cols' => array( 32 ),
'rows' => array( 0 ),
'tags' => array( 'productFamilyId_fieldheadercolumn' ),
'items' => array( 'simple_grid_field81' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field32' => array( 'cols' => array( 33 ),
'rows' => array( 0 ),
'tags' => array( 'orderShipCompany_fieldheadercolumn' ),
'items' => array( 'simple_grid_field82' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field33' => array( 'cols' => array( 34 ),
'rows' => array( 0 ),
'tags' => array( 'orderInvoiceRequired_fieldheadercolumn' ),
'items' => array( 'simple_grid_field83' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field34' => array( 'cols' => array( 35 ),
'rows' => array( 0 ),
'tags' => array( 'internalCommunication_fieldheadercolumn' ),
'items' => array( 'simple_grid_field84' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field35' => array( 'cols' => array( 36 ),
'rows' => array( 0 ),
'tags' => array( 'deliveryComments_fieldheadercolumn' ),
'items' => array( 'simple_grid_field85' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field36' => array( 'cols' => array( 37 ),
'rows' => array( 0 ),
'tags' => array( 'callComments_fieldheadercolumn' ),
'items' => array( 'simple_grid_field86' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field37' => array( 'cols' => array( 38 ),
'rows' => array( 0 ),
'tags' => array( 'callGdprAcceptance_fieldheadercolumn' ),
'items' => array( 'simple_grid_field87' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field38' => array( 'cols' => array( 39 ),
'rows' => array( 0 ),
'tags' => array( 'callGdprRecordingAcceptance_fieldheadercolumn' ),
'items' => array( 'simple_grid_field88' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field39' => array( 'cols' => array( 40 ),
'rows' => array( 0 ),
'tags' => array( 'orderPaymentMethod_fieldheadercolumn' ),
'items' => array( 'simple_grid_field89' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field40' => array( 'cols' => array( 41 ),
'rows' => array( 0 ),
'tags' => array( 'contactName_fieldheadercolumn' ),
'items' => array( 'simple_grid_field90' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field41' => array( 'cols' => array( 42 ),
'rows' => array( 0 ),
'tags' => array( 'contactZipCode_fieldheadercolumn' ),
'items' => array( 'simple_grid_field91' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field42' => array( 'cols' => array( 43 ),
'rows' => array( 0 ),
'tags' => array( 'contactCity_fieldheadercolumn' ),
'items' => array( 'simple_grid_field92' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field43' => array( 'cols' => array( 44 ),
'rows' => array( 0 ),
'tags' => array( 'ContactArea_fieldheadercolumn' ),
'items' => array( 'simple_grid_field93' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field44' => array( 'cols' => array( 45 ),
'rows' => array( 0 ),
'tags' => array( 'contactGender_fieldheadercolumn' ),
'items' => array( 'simple_grid_field94' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field45' => array( 'cols' => array( 46 ),
'rows' => array( 0 ),
'tags' => array( 'callDate_fieldheadercolumn' ),
'items' => array( 'simple_grid_field95' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field46' => array( 'cols' => array( 47 ),
'rows' => array( 0 ),
'tags' => array( 'callTime_fieldheadercolumn' ),
'items' => array( 'simple_grid_field96' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field47' => array( 'cols' => array( 48 ),
'rows' => array( 0 ),
'tags' => array( 'contactAge_fieldheadercolumn' ),
'items' => array( 'simple_grid_field97' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field48' => array( 'cols' => array( 49 ),
'rows' => array( 0 ),
'tags' => array( 'crmUser_fieldheadercolumn' ),
'items' => array( 'simple_grid_field98' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field49' => array( 'cols' => array( 50 ),
'rows' => array( 0 ),
'tags' => array( 'pauseAfterCall_fieldheadercolumn' ),
'items' => array( 'simple_grid_field99' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_icons' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'inline_cancel' ),
'items' => array( 'grid_inline_cancel' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array( 'broadcast_fieldcolumn' ),
'items' => array( 'simple_grid_field5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field1' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array( 'tvchannel_fieldcolumn' ),
'items' => array( 'simple_grid_field6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field2' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array( 'seller_fieldcolumn' ),
'items' => array( 'simple_grid_field7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field3' => array( 'cols' => array( 4 ),
'rows' => array( 1 ),
'tags' => array( 'callStatusId_fieldcolumn' ),
'items' => array( 'simple_grid_field8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field4' => array( 'cols' => array( 5 ),
'rows' => array( 1 ),
'tags' => array( 'remarks_fieldcolumn' ),
'items' => array( 'simple_grid_field10' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field5' => array( 'cols' => array( 6 ),
'rows' => array( 1 ),
'tags' => array( 'redialDate_fieldcolumn' ),
'items' => array( 'simple_grid_field12' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field6' => array( 'cols' => array( 7 ),
'rows' => array( 1 ),
'tags' => array( 'redialComments_fieldcolumn' ),
'items' => array( 'simple_grid_field13' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field7' => array( 'cols' => array( 8 ),
'rows' => array( 1 ),
'tags' => array( 'redialIsPrivate_fieldcolumn' ),
'items' => array( 'simple_grid_field14' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field8' => array( 'cols' => array( 9 ),
'rows' => array( 1 ),
'tags' => array( 'redialDone_fieldcolumn' ),
'items' => array( 'simple_grid_field15' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field9' => array( 'cols' => array( 10 ),
'rows' => array( 1 ),
'tags' => array( 'contactMethod_fieldcolumn' ),
'items' => array( 'simple_grid_field16' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field10' => array( 'cols' => array( 11 ),
'rows' => array( 1 ),
'tags' => array( 'courier_fieldcolumn' ),
'items' => array( 'simple_grid_field17' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field11' => array( 'cols' => array( 12 ),
'rows' => array( 1 ),
'tags' => array( 'courierDeliveryDate_fieldcolumn' ),
'items' => array( 'simple_grid_field20' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field12' => array( 'cols' => array( 13 ),
'rows' => array( 1 ),
'tags' => array( 'courierTimeFrom_fieldcolumn' ),
'items' => array( 'simple_grid_field21' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field13' => array( 'cols' => array( 14 ),
'rows' => array( 1 ),
'tags' => array( 'courierTimeTo_fieldcolumn' ),
'items' => array( 'simple_grid_field22' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field14' => array( 'cols' => array( 15 ),
'rows' => array( 1 ),
'tags' => array( 'contactId_fieldcolumn' ),
'items' => array( 'simple_grid_field23' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field15' => array( 'cols' => array( 16 ),
'rows' => array( 1 ),
'tags' => array( 'dialerRecording_fieldcolumn' ),
'items' => array( 'simple_grid_field25' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field16' => array( 'cols' => array( 17 ),
'rows' => array( 1 ),
'tags' => array( 'dialerCampaign_fieldcolumn' ),
'items' => array( 'simple_grid_field29' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field17' => array( 'cols' => array( 18 ),
'rows' => array( 1 ),
'tags' => array( 'dialerList_fieldcolumn' ),
'items' => array( 'simple_grid_field31' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field18' => array( 'cols' => array( 19 ),
'rows' => array( 1 ),
'tags' => array( 'dialerLeadID_fieldcolumn' ),
'items' => array( 'simple_grid_field32' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field19' => array( 'cols' => array( 20 ),
'rows' => array( 1 ),
'tags' => array( 'dialerAgent_fieldcolumn' ),
'items' => array( 'simple_grid_field33' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field20' => array( 'cols' => array( 21 ),
'rows' => array( 1 ),
'tags' => array( 'callDenialReasonID_fieldcolumn' ),
'items' => array( 'simple_grid_field9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field21' => array( 'cols' => array( 22 ),
'rows' => array( 1 ),
'tags' => array( 'callClassificationID_fieldcolumn' ),
'items' => array( 'simple_grid_field30' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field22' => array( 'cols' => array( 23 ),
'rows' => array( 1 ),
'tags' => array( 'callSubClassificationID_fieldcolumn' ),
'items' => array( 'simple_grid_field34' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field23' => array( 'cols' => array( 24 ),
'rows' => array( 1 ),
'tags' => array( 'dialerPhone_fieldcolumn' ),
'items' => array( 'simple_grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field24' => array( 'cols' => array( 25 ),
'rows' => array( 1 ),
'tags' => array( 'dialerCallEpoch_fieldcolumn' ),
'items' => array( 'simple_grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field25' => array( 'cols' => array( 26 ),
'rows' => array( 1 ),
'tags' => array( 'callStart_fieldcolumn' ),
'items' => array( 'simple_grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field26' => array( 'cols' => array( 27 ),
'rows' => array( 1 ),
'tags' => array( 'callHangup_fieldcolumn' ),
'items' => array( 'simple_grid_field4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field27' => array( 'cols' => array( 28 ),
'rows' => array( 1 ),
'tags' => array( 'callEnd_fieldcolumn' ),
'items' => array( 'simple_grid_field24' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field28' => array( 'cols' => array( 29 ),
'rows' => array( 1 ),
'tags' => array( 'talkTime_fieldcolumn' ),
'items' => array( 'simple_grid_field26' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field29' => array( 'cols' => array( 30 ),
'rows' => array( 1 ),
'tags' => array( 'typingTime_fieldcolumn' ),
'items' => array( 'simple_grid_field27' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field30' => array( 'cols' => array( 31 ),
'rows' => array( 1 ),
'tags' => array( 'totalCallTime_fieldcolumn' ),
'items' => array( 'simple_grid_field28' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field31' => array( 'cols' => array( 32 ),
'rows' => array( 1 ),
'tags' => array( 'productFamilyId_fieldcolumn' ),
'items' => array( 'simple_grid_field38' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field32' => array( 'cols' => array( 33 ),
'rows' => array( 1 ),
'tags' => array( 'orderShipCompany_fieldcolumn' ),
'items' => array( 'simple_grid_field39' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field33' => array( 'cols' => array( 34 ),
'rows' => array( 1 ),
'tags' => array( 'orderInvoiceRequired_fieldcolumn' ),
'items' => array( 'simple_grid_field40' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field34' => array( 'cols' => array( 35 ),
'rows' => array( 1 ),
'tags' => array( 'internalCommunication_fieldcolumn' ),
'items' => array( 'simple_grid_field41' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field35' => array( 'cols' => array( 36 ),
'rows' => array( 1 ),
'tags' => array( 'deliveryComments_fieldcolumn' ),
'items' => array( 'simple_grid_field11' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field36' => array( 'cols' => array( 37 ),
'rows' => array( 1 ),
'tags' => array( 'callComments_fieldcolumn' ),
'items' => array( 'simple_grid_field19' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field37' => array( 'cols' => array( 38 ),
'rows' => array( 1 ),
'tags' => array( 'callGdprAcceptance_fieldcolumn' ),
'items' => array( 'simple_grid_field42' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field38' => array( 'cols' => array( 39 ),
'rows' => array( 1 ),
'tags' => array( 'callGdprRecordingAcceptance_fieldcolumn' ),
'items' => array( 'simple_grid_field43' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field39' => array( 'cols' => array( 40 ),
'rows' => array( 1 ),
'tags' => array( 'orderPaymentMethod_fieldcolumn' ),
'items' => array( 'simple_grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field40' => array( 'cols' => array( 41 ),
'rows' => array( 1 ),
'tags' => array( 'contactName_fieldcolumn' ),
'items' => array( 'simple_grid_field35' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field41' => array( 'cols' => array( 42 ),
'rows' => array( 1 ),
'tags' => array( 'contactZipCode_fieldcolumn' ),
'items' => array( 'simple_grid_field36' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field42' => array( 'cols' => array( 43 ),
'rows' => array( 1 ),
'tags' => array( 'contactCity_fieldcolumn' ),
'items' => array( 'simple_grid_field37' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field43' => array( 'cols' => array( 44 ),
'rows' => array( 1 ),
'tags' => array( 'ContactArea_fieldcolumn' ),
'items' => array( 'simple_grid_field44' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field44' => array( 'cols' => array( 45 ),
'rows' => array( 1 ),
'tags' => array( 'contactGender_fieldcolumn' ),
'items' => array( 'simple_grid_field45' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field45' => array( 'cols' => array( 46 ),
'rows' => array( 1 ),
'tags' => array( 'callDate_fieldcolumn' ),
'items' => array( 'simple_grid_field18' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field46' => array( 'cols' => array( 47 ),
'rows' => array( 1 ),
'tags' => array( 'callTime_fieldcolumn' ),
'items' => array( 'simple_grid_field46' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field47' => array( 'cols' => array( 48 ),
'rows' => array( 1 ),
'tags' => array( 'contactAge_fieldcolumn' ),
'items' => array( 'simple_grid_field47' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field48' => array( 'cols' => array( 49 ),
'rows' => array( 1 ),
'tags' => array( 'crmUser_fieldcolumn' ),
'items' => array( 'simple_grid_field48' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field49' => array( 'cols' => array( 50 ),
'rows' => array( 1 ),
'tags' => array( 'pauseAfterCall_fieldcolumn' ),
'items' => array( 'simple_grid_field49' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_icons' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field1' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field2' => array( 'cols' => array( 3 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field3' => array( 'cols' => array( 4 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field4' => array( 'cols' => array( 5 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field5' => array( 'cols' => array( 6 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field6' => array( 'cols' => array( 7 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field7' => array( 'cols' => array( 8 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field8' => array( 'cols' => array( 9 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field9' => array( 'cols' => array( 10 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field10' => array( 'cols' => array( 11 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field11' => array( 'cols' => array( 12 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field12' => array( 'cols' => array( 13 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field13' => array( 'cols' => array( 14 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field14' => array( 'cols' => array( 15 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field15' => array( 'cols' => array( 16 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field16' => array( 'cols' => array( 17 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field17' => array( 'cols' => array( 18 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field18' => array( 'cols' => array( 19 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field19' => array( 'cols' => array( 20 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field20' => array( 'cols' => array( 21 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field21' => array( 'cols' => array( 22 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field22' => array( 'cols' => array( 23 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field23' => array( 'cols' => array( 24 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field24' => array( 'cols' => array( 25 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field25' => array( 'cols' => array( 26 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field26' => array( 'cols' => array( 27 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field27' => array( 'cols' => array( 28 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field28' => array( 'cols' => array( 29 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field29' => array( 'cols' => array( 30 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field30' => array( 'cols' => array( 31 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field31' => array( 'cols' => array( 32 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field32' => array( 'cols' => array( 33 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field33' => array( 'cols' => array( 34 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field34' => array( 'cols' => array( 35 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field35' => array( 'cols' => array( 36 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field36' => array( 'cols' => array( 37 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field37' => array( 'cols' => array( 38 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field38' => array( 'cols' => array( 39 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field39' => array( 'cols' => array( 40 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field40' => array( 'cols' => array( 41 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field41' => array( 'cols' => array( 42 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field42' => array( 'cols' => array( 43 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field43' => array( 'cols' => array( 44 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field44' => array( 'cols' => array( 45 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field45' => array( 'cols' => array( 46 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field46' => array( 'cols' => array( 47 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field47' => array( 'cols' => array( 48 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field48' => array( 'cols' => array( 49 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field49' => array( 'cols' => array( 50 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 51,
'height' => 3 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'gridType' => 0,
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'masterprint',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'masterprint',
'type' => 'masterprint',
'layoutId' => 'masterprint',
'disabled' => 0,
'default' => 0,
'forms' => array( 'top' => array( 'modelId' => 'masterlist-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'masterprint_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'empty-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'inline_add' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'empty-above-grid',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'horizontal-grid',
'grid' => array( array( 'section' => 'head',
'cells' => array( array( 'cell' => 'headcell_icons' ),
array( 'cell' => 'headcell_field' ),
array( 'cell' => 'headcell_field1' ),
array( 'cell' => 'headcell_field2' ),
array( 'cell' => 'headcell_field3' ),
array( 'cell' => 'headcell_field4' ),
array( 'cell' => 'headcell_field5' ),
array( 'cell' => 'headcell_field6' ),
array( 'cell' => 'headcell_field7' ),
array( 'cell' => 'headcell_field8' ),
array( 'cell' => 'headcell_field9' ),
array( 'cell' => 'headcell_field10' ),
array( 'cell' => 'headcell_field11' ),
array( 'cell' => 'headcell_field12' ),
array( 'cell' => 'headcell_field13' ),
array( 'cell' => 'headcell_field14' ),
array( 'cell' => 'headcell_field15' ),
array( 'cell' => 'headcell_field16' ),
array( 'cell' => 'headcell_field17' ),
array( 'cell' => 'headcell_field18' ),
array( 'cell' => 'headcell_field19' ),
array( 'cell' => 'headcell_field20' ),
array( 'cell' => 'headcell_field21' ),
array( 'cell' => 'headcell_field22' ),
array( 'cell' => 'headcell_field23' ),
array( 'cell' => 'headcell_field24' ),
array( 'cell' => 'headcell_field25' ),
array( 'cell' => 'headcell_field26' ),
array( 'cell' => 'headcell_field27' ),
array( 'cell' => 'headcell_field28' ),
array( 'cell' => 'headcell_field29' ),
array( 'cell' => 'headcell_field30' ),
array( 'cell' => 'headcell_field31' ),
array( 'cell' => 'headcell_field32' ),
array( 'cell' => 'headcell_field33' ),
array( 'cell' => 'headcell_field34' ),
array( 'cell' => 'headcell_field35' ),
array( 'cell' => 'headcell_field36' ),
array( 'cell' => 'headcell_field37' ),
array( 'cell' => 'headcell_field38' ),
array( 'cell' => 'headcell_field39' ),
array( 'cell' => 'headcell_field40' ),
array( 'cell' => 'headcell_field41' ),
array( 'cell' => 'headcell_field42' ),
array( 'cell' => 'headcell_field43' ),
array( 'cell' => 'headcell_field44' ),
array( 'cell' => 'headcell_field45' ),
array( 'cell' => 'headcell_field46' ),
array( 'cell' => 'headcell_field47' ),
array( 'cell' => 'headcell_field48' ),
array( 'cell' => 'headcell_field49' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_icons' ),
array( 'cell' => 'cell_field' ),
array( 'cell' => 'cell_field1' ),
array( 'cell' => 'cell_field2' ),
array( 'cell' => 'cell_field3' ),
array( 'cell' => 'cell_field4' ),
array( 'cell' => 'cell_field5' ),
array( 'cell' => 'cell_field6' ),
array( 'cell' => 'cell_field7' ),
array( 'cell' => 'cell_field8' ),
array( 'cell' => 'cell_field9' ),
array( 'cell' => 'cell_field10' ),
array( 'cell' => 'cell_field11' ),
array( 'cell' => 'cell_field12' ),
array( 'cell' => 'cell_field13' ),
array( 'cell' => 'cell_field14' ),
array( 'cell' => 'cell_field15' ),
array( 'cell' => 'cell_field16' ),
array( 'cell' => 'cell_field17' ),
array( 'cell' => 'cell_field18' ),
array( 'cell' => 'cell_field19' ),
array( 'cell' => 'cell_field20' ),
array( 'cell' => 'cell_field21' ),
array( 'cell' => 'cell_field22' ),
array( 'cell' => 'cell_field23' ),
array( 'cell' => 'cell_field24' ),
array( 'cell' => 'cell_field25' ),
array( 'cell' => 'cell_field26' ),
array( 'cell' => 'cell_field27' ),
array( 'cell' => 'cell_field28' ),
array( 'cell' => 'cell_field29' ),
array( 'cell' => 'cell_field30' ),
array( 'cell' => 'cell_field31' ),
array( 'cell' => 'cell_field32' ),
array( 'cell' => 'cell_field33' ),
array( 'cell' => 'cell_field34' ),
array( 'cell' => 'cell_field35' ),
array( 'cell' => 'cell_field36' ),
array( 'cell' => 'cell_field37' ),
array( 'cell' => 'cell_field38' ),
array( 'cell' => 'cell_field39' ),
array( 'cell' => 'cell_field40' ),
array( 'cell' => 'cell_field41' ),
array( 'cell' => 'cell_field42' ),
array( 'cell' => 'cell_field43' ),
array( 'cell' => 'cell_field44' ),
array( 'cell' => 'cell_field45' ),
array( 'cell' => 'cell_field46' ),
array( 'cell' => 'cell_field47' ),
array( 'cell' => 'cell_field48' ),
array( 'cell' => 'cell_field49' ) ) ),
array( 'section' => 'foot',
'cells' => array( array( 'cell' => 'footcell_icons' ),
array( 'cell' => 'footcell_field' ),
array( 'cell' => 'footcell_field1' ),
array( 'cell' => 'footcell_field2' ),
array( 'cell' => 'footcell_field3' ),
array( 'cell' => 'footcell_field4' ),
array( 'cell' => 'footcell_field5' ),
array( 'cell' => 'footcell_field6' ),
array( 'cell' => 'footcell_field7' ),
array( 'cell' => 'footcell_field8' ),
array( 'cell' => 'footcell_field9' ),
array( 'cell' => 'footcell_field10' ),
array( 'cell' => 'footcell_field11' ),
array( 'cell' => 'footcell_field12' ),
array( 'cell' => 'footcell_field13' ),
array( 'cell' => 'footcell_field14' ),
array( 'cell' => 'footcell_field15' ),
array( 'cell' => 'footcell_field16' ),
array( 'cell' => 'footcell_field17' ),
array( 'cell' => 'footcell_field18' ),
array( 'cell' => 'footcell_field19' ),
array( 'cell' => 'footcell_field20' ),
array( 'cell' => 'footcell_field21' ),
array( 'cell' => 'footcell_field22' ),
array( 'cell' => 'footcell_field23' ),
array( 'cell' => 'footcell_field24' ),
array( 'cell' => 'footcell_field25' ),
array( 'cell' => 'footcell_field26' ),
array( 'cell' => 'footcell_field27' ),
array( 'cell' => 'footcell_field28' ),
array( 'cell' => 'footcell_field29' ),
array( 'cell' => 'footcell_field30' ),
array( 'cell' => 'footcell_field31' ),
array( 'cell' => 'footcell_field32' ),
array( 'cell' => 'footcell_field33' ),
array( 'cell' => 'footcell_field34' ),
array( 'cell' => 'footcell_field35' ),
array( 'cell' => 'footcell_field36' ),
array( 'cell' => 'footcell_field37' ),
array( 'cell' => 'footcell_field38' ),
array( 'cell' => 'footcell_field39' ),
array( 'cell' => 'footcell_field40' ),
array( 'cell' => 'footcell_field41' ),
array( 'cell' => 'footcell_field42' ),
array( 'cell' => 'footcell_field43' ),
array( 'cell' => 'footcell_field44' ),
array( 'cell' => 'footcell_field45' ),
array( 'cell' => 'footcell_field46' ),
array( 'cell' => 'footcell_field47' ),
array( 'cell' => 'footcell_field48' ),
array( 'cell' => 'footcell_field49' ) ) ) ),
'cells' => array( 'headcell_field' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field50' ),
'field' => 'broadcast',
'columnName' => 'field' ),
'cell_field' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field5' ),
'field' => 'broadcast',
'columnName' => 'field' ),
'footcell_field' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field1' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field51' ),
'field' => 'tvchannel',
'columnName' => 'field' ),
'cell_field1' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field6' ),
'field' => 'tvchannel',
'columnName' => 'field' ),
'footcell_field1' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field2' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field52' ),
'field' => 'seller',
'columnName' => 'field' ),
'cell_field2' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field7' ),
'field' => 'seller',
'columnName' => 'field' ),
'footcell_field2' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field3' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field53' ),
'field' => 'callStatusId',
'columnName' => 'field' ),
'cell_field3' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field8' ),
'field' => 'callStatusId',
'columnName' => 'field' ),
'footcell_field3' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field4' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field54' ),
'field' => 'remarks',
'columnName' => 'field' ),
'cell_field4' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field10' ),
'field' => 'remarks',
'columnName' => 'field' ),
'footcell_field4' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field5' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field55' ),
'field' => 'redialDate',
'columnName' => 'field' ),
'cell_field5' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field12' ),
'field' => 'redialDate',
'columnName' => 'field' ),
'footcell_field5' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field6' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field56' ),
'field' => 'redialComments',
'columnName' => 'field' ),
'cell_field6' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field13' ),
'field' => 'redialComments',
'columnName' => 'field' ),
'footcell_field6' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field7' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field57' ),
'field' => 'redialIsPrivate',
'columnName' => 'field' ),
'cell_field7' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field14' ),
'field' => 'redialIsPrivate',
'columnName' => 'field' ),
'footcell_field7' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field8' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field58' ),
'field' => 'redialDone',
'columnName' => 'field' ),
'cell_field8' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field15' ),
'field' => 'redialDone',
'columnName' => 'field' ),
'footcell_field8' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field9' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field59' ),
'field' => 'contactMethod',
'columnName' => 'field' ),
'cell_field9' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field16' ),
'field' => 'contactMethod',
'columnName' => 'field' ),
'footcell_field9' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field10' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field60' ),
'field' => 'courier',
'columnName' => 'field' ),
'cell_field10' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field17' ),
'field' => 'courier',
'columnName' => 'field' ),
'footcell_field10' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field11' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field61' ),
'field' => 'courierDeliveryDate',
'columnName' => 'field' ),
'cell_field11' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field20' ),
'field' => 'courierDeliveryDate',
'columnName' => 'field' ),
'footcell_field11' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field12' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field62' ),
'field' => 'courierTimeFrom',
'columnName' => 'field' ),
'cell_field12' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field21' ),
'field' => 'courierTimeFrom',
'columnName' => 'field' ),
'footcell_field12' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field13' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field63' ),
'field' => 'courierTimeTo',
'columnName' => 'field' ),
'cell_field13' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field22' ),
'field' => 'courierTimeTo',
'columnName' => 'field' ),
'footcell_field13' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field14' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field64' ),
'field' => 'contactId',
'columnName' => 'field' ),
'cell_field14' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field23' ),
'field' => 'contactId',
'columnName' => 'field' ),
'footcell_field14' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field15' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field65' ),
'field' => 'dialerRecording',
'columnName' => 'field' ),
'cell_field15' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field25' ),
'field' => 'dialerRecording',
'columnName' => 'field' ),
'footcell_field15' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field16' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field66' ),
'field' => 'dialerCampaign',
'columnName' => 'field' ),
'cell_field16' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field29' ),
'field' => 'dialerCampaign',
'columnName' => 'field' ),
'footcell_field16' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field17' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field67' ),
'field' => 'dialerList',
'columnName' => 'field' ),
'cell_field17' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field31' ),
'field' => 'dialerList',
'columnName' => 'field' ),
'footcell_field17' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field18' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field68' ),
'field' => 'dialerLeadID',
'columnName' => 'field' ),
'cell_field18' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field32' ),
'field' => 'dialerLeadID',
'columnName' => 'field' ),
'footcell_field18' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field19' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field69' ),
'field' => 'dialerAgent',
'columnName' => 'field' ),
'cell_field19' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field33' ),
'field' => 'dialerAgent',
'columnName' => 'field' ),
'footcell_field19' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field20' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field70' ),
'field' => 'callDenialReasonID',
'columnName' => 'field' ),
'cell_field20' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field9' ),
'field' => 'callDenialReasonID',
'columnName' => 'field' ),
'footcell_field20' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field21' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field71' ),
'field' => 'callClassificationID',
'columnName' => 'field' ),
'cell_field21' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field30' ),
'field' => 'callClassificationID',
'columnName' => 'field' ),
'footcell_field21' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field22' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field72' ),
'field' => 'callSubClassificationID',
'columnName' => 'field' ),
'cell_field22' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field34' ),
'field' => 'callSubClassificationID',
'columnName' => 'field' ),
'footcell_field22' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field23' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field73' ),
'field' => 'dialerPhone',
'columnName' => 'field' ),
'cell_field23' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field1' ),
'field' => 'dialerPhone',
'columnName' => 'field' ),
'footcell_field23' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field24' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field74' ),
'field' => 'dialerCallEpoch',
'columnName' => 'field' ),
'cell_field24' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field3' ),
'field' => 'dialerCallEpoch',
'columnName' => 'field' ),
'footcell_field24' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field25' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field75' ),
'field' => 'callStart',
'columnName' => 'field' ),
'cell_field25' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field2' ),
'field' => 'callStart',
'columnName' => 'field' ),
'footcell_field25' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field26' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field76' ),
'field' => 'callHangup',
'columnName' => 'field' ),
'cell_field26' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field4' ),
'field' => 'callHangup',
'columnName' => 'field' ),
'footcell_field26' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field27' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field77' ),
'field' => 'callEnd',
'columnName' => 'field' ),
'cell_field27' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field24' ),
'field' => 'callEnd',
'columnName' => 'field' ),
'footcell_field27' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field28' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field78' ),
'field' => 'talkTime',
'columnName' => 'field' ),
'cell_field28' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field26' ),
'field' => 'talkTime',
'columnName' => 'field' ),
'footcell_field28' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field29' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field79' ),
'field' => 'typingTime',
'columnName' => 'field' ),
'cell_field29' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field27' ),
'field' => 'typingTime',
'columnName' => 'field' ),
'footcell_field29' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field30' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field80' ),
'field' => 'totalCallTime',
'columnName' => 'field' ),
'cell_field30' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field28' ),
'field' => 'totalCallTime',
'columnName' => 'field' ),
'footcell_field30' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field31' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field81' ),
'field' => 'productFamilyId',
'columnName' => 'field' ),
'cell_field31' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field38' ),
'field' => 'productFamilyId',
'columnName' => 'field' ),
'footcell_field31' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field32' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field82' ),
'field' => 'orderShipCompany',
'columnName' => 'field' ),
'cell_field32' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field39' ),
'field' => 'orderShipCompany',
'columnName' => 'field' ),
'footcell_field32' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field33' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field83' ),
'field' => 'orderInvoiceRequired',
'columnName' => 'field' ),
'cell_field33' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field40' ),
'field' => 'orderInvoiceRequired',
'columnName' => 'field' ),
'footcell_field33' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field34' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field84' ),
'field' => 'internalCommunication',
'columnName' => 'field' ),
'cell_field34' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field41' ),
'field' => 'internalCommunication',
'columnName' => 'field' ),
'footcell_field34' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field35' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field85' ),
'field' => 'deliveryComments',
'columnName' => 'field' ),
'cell_field35' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field11' ),
'field' => 'deliveryComments',
'columnName' => 'field' ),
'footcell_field35' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field36' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field86' ),
'field' => 'callComments',
'columnName' => 'field' ),
'cell_field36' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field19' ),
'field' => 'callComments',
'columnName' => 'field' ),
'footcell_field36' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field37' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field87' ),
'field' => 'callGdprAcceptance',
'columnName' => 'field' ),
'cell_field37' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field42' ),
'field' => 'callGdprAcceptance',
'columnName' => 'field' ),
'footcell_field37' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field38' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field88' ),
'field' => 'callGdprRecordingAcceptance',
'columnName' => 'field' ),
'cell_field38' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field43' ),
'field' => 'callGdprRecordingAcceptance',
'columnName' => 'field' ),
'footcell_field38' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field39' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field89' ),
'field' => 'orderPaymentMethod',
'columnName' => 'field' ),
'cell_field39' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field' ),
'field' => 'orderPaymentMethod',
'columnName' => 'field' ),
'footcell_field39' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field40' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field90' ),
'field' => 'contactName',
'columnName' => 'field' ),
'cell_field40' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field35' ),
'field' => 'contactName',
'columnName' => 'field' ),
'footcell_field40' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field41' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field91' ),
'field' => 'contactZipCode',
'columnName' => 'field' ),
'cell_field41' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field36' ),
'field' => 'contactZipCode',
'columnName' => 'field' ),
'footcell_field41' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field42' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field92' ),
'field' => 'contactCity',
'columnName' => 'field' ),
'cell_field42' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field37' ),
'field' => 'contactCity',
'columnName' => 'field' ),
'footcell_field42' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field43' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field93' ),
'field' => 'ContactArea',
'columnName' => 'field' ),
'cell_field43' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field44' ),
'field' => 'ContactArea',
'columnName' => 'field' ),
'footcell_field43' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field44' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field94' ),
'field' => 'contactGender',
'columnName' => 'field' ),
'cell_field44' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field45' ),
'field' => 'contactGender',
'columnName' => 'field' ),
'footcell_field44' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field45' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field95' ),
'field' => 'callDate',
'columnName' => 'field' ),
'cell_field45' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field18' ),
'field' => 'callDate',
'columnName' => 'field' ),
'footcell_field45' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field46' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field96' ),
'field' => 'callTime',
'columnName' => 'field' ),
'cell_field46' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field46' ),
'field' => 'callTime',
'columnName' => 'field' ),
'footcell_field46' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field47' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field97' ),
'field' => 'contactAge',
'columnName' => 'field' ),
'cell_field47' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field47' ),
'field' => 'contactAge',
'columnName' => 'field' ),
'footcell_field47' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field48' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field98' ),
'field' => 'crmUser',
'columnName' => 'field' ),
'cell_field48' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field48' ),
'field' => 'crmUser',
'columnName' => 'field' ),
'footcell_field48' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field49' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field99' ),
'field' => 'pauseAfterCall',
'columnName' => 'field' ),
'cell_field49' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field49' ),
'field' => 'pauseAfterCall',
'columnName' => 'field' ),
'footcell_field49' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_icons' => array( 'model' => 'headcell_icons',
'items' => array(  ) ),
'cell_icons' => array( 'model' => 'cell_icons',
'items' => array( 'grid_inline_cancel' ) ),
'footcell_icons' => array( 'model' => 'footcell_icons',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'masterprint_header' => array( 'type' => 'masterprint_header' ),
'simple_grid_field5' => array( 'field' => 'broadcast',
'type' => 'grid_field' ),
'simple_grid_field50' => array( 'type' => 'grid_field_label',
'field' => 'broadcast' ),
'simple_grid_field6' => array( 'field' => 'tvchannel',
'type' => 'grid_field' ),
'simple_grid_field51' => array( 'type' => 'grid_field_label',
'field' => 'tvchannel' ),
'simple_grid_field7' => array( 'field' => 'seller',
'type' => 'grid_field' ),
'simple_grid_field52' => array( 'type' => 'grid_field_label',
'field' => 'seller' ),
'simple_grid_field8' => array( 'field' => 'callStatusId',
'type' => 'grid_field' ),
'simple_grid_field53' => array( 'type' => 'grid_field_label',
'field' => 'callStatusId' ),
'simple_grid_field10' => array( 'field' => 'remarks',
'type' => 'grid_field' ),
'simple_grid_field54' => array( 'type' => 'grid_field_label',
'field' => 'remarks' ),
'simple_grid_field12' => array( 'field' => 'redialDate',
'type' => 'grid_field' ),
'simple_grid_field55' => array( 'type' => 'grid_field_label',
'field' => 'redialDate' ),
'simple_grid_field13' => array( 'field' => 'redialComments',
'type' => 'grid_field' ),
'simple_grid_field56' => array( 'type' => 'grid_field_label',
'field' => 'redialComments' ),
'simple_grid_field14' => array( 'field' => 'redialIsPrivate',
'type' => 'grid_field' ),
'simple_grid_field57' => array( 'type' => 'grid_field_label',
'field' => 'redialIsPrivate' ),
'simple_grid_field15' => array( 'field' => 'redialDone',
'type' => 'grid_field' ),
'simple_grid_field58' => array( 'type' => 'grid_field_label',
'field' => 'redialDone' ),
'simple_grid_field16' => array( 'field' => 'contactMethod',
'type' => 'grid_field' ),
'simple_grid_field59' => array( 'type' => 'grid_field_label',
'field' => 'contactMethod' ),
'simple_grid_field17' => array( 'field' => 'courier',
'type' => 'grid_field' ),
'simple_grid_field60' => array( 'type' => 'grid_field_label',
'field' => 'courier' ),
'simple_grid_field20' => array( 'field' => 'courierDeliveryDate',
'type' => 'grid_field' ),
'simple_grid_field61' => array( 'type' => 'grid_field_label',
'field' => 'courierDeliveryDate' ),
'simple_grid_field21' => array( 'field' => 'courierTimeFrom',
'type' => 'grid_field' ),
'simple_grid_field62' => array( 'type' => 'grid_field_label',
'field' => 'courierTimeFrom' ),
'simple_grid_field22' => array( 'field' => 'courierTimeTo',
'type' => 'grid_field' ),
'simple_grid_field63' => array( 'type' => 'grid_field_label',
'field' => 'courierTimeTo' ),
'simple_grid_field23' => array( 'field' => 'contactId',
'type' => 'grid_field' ),
'simple_grid_field64' => array( 'type' => 'grid_field_label',
'field' => 'contactId' ),
'simple_grid_field25' => array( 'field' => 'dialerRecording',
'type' => 'grid_field' ),
'simple_grid_field65' => array( 'type' => 'grid_field_label',
'field' => 'dialerRecording' ),
'simple_grid_field29' => array( 'field' => 'dialerCampaign',
'type' => 'grid_field' ),
'simple_grid_field66' => array( 'type' => 'grid_field_label',
'field' => 'dialerCampaign' ),
'simple_grid_field31' => array( 'field' => 'dialerList',
'type' => 'grid_field' ),
'simple_grid_field67' => array( 'type' => 'grid_field_label',
'field' => 'dialerList' ),
'simple_grid_field32' => array( 'field' => 'dialerLeadID',
'type' => 'grid_field' ),
'simple_grid_field68' => array( 'type' => 'grid_field_label',
'field' => 'dialerLeadID' ),
'simple_grid_field33' => array( 'field' => 'dialerAgent',
'type' => 'grid_field' ),
'simple_grid_field69' => array( 'type' => 'grid_field_label',
'field' => 'dialerAgent' ),
'simple_grid_field9' => array( 'field' => 'callDenialReasonID',
'type' => 'grid_field' ),
'simple_grid_field70' => array( 'type' => 'grid_field_label',
'field' => 'callDenialReasonID' ),
'simple_grid_field30' => array( 'field' => 'callClassificationID',
'type' => 'grid_field' ),
'simple_grid_field71' => array( 'type' => 'grid_field_label',
'field' => 'callClassificationID' ),
'simple_grid_field34' => array( 'field' => 'callSubClassificationID',
'type' => 'grid_field' ),
'simple_grid_field72' => array( 'type' => 'grid_field_label',
'field' => 'callSubClassificationID' ),
'simple_grid_field1' => array( 'field' => 'dialerPhone',
'type' => 'grid_field' ),
'simple_grid_field73' => array( 'type' => 'grid_field_label',
'field' => 'dialerPhone' ),
'simple_grid_field3' => array( 'field' => 'dialerCallEpoch',
'type' => 'grid_field' ),
'simple_grid_field74' => array( 'type' => 'grid_field_label',
'field' => 'dialerCallEpoch' ),
'simple_grid_field2' => array( 'field' => 'callStart',
'type' => 'grid_field' ),
'simple_grid_field75' => array( 'type' => 'grid_field_label',
'field' => 'callStart' ),
'simple_grid_field4' => array( 'field' => 'callHangup',
'type' => 'grid_field' ),
'simple_grid_field76' => array( 'type' => 'grid_field_label',
'field' => 'callHangup' ),
'simple_grid_field24' => array( 'field' => 'callEnd',
'type' => 'grid_field' ),
'simple_grid_field77' => array( 'type' => 'grid_field_label',
'field' => 'callEnd' ),
'simple_grid_field26' => array( 'field' => 'talkTime',
'type' => 'grid_field' ),
'simple_grid_field78' => array( 'type' => 'grid_field_label',
'field' => 'talkTime' ),
'simple_grid_field27' => array( 'field' => 'typingTime',
'type' => 'grid_field' ),
'simple_grid_field79' => array( 'type' => 'grid_field_label',
'field' => 'typingTime' ),
'simple_grid_field28' => array( 'field' => 'totalCallTime',
'type' => 'grid_field' ),
'simple_grid_field80' => array( 'type' => 'grid_field_label',
'field' => 'totalCallTime' ),
'simple_grid_field38' => array( 'field' => 'productFamilyId',
'type' => 'grid_field' ),
'simple_grid_field81' => array( 'type' => 'grid_field_label',
'field' => 'productFamilyId' ),
'simple_grid_field39' => array( 'field' => 'orderShipCompany',
'type' => 'grid_field' ),
'simple_grid_field82' => array( 'type' => 'grid_field_label',
'field' => 'orderShipCompany' ),
'simple_grid_field40' => array( 'field' => 'orderInvoiceRequired',
'type' => 'grid_field' ),
'simple_grid_field83' => array( 'type' => 'grid_field_label',
'field' => 'orderInvoiceRequired' ),
'simple_grid_field41' => array( 'field' => 'internalCommunication',
'type' => 'grid_field' ),
'simple_grid_field84' => array( 'type' => 'grid_field_label',
'field' => 'internalCommunication' ),
'simple_grid_field11' => array( 'field' => 'deliveryComments',
'type' => 'grid_field' ),
'simple_grid_field85' => array( 'type' => 'grid_field_label',
'field' => 'deliveryComments' ),
'simple_grid_field19' => array( 'field' => 'callComments',
'type' => 'grid_field' ),
'simple_grid_field86' => array( 'type' => 'grid_field_label',
'field' => 'callComments' ),
'simple_grid_field42' => array( 'field' => 'callGdprAcceptance',
'type' => 'grid_field' ),
'simple_grid_field87' => array( 'type' => 'grid_field_label',
'field' => 'callGdprAcceptance' ),
'simple_grid_field43' => array( 'field' => 'callGdprRecordingAcceptance',
'type' => 'grid_field' ),
'simple_grid_field88' => array( 'type' => 'grid_field_label',
'field' => 'callGdprRecordingAcceptance' ),
'simple_grid_field' => array( 'field' => 'orderPaymentMethod',
'type' => 'grid_field' ),
'simple_grid_field89' => array( 'type' => 'grid_field_label',
'field' => 'orderPaymentMethod' ),
'simple_grid_field35' => array( 'field' => 'contactName',
'type' => 'grid_field' ),
'simple_grid_field90' => array( 'type' => 'grid_field_label',
'field' => 'contactName' ),
'simple_grid_field36' => array( 'field' => 'contactZipCode',
'type' => 'grid_field' ),
'simple_grid_field91' => array( 'type' => 'grid_field_label',
'field' => 'contactZipCode' ),
'simple_grid_field37' => array( 'field' => 'contactCity',
'type' => 'grid_field' ),
'simple_grid_field92' => array( 'type' => 'grid_field_label',
'field' => 'contactCity' ),
'simple_grid_field44' => array( 'field' => 'ContactArea',
'type' => 'grid_field' ),
'simple_grid_field93' => array( 'type' => 'grid_field_label',
'field' => 'ContactArea' ),
'simple_grid_field45' => array( 'field' => 'contactGender',
'type' => 'grid_field' ),
'simple_grid_field94' => array( 'type' => 'grid_field_label',
'field' => 'contactGender' ),
'simple_grid_field18' => array( 'field' => 'callDate',
'type' => 'grid_field' ),
'simple_grid_field95' => array( 'type' => 'grid_field_label',
'field' => 'callDate' ),
'simple_grid_field46' => array( 'field' => 'callTime',
'type' => 'grid_field' ),
'simple_grid_field96' => array( 'type' => 'grid_field_label',
'field' => 'callTime' ),
'simple_grid_field47' => array( 'field' => 'contactAge',
'type' => 'grid_field' ),
'simple_grid_field97' => array( 'type' => 'grid_field_label',
'field' => 'contactAge' ),
'simple_grid_field48' => array( 'field' => 'crmUser',
'type' => 'grid_field' ),
'simple_grid_field98' => array( 'type' => 'grid_field_label',
'field' => 'crmUser' ),
'simple_grid_field49' => array( 'field' => 'pauseAfterCall',
'type' => 'grid_field' ),
'simple_grid_field99' => array( 'type' => 'grid_field_label',
'field' => 'pauseAfterCall' ),
'inline_add' => array( 'type' => 'inline_add',
'detailsOnly' => true ),
'grid_inline_cancel' => array( 'type' => 'grid_inline_cancel' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>