<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'callStatusId',
'callDenialReasonID',
'callClassificationID',
'callSubClassificationID',
'dialerPhone',
'dialerCampaign',
'callDate' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'callStatusId' => array( 'integrated_search_field11',
'search_field_between5',
'search_field_options5',
'search_field_label5' ),
'callDenialReasonID' => array( 'integrated_search_field12',
'search_field_between6',
'search_field_options6',
'search_field_label6' ),
'callClassificationID' => array( 'integrated_search_field13',
'search_field_label4',
'search_field_options4',
'search_field_between4' ),
'callSubClassificationID' => array( 'integrated_search_field14',
'search_field_options',
'search_field_between',
'search_field_label' ),
'dialerPhone' => array( 'integrated_search_field26',
'search_field_label3',
'search_field_options3',
'search_field_between3' ),
'dialerCampaign' => array( 'integrated_search_field28',
'search_field_label2',
'search_field_options2',
'search_field_between2' ),
'callDate' => array( 'integrated_search_field',
'search_field_label1',
'search_field_options1',
'search_field_between1' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array( 'logo',
'menu',
'loginform_login',
'username_button' ),
'top' => array( 'search_header' ),
'above-grid' => array(  ),
'below-grid' => array( 'search_search',
'search_reset',
'search_back_list',
'search_cancel' ),
'grid' => array( 'integrated_search_field',
'search_field_between1',
'search_field_label1',
'search_field_options1',
'search_field_label4',
'search_field_options4',
'integrated_search_field13',
'search_field_between4',
'search_field_label',
'search_field_label3',
'search_field_options3',
'integrated_search_field26',
'search_field_between3',
'search_field_label2',
'integrated_search_field28',
'search_field_between2',
'search_field_label6',
'search_field_options6',
'integrated_search_field12',
'search_field_between6',
'integrated_search_field14',
'search_field_between',
'search_field_label5',
'search_field_options5',
'integrated_search_field11',
'search_field_between5',
'search_field_options2',
'search_field_options' ) ),
'formXtTags' => array( 'above-grid' => array(  ) ),
'itemForms' => array( 'logo' => 'supertop',
'menu' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'search_header' => 'top',
'search_search' => 'below-grid',
'search_reset' => 'below-grid',
'search_back_list' => 'below-grid',
'search_cancel' => 'below-grid',
'integrated_search_field' => 'grid',
'search_field_between1' => 'grid',
'search_field_label1' => 'grid',
'search_field_options1' => 'grid',
'search_field_label4' => 'grid',
'search_field_options4' => 'grid',
'integrated_search_field13' => 'grid',
'search_field_between4' => 'grid',
'search_field_label' => 'grid',
'search_field_label3' => 'grid',
'search_field_options3' => 'grid',
'integrated_search_field26' => 'grid',
'search_field_between3' => 'grid',
'search_field_label2' => 'grid',
'integrated_search_field28' => 'grid',
'search_field_between2' => 'grid',
'search_field_label6' => 'grid',
'search_field_options6' => 'grid',
'integrated_search_field12' => 'grid',
'search_field_between6' => 'grid',
'integrated_search_field14' => 'grid',
'search_field_between' => 'grid',
'search_field_label5' => 'grid',
'search_field_options5' => 'grid',
'integrated_search_field11' => 'grid',
'search_field_between5' => 'grid',
'search_field_options2' => 'grid',
'search_field_options' => 'grid' ),
'itemLocations' => array( 'integrated_search_field' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'search_field_between1' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'search_field_label1' => array( 'location' => 'grid',
'cellId' => 'c9' ),
'search_field_options1' => array( 'location' => 'grid',
'cellId' => 'c12' ),
'search_field_label4' => array( 'location' => 'grid',
'cellId' => 'c19' ),
'search_field_options4' => array( 'location' => 'grid',
'cellId' => 'c20' ),
'integrated_search_field13' => array( 'location' => 'grid',
'cellId' => 'c22' ),
'search_field_between4' => array( 'location' => 'grid',
'cellId' => 'c22' ),
'search_field_label' => array( 'location' => 'grid',
'cellId' => 'c23' ),
'search_field_label3' => array( 'location' => 'grid',
'cellId' => 'c34' ),
'search_field_options3' => array( 'location' => 'grid',
'cellId' => 'c35' ),
'integrated_search_field26' => array( 'location' => 'grid',
'cellId' => 'c37' ),
'search_field_between3' => array( 'location' => 'grid',
'cellId' => 'c37' ),
'search_field_label2' => array( 'location' => 'grid',
'cellId' => 'c38' ),
'integrated_search_field28' => array( 'location' => 'grid',
'cellId' => 'c40' ),
'search_field_between2' => array( 'location' => 'grid',
'cellId' => 'c40' ),
'search_field_label6' => array( 'location' => 'grid',
'cellId' => 'c48' ),
'search_field_options6' => array( 'location' => 'grid',
'cellId' => 'c49' ),
'integrated_search_field12' => array( 'location' => 'grid',
'cellId' => 'c51' ),
'search_field_between6' => array( 'location' => 'grid',
'cellId' => 'c51' ),
'integrated_search_field14' => array( 'location' => 'grid',
'cellId' => 'c55' ),
'search_field_between' => array( 'location' => 'grid',
'cellId' => 'c55' ),
'search_field_label5' => array( 'location' => 'grid',
'cellId' => 'c58' ),
'search_field_options5' => array( 'location' => 'grid',
'cellId' => 'c59' ),
'integrated_search_field11' => array( 'location' => 'grid',
'cellId' => 'c61' ),
'search_field_between5' => array( 'location' => 'grid',
'cellId' => 'c61' ),
'search_field_options2' => array( 'location' => 'grid',
'cellId' => 'c75' ),
'search_field_options' => array( 'location' => 'grid',
'cellId' => 'c78' ) ),
'itemVisiblity' => array( 'menu' => 3,
'loginform_login' => 3,
'username_button' => 3 ) ),
'itemsByType' => array( 'search_header' => array( 'search_header' ),
'search_reset' => array( 'search_reset' ),
'search_back_list' => array( 'search_back_list' ),
'search_search' => array( 'search_search' ),
'search_cancel' => array( 'search_cancel' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'search_field' => array( 'integrated_search_field11',
'integrated_search_field12',
'integrated_search_field13',
'integrated_search_field14',
'integrated_search_field26',
'integrated_search_field28',
'integrated_search_field' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'logout_link' => array( 'logout_link' ),
'adminarea_link' => array( 'adminarea_link' ),
'search_field_options' => array( 'search_field_options',
'search_field_options1',
'search_field_options2',
'search_field_options3',
'search_field_options4',
'search_field_options6',
'search_field_options5' ),
'search_field_between' => array( 'search_field_between',
'search_field_between1',
'search_field_between2',
'search_field_between3',
'search_field_between4',
'search_field_between6',
'search_field_between5' ),
'search_field_label' => array( 'search_field_label1',
'search_field_label2',
'search_field_label3',
'search_field_label4',
'search_field_label6',
'search_field_label5',
'search_field_label' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c9' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c12' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c3' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c11' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c5' => array( 'cols' => array( 4 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c74' => array( 'cols' => array( 5 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c36' => array( 'cols' => array( 6 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c34' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'dialerPhone_fieldblock' ),
'items' => array( 'search_field_label3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c35' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'search_field_options3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c37' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_search_field26',
'search_field_between3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c15' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c38' => array( 'cols' => array( 4 ),
'rows' => array( 1 ),
'tags' => array( 'dialerCampaign_fieldblock' ),
'items' => array( 'search_field_label2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c75' => array( 'cols' => array( 5 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'search_field_options2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c40' => array( 'cols' => array( 6 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_search_field28',
'search_field_between2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c29' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c30' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c32' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c16' => array( 'cols' => array( 3 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c33' => array( 'cols' => array( 4 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c76' => array( 'cols' => array( 5 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c45' => array( 'cols' => array( 6 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c19' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c20' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'search_field_options4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c22' => array( 'cols' => array( 2 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_search_field13',
'search_field_between4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c18' => array( 'cols' => array( 3 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c23' => array( 'cols' => array( 4 ),
'rows' => array( 3 ),
'tags' => array( 'callSubClassificationID_fieldblock' ),
'items' => array( 'search_field_label' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c78' => array( 'cols' => array( 5 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'search_field_options' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c55' => array( 'cols' => array( 6 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_search_field14',
'search_field_between' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c58' => array( 'cols' => array( 0 ),
'rows' => array( 4 ),
'tags' => array( 'callStatusId_fieldblock' ),
'items' => array( 'search_field_label5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c59' => array( 'cols' => array( 1 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'search_field_options5' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c61' => array( 'cols' => array( 2 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_search_field11',
'search_field_between5' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c21' => array( 'cols' => array( 3 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c62' => array( 'cols' => array( 4 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c79' => array( 'cols' => array( 5 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c60' => array( 'cols' => array( 6 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c48' => array( 'cols' => array( 0 ),
'rows' => array( 5 ),
'tags' => array( 'callDenialReasonID_fieldblock' ),
'items' => array( 'search_field_label6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c49' => array( 'cols' => array( 1 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'search_field_options6' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c51' => array( 'cols' => array( 2 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'integrated_search_field12',
'search_field_between6' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c31' => array( 'cols' => array( 3 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c52' => array( 'cols' => array( 4 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c81' => array( 'cols' => array( 5 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c68' => array( 'cols' => array( 6 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c43' => array( 'cols' => array( 0 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c44' => array( 'cols' => array( 1 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c46' => array( 'cols' => array( 2 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c87' => array( 'cols' => array( 3 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c47' => array( 'cols' => array( 4 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c82' => array( 'cols' => array( 5 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c69' => array( 'cols' => array( 6 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 7,
'height' => 7 ) ) ),
'loginForm' => array( 'loginForm' => 1 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'search',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'search',
'type' => 'search',
'layoutId' => 'topbar',
'disabled' => 0,
'default' => 1,
'forms' => array( 'supertop' => array( 'modelId' => 'topbar-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ),
array( 'cell' => 'c3' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'logo' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'menu' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c3' => array( 'model' => 'c3',
'items' => array( 'loginform_login',
'username_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'search-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'search_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'search-above-grid',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'search-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'search_search',
'search_reset',
'search_back_list',
'search_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-search',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c9' ),
array( 'cell' => 'c12' ),
array( 'cell' => 'c3' ),
array( 'cell' => 'c11' ),
array( 'cell' => 'c5' ),
array( 'cell' => 'c74' ),
array( 'cell' => 'c36' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c34' ),
array( 'cell' => 'c35' ),
array( 'cell' => 'c37' ),
array( 'cell' => 'c15' ),
array( 'cell' => 'c38' ),
array( 'cell' => 'c75' ),
array( 'cell' => 'c40' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c29' ),
array( 'cell' => 'c30' ),
array( 'cell' => 'c32' ),
array( 'cell' => 'c16' ),
array( 'cell' => 'c33' ),
array( 'cell' => 'c76' ),
array( 'cell' => 'c45' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c19' ),
array( 'cell' => 'c20' ),
array( 'cell' => 'c22' ),
array( 'cell' => 'c18' ),
array( 'cell' => 'c23' ),
array( 'cell' => 'c78' ),
array( 'cell' => 'c55' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c58' ),
array( 'cell' => 'c59' ),
array( 'cell' => 'c61' ),
array( 'cell' => 'c21' ),
array( 'cell' => 'c62' ),
array( 'cell' => 'c79' ),
array( 'cell' => 'c60' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c48' ),
array( 'cell' => 'c49' ),
array( 'cell' => 'c51' ),
array( 'cell' => 'c31' ),
array( 'cell' => 'c52' ),
array( 'cell' => 'c81' ),
array( 'cell' => 'c68' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c43' ),
array( 'cell' => 'c44' ),
array( 'cell' => 'c46' ),
array( 'cell' => 'c87' ),
array( 'cell' => 'c47' ),
array( 'cell' => 'c82' ),
array( 'cell' => 'c69' ) ) ) ),
'cells' => array( 'c3' => array( 'model' => 'c5',
'items' => array( 'integrated_search_field',
'search_field_between1' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'width' => '120px',
'persistent' => true,
'orientation' => 'vertical',
'background' => '#eef8ff' ),
'c5' => array( 'model' => 'c5',
'items' => array(  ),
'width' => '100px',
'align' => 'right',
'background' => '#eef8ff' ),
'c9' => array( 'model' => 'c5',
'items' => array( 'search_field_label1' ),
'width' => '140px',
'persistent' => true,
'align' => 'right',
'background' => '#ffeeee' ),
'c12' => array( 'model' => 'c5',
'items' => array( 'search_field_options1' ),
'width' => '80px',
'persistent' => true,
'background' => '#ffeeee' ),
'c19' => array( 'model' => 'c5',
'items' => array( 'search_field_label4' ),
'persistent' => true,
'align' => 'right' ),
'c20' => array( 'model' => 'c5',
'items' => array( 'search_field_options4' ) ),
'c22' => array( 'model' => 'c5',
'items' => array( 'integrated_search_field13',
'search_field_between4' ),
'orientation' => 'vertical' ),
'c23' => array( 'model' => 'c3',
'items' => array( 'search_field_label' ),
'align' => 'right' ),
'c29' => array( 'model' => 'c5',
'items' => array(  ),
'align' => 'right',
'persistent' => true ),
'c30' => array( 'model' => 'c5',
'items' => array(  ) ),
'c32' => array( 'model' => 'c5',
'items' => array(  ),
'orientation' => 'vertical' ),
'c33' => array( 'model' => 'c5',
'items' => array(  ),
'align' => 'right' ),
'c34' => array( 'model' => 'c5',
'items' => array( 'search_field_label3' ),
'align' => 'right' ),
'c35' => array( 'model' => 'c5',
'items' => array( 'search_field_options3' ) ),
'c36' => array( 'model' => 'c5',
'items' => array(  ),
'orientation' => 'vertical',
'width' => '120px',
'background' => '#eef8ff' ),
'c37' => array( 'model' => 'c5',
'items' => array( 'integrated_search_field26',
'search_field_between3' ),
'orientation' => 'vertical' ),
'c38' => array( 'model' => 'c5',
'items' => array( 'search_field_label2' ),
'align' => 'right' ),
'c40' => array( 'model' => 'c5',
'items' => array( 'integrated_search_field28',
'search_field_between2' ),
'orientation' => 'vertical' ),
'c43' => array( 'model' => 'c5',
'items' => array(  ),
'align' => 'right',
'persistent' => true ),
'c44' => array( 'model' => 'c5',
'items' => array(  ) ),
'c45' => array( 'model' => 'c3',
'items' => array(  ),
'orientation' => 'vertical' ),
'c46' => array( 'model' => 'c5',
'items' => array(  ),
'orientation' => 'vertical' ),
'c47' => array( 'model' => 'c3',
'items' => array(  ) ),
'c48' => array( 'model' => 'c5',
'items' => array( 'search_field_label6' ),
'align' => 'right' ),
'c49' => array( 'model' => 'c5',
'items' => array( 'search_field_options6' ) ),
'c51' => array( 'model' => 'c5',
'items' => array( 'integrated_search_field12',
'search_field_between6' ),
'orientation' => 'vertical' ),
'c52' => array( 'model' => 'c3',
'items' => array(  ) ),
'c55' => array( 'model' => 'c5',
'items' => array( 'integrated_search_field14',
'search_field_between' ) ),
'c58' => array( 'model' => 'c5',
'items' => array( 'search_field_label5' ),
'align' => 'right' ),
'c59' => array( 'model' => 'c5',
'items' => array( 'search_field_options5' ) ),
'c60' => array( 'model' => 'c3',
'items' => array(  ) ),
'c61' => array( 'model' => 'c5',
'items' => array( 'integrated_search_field11',
'search_field_between5' ),
'orientation' => 'vertical' ),
'c62' => array( 'model' => 'c3',
'items' => array(  ),
'align' => 'right' ),
'c68' => array( 'model' => 'c3',
'items' => array(  ) ),
'c69' => array( 'model' => 'c3',
'items' => array(  ) ),
'c74' => array( 'model' => 'c3',
'items' => array(  ),
'width' => '80px',
'background' => '#eef8ff' ),
'c75' => array( 'model' => 'c3',
'items' => array( 'search_field_options2' ) ),
'c76' => array( 'model' => 'c3',
'items' => array(  ) ),
'c78' => array( 'model' => 'c3',
'items' => array( 'search_field_options' ) ),
'c79' => array( 'model' => 'c3',
'items' => array(  ) ),
'c81' => array( 'model' => 'c3',
'items' => array(  ) ),
'c82' => array( 'model' => 'c3',
'items' => array(  ) ),
'c11' => array( 'model' => 'c5',
'items' => array(  ),
'persistent' => true,
'width' => '20px',
'background' => '#eef8ff' ),
'c15' => array( 'model' => 'c5',
'items' => array(  ) ),
'c16' => array( 'model' => 'c5',
'items' => array(  ) ),
'c18' => array( 'model' => 'c3',
'items' => array(  ) ),
'c21' => array( 'model' => 'c3',
'items' => array(  ) ),
'c31' => array( 'model' => 'c3',
'items' => array(  ) ),
'c87' => array( 'model' => 'c3',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'separateLabels' => false ) ),
'items' => array( 'search_header' => array( 'type' => 'search_header',
'title' => array( 'page' => 'search',
'table' => 'callsAgentView',
'type' => 7 ) ),
'search_reset' => array( 'type' => 'search_reset' ),
'search_back_list' => array( 'type' => 'search_back_list' ),
'search_search' => array( 'type' => 'search_search' ),
'search_cancel' => array( 'type' => 'search_cancel' ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu' ),
'integrated_search_field11' => array( 'field' => 'callStatusId',
'type' => 'search_field',
'orientation' => 0,
'required' => false,
'joined' => false,
'separated' => true ),
'integrated_search_field12' => array( 'field' => 'callDenialReasonID',
'type' => 'search_field',
'orientation' => 0,
'required' => false,
'joined' => false,
'separated' => true ),
'integrated_search_field13' => array( 'field' => 'callClassificationID',
'type' => 'search_field',
'orientation' => 0,
'required' => false,
'joined' => false,
'separated' => true ),
'integrated_search_field14' => array( 'field' => 'callSubClassificationID',
'type' => 'search_field',
'orientation' => 0,
'required' => false,
'joined' => false,
'separated' => true ),
'integrated_search_field26' => array( 'field' => 'dialerPhone',
'type' => 'search_field',
'orientation' => 0,
'required' => false,
'joined' => false,
'separated' => true ),
'integrated_search_field28' => array( 'field' => 'dialerCampaign',
'type' => 'search_field',
'orientation' => 0,
'required' => false,
'joined' => false,
'separated' => true ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'logout_link',
'adminarea_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => true ),
'logout_link' => array( 'type' => 'logout_link' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'integrated_search_field' => array( 'field' => 'callDate',
'type' => 'search_field',
'orientation' => 0,
'required' => false,
'joined' => false,
'separated' => true ),
'search_field_options' => array( 'type' => 'search_field_options',
'field' => 'callSubClassificationID',
'separated' => true ),
'search_field_between' => array( 'type' => 'search_field_between',
'field' => 'callSubClassificationID',
'separated' => true ),
'search_field_label1' => array( 'type' => 'search_field_label',
'field' => 'callDate',
'separated' => true,
'label' => array( 'field' => 'callDate',
'table' => 'agentCallsView',
'type' => 3 ) ),
'search_field_options1' => array( 'type' => 'search_field_options',
'field' => 'callDate',
'separated' => true ),
'search_field_between1' => array( 'type' => 'search_field_between',
'field' => 'callDate',
'separated' => true ),
'search_field_label2' => array( 'type' => 'search_field_label',
'field' => 'dialerCampaign',
'separated' => true ),
'search_field_options2' => array( 'type' => 'search_field_options',
'field' => 'dialerCampaign',
'separated' => true ),
'search_field_between2' => array( 'type' => 'search_field_between',
'field' => 'dialerCampaign',
'separated' => true ),
'search_field_label3' => array( 'type' => 'search_field_label',
'field' => 'dialerPhone',
'separated' => true,
'label' => array( 'field' => 'dialerPhone',
'table' => 'agentCallsView',
'type' => 3 ) ),
'search_field_options3' => array( 'type' => 'search_field_options',
'field' => 'dialerPhone',
'separated' => true ),
'search_field_between3' => array( 'type' => 'search_field_between',
'field' => 'dialerPhone',
'separated' => true ),
'search_field_label4' => array( 'type' => 'search_field_label',
'field' => 'callClassificationID',
'separated' => true,
'label' => array( 'field' => 'callClassificationID',
'table' => 'agentCallsView',
'type' => 3 ) ),
'search_field_options4' => array( 'type' => 'search_field_options',
'field' => 'callClassificationID',
'separated' => true ),
'search_field_between4' => array( 'type' => 'search_field_between',
'field' => 'callClassificationID',
'separated' => true ),
'search_field_between6' => array( 'type' => 'search_field_between',
'field' => 'callDenialReasonID',
'separated' => true ),
'search_field_options6' => array( 'type' => 'search_field_options',
'field' => 'callDenialReasonID',
'separated' => true ),
'search_field_label6' => array( 'type' => 'search_field_label',
'field' => 'callDenialReasonID',
'separated' => true,
'label' => array( 'field' => 'callDenialReasonID',
'table' => 'agentCallsView',
'type' => 3 ) ),
'search_field_between5' => array( 'type' => 'search_field_between',
'field' => 'callStatusId',
'separated' => true ),
'search_field_options5' => array( 'type' => 'search_field_options',
'field' => 'callStatusId',
'separated' => true ),
'search_field_label5' => array( 'type' => 'search_field_label',
'field' => 'callStatusId',
'separated' => true ),
'search_field_label' => array( 'type' => 'search_field_label',
'field' => 'callSubClassificationID',
'separated' => true,
'label' => array( 'field' => 'callSubClassificationID',
'table' => 'agentCallsView',
'type' => 3 ) ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>