<?php
			$optionsArray = array( 'list' => array( 'inlineAdd' => false,
'detailsAdd' => false,
'inlineEdit' => false,
'delete' => false,
'updateSelected' => false,
'addInPopup' => null,
'editInPopup' => null,
'viewInPopup' => null,
'clickSort' => true,
'sortDropdown' => false,
'showHideFields' => false,
'reorderFields' => false ),
'listSearch' => array( 'alwaysOnPanelFields' => array(  ),
'searchPanel' => true,
'fixedSearchPanel' => false,
'simpleSearchOptions' => false,
'searchSaving' => false ),
'totals' => array( 'id' => array( 'totalsType' => '' ),
'dialerPhone' => array( 'totalsType' => '' ),
'dialerAgent' => array( 'totalsType' => '' ),
'callDate' => array( 'totalsType' => '' ),
'callTime' => array( 'totalsType' => '' ),
'redialDate' => array( 'totalsType' => '' ),
'redialTime' => array( 'totalsType' => '' ),
'redialComments' => array( 'totalsType' => '' ),
'redialIsPrivate' => array( 'totalsType' => '' ),
'redialDone' => array( 'totalsType' => '' ),
'callClassificationID' => array( 'totalsType' => '' ),
'callSubClassificationID' => array( 'totalsType' => '' ),
'totalCallTime' => array( 'totalsType' => '' ),
'dialerRecording' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'callDate',
'callTime',
'callClassificationID',
'callSubClassificationID',
'redialDate',
'redialComments',
'redialIsPrivate',
'redialDone',
'dialerPhone',
'dialerAgent',
'dialerRecording',
'redialTime',
'id' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array( 'redialTime',
'id',
'dialerRecording',
'dialerAgent',
'dialerPhone',
'redialDone',
'redialIsPrivate',
'redialComments',
'redialDate',
'callSubClassificationID',
'callClassificationID',
'totalCallTime',
'callTime',
'callDate' ),
'filterFields' => array(  ),
'inlineAddFields' => array(  ),
'inlineEditFields' => array(  ),
'fieldItems' => array( 'callDate' => array( 'simple_grid_field3',
'simple_grid_field10' ),
'callTime' => array( 'simple_grid_field4',
'simple_grid_field11' ),
'callClassificationID' => array( 'simple_grid_field15',
'simple_grid_field17' ),
'callSubClassificationID' => array( 'simple_grid_field16',
'simple_grid_field22' ),
'redialDate' => array( 'simple_grid_field18',
'simple_grid_field23' ),
'redialComments' => array( 'simple_grid_field19',
'simple_grid_field24' ),
'redialIsPrivate' => array( 'simple_grid_field20',
'simple_grid_field25' ),
'redialDone' => array( 'simple_grid_field21',
'simple_grid_field26' ),
'dialerPhone' => array( 'simple_grid_field28',
'simple_grid_field29' ),
'dialerAgent' => array( 'simple_grid_field33',
'simple_grid_field35' ),
'dialerRecording' => array( 'simple_grid_field34',
'simple_grid_field36' ),
'redialTime' => array( 'simple_grid_field5',
'simple_grid_field13' ),
'id' => array( 'grid_field',
'grid_field_label' ) ),
'hideEmptyFields' => array(  ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array( 'logo',
'menu',
'simple_search',
'list_options',
'loginform_login',
'username_button' ),
'left' => array( 'search_panel' ),
'top' => array(  ),
'above-grid' => array( 'details_found',
'page_size' ),
'below-grid' => array( 'pagination' ),
'grid' => array( 'simple_grid_field23',
'simple_grid_field10',
'simple_grid_field3',
'simple_grid_field11',
'simple_grid_field4',
'simple_grid_field17',
'simple_grid_field15',
'simple_grid_field22',
'simple_grid_field16',
'simple_grid_field26',
'simple_grid_field21',
'simple_grid_field29',
'simple_grid_field28',
'simple_grid_field36',
'simple_grid_field34',
'custom_button',
'simple_grid_field18',
'simple_grid_field13',
'simple_grid_field5',
'simple_grid_field24',
'simple_grid_field19',
'simple_grid_field25',
'simple_grid_field20',
'simple_grid_field35',
'simple_grid_field33',
'grid_field_label',
'grid_field' ) ),
'formXtTags' => array( 'top' => array(  ),
'above-grid' => array( 'details_found',
'recsPerPage' ),
'below-grid' => array( 'pagination' ) ),
'itemForms' => array( 'logo' => 'supertop',
'menu' => 'supertop',
'simple_search' => 'supertop',
'list_options' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'search_panel' => 'left',
'details_found' => 'above-grid',
'page_size' => 'above-grid',
'pagination' => 'below-grid',
'simple_grid_field23' => 'grid',
'simple_grid_field10' => 'grid',
'simple_grid_field3' => 'grid',
'simple_grid_field11' => 'grid',
'simple_grid_field4' => 'grid',
'simple_grid_field17' => 'grid',
'simple_grid_field15' => 'grid',
'simple_grid_field22' => 'grid',
'simple_grid_field16' => 'grid',
'simple_grid_field26' => 'grid',
'simple_grid_field21' => 'grid',
'simple_grid_field29' => 'grid',
'simple_grid_field28' => 'grid',
'simple_grid_field36' => 'grid',
'simple_grid_field34' => 'grid',
'custom_button' => 'grid',
'simple_grid_field18' => 'grid',
'simple_grid_field13' => 'grid',
'simple_grid_field5' => 'grid',
'simple_grid_field24' => 'grid',
'simple_grid_field19' => 'grid',
'simple_grid_field25' => 'grid',
'simple_grid_field20' => 'grid',
'simple_grid_field35' => 'grid',
'simple_grid_field33' => 'grid',
'grid_field_label' => 'grid',
'grid_field' => 'grid' ),
'itemLocations' => array( 'simple_grid_field23' => array( 'location' => 'grid',
'cellId' => 'footcell_field' ),
'simple_grid_field10' => array( 'location' => 'grid',
'cellId' => 'headcell_field3' ),
'simple_grid_field3' => array( 'location' => 'grid',
'cellId' => 'cell_field3' ),
'simple_grid_field11' => array( 'location' => 'grid',
'cellId' => 'headcell_field4' ),
'simple_grid_field4' => array( 'location' => 'grid',
'cellId' => 'cell_field4' ),
'simple_grid_field17' => array( 'location' => 'grid',
'cellId' => 'headcell_field6' ),
'simple_grid_field15' => array( 'location' => 'grid',
'cellId' => 'cell_field6' ),
'simple_grid_field22' => array( 'location' => 'grid',
'cellId' => 'headcell_field7' ),
'simple_grid_field16' => array( 'location' => 'grid',
'cellId' => 'cell_field7' ),
'simple_grid_field26' => array( 'location' => 'grid',
'cellId' => 'headcell_field11' ),
'simple_grid_field21' => array( 'location' => 'grid',
'cellId' => 'cell_field11' ),
'simple_grid_field29' => array( 'location' => 'grid',
'cellId' => 'headcell_field12' ),
'simple_grid_field28' => array( 'location' => 'grid',
'cellId' => 'cell_field12' ),
'simple_grid_field36' => array( 'location' => 'grid',
'cellId' => 'headcell_field14' ),
'simple_grid_field34' => array( 'location' => 'grid',
'cellId' => 'cell_field14' ),
'custom_button' => array( 'location' => 'grid',
'cellId' => 'cell_field16' ),
'simple_grid_field18' => array( 'location' => 'grid',
'cellId' => 'footcell_field16' ),
'simple_grid_field13' => array( 'location' => 'grid',
'cellId' => 'footcell_field18' ),
'simple_grid_field5' => array( 'location' => 'grid',
'cellId' => 'footcell_field19' ),
'simple_grid_field24' => array( 'location' => 'grid',
'cellId' => 'footcell_field21' ),
'simple_grid_field19' => array( 'location' => 'grid',
'cellId' => 'footcell_field22' ),
'simple_grid_field25' => array( 'location' => 'grid',
'cellId' => 'footcell_field24' ),
'simple_grid_field20' => array( 'location' => 'grid',
'cellId' => 'footcell_field25' ),
'simple_grid_field35' => array( 'location' => 'grid',
'cellId' => 'cell_field18' ),
'simple_grid_field33' => array( 'location' => 'grid',
'cellId' => 'cell_field19' ),
'grid_field_label' => array( 'location' => 'grid',
'cellId' => 'headcell_field' ),
'grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ) ),
'itemVisiblity' => array( 'menu' => 3,
'simple_search' => 3,
'list_options' => 3,
'loginform_login' => 3,
'username_button' => 3,
'search_panel' => 5 ) ),
'itemsByType' => array( 'page_size' => array( 'page_size' ),
'details_found' => array( 'details_found' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'simple_search' => array( 'simple_search' ),
'pagination' => array( 'pagination' ),
'grid_field' => array( 'simple_grid_field3',
'simple_grid_field4',
'simple_grid_field15',
'simple_grid_field16',
'simple_grid_field18',
'simple_grid_field19',
'simple_grid_field20',
'simple_grid_field21',
'simple_grid_field28',
'simple_grid_field33',
'simple_grid_field34',
'simple_grid_field5',
'grid_field' ),
'search_panel' => array( 'search_panel' ),
'list_options' => array( 'list_options' ),
'show_search_panel' => array( 'show_search_panel' ),
'hide_search_panel' => array( 'hide_search_panel' ),
'search_panel_field' => array( 'search_panel_field',
'search_panel_field3',
'search_panel_field4',
'search_panel_field9',
'search_panel_field15',
'search_panel_field16',
'search_panel_field18',
'search_panel_field19',
'search_panel_field20',
'search_panel_field21',
'search_panel_field28',
'search_panel_field33',
'search_panel_field34',
'search_panel_field5' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'logout_link' => array( 'logout_link' ),
'adminarea_link' => array( 'adminarea_link' ),
'advsearch_link' => array( 'advsearch_link' ),
'grid_field_label' => array( 'simple_grid_field10',
'simple_grid_field11',
'simple_grid_field17',
'simple_grid_field22',
'simple_grid_field23',
'simple_grid_field24',
'simple_grid_field25',
'simple_grid_field26',
'simple_grid_field29',
'simple_grid_field35',
'simple_grid_field36',
'simple_grid_field13',
'grid_field_label' ),
'custom_button' => array( 'custom_button' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'cell_field' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field18' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array( 'dialerAgent_fieldheadercolumn' ),
'items' => array( 'simple_grid_field35' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field3' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array( 'callDate_fieldheadercolumn' ),
'items' => array( 'simple_grid_field10' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field4' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array( 'callTime_fieldheadercolumn' ),
'items' => array( 'simple_grid_field11' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field' => array( 'cols' => array( 4 ),
'rows' => array( 0 ),
'tags' => array( 'redialDate_fieldheadercolumn' ),
'items' => array( 'simple_grid_field23' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field18' => array( 'cols' => array( 5 ),
'rows' => array( 0 ),
'tags' => array( 'redialTime_fieldheadercolumn' ),
'items' => array( 'simple_grid_field13' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field21' => array( 'cols' => array( 6 ),
'rows' => array( 0 ),
'tags' => array( 'redialComments_fieldheadercolumn' ),
'items' => array( 'simple_grid_field24' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field24' => array( 'cols' => array( 7 ),
'rows' => array( 0 ),
'tags' => array( 'redialIsPrivate_fieldheadercolumn' ),
'items' => array( 'simple_grid_field25' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field6' => array( 'cols' => array( 8 ),
'rows' => array( 0 ),
'tags' => array( 'callClassificationID_fieldheadercolumn' ),
'items' => array( 'simple_grid_field17' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field7' => array( 'cols' => array( 9 ),
'rows' => array( 0 ),
'tags' => array( 'callSubClassificationID_fieldheadercolumn' ),
'items' => array( 'simple_grid_field22' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field11' => array( 'cols' => array( 10 ),
'rows' => array( 0 ),
'tags' => array( 'redialDone_fieldheadercolumn' ),
'items' => array( 'simple_grid_field26' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field12' => array( 'cols' => array( 11 ),
'rows' => array( 0 ),
'tags' => array( 'dialerPhone_fieldheadercolumn' ),
'items' => array( 'simple_grid_field29' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field14' => array( 'cols' => array( 12 ),
'rows' => array( 0 ),
'tags' => array( 'dialerRecording_fieldheadercolumn' ),
'items' => array( 'simple_grid_field36' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field' => array( 'cols' => array( 13 ),
'rows' => array( 0 ),
'tags' => array( 'id_fieldheadercolumn' ),
'items' => array( 'grid_field_label' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field16' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'cell_field19' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array( 'dialerAgent_fieldcolumn' ),
'items' => array( 'simple_grid_field33' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field3' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array( 'callDate_fieldcolumn' ),
'items' => array( 'simple_grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field4' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array( 'callTime_fieldcolumn' ),
'items' => array( 'simple_grid_field4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field16' => array( 'cols' => array( 4 ),
'rows' => array( 1 ),
'tags' => array( 'redialDate_fieldcolumn' ),
'items' => array( 'simple_grid_field18' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field19' => array( 'cols' => array( 5 ),
'rows' => array( 1 ),
'tags' => array( 'redialTime_fieldcolumn' ),
'items' => array( 'simple_grid_field5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field22' => array( 'cols' => array( 6 ),
'rows' => array( 1 ),
'tags' => array( 'redialComments_fieldcolumn' ),
'items' => array( 'simple_grid_field19' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field25' => array( 'cols' => array( 7 ),
'rows' => array( 1 ),
'tags' => array( 'redialIsPrivate_fieldcolumn' ),
'items' => array( 'simple_grid_field20' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field6' => array( 'cols' => array( 8 ),
'rows' => array( 1 ),
'tags' => array( 'callClassificationID_fieldcolumn' ),
'items' => array( 'simple_grid_field15' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field7' => array( 'cols' => array( 9 ),
'rows' => array( 1 ),
'tags' => array( 'callSubClassificationID_fieldcolumn' ),
'items' => array( 'simple_grid_field16' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field11' => array( 'cols' => array( 10 ),
'rows' => array( 1 ),
'tags' => array( 'redialDone_fieldcolumn' ),
'items' => array( 'simple_grid_field21' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field12' => array( 'cols' => array( 11 ),
'rows' => array( 1 ),
'tags' => array( 'dialerPhone_fieldcolumn' ),
'items' => array( 'simple_grid_field28' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field14' => array( 'cols' => array( 12 ),
'rows' => array( 1 ),
'tags' => array( 'dialerRecording_fieldcolumn' ),
'items' => array( 'simple_grid_field34' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field1' => array( 'cols' => array( 13 ),
'rows' => array( 1 ),
'tags' => array( 'id_fieldcolumn' ),
'items' => array( 'grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field17' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field20' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field3' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field4' => array( 'cols' => array( 3 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field17' => array( 'cols' => array( 4 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field20' => array( 'cols' => array( 5 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field23' => array( 'cols' => array( 6 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field26' => array( 'cols' => array( 7 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field6' => array( 'cols' => array( 8 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field7' => array( 'cols' => array( 9 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field11' => array( 'cols' => array( 10 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field12' => array( 'cols' => array( 11 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field14' => array( 'cols' => array( 12 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field1' => array( 'cols' => array( 13 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 14,
'height' => 3 ) ) ),
'loginForm' => array( 'loginForm' => 1 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array( 'details_found' => array( 'tag' => 'DISPLAYING',
'type' => 2 ) ) ),
'gridType' => 0,
'recsPerRow' => 1,
'hasCustomButtons' => true,
'customButtons' => array( 'executeCallback' ) ),
'misc' => array( 'type' => 'list',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array( 'executeCallback' ) ),
'dataGrid' => array( 'groupFields' => array(  ) ) );
			$pageArray = array( 'id' => 'list',
'type' => 'list',
'layoutId' => 'topbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'topbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'logo',
'menu' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'simple_search',
'list_options',
'loginform_login',
'username_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'list-vbar',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'search_panel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'list-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'list-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'details_found',
'page_size' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'list-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'pagination' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'horizontal-grid',
'grid' => array( array( 'section' => 'head',
'cells' => array( array( 'cell' => 'cell_field' ),
array( 'cell' => 'cell_field18' ),
array( 'cell' => 'headcell_field3' ),
array( 'cell' => 'headcell_field4' ),
array( 'cell' => 'footcell_field' ),
array( 'cell' => 'footcell_field18' ),
array( 'cell' => 'footcell_field21' ),
array( 'cell' => 'footcell_field24' ),
array( 'cell' => 'headcell_field6' ),
array( 'cell' => 'headcell_field7' ),
array( 'cell' => 'headcell_field11' ),
array( 'cell' => 'headcell_field12' ),
array( 'cell' => 'headcell_field14' ),
array( 'cell' => 'headcell_field' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_field16' ),
array( 'cell' => 'cell_field19' ),
array( 'cell' => 'cell_field3' ),
array( 'cell' => 'cell_field4' ),
array( 'cell' => 'footcell_field16' ),
array( 'cell' => 'footcell_field19' ),
array( 'cell' => 'footcell_field22' ),
array( 'cell' => 'footcell_field25' ),
array( 'cell' => 'cell_field6' ),
array( 'cell' => 'cell_field7' ),
array( 'cell' => 'cell_field11' ),
array( 'cell' => 'cell_field12' ),
array( 'cell' => 'cell_field14' ),
array( 'cell' => 'cell_field1' ) ) ),
array( 'section' => 'foot',
'cells' => array( array( 'cell' => 'cell_field17' ),
array( 'cell' => 'cell_field20' ),
array( 'cell' => 'footcell_field3' ),
array( 'cell' => 'footcell_field4' ),
array( 'cell' => 'footcell_field17' ),
array( 'cell' => 'footcell_field20' ),
array( 'cell' => 'footcell_field23' ),
array( 'cell' => 'footcell_field26' ),
array( 'cell' => 'footcell_field6' ),
array( 'cell' => 'footcell_field7' ),
array( 'cell' => 'footcell_field11' ),
array( 'cell' => 'footcell_field12' ),
array( 'cell' => 'footcell_field14' ),
array( 'cell' => 'footcell_field1' ) ) ) ),
'cells' => array( 'cell_field' => array( 'model' => 'headcell_field',
'items' => array(  ),
'columnName' => '' ),
'footcell_field' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field23' ),
'columnName' => 'field',
'field' => 'redialDate' ),
'headcell_field3' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field10' ),
'field' => 'callDate',
'columnName' => 'field' ),
'cell_field3' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field3' ),
'field' => 'callDate',
'columnName' => 'field' ),
'footcell_field3' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field4' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field11' ),
'field' => 'callTime',
'columnName' => 'field' ),
'cell_field4' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field4' ),
'field' => 'callTime',
'columnName' => 'field' ),
'footcell_field4' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field6' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field17' ),
'field' => 'callClassificationID',
'columnName' => 'field' ),
'cell_field6' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field15' ),
'field' => 'callClassificationID',
'columnName' => 'field' ),
'footcell_field6' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field7' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field22' ),
'field' => 'callSubClassificationID',
'columnName' => 'field' ),
'cell_field7' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field16' ),
'field' => 'callSubClassificationID',
'columnName' => 'field' ),
'footcell_field7' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field11' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field26' ),
'field' => 'redialDone',
'columnName' => 'field' ),
'cell_field11' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field21' ),
'field' => 'redialDone',
'columnName' => 'field' ),
'footcell_field11' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field12' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field29' ),
'field' => 'dialerPhone',
'columnName' => 'field' ),
'cell_field12' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field28' ),
'field' => 'dialerPhone',
'columnName' => 'field' ),
'footcell_field12' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field14' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field36' ),
'field' => 'dialerRecording',
'columnName' => 'field' ),
'cell_field14' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field34' ),
'field' => 'dialerRecording',
'columnName' => 'field' ),
'footcell_field14' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'cell_field16' => array( 'model' => 'cell_field',
'items' => array( 'custom_button' ),
'columnName' => '' ),
'cell_field17' => array( 'model' => 'footcell_field',
'items' => array(  ),
'columnName' => '' ),
'footcell_field16' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field18' ),
'columnName' => 'field',
'field' => 'redialDate' ),
'footcell_field17' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'footcell_field18' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field13' ),
'columnName' => 'field',
'field' => 'redialTime' ),
'footcell_field19' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field5' ),
'columnName' => 'field',
'field' => 'redialTime' ),
'footcell_field20' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'footcell_field21' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field24' ),
'columnName' => 'field',
'field' => 'redialComments' ),
'footcell_field22' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field19' ),
'columnName' => 'field',
'field' => 'redialComments' ),
'footcell_field23' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'footcell_field24' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field25' ),
'columnName' => 'field',
'field' => 'redialIsPrivate' ),
'footcell_field25' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field20' ),
'columnName' => 'field',
'field' => 'redialIsPrivate' ),
'footcell_field26' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'cell_field18' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field35' ),
'columnName' => 'field',
'field' => 'dialerAgent' ),
'cell_field19' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field33' ),
'columnName' => 'field',
'field' => 'dialerAgent' ),
'cell_field20' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label' ),
'field' => 'id',
'columnName' => 'field' ),
'cell_field1' => array( 'model' => 'cell_field',
'items' => array( 'grid_field' ),
'field' => 'id',
'columnName' => 'field' ),
'footcell_field1' => array( 'model' => 'footcell_field',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'page_size' => array( 'type' => 'page_size' ),
'details_found' => array( 'type' => 'details_found' ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu' ),
'simple_search' => array( 'type' => 'simple_search' ),
'pagination' => array( 'type' => 'pagination' ),
'simple_grid_field3' => array( 'field' => 'callDate',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field4' => array( 'field' => 'callTime',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field15' => array( 'field' => 'callClassificationID',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field16' => array( 'field' => 'callSubClassificationID',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field18' => array( 'field' => 'redialDate',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field19' => array( 'field' => 'redialComments',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field20' => array( 'field' => 'redialIsPrivate',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field21' => array( 'field' => 'redialDone',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field28' => array( 'field' => 'dialerPhone',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field33' => array( 'field' => 'dialerAgent',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field34' => array( 'field' => 'dialerRecording',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'search_panel' => array( 'type' => 'search_panel',
'items' => array( 'search_panel_field5',
'search_panel_field',
'search_panel_field34',
'search_panel_field33',
'search_panel_field28',
'search_panel_field21',
'search_panel_field20',
'search_panel_field19',
'search_panel_field18',
'search_panel_field16',
'search_panel_field15',
'search_panel_field9',
'search_panel_field4',
'search_panel_field3' ),
'_flexiblePanel' => true ),
'list_options' => array( 'type' => 'list_options',
'items' => array( 'advsearch_link',
'show_search_panel',
'hide_search_panel' ) ),
'show_search_panel' => array( 'type' => 'show_search_panel' ),
'hide_search_panel' => array( 'type' => 'hide_search_panel' ),
'search_panel_field' => array( 'field' => 'id',
'type' => 'search_panel_field' ),
'search_panel_field3' => array( 'field' => 'callDate',
'type' => 'search_panel_field' ),
'search_panel_field4' => array( 'field' => 'callTime',
'type' => 'search_panel_field',
'alwaysOnPanel' => false,
'required' => false ),
'search_panel_field9' => array( 'field' => 'totalCallTime',
'type' => 'search_panel_field' ),
'search_panel_field15' => array( 'field' => 'callClassificationID',
'type' => 'search_panel_field',
'alwaysOnPanel' => false,
'required' => false ),
'search_panel_field16' => array( 'field' => 'callSubClassificationID',
'type' => 'search_panel_field' ),
'search_panel_field18' => array( 'field' => 'redialDate',
'type' => 'search_panel_field',
'alwaysOnPanel' => false,
'required' => false ),
'search_panel_field19' => array( 'field' => 'redialComments',
'type' => 'search_panel_field' ),
'search_panel_field20' => array( 'field' => 'redialIsPrivate',
'type' => 'search_panel_field',
'alwaysOnPanel' => false,
'required' => false ),
'search_panel_field21' => array( 'field' => 'redialDone',
'type' => 'search_panel_field' ),
'search_panel_field28' => array( 'field' => 'dialerPhone',
'type' => 'search_panel_field' ),
'search_panel_field33' => array( 'field' => 'dialerAgent',
'type' => 'search_panel_field',
'alwaysOnPanel' => false,
'required' => false ),
'search_panel_field34' => array( 'field' => 'dialerRecording',
'type' => 'search_panel_field' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'logout_link',
'adminarea_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => true ),
'logout_link' => array( 'type' => 'logout_link' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'search_panel_field5' => array( 'field' => 'redialTime',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'advsearch_link' => array( 'type' => 'advsearch_link' ),
'simple_grid_field5' => array( 'field' => 'redialTime',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field10' => array( 'type' => 'grid_field_label',
'field' => 'callDate',
'clickSort' => true ),
'simple_grid_field11' => array( 'type' => 'grid_field_label',
'field' => 'callTime',
'clickSort' => true ),
'simple_grid_field17' => array( 'type' => 'grid_field_label',
'field' => 'callClassificationID',
'clickSort' => true ),
'simple_grid_field22' => array( 'type' => 'grid_field_label',
'field' => 'callSubClassificationID',
'clickSort' => true ),
'simple_grid_field23' => array( 'type' => 'grid_field_label',
'field' => 'redialDate',
'clickSort' => true ),
'simple_grid_field24' => array( 'type' => 'grid_field_label',
'field' => 'redialComments',
'clickSort' => true ),
'simple_grid_field25' => array( 'type' => 'grid_field_label',
'field' => 'redialIsPrivate',
'clickSort' => true ),
'simple_grid_field26' => array( 'type' => 'grid_field_label',
'field' => 'redialDone',
'clickSort' => true ),
'simple_grid_field29' => array( 'type' => 'grid_field_label',
'field' => 'dialerPhone',
'clickSort' => true ),
'simple_grid_field35' => array( 'type' => 'grid_field_label',
'field' => 'dialerAgent',
'clickSort' => true ),
'simple_grid_field36' => array( 'type' => 'grid_field_label',
'field' => 'dialerRecording',
'clickSort' => true ),
'simple_grid_field13' => array( 'type' => 'grid_field_label',
'field' => 'redialTime',
'clickSort' => true ),
'custom_button' => array( 'type' => 'custom_button',
'eventId' => 'executeCallback',
'label' => array( 'text' => 'executeCallback',
'type' => 0 ) ),
'grid_field' => array( 'field' => 'id',
'type' => 'grid_field' ),
'grid_field_label' => array( 'type' => 'grid_field_label',
'field' => 'id' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>