<?php
			$optionsArray = array( 'pdf' => array( 'pdfView' => false ),
'details' => array( 'dbo.voltonApplications' => array( 'displayPreview' => 1,
'previewPageId' => 'voltonInDetailAddList' ),
'dbo.orderItems' => array( 'displayPreview' => 1,
'previewPageId' => 'list' ),
'dbo.internalComments' => array( 'displayPreview' => 1,
'previewPageId' => 'list' ),
'dbo.novaApplications' => array( 'displayPreview' => 1,
'previewPageId' => 'novaInlineAddList' ) ),
'master' => array( 'dbo.callStatus' => array( 'preview' => false ) ),
'fields' => array( 'gridFields' => array( 'callStatusId',
'callGdprRecordingAcceptance',
'redialComments',
'remarks',
'callClassificationID',
'callDenialReasonID',
'callGdprAcceptance',
'dialerLeadID',
'tvchannel',
'contactName',
'seller',
'broadcast',
'callEnd',
'typingTime',
'callHangup',
'talkTime',
'dialerRecording',
'totalCallTime',
'dialerCallEpoch',
'callComments',
'contactAge',
'contactGender',
'contactZipCode',
'contactCity',
'ContactArea',
'dialerPhone',
'productFamilyId',
'callStart',
'redialDate',
'redialIsPrivate',
'callSubClassificationID',
'orderPaymentMethod',
'courier',
'courierDeliveryDate',
'deliveryComments',
'courierTimeTo',
'courierTimeFrom',
'contactMethod',
'orderShipCompany',
'orderInvoiceRequired',
'contactId' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'callStatusId' => array( 'integrated_edit_field7',
'edit_field_label4' ),
'callGdprRecordingAcceptance' => array( 'integrated_edit_field42',
'edit_field_label25' ),
'redialComments' => array( 'integrated_edit_field6',
'edit_field_label8' ),
'remarks' => array( 'integrated_edit_field9',
'edit_field_label5' ),
'callClassificationID' => array( 'integrated_edit_field3',
'edit_field_label12' ),
'callDenialReasonID' => array( 'integrated_edit_field2',
'edit_field_label11' ),
'callGdprAcceptance' => array( 'integrated_edit_field41',
'edit_field_label26' ),
'dialerPhone' => array( 'edit_field_label10',
'integrated_edit_field' ),
'dialerLeadID' => array( 'integrated_edit_field30' ),
'callComments' => array( 'edit_field_label9',
'integrated_edit_field18' ),
'tvchannel' => array( 'integrated_edit_field5' ),
'contactName' => array( 'integrated_edit_field34',
'edit_field_label20' ),
'seller' => array( 'integrated_edit_field28' ),
'broadcast' => array( 'integrated_edit_field4' ),
'callEnd' => array( 'integrated_edit_field25' ),
'typingTime' => array( 'integrated_edit_field27' ),
'callHangup' => array( 'integrated_edit_field14' ),
'talkTime' => array( 'integrated_edit_field26' ),
'dialerRecording' => array( 'integrated_edit_field24' ),
'totalCallTime' => array( 'integrated_edit_field32' ),
'dialerCallEpoch' => array( 'integrated_edit_field23' ),
'contactAge' => array( 'integrated_edit_field17',
'edit_field_label14' ),
'contactGender' => array( 'integrated_edit_field43',
'edit_field_label21' ),
'contactZipCode' => array( 'integrated_edit_field35',
'edit_field_label22' ),
'contactCity' => array( 'integrated_edit_field39',
'edit_field_label24' ),
'ContactArea' => array( 'integrated_edit_field40',
'edit_field_label23' ),
'productFamilyId' => array( 'integrated_edit_field1' ),
'callStart' => array( 'integrated_edit_field36',
'edit_field_label3' ),
'redialDate' => array( 'edit_field_label6',
'integrated_edit_field11' ),
'redialIsPrivate' => array( 'integrated_edit_field12',
'edit_field_label7' ),
'callSubClassificationID' => array( 'integrated_edit_field8' ),
'orderPaymentMethod' => array( 'integrated_edit_field33' ),
'courier' => array( 'integrated_edit_field16' ),
'courierDeliveryDate' => array( 'integrated_edit_field19' ),
'deliveryComments' => array( 'integrated_edit_field10' ),
'courierTimeTo' => array( 'integrated_edit_field21' ),
'courierTimeFrom' => array( 'integrated_edit_field20' ),
'contactMethod' => array( 'integrated_edit_field15' ),
'orderShipCompany' => array( 'integrated_edit_field37' ),
'orderInvoiceRequired' => array( 'integrated_edit_field38' ),
'contactId' => array( 'integrated_edit_field22' ) ) ),
'pageLinks' => array( 'edit' => true,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'top' => array( 'view_header' ),
'above-grid' => array( 'text',
'text1',
'text7',
'text8',
'text9',
'text10',
'text11' ),
'below-grid' => array( 'view_back_list',
'view_close',
'hamburger' ),
'grid' => array( 'section3',
'section9',
'section',
'section7',
'section10' ),
'section6' => array( 'integrated_edit_field22',
'integrated_edit_field37',
'integrated_edit_field38',
'orderTotal',
'details_preview1',
'integrated_edit_field15',
'integrated_edit_field20',
'integrated_edit_field21',
'integrated_edit_field10',
'integrated_edit_field19',
'text6',
'integrated_edit_field16',
'integrated_edit_field33' ),
'section5' => array( 'edit_field_label4',
'integrated_edit_field7',
'edit_field_label11',
'integrated_edit_field2' ),
'section2' => array( 'integrated_edit_field42',
'integrated_edit_field41',
'edit_field_label10',
'edit_field_label8',
'edit_field_label9',
'edit_field_label5',
'edit_field_label12',
'section4',
'section5',
'section1',
'section8',
'section6',
'section2',
'integrated_edit_field3',
'integrated_edit_field9',
'integrated_edit_field6',
'integrated_edit_field18',
'integrated_edit_field8',
'edit_field_label7',
'integrated_edit_field12',
'integrated_edit_field11',
'edit_field_label6',
'edit_field_label3',
'integrated_edit_field36',
'text5',
'callTimerText',
'agentStatus',
'edit_field_label25',
'edit_field_label26',
'integrated_edit_field1',
'integrated_edit_field',
'section11' ),
'section4' => array( 'text2',
'integrated_edit_field5',
'text4',
'integrated_edit_field28',
'integrated_edit_field4',
'text3' ),
'section1' => array(  ),
'section' => array(  ),
'section3' => array( 'integrated_edit_field24',
'integrated_edit_field30',
'integrated_edit_field23' ),
'section7' => array( 'details_preview2' ),
'section9' => array( 'details_preview4' ),
'section8' => array( 'integrated_edit_field25',
'integrated_edit_field27',
'integrated_edit_field32',
'integrated_edit_field14',
'integrated_edit_field26' ),
'section11' => array( 'edit_field_label23',
'integrated_edit_field40',
'edit_field_label24',
'integrated_edit_field39',
'edit_field_label22',
'integrated_edit_field35',
'edit_field_label21',
'integrated_edit_field43',
'edit_field_label14',
'integrated_edit_field17',
'edit_field_label20',
'integrated_edit_field34' ),
'section10' => array( 'details_preview' ) ),
'formXtTags' => array(  ),
'itemForms' => array( 'view_header' => 'top',
'text' => 'above-grid',
'text1' => 'above-grid',
'text7' => 'above-grid',
'text8' => 'above-grid',
'text9' => 'above-grid',
'text10' => 'above-grid',
'text11' => 'above-grid',
'view_back_list' => 'below-grid',
'view_close' => 'below-grid',
'hamburger' => 'below-grid',
'section3' => 'grid',
'section9' => 'grid',
'section' => 'grid',
'section7' => 'grid',
'section10' => 'grid',
'integrated_edit_field22' => 'section6',
'integrated_edit_field37' => 'section6',
'integrated_edit_field38' => 'section6',
'orderTotal' => 'section6',
'details_preview1' => 'section6',
'integrated_edit_field15' => 'section6',
'integrated_edit_field20' => 'section6',
'integrated_edit_field21' => 'section6',
'integrated_edit_field10' => 'section6',
'integrated_edit_field19' => 'section6',
'text6' => 'section6',
'integrated_edit_field16' => 'section6',
'integrated_edit_field33' => 'section6',
'edit_field_label4' => 'section5',
'integrated_edit_field7' => 'section5',
'edit_field_label11' => 'section5',
'integrated_edit_field2' => 'section5',
'integrated_edit_field42' => 'section2',
'integrated_edit_field41' => 'section2',
'edit_field_label10' => 'section2',
'edit_field_label8' => 'section2',
'edit_field_label9' => 'section2',
'edit_field_label5' => 'section2',
'edit_field_label12' => 'section2',
'section4' => 'section2',
'section5' => 'section2',
'section1' => 'section2',
'section8' => 'section2',
'section6' => 'section2',
'section2' => 'section2',
'integrated_edit_field3' => 'section2',
'integrated_edit_field9' => 'section2',
'integrated_edit_field6' => 'section2',
'integrated_edit_field18' => 'section2',
'integrated_edit_field8' => 'section2',
'edit_field_label7' => 'section2',
'integrated_edit_field12' => 'section2',
'integrated_edit_field11' => 'section2',
'edit_field_label6' => 'section2',
'edit_field_label3' => 'section2',
'integrated_edit_field36' => 'section2',
'text5' => 'section2',
'callTimerText' => 'section2',
'agentStatus' => 'section2',
'edit_field_label25' => 'section2',
'edit_field_label26' => 'section2',
'integrated_edit_field1' => 'section2',
'integrated_edit_field' => 'section2',
'section11' => 'section2',
'text2' => 'section4',
'integrated_edit_field5' => 'section4',
'text4' => 'section4',
'integrated_edit_field28' => 'section4',
'integrated_edit_field4' => 'section4',
'text3' => 'section4',
'integrated_edit_field24' => 'section3',
'integrated_edit_field30' => 'section3',
'integrated_edit_field23' => 'section3',
'details_preview2' => 'section7',
'details_preview4' => 'section9',
'integrated_edit_field25' => 'section8',
'integrated_edit_field27' => 'section8',
'integrated_edit_field32' => 'section8',
'integrated_edit_field14' => 'section8',
'integrated_edit_field26' => 'section8',
'edit_field_label23' => 'section11',
'integrated_edit_field40' => 'section11',
'edit_field_label24' => 'section11',
'integrated_edit_field39' => 'section11',
'edit_field_label22' => 'section11',
'integrated_edit_field35' => 'section11',
'edit_field_label21' => 'section11',
'integrated_edit_field43' => 'section11',
'edit_field_label14' => 'section11',
'integrated_edit_field17' => 'section11',
'edit_field_label20' => 'section11',
'integrated_edit_field34' => 'section11',
'details_preview' => 'section10' ),
'itemLocations' => array( 'section3' => array( 'location' => 'grid',
'cellId' => 'c5' ),
'section9' => array( 'location' => 'grid',
'cellId' => 'c7' ),
'section' => array( 'location' => 'grid',
'cellId' => 'c8' ),
'section7' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'section10' => array( 'location' => 'grid',
'cellId' => 'c' ),
'integrated_edit_field22' => array( 'location' => 'section6',
'cellId' => 'c3' ),
'integrated_edit_field37' => array( 'location' => 'section6',
'cellId' => 'c25' ),
'integrated_edit_field38' => array( 'location' => 'section6',
'cellId' => 'c42' ),
'orderTotal' => array( 'location' => 'section6',
'cellId' => 'c43' ),
'details_preview1' => array( 'location' => 'section6',
'cellId' => 'c54' ),
'integrated_edit_field15' => array( 'location' => 'section6',
'cellId' => 'c31' ),
'integrated_edit_field20' => array( 'location' => 'section6',
'cellId' => 'c32' ),
'integrated_edit_field21' => array( 'location' => 'section6',
'cellId' => 'c32' ),
'integrated_edit_field10' => array( 'location' => 'section6',
'cellId' => 'c39' ),
'integrated_edit_field19' => array( 'location' => 'section6',
'cellId' => 'c58' ),
'text6' => array( 'location' => 'section6',
'cellId' => 'c61' ),
'integrated_edit_field16' => array( 'location' => 'section6',
'cellId' => 'c65' ),
'integrated_edit_field33' => array( 'location' => 'section6',
'cellId' => 'c67' ),
'edit_field_label4' => array( 'location' => 'section5',
'cellId' => 'c1' ),
'integrated_edit_field7' => array( 'location' => 'section5',
'cellId' => 'c' ),
'edit_field_label11' => array( 'location' => 'section5',
'cellId' => 'c8' ),
'integrated_edit_field2' => array( 'location' => 'section5',
'cellId' => 'c9' ),
'integrated_edit_field42' => array( 'location' => 'section2',
'cellId' => 'c12' ),
'integrated_edit_field41' => array( 'location' => 'section2',
'cellId' => 'c13' ),
'edit_field_label10' => array( 'location' => 'section2',
'cellId' => 'c6' ),
'edit_field_label8' => array( 'location' => 'section2',
'cellId' => 'c25' ),
'edit_field_label9' => array( 'location' => 'section2',
'cellId' => 'c54' ),
'edit_field_label5' => array( 'location' => 'section2',
'cellId' => 'c42' ),
'edit_field_label12' => array( 'location' => 'section2',
'cellId' => 'c45' ),
'section4' => array( 'location' => 'section2',
'cellId' => 'c64' ),
'section5' => array( 'location' => 'section2',
'cellId' => 'c64' ),
'section1' => array( 'location' => 'section2',
'cellId' => 'c64' ),
'section8' => array( 'location' => 'section2',
'cellId' => 'c64' ),
'section6' => array( 'location' => 'section2',
'cellId' => 'c64' ),
'section2' => array( 'location' => 'section2',
'cellId' => 'c64' ),
'integrated_edit_field3' => array( 'location' => 'section2',
'cellId' => 'c22' ),
'integrated_edit_field9' => array( 'location' => 'section2',
'cellId' => 'c76' ),
'integrated_edit_field6' => array( 'location' => 'section2',
'cellId' => 'c80' ),
'integrated_edit_field18' => array( 'location' => 'section2',
'cellId' => 'c87' ),
'integrated_edit_field8' => array( 'location' => 'section2',
'cellId' => 'c90' ),
'edit_field_label7' => array( 'location' => 'section2',
'cellId' => 'c120' ),
'integrated_edit_field12' => array( 'location' => 'section2',
'cellId' => 'c120' ),
'integrated_edit_field11' => array( 'location' => 'section2',
'cellId' => 'c121' ),
'edit_field_label6' => array( 'location' => 'section2',
'cellId' => 'c16' ),
'edit_field_label3' => array( 'location' => 'section2',
'cellId' => 'c112' ),
'integrated_edit_field36' => array( 'location' => 'section2',
'cellId' => 'c113' ),
'text5' => array( 'location' => 'section2',
'cellId' => 'c98' ),
'callTimerText' => array( 'location' => 'section2',
'cellId' => 'c98' ),
'agentStatus' => array( 'location' => 'section2',
'cellId' => 'c132' ),
'edit_field_label25' => array( 'location' => 'section2',
'cellId' => 'c135' ),
'edit_field_label26' => array( 'location' => 'section2',
'cellId' => 'c136' ),
'integrated_edit_field1' => array( 'location' => 'section2',
'cellId' => 'c139' ),
'integrated_edit_field' => array( 'location' => 'section2',
'cellId' => 'c20' ),
'section11' => array( 'location' => 'section2',
'cellId' => 'c145' ),
'text2' => array( 'location' => 'section4',
'cellId' => 'c3' ),
'integrated_edit_field5' => array( 'location' => 'section4',
'cellId' => 'c2' ),
'text4' => array( 'location' => 'section4',
'cellId' => 'c7' ),
'integrated_edit_field28' => array( 'location' => 'section4',
'cellId' => 'c8' ),
'integrated_edit_field4' => array( 'location' => 'section4',
'cellId' => 'c9' ),
'text3' => array( 'location' => 'section4',
'cellId' => 'c10' ),
'integrated_edit_field24' => array( 'location' => 'section3',
'cellId' => 'c' ),
'integrated_edit_field30' => array( 'location' => 'section3',
'cellId' => 'c1' ),
'integrated_edit_field23' => array( 'location' => 'section3',
'cellId' => 'c2' ),
'details_preview2' => array( 'location' => 'section7',
'cellId' => 'c' ),
'details_preview4' => array( 'location' => 'section9',
'cellId' => 'c1' ),
'integrated_edit_field25' => array( 'location' => 'section8',
'cellId' => 'c' ),
'integrated_edit_field27' => array( 'location' => 'section8',
'cellId' => 'c5' ),
'integrated_edit_field32' => array( 'location' => 'section8',
'cellId' => 'c6' ),
'integrated_edit_field14' => array( 'location' => 'section8',
'cellId' => 'c1' ),
'integrated_edit_field26' => array( 'location' => 'section8',
'cellId' => 'c2' ),
'edit_field_label23' => array( 'location' => 'section11',
'cellId' => 'c4' ),
'integrated_edit_field40' => array( 'location' => 'section11',
'cellId' => 'c5' ),
'edit_field_label24' => array( 'location' => 'section11',
'cellId' => 'c6' ),
'integrated_edit_field39' => array( 'location' => 'section11',
'cellId' => 'c7' ),
'edit_field_label22' => array( 'location' => 'section11',
'cellId' => 'c8' ),
'integrated_edit_field35' => array( 'location' => 'section11',
'cellId' => 'c9' ),
'edit_field_label21' => array( 'location' => 'section11',
'cellId' => 'c16' ),
'integrated_edit_field43' => array( 'location' => 'section11',
'cellId' => 'c17' ),
'edit_field_label14' => array( 'location' => 'section11',
'cellId' => 'c18' ),
'integrated_edit_field17' => array( 'location' => 'section11',
'cellId' => 'c19' ),
'edit_field_label20' => array( 'location' => 'section11',
'cellId' => 'c20' ),
'integrated_edit_field34' => array( 'location' => 'section11',
'cellId' => 'c21' ),
'details_preview' => array( 'location' => 'section10',
'cellId' => 'c1' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'view_header' => array( 'view_header' ),
'view_back_list' => array( 'view_back_list' ),
'view_close' => array( 'view_close' ),
'hamburger' => array( 'hamburger' ),
'details_preview' => array( 'details_preview',
'details_preview4',
'details_preview2',
'details_preview1' ),
'text' => array( 'text',
'orderTotal',
'text2',
'text4',
'text1',
'text3',
'agentStatus',
'callTimerText',
'text5',
'text6',
'text7',
'text8',
'text9',
'text10',
'text11' ),
'section' => array( 'section10',
'section9',
'section',
'section7',
'section4',
'section5',
'section1',
'section8',
'section6',
'section2',
'section11',
'section3' ),
'edit_field' => array( 'integrated_edit_field7',
'integrated_edit_field42',
'integrated_edit_field6',
'integrated_edit_field9',
'integrated_edit_field3',
'integrated_edit_field2',
'integrated_edit_field41',
'integrated_edit_field5',
'integrated_edit_field34',
'integrated_edit_field28',
'integrated_edit_field4',
'integrated_edit_field18',
'integrated_edit_field17',
'integrated_edit_field43',
'integrated_edit_field35',
'integrated_edit_field39',
'integrated_edit_field40',
'integrated_edit_field',
'integrated_edit_field36',
'integrated_edit_field11',
'integrated_edit_field12',
'integrated_edit_field8' ),
'view_edit' => array( 'view_edit' ),
'edit_field_label' => array( 'edit_field_label10',
'edit_field_label11',
'edit_field_label8',
'edit_field_label9',
'edit_field_label5',
'edit_field_label12',
'edit_field_label4',
'edit_field_label20',
'edit_field_label14',
'edit_field_label21',
'edit_field_label22',
'edit_field_label24',
'edit_field_label23',
'edit_field_label26',
'edit_field_label25',
'edit_field_label3',
'edit_field_label6',
'edit_field_label7' ),
'integrated_edit_field' => array( 'integrated_edit_field30',
'integrated_edit_field25',
'integrated_edit_field27',
'integrated_edit_field14',
'integrated_edit_field26',
'integrated_edit_field24',
'integrated_edit_field32',
'integrated_edit_field23',
'integrated_edit_field1',
'integrated_edit_field33',
'integrated_edit_field16',
'integrated_edit_field19',
'integrated_edit_field10',
'integrated_edit_field21',
'integrated_edit_field20',
'integrated_edit_field15',
'integrated_edit_field37',
'integrated_edit_field38',
'integrated_edit_field22' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c8' => array( 'cols' => array( 0,
1,
2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'section' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 0,
1,
2 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'section3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 0,
1,
2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'section10' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 0,
1,
2 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'section9' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 0,
1,
2 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'section7' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 0 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 1 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c9' => array( 'cols' => array( 2 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c10' => array( 'cols' => array( 0,
1,
2 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 3,
'height' => 7 ),
'section6' => array( 'cells' => array( 'c3' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c63' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c56' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c1' => array( 'cols' => array( 4 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 5 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c27' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c64' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c57' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c28' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c29' => array( 'cols' => array( 4 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 5 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c31' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field15' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c65' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field16' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c58' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field19' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c32' => array( 'cols' => array( 3 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field20',
'integrated_edit_field21' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c33' => array( 'cols' => array( 4 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 5 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c39' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field10' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c66' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c59' => array( 'cols' => array( 2 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c40' => array( 'cols' => array( 3 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c41' => array( 'cols' => array( 4 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c9' => array( 'cols' => array( 5 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c25' => array( 'cols' => array( 0 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c67' => array( 'cols' => array( 1 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field33' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c60' => array( 'cols' => array( 2 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c26' => array( 'cols' => array( 3 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c6' => array( 'cols' => array( 4 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c10' => array( 'cols' => array( 5 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c42' => array( 'cols' => array( 0 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c68' => array( 'cols' => array( 1 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c61' => array( 'cols' => array( 2 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'text6' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c43' => array( 'cols' => array( 3 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c7' => array( 'cols' => array( 4 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c11' => array( 'cols' => array( 5 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c54' => array( 'cols' => array( 0 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array( 'details_preview1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c69' => array( 'cols' => array( 1 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c62' => array( 'cols' => array( 2 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c55' => array( 'cols' => array( 3 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 4 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c12' => array( 'cols' => array( 5 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 6,
'height' => 7 ),
'section5' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array( 'callStatusId_fieldblock' ),
'items' => array( 'edit_field_label4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field7' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'callDenialReasonID_fieldblock' ),
'items' => array( 'edit_field_label11' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c9' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 0 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 1 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 5 ),
'section2' => array( 'cells' => array( 'c98' => array( 'cols' => array( 0,
1,
2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'text5',
'callTimerText' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c132' => array( 'cols' => array( 3,
4,
5,
6,
7 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c134' => array( 'cols' => array( 8 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c135' => array( 'cols' => array( 9 ),
'rows' => array( 0 ),
'tags' => array( 'callGdprRecordingAcceptance_fieldblock' ),
'items' => array( 'edit_field_label25' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c136' => array( 'cols' => array( 10 ),
'rows' => array( 0 ),
'tags' => array( 'callGdprAcceptance_fieldblock' ),
'items' => array( 'edit_field_label26' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 0,
1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c20' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c145' => array( 'cols' => array( 3,
4,
5,
6,
7 ),
'rows' => array( 1,
2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c30' => array( 'cols' => array( 8 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c12' => array( 'cols' => array( 9 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field42' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c13' => array( 'cols' => array( 10 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field41' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c112' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array( 'callStart_fieldblock' ),
'items' => array( 'edit_field_label3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c113' => array( 'cols' => array( 1,
2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field36' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c129' => array( 'cols' => array( 8 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c64' => array( 'cols' => array( 9,
10 ),
'rows' => array( 2,
3,
4,
5,
6 ),
'tags' => array(  ),
'items' => array( 'section4',
'section5',
'section1',
'section8',
'section6',
'section2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c45' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array( 'callClassificationID_fieldblock' ),
'items' => array( 'edit_field_label12' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c22' => array( 'cols' => array( 1,
2 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c90' => array( 'cols' => array( 3 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c139' => array( 'cols' => array( 4,
5,
6,
7 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c68' => array( 'cols' => array( 8 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c42' => array( 'cols' => array( 0 ),
'rows' => array( 4 ),
'tags' => array( 'remarks_fieldblock' ),
'items' => array( 'edit_field_label5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c76' => array( 'cols' => array( 1,
2,
3,
4,
5,
6,
7 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field9' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c44' => array( 'cols' => array( 8 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c16' => array( 'cols' => array( 0 ),
'rows' => array( 5 ),
'tags' => array( 'redialDate_fieldblock' ),
'items' => array( 'edit_field_label6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c121' => array( 'cols' => array( 1,
2 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field11' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c120' => array( 'cols' => array( 3,
4 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'edit_field_label7',
'integrated_edit_field12' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c122' => array( 'cols' => array( 5 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c123' => array( 'cols' => array( 6 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c130' => array( 'cols' => array( 7 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 8 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c25' => array( 'cols' => array( 0 ),
'rows' => array( 6 ),
'tags' => array( 'redialComments_fieldblock' ),
'items' => array( 'edit_field_label8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c80' => array( 'cols' => array( 1,
2,
3,
4,
5,
6,
7 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field6' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c36' => array( 'cols' => array( 8 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c54' => array( 'cols' => array( 0 ),
'rows' => array( 7 ),
'tags' => array( 'callComments_fieldblock' ),
'items' => array( 'edit_field_label9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c87' => array( 'cols' => array( 1,
2,
3,
4,
5,
6,
7 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field18' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c75' => array( 'cols' => array( 8 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c61' => array( 'cols' => array( 9,
10 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c51' => array( 'cols' => array( 0 ),
'rows' => array( 8 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c88' => array( 'cols' => array( 1,
2,
3,
4,
5,
6,
7 ),
'rows' => array( 8 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c53' => array( 'cols' => array( 8 ),
'rows' => array( 8 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c57' => array( 'cols' => array( 9,
10 ),
'rows' => array( 8 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 11,
'height' => 9 ),
'section4' => array( 'cells' => array( 'c3' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'text2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field5' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c10' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'text3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c9' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'text4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field28' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 3 ),
'section1' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section3' => array( 'cells' => array( 'c' => array( 'cols' => array( 0,
1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field24' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c1' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field30' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field23' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 2 ),
'section7' => array( 'cells' => array( 'c' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'details_preview2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section9' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'details_preview4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section8' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field14' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field26' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field25' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field27' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 0,
1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field32' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 3 ),
'section11' => array( 'cells' => array( 'c20' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array( 'contactName_fieldblock' ),
'items' => array( 'edit_field_label20' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c21' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field34' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c22' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c23' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c16' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'contactGender_fieldblock' ),
'items' => array( 'edit_field_label21' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c17' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field43' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c18' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array( 'contactAge_fieldblock' ),
'items' => array( 'edit_field_label14' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c19' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field17' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array( 'contactZipCode_fieldblock' ),
'items' => array( 'edit_field_label22' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c9' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field35' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c10' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c11' => array( 'cols' => array( 3 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array( 'ContactArea_fieldblock' ),
'items' => array( 'edit_field_label23' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field40' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 2 ),
'rows' => array( 3 ),
'tags' => array( 'contactCity_fieldblock' ),
'items' => array( 'edit_field_label24' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 3 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field39' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 4,
'height' => 4 ),
'section10' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'details_preview' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'view',
'breadcrumb' => false,
'nextPrev' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'view',
'type' => 'view',
'layoutId' => 'nomenu',
'disabled' => 0,
'default' => 0,
'forms' => array( 'top' => array( 'modelId' => 'view-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'view_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'view-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1',
'colspan' => 2 ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'text',
'text1',
'text7',
'text8',
'text9',
'text10',
'text11' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'view-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'view_back_list',
'view_close' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'hamburger' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c8',
'colspan' => 3 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c5',
'colspan' => 3 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c',
'colspan' => 3 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c7',
'colspan' => 3 ) ) ),
array( 'cells' => array( array( 'cell' => 'c3',
'colspan' => 3 ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c4' ),
array( 'cell' => 'c6' ),
array( 'cell' => 'c9' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c10',
'colspan' => 3 ) ),
'section' => '' ) ),
'cells' => array( 'c5' => array( 'model' => 'c3',
'items' => array( 'section3' ),
'width' => '80%' ),
'c7' => array( 'model' => 'c3',
'items' => array( 'section9' ),
'align' => 'left',
'background' => '#0090ff' ),
'c8' => array( 'model' => 'c3',
'items' => array( 'section' ),
'background' => '#ffe6ad' ),
'c3' => array( 'model' => 'c3',
'items' => array( 'section7' ),
'background' => '#d1ffd8' ),
'c' => array( 'model' => 'c3',
'items' => array( 'section10' ) ),
'c4' => array( 'model' => 'c3',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c6' => array( 'model' => 'c3',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c9' => array( 'model' => 'c3',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c10' => array( 'model' => 'c3',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'columnCount' => 3,
'inlineLabels' => true,
'separateLabels' => false ),
'section6' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c3' ),
array( 'cell' => 'c63' ),
array( 'cell' => 'c56' ),
array( 'cell' => 'c' ),
array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c27' ),
array( 'cell' => 'c64' ),
array( 'cell' => 'c57' ),
array( 'cell' => 'c28' ),
array( 'cell' => 'c29' ),
array( 'cell' => 'c4' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c31' ),
array( 'cell' => 'c65' ),
array( 'cell' => 'c58' ),
array( 'cell' => 'c32' ),
array( 'cell' => 'c33' ),
array( 'cell' => 'c8' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c39' ),
array( 'cell' => 'c66' ),
array( 'cell' => 'c59' ),
array( 'cell' => 'c40' ),
array( 'cell' => 'c41' ),
array( 'cell' => 'c9' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c25' ),
array( 'cell' => 'c67' ),
array( 'cell' => 'c60' ),
array( 'cell' => 'c26' ),
array( 'cell' => 'c6' ),
array( 'cell' => 'c10' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c42' ),
array( 'cell' => 'c68' ),
array( 'cell' => 'c61' ),
array( 'cell' => 'c43' ),
array( 'cell' => 'c7' ),
array( 'cell' => 'c11' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c54' ),
array( 'cell' => 'c69' ),
array( 'cell' => 'c62' ),
array( 'cell' => 'c55' ),
array( 'cell' => 'c5' ),
array( 'cell' => 'c12' ) ) ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field22' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'orientation' => 'vertical',
'width' => '100px',
'background' => '#fff3e2',
'persistent' => true ),
'c' => array( 'model' => 'c3',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'orientation' => 'vertical',
'width' => '100px',
'background' => '#fff3e2',
'persistent' => true ),
'c5' => array( 'model' => 'c3',
'items' => array(  ),
'background' => '#fff3e2' ),
'c25' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field37' ),
'orientation' => 'vertical',
'width' => '100px',
'background' => '#fff3e2',
'persistent' => true ),
'c26' => array( 'model' => 'c3',
'items' => array(  ),
'orientation' => 'vertical',
'width' => '100px',
'background' => '#fff3e2',
'persistent' => true ),
'c42' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field38' ),
'width' => '100px',
'background' => '#fff3e2',
'persistent' => true ),
'c43' => array( 'model' => 'c3',
'items' => array( 'orderTotal' ),
'width' => '100px',
'background' => '#fff3e2',
'persistent' => true,
'align' => 'left' ),
'c54' => array( 'model' => 'c3',
'items' => array( 'details_preview1' ),
'width' => '150px',
'background' => '#fff3e2',
'padding' => array( 'top' => '10px' ) ),
'c1' => array( 'model' => 'c3',
'items' => array(  ),
'background' => '#fff3e2' ),
'c6' => array( 'model' => 'c2',
'items' => array(  ),
'background' => '#fff3e2' ),
'c7' => array( 'model' => 'c3',
'items' => array(  ),
'background' => '#fff3e2' ),
'c8' => array( 'model' => 'c2',
'items' => array(  ) ),
'c9' => array( 'model' => 'c3',
'items' => array(  ) ),
'c10' => array( 'model' => 'c2',
'items' => array(  ) ),
'c11' => array( 'model' => 'c3',
'items' => array(  ) ),
'c27' => array( 'model' => 'c3',
'items' => array(  ),
'background' => '#fff3e2' ),
'c28' => array( 'model' => 'c3',
'items' => array(  ),
'background' => '#fff3e2' ),
'c29' => array( 'model' => 'c2',
'items' => array(  ),
'background' => '#fff3e2' ),
'c31' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field15' ),
'background' => '#fff3e2' ),
'c32' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field20',
'integrated_edit_field21' ),
'background' => '#fff3e2' ),
'c33' => array( 'model' => 'c2',
'items' => array(  ),
'background' => '#fff3e2',
'orientation' => 'vertical' ),
'c39' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field10' ),
'background' => '#fff3e2' ),
'c2' => array( 'model' => 'c3',
'items' => array(  ) ),
'c4' => array( 'model' => 'c2',
'items' => array(  ) ),
'c12' => array( 'model' => 'c3',
'items' => array(  ) ),
'c40' => array( 'model' => 'c3',
'items' => array(  ),
'background' => '#fff3e2' ),
'c41' => array( 'model' => 'c3',
'items' => array(  ),
'background' => '#fff3e2' ),
'c55' => array( 'model' => 'c3',
'items' => array(  ),
'width' => '150px',
'background' => '#fff3e2',
'padding' => array( 'top' => '10px' ) ),
'c56' => array( 'model' => 'c3',
'items' => array(  ) ),
'c57' => array( 'model' => 'c3',
'items' => array(  ) ),
'c58' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field19' ) ),
'c59' => array( 'model' => 'c3',
'items' => array(  ) ),
'c60' => array( 'model' => 'c3',
'items' => array(  ) ),
'c61' => array( 'model' => 'c3',
'items' => array( 'text6' ),
'align' => 'right' ),
'c62' => array( 'model' => 'c3',
'items' => array(  ) ),
'c63' => array( 'model' => 'c3',
'items' => array(  ) ),
'c64' => array( 'model' => 'c3',
'items' => array(  ) ),
'c65' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field16' ) ),
'c66' => array( 'model' => 'c3',
'items' => array(  ) ),
'c67' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field33' ) ),
'c68' => array( 'model' => 'c3',
'items' => array(  ) ),
'c69' => array( 'model' => 'c3',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'columnCount' => 4,
'inlineLabels' => false,
'separateLabels' => false ),
'section5' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c8' ),
array( 'cell' => 'c9' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c6' ),
array( 'cell' => 'c7' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c4' ),
array( 'cell' => 'c5' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2' ),
array( 'cell' => 'c3' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_field_label4' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field7' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c1',
'items' => array(  ) ),
'c3' => array( 'model' => 'c1',
'items' => array(  ) ),
'c4' => array( 'model' => 'c1',
'items' => array(  ) ),
'c5' => array( 'model' => 'c1',
'items' => array(  ) ),
'c6' => array( 'model' => 'c1',
'items' => array(  ) ),
'c7' => array( 'model' => 'c1',
'items' => array(  ) ),
'c8' => array( 'model' => 'c1',
'items' => array( 'edit_field_label11' ) ),
'c9' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field2' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section2' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c98',
'colspan' => 3 ),
array( 'cell' => 'c132',
'colspan' => 5 ),
array( 'cell' => 'c134' ),
array( 'cell' => 'c135' ),
array( 'cell' => 'c136',
'colspan' => 1 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c6',
'rowspan' => 1,
'colspan' => 2 ),
array( 'cell' => 'c20' ),
array( 'cell' => 'c145',
'colspan' => 5,
'rowspan' => 2 ),
array( 'cell' => 'c30',
'colspan' => 1,
'rowspan' => 1 ),
array( 'cell' => 'c12' ),
array( 'cell' => 'c13',
'rowspan' => 1,
'colspan' => 1 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c112' ),
array( 'cell' => 'c113',
'colspan' => 2 ),
array( 'cell' => 'c129' ),
array( 'cell' => 'c64',
'colspan' => 2,
'rowspan' => 5 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c45' ),
array( 'cell' => 'c22',
'colspan' => 2 ),
array( 'cell' => 'c90' ),
array( 'cell' => 'c139',
'colspan' => 4 ),
array( 'cell' => 'c68',
'colspan' => 1 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c42' ),
array( 'cell' => 'c76',
'colspan' => 7 ),
array( 'cell' => 'c44',
'colspan' => 1 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c16' ),
array( 'cell' => 'c121',
'colspan' => 2 ),
array( 'cell' => 'c120',
'colspan' => 2 ),
array( 'cell' => 'c122' ),
array( 'cell' => 'c123' ),
array( 'cell' => 'c130',
'colspan' => 1 ),
array( 'cell' => 'c' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c25' ),
array( 'cell' => 'c80',
'colspan' => 7 ),
array( 'cell' => 'c36',
'colspan' => 1 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c54' ),
array( 'cell' => 'c87',
'colspan' => 7 ),
array( 'cell' => 'c75' ),
array( 'cell' => 'c61',
'colspan' => 2 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c51' ),
array( 'cell' => 'c88',
'colspan' => 7 ),
array( 'cell' => 'c53' ),
array( 'cell' => 'c57',
'colspan' => 2 ) ) ) ),
'cells' => array( 'c12' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field42' ),
'background' => '#fffee4',
'orientation' => 'horizontal',
'width' => '145px' ),
'c13' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field41' ),
'background' => '#fffee4',
'color' => '#ff0000',
'orientation' => 'horizontal',
'width' => '130px' ),
'c6' => array( 'model' => 'c2',
'items' => array( 'edit_field_label10' ),
'width' => '150px',
'persistent' => true,
'align' => 'right',
'background' => '#f6fcff',
'orientation' => 'vertical' ),
'c36' => array( 'model' => 'c2',
'items' => array(  ),
'align' => 'right',
'background' => '#f6fcff' ),
'c25' => array( 'model' => 'c1',
'items' => array( 'edit_field_label8' ),
'align' => 'right',
'background' => '#f6fcff' ),
'c51' => array( 'model' => 'c1',
'items' => array(  ),
'align' => 'right',
'background' => '#f6fcff' ),
'c53' => array( 'model' => 'c2',
'items' => array(  ),
'background' => '#f6fcff' ),
'c54' => array( 'model' => 'c1',
'items' => array( 'edit_field_label9' ),
'background' => '#f6fcff',
'align' => 'right' ),
'c57' => array( 'model' => 'c1',
'items' => array(  ) ),
'c61' => array( 'model' => 'c1',
'items' => array(  ) ),
'c30' => array( 'model' => 'c2',
'items' => array(  ),
'width' => '30px',
'persistent' => true,
'align' => 'right',
'background' => '#f6fcff',
'orientation' => 'vertical' ),
'c42' => array( 'model' => 'c1',
'items' => array( 'edit_field_label5' ),
'align' => 'right',
'background' => '#f6fcff' ),
'c44' => array( 'model' => 'c2',
'items' => array(  ),
'align' => 'right',
'background' => '#f6fcff' ),
'c45' => array( 'model' => 'c1',
'items' => array( 'edit_field_label12' ),
'align' => 'right',
'background' => '#f6fcff' ),
'c64' => array( 'model' => 'c1',
'items' => array( 'section4',
'section5',
'section1',
'section8',
'section6',
'section2' ) ),
'c68' => array( 'model' => 'c2',
'items' => array(  ),
'align' => 'right',
'background' => '#f6fcff' ),
'c75' => array( 'model' => 'c3',
'items' => array(  ),
'background' => '#f6fcff' ),
'c22' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field3' ),
'background' => '#f6fcff' ),
'c76' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field9' ),
'background' => '#f6fcff' ),
'c80' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field6' ),
'background' => '#f6fcff' ),
'c87' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field18' ),
'background' => '#f6fcff' ),
'c88' => array( 'model' => 'c2',
'items' => array(  ),
'background' => '#f6fcff' ),
'c90' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field8' ),
'background' => '#f6fcff',
'persistent' => true ),
'c' => array( 'model' => 'c2',
'items' => array(  ),
'align' => 'right',
'nowrap' => true,
'background' => '#f6fcff' ),
'c120' => array( 'model' => 'c2',
'items' => array( 'edit_field_label7',
'integrated_edit_field12' ),
'background' => '#f6fcff',
'align' => 'left' ),
'c121' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field11' ),
'background' => '#f6fcff' ),
'c16' => array( 'model' => 'c1',
'items' => array( 'edit_field_label6' ),
'align' => 'right',
'background' => '#f6fcff' ),
'c112' => array( 'model' => 'c1',
'items' => array( 'edit_field_label3' ),
'align' => 'right',
'background' => '#f6fcff' ),
'c113' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field36' ),
'background' => '#f6fcff' ),
'c129' => array( 'model' => 'c2',
'items' => array(  ),
'background' => '#f6fcff' ),
'c130' => array( 'model' => 'c2',
'items' => array(  ),
'background' => '#f6fcff',
'align' => 'left' ),
'c98' => array( 'model' => 'c1',
'items' => array( 'text5',
'callTimerText' ),
'background' => '#f9ff36',
'width' => '100px',
'align' => 'center',
'orientation' => 'horizontal',
'bold' => true,
'font-size' => '14px' ),
'c132' => array( 'model' => 'c1',
'items' => array( 'agentStatus' ),
'align' => 'center',
'width' => '300px',
'persistent' => true,
'background' => '#f9ff36',
'orientation' => 'horizontal',
'bold' => true,
'font-size' => '14px' ),
'c134' => array( 'model' => 'c2',
'items' => array(  ),
'background' => '#f6fcff' ),
'c135' => array( 'model' => 'c3',
'items' => array( 'edit_field_label25' ),
'background' => '#fffee4' ),
'c136' => array( 'model' => 'c3',
'items' => array( 'edit_field_label26' ),
'background' => '#fffee4' ),
'c139' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field1' ),
'align' => 'left',
'background' => '#f6fcff',
'persistent' => true ),
'c20' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field' ),
'width' => '150px',
'persistent' => true,
'align' => 'left',
'background' => '#f6fcff',
'orientation' => 'vertical' ),
'c123' => array( 'model' => 'c2',
'items' => array(  ),
'background' => '#f6fcff',
'align' => 'left',
'padding' => array( 'top' => '-12px' ) ),
'c145' => array( 'model' => 'c1',
'items' => array( 'section11' ),
'align' => 'center',
'color' => '#0b04d1',
'persistent' => true,
'background' => '#f6fcff',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'c122' => array( 'model' => 'c2',
'items' => array(  ),
'background' => '#f6fcff',
'align' => 'left',
'padding' => array( 'top' => '-15px' ),
'orientation' => 'horizontal',
'nowrap' => true ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section4' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c3' ),
array( 'cell' => 'c2' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c10' ),
array( 'cell' => 'c9' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c7' ),
array( 'cell' => 'c8' ) ) ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array( 'text2' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'width' => '30%',
'background' => '#effffe' ),
'c2' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field5' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'orientation' => 'vertical',
'background' => '#effffe' ),
'c7' => array( 'model' => 'c3',
'items' => array( 'text4' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'width' => '30%',
'background' => '#effffe' ),
'c8' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field28' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'orientation' => 'vertical',
'background' => '#effffe' ),
'c9' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field4' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'orientation' => 'vertical',
'background' => '#effffe' ),
'c10' => array( 'model' => 'c3',
'items' => array( 'text3' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'width' => '30%',
'background' => '#effffe' ) ),
'deferredItems' => array(  ),
'columnCount' => 2,
'inlineLabels' => false,
'separateLabels' => false ),
'section1' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'background' => '#effffe' ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'background' => '#effffe' ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section3' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c',
'colspan' => 2 ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ) ) ),
'cells' => array( 'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field24' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'width' => '25%',
'background' => '#effffe' ),
'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field30' ),
'width' => '12%',
'background' => '#effffe' ),
'c2' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field23' ),
'width' => '13%',
'background' => '#effffe' ) ),
'deferredItems' => array(  ),
'columnCount' => 2,
'inlineLabels' => false,
'separateLabels' => false ),
'section7' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ) ) ) ),
'cells' => array( 'c' => array( 'model' => 'c1',
'items' => array( 'details_preview2' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section9' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'details_preview4' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section8' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ) ),
array( 'cells' => array( array( 'cell' => 'c' ),
array( 'cell' => 'c5' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c6',
'colspan' => 2 ) ) ) ),
'cells' => array( 'c' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field25' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'background' => '#effffe' ),
'c5' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field27' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'background' => '#effffe' ),
'c6' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field32' ),
'align' => 'center',
'background' => '#eff8ff' ),
'c1' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field14' ),
'background' => '#effffe' ),
'c2' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field26' ),
'background' => '#effffe' ) ),
'deferredItems' => array(  ),
'columnCount' => 4,
'inlineLabels' => false,
'separateLabels' => false ),
'section11' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c20' ),
array( 'cell' => 'c21' ),
array( 'cell' => 'c22' ),
array( 'cell' => 'c23' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c16' ),
array( 'cell' => 'c17' ),
array( 'cell' => 'c18' ),
array( 'cell' => 'c19' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c8' ),
array( 'cell' => 'c9' ),
array( 'cell' => 'c10' ),
array( 'cell' => 'c11' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c4' ),
array( 'cell' => 'c5' ),
array( 'cell' => 'c6' ),
array( 'cell' => 'c7' ) ) ) ),
'cells' => array( 'c4' => array( 'model' => 'c1',
'items' => array( 'edit_field_label23' ),
'align' => 'right' ),
'c5' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field40' ),
'align' => 'left' ),
'c6' => array( 'model' => 'c1',
'items' => array( 'edit_field_label24' ),
'align' => 'right' ),
'c7' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field39' ),
'align' => 'left' ),
'c8' => array( 'model' => 'c1',
'items' => array( 'edit_field_label22' ),
'align' => 'right' ),
'c9' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field35' ),
'align' => 'left' ),
'c10' => array( 'model' => 'c1',
'items' => array(  ),
'align' => 'right' ),
'c11' => array( 'model' => 'c1',
'items' => array(  ),
'align' => 'left' ),
'c16' => array( 'model' => 'c1',
'items' => array( 'edit_field_label21' ),
'align' => 'right' ),
'c17' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field43' ),
'align' => 'left' ),
'c18' => array( 'model' => 'c1',
'items' => array( 'edit_field_label14' ),
'align' => 'right' ),
'c19' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field17' ),
'align' => 'left' ),
'c20' => array( 'model' => 'c1',
'items' => array( 'edit_field_label20' ),
'align' => 'right' ),
'c21' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field34' ),
'align' => 'left' ),
'c22' => array( 'model' => 'c1',
'items' => array(  ),
'align' => 'right' ),
'c23' => array( 'model' => 'c1',
'items' => array(  ),
'align' => 'left' ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section10' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'details_preview' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'view_header' => array( 'type' => 'view_header',
'title' => array( 'page' => 'view',
'table' => 'dbo.Calls',
'type' => 7 ) ),
'view_back_list' => array( 'type' => 'view_back_list' ),
'view_close' => array( 'type' => 'view_close' ),
'hamburger' => array( 'type' => 'hamburger',
'items' => array( 'view_edit' ) ),
'details_preview' => array( 'type' => 'details_preview',
'table' => 'dbo.voltonApplications',
'items' => array(  ),
'popup' => false,
'pageId' => 'voltonInDetailAddList',
'mobileDisplay' => 'both' ),
'text' => array( 'type' => 'text',
'label' => array( 'text' => 'Τηλέφωνο',
'type' => 0 ),
'editedByRte' => false,
'color' => '#e11717' ),
'section10' => array( 'type' => 'section',
'title' => array( 'text' => 'Αιτήσεις Volton',
'type' => 0 ),
'location' => 'section10',
'initiallyClosed' => true ),
'section9' => array( 'type' => 'section',
'title' => array( 'text' => 'Αιτήσεις Nova',
'type' => 0 ),
'location' => 'section9',
'initiallyClosed' => true ),
'details_preview4' => array( 'type' => 'details_preview',
'table' => 'dbo.novaApplications',
'items' => array(  ),
'popup' => false,
'pageId' => 'novaInlineAddList' ),
'section' => array( 'type' => 'section',
'title' => array( 'text' => 'Στοιχεία Κλήσης',
'type' => 0 ),
'location' => 'section2',
'mobileDisplay' => '' ),
'details_preview2' => array( 'type' => 'details_preview',
'table' => 'dbo.internalComments',
'items' => array(  ),
'popup' => false,
'pageId' => 'list' ),
'section7' => array( 'type' => 'section',
'title' => array( 'text' => 'Εσωτερική Επικοινωνία',
'type' => 0 ),
'location' => 'section7',
'initiallyClosed' => true ),
'integrated_edit_field7' => array( 'field' => 'callStatusId',
'type' => 'edit_field',
'orientation' => 1,
'label' => array( 'field' => 'callStatusId',
'table' => 'dbo.Calls',
'type' => 3 ),
'joined' => false,
'separated' => true ),
'integrated_edit_field42' => array( 'field' => 'callGdprRecordingAcceptance',
'type' => 'edit_field',
'orientation' => 0,
'nowrap' => true,
'label' => array( 'field' => 'callGdprRecordingAcceptance',
'table' => 'dbo.Calls',
'type' => 3 ),
'joined' => false,
'separated' => true ),
'integrated_edit_field6' => array( 'field' => 'redialComments',
'type' => 'edit_field',
'orientation' => 1,
'nowrap' => false,
'joined' => false,
'separated' => true,
'width' => '100%' ),
'integrated_edit_field9' => array( 'field' => 'remarks',
'type' => 'edit_field',
'orientation' => 1,
'label' => array( 'field' => 'remarks',
'table' => 'dbo.Calls',
'type' => 3 ),
'joined' => false,
'separated' => true ),
'integrated_edit_field3' => array( 'field' => 'callClassificationID',
'type' => 'edit_field',
'orientation' => 1,
'label' => array( 'field' => 'callClassificationID',
'table' => 'dbo.Calls',
'type' => 3 ),
'joined' => false,
'separated' => true ),
'view_edit' => array( 'type' => 'view_edit' ),
'integrated_edit_field2' => array( 'field' => 'callDenialReasonID',
'type' => 'edit_field',
'orientation' => 1,
'joined' => false,
'separated' => true,
'color' => '#ff0505' ),
'details_preview1' => array( 'type' => 'details_preview',
'table' => 'dbo.orderItems',
'items' => array(  ),
'popup' => false,
'pageId' => 'list',
'background' => '#edffcd' ),
'integrated_edit_field41' => array( 'field' => 'callGdprAcceptance',
'type' => 'edit_field',
'orientation' => 0,
'joined' => false,
'separated' => true,
'nowrap' => true ),
'edit_field_label10' => array( 'type' => 'edit_field_label',
'field' => 'dialerPhone',
'separated' => true ),
'edit_field_label11' => array( 'type' => 'edit_field_label',
'field' => 'callDenialReasonID',
'separated' => true,
'color' => '#ff0505' ),
'integrated_edit_field30' => array( 'field' => 'dialerLeadID',
'type' => 'integrated_edit_field',
'orientation' => 1,
'joined' => true,
'separated' => false ),
'edit_field_label8' => array( 'type' => 'edit_field_label',
'field' => 'redialComments',
'separated' => true ),
'edit_field_label9' => array( 'type' => 'edit_field_label',
'field' => 'callComments',
'separated' => true ),
'edit_field_label5' => array( 'type' => 'edit_field_label',
'field' => 'remarks',
'separated' => true,
'label' => array( 'field' => 'remarks',
'table' => 'dbo.Calls',
'type' => 3 ) ),
'edit_field_label12' => array( 'type' => 'edit_field_label',
'field' => 'callClassificationID',
'separated' => true ),
'section4' => array( 'type' => 'section',
'title' => array( 'text' => 'Εικόνα Πελάτη',
'type' => 0 ),
'location' => 'section',
'initiallyClosed' => true ),
'section5' => array( 'type' => 'section',
'title' => array( 'text' => 'Αγορές Πελάτη',
'type' => 0 ),
'location' => 'section1',
'initiallyClosed' => true ),
'section1' => array( 'type' => 'section',
'title' => array( 'text' => 'Πληροφορίες Κλήσης',
'type' => 0 ),
'location' => 'section4',
'initiallyClosed' => true ),
'orderTotal' => array( 'type' => 'text',
'label' => array( 'text' => '0',
'type' => 0 ),
'editedByRte' => false,
'padding' => array( 'left' => '5px' ),
'bold' => true,
'font-size' => '16px',
'color' => '#c00909' ),
'text2' => array( 'type' => 'text',
'label' => array( 'text' => 'Κανάλι',
'type' => 0 ),
'editedByRte' => false ),
'integrated_edit_field5' => array( 'field' => 'tvchannel',
'type' => 'edit_field',
'orientation' => 0,
'nowrap' => true,
'joined' => false,
'separated' => true ),
'integrated_edit_field34' => array( 'field' => 'contactName',
'type' => 'edit_field',
'orientation' => 1,
'joined' => false,
'separated' => true,
'padding' => array( 'top' => '5px' ),
'color' => '#0b04d1' ),
'text4' => array( 'type' => 'text',
'label' => array( 'text' => 'Πωλητής',
'type' => 0 ),
'editedByRte' => false ),
'integrated_edit_field28' => array( 'field' => 'seller',
'type' => 'edit_field',
'orientation' => 0,
'joined' => false,
'separated' => true ),
'integrated_edit_field4' => array( 'field' => 'broadcast',
'type' => 'edit_field',
'orientation' => 0,
'nowrap' => true,
'joined' => false,
'separated' => true ),
'text1' => array( 'type' => 'text',
'label' => array( 'text' => 'Επανάκληση',
'type' => 0 ),
'editedByRte' => false,
'padding' => array( 'top' => '15px' ),
'bold' => true ),
'text3' => array( 'type' => 'text',
'label' => array( 'text' => 'Εκπομπή',
'type' => 0 ),
'editedByRte' => false ),
'section8' => array( 'type' => 'section',
'title' => array( 'text' => 'Χρόνοι',
'type' => 0 ),
'location' => 'section8',
'initiallyClosed' => true ),
'integrated_edit_field25' => array( 'field' => 'callEnd',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field27' => array( 'field' => 'typingTime',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field14' => array( 'field' => 'callHangup',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field26' => array( 'field' => 'talkTime',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'section6' => array( 'type' => 'section',
'title' => array( 'text' => 'Dialer Data',
'type' => 0 ),
'location' => 'section3',
'initiallyClosed' => true ),
'integrated_edit_field24' => array( 'field' => 'dialerRecording',
'type' => 'integrated_edit_field',
'orientation' => 0,
'joined' => true,
'separated' => false,
'nowrap' => false ),
'integrated_edit_field32' => array( 'field' => 'totalCallTime',
'type' => 'integrated_edit_field',
'orientation' => 0,
'bold' => true ),
'integrated_edit_field23' => array( 'field' => 'dialerCallEpoch',
'type' => 'integrated_edit_field',
'orientation' => 1,
'joined' => true,
'separated' => false ),
'section2' => array( 'type' => 'section',
'title' => array( 'text' => 'Call Results',
'type' => 0 ),
'location' => 'section5',
'initiallyClosed' => true ),
'edit_field_label4' => array( 'type' => 'edit_field_label',
'field' => 'callStatusId',
'separated' => true ),
'edit_field_label20' => array( 'type' => 'edit_field_label',
'field' => 'contactName',
'separated' => true,
'padding' => array( 'top' => '10px' ) ),
'integrated_edit_field18' => array( 'field' => 'callComments',
'type' => 'edit_field',
'orientation' => 1,
'nowrap' => false,
'joined' => false,
'separated' => true ),
'integrated_edit_field17' => array( 'field' => 'contactAge',
'type' => 'edit_field',
'orientation' => 1,
'joined' => false,
'separated' => true,
'color' => '#0b04d1' ),
'edit_field_label14' => array( 'type' => 'edit_field_label',
'field' => 'contactAge',
'separated' => true,
'label' => array( 'field' => 'contactAge',
'table' => 'dbo.Calls',
'type' => 3 ) ),
'integrated_edit_field43' => array( 'field' => 'contactGender',
'type' => 'edit_field',
'orientation' => 1,
'joined' => false,
'separated' => true,
'color' => '#0b04d1' ),
'edit_field_label21' => array( 'type' => 'edit_field_label',
'field' => 'contactGender',
'separated' => true ),
'integrated_edit_field35' => array( 'field' => 'contactZipCode',
'type' => 'edit_field',
'orientation' => 1,
'joined' => false,
'separated' => true,
'color' => '#0b04d1' ),
'edit_field_label22' => array( 'type' => 'edit_field_label',
'field' => 'contactZipCode',
'separated' => true ),
'integrated_edit_field39' => array( 'field' => 'contactCity',
'type' => 'edit_field',
'orientation' => 1,
'joined' => false,
'separated' => true,
'color' => '#0b04d1' ),
'edit_field_label24' => array( 'type' => 'edit_field_label',
'field' => 'contactCity',
'separated' => true ),
'integrated_edit_field40' => array( 'field' => 'ContactArea',
'type' => 'edit_field',
'orientation' => 1,
'joined' => false,
'separated' => true,
'color' => '#0b04d1' ),
'edit_field_label23' => array( 'type' => 'edit_field_label',
'field' => 'ContactArea',
'separated' => true ),
'section11' => array( 'type' => 'section',
'title' => array( 'text' => 'Συλλογή Στοιχείων Επαφής',
'type' => 0 ),
'location' => 'section11',
'mobileDisplay' => '',
'padding' => array( 'top' => '5px' ) ),
'integrated_edit_field' => array( 'field' => 'dialerPhone',
'type' => 'edit_field',
'orientation' => 1,
'label' => array( 'field' => 'dialerPhone',
'table' => 'dbo.Calls',
'type' => 3 ),
'joined' => false,
'separated' => true,
'padding' => array( 'top' => '5px' ) ),
'integrated_edit_field1' => array( 'field' => 'productFamilyId',
'type' => 'integrated_edit_field',
'orientation' => 1,
'joined' => true,
'separated' => false,
'nowrap' => true ),
'edit_field_label26' => array( 'type' => 'edit_field_label',
'field' => 'callGdprAcceptance',
'separated' => true ),
'edit_field_label25' => array( 'type' => 'edit_field_label',
'field' => 'callGdprRecordingAcceptance',
'separated' => true ),
'agentStatus' => array( 'type' => 'text',
'label' => array( 'text' => 'agentStatus',
'type' => 0 ),
'editedByRte' => false,
'bold' => true ),
'callTimerText' => array( 'type' => 'text',
'editedByRte' => false,
'bold' => true,
'padding' => array( 'top' => '5px' ) ),
'text5' => array( 'type' => 'text',
'label' => array( 'text' => 'Χρονόμετρο Κλήσης: ',
'type' => 0 ),
'editedByRte' => false,
'bold' => true,
'padding' => array( 'top' => '5px' ) ),
'integrated_edit_field36' => array( 'field' => 'callStart',
'type' => 'edit_field',
'orientation' => 1,
'joined' => false,
'separated' => true,
'padding' => array( 'top' => '5px' ) ),
'edit_field_label3' => array( 'type' => 'edit_field_label',
'field' => 'callStart',
'separated' => true ),
'edit_field_label6' => array( 'type' => 'edit_field_label',
'field' => 'redialDate',
'separated' => true ),
'integrated_edit_field11' => array( 'field' => 'redialDate',
'type' => 'edit_field',
'orientation' => 1,
'nowrap' => true,
'joined' => false,
'separated' => true ),
'integrated_edit_field12' => array( 'field' => 'redialIsPrivate',
'type' => 'edit_field',
'orientation' => 1,
'joined' => false,
'separated' => true,
'padding' => array( 'top' => '-5px',
'left' => '15px' ) ),
'edit_field_label7' => array( 'type' => 'edit_field_label',
'field' => 'redialIsPrivate',
'separated' => true,
'padding' => array( 'top' => '-5px' ) ),
'integrated_edit_field8' => array( 'field' => 'callSubClassificationID',
'type' => 'edit_field',
'orientation' => 1,
'label' => array( 'field' => 'callSubClassificationID',
'table' => 'dbo.Calls',
'type' => 3 ),
'joined' => false,
'separated' => true ),
'integrated_edit_field33' => array( 'field' => 'orderPaymentMethod',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field16' => array( 'field' => 'courier',
'type' => 'integrated_edit_field',
'orientation' => 0,
'joined' => true,
'separated' => false ),
'text6' => array( 'type' => 'text',
'label' => array( 'text' => 'Συνολική Αξία: ',
'type' => 0 ),
'editedByRte' => false,
'bold' => true,
'font-size' => '16px',
'color' => '#c00909' ),
'integrated_edit_field19' => array( 'field' => 'courierDeliveryDate',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field10' => array( 'field' => 'deliveryComments',
'type' => 'integrated_edit_field',
'orientation' => 0,
'joined' => true,
'separated' => false ),
'integrated_edit_field21' => array( 'field' => 'courierTimeTo',
'type' => 'integrated_edit_field',
'orientation' => 1,
'joined' => true,
'separated' => false ),
'integrated_edit_field20' => array( 'field' => 'courierTimeFrom',
'type' => 'integrated_edit_field',
'orientation' => 1,
'joined' => true,
'separated' => false ),
'integrated_edit_field15' => array( 'field' => 'contactMethod',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'contactMethod',
'table' => 'dbo.Calls',
'type' => 3 ),
'joined' => true,
'separated' => false ),
'integrated_edit_field37' => array( 'field' => 'orderShipCompany',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field38' => array( 'field' => 'orderInvoiceRequired',
'type' => 'integrated_edit_field',
'orientation' => 0,
'joined' => true,
'separated' => false ),
'section3' => array( 'type' => 'section',
'title' => array( 'text' => 'Παραγγελία Προϊόντων',
'type' => 0 ),
'location' => 'section6',
'initiallyClosed' => true ),
'integrated_edit_field22' => array( 'field' => 'contactId',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'text7' => array( 'type' => 'text',
'label' => array( 'text' => '0',
'type' => 0 ),
'editedByRte' => false,
'padding' => array( 'left' => '5px' ),
'bold' => true,
'font-size' => '16px',
'color' => '#c00909' ),
'text8' => array( 'type' => 'text',
'label' => array( 'text' => 'Συνολική Αξία: ',
'type' => 0 ),
'editedByRte' => false,
'bold' => true,
'font-size' => '16px',
'color' => '#c00909' ),
'text9' => array( 'type' => 'text',
'label' => array( 'text' => 'Χρονόμετρο Κλήσης: ',
'type' => 0 ),
'editedByRte' => false,
'bold' => true,
'padding' => array( 'top' => '5px' ) ),
'text10' => array( 'type' => 'text',
'editedByRte' => false,
'bold' => true,
'padding' => array( 'top' => '5px' ) ),
'text11' => array( 'type' => 'text',
'label' => array( 'text' => 'agentStatus',
'type' => 0 ),
'editedByRte' => false,
'bold' => true ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>