<?php
			$optionsArray = array( 'pdf' => array( 'pdfView' => false ),
'listSearch' => array( 'alwaysOnPanelFields' => array(  ),
'searchPanel' => true,
'fixedSearchPanel' => false,
'simpleSearchOptions' => false,
'searchSaving' => false ),
'fields' => array( 'gridFields' => array( 'callAppsCount',
'forCount',
'talktime',
'typingTime',
'totalCallTime' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array( 'dialerList',
'callAppsCount',
'forCount',
'dialerAgent',
'callResult',
'callDate',
'dialerCampaign' ),
'filterFields' => array( 'dialerAgent',
'dialerCampaign',
'dialerList',
'callResult',
'forCount',
'callAppsCount' ),
'fieldItems' => array( 'callResult' => array( 'report_group_field3' ),
'dialerList' => array( 'report_group_field2' ),
'dialerCampaign' => array( 'report_group_field1' ),
'callAppsCount' => array( 'report_grid_field5' ),
'forCount' => array( 'report_grid_field4' ),
'callTimeBreak' => array( 'report_group_field4' ),
'callDate' => array( 'report_group_field' ),
'talktime' => array( 'report_grid_field' ),
'typingTime' => array( 'report_grid_field1' ),
'totalCallTime' => array( 'report_grid_field2' ),
'dialerAgent' => array( 'report_group_field5' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array( 'logo',
'menu',
'simple_search',
'list_options',
'loginform_login',
'username_button' ),
'left' => array( 'search_panel',
'filter_panel' ),
'top' => array( 'breadcrumb' ),
'above-grid' => array( 'custom_button',
'details_found',
'page_size',
'print_panel' ),
'below-grid' => array( 'pagination' ),
'grid' => array( 'report_group_field',
'report_group_field1',
'report_group_field2',
'report_group_field3',
'report_group_field4',
'report_group_field5',
'report_grid_field4',
'report_grid_field5',
'report_grid_field',
'report_grid_field1',
'report_grid_field2' ) ),
'formXtTags' => array( 'top' => array( 'breadcrumb' ),
'below-grid' => array( 'pagination' ) ),
'itemForms' => array( 'logo' => 'supertop',
'menu' => 'supertop',
'simple_search' => 'supertop',
'list_options' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'search_panel' => 'left',
'filter_panel' => 'left',
'breadcrumb' => 'top',
'custom_button' => 'above-grid',
'details_found' => 'above-grid',
'page_size' => 'above-grid',
'print_panel' => 'above-grid',
'pagination' => 'below-grid',
'report_group_field' => 'grid',
'report_group_field1' => 'grid',
'report_group_field2' => 'grid',
'report_group_field3' => 'grid',
'report_group_field4' => 'grid',
'report_group_field5' => 'grid',
'report_grid_field4' => 'grid',
'report_grid_field5' => 'grid',
'report_grid_field' => 'grid',
'report_grid_field1' => 'grid',
'report_grid_field2' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array( 'menu' => 3,
'simple_search' => 3,
'list_options' => 3,
'loginform_login' => 3,
'username_button' => 3,
'search_panel' => 5,
'filter_panel' => 3,
'print_panel' => 5 ) ),
'itemsByType' => array( 'page_size' => array( 'page_size' ),
'details_found' => array( 'details_found' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'simple_search' => array( 'simple_search' ),
'pagination' => array( 'pagination' ),
'list_options' => array( 'list_options' ),
'export_report_excel' => array( 'export_report_excel' ),
'export_report_word' => array( 'export_report_word' ),
'hide_search_panel' => array( 'hide_search_panel' ),
'show_search_panel' => array( 'show_search_panel' ),
'-' => array( '-',
'-1' ),
'search_panel' => array( 'search_panel' ),
'report_group_field' => array( 'report_group_field3',
'report_group_field2',
'report_group_field1',
'report_group_field4',
'report_group_field',
'report_group_field5' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'logout_link' => array( 'logout_link' ),
'adminarea_link' => array( 'adminarea_link' ),
'print_panel' => array( 'print_panel' ),
'print_scope' => array( 'print_scope' ),
'print_button' => array( 'print_button' ),
'print_records' => array( 'print_records' ),
'advsearch_link' => array( 'advsearch_link' ),
'search_panel_field' => array( 'search_panel_field27',
'search_panel_field29',
'search_panel_field1',
'search_panel_field',
'search_panel_field2',
'search_panel_field3',
'search_panel_field4' ),
'report_grid_field' => array( 'report_grid_field5',
'report_grid_field4',
'report_grid_field',
'report_grid_field1',
'report_grid_field2' ),
'custom_button' => array( 'custom_button' ),
'filter_panel' => array( 'filter_panel' ),
'filter_panel_field' => array( 'filter_panel_field',
'filter_panel_field2',
'filter_panel_field3',
'filter_panel_field4',
'filter_panel_field1',
'filter_panel_field5' ),
'breadcrumb' => array( 'breadcrumb' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 1 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array( 'details_found' => array( 'tag' => 'DISPLAYING',
'type' => 2 ) ) ),
'hasCustomButtons' => true,
'customButtons' => array( 'refreshPage' ) ),
'misc' => array( 'type' => 'report',
'breadcrumb' => true ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array( 'refreshPage' ) ) );
			$pageArray = array( 'id' => 'report',
'type' => 'report',
'layoutId' => 'topbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'topbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'logo',
'menu' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'simple_search',
'list_options',
'loginform_login',
'username_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'list-vbar',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'search_panel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'filter_panel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'list-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'breadcrumb' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'report-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'custom_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'details_found',
'page_size',
'print_panel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'report-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'pagination' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'report-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'report_group_field',
'report_group_field1',
'report_group_field2',
'report_group_field3',
'report_group_field4',
'report_group_field5' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'orientation' => 'vertical' ),
'c2' => array( 'model' => 'c2',
'items' => array( 'report_grid_field4',
'report_grid_field5',
'report_grid_field',
'report_grid_field1',
'report_grid_field2' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'page_size' => array( 'type' => 'page_size' ),
'details_found' => array( 'type' => 'details_found' ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu' ),
'simple_search' => array( 'type' => 'simple_search' ),
'pagination' => array( 'type' => 'pagination' ),
'list_options' => array( 'type' => 'list_options',
'items' => array( 'advsearch_link',
'show_search_panel',
'hide_search_panel',
'-1',
'export_report_excel',
'export_report_word' ) ),
'export_report_excel' => array( 'type' => 'export_report_excel' ),
'export_report_word' => array( 'type' => 'export_report_word' ),
'hide_search_panel' => array( 'type' => 'hide_search_panel' ),
'show_search_panel' => array( 'type' => 'show_search_panel' ),
'-' => array( 'type' => '-' ),
'search_panel' => array( 'type' => 'search_panel',
'items' => array( 'search_panel_field29',
'search_panel_field4',
'search_panel_field3',
'search_panel_field2',
'search_panel_field1',
'search_panel_field',
'search_panel_field27' ),
'_flexiblePanel' => true ),
'report_group_field3' => array( 'field' => 'callResult',
'type' => 'report_group_field' ),
'report_group_field2' => array( 'field' => 'dialerList',
'type' => 'report_group_field' ),
'report_group_field1' => array( 'field' => 'dialerCampaign',
'type' => 'report_group_field' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'logout_link',
'adminarea_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => true ),
'logout_link' => array( 'type' => 'logout_link' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'print_panel' => array( 'type' => 'print_panel',
'items' => array( 'print_scope',
'print_records',
'print_button' ) ),
'print_scope' => array( 'type' => 'print_scope' ),
'print_button' => array( 'type' => 'print_button' ),
'print_records' => array( 'type' => 'print_records' ),
'-1' => array( 'type' => '-' ),
'advsearch_link' => array( 'type' => 'advsearch_link' ),
'search_panel_field27' => array( 'field' => 'dialerCampaign',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field29' => array( 'field' => 'dialerList',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'report_grid_field5' => array( 'field' => 'callAppsCount',
'type' => 'report_grid_field' ),
'report_grid_field4' => array( 'field' => 'forCount',
'type' => 'report_grid_field' ),
'search_panel_field1' => array( 'field' => 'callResult',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'report_group_field4' => array( 'field' => 'callTimeBreak',
'type' => 'report_group_field' ),
'search_panel_field' => array( 'field' => 'callDate',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'report_group_field' => array( 'field' => 'callDate',
'type' => 'report_group_field' ),
'report_grid_field' => array( 'field' => 'talktime',
'type' => 'report_grid_field' ),
'report_grid_field1' => array( 'field' => 'typingTime',
'type' => 'report_grid_field' ),
'report_grid_field2' => array( 'field' => 'totalCallTime',
'type' => 'report_grid_field' ),
'custom_button' => array( 'type' => 'custom_button',
'eventId' => 'refreshPage',
'label' => array( 'text' => 'refreshPage',
'type' => 0 ) ),
'search_panel_field2' => array( 'field' => 'dialerAgent',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'report_group_field5' => array( 'field' => 'dialerAgent',
'type' => 'report_group_field' ),
'filter_panel' => array( 'type' => 'filter_panel',
'items' => array( 'filter_panel_field4',
'filter_panel_field',
'filter_panel_field5',
'filter_panel_field1',
'filter_panel_field3',
'filter_panel_field2' ) ),
'filter_panel_field' => array( 'field' => 'dialerAgent',
'type' => 'filter_panel_field' ),
'filter_panel_field2' => array( 'field' => 'dialerCampaign',
'type' => 'filter_panel_field' ),
'filter_panel_field3' => array( 'field' => 'dialerList',
'type' => 'filter_panel_field' ),
'filter_panel_field4' => array( 'field' => 'callResult',
'type' => 'filter_panel_field' ),
'breadcrumb' => array( 'type' => 'breadcrumb' ),
'filter_panel_field1' => array( 'field' => 'forCount',
'type' => 'filter_panel_field' ),
'filter_panel_field5' => array( 'field' => 'callAppsCount',
'type' => 'filter_panel_field' ),
'search_panel_field3' => array( 'field' => 'forCount',
'type' => 'search_panel_field',
'alwaysOnPanel' => false,
'required' => false ),
'search_panel_field4' => array( 'field' => 'callAppsCount',
'type' => 'search_panel_field',
'alwaysOnPanel' => false,
'required' => false ) ),
'dbProps' => array(  ),
'version' => 4,
'pageWidth' => 'full' );
		?>