<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'talkTime',
'typingTime',
'totalCallTime',
'callStatusId',
'callDenialReasonID',
'callClassificationID',
'callSubClassificationID',
'dialerPhone',
'dialerCampaign',
'dialerList',
'dialerAgent',
'contactName',
'callTime',
'callDate',
'contactAge',
'crmUser',
'pauseAfterCall' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'talkTime' => array( 'integrated_search_field5',
'search_field_label11',
'search_field_options11',
'search_field_between11' ),
'typingTime' => array( 'integrated_search_field6',
'search_field_label12',
'search_field_options12',
'search_field_between12' ),
'totalCallTime' => array( 'integrated_search_field7',
'search_field_label13',
'search_field_options13',
'search_field_between13' ),
'callStatusId' => array( 'integrated_search_field11',
'search_field_label6',
'search_field_options6',
'search_field_between6' ),
'callDenialReasonID' => array( 'integrated_search_field12',
'search_field_label7',
'search_field_options7',
'search_field_between7' ),
'callClassificationID' => array( 'integrated_search_field13',
'search_field_label4',
'search_field_options4',
'search_field_between4' ),
'callSubClassificationID' => array( 'integrated_search_field14',
'search_field_label5',
'search_field_options5',
'search_field_between5' ),
'dialerPhone' => array( 'integrated_search_field26',
'search_field_label3',
'search_field_options3',
'search_field_between3' ),
'dialerCampaign' => array( 'integrated_search_field28',
'search_field_label8',
'search_field_options8',
'search_field_between8' ),
'dialerList' => array( 'integrated_search_field29',
'search_field_label9',
'search_field_options9',
'search_field_between9' ),
'dialerAgent' => array( 'integrated_search_field31',
'search_field_label',
'search_field_options',
'search_field_between' ),
'contactName' => array( 'integrated_search_field41',
'search_field_label10',
'search_field_options10',
'search_field_between10' ),
'callTime' => array( 'integrated_search_field1',
'search_field_label2',
'search_field_options2',
'search_field_between2' ),
'callDate' => array( 'integrated_search_field',
'search_field_label1',
'search_field_options1',
'search_field_between1' ),
'contactAge' => array( 'integrated_search_field2' ),
'crmUser' => array( 'integrated_search_field3' ),
'pauseAfterCall' => array( 'integrated_search_field4' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array( 'logo',
'menu',
'loginform_login',
'username_button' ),
'top' => array( 'search_header' ),
'above-grid' => array(  ),
'below-grid' => array( 'search_search',
'search_reset',
'search_back_list',
'search_cancel' ),
'grid' => array( 'integrated_search_field',
'search_field_between1',
'search_field_label',
'search_field_label1',
'search_field_options1',
'search_field_label4',
'search_field_options4',
'integrated_search_field13',
'search_field_between4',
'search_field_label12',
'search_field_label11',
'search_field_label3',
'search_field_options3',
'integrated_search_field26',
'search_field_between3',
'search_field_label9',
'search_field_label2',
'search_field_options2',
'integrated_search_field31',
'search_field_between',
'integrated_search_field1',
'search_field_between2',
'search_field_label8',
'integrated_search_field28',
'search_field_between8',
'integrated_search_field29',
'search_field_between9',
'search_field_label7',
'search_field_options7',
'integrated_search_field5',
'search_field_between11',
'integrated_search_field12',
'search_field_between7',
'search_field_label6',
'search_field_options6',
'integrated_search_field6',
'search_field_between12',
'integrated_search_field11',
'search_field_between6',
'search_field_label5',
'search_field_options5',
'integrated_search_field7',
'search_field_between13',
'integrated_search_field14',
'search_field_between5',
'search_field_label13',
'search_field_label10',
'search_field_options10',
'integrated_search_field41',
'search_field_between10',
'search_field_options',
'search_field_options8',
'search_field_options9',
'search_field_options11',
'search_field_options12',
'search_field_options13',
'integrated_search_field2',
'integrated_search_field3',
'integrated_search_field4' ) ),
'formXtTags' => array( 'above-grid' => array(  ) ),
'itemForms' => array( 'logo' => 'supertop',
'menu' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'search_header' => 'top',
'search_search' => 'below-grid',
'search_reset' => 'below-grid',
'search_back_list' => 'below-grid',
'search_cancel' => 'below-grid',
'integrated_search_field' => 'grid',
'search_field_between1' => 'grid',
'search_field_label' => 'grid',
'search_field_label1' => 'grid',
'search_field_options1' => 'grid',
'search_field_label4' => 'grid',
'search_field_options4' => 'grid',
'integrated_search_field13' => 'grid',
'search_field_between4' => 'grid',
'search_field_label12' => 'grid',
'search_field_label11' => 'grid',
'search_field_label3' => 'grid',
'search_field_options3' => 'grid',
'integrated_search_field26' => 'grid',
'search_field_between3' => 'grid',
'search_field_label9' => 'grid',
'search_field_label2' => 'grid',
'search_field_options2' => 'grid',
'integrated_search_field31' => 'grid',
'search_field_between' => 'grid',
'integrated_search_field1' => 'grid',
'search_field_between2' => 'grid',
'search_field_label8' => 'grid',
'integrated_search_field28' => 'grid',
'search_field_between8' => 'grid',
'integrated_search_field29' => 'grid',
'search_field_between9' => 'grid',
'search_field_label7' => 'grid',
'search_field_options7' => 'grid',
'integrated_search_field5' => 'grid',
'search_field_between11' => 'grid',
'integrated_search_field12' => 'grid',
'search_field_between7' => 'grid',
'search_field_label6' => 'grid',
'search_field_options6' => 'grid',
'integrated_search_field6' => 'grid',
'search_field_between12' => 'grid',
'integrated_search_field11' => 'grid',
'search_field_between6' => 'grid',
'search_field_label5' => 'grid',
'search_field_options5' => 'grid',
'integrated_search_field7' => 'grid',
'search_field_between13' => 'grid',
'integrated_search_field14' => 'grid',
'search_field_between5' => 'grid',
'search_field_label13' => 'grid',
'search_field_label10' => 'grid',
'search_field_options10' => 'grid',
'integrated_search_field41' => 'grid',
'search_field_between10' => 'grid',
'search_field_options' => 'grid',
'search_field_options8' => 'grid',
'search_field_options9' => 'grid',
'search_field_options11' => 'grid',
'search_field_options12' => 'grid',
'search_field_options13' => 'grid',
'integrated_search_field2' => 'grid',
'integrated_search_field3' => 'grid',
'integrated_search_field4' => 'grid' ),
'itemLocations' => array( 'integrated_search_field' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'search_field_between1' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'search_field_label' => array( 'location' => 'grid',
'cellId' => 'c5' ),
'search_field_label1' => array( 'location' => 'grid',
'cellId' => 'c9' ),
'search_field_options1' => array( 'location' => 'grid',
'cellId' => 'c12' ),
'search_field_label4' => array( 'location' => 'grid',
'cellId' => 'c19' ),
'search_field_options4' => array( 'location' => 'grid',
'cellId' => 'c20' ),
'integrated_search_field13' => array( 'location' => 'grid',
'cellId' => 'c22' ),
'search_field_between4' => array( 'location' => 'grid',
'cellId' => 'c22' ),
'search_field_label12' => array( 'location' => 'grid',
'cellId' => 'c23' ),
'search_field_label11' => array( 'location' => 'grid',
'cellId' => 'c28' ),
'search_field_label3' => array( 'location' => 'grid',
'cellId' => 'c29' ),
'search_field_options3' => array( 'location' => 'grid',
'cellId' => 'c30' ),
'integrated_search_field26' => array( 'location' => 'grid',
'cellId' => 'c32' ),
'search_field_between3' => array( 'location' => 'grid',
'cellId' => 'c32' ),
'search_field_label9' => array( 'location' => 'grid',
'cellId' => 'c33' ),
'search_field_label2' => array( 'location' => 'grid',
'cellId' => 'c34' ),
'search_field_options2' => array( 'location' => 'grid',
'cellId' => 'c35' ),
'integrated_search_field31' => array( 'location' => 'grid',
'cellId' => 'c36' ),
'search_field_between' => array( 'location' => 'grid',
'cellId' => 'c36' ),
'integrated_search_field1' => array( 'location' => 'grid',
'cellId' => 'c37' ),
'search_field_between2' => array( 'location' => 'grid',
'cellId' => 'c37' ),
'search_field_label8' => array( 'location' => 'grid',
'cellId' => 'c38' ),
'integrated_search_field28' => array( 'location' => 'grid',
'cellId' => 'c40' ),
'search_field_between8' => array( 'location' => 'grid',
'cellId' => 'c40' ),
'integrated_search_field29' => array( 'location' => 'grid',
'cellId' => 'c45' ),
'search_field_between9' => array( 'location' => 'grid',
'cellId' => 'c45' ),
'search_field_label7' => array( 'location' => 'grid',
'cellId' => 'c48' ),
'search_field_options7' => array( 'location' => 'grid',
'cellId' => 'c49' ),
'integrated_search_field5' => array( 'location' => 'grid',
'cellId' => 'c50' ),
'search_field_between11' => array( 'location' => 'grid',
'cellId' => 'c50' ),
'integrated_search_field12' => array( 'location' => 'grid',
'cellId' => 'c51' ),
'search_field_between7' => array( 'location' => 'grid',
'cellId' => 'c51' ),
'search_field_label6' => array( 'location' => 'grid',
'cellId' => 'c53' ),
'search_field_options6' => array( 'location' => 'grid',
'cellId' => 'c54' ),
'integrated_search_field6' => array( 'location' => 'grid',
'cellId' => 'c55' ),
'search_field_between12' => array( 'location' => 'grid',
'cellId' => 'c55' ),
'integrated_search_field11' => array( 'location' => 'grid',
'cellId' => 'c56' ),
'search_field_between6' => array( 'location' => 'grid',
'cellId' => 'c56' ),
'search_field_label5' => array( 'location' => 'grid',
'cellId' => 'c58' ),
'search_field_options5' => array( 'location' => 'grid',
'cellId' => 'c59' ),
'integrated_search_field7' => array( 'location' => 'grid',
'cellId' => 'c60' ),
'search_field_between13' => array( 'location' => 'grid',
'cellId' => 'c60' ),
'integrated_search_field14' => array( 'location' => 'grid',
'cellId' => 'c61' ),
'search_field_between5' => array( 'location' => 'grid',
'cellId' => 'c61' ),
'search_field_label13' => array( 'location' => 'grid',
'cellId' => 'c62' ),
'search_field_label10' => array( 'location' => 'grid',
'cellId' => 'c63' ),
'search_field_options10' => array( 'location' => 'grid',
'cellId' => 'c64' ),
'integrated_search_field41' => array( 'location' => 'grid',
'cellId' => 'c66' ),
'search_field_between10' => array( 'location' => 'grid',
'cellId' => 'c66' ),
'search_field_options' => array( 'location' => 'grid',
'cellId' => 'c74' ),
'search_field_options8' => array( 'location' => 'grid',
'cellId' => 'c75' ),
'search_field_options9' => array( 'location' => 'grid',
'cellId' => 'c76' ),
'search_field_options11' => array( 'location' => 'grid',
'cellId' => 'c77' ),
'search_field_options12' => array( 'location' => 'grid',
'cellId' => 'c78' ),
'search_field_options13' => array( 'location' => 'grid',
'cellId' => 'c79' ),
'integrated_search_field2' => array( 'location' => 'grid',
'cellId' => 'c91' ),
'integrated_search_field3' => array( 'location' => 'grid',
'cellId' => 'c91' ),
'integrated_search_field4' => array( 'location' => 'grid',
'cellId' => 'c91' ) ),
'itemVisiblity' => array( 'menu' => 3,
'loginform_login' => 3,
'username_button' => 3 ) ),
'itemsByType' => array( 'search_header' => array( 'search_header' ),
'search_reset' => array( 'search_reset' ),
'search_back_list' => array( 'search_back_list' ),
'search_search' => array( 'search_search' ),
'search_cancel' => array( 'search_cancel' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'search_field' => array( 'integrated_search_field5',
'integrated_search_field6',
'integrated_search_field7',
'integrated_search_field11',
'integrated_search_field12',
'integrated_search_field13',
'integrated_search_field14',
'integrated_search_field26',
'integrated_search_field28',
'integrated_search_field29',
'integrated_search_field31',
'integrated_search_field41',
'integrated_search_field1',
'integrated_search_field' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'logout_link' => array( 'logout_link' ),
'adminarea_link' => array( 'adminarea_link' ),
'search_field_label' => array( 'search_field_label',
'search_field_label1',
'search_field_label2',
'search_field_label3',
'search_field_label4',
'search_field_label5',
'search_field_label6',
'search_field_label7',
'search_field_label8',
'search_field_label9',
'search_field_label10',
'search_field_label11',
'search_field_label12',
'search_field_label13' ),
'search_field_options' => array( 'search_field_options',
'search_field_options1',
'search_field_options2',
'search_field_options3',
'search_field_options4',
'search_field_options5',
'search_field_options6',
'search_field_options7',
'search_field_options8',
'search_field_options9',
'search_field_options10',
'search_field_options11',
'search_field_options12',
'search_field_options13' ),
'search_field_between' => array( 'search_field_between',
'search_field_between1',
'search_field_between2',
'search_field_between3',
'search_field_between4',
'search_field_between5',
'search_field_between6',
'search_field_between7',
'search_field_between8',
'search_field_between9',
'search_field_between10',
'search_field_between11',
'search_field_between12',
'search_field_between13' ),
'integrated_search_field' => array( 'integrated_search_field2',
'integrated_search_field3',
'integrated_search_field4' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c9' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c12' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c3' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c11' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c5' => array( 'cols' => array( 4 ),
'rows' => array( 0 ),
'tags' => array( 'dialerAgent_fieldblock' ),
'items' => array( 'search_field_label' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c74' => array( 'cols' => array( 5 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'search_field_options' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c36' => array( 'cols' => array( 6 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_search_field31',
'search_field_between' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c34' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'callTime_fieldblock' ),
'items' => array( 'search_field_label2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c35' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'search_field_options2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c37' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_search_field1',
'search_field_between2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c15' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c38' => array( 'cols' => array( 4 ),
'rows' => array( 1 ),
'tags' => array( 'dialerCampaign_fieldblock' ),
'items' => array( 'search_field_label8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c75' => array( 'cols' => array( 5 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'search_field_options8' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c40' => array( 'cols' => array( 6 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_search_field28',
'search_field_between8' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c29' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array( 'dialerPhone_fieldblock' ),
'items' => array( 'search_field_label3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c30' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'search_field_options3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c32' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_search_field26',
'search_field_between3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c16' => array( 'cols' => array( 3 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c33' => array( 'cols' => array( 4 ),
'rows' => array( 2 ),
'tags' => array( 'dialerList_fieldblock' ),
'items' => array( 'search_field_label9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c76' => array( 'cols' => array( 5 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'search_field_options9' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c45' => array( 'cols' => array( 6 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_search_field29',
'search_field_between9' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c24' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c25' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c27' => array( 'cols' => array( 2 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c17' => array( 'cols' => array( 3 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c28' => array( 'cols' => array( 4 ),
'rows' => array( 3 ),
'tags' => array( 'talkTime_fieldblock' ),
'items' => array( 'search_field_label11' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c77' => array( 'cols' => array( 5 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'search_field_options11' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c50' => array( 'cols' => array( 6 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_search_field5',
'search_field_between11' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c19' => array( 'cols' => array( 0 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c20' => array( 'cols' => array( 1 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'search_field_options4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c22' => array( 'cols' => array( 2 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_search_field13',
'search_field_between4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c18' => array( 'cols' => array( 3 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c23' => array( 'cols' => array( 4 ),
'rows' => array( 4 ),
'tags' => array( 'typingTime_fieldblock' ),
'items' => array( 'search_field_label12' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c78' => array( 'cols' => array( 5 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'search_field_options12' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c55' => array( 'cols' => array( 6 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_search_field6',
'search_field_between12' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c58' => array( 'cols' => array( 0 ),
'rows' => array( 5 ),
'tags' => array( 'callSubClassificationID_fieldblock' ),
'items' => array( 'search_field_label5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c59' => array( 'cols' => array( 1 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'search_field_options5' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c61' => array( 'cols' => array( 2 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'integrated_search_field14',
'search_field_between5' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c21' => array( 'cols' => array( 3 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c62' => array( 'cols' => array( 4 ),
'rows' => array( 5 ),
'tags' => array( 'totalCallTime_fieldblock' ),
'items' => array( 'search_field_label13' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c79' => array( 'cols' => array( 5 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'search_field_options13' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c60' => array( 'cols' => array( 6 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'integrated_search_field7',
'search_field_between13' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c53' => array( 'cols' => array( 0 ),
'rows' => array( 6 ),
'tags' => array( 'callStatusId_fieldblock' ),
'items' => array( 'search_field_label6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c54' => array( 'cols' => array( 1 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array( 'search_field_options6' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c56' => array( 'cols' => array( 2 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array( 'integrated_search_field11',
'search_field_between6' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c26' => array( 'cols' => array( 3 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c57' => array( 'cols' => array( 4 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c80' => array( 'cols' => array( 5 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c65' => array( 'cols' => array( 6 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c48' => array( 'cols' => array( 0 ),
'rows' => array( 7 ),
'tags' => array( 'callDenialReasonID_fieldblock' ),
'items' => array( 'search_field_label7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c49' => array( 'cols' => array( 1 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array( 'search_field_options7' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c51' => array( 'cols' => array( 2 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array( 'integrated_search_field12',
'search_field_between7' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c31' => array( 'cols' => array( 3 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c52' => array( 'cols' => array( 4 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c81' => array( 'cols' => array( 5 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c68' => array( 'cols' => array( 6 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c43' => array( 'cols' => array( 0 ),
'rows' => array( 8 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c44' => array( 'cols' => array( 1 ),
'rows' => array( 8 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c46' => array( 'cols' => array( 2 ),
'rows' => array( 8 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c87' => array( 'cols' => array( 3 ),
'rows' => array( 8 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c47' => array( 'cols' => array( 4 ),
'rows' => array( 8 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c82' => array( 'cols' => array( 5 ),
'rows' => array( 8 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c69' => array( 'cols' => array( 6 ),
'rows' => array( 8 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 0 ),
'rows' => array( 9 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c39' => array( 'cols' => array( 1 ),
'rows' => array( 9 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c41' => array( 'cols' => array( 2 ),
'rows' => array( 9 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c88' => array( 'cols' => array( 3 ),
'rows' => array( 9 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c42' => array( 'cols' => array( 4 ),
'rows' => array( 9 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c83' => array( 'cols' => array( 5 ),
'rows' => array( 9 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c70' => array( 'cols' => array( 6 ),
'rows' => array( 9 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c1' => array( 'cols' => array( 0 ),
'rows' => array( 10 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 1 ),
'rows' => array( 10 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 2 ),
'rows' => array( 10 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c89' => array( 'cols' => array( 3 ),
'rows' => array( 10 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c14' => array( 'cols' => array( 4 ),
'rows' => array( 10 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c84' => array( 'cols' => array( 5 ),
'rows' => array( 10 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c71' => array( 'cols' => array( 6 ),
'rows' => array( 10 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c63' => array( 'cols' => array( 0 ),
'rows' => array( 11 ),
'tags' => array( 'contactName_fieldblock' ),
'items' => array( 'search_field_label10' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c64' => array( 'cols' => array( 1 ),
'rows' => array( 11 ),
'tags' => array(  ),
'items' => array( 'search_field_options10' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c66' => array( 'cols' => array( 2 ),
'rows' => array( 11 ),
'tags' => array(  ),
'items' => array( 'integrated_search_field41',
'search_field_between10' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c90' => array( 'cols' => array( 3 ),
'rows' => array( 11 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c67' => array( 'cols' => array( 4 ),
'rows' => array( 11 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c85' => array( 'cols' => array( 5 ),
'rows' => array( 11 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c72' => array( 'cols' => array( 6 ),
'rows' => array( 11 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c10' => array( 'cols' => array( 0 ),
'rows' => array( 12 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c13' => array( 'cols' => array( 1 ),
'rows' => array( 12 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 2 ),
'rows' => array( 12 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c91' => array( 'cols' => array( 3 ),
'rows' => array( 12 ),
'tags' => array(  ),
'items' => array( 'integrated_search_field2',
'integrated_search_field3',
'integrated_search_field4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 4 ),
'rows' => array( 12 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c86' => array( 'cols' => array( 5 ),
'rows' => array( 12 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c73' => array( 'cols' => array( 6 ),
'rows' => array( 12 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 7,
'height' => 13 ) ) ),
'loginForm' => array( 'loginForm' => 1 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'search',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'search',
'type' => 'search',
'layoutId' => 'topbar',
'disabled' => 0,
'default' => 1,
'forms' => array( 'supertop' => array( 'modelId' => 'topbar-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ),
array( 'cell' => 'c3' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'logo' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'menu' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c3' => array( 'model' => 'c3',
'items' => array( 'loginform_login',
'username_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'search-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'search_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'search-above-grid',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'search-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'search_search',
'search_reset',
'search_back_list',
'search_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-search',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c9' ),
array( 'cell' => 'c12' ),
array( 'cell' => 'c3' ),
array( 'cell' => 'c11' ),
array( 'cell' => 'c5' ),
array( 'cell' => 'c74' ),
array( 'cell' => 'c36' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c34' ),
array( 'cell' => 'c35' ),
array( 'cell' => 'c37' ),
array( 'cell' => 'c15' ),
array( 'cell' => 'c38' ),
array( 'cell' => 'c75' ),
array( 'cell' => 'c40' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c29' ),
array( 'cell' => 'c30' ),
array( 'cell' => 'c32' ),
array( 'cell' => 'c16' ),
array( 'cell' => 'c33' ),
array( 'cell' => 'c76' ),
array( 'cell' => 'c45' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c24' ),
array( 'cell' => 'c25' ),
array( 'cell' => 'c27' ),
array( 'cell' => 'c17' ),
array( 'cell' => 'c28' ),
array( 'cell' => 'c77' ),
array( 'cell' => 'c50' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c19' ),
array( 'cell' => 'c20' ),
array( 'cell' => 'c22' ),
array( 'cell' => 'c18' ),
array( 'cell' => 'c23' ),
array( 'cell' => 'c78' ),
array( 'cell' => 'c55' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c58' ),
array( 'cell' => 'c59' ),
array( 'cell' => 'c61' ),
array( 'cell' => 'c21' ),
array( 'cell' => 'c62' ),
array( 'cell' => 'c79' ),
array( 'cell' => 'c60' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c53' ),
array( 'cell' => 'c54' ),
array( 'cell' => 'c56' ),
array( 'cell' => 'c26' ),
array( 'cell' => 'c57' ),
array( 'cell' => 'c80' ),
array( 'cell' => 'c65' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c48' ),
array( 'cell' => 'c49' ),
array( 'cell' => 'c51' ),
array( 'cell' => 'c31' ),
array( 'cell' => 'c52' ),
array( 'cell' => 'c81' ),
array( 'cell' => 'c68' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c43' ),
array( 'cell' => 'c44' ),
array( 'cell' => 'c46' ),
array( 'cell' => 'c87' ),
array( 'cell' => 'c47' ),
array( 'cell' => 'c82' ),
array( 'cell' => 'c69' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ),
array( 'cell' => 'c39' ),
array( 'cell' => 'c41' ),
array( 'cell' => 'c88' ),
array( 'cell' => 'c42' ),
array( 'cell' => 'c83' ),
array( 'cell' => 'c70' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ),
array( 'cell' => 'c8' ),
array( 'cell' => 'c89' ),
array( 'cell' => 'c14' ),
array( 'cell' => 'c84' ),
array( 'cell' => 'c71' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c63' ),
array( 'cell' => 'c64' ),
array( 'cell' => 'c66' ),
array( 'cell' => 'c90' ),
array( 'cell' => 'c67' ),
array( 'cell' => 'c85' ),
array( 'cell' => 'c72' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c10' ),
array( 'cell' => 'c13' ),
array( 'cell' => 'c7' ),
array( 'cell' => 'c91' ),
array( 'cell' => 'c6' ),
array( 'cell' => 'c86' ),
array( 'cell' => 'c73' ) ) ) ),
'cells' => array( 'c3' => array( 'model' => 'c5',
'items' => array( 'integrated_search_field',
'search_field_between1' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'width' => '120px',
'persistent' => true,
'orientation' => 'vertical' ),
'c' => array( 'model' => 'c5',
'items' => array(  ),
'align' => 'right' ),
'c5' => array( 'model' => 'c5',
'items' => array( 'search_field_label' ),
'width' => '100px',
'align' => 'right' ),
'c6' => array( 'model' => 'c3',
'items' => array(  ) ),
'c7' => array( 'model' => 'c3',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c8' => array( 'model' => 'c5',
'items' => array(  ),
'orientation' => 'vertical' ),
'c9' => array( 'model' => 'c5',
'items' => array( 'search_field_label1' ),
'width' => '140px',
'persistent' => true,
'align' => 'right' ),
'c10' => array( 'model' => 'c5',
'items' => array(  ) ),
'c12' => array( 'model' => 'c5',
'items' => array( 'search_field_options1' ),
'width' => '80px',
'persistent' => true ),
'c13' => array( 'model' => 'c3',
'items' => array(  ) ),
'c14' => array( 'model' => 'c3',
'items' => array(  ) ),
'c19' => array( 'model' => 'c5',
'items' => array( 'search_field_label4' ),
'persistent' => true,
'align' => 'right' ),
'c20' => array( 'model' => 'c5',
'items' => array( 'search_field_options4' ) ),
'c22' => array( 'model' => 'c5',
'items' => array( 'integrated_search_field13',
'search_field_between4' ),
'orientation' => 'vertical' ),
'c23' => array( 'model' => 'c3',
'items' => array( 'search_field_label12' ),
'align' => 'right' ),
'c24' => array( 'model' => 'c5',
'items' => array(  ),
'align' => 'right',
'persistent' => true ),
'c25' => array( 'model' => 'c5',
'items' => array(  ) ),
'c27' => array( 'model' => 'c5',
'items' => array(  ),
'orientation' => 'vertical' ),
'c28' => array( 'model' => 'c3',
'items' => array( 'search_field_label11' ),
'align' => 'right' ),
'c29' => array( 'model' => 'c5',
'items' => array( 'search_field_label3' ),
'align' => 'right' ),
'c30' => array( 'model' => 'c5',
'items' => array( 'search_field_options3' ) ),
'c32' => array( 'model' => 'c5',
'items' => array( 'integrated_search_field26',
'search_field_between3' ),
'orientation' => 'vertical' ),
'c33' => array( 'model' => 'c5',
'items' => array( 'search_field_label9' ),
'align' => 'right' ),
'c34' => array( 'model' => 'c5',
'items' => array( 'search_field_label2' ),
'align' => 'right' ),
'c35' => array( 'model' => 'c5',
'items' => array( 'search_field_options2' ) ),
'c36' => array( 'model' => 'c3',
'items' => array( 'integrated_search_field31',
'search_field_between' ),
'orientation' => 'vertical',
'width' => '120px' ),
'c37' => array( 'model' => 'c5',
'items' => array( 'integrated_search_field1',
'search_field_between2' ),
'orientation' => 'vertical' ),
'c38' => array( 'model' => 'c5',
'items' => array( 'search_field_label8' ),
'align' => 'right' ),
'c39' => array( 'model' => 'c5',
'items' => array(  ) ),
'c40' => array( 'model' => 'c3',
'items' => array( 'integrated_search_field28',
'search_field_between8' ),
'orientation' => 'vertical' ),
'c41' => array( 'model' => 'c5',
'items' => array(  ),
'orientation' => 'vertical' ),
'c42' => array( 'model' => 'c3',
'items' => array(  ) ),
'c43' => array( 'model' => 'c5',
'items' => array(  ),
'align' => 'right' ),
'c44' => array( 'model' => 'c5',
'items' => array(  ) ),
'c45' => array( 'model' => 'c3',
'items' => array( 'integrated_search_field29',
'search_field_between9' ),
'orientation' => 'vertical' ),
'c46' => array( 'model' => 'c5',
'items' => array(  ),
'orientation' => 'vertical' ),
'c47' => array( 'model' => 'c3',
'items' => array(  ) ),
'c48' => array( 'model' => 'c5',
'items' => array( 'search_field_label7' ),
'align' => 'right' ),
'c49' => array( 'model' => 'c5',
'items' => array( 'search_field_options7' ) ),
'c50' => array( 'model' => 'c3',
'items' => array( 'integrated_search_field5',
'search_field_between11' ) ),
'c51' => array( 'model' => 'c5',
'items' => array( 'integrated_search_field12',
'search_field_between7' ),
'orientation' => 'vertical' ),
'c52' => array( 'model' => 'c3',
'items' => array(  ) ),
'c53' => array( 'model' => 'c5',
'items' => array( 'search_field_label6' ),
'align' => 'right' ),
'c54' => array( 'model' => 'c5',
'items' => array( 'search_field_options6' ) ),
'c55' => array( 'model' => 'c3',
'items' => array( 'integrated_search_field6',
'search_field_between12' ) ),
'c56' => array( 'model' => 'c5',
'items' => array( 'integrated_search_field11',
'search_field_between6' ),
'orientation' => 'vertical' ),
'c57' => array( 'model' => 'c3',
'items' => array(  ) ),
'c58' => array( 'model' => 'c5',
'items' => array( 'search_field_label5' ),
'align' => 'right' ),
'c59' => array( 'model' => 'c5',
'items' => array( 'search_field_options5' ) ),
'c60' => array( 'model' => 'c3',
'items' => array( 'integrated_search_field7',
'search_field_between13' ) ),
'c61' => array( 'model' => 'c5',
'items' => array( 'integrated_search_field14',
'search_field_between5' ),
'orientation' => 'vertical' ),
'c62' => array( 'model' => 'c3',
'items' => array( 'search_field_label13' ),
'align' => 'right' ),
'c1' => array( 'model' => 'c5',
'items' => array(  ),
'align' => 'right' ),
'c2' => array( 'model' => 'c5',
'items' => array(  ) ),
'c63' => array( 'model' => 'c5',
'items' => array( 'search_field_label10' ),
'align' => 'right' ),
'c64' => array( 'model' => 'c5',
'items' => array( 'search_field_options10' ) ),
'c65' => array( 'model' => 'c3',
'items' => array(  ) ),
'c66' => array( 'model' => 'c5',
'items' => array( 'integrated_search_field41',
'search_field_between10' ),
'orientation' => 'vertical' ),
'c67' => array( 'model' => 'c3',
'items' => array(  ) ),
'c68' => array( 'model' => 'c3',
'items' => array(  ) ),
'c69' => array( 'model' => 'c3',
'items' => array(  ) ),
'c70' => array( 'model' => 'c3',
'items' => array(  ) ),
'c71' => array( 'model' => 'c3',
'items' => array(  ) ),
'c72' => array( 'model' => 'c3',
'items' => array(  ) ),
'c73' => array( 'model' => 'c3',
'items' => array(  ) ),
'c74' => array( 'model' => 'c3',
'items' => array( 'search_field_options' ),
'width' => '80px' ),
'c75' => array( 'model' => 'c3',
'items' => array( 'search_field_options8' ) ),
'c76' => array( 'model' => 'c3',
'items' => array( 'search_field_options9' ) ),
'c77' => array( 'model' => 'c3',
'items' => array( 'search_field_options11' ) ),
'c78' => array( 'model' => 'c3',
'items' => array( 'search_field_options12' ) ),
'c79' => array( 'model' => 'c3',
'items' => array( 'search_field_options13' ) ),
'c80' => array( 'model' => 'c3',
'items' => array(  ) ),
'c81' => array( 'model' => 'c3',
'items' => array(  ) ),
'c82' => array( 'model' => 'c3',
'items' => array(  ) ),
'c83' => array( 'model' => 'c3',
'items' => array(  ) ),
'c84' => array( 'model' => 'c3',
'items' => array(  ) ),
'c85' => array( 'model' => 'c3',
'items' => array(  ) ),
'c86' => array( 'model' => 'c3',
'items' => array(  ) ),
'c11' => array( 'model' => 'c5',
'items' => array(  ),
'persistent' => true,
'width' => '20px' ),
'c15' => array( 'model' => 'c5',
'items' => array(  ) ),
'c16' => array( 'model' => 'c5',
'items' => array(  ) ),
'c17' => array( 'model' => 'c3',
'items' => array(  ) ),
'c18' => array( 'model' => 'c3',
'items' => array(  ) ),
'c21' => array( 'model' => 'c3',
'items' => array(  ) ),
'c26' => array( 'model' => 'c3',
'items' => array(  ) ),
'c31' => array( 'model' => 'c3',
'items' => array(  ) ),
'c87' => array( 'model' => 'c3',
'items' => array(  ) ),
'c88' => array( 'model' => 'c3',
'items' => array(  ) ),
'c89' => array( 'model' => 'c3',
'items' => array(  ) ),
'c90' => array( 'model' => 'c3',
'items' => array(  ) ),
'c91' => array( 'model' => 'c3',
'items' => array( 'integrated_search_field2',
'integrated_search_field3',
'integrated_search_field4' ) ) ),
'deferredItems' => array(  ),
'separateLabels' => false ) ),
'items' => array( 'search_header' => array( 'type' => 'search_header' ),
'search_reset' => array( 'type' => 'search_reset' ),
'search_back_list' => array( 'type' => 'search_back_list' ),
'search_search' => array( 'type' => 'search_search' ),
'search_cancel' => array( 'type' => 'search_cancel' ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu' ),
'integrated_search_field5' => array( 'field' => 'talkTime',
'type' => 'search_field',
'orientation' => 0,
'required' => false,
'joined' => false,
'separated' => true ),
'integrated_search_field6' => array( 'field' => 'typingTime',
'type' => 'search_field',
'orientation' => 0,
'required' => false,
'joined' => false,
'separated' => true ),
'integrated_search_field7' => array( 'field' => 'totalCallTime',
'type' => 'search_field',
'orientation' => 0,
'required' => false,
'joined' => false,
'separated' => true ),
'integrated_search_field11' => array( 'field' => 'callStatusId',
'type' => 'search_field',
'orientation' => 0,
'required' => false,
'joined' => false,
'separated' => true ),
'integrated_search_field12' => array( 'field' => 'callDenialReasonID',
'type' => 'search_field',
'orientation' => 0,
'required' => false,
'joined' => false,
'separated' => true ),
'integrated_search_field13' => array( 'field' => 'callClassificationID',
'type' => 'search_field',
'orientation' => 0,
'required' => false,
'joined' => false,
'separated' => true ),
'integrated_search_field14' => array( 'field' => 'callSubClassificationID',
'type' => 'search_field',
'orientation' => 0,
'required' => false,
'joined' => false,
'separated' => true ),
'integrated_search_field26' => array( 'field' => 'dialerPhone',
'type' => 'search_field',
'orientation' => 0,
'required' => false,
'joined' => false,
'separated' => true ),
'integrated_search_field28' => array( 'field' => 'dialerCampaign',
'type' => 'search_field',
'orientation' => 0,
'required' => false,
'joined' => false,
'separated' => true ),
'integrated_search_field29' => array( 'field' => 'dialerList',
'type' => 'search_field',
'orientation' => 0,
'required' => false,
'joined' => false,
'separated' => true ),
'integrated_search_field31' => array( 'field' => 'dialerAgent',
'type' => 'search_field',
'orientation' => 0,
'required' => false,
'joined' => false,
'separated' => true ),
'integrated_search_field41' => array( 'field' => 'contactName',
'type' => 'search_field',
'orientation' => 0,
'required' => false,
'joined' => false,
'separated' => true ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'logout_link',
'adminarea_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => true ),
'logout_link' => array( 'type' => 'logout_link' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'integrated_search_field1' => array( 'field' => 'callTime',
'type' => 'search_field',
'orientation' => 0,
'required' => false,
'joined' => false,
'separated' => true ),
'integrated_search_field' => array( 'field' => 'callDate',
'type' => 'search_field',
'orientation' => 0,
'required' => false,
'joined' => false,
'separated' => true ),
'search_field_label' => array( 'type' => 'search_field_label',
'field' => 'dialerAgent',
'separated' => true ),
'search_field_options' => array( 'type' => 'search_field_options',
'field' => 'dialerAgent',
'separated' => true ),
'search_field_between' => array( 'type' => 'search_field_between',
'field' => 'dialerAgent',
'separated' => true ),
'search_field_label1' => array( 'type' => 'search_field_label',
'field' => 'callDate',
'separated' => true ),
'search_field_options1' => array( 'type' => 'search_field_options',
'field' => 'callDate',
'separated' => true ),
'search_field_between1' => array( 'type' => 'search_field_between',
'field' => 'callDate',
'separated' => true ),
'search_field_label2' => array( 'type' => 'search_field_label',
'field' => 'callTime',
'separated' => true ),
'search_field_options2' => array( 'type' => 'search_field_options',
'field' => 'callTime',
'separated' => true ),
'search_field_between2' => array( 'type' => 'search_field_between',
'field' => 'callTime',
'separated' => true ),
'search_field_label3' => array( 'type' => 'search_field_label',
'field' => 'dialerPhone',
'separated' => true ),
'search_field_options3' => array( 'type' => 'search_field_options',
'field' => 'dialerPhone',
'separated' => true ),
'search_field_between3' => array( 'type' => 'search_field_between',
'field' => 'dialerPhone',
'separated' => true ),
'search_field_label4' => array( 'type' => 'search_field_label',
'field' => 'callClassificationID',
'separated' => true ),
'search_field_options4' => array( 'type' => 'search_field_options',
'field' => 'callClassificationID',
'separated' => true ),
'search_field_between4' => array( 'type' => 'search_field_between',
'field' => 'callClassificationID',
'separated' => true ),
'search_field_label5' => array( 'type' => 'search_field_label',
'field' => 'callSubClassificationID',
'separated' => true ),
'search_field_options5' => array( 'type' => 'search_field_options',
'field' => 'callSubClassificationID',
'separated' => true ),
'search_field_between5' => array( 'type' => 'search_field_between',
'field' => 'callSubClassificationID',
'separated' => true ),
'search_field_label6' => array( 'type' => 'search_field_label',
'field' => 'callStatusId',
'separated' => true ),
'search_field_options6' => array( 'type' => 'search_field_options',
'field' => 'callStatusId',
'separated' => true ),
'search_field_between6' => array( 'type' => 'search_field_between',
'field' => 'callStatusId',
'separated' => true ),
'search_field_label7' => array( 'type' => 'search_field_label',
'field' => 'callDenialReasonID',
'separated' => true ),
'search_field_options7' => array( 'type' => 'search_field_options',
'field' => 'callDenialReasonID',
'separated' => true ),
'search_field_between7' => array( 'type' => 'search_field_between',
'field' => 'callDenialReasonID',
'separated' => true ),
'search_field_label8' => array( 'type' => 'search_field_label',
'field' => 'dialerCampaign',
'separated' => true ),
'search_field_options8' => array( 'type' => 'search_field_options',
'field' => 'dialerCampaign',
'separated' => true ),
'search_field_between8' => array( 'type' => 'search_field_between',
'field' => 'dialerCampaign',
'separated' => true ),
'search_field_label9' => array( 'type' => 'search_field_label',
'field' => 'dialerList',
'separated' => true ),
'search_field_options9' => array( 'type' => 'search_field_options',
'field' => 'dialerList',
'separated' => true ),
'search_field_between9' => array( 'type' => 'search_field_between',
'field' => 'dialerList',
'separated' => true ),
'search_field_label10' => array( 'type' => 'search_field_label',
'field' => 'contactName',
'separated' => true ),
'search_field_options10' => array( 'type' => 'search_field_options',
'field' => 'contactName',
'separated' => true ),
'search_field_between10' => array( 'type' => 'search_field_between',
'field' => 'contactName',
'separated' => true ),
'search_field_label11' => array( 'type' => 'search_field_label',
'field' => 'talkTime',
'separated' => true ),
'search_field_options11' => array( 'type' => 'search_field_options',
'field' => 'talkTime',
'separated' => true ),
'search_field_between11' => array( 'type' => 'search_field_between',
'field' => 'talkTime',
'separated' => true ),
'search_field_label12' => array( 'type' => 'search_field_label',
'field' => 'typingTime',
'separated' => true ),
'search_field_options12' => array( 'type' => 'search_field_options',
'field' => 'typingTime',
'separated' => true ),
'search_field_between12' => array( 'type' => 'search_field_between',
'field' => 'typingTime',
'separated' => true ),
'search_field_label13' => array( 'type' => 'search_field_label',
'field' => 'totalCallTime',
'separated' => true ),
'search_field_options13' => array( 'type' => 'search_field_options',
'field' => 'totalCallTime',
'separated' => true ),
'search_field_between13' => array( 'type' => 'search_field_between',
'field' => 'totalCallTime',
'separated' => true ),
'integrated_search_field2' => array( 'field' => 'contactAge',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field3' => array( 'field' => 'crmUser',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field4' => array( 'field' => 'pauseAfterCall',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>