<?php
			$optionsArray = array( 'captcha' => array( 'captcha' => false ),
'fields' => array( 'gridFields' => array( 'callGdprAcceptance',
'remarks',
'dialerRecording',
'broadcast',
'dialerCallEpoch',
'callGdprRecordingAcceptance',
'callHangup',
'dialerLeadID',
'dialerCampaign',
'contactName',
'courierDeliveryDate',
'courier',
'callComments',
'dialerList',
'deliveryComments',
'contactAge',
'callDenialReasonID',
'callStatusId',
'talkTime',
'redialIsPrivate',
'courierTimeTo',
'dialerPhone',
'contactMethod',
'tvchannel',
'orderInvoiceRequired',
'callSubClassificationID',
'redialComments',
'contactGender',
'seller',
'callStart',
'callClassificationID',
'productFamilyId',
'ContactArea',
'redialDate',
'courierTimeFrom',
'contactCity',
'contactZipCode',
'totalCallTime',
'typingTime',
'callEnd',
'orderPaymentMethod',
'orderShipCompany',
'contactId' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'callGdprAcceptance' => array( 'integrated_edit_field41',
'edit_field_label26' ),
'remarks' => array( 'integrated_edit_field9',
'edit_field_label5' ),
'dialerRecording' => array( 'integrated_edit_field24' ),
'callStatusId' => array( 'edit_field_label4',
'integrated_edit_field7' ),
'broadcast' => array( 'integrated_edit_field4' ),
'dialerCallEpoch' => array( 'integrated_edit_field23' ),
'callGdprRecordingAcceptance' => array( 'integrated_edit_field42',
'edit_field_label25' ),
'callHangup' => array( 'integrated_edit_field14' ),
'dialerLeadID' => array( 'integrated_edit_field30' ),
'dialerCampaign' => array( 'integrated_edit_field13',
'edit_field_label1' ),
'contactName' => array( 'integrated_edit_field34',
'edit_field_label20' ),
'courierDeliveryDate' => array( 'integrated_edit_field19' ),
'courier' => array( 'integrated_edit_field16',
'edit_field_label18' ),
'callComments' => array( 'integrated_edit_field18',
'edit_field_label9' ),
'dialerList' => array( 'integrated_edit_field29',
'edit_field_label2' ),
'deliveryComments' => array( 'integrated_edit_field10',
'edit_field_label15' ),
'contactAge' => array( 'integrated_edit_field17',
'edit_field_label14' ),
'callDenialReasonID' => array( 'integrated_edit_field2',
'edit_field_label11' ),
'talkTime' => array( 'integrated_edit_field26' ),
'redialIsPrivate' => array( 'integrated_edit_field12',
'edit_field_label7' ),
'courierTimeTo' => array( 'integrated_edit_field21' ),
'dialerPhone' => array( 'integrated_edit_field',
'edit_field_label10' ),
'contactCity' => array( 'edit_field_label24',
'integrated_edit_field39' ),
'ContactArea' => array( 'edit_field_label23',
'integrated_edit_field40' ),
'contactZipCode' => array( 'edit_field_label22',
'integrated_edit_field35' ),
'contactMethod' => array( 'integrated_edit_field15',
'edit_field_label17' ),
'tvchannel' => array( 'integrated_edit_field5' ),
'contactGender' => array( 'edit_field_label21',
'integrated_edit_field43' ),
'orderInvoiceRequired' => array( 'integrated_edit_field38' ),
'callSubClassificationID' => array( 'integrated_edit_field8' ),
'redialComments' => array( 'integrated_edit_field6',
'edit_field_label8' ),
'seller' => array( 'integrated_edit_field28' ),
'callStart' => array( 'integrated_edit_field36',
'edit_field_label3' ),
'productFamilyId' => array( 'edit_field_label13',
'integrated_edit_field1' ),
'callClassificationID' => array( 'integrated_edit_field3',
'edit_field_label12' ),
'redialDate' => array( 'edit_field_label6',
'integrated_edit_field11' ),
'courierTimeFrom' => array( 'integrated_edit_field20' ),
'totalCallTime' => array( 'integrated_edit_field32' ),
'typingTime' => array( 'integrated_edit_field27' ),
'callEnd' => array( 'integrated_edit_field25' ),
'orderPaymentMethod' => array( 'integrated_edit_field33' ),
'orderShipCompany' => array( 'integrated_edit_field37' ),
'contactId' => array( 'integrated_edit_field22' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array( 'collapse_button',
'add_header',
'edit_field_label1',
'integrated_edit_field13',
'edit_field_label2',
'integrated_edit_field29',
'loginform_login',
'username_button' ),
'left' => array( 'logo1',
'expand_button',
'text',
'custom_button1',
'custom_button2',
'custom_button',
'custom_button9',
'text7',
'custom_button_container',
'custom_button_container1',
'custom_button_container2',
'btHangupWithPause',
'btHangupWithResume',
'text1' ),
'top' => array(  ),
'above-grid' => array( 'text8' ),
'below-grid' => array( 'add_save',
'add_back_list',
'add_cancel' ),
'grid' => array( 'section3',
'section9',
'section',
'section7',
'section10' ),
'section2' => array( 'integrated_edit_field42',
'integrated_edit_field41',
'edit_field_label17',
'edit_field_label10',
'edit_field_label8',
'edit_field_label15',
'edit_field_label9',
'edit_field_label18',
'edit_field_label5',
'edit_field_label12',
'section4',
'section5',
'section1',
'section8',
'section6',
'section2',
'integrated_edit_field3',
'integrated_edit_field9',
'integrated_edit_field6',
'integrated_edit_field15',
'integrated_edit_field16',
'integrated_edit_field10',
'integrated_edit_field18',
'integrated_edit_field8',
'integrated_edit_field19',
'integrated_edit_field34',
'integrated_edit_field35',
'integrated_edit_field39',
'integrated_edit_field20',
'edit_field_label7',
'integrated_edit_field11',
'edit_field_label6',
'integrated_edit_field40',
'integrated_edit_field1',
'edit_field_label13',
'edit_field_label3',
'integrated_edit_field36',
'integrated_edit_field43',
'edit_field_label20',
'edit_field_label25',
'edit_field_label26',
'text5',
'edit_field_label21',
'edit_field_label22',
'edit_field_label23',
'edit_field_label24',
'integrated_edit_field',
'integrated_edit_field21',
'integrated_edit_field12',
'edit_field_label14',
'integrated_edit_field17' ),
'section4' => array( 'text2',
'integrated_edit_field5',
'text4',
'integrated_edit_field28',
'integrated_edit_field4',
'text3' ),
'section6' => array( 'integrated_edit_field22',
'integrated_edit_field37',
'integrated_edit_field33',
'text6',
'orderTotal',
'details_preview1',
'integrated_edit_field38' ),
'section' => array(  ),
'section1' => array(  ),
'section3' => array( 'integrated_edit_field24',
'integrated_edit_field30',
'integrated_edit_field23' ),
'section7' => array( 'details_preview2' ),
'section8' => array( 'integrated_edit_field25',
'integrated_edit_field27',
'integrated_edit_field32',
'integrated_edit_field14',
'integrated_edit_field26' ),
'section9' => array( 'details_preview4' ),
'section10' => array( 'details_preview' ),
'section5' => array( 'edit_field_label4',
'integrated_edit_field7',
'edit_field_label11',
'integrated_edit_field2' ) ),
'formXtTags' => array( 'top' => array(  ) ),
'itemForms' => array( 'collapse_button' => 'supertop',
'add_header' => 'supertop',
'edit_field_label1' => 'supertop',
'integrated_edit_field13' => 'supertop',
'edit_field_label2' => 'supertop',
'integrated_edit_field29' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'logo1' => 'left',
'expand_button' => 'left',
'text' => 'left',
'custom_button1' => 'left',
'custom_button2' => 'left',
'custom_button' => 'left',
'custom_button9' => 'left',
'text7' => 'left',
'custom_button_container' => 'left',
'custom_button_container1' => 'left',
'custom_button_container2' => 'left',
'btHangupWithPause' => 'left',
'btHangupWithResume' => 'left',
'text1' => 'left',
'text8' => 'above-grid',
'add_save' => 'below-grid',
'add_back_list' => 'below-grid',
'add_cancel' => 'below-grid',
'section3' => 'grid',
'section9' => 'grid',
'section' => 'grid',
'section7' => 'grid',
'section10' => 'grid',
'integrated_edit_field42' => 'section2',
'integrated_edit_field41' => 'section2',
'edit_field_label17' => 'section2',
'edit_field_label10' => 'section2',
'edit_field_label8' => 'section2',
'edit_field_label15' => 'section2',
'edit_field_label9' => 'section2',
'edit_field_label18' => 'section2',
'edit_field_label5' => 'section2',
'edit_field_label12' => 'section2',
'section4' => 'section2',
'section5' => 'section2',
'section1' => 'section2',
'section8' => 'section2',
'section6' => 'section2',
'section2' => 'section2',
'integrated_edit_field3' => 'section2',
'integrated_edit_field9' => 'section2',
'integrated_edit_field6' => 'section2',
'integrated_edit_field15' => 'section2',
'integrated_edit_field16' => 'section2',
'integrated_edit_field10' => 'section2',
'integrated_edit_field18' => 'section2',
'integrated_edit_field8' => 'section2',
'integrated_edit_field19' => 'section2',
'integrated_edit_field34' => 'section2',
'integrated_edit_field35' => 'section2',
'integrated_edit_field39' => 'section2',
'integrated_edit_field20' => 'section2',
'edit_field_label7' => 'section2',
'integrated_edit_field11' => 'section2',
'edit_field_label6' => 'section2',
'integrated_edit_field40' => 'section2',
'integrated_edit_field1' => 'section2',
'edit_field_label13' => 'section2',
'edit_field_label3' => 'section2',
'integrated_edit_field36' => 'section2',
'integrated_edit_field43' => 'section2',
'edit_field_label20' => 'section2',
'edit_field_label25' => 'section2',
'edit_field_label26' => 'section2',
'text5' => 'section2',
'edit_field_label21' => 'section2',
'edit_field_label22' => 'section2',
'edit_field_label23' => 'section2',
'edit_field_label24' => 'section2',
'integrated_edit_field' => 'section2',
'integrated_edit_field21' => 'section2',
'integrated_edit_field12' => 'section2',
'edit_field_label14' => 'section2',
'integrated_edit_field17' => 'section2',
'text2' => 'section4',
'integrated_edit_field5' => 'section4',
'text4' => 'section4',
'integrated_edit_field28' => 'section4',
'integrated_edit_field4' => 'section4',
'text3' => 'section4',
'integrated_edit_field22' => 'section6',
'integrated_edit_field37' => 'section6',
'integrated_edit_field33' => 'section6',
'text6' => 'section6',
'orderTotal' => 'section6',
'details_preview1' => 'section6',
'integrated_edit_field38' => 'section6',
'integrated_edit_field24' => 'section3',
'integrated_edit_field30' => 'section3',
'integrated_edit_field23' => 'section3',
'details_preview2' => 'section7',
'integrated_edit_field25' => 'section8',
'integrated_edit_field27' => 'section8',
'integrated_edit_field32' => 'section8',
'integrated_edit_field14' => 'section8',
'integrated_edit_field26' => 'section8',
'details_preview4' => 'section9',
'details_preview' => 'section10',
'edit_field_label4' => 'section5',
'integrated_edit_field7' => 'section5',
'edit_field_label11' => 'section5',
'integrated_edit_field2' => 'section5' ),
'itemLocations' => array( 'section3' => array( 'location' => 'grid',
'cellId' => 'c5' ),
'section9' => array( 'location' => 'grid',
'cellId' => 'c7' ),
'section' => array( 'location' => 'grid',
'cellId' => 'c8' ),
'section7' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'section10' => array( 'location' => 'grid',
'cellId' => 'c' ),
'integrated_edit_field42' => array( 'location' => 'section2',
'cellId' => 'c12' ),
'integrated_edit_field41' => array( 'location' => 'section2',
'cellId' => 'c13' ),
'edit_field_label17' => array( 'location' => 'section2',
'cellId' => 'c15' ),
'edit_field_label10' => array( 'location' => 'section2',
'cellId' => 'c6' ),
'edit_field_label8' => array( 'location' => 'section2',
'cellId' => 'c25' ),
'edit_field_label15' => array( 'location' => 'section2',
'cellId' => 'c48' ),
'edit_field_label9' => array( 'location' => 'section2',
'cellId' => 'c54' ),
'edit_field_label18' => array( 'location' => 'section2',
'cellId' => 'c26' ),
'edit_field_label5' => array( 'location' => 'section2',
'cellId' => 'c42' ),
'edit_field_label12' => array( 'location' => 'section2',
'cellId' => 'c45' ),
'section4' => array( 'location' => 'section2',
'cellId' => 'c64' ),
'section5' => array( 'location' => 'section2',
'cellId' => 'c64' ),
'section1' => array( 'location' => 'section2',
'cellId' => 'c64' ),
'section8' => array( 'location' => 'section2',
'cellId' => 'c64' ),
'section6' => array( 'location' => 'section2',
'cellId' => 'c64' ),
'section2' => array( 'location' => 'section2',
'cellId' => 'c64' ),
'integrated_edit_field3' => array( 'location' => 'section2',
'cellId' => 'c22' ),
'integrated_edit_field9' => array( 'location' => 'section2',
'cellId' => 'c76' ),
'integrated_edit_field6' => array( 'location' => 'section2',
'cellId' => 'c80' ),
'integrated_edit_field15' => array( 'location' => 'section2',
'cellId' => 'c84' ),
'integrated_edit_field16' => array( 'location' => 'section2',
'cellId' => 'c85' ),
'integrated_edit_field10' => array( 'location' => 'section2',
'cellId' => 'c86' ),
'integrated_edit_field18' => array( 'location' => 'section2',
'cellId' => 'c87' ),
'integrated_edit_field8' => array( 'location' => 'section2',
'cellId' => 'c90' ),
'integrated_edit_field19' => array( 'location' => 'section2',
'cellId' => 'c100' ),
'integrated_edit_field34' => array( 'location' => 'section2',
'cellId' => 'c104' ),
'integrated_edit_field35' => array( 'location' => 'section2',
'cellId' => 'c105' ),
'integrated_edit_field39' => array( 'location' => 'section2',
'cellId' => 'c106' ),
'integrated_edit_field20' => array( 'location' => 'section2',
'cellId' => 'c114' ),
'edit_field_label7' => array( 'location' => 'section2',
'cellId' => 'c120' ),
'integrated_edit_field11' => array( 'location' => 'section2',
'cellId' => 'c121' ),
'edit_field_label6' => array( 'location' => 'section2',
'cellId' => 'c16' ),
'integrated_edit_field40' => array( 'location' => 'section2',
'cellId' => 'c122' ),
'integrated_edit_field1' => array( 'location' => 'section2',
'cellId' => 'c23' ),
'edit_field_label13' => array( 'location' => 'section2',
'cellId' => 'c46' ),
'edit_field_label3' => array( 'location' => 'section2',
'cellId' => 'c112' ),
'integrated_edit_field36' => array( 'location' => 'section2',
'cellId' => 'c113' ),
'integrated_edit_field43' => array( 'location' => 'section2',
'cellId' => 'c128' ),
'edit_field_label20' => array( 'location' => 'section2',
'cellId' => 'c133' ),
'edit_field_label25' => array( 'location' => 'section2',
'cellId' => 'c135' ),
'edit_field_label26' => array( 'location' => 'section2',
'cellId' => 'c136' ),
'text5' => array( 'location' => 'section2',
'cellId' => 'c137' ),
'edit_field_label21' => array( 'location' => 'section2',
'cellId' => 'c138' ),
'edit_field_label22' => array( 'location' => 'section2',
'cellId' => 'c139' ),
'edit_field_label23' => array( 'location' => 'section2',
'cellId' => 'c140' ),
'edit_field_label24' => array( 'location' => 'section2',
'cellId' => 'c141' ),
'integrated_edit_field' => array( 'location' => 'section2',
'cellId' => 'c20' ),
'integrated_edit_field21' => array( 'location' => 'section2',
'cellId' => 'c116' ),
'integrated_edit_field12' => array( 'location' => 'section2',
'cellId' => 'c123' ),
'edit_field_label14' => array( 'location' => 'section2',
'cellId' => 'c142' ),
'integrated_edit_field17' => array( 'location' => 'section2',
'cellId' => 'c131' ),
'text2' => array( 'location' => 'section4',
'cellId' => 'c3' ),
'integrated_edit_field5' => array( 'location' => 'section4',
'cellId' => 'c2' ),
'text4' => array( 'location' => 'section4',
'cellId' => 'c7' ),
'integrated_edit_field28' => array( 'location' => 'section4',
'cellId' => 'c8' ),
'integrated_edit_field4' => array( 'location' => 'section4',
'cellId' => 'c9' ),
'text3' => array( 'location' => 'section4',
'cellId' => 'c10' ),
'integrated_edit_field22' => array( 'location' => 'section6',
'cellId' => 'c3' ),
'integrated_edit_field37' => array( 'location' => 'section6',
'cellId' => 'c25' ),
'integrated_edit_field33' => array( 'location' => 'section6',
'cellId' => 'c26' ),
'text6' => array( 'location' => 'section6',
'cellId' => 'c42' ),
'orderTotal' => array( 'location' => 'section6',
'cellId' => 'c43' ),
'details_preview1' => array( 'location' => 'section6',
'cellId' => 'c54' ),
'integrated_edit_field38' => array( 'location' => 'section6',
'cellId' => 'c6' ),
'integrated_edit_field24' => array( 'location' => 'section3',
'cellId' => 'c' ),
'integrated_edit_field30' => array( 'location' => 'section3',
'cellId' => 'c1' ),
'integrated_edit_field23' => array( 'location' => 'section3',
'cellId' => 'c2' ),
'details_preview2' => array( 'location' => 'section7',
'cellId' => 'c' ),
'integrated_edit_field25' => array( 'location' => 'section8',
'cellId' => 'c' ),
'integrated_edit_field27' => array( 'location' => 'section8',
'cellId' => 'c5' ),
'integrated_edit_field32' => array( 'location' => 'section8',
'cellId' => 'c6' ),
'integrated_edit_field14' => array( 'location' => 'section8',
'cellId' => 'c1' ),
'integrated_edit_field26' => array( 'location' => 'section8',
'cellId' => 'c2' ),
'details_preview4' => array( 'location' => 'section9',
'cellId' => 'c1' ),
'details_preview' => array( 'location' => 'section10',
'cellId' => 'c1' ),
'edit_field_label4' => array( 'location' => 'section5',
'cellId' => 'c1' ),
'integrated_edit_field7' => array( 'location' => 'section5',
'cellId' => 'c' ),
'edit_field_label11' => array( 'location' => 'section5',
'cellId' => 'c8' ),
'integrated_edit_field2' => array( 'location' => 'section5',
'cellId' => 'c9' ) ),
'itemVisiblity' => array( 'collapse_button' => 5,
'loginform_login' => 3,
'username_button' => 3,
'expand_button' => 5 ) ),
'itemsByType' => array( 'add_header' => array( 'add_header' ),
'edit_field' => array( 'integrated_edit_field41',
'integrated_edit_field9',
'integrated_edit_field4',
'integrated_edit_field42',
'integrated_edit_field13',
'integrated_edit_field34',
'integrated_edit_field16',
'integrated_edit_field18',
'integrated_edit_field29',
'integrated_edit_field10',
'integrated_edit_field17',
'integrated_edit_field2',
'integrated_edit_field7',
'integrated_edit_field12',
'integrated_edit_field21',
'integrated_edit_field',
'integrated_edit_field15',
'integrated_edit_field5',
'integrated_edit_field8',
'integrated_edit_field6',
'integrated_edit_field43',
'integrated_edit_field28',
'integrated_edit_field36',
'integrated_edit_field3',
'integrated_edit_field1',
'integrated_edit_field40',
'integrated_edit_field11',
'integrated_edit_field20',
'integrated_edit_field39',
'integrated_edit_field35' ),
'text' => array( 'text',
'text8',
'text5',
'text2',
'text6',
'text1',
'text4',
'orderTotal',
'text3',
'text7' ),
'add_save' => array( 'add_save' ),
'add_back_list' => array( 'add_back_list' ),
'add_cancel' => array( 'add_cancel' ),
'integrated_edit_field' => array( 'integrated_edit_field24',
'integrated_edit_field23',
'integrated_edit_field14',
'integrated_edit_field30',
'integrated_edit_field19',
'integrated_edit_field26',
'integrated_edit_field38',
'integrated_edit_field32',
'integrated_edit_field27',
'integrated_edit_field25',
'integrated_edit_field33',
'integrated_edit_field37',
'integrated_edit_field22' ),
'edit_field_label' => array( 'edit_field_label4',
'edit_field_label14',
'edit_field_label1',
'edit_field_label2',
'edit_field_label24',
'edit_field_label23',
'edit_field_label22',
'edit_field_label21',
'edit_field_label26',
'edit_field_label25',
'edit_field_label20',
'edit_field_label3',
'edit_field_label13',
'edit_field_label6',
'edit_field_label7',
'edit_field_label12',
'edit_field_label15',
'edit_field_label8',
'edit_field_label10',
'edit_field_label17',
'edit_field_label5',
'edit_field_label18',
'edit_field_label9',
'edit_field_label11' ),
'section' => array( 'section2',
'section',
'section8',
'section6',
'section10',
'section7',
'section5',
'section9',
'section1',
'section4',
'section3' ),
'details_preview' => array( 'details_preview',
'details_preview2',
'details_preview4',
'details_preview1' ),
'collapse_button' => array( 'collapse_button' ),
'logo' => array( 'logo1' ),
'custom_button' => array( 'btHangupWithPause',
'btHangupWithResume',
'custom_button',
'custom_button1',
'custom_button2',
'custom_button4',
'inVoltonButton',
'wasVoltonButton',
'onPhotovoltaicButton',
'haveNoPower',
'haveOtherProvider',
'custom_button3',
'custom_button5',
'custom_button6',
'custom_button7',
'custom_button8',
'custom_button9' ),
'custom_button_container' => array( 'custom_button_container',
'custom_button_container1',
'custom_button_container2' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'logout_link' => array( 'logout_link' ),
'adminarea_link' => array( 'adminarea_link' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c8' => array( 'cols' => array( 0,
1,
2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'section' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 0,
1,
2 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'section3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 0,
1,
2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'section10' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 0,
1,
2 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'section9' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 0,
1,
2 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'section7' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 0 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 1 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c9' => array( 'cols' => array( 2 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c10' => array( 'cols' => array( 0,
1,
2 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 3,
'height' => 7 ),
'section2' => array( 'cells' => array( 'c97' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c98' => array( 'cols' => array( 1,
2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c132' => array( 'cols' => array( 3,
4 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c137' => array( 'cols' => array( 5,
6,
7 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'text5' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c134' => array( 'cols' => array( 8 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c135' => array( 'cols' => array( 9 ),
'rows' => array( 0 ),
'tags' => array( 'callGdprRecordingAcceptance_fieldblock' ),
'items' => array( 'edit_field_label25' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c136' => array( 'cols' => array( 10 ),
'rows' => array( 0 ),
'tags' => array( 'callGdprAcceptance_fieldblock' ),
'items' => array( 'edit_field_label26' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 0,
1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c20' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c10' => array( 'cols' => array( 3,
4 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c133' => array( 'cols' => array( 5 ),
'rows' => array( 1 ),
'tags' => array( 'contactName_fieldblock' ),
'items' => array( 'edit_field_label20' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c104' => array( 'cols' => array( 6,
7 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field34' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c30' => array( 'cols' => array( 8 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c12' => array( 'cols' => array( 9 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field42' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c13' => array( 'cols' => array( 10 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field41' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c112' => array( 'cols' => array( 0 ),
'rows' => array( 2,
3 ),
'tags' => array( 'callStart_fieldblock' ),
'items' => array( 'edit_field_label3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c113' => array( 'cols' => array( 1,
2 ),
'rows' => array( 2,
3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field36' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c127' => array( 'cols' => array( 3,
4 ),
'rows' => array( 2,
3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c138' => array( 'cols' => array( 5 ),
'rows' => array( 2 ),
'tags' => array( 'contactGender_fieldblock' ),
'items' => array( 'edit_field_label21' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c128' => array( 'cols' => array( 6,
7 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field43' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c129' => array( 'cols' => array( 8 ),
'rows' => array( 2,
3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c64' => array( 'cols' => array( 9,
10 ),
'rows' => array( 2,
3,
4,
5,
6,
7,
8,
9,
10,
11 ),
'tags' => array(  ),
'items' => array( 'section4',
'section5',
'section1',
'section8',
'section6',
'section2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c142' => array( 'cols' => array( 5 ),
'rows' => array( 3 ),
'tags' => array( 'contactAge_fieldblock' ),
'items' => array( 'edit_field_label14' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c131' => array( 'cols' => array( 6,
7 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field17' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c45' => array( 'cols' => array( 0 ),
'rows' => array( 4 ),
'tags' => array( 'callClassificationID_fieldblock' ),
'items' => array( 'edit_field_label12' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c22' => array( 'cols' => array( 1,
2 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c90' => array( 'cols' => array( 3,
4 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c139' => array( 'cols' => array( 5 ),
'rows' => array( 4 ),
'tags' => array( 'contactZipCode_fieldblock' ),
'items' => array( 'edit_field_label22' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c105' => array( 'cols' => array( 6,
7 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field35' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c68' => array( 'cols' => array( 8 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c46' => array( 'cols' => array( 0 ),
'rows' => array( 5 ),
'tags' => array( 'productFamilyId_fieldblock' ),
'items' => array( 'edit_field_label13' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c23' => array( 'cols' => array( 1,
2,
3,
4 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c140' => array( 'cols' => array( 5 ),
'rows' => array( 5 ),
'tags' => array( 'ContactArea_fieldblock' ),
'items' => array( 'edit_field_label23' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c122' => array( 'cols' => array( 6,
7 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field40' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c70' => array( 'cols' => array( 8 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c42' => array( 'cols' => array( 0 ),
'rows' => array( 6 ),
'tags' => array( 'remarks_fieldblock' ),
'items' => array( 'edit_field_label5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c76' => array( 'cols' => array( 1,
2,
3,
4 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field9' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c141' => array( 'cols' => array( 5 ),
'rows' => array( 6 ),
'tags' => array( 'contactCity_fieldblock' ),
'items' => array( 'edit_field_label24' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c106' => array( 'cols' => array( 6,
7 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field39' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c44' => array( 'cols' => array( 8 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c16' => array( 'cols' => array( 0 ),
'rows' => array( 7 ),
'tags' => array( 'redialDate_fieldblock' ),
'items' => array( 'edit_field_label6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c121' => array( 'cols' => array( 1,
2 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field11' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c120' => array( 'cols' => array( 3 ),
'rows' => array( 7 ),
'tags' => array( 'redialIsPrivate_fieldblock' ),
'items' => array( 'edit_field_label7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c123' => array( 'cols' => array( 4 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field12' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c130' => array( 'cols' => array( 5 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c119' => array( 'cols' => array( 6,
7 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 8 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c25' => array( 'cols' => array( 0 ),
'rows' => array( 8 ),
'tags' => array( 'redialComments_fieldblock' ),
'items' => array( 'edit_field_label8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c80' => array( 'cols' => array( 1,
2,
3,
4,
5,
6,
7 ),
'rows' => array( 8 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field6' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c36' => array( 'cols' => array( 8 ),
'rows' => array( 8 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c15' => array( 'cols' => array( 0 ),
'rows' => array( 9 ),
'tags' => array( 'contactMethod_fieldblock' ),
'items' => array( 'edit_field_label17' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c84' => array( 'cols' => array( 1,
2,
3,
4 ),
'rows' => array( 9 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field15' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c100' => array( 'cols' => array( 5 ),
'rows' => array( 9 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field19' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c114' => array( 'cols' => array( 6 ),
'rows' => array( 9 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field20' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c116' => array( 'cols' => array( 7 ),
'rows' => array( 9 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field21' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c50' => array( 'cols' => array( 8 ),
'rows' => array( 9,
10 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c26' => array( 'cols' => array( 0 ),
'rows' => array( 10 ),
'tags' => array( 'courier_fieldblock' ),
'items' => array( 'edit_field_label18' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c85' => array( 'cols' => array( 1,
2,
3,
4 ),
'rows' => array( 10 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field16' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c101' => array( 'cols' => array( 5 ),
'rows' => array( 10 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c115' => array( 'cols' => array( 6,
7 ),
'rows' => array( 10 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c48' => array( 'cols' => array( 0 ),
'rows' => array( 11 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c86' => array( 'cols' => array( 1,
2,
3,
4,
5,
6,
7 ),
'rows' => array( 11 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field10' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c74' => array( 'cols' => array( 8 ),
'rows' => array( 11 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c54' => array( 'cols' => array( 0 ),
'rows' => array( 12 ),
'tags' => array( 'callComments_fieldblock' ),
'items' => array( 'edit_field_label9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c87' => array( 'cols' => array( 1,
2,
3,
4,
5,
6,
7 ),
'rows' => array( 12 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field18' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c75' => array( 'cols' => array( 8 ),
'rows' => array( 12 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c61' => array( 'cols' => array( 9,
10 ),
'rows' => array( 12 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c51' => array( 'cols' => array( 0 ),
'rows' => array( 13 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c88' => array( 'cols' => array( 1,
2,
3,
4,
5,
6,
7 ),
'rows' => array( 13 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c53' => array( 'cols' => array( 8 ),
'rows' => array( 13 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c57' => array( 'cols' => array( 9,
10 ),
'rows' => array( 13 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 11,
'height' => 14 ),
'section4' => array( 'cells' => array( 'c3' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'text2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field5' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c10' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'text3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c9' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'text4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field28' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 3 ),
'section6' => array( 'cells' => array( 'c3' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c1' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c25' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c26' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c6' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field38' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c9' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c42' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c43' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c7' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c10' => array( 'cols' => array( 3 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c54' => array( 'cols' => array( 0,
1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'details_preview1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 2 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c11' => array( 'cols' => array( 3 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 4,
'height' => 4 ),
'section' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section1' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section3' => array( 'cells' => array( 'c' => array( 'cols' => array( 0,
1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field24' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c1' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field30' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field23' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 2 ),
'section7' => array( 'cells' => array( 'c' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'details_preview2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section8' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field14' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field26' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field25' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field27' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 0,
1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field32' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 3 ),
'section9' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'details_preview4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section10' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'details_preview' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section5' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array( 'callStatusId_fieldblock' ),
'items' => array( 'edit_field_label4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field7' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'callDenialReasonID_fieldblock' ),
'items' => array( 'edit_field_label11' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c9' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 0 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 1 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 5 ) ) ),
'loginForm' => array( 'loginForm' => 1 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => true,
'customButtons' => array( 'btHangupWithPauseClick',
'btHangupWithResumeClick',
'instantDenial',
'phoneFaxClick',
'noAnswer',
'noInterest',
'inVolton',
'pastVoltonSubscriber',
'havePVPanels',
'dontHavePower',
'otherProvider',
'novaNoAvailability',
'novaOtherProvider',
'novaExistingCustomer',
'novaNotIneterested',
'productsNotInterested',
'noComm1' ) ),
'misc' => array( 'type' => 'add',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array( 'btHangupWithPauseClick',
'btHangupWithResumeClick',
'instantDenial',
'phoneFaxClick',
'noAnswer',
'noInterest',
'inVolton',
'pastVoltonSubscriber',
'havePVPanels',
'dontHavePower',
'otherProvider',
'novaNoAvailability',
'novaOtherProvider',
'novaExistingCustomer',
'novaNotIneterested',
'productsNotInterested',
'noComm1' ) ) );
			$pageArray = array( 'id' => 'add',
'type' => 'add',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 2,
'forms' => array( 'supertop' => array( 'modelId' => 'leftbar-top-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'collapse_button',
'add_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'width' => '30%' ),
'c2' => array( 'model' => 'c2',
'items' => array( 'edit_field_label1',
'integrated_edit_field13',
'edit_field_label2',
'integrated_edit_field29',
'loginform_login',
'username_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0',
'rowspan' => 1 ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c1' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c5' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c3' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c4' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ) ) ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo1',
'expand_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array(  ),
'align' => 'center',
'orientation' => 'vertical',
'padding' => array( 'top' => '40px' ) ),
'c2' => array( 'model' => 'c1',
'items' => array( 'text',
'custom_button1',
'custom_button2',
'custom_button',
'custom_button9',
'text7',
'custom_button_container',
'custom_button_container1',
'custom_button_container2' ),
'align' => 'center',
'orientation' => 'vertical' ),
'c3' => array( 'model' => 'c1',
'items' => array( 'btHangupWithPause',
'btHangupWithResume' ),
'align' => 'center',
'orientation' => 'vertical' ),
'c1' => array( 'model' => 'c0',
'items' => array(  ),
'padding' => array( 'top' => '60px' ),
'background' => '#ffffff' ),
'c4' => array( 'model' => 'c1',
'items' => array(  ),
'align' => 'center' ),
'c5' => array( 'model' => 'c1',
'items' => array( 'text1' ),
'padding' => array( 'top' => '30px' ),
'align' => 'center' ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'add-header',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ) ) ) ),
'cells' => array( 'c' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'add-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c2',
'colspan' => 1 ) ),
'section' => '' ) ),
'cells' => array( 'c2' => array( 'model' => 'c2',
'items' => array( 'text8' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'add-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add_save',
'add_back_list',
'add_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c8',
'colspan' => 3 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c5',
'colspan' => 3 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c',
'colspan' => 3 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c7',
'colspan' => 3 ) ) ),
array( 'cells' => array( array( 'cell' => 'c3',
'colspan' => 3 ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c4' ),
array( 'cell' => 'c6' ),
array( 'cell' => 'c9' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c10',
'colspan' => 3 ) ),
'section' => '' ) ),
'cells' => array( 'c5' => array( 'model' => 'c3',
'items' => array( 'section3' ),
'width' => '80%' ),
'c7' => array( 'model' => 'c3',
'items' => array( 'section9' ),
'align' => 'left',
'background' => '#0090ff' ),
'c8' => array( 'model' => 'c3',
'items' => array( 'section' ),
'background' => '#ffe6ad' ),
'c3' => array( 'model' => 'c3',
'items' => array( 'section7' ),
'background' => '#d1ffd8' ),
'c' => array( 'model' => 'c3',
'items' => array( 'section10' ) ),
'c4' => array( 'model' => 'c3',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c6' => array( 'model' => 'c3',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c9' => array( 'model' => 'c3',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c10' => array( 'model' => 'c3',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'columnCount' => 3,
'inlineLabels' => true,
'separateLabels' => false ),
'section2' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c97' ),
array( 'cell' => 'c98',
'colspan' => 2 ),
array( 'cell' => 'c132',
'colspan' => 2 ),
array( 'cell' => 'c137',
'colspan' => 3 ),
array( 'cell' => 'c134' ),
array( 'cell' => 'c135' ),
array( 'cell' => 'c136',
'colspan' => 1 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c6',
'rowspan' => 1,
'colspan' => 2 ),
array( 'cell' => 'c20' ),
array( 'cell' => 'c10',
'colspan' => 2 ),
array( 'cell' => 'c133' ),
array( 'cell' => 'c104',
'colspan' => 2 ),
array( 'cell' => 'c30',
'colspan' => 1,
'rowspan' => 1 ),
array( 'cell' => 'c12' ),
array( 'cell' => 'c13',
'rowspan' => 1,
'colspan' => 1 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c112',
'rowspan' => 2 ),
array( 'cell' => 'c113',
'colspan' => 2,
'rowspan' => 2 ),
array( 'cell' => 'c127',
'colspan' => 2,
'rowspan' => 2 ),
array( 'cell' => 'c138' ),
array( 'cell' => 'c128',
'colspan' => 2 ),
array( 'cell' => 'c129',
'rowspan' => 2 ),
array( 'cell' => 'c64',
'colspan' => 2,
'rowspan' => 10 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c142' ),
array( 'cell' => 'c131',
'colspan' => 2 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c45' ),
array( 'cell' => 'c22',
'colspan' => 2 ),
array( 'cell' => 'c90',
'colspan' => 2 ),
array( 'cell' => 'c139' ),
array( 'cell' => 'c105',
'colspan' => 2 ),
array( 'cell' => 'c68',
'colspan' => 1 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c46' ),
array( 'cell' => 'c23',
'colspan' => 4 ),
array( 'cell' => 'c140' ),
array( 'cell' => 'c122',
'colspan' => 2 ),
array( 'cell' => 'c70' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c42' ),
array( 'cell' => 'c76',
'colspan' => 4 ),
array( 'cell' => 'c141' ),
array( 'cell' => 'c106',
'colspan' => 2 ),
array( 'cell' => 'c44',
'colspan' => 1 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c16' ),
array( 'cell' => 'c121',
'colspan' => 2 ),
array( 'cell' => 'c120' ),
array( 'cell' => 'c123' ),
array( 'cell' => 'c130' ),
array( 'cell' => 'c119',
'colspan' => 2 ),
array( 'cell' => 'c' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c25' ),
array( 'cell' => 'c80',
'colspan' => 7 ),
array( 'cell' => 'c36',
'colspan' => 1 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c15',
'rowspan' => 1 ),
array( 'cell' => 'c84',
'colspan' => 4 ),
array( 'cell' => 'c100' ),
array( 'cell' => 'c114' ),
array( 'cell' => 'c116' ),
array( 'cell' => 'c50',
'rowspan' => 2,
'colspan' => 1 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c26' ),
array( 'cell' => 'c85',
'colspan' => 4 ),
array( 'cell' => 'c101' ),
array( 'cell' => 'c115',
'colspan' => 2 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c48' ),
array( 'cell' => 'c86',
'colspan' => 7 ),
array( 'cell' => 'c74' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c54' ),
array( 'cell' => 'c87',
'colspan' => 7 ),
array( 'cell' => 'c75' ),
array( 'cell' => 'c61',
'colspan' => 2 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c51' ),
array( 'cell' => 'c88',
'colspan' => 7 ),
array( 'cell' => 'c53' ),
array( 'cell' => 'c57',
'colspan' => 2 ) ) ) ),
'cells' => array( 'c12' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field42' ),
'background' => '#fffee4',
'orientation' => 'horizontal',
'width' => '145px' ),
'c13' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field41' ),
'background' => '#fffee4',
'color' => '#ff0000',
'orientation' => 'horizontal',
'width' => '130px' ),
'c10' => array( 'model' => 'c1',
'items' => array(  ),
'width' => '150px',
'persistent' => true,
'align' => 'right',
'background' => '#f6fcff' ),
'c15' => array( 'model' => 'c3',
'items' => array( 'edit_field_label17' ),
'align' => 'right',
'background' => '#f6fcff' ),
'c6' => array( 'model' => 'c2',
'items' => array( 'edit_field_label10' ),
'width' => '150px',
'persistent' => true,
'align' => 'right',
'background' => '#f6fcff' ),
'c36' => array( 'model' => 'c2',
'items' => array(  ),
'align' => 'right',
'background' => '#f6fcff' ),
'c25' => array( 'model' => 'c1',
'items' => array( 'edit_field_label8' ),
'align' => 'right',
'background' => '#f6fcff' ),
'c48' => array( 'model' => 'c1',
'items' => array( 'edit_field_label15' ),
'persistent' => true,
'background' => '#f6fcff',
'align' => 'right' ),
'c50' => array( 'model' => 'c2',
'items' => array(  ),
'background' => '#f6fcff',
'orientation' => 'vertical' ),
'c51' => array( 'model' => 'c1',
'items' => array(  ),
'align' => 'right',
'background' => '#f6fcff' ),
'c53' => array( 'model' => 'c2',
'items' => array(  ),
'background' => '#f6fcff' ),
'c54' => array( 'model' => 'c1',
'items' => array( 'edit_field_label9' ),
'background' => '#f6fcff',
'align' => 'right' ),
'c57' => array( 'model' => 'c1',
'items' => array(  ) ),
'c61' => array( 'model' => 'c1',
'items' => array(  ) ),
'c26' => array( 'model' => 'c3',
'items' => array( 'edit_field_label18' ),
'align' => 'right',
'background' => '#f6fcff' ),
'c30' => array( 'model' => 'c2',
'items' => array(  ),
'width' => '30px',
'persistent' => true,
'align' => 'right',
'background' => '#f6fcff',
'orientation' => 'vertical' ),
'c42' => array( 'model' => 'c1',
'items' => array( 'edit_field_label5' ),
'align' => 'right',
'background' => '#f6fcff' ),
'c44' => array( 'model' => 'c2',
'items' => array(  ),
'align' => 'right',
'background' => '#f6fcff' ),
'c45' => array( 'model' => 'c1',
'items' => array( 'edit_field_label12' ),
'align' => 'right',
'background' => '#f6fcff' ),
'c64' => array( 'model' => 'c1',
'items' => array( 'section4',
'section5',
'section1',
'section8',
'section6',
'section2' ) ),
'c68' => array( 'model' => 'c2',
'items' => array(  ),
'align' => 'right',
'background' => '#f6fcff' ),
'c74' => array( 'model' => 'c3',
'items' => array(  ),
'persistent' => true,
'background' => '#f6fcff' ),
'c75' => array( 'model' => 'c3',
'items' => array(  ),
'background' => '#f6fcff' ),
'c22' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field3' ),
'background' => '#f6fcff' ),
'c76' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field9' ),
'background' => '#f6fcff' ),
'c80' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field6' ),
'background' => '#f6fcff' ),
'c84' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field15' ),
'background' => '#f6fcff' ),
'c85' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field16' ),
'background' => '#f6fcff' ),
'c86' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field10' ),
'background' => '#f6fcff' ),
'c87' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field18' ),
'background' => '#f6fcff' ),
'c88' => array( 'model' => 'c2',
'items' => array(  ),
'background' => '#f6fcff' ),
'c90' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field8' ),
'align' => 'right',
'background' => '#f6fcff',
'persistent' => true ),
'c100' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field19' ),
'align' => 'right',
'background' => '#f6fcff' ),
'c104' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field34' ),
'width' => '170px',
'background' => '#ffffee',
'border' => array( array( 'side' => 'right',
'width' => '1px',
'color' => '#0b04d1' ) ) ),
'c105' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field35' ),
'background' => '#ffffee',
'border' => array( array( 'side' => 'right',
'width' => '1px',
'color' => '#0b04d1' ) ) ),
'c106' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field39' ),
'background' => '#ffffee',
'border' => array( array( 'side' => 'right',
'width' => '1px',
'color' => '#0b04d1' ),
array( 'side' => 'bottom',
'width' => '1px',
'color' => '#0b04d1' ) ) ),
'c114' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field20' ),
'background' => '#f6fcff' ),
'c115' => array( 'model' => 'c2',
'items' => array(  ),
'background' => '#f6fcff' ),
'c' => array( 'model' => 'c2',
'items' => array(  ),
'align' => 'right',
'nowrap' => true,
'background' => '#f6fcff' ),
'c119' => array( 'model' => 'c2',
'items' => array(  ),
'background' => '#f6fcff' ),
'c120' => array( 'model' => 'c2',
'items' => array( 'edit_field_label7' ),
'background' => '#f6fcff',
'align' => 'right' ),
'c121' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field11' ),
'background' => '#f6fcff' ),
'c16' => array( 'model' => 'c1',
'items' => array( 'edit_field_label6' ),
'align' => 'right',
'background' => '#f6fcff' ),
'c70' => array( 'model' => 'c2',
'items' => array(  ),
'align' => 'right',
'background' => '#f6fcff' ),
'c122' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field40' ),
'background' => '#ffffee',
'border' => array( array( 'side' => 'right',
'width' => '1px',
'color' => '#0b04d1' ) ) ),
'c23' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field1' ),
'background' => '#f6fcff' ),
'c46' => array( 'model' => 'c1',
'items' => array( 'edit_field_label13' ),
'align' => 'right',
'background' => '#f6fcff' ),
'c112' => array( 'model' => 'c1',
'items' => array( 'edit_field_label3' ),
'align' => 'right',
'background' => '#f6fcff' ),
'c113' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field36' ),
'background' => '#f6fcff' ),
'c127' => array( 'model' => 'c1',
'items' => array(  ),
'align' => 'right',
'persistent' => true,
'background' => '#f6fcff' ),
'c128' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field43' ),
'border' => array( array( 'side' => 'right',
'width' => '1px',
'color' => '#0b04d1' ) ),
'background' => '#ffffee' ),
'c129' => array( 'model' => 'c2',
'items' => array(  ),
'background' => '#f6fcff' ),
'c130' => array( 'model' => 'c2',
'items' => array(  ),
'background' => '#f6fcff',
'align' => 'left' ),
'c97' => array( 'model' => 'c1',
'items' => array(  ),
'background' => '#f6fcff' ),
'c98' => array( 'model' => 'c1',
'items' => array(  ),
'background' => '#f6fcff' ),
'c132' => array( 'model' => 'c1',
'items' => array(  ),
'align' => 'center',
'color' => '#0b04d1',
'width' => '20px',
'persistent' => true,
'background' => '#f6fcff' ),
'c133' => array( 'model' => 'c1',
'items' => array( 'edit_field_label20' ),
'width' => '180px',
'align' => 'right',
'background' => '#ffffee',
'border' => array( array( 'side' => 'left',
'width' => '1px',
'color' => '#0b04d1' ) ) ),
'c134' => array( 'model' => 'c2',
'items' => array(  ),
'background' => '#f6fcff' ),
'c135' => array( 'model' => 'c3',
'items' => array( 'edit_field_label25' ),
'background' => '#fffee4' ),
'c136' => array( 'model' => 'c3',
'items' => array( 'edit_field_label26' ),
'background' => '#fffee4' ),
'c137' => array( 'model' => 'c1',
'items' => array( 'text5' ),
'align' => 'center',
'color' => '#ffffff',
'background' => '#0b04d1',
'bold' => true,
'border' => array( array( 'side' => '',
'width' => '1px',
'color' => '#0b04d1' ) ) ),
'c138' => array( 'model' => 'c1',
'items' => array( 'edit_field_label21' ),
'align' => 'right',
'border' => array( array( 'side' => 'left',
'width' => '1px',
'color' => '#0b04d1' ) ),
'background' => '#ffffee' ),
'c139' => array( 'model' => 'c1',
'items' => array( 'edit_field_label22' ),
'align' => 'right',
'background' => '#ffffee',
'border' => array( array( 'side' => 'left',
'width' => '1px',
'color' => '#0b04d1' ) ) ),
'c140' => array( 'model' => 'c1',
'items' => array( 'edit_field_label23' ),
'align' => 'right',
'background' => '#ffffee',
'border' => array( array( 'side' => 'left',
'width' => '1px',
'color' => '#0b04d1' ) ) ),
'c141' => array( 'model' => 'c1',
'items' => array( 'edit_field_label24' ),
'align' => 'right',
'background' => '#ffffee',
'border' => array( array( 'side' => 'left',
'width' => '1px',
'color' => '#0b04d1' ),
array( 'side' => 'bottom',
'width' => '1px',
'color' => '#0b04d1' ) ) ),
'c20' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field' ),
'width' => '150px',
'persistent' => true,
'align' => 'left',
'background' => '#f6fcff' ),
'c101' => array( 'model' => 'c2',
'items' => array(  ),
'align' => 'right',
'background' => '#f6fcff' ),
'c116' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field21' ),
'background' => '#f6fcff' ),
'c123' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field12' ),
'background' => '#f6fcff',
'align' => 'left',
'padding' => array( 'top' => '-12px' ) ),
'c142' => array( 'model' => 'c1',
'items' => array( 'edit_field_label14' ),
'align' => 'right',
'border' => array( array( 'side' => 'left',
'width' => '1px',
'color' => '#0b04d1' ) ),
'background' => '#ffffee' ),
'c131' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field17' ),
'border' => array( array( 'side' => 'right',
'width' => '1px',
'color' => '#0b04d1' ) ),
'background' => '#ffffee' ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section4' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c3' ),
array( 'cell' => 'c2' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c10' ),
array( 'cell' => 'c9' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c7' ),
array( 'cell' => 'c8' ) ) ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array( 'text2' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'width' => '30%',
'background' => '#effffe' ),
'c2' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field5' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'orientation' => 'vertical',
'background' => '#effffe' ),
'c7' => array( 'model' => 'c3',
'items' => array( 'text4' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'width' => '30%',
'background' => '#effffe' ),
'c8' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field28' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'orientation' => 'vertical',
'background' => '#effffe' ),
'c9' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field4' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'orientation' => 'vertical',
'background' => '#effffe' ),
'c10' => array( 'model' => 'c3',
'items' => array( 'text3' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'width' => '30%',
'background' => '#effffe' ) ),
'deferredItems' => array(  ),
'columnCount' => 2,
'inlineLabels' => false,
'separateLabels' => false ),
'section6' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c3' ),
array( 'cell' => 'c' ),
array( 'cell' => 'c1' ),
array( 'cell' => 'c8' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c25' ),
array( 'cell' => 'c26' ),
array( 'cell' => 'c6' ),
array( 'cell' => 'c9' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c42' ),
array( 'cell' => 'c43' ),
array( 'cell' => 'c7' ),
array( 'cell' => 'c10' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c54',
'colspan' => 2 ),
array( 'cell' => 'c5' ),
array( 'cell' => 'c11' ) ) ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field22' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'orientation' => 'vertical',
'width' => '100px',
'background' => '#fff3e2',
'persistent' => true ),
'c' => array( 'model' => 'c3',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'orientation' => 'vertical',
'width' => '100px',
'background' => '#fff3e2',
'persistent' => true ),
'c5' => array( 'model' => 'c3',
'items' => array(  ),
'background' => '#fff3e2' ),
'c25' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field37' ),
'orientation' => 'vertical',
'width' => '100px',
'background' => '#fff3e2',
'persistent' => true ),
'c26' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field33' ),
'orientation' => 'vertical',
'width' => '100px',
'background' => '#fff3e2',
'persistent' => true ),
'c42' => array( 'model' => 'c3',
'items' => array( 'text6' ),
'width' => '100px',
'background' => '#fff3e2',
'persistent' => true,
'align' => 'right' ),
'c43' => array( 'model' => 'c3',
'items' => array( 'orderTotal' ),
'width' => '100px',
'background' => '#fff3e2',
'persistent' => true,
'align' => 'left' ),
'c54' => array( 'model' => 'c3',
'items' => array( 'details_preview1' ),
'width' => '150px',
'background' => '#fff3e2',
'padding' => array( 'top' => '10px' ) ),
'c1' => array( 'model' => 'c3',
'items' => array(  ),
'background' => '#fff3e2' ),
'c6' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field38' ),
'background' => '#fff3e2' ),
'c7' => array( 'model' => 'c3',
'items' => array(  ),
'background' => '#fff3e2' ),
'c8' => array( 'model' => 'c3',
'items' => array(  ),
'width' => '80px',
'persistent' => true ),
'c9' => array( 'model' => 'c2',
'items' => array(  ) ),
'c10' => array( 'model' => 'c3',
'items' => array(  ) ),
'c11' => array( 'model' => 'c3',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'columnCount' => 4,
'inlineLabels' => false,
'separateLabels' => false ),
'section' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'background' => '#effffe' ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section1' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'background' => '#effffe' ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section3' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c',
'colspan' => 2 ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ) ) ),
'cells' => array( 'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field24' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'width' => '25%',
'background' => '#effffe' ),
'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field30' ),
'width' => '12%',
'background' => '#effffe' ),
'c2' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field23' ),
'width' => '13%',
'background' => '#effffe' ) ),
'deferredItems' => array(  ),
'columnCount' => 2,
'inlineLabels' => false,
'separateLabels' => false ),
'section7' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ) ) ) ),
'cells' => array( 'c' => array( 'model' => 'c1',
'items' => array( 'details_preview2' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section8' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ) ),
array( 'cells' => array( array( 'cell' => 'c' ),
array( 'cell' => 'c5' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c6',
'colspan' => 2 ) ) ) ),
'cells' => array( 'c' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field25' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'background' => '#effffe' ),
'c5' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field27' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'background' => '#effffe' ),
'c6' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field32' ),
'align' => 'center',
'background' => '#eff8ff' ),
'c1' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field14' ),
'background' => '#effffe' ),
'c2' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field26' ),
'background' => '#effffe' ) ),
'deferredItems' => array(  ),
'columnCount' => 4,
'inlineLabels' => false,
'separateLabels' => false ),
'section9' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'details_preview4' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section10' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'details_preview' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section5' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c8' ),
array( 'cell' => 'c9' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c6' ),
array( 'cell' => 'c7' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c4' ),
array( 'cell' => 'c5' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2' ),
array( 'cell' => 'c3' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_field_label4' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field7' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c1',
'items' => array(  ) ),
'c3' => array( 'model' => 'c1',
'items' => array(  ) ),
'c4' => array( 'model' => 'c1',
'items' => array(  ) ),
'c5' => array( 'model' => 'c1',
'items' => array(  ) ),
'c6' => array( 'model' => 'c1',
'items' => array(  ) ),
'c7' => array( 'model' => 'c1',
'items' => array(  ) ),
'c8' => array( 'model' => 'c1',
'items' => array( 'edit_field_label11' ) ),
'c9' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field2' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'add_header' => array( 'type' => 'add_header',
'title' => array( 'page' => 'add',
'table' => 'dbo.Calls',
'type' => 7 ) ),
'integrated_edit_field41' => array( 'field' => 'callGdprAcceptance',
'type' => 'edit_field',
'orientation' => 0,
'joined' => false,
'separated' => true,
'nowrap' => true ),
'text' => array( 'type' => 'text',
'label' => array( 'text' => 'Αποτέλεσμα',
'type' => 0 ),
'editedByRte' => false,
'color' => '#0079ad',
'mobileDisplay' => '',
'font-size' => '16px',
'padding' => array( 'top' => '20px' ) ),
'add_save' => array( 'type' => 'add_save' ),
'add_back_list' => array( 'type' => 'add_back_list' ),
'add_cancel' => array( 'type' => 'add_cancel' ),
'integrated_edit_field9' => array( 'field' => 'remarks',
'type' => 'edit_field',
'orientation' => 1,
'label' => array( 'field' => 'remarks',
'table' => 'dbo.Calls',
'type' => 3 ),
'joined' => false,
'separated' => true ),
'integrated_edit_field24' => array( 'field' => 'dialerRecording',
'type' => 'integrated_edit_field',
'orientation' => 0,
'joined' => true,
'separated' => false,
'nowrap' => false ),
'edit_field_label4' => array( 'type' => 'edit_field_label',
'field' => 'callStatusId',
'separated' => true ),
'section2' => array( 'type' => 'section',
'title' => array( 'text' => 'Call Results',
'type' => 0 ),
'location' => 'section5',
'initiallyClosed' => true ),
'integrated_edit_field4' => array( 'field' => 'broadcast',
'type' => 'edit_field',
'orientation' => 0,
'nowrap' => true,
'joined' => false,
'separated' => true ),
'section' => array( 'type' => 'section',
'title' => array( 'text' => 'Στοιχεία Κλήσης',
'type' => 0 ),
'location' => 'section2',
'mobileDisplay' => '' ),
'integrated_edit_field23' => array( 'field' => 'dialerCallEpoch',
'type' => 'integrated_edit_field',
'orientation' => 1,
'joined' => true,
'separated' => false ),
'section8' => array( 'type' => 'section',
'title' => array( 'text' => 'Χρόνοι',
'type' => 0 ),
'location' => 'section8',
'initiallyClosed' => true ),
'integrated_edit_field42' => array( 'field' => 'callGdprRecordingAcceptance',
'type' => 'edit_field',
'orientation' => 0,
'nowrap' => true,
'label' => array( 'field' => 'callGdprRecordingAcceptance',
'table' => 'dbo.Calls',
'type' => 3 ),
'joined' => false,
'separated' => true ),
'integrated_edit_field14' => array( 'field' => 'callHangup',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field30' => array( 'field' => 'dialerLeadID',
'type' => 'integrated_edit_field',
'orientation' => 1,
'joined' => true,
'separated' => false ),
'section6' => array( 'type' => 'section',
'title' => array( 'text' => 'Dialer Data',
'type' => 0 ),
'location' => 'section3',
'initiallyClosed' => true ),
'integrated_edit_field13' => array( 'field' => 'dialerCampaign',
'type' => 'edit_field',
'orientation' => 1,
'joined' => false,
'separated' => true,
'width' => '80px' ),
'integrated_edit_field34' => array( 'field' => 'contactName',
'type' => 'edit_field',
'orientation' => 1,
'joined' => false,
'separated' => true,
'padding' => array( 'top' => '5px' ) ),
'text8' => array( 'type' => 'text',
'label' => array( 'text' => 'Συλλογή Στοιχείων Επαφής',
'type' => 0 ),
'editedByRte' => false,
'bold' => true,
'font-size' => '14px' ),
'integrated_edit_field19' => array( 'field' => 'courierDeliveryDate',
'type' => 'integrated_edit_field',
'orientation' => 1,
'joined' => true,
'separated' => false,
'label' => array( 'field' => 'courierDeliveryDate',
'table' => 'dbo.Calls',
'type' => 3 ) ),
'details_preview' => array( 'type' => 'details_preview',
'table' => 'dbo.voltonApplications',
'items' => array(  ),
'popup' => false,
'pageId' => 'voltonInDetailAddList',
'mobileDisplay' => 'both' ),
'section10' => array( 'type' => 'section',
'title' => array( 'text' => 'Αιτήσεις Volton',
'type' => 0 ),
'location' => 'section10',
'initiallyClosed' => true ),
'integrated_edit_field16' => array( 'field' => 'courier',
'type' => 'edit_field',
'orientation' => 0,
'joined' => false,
'separated' => true ),
'integrated_edit_field18' => array( 'field' => 'callComments',
'type' => 'edit_field',
'orientation' => 1,
'nowrap' => false,
'joined' => false,
'separated' => true ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'logo1' => array( 'type' => 'logo' ),
'details_preview2' => array( 'type' => 'details_preview',
'table' => 'dbo.internalComments',
'items' => array(  ),
'popup' => false,
'pageId' => 'list' ),
'integrated_edit_field29' => array( 'field' => 'dialerList',
'type' => 'edit_field',
'orientation' => 1,
'joined' => false,
'separated' => true,
'width' => '80px' ),
'integrated_edit_field10' => array( 'field' => 'deliveryComments',
'type' => 'edit_field',
'orientation' => 0,
'joined' => false,
'separated' => true ),
'details_preview4' => array( 'type' => 'details_preview',
'table' => 'dbo.novaApplications',
'items' => array(  ),
'popup' => false,
'pageId' => 'novaInlineAddList' ),
'section7' => array( 'type' => 'section',
'title' => array( 'text' => 'Εσωτερική Επικοινωνία',
'type' => 0 ),
'location' => 'section7',
'initiallyClosed' => true ),
'integrated_edit_field17' => array( 'field' => 'contactAge',
'type' => 'edit_field',
'orientation' => 1,
'joined' => false,
'separated' => true ),
'integrated_edit_field2' => array( 'field' => 'callDenialReasonID',
'type' => 'edit_field',
'orientation' => 1,
'joined' => false,
'separated' => true,
'color' => '#ff0505' ),
'integrated_edit_field7' => array( 'field' => 'callStatusId',
'type' => 'edit_field',
'orientation' => 1,
'label' => array( 'field' => 'callStatusId',
'table' => 'dbo.Calls',
'type' => 3 ),
'joined' => false,
'separated' => true ),
'integrated_edit_field26' => array( 'field' => 'talkTime',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'edit_field_label14' => array( 'type' => 'edit_field_label',
'field' => 'contactAge',
'separated' => true,
'label' => array( 'field' => 'contactAge',
'table' => 'dbo.Calls',
'type' => 3 ) ),
'integrated_edit_field12' => array( 'field' => 'redialIsPrivate',
'type' => 'edit_field',
'orientation' => 1,
'joined' => false,
'separated' => true ),
'integrated_edit_field21' => array( 'field' => 'courierTimeTo',
'type' => 'edit_field',
'orientation' => 1,
'joined' => false,
'separated' => true ),
'integrated_edit_field' => array( 'field' => 'dialerPhone',
'type' => 'edit_field',
'orientation' => 1,
'label' => array( 'field' => 'dialerPhone',
'table' => 'dbo.Calls',
'type' => 3 ),
'joined' => false,
'separated' => true,
'padding' => array( 'top' => '5px' ) ),
'edit_field_label1' => array( 'type' => 'edit_field_label',
'field' => 'dialerCampaign',
'separated' => true ),
'edit_field_label2' => array( 'type' => 'edit_field_label',
'field' => 'dialerList',
'separated' => true ),
'section5' => array( 'type' => 'section',
'title' => array( 'text' => 'Αγορές Πελάτη',
'type' => 0 ),
'location' => 'section1',
'initiallyClosed' => true ),
'edit_field_label24' => array( 'type' => 'edit_field_label',
'field' => 'contactCity',
'separated' => true ),
'edit_field_label23' => array( 'type' => 'edit_field_label',
'field' => 'ContactArea',
'separated' => true ),
'edit_field_label22' => array( 'type' => 'edit_field_label',
'field' => 'contactZipCode',
'separated' => true ),
'integrated_edit_field15' => array( 'field' => 'contactMethod',
'type' => 'edit_field',
'orientation' => 0,
'label' => array( 'field' => 'contactMethod',
'table' => 'dbo.Calls',
'type' => 3 ),
'joined' => false,
'separated' => true ),
'integrated_edit_field5' => array( 'field' => 'tvchannel',
'type' => 'edit_field',
'orientation' => 0,
'nowrap' => true,
'joined' => false,
'separated' => true ),
'edit_field_label21' => array( 'type' => 'edit_field_label',
'field' => 'contactGender',
'separated' => true ),
'text5' => array( 'type' => 'text',
'label' => array( 'text' => 'Συλλογή Στοιχείων Επαφής',
'type' => 0 ),
'editedByRte' => false,
'bold' => true,
'font-size' => '14px' ),
'edit_field_label26' => array( 'type' => 'edit_field_label',
'field' => 'callGdprAcceptance',
'separated' => true ),
'edit_field_label25' => array( 'type' => 'edit_field_label',
'field' => 'callGdprRecordingAcceptance',
'separated' => true ),
'edit_field_label20' => array( 'type' => 'edit_field_label',
'field' => 'contactName',
'separated' => true,
'padding' => array( 'top' => '10px' ) ),
'integrated_edit_field38' => array( 'field' => 'orderInvoiceRequired',
'type' => 'integrated_edit_field',
'orientation' => 0,
'joined' => true,
'separated' => false ),
'section9' => array( 'type' => 'section',
'title' => array( 'text' => 'Αιτήσεις Nova',
'type' => 0 ),
'location' => 'section9',
'initiallyClosed' => true ),
'integrated_edit_field8' => array( 'field' => 'callSubClassificationID',
'type' => 'edit_field',
'orientation' => 1,
'label' => array( 'field' => 'callSubClassificationID',
'table' => 'dbo.Calls',
'type' => 3 ),
'joined' => false,
'separated' => true ),
'btHangupWithPause' => array( 'eventId' => 'btHangupWithPauseClick',
'label' => array( 'text' => 'Hangup >> Pause',
'type' => 0 ),
'type' => 'custom_button',
'width' => '120px',
'buttonSize' => 'normal',
'buttonStyle' => 'primary',
'padding' => array( 'bottom' => '5px' ) ),
'section1' => array( 'type' => 'section',
'title' => array( 'text' => 'Πληροφορίες Κλήσης',
'type' => 0 ),
'location' => 'section4',
'initiallyClosed' => true ),
'integrated_edit_field6' => array( 'field' => 'redialComments',
'type' => 'edit_field',
'orientation' => 1,
'nowrap' => false,
'joined' => false,
'separated' => true,
'width' => '100%' ),
'integrated_edit_field43' => array( 'field' => 'contactGender',
'type' => 'edit_field',
'orientation' => 1,
'joined' => false,
'separated' => true ),
'integrated_edit_field28' => array( 'field' => 'seller',
'type' => 'edit_field',
'orientation' => 0,
'joined' => false,
'separated' => true ),
'integrated_edit_field36' => array( 'field' => 'callStart',
'type' => 'edit_field',
'orientation' => 1,
'joined' => false,
'separated' => true,
'padding' => array( 'top' => '5px' ) ),
'edit_field_label3' => array( 'type' => 'edit_field_label',
'field' => 'callStart',
'separated' => true ),
'edit_field_label13' => array( 'type' => 'edit_field_label',
'field' => 'productFamilyId',
'separated' => true ),
'integrated_edit_field3' => array( 'field' => 'callClassificationID',
'type' => 'edit_field',
'orientation' => 1,
'label' => array( 'field' => 'callClassificationID',
'table' => 'dbo.Calls',
'type' => 3 ),
'joined' => false,
'separated' => true ),
'text2' => array( 'type' => 'text',
'label' => array( 'text' => 'Κανάλι',
'type' => 0 ),
'editedByRte' => false ),
'integrated_edit_field1' => array( 'field' => 'productFamilyId',
'type' => 'edit_field',
'orientation' => 1,
'joined' => false,
'separated' => true ),
'btHangupWithResume' => array( 'eventId' => 'btHangupWithResumeClick',
'label' => array( 'text' => 'Hangup >> Active',
'type' => 0 ),
'type' => 'custom_button',
'width' => '120px',
'buttonStyle' => '',
'background' => '#109605',
'padding' => array( 'bottom' => '10px' ) ),
'integrated_edit_field40' => array( 'field' => 'ContactArea',
'type' => 'edit_field',
'orientation' => 1,
'joined' => false,
'separated' => true ),
'details_preview1' => array( 'type' => 'details_preview',
'table' => 'dbo.orderItems',
'items' => array(  ),
'popup' => false,
'pageId' => 'list',
'background' => '#edffcd' ),
'edit_field_label6' => array( 'type' => 'edit_field_label',
'field' => 'redialDate',
'separated' => true ),
'integrated_edit_field11' => array( 'field' => 'redialDate',
'type' => 'edit_field',
'orientation' => 1,
'nowrap' => true,
'joined' => false,
'separated' => true ),
'text6' => array( 'type' => 'text',
'label' => array( 'text' => 'Συνολική Αξία: ',
'type' => 0 ),
'editedByRte' => false,
'bold' => true,
'font-size' => '16px',
'color' => '#c00909' ),
'edit_field_label7' => array( 'type' => 'edit_field_label',
'field' => 'redialIsPrivate',
'separated' => true ),
'integrated_edit_field20' => array( 'field' => 'courierTimeFrom',
'type' => 'edit_field',
'orientation' => 1,
'joined' => false,
'separated' => true ),
'integrated_edit_field39' => array( 'field' => 'contactCity',
'type' => 'edit_field',
'orientation' => 1,
'joined' => false,
'separated' => true ),
'integrated_edit_field35' => array( 'field' => 'contactZipCode',
'type' => 'edit_field',
'orientation' => 1,
'joined' => false,
'separated' => true ),
'text1' => array( 'type' => 'text',
'label' => array( 'text' => 'Τερματισμός Κλήσης',
'type' => 0 ),
'editedByRte' => false,
'color' => '#0079ad',
'font-size' => '16px' ),
'custom_button_container' => array( 'type' => 'custom_button_container',
'items' => array( 'custom_button4',
'inVoltonButton',
'wasVoltonButton',
'onPhotovoltaicButton',
'haveNoPower',
'haveOtherProvider' ),
'label' => array( 'type' => 0,
'text' => 'Volton' ),
'width' => '140px',
'background' => 'transparent',
'padding' => array( 'bottom' => '5px' ),
'buttonStyle' => 'link',
'color' => '#ffffff',
'buttonSize' => 'normal' ),
'custom_button' => array( 'type' => 'custom_button',
'eventId' => 'instantDenial',
'label' => array( 'text' => 'Άμεση Άρνηση',
'type' => 0 ),
'width' => '125px',
'padding' => array( 'bottom' => '5px' ),
'buttonStyle' => '' ),
'custom_button1' => array( 'type' => 'custom_button',
'eventId' => 'phoneFaxClick',
'label' => array( 'text' => 'Τηλεφωνητής/Fax',
'type' => 0 ),
'width' => '125px',
'padding' => array( 'bottom' => '10px' ),
'buttonStyle' => 'primary' ),
'custom_button2' => array( 'eventId' => 'noAnswer',
'label' => array( 'text' => 'Δεν Απαντά',
'type' => 0 ),
'type' => 'custom_button',
'width' => '125px',
'padding' => array( 'bottom' => '5px' ),
'buttonStyle' => '' ),
'custom_button4' => array( 'eventId' => 'noInterest',
'label' => array( 'text' => 'Δεν Ενδιαφέρομαι',
'type' => 0 ),
'type' => 'custom_button',
'width' => '140px' ),
'integrated_edit_field32' => array( 'field' => 'totalCallTime',
'type' => 'integrated_edit_field',
'orientation' => 0,
'bold' => true ),
'integrated_edit_field27' => array( 'field' => 'typingTime',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field25' => array( 'field' => 'callEnd',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'text4' => array( 'type' => 'text',
'label' => array( 'text' => 'Πωλητής',
'type' => 0 ),
'editedByRte' => false ),
'section4' => array( 'type' => 'section',
'title' => array( 'text' => 'Εικόνα Πελάτη',
'type' => 0 ),
'location' => 'section',
'initiallyClosed' => true ),
'edit_field_label12' => array( 'type' => 'edit_field_label',
'field' => 'callClassificationID',
'separated' => true ),
'edit_field_label15' => array( 'type' => 'edit_field_label',
'field' => 'deliveryComments',
'separated' => true ),
'edit_field_label8' => array( 'type' => 'edit_field_label',
'field' => 'redialComments',
'separated' => true ),
'edit_field_label10' => array( 'type' => 'edit_field_label',
'field' => 'dialerPhone',
'separated' => true ),
'edit_field_label17' => array( 'type' => 'edit_field_label',
'field' => 'contactMethod',
'separated' => true ),
'edit_field_label5' => array( 'type' => 'edit_field_label',
'field' => 'remarks',
'separated' => true,
'label' => array( 'field' => 'remarks',
'table' => 'dbo.Calls',
'type' => 3 ) ),
'edit_field_label18' => array( 'type' => 'edit_field_label',
'field' => 'courier',
'separated' => true ),
'edit_field_label9' => array( 'type' => 'edit_field_label',
'field' => 'callComments',
'separated' => true ),
'inVoltonButton' => array( 'eventId' => 'inVolton',
'label' => array( 'text' => 'Είμαι στη Volton',
'type' => 0 ),
'type' => 'custom_button',
'width' => '140px' ),
'wasVoltonButton' => array( 'eventId' => 'pastVoltonSubscriber',
'label' => array( 'text' => 'Ήμουν στη Volton',
'type' => 0 ),
'type' => 'custom_button',
'width' => '140px' ),
'onPhotovoltaicButton' => array( 'eventId' => 'havePVPanels',
'label' => array( 'text' => 'Έχω Φωτοβολταϊκά',
'type' => 0 ),
'type' => 'custom_button',
'width' => '140px' ),
'haveNoPower' => array( 'eventId' => 'dontHavePower',
'label' => array( 'text' => 'Δεν σας Εμπιστεύομαι',
'type' => 0 ),
'type' => 'custom_button',
'width' => '140px' ),
'haveOtherProvider' => array( 'eventId' => 'otherProvider',
'label' => array( 'text' => 'Έχω Άλλο Πάροχο',
'type' => 0 ),
'type' => 'custom_button',
'width' => '140px' ),
'custom_button_container1' => array( 'type' => 'custom_button_container',
'items' => array( 'custom_button7',
'custom_button5',
'custom_button6',
'custom_button3' ),
'label' => array( 'type' => 0,
'text' => 'Nova' ),
'width' => '140px',
'buttonStyle' => 'link',
'background' => 'transparent',
'color' => '#ffffff',
'padding' => array( 'bottom' => '5px' ),
'buttonSize' => 'normal' ),
'custom_button_container2' => array( 'type' => 'custom_button_container',
'items' => array( 'custom_button8' ),
'label' => array( 'type' => 0,
'text' => 'Προϊόντα' ),
'background' => 'transparent',
'padding' => array( 'bottom' => '25px' ),
'width' => '140px',
'buttonStyle' => 'link-button',
'color' => '#ffffff',
'buttonSize' => 'normal' ),
'orderTotal' => array( 'type' => 'text',
'label' => array( 'text' => '0',
'type' => 0 ),
'editedByRte' => false,
'padding' => array( 'left' => '5px' ),
'bold' => true,
'font-size' => '16px',
'color' => '#c00909' ),
'custom_button3' => array( 'eventId' => 'novaNoAvailability',
'label' => array( 'text' => 'Χωρίς Διαθεσιμότητα',
'type' => 0 ),
'type' => 'custom_button',
'width' => '140px' ),
'custom_button5' => array( 'eventId' => 'novaOtherProvider',
'label' => array( 'text' => 'Έχω Δέσμευση',
'type' => 0 ),
'type' => 'custom_button',
'width' => '140px' ),
'custom_button6' => array( 'eventId' => 'novaExistingCustomer',
'label' => array( 'text' => 'Έχω Nova',
'type' => 0 ),
'type' => 'custom_button',
'width' => '140px' ),
'custom_button7' => array( 'eventId' => 'novaNotIneterested',
'label' => array( 'text' => 'Δεν Ενδιαφέρομαι',
'type' => 0 ),
'type' => 'custom_button',
'width' => '140px' ),
'custom_button8' => array( 'eventId' => 'productsNotInterested',
'label' => array( 'text' => 'Δεν Ενδιαφέρομαι',
'type' => 0 ),
'type' => 'custom_button',
'width' => '140px' ),
'custom_button9' => array( 'eventId' => 'noComm1',
'label' => array( 'text' => 'Αδύνατη Επικοινωνία',
'type' => 0 ),
'type' => 'custom_button',
'buttonStyle' => 'danger',
'width' => '125px',
'padding' => array( 'bottom' => '25px' ) ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'logout_link',
'adminarea_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => true ),
'logout_link' => array( 'type' => 'logout_link' ),
'edit_field_label11' => array( 'type' => 'edit_field_label',
'field' => 'callDenialReasonID',
'separated' => true,
'color' => '#ff0505' ),
'text3' => array( 'type' => 'text',
'label' => array( 'text' => 'Εκπομπή',
'type' => 0 ),
'editedByRte' => false ),
'text7' => array( 'type' => 'text',
'label' => array( 'text' => 'Αρνητικό Αποτέλεσμα',
'type' => 0 ),
'editedByRte' => false,
'color' => '#ff0000',
'mobileDisplay' => '',
'font-size' => '16px' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'integrated_edit_field33' => array( 'field' => 'orderPaymentMethod',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field37' => array( 'field' => 'orderShipCompany',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field22' => array( 'field' => 'contactId',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'section3' => array( 'type' => 'section',
'title' => array( 'text' => 'Παραγγελία Προϊόντων',
'type' => 0 ),
'location' => 'section6',
'initiallyClosed' => true ),
'expand_button' => array( 'type' => 'expand_button' ) ),
'dbProps' => array(  ),
'version' => 4,
'pageWidth' => 'full',
'barWidth' => '200px' );
		?>