<?php
			$optionsArray = array( 'list' => array( 'inlineAdd' => true,
'detailsAdd' => true,
'inlineEdit' => true,
'delete' => false,
'updateSelected' => false,
'addInPopup' => null,
'editInPopup' => null,
'viewInPopup' => null,
'clickSort' => false,
'sortDropdown' => false,
'showHideFields' => true,
'reorderFields' => false ),
'listSearch' => array( 'alwaysOnPanelFields' => array(  ),
'searchPanel' => true,
'fixedSearchPanel' => false,
'simpleSearchOptions' => false,
'searchSaving' => false ),
'totals' => array( 'id' => array( 'totalsType' => '' ),
'callphone' => array( 'totalsType' => '' ),
'agent' => array( 'totalsType' => '' ),
'dialerCampaign' => array( 'totalsType' => '' ),
'dialerList' => array( 'totalsType' => '' ),
'callDate' => array( 'totalsType' => '' ),
'agentApplicationStatus' => array( 'totalsType' => '' ),
'applicationStatusId' => array( 'totalsType' => '' ),
'applicationPhaseStatusId' => array( 'totalsType' => '' ),
'lastStatusDate' => array( 'totalsType' => '' ),
'applicationAge' => array( 'totalsType' => '' ),
'forCount' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array(  ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array( 'id',
'applicationStatusId' ),
'filterFields' => array( 'applicationStatusId' ),
'inlineAddFields' => array(  ),
'inlineEditFields' => array(  ),
'fieldItems' => array(  ),
'hideEmptyFields' => array(  ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => true ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array( 'logo',
'menu',
'simple_search',
'list_options',
'loginform_login',
'username_button' ),
'left' => array( 'search_panel',
'filter_panel' ),
'top' => array( 'breadcrumb' ),
'above-grid' => array( 'inline_add',
'inline_save_all',
'inline_cancel_all',
'details_found',
'page_size',
'print_panel',
'columns_control' ),
'below-grid' => array( 'pagination' ),
'grid' => array( 'grid_checkbox',
'grid_inline_edit',
'grid_inline_save',
'grid_inline_cancel',
'grid_copy',
'grid_alldetails_link',
'grid_details_link',
'details_preview',
'text3',
'text',
'text1',
'text2',
'text4',
'image',
'text5',
'inline_add1',
'text6' ) ),
'formXtTags' => array( 'top' => array( 'breadcrumb' ),
'below-grid' => array( 'pagination' ) ),
'itemForms' => array( 'logo' => 'supertop',
'menu' => 'supertop',
'simple_search' => 'supertop',
'list_options' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'search_panel' => 'left',
'filter_panel' => 'left',
'breadcrumb' => 'top',
'inline_add' => 'above-grid',
'inline_save_all' => 'above-grid',
'inline_cancel_all' => 'above-grid',
'details_found' => 'above-grid',
'page_size' => 'above-grid',
'print_panel' => 'above-grid',
'columns_control' => 'above-grid',
'pagination' => 'below-grid',
'grid_checkbox' => 'grid',
'grid_inline_edit' => 'grid',
'grid_inline_save' => 'grid',
'grid_inline_cancel' => 'grid',
'grid_copy' => 'grid',
'grid_alldetails_link' => 'grid',
'grid_details_link' => 'grid',
'details_preview' => 'grid',
'text3' => 'grid',
'text' => 'grid',
'text1' => 'grid',
'text2' => 'grid',
'text4' => 'grid',
'image' => 'grid',
'text5' => 'grid',
'inline_add1' => 'grid',
'text6' => 'grid' ),
'itemLocations' => array( 'grid_checkbox' => array( 'location' => 'grid',
'cellId' => 'cell_top' ),
'grid_inline_edit' => array( 'location' => 'grid',
'cellId' => 'cell_top' ),
'grid_inline_save' => array( 'location' => 'grid',
'cellId' => 'cell_top' ),
'grid_inline_cancel' => array( 'location' => 'grid',
'cellId' => 'cell_top' ),
'grid_copy' => array( 'location' => 'grid',
'cellId' => 'cell_top' ),
'grid_alldetails_link' => array( 'location' => 'grid',
'cellId' => 'cell_top' ),
'grid_details_link' => array( 'location' => 'grid',
'cellId' => 'cell_top' ),
'details_preview' => array( 'location' => 'grid',
'cellId' => 'cell_dpreview' ),
'text3' => array( 'location' => 'grid',
'cellId' => 'cell_label3' ),
'text' => array( 'location' => 'grid',
'cellId' => 'cell_field61' ),
'text1' => array( 'location' => 'grid',
'cellId' => 'cell_label72' ),
'text2' => array( 'location' => 'grid',
'cellId' => 'cell_label68' ),
'text4' => array( 'location' => 'grid',
'cellId' => 'cell_label114' ),
'image' => array( 'location' => 'grid',
'cellId' => 'cell_field93' ),
'text5' => array( 'location' => 'grid',
'cellId' => 'cell_field94' ),
'inline_add1' => array( 'location' => 'grid',
'cellId' => 'cell_field28' ),
'text6' => array( 'location' => 'grid',
'cellId' => 'cell_label42' ) ),
'itemVisiblity' => array( 'menu' => 3,
'simple_search' => 3,
'list_options' => 3,
'loginform_login' => 3,
'username_button' => 3,
'search_panel' => 5,
'filter_panel' => 3,
'print_panel' => 5 ) ),
'itemsByType' => array( 'export_selected' => array( 'export_selected' ),
'inline_add' => array( 'inline_add',
'inline_add1' ),
'inline_save_all' => array( 'inline_save_all' ),
'inline_cancel_all' => array( 'inline_cancel_all' ),
'details_found' => array( 'details_found' ),
'page_size' => array( 'page_size' ),
'print_panel' => array( 'print_panel' ),
'print_scope' => array( 'print_scope' ),
'print_records' => array( 'print_records' ),
'print_button' => array( 'print_button' ),
'pagination' => array( 'pagination' ),
'grid_checkbox' => array( 'grid_checkbox' ),
'-' => array( '-4',
'-3',
'-2',
'-1',
'-' ),
'grid_inline_edit' => array( 'grid_inline_edit' ),
'grid_inline_save' => array( 'grid_inline_save' ),
'grid_inline_cancel' => array( 'grid_inline_cancel' ),
'grid_copy' => array( 'grid_copy' ),
'export' => array( 'export' ),
'grid_checkbox_head' => array( 'grid_checkbox_head' ),
'search_panel_field' => array( 'search_panel_field',
'search_panel_field2' ),
'edit_selected' => array( 'edit_selected' ),
'advsearch_link' => array( 'advsearch_link' ),
'show_search_panel' => array( 'show_search_panel' ),
'hide_search_panel' => array( 'hide_search_panel' ),
'breadcrumb' => array( 'breadcrumb' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'simple_search' => array( 'simple_search' ),
'search_panel' => array( 'search_panel' ),
'list_options' => array( 'list_options' ),
'text' => array( 'text',
'text1',
'text2',
'text3',
'text4',
'text5',
'text6' ),
'image' => array( 'image' ),
'print_details' => array( 'print_details' ),
'details_preview' => array( 'details_preview' ),
'grid_alldetails_link' => array( 'grid_alldetails_link' ),
'grid_details_link' => array( 'grid_details_link' ),
'filter_panel' => array( 'filter_panel' ),
'filter_panel_field' => array( 'filter_panel_field' ),
'columns_control' => array( 'columns_control' ),
'username_button' => array( 'username_button' ),
'adminarea_link' => array( 'adminarea_link' ),
'loginform_login' => array( 'loginform_login' ),
'logout_link' => array( 'logout_link' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'cell_top' => array( 'cols' => array( 0,
1,
2,
3,
4,
5 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'grid_checkbox',
'grid_inline_edit',
'grid_inline_save',
'grid_inline_cancel',
'grid_copy',
'grid_alldetails_link',
'grid_details_link' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'cell_field93' => array( 'cols' => array( 0 ),
'rows' => array( 1,
2 ),
'tags' => array(  ),
'items' => array( 'image' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'cell_field94' => array( 'cols' => array( 1,
2,
3 ),
'rows' => array( 1,
2 ),
'tags' => array(  ),
'items' => array( 'text5' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'cell_field120' => array( 'cols' => array( 4 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field121' => array( 'cols' => array( 5 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field126' => array( 'cols' => array( 4 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field127' => array( 'cols' => array( 5 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field61' => array( 'cols' => array( 0,
1,
2,
3,
4,
5 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'text' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'cell_label72' => array( 'cols' => array( 0,
1,
2,
3,
4,
5 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'text1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'cell_field95' => array( 'cols' => array( 0 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'cell_field124' => array( 'cols' => array( 1,
2 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'cell_field128' => array( 'cols' => array( 3 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'cell_field129' => array( 'cols' => array( 4 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'cell_field130' => array( 'cols' => array( 5 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'cell_label68' => array( 'cols' => array( 0,
1,
2,
3,
4,
5 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array( 'text2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'cell_field114' => array( 'cols' => array( 0 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'cell_field115' => array( 'cols' => array( 1 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'cell_field116' => array( 'cols' => array( 2 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'cell_field117' => array( 'cols' => array( 3 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'cell_field118' => array( 'cols' => array( 4 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'cell_field119' => array( 'cols' => array( 5 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'cell_label3' => array( 'cols' => array( 0,
1,
2,
3,
4,
5 ),
'rows' => array( 8 ),
'tags' => array(  ),
'items' => array( 'text3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'cell_label133' => array( 'cols' => array( 0 ),
'rows' => array( 9 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'cell_label134' => array( 'cols' => array( 1 ),
'rows' => array( 9 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'cell_label135' => array( 'cols' => array( 2 ),
'rows' => array( 9 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'cell_label136' => array( 'cols' => array( 3 ),
'rows' => array( 9 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'cell_label137' => array( 'cols' => array( 4 ),
'rows' => array( 9 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'cell_label138' => array( 'cols' => array( 5 ),
'rows' => array( 9 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'cell_label114' => array( 'cols' => array( 0,
1,
2,
3,
4,
5 ),
'rows' => array( 10 ),
'tags' => array(  ),
'items' => array( 'text4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'cell_label24' => array( 'cols' => array( 0 ),
'rows' => array( 11 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'cell_field24' => array( 'cols' => array( 1 ),
'rows' => array( 11 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'cell_label25' => array( 'cols' => array( 2 ),
'rows' => array( 11 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'cell_field25' => array( 'cols' => array( 3 ),
'rows' => array( 11 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'cell_label26' => array( 'cols' => array( 4 ),
'rows' => array( 11 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'cell_field26' => array( 'cols' => array( 5 ),
'rows' => array( 11 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label38' => array( 'cols' => array( 0 ),
'rows' => array( 12 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label39' => array( 'cols' => array( 1 ),
'rows' => array( 12 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label40' => array( 'cols' => array( 2 ),
'rows' => array( 12 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label41' => array( 'cols' => array( 3 ),
'rows' => array( 12 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label42' => array( 'cols' => array( 4 ),
'rows' => array( 12 ),
'tags' => array(  ),
'items' => array( 'text6' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'cell_label43' => array( 'cols' => array( 5 ),
'rows' => array( 12 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label' => array( 'cols' => array( 0 ),
'rows' => array( 13 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label27' => array( 'cols' => array( 1 ),
'rows' => array( 13 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label28' => array( 'cols' => array( 2 ),
'rows' => array( 13 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label29' => array( 'cols' => array( 3 ),
'rows' => array( 13 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label30' => array( 'cols' => array( 4 ),
'rows' => array( 13 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label31' => array( 'cols' => array( 5 ),
'rows' => array( 13 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field28' => array( 'cols' => array( 0,
1,
2 ),
'rows' => array( 14 ),
'tags' => array( 'inlineadd_link' ),
'items' => array( 'inline_add1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field30' => array( 'cols' => array( 3 ),
'rows' => array( 14 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field31' => array( 'cols' => array( 4 ),
'rows' => array( 14 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field32' => array( 'cols' => array( 5 ),
'rows' => array( 14 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_dpreview' => array( 'cols' => array( 0,
1,
2,
3,
4,
5 ),
'rows' => array( 15 ),
'tags' => array(  ),
'items' => array( 'details_preview' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 6,
'height' => 16 ) ) ),
'loginForm' => array( 'loginForm' => 1 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array( 'details_found' => array( 'tag' => 'DISPLAYING',
'type' => 2 ) ) ),
'gridType' => 2,
'recsPerRow' => 1,
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'list',
'breadcrumb' => true ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dataGrid' => array( 'groupFields' => array(  ) ) );
			$pageArray = array( 'id' => 'novaInlineAddList',
'type' => 'list',
'layoutId' => 'topbar',
'disabled' => 0,
'default' => 1,
'forms' => array( 'supertop' => array( 'modelId' => 'topbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'logo',
'menu' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'simple_search',
'list_options',
'loginform_login',
'username_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'list-vbar',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'search_panel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'filter_panel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'list-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'breadcrumb' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'list-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'inline_add',
'inline_save_all',
'inline_cancel_all' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'details_found',
'page_size',
'print_panel',
'columns_control' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'list-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'pagination' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'columns-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'cell_top',
'colspan' => 6 ) ),
'section' => 'head' ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_field93',
'rowspan' => 2 ),
array( 'cell' => 'cell_field94',
'colspan' => 3,
'rowspan' => 2 ),
array( 'cell' => 'cell_field120' ),
array( 'cell' => 'cell_field121' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_field126' ),
array( 'cell' => 'cell_field127' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_field61',
'colspan' => 6 ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_label72',
'colspan' => 6 ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_field95' ),
array( 'cell' => 'cell_field124',
'colspan' => 2 ),
array( 'cell' => 'cell_field128' ),
array( 'cell' => 'cell_field129' ),
array( 'cell' => 'cell_field130' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_label68',
'colspan' => 6 ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_field114' ),
array( 'cell' => 'cell_field115' ),
array( 'cell' => 'cell_field116' ),
array( 'cell' => 'cell_field117' ),
array( 'cell' => 'cell_field118' ),
array( 'cell' => 'cell_field119' ) ) ),
array( 'cells' => array( array( 'cell' => 'cell_label3',
'colspan' => 6 ) ),
'section' => 'body' ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_label133' ),
array( 'cell' => 'cell_label134' ),
array( 'cell' => 'cell_label135' ),
array( 'cell' => 'cell_label136' ),
array( 'cell' => 'cell_label137' ),
array( 'cell' => 'cell_label138' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_label114',
'colspan' => 6 ) ) ),
array( 'cells' => array( array( 'cell' => 'cell_label24' ),
array( 'cell' => 'cell_field24' ),
array( 'cell' => 'cell_label25' ),
array( 'cell' => 'cell_field25' ),
array( 'cell' => 'cell_label26' ),
array( 'cell' => 'cell_field26' ) ),
'section' => 'body' ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_label38' ),
array( 'cell' => 'cell_label39' ),
array( 'cell' => 'cell_label40' ),
array( 'cell' => 'cell_label41' ),
array( 'cell' => 'cell_label42' ),
array( 'cell' => 'cell_label43' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_label' ),
array( 'cell' => 'cell_label27' ),
array( 'cell' => 'cell_label28' ),
array( 'cell' => 'cell_label29' ),
array( 'cell' => 'cell_label30' ),
array( 'cell' => 'cell_label31' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_field28',
'colspan' => 3 ),
array( 'cell' => 'cell_field30' ),
array( 'cell' => 'cell_field31' ),
array( 'cell' => 'cell_field32' ) ) ),
array( 'cells' => array( array( 'cell' => 'cell_dpreview',
'colspan' => 6 ) ),
'section' => 'foot' ) ),
'cells' => array( 'cell_top' => array( 'model' => 'cell_top',
'items' => array( 'grid_checkbox',
'grid_inline_edit',
'grid_inline_save',
'grid_inline_cancel',
'grid_copy',
'grid_alldetails_link',
'grid_details_link' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'cell_dpreview' => array( 'model' => 'cell_dpreview',
'items' => array( 'details_preview' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'cell_label3' => array( 'model' => 'cell_label',
'items' => array( 'text3' ),
'border' => array( array( 'side' => '',
'width' => '1px',
'color' => '#52bfff' ) ),
'align' => 'left',
'background' => '#f1fafd' ),
'cell_label24' => array( 'model' => 'cell_label',
'items' => array(  ),
'border' => array( array( 'side' => '',
'width' => '0' ) ),
'persistent' => true ),
'cell_field24' => array( 'model' => 'cell_field',
'items' => array(  ),
'border' => array( array( 'side' => '',
'width' => '0' ) ),
'persistent' => true ),
'cell_label25' => array( 'model' => 'cell_label',
'items' => array(  ),
'border' => array( array( 'side' => '',
'width' => '0' ) ),
'persistent' => true ),
'cell_field25' => array( 'model' => 'cell_field',
'items' => array(  ),
'border' => array( array( 'side' => '',
'width' => '0' ) ),
'persistent' => true ),
'cell_label26' => array( 'model' => 'cell_label',
'items' => array(  ),
'border' => array( array( 'side' => '',
'width' => '0' ) ),
'persistent' => true ),
'cell_field26' => array( 'model' => 'cell_field',
'items' => array(  ),
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_field61' => array( 'model' => 'cell_field',
'items' => array( 'text' ),
'border' => array( array( 'side' => '',
'width' => '1px',
'color' => '#52bfff' ) ),
'background' => '#f1fafd' ),
'cell_label72' => array( 'model' => 'cell_label',
'items' => array( 'text1' ),
'border' => array( array( 'side' => '',
'color' => '#52bfff',
'width' => '1px' ) ),
'align' => 'left',
'background' => '#f1fafd' ),
'cell_label68' => array( 'model' => 'cell_label',
'items' => array( 'text2' ),
'border' => array( array( 'side' => '',
'width' => '1px',
'color' => '#52bfff' ) ),
'align' => 'left',
'background' => '#f1fafd' ),
'cell_label114' => array( 'model' => 'cell_label',
'items' => array( 'text4' ),
'border' => array( array( 'side' => '',
'width' => '1px',
'color' => '#52bfff' ) ),
'align' => 'left',
'background' => '#f1fafd' ),
'cell_label133' => array( 'model' => 'cell_label',
'items' => array(  ),
'border' => array( array( 'side' => '',
'width' => '0' ) ),
'persistent' => true ),
'cell_label134' => array( 'model' => 'cell_field',
'items' => array(  ),
'border' => array( array( 'side' => '',
'width' => '0' ) ),
'persistent' => true ),
'cell_label135' => array( 'model' => 'cell_label',
'items' => array(  ),
'border' => array( array( 'side' => '',
'width' => '0' ) ),
'persistent' => true ),
'cell_label136' => array( 'model' => 'cell_field',
'items' => array(  ),
'border' => array( array( 'side' => '',
'width' => '0' ) ),
'persistent' => true ),
'cell_label137' => array( 'model' => 'cell_label',
'items' => array(  ),
'border' => array( array( 'side' => '',
'width' => '0' ) ),
'persistent' => true ),
'cell_label138' => array( 'model' => 'cell_field',
'items' => array(  ),
'border' => array( array( 'side' => '',
'width' => '0' ) ),
'persistent' => true ),
'cell_field114' => array( 'model' => 'cell_label',
'items' => array(  ),
'border' => array( array( 'side' => '',
'width' => '0' ) ),
'persistent' => true ),
'cell_field115' => array( 'model' => 'cell_field',
'items' => array(  ),
'border' => array( array( 'side' => '',
'width' => '0' ) ),
'persistent' => true ),
'cell_field116' => array( 'model' => 'cell_label',
'items' => array(  ),
'border' => array( array( 'side' => '',
'width' => '0' ) ),
'persistent' => true ),
'cell_field117' => array( 'model' => 'cell_field',
'items' => array(  ),
'border' => array( array( 'side' => '',
'width' => '0' ) ),
'persistent' => true ),
'cell_field118' => array( 'model' => 'cell_label',
'items' => array(  ),
'border' => array( array( 'side' => '',
'width' => '0' ) ),
'persistent' => true ),
'cell_field119' => array( 'model' => 'cell_field',
'items' => array(  ),
'border' => array( array( 'side' => '',
'width' => '0' ) ),
'persistent' => true ),
'cell_field93' => array( 'model' => 'cell_field',
'items' => array( 'image' ),
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_field94' => array( 'model' => 'cell_field',
'items' => array( 'text5' ),
'border' => array( array( 'side' => '',
'width' => '0' ) ),
'align' => 'center',
'bold' => true,
'padding' => array( 'top' => '30px' ) ),
'cell_field120' => array( 'model' => 'cell_field',
'items' => array(  ),
'border' => array( array( 'side' => '',
'width' => '0' ) ),
'background' => '#fff9c8' ),
'cell_field121' => array( 'model' => 'cell_field',
'items' => array(  ),
'border' => array( array( 'side' => '',
'width' => '0' ) ),
'background' => '#fff9c8' ),
'cell_field126' => array( 'model' => 'cell_field',
'items' => array(  ),
'border' => array( array( 'side' => '',
'width' => '0' ) ),
'background' => '#fff9c8' ),
'cell_field127' => array( 'model' => 'cell_field',
'items' => array(  ),
'border' => array( array( 'side' => '',
'width' => '0' ) ),
'background' => '#fff9c8' ),
'cell_field95' => array( 'model' => 'cell_label',
'items' => array(  ),
'persistent' => true,
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_field124' => array( 'model' => 'cell_field',
'items' => array(  ),
'persistent' => true,
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_field128' => array( 'model' => 'cell_field',
'items' => array(  ),
'persistent' => true,
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_field129' => array( 'model' => 'cell_label',
'items' => array(  ),
'persistent' => true,
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_field130' => array( 'model' => 'cell_field',
'items' => array(  ),
'persistent' => true,
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_field28' => array( 'model' => 'cell_field',
'items' => array( 'inline_add1' ),
'align' => 'center' ),
'cell_field30' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'cell_field31' => array( 'model' => 'cell_label',
'items' => array(  ) ),
'cell_field32' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'cell_label' => array( 'model' => 'cell_label',
'items' => array(  ),
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_label27' => array( 'model' => 'cell_field',
'items' => array(  ),
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_label28' => array( 'model' => 'cell_label',
'items' => array(  ),
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_label29' => array( 'model' => 'cell_field',
'items' => array(  ),
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_label30' => array( 'model' => 'cell_label',
'items' => array(  ),
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_label31' => array( 'model' => 'cell_field',
'items' => array(  ),
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_label38' => array( 'model' => 'cell_label',
'items' => array(  ),
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_label39' => array( 'model' => 'cell_field',
'items' => array(  ),
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_label40' => array( 'model' => 'cell_label',
'items' => array(  ),
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_label41' => array( 'model' => 'cell_field',
'items' => array(  ),
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_label42' => array( 'model' => 'cell_label',
'items' => array( 'text6' ),
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_label43' => array( 'model' => 'cell_field',
'items' => array(  ),
'orientation' => 'vertical',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ) ),
'deferredItems' => array( 'grid_checkbox_head' ),
'buildType' => 2,
'columnCount' => 3 ) ),
'items' => array( 'export_selected' => array( 'type' => 'export_selected' ),
'inline_add' => array( 'type' => 'inline_add' ),
'inline_save_all' => array( 'type' => 'inline_save_all' ),
'inline_cancel_all' => array( 'type' => 'inline_cancel_all' ),
'details_found' => array( 'type' => 'details_found' ),
'page_size' => array( 'type' => 'page_size' ),
'print_panel' => array( 'type' => 'print_panel',
'items' => array( 'print_scope',
'print_details',
'print_records',
'print_button' ) ),
'print_scope' => array( 'type' => 'print_scope' ),
'print_records' => array( 'type' => 'print_records' ),
'print_button' => array( 'type' => 'print_button' ),
'pagination' => array( 'type' => 'pagination' ),
'grid_checkbox' => array( 'type' => 'grid_checkbox' ),
'-4' => array( 'type' => '-' ),
'grid_inline_edit' => array( 'type' => 'grid_inline_edit' ),
'grid_inline_save' => array( 'type' => 'grid_inline_save' ),
'grid_inline_cancel' => array( 'type' => 'grid_inline_cancel' ),
'grid_copy' => array( 'type' => 'grid_copy',
'popup' => false ),
'export' => array( 'type' => 'export' ),
'grid_checkbox_head' => array( 'type' => 'grid_checkbox_head' ),
'search_panel_field' => array( 'field' => 'id',
'type' => 'search_panel_field',
'alwaysOnPanel' => false,
'required' => false ),
'search_panel_field2' => array( 'field' => 'applicationStatusId',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'edit_selected' => array( 'type' => 'edit_selected' ),
'-3' => array( 'type' => '-' ),
'-2' => array( 'type' => '-' ),
'-1' => array( 'type' => '-' ),
'-' => array( 'type' => '-' ),
'advsearch_link' => array( 'type' => 'advsearch_link' ),
'show_search_panel' => array( 'type' => 'show_search_panel' ),
'hide_search_panel' => array( 'type' => 'hide_search_panel' ),
'breadcrumb' => array( 'type' => 'breadcrumb' ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu' ),
'simple_search' => array( 'type' => 'simple_search' ),
'search_panel' => array( 'type' => 'search_panel',
'items' => array( 'search_panel_field',
'search_panel_field2' ),
'_flexiblePanel' => true ),
'list_options' => array( 'type' => 'list_options',
'items' => array( 'edit_selected',
'export_selected',
'-3',
'-2',
'-1',
'-',
'advsearch_link',
'show_search_panel',
'hide_search_panel',
'-4',
'export' ) ),
'text' => array( 'type' => 'text',
'label' => array( 'text' => 'Στοιχεία Συνδρομητή',
'type' => 0 ),
'editedByRte' => false,
'bold' => true,
'font-size' => '16px' ),
'text1' => array( 'type' => 'text',
'label' => array( 'text' => 'Επιλογή Προγράμματος',
'type' => 0 ),
'editedByRte' => false,
'font-size' => '16px',
'bold' => true ),
'text2' => array( 'type' => 'text',
'label' => array( 'text' => 'Πρόσθετες Υπηρεσίες',
'type' => 0 ),
'editedByRte' => false,
'font-size' => '16px',
'bold' => true ),
'text3' => array( 'type' => 'text',
'label' => array( 'text' => 'Στοιχεία Φορητότητας',
'type' => 0 ),
'editedByRte' => false,
'font-size' => '16px',
'bold' => true ),
'text4' => array( 'type' => 'text',
'label' => array( 'text' => 'Δικαιολογητικά',
'type' => 0 ),
'editedByRte' => false,
'font-size' => '16px',
'bold' => true ),
'image' => array( 'type' => 'image',
'imagePath' => 'nova-logo-new.png',
'padding' => array( 'top' => '12px' ),
'mobileControl' => '' ),
'text5' => array( 'type' => 'text',
'label' => array( 'text' => 'ΑΙΤΗΣΗ ΕΝΕΡΓΟΠΟΙΗΣΗΣ ΥΠΗΡΕΣΙΩΝ',
'type' => 0 ),
'editedByRte' => false,
'bold' => true,
'font-size' => '20px' ),
'print_details' => array( 'type' => 'print_details',
'tables' => array( 'dbo.internalComments' => true ) ),
'details_preview' => array( 'type' => 'details_preview',
'table' => 'dbo.internalComments',
'items' => array(  ),
'popup' => false,
'hideEmptyPreview' => false,
'proceedLink' => false,
'pageId' => 'list' ),
'grid_alldetails_link' => array( 'type' => 'grid_alldetails_link' ),
'grid_details_link' => array( 'type' => 'grid_details_link',
'table' => 'dbo.internalComments',
'badge' => true,
'hideIfNone' => false,
'showCount' => false ),
'filter_panel' => array( 'type' => 'filter_panel',
'items' => array( 'filter_panel_field' ) ),
'filter_panel_field' => array( 'field' => 'applicationStatusId',
'type' => 'filter_panel_field' ),
'columns_control' => array( 'type' => 'columns_control',
'showHide' => true,
'reorder' => false ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'logout_link',
'adminarea_link' ) ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => true ),
'logout_link' => array( 'type' => 'logout_link' ),
'inline_add1' => array( 'type' => 'inline_add',
'label' => array( 'type' => 0,
'text' => 'Νέα Αίτηση' ) ),
'text6' => array( 'type' => 'text',
'label' => array( 'text' => 'Από / Έως',
'type' => 0 ),
'editedByRte' => false ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>