<?php
			$optionsArray = array( 'pdf' => array( 'pdfView' => false ),
'fields' => array( 'gridFields' => array( 'applicationStatusId',
'applicationPhaseStatusId',
'forCount',
'lastStatusDate',
'agentApplicationStatus',
'callDate',
'agent',
'callphone',
'id',
'dialerCampaign',
'dialerList',
'applicationAge' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'applicationStatusId' => array( 'integrated_edit_field3',
'integrated_edit_field83' ),
'applicationPhaseStatusId' => array( 'integrated_edit_field8' ),
'forCount' => array( 'integrated_edit_field7' ),
'lastStatusDate' => array( 'integrated_edit_field6' ),
'agentApplicationStatus' => array( 'integrated_edit_field5' ),
'callDate' => array( 'integrated_edit_field4' ),
'agent' => array( 'integrated_edit_field2' ),
'callphone' => array( 'integrated_edit_field1' ),
'id' => array( 'integrated_edit_field' ),
'dialerCampaign' => array( 'integrated_edit_field9' ),
'dialerList' => array( 'integrated_edit_field10' ),
'applicationAge' => array( 'integrated_edit_field11' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array( 'logo',
'menu',
'loginform_login',
'username_button' ),
'top' => array( 'view_header' ),
'above-grid' => array(  ),
'below-grid' => array( 'view_back_list',
'view_close',
'hamburger' ),
'grid' => array( 'text1',
'text',
'text3',
'text2',
'text4',
'text6',
'text5',
'integrated_edit_field3',
'details_preview',
'text7',
'integrated_edit_field',
'integrated_edit_field4',
'integrated_edit_field7',
'integrated_edit_field10',
'integrated_edit_field1',
'integrated_edit_field5',
'integrated_edit_field8',
'integrated_edit_field11',
'integrated_edit_field2',
'integrated_edit_field6',
'integrated_edit_field9',
'integrated_edit_field83' ) ),
'formXtTags' => array( 'above-grid' => array(  ) ),
'itemForms' => array( 'logo' => 'supertop',
'menu' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'view_header' => 'top',
'view_back_list' => 'below-grid',
'view_close' => 'below-grid',
'hamburger' => 'below-grid',
'text1' => 'grid',
'text' => 'grid',
'text3' => 'grid',
'text2' => 'grid',
'text4' => 'grid',
'text6' => 'grid',
'text5' => 'grid',
'integrated_edit_field3' => 'grid',
'details_preview' => 'grid',
'text7' => 'grid',
'integrated_edit_field' => 'grid',
'integrated_edit_field4' => 'grid',
'integrated_edit_field7' => 'grid',
'integrated_edit_field10' => 'grid',
'integrated_edit_field1' => 'grid',
'integrated_edit_field5' => 'grid',
'integrated_edit_field8' => 'grid',
'integrated_edit_field11' => 'grid',
'integrated_edit_field2' => 'grid',
'integrated_edit_field6' => 'grid',
'integrated_edit_field9' => 'grid',
'integrated_edit_field83' => 'grid' ),
'itemLocations' => array( 'text1' => array( 'location' => 'grid',
'cellId' => 'c36' ),
'text' => array( 'location' => 'grid',
'cellId' => 'c41' ),
'text3' => array( 'location' => 'grid',
'cellId' => 'c8' ),
'text2' => array( 'location' => 'grid',
'cellId' => 'c52' ),
'text4' => array( 'location' => 'grid',
'cellId' => 'c75' ),
'text6' => array( 'location' => 'grid',
'cellId' => 'c91' ),
'text5' => array( 'location' => 'grid',
'cellId' => 'c94' ),
'integrated_edit_field3' => array( 'location' => 'grid',
'cellId' => 'c97' ),
'details_preview' => array( 'location' => 'grid',
'cellId' => 'c7' ),
'text7' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_edit_field' => array( 'location' => 'grid',
'cellId' => 'c6' ),
'integrated_edit_field4' => array( 'location' => 'grid',
'cellId' => 'c6' ),
'integrated_edit_field7' => array( 'location' => 'grid',
'cellId' => 'c6' ),
'integrated_edit_field10' => array( 'location' => 'grid',
'cellId' => 'c6' ),
'integrated_edit_field1' => array( 'location' => 'grid',
'cellId' => 'c148' ),
'integrated_edit_field5' => array( 'location' => 'grid',
'cellId' => 'c148' ),
'integrated_edit_field8' => array( 'location' => 'grid',
'cellId' => 'c148' ),
'integrated_edit_field11' => array( 'location' => 'grid',
'cellId' => 'c148' ),
'integrated_edit_field2' => array( 'location' => 'grid',
'cellId' => 'c149' ),
'integrated_edit_field6' => array( 'location' => 'grid',
'cellId' => 'c149' ),
'integrated_edit_field9' => array( 'location' => 'grid',
'cellId' => 'c149' ),
'integrated_edit_field83' => array( 'location' => 'grid',
'cellId' => 'c153' ) ),
'itemVisiblity' => array( 'menu' => 3,
'loginform_login' => 3,
'username_button' => 3 ) ),
'itemsByType' => array( 'view_header' => array( 'view_header' ),
'view_back_list' => array( 'view_back_list' ),
'view_close' => array( 'view_close' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'integrated_edit_field' => array( 'integrated_edit_field3',
'integrated_edit_field8',
'integrated_edit_field7',
'integrated_edit_field6',
'integrated_edit_field5',
'integrated_edit_field4',
'integrated_edit_field2',
'integrated_edit_field1',
'integrated_edit_field83',
'integrated_edit_field',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field11' ),
'text' => array( 'text7',
'text5',
'text6',
'text4',
'text2',
'text3',
'text',
'text1' ),
'details_preview' => array( 'details_preview' ),
'hamburger' => array( 'hamburger' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'logout_link' => array( 'logout_link' ),
'adminarea_link' => array( 'adminarea_link' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c59' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c89' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c97' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'text3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c21' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c22' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c36' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'text1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c37' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c42' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c50' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c123' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c124' => array( 'cols' => array( 2 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c41' => array( 'cols' => array( 0 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'text' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c43' => array( 'cols' => array( 1 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c51' => array( 'cols' => array( 2 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c74' => array( 'cols' => array( 0 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c121' => array( 'cols' => array( 1 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c122' => array( 'cols' => array( 2 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c52' => array( 'cols' => array( 0 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array( 'text2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c60' => array( 'cols' => array( 1 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c61' => array( 'cols' => array( 2 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c118' => array( 'cols' => array( 0 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c119' => array( 'cols' => array( 1 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c120' => array( 'cols' => array( 2 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c75' => array( 'cols' => array( 0 ),
'rows' => array( 8 ),
'tags' => array(  ),
'items' => array( 'text4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c76' => array( 'cols' => array( 1 ),
'rows' => array( 8 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c90' => array( 'cols' => array( 2 ),
'rows' => array( 8 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 0 ),
'rows' => array( 9 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c116' => array( 'cols' => array( 1 ),
'rows' => array( 9 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c117' => array( 'cols' => array( 2 ),
'rows' => array( 9 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c1' => array( 'cols' => array( 0,
1,
2 ),
'rows' => array( 10 ),
'tags' => array(  ),
'items' => array( 'text7' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c145' => array( 'cols' => array( 0 ),
'rows' => array( 11 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c146' => array( 'cols' => array( 1 ),
'rows' => array( 11 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c147' => array( 'cols' => array( 2 ),
'rows' => array( 11 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c91' => array( 'cols' => array( 0 ),
'rows' => array( 12 ),
'tags' => array(  ),
'items' => array( 'text6' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c92' => array( 'cols' => array( 1 ),
'rows' => array( 12 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c93' => array( 'cols' => array( 2 ),
'rows' => array( 12 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c94' => array( 'cols' => array( 0 ),
'rows' => array( 13 ),
'tags' => array(  ),
'items' => array( 'text5' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c95' => array( 'cols' => array( 1 ),
'rows' => array( 13 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c96' => array( 'cols' => array( 2 ),
'rows' => array( 13 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c98' => array( 'cols' => array( 0 ),
'rows' => array( 14 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c99' => array( 'cols' => array( 1 ),
'rows' => array( 14 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c100' => array( 'cols' => array( 2 ),
'rows' => array( 14 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c153' => array( 'cols' => array( 0 ),
'rows' => array( 15 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field83' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c154' => array( 'cols' => array( 1 ),
'rows' => array( 15 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c155' => array( 'cols' => array( 2 ),
'rows' => array( 15 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 0,
1,
2 ),
'rows' => array( 16 ),
'tags' => array(  ),
'items' => array( 'details_preview' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 0 ),
'rows' => array( 17 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field',
'integrated_edit_field4',
'integrated_edit_field7',
'integrated_edit_field10' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c148' => array( 'cols' => array( 1 ),
'rows' => array( 17 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field1',
'integrated_edit_field5',
'integrated_edit_field8',
'integrated_edit_field11' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c149' => array( 'cols' => array( 2 ),
'rows' => array( 17 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field2',
'integrated_edit_field6',
'integrated_edit_field9' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 3,
'height' => 18 ) ) ),
'loginForm' => array( 'loginForm' => 1 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'view',
'breadcrumb' => false,
'nextPrev' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'volton_view_popup',
'type' => 'view',
'layoutId' => 'topbar',
'disabled' => 0,
'default' => 2,
'forms' => array( 'supertop' => array( 'modelId' => 'topbar-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ),
array( 'cell' => 'c3' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'logo' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'menu' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c3' => array( 'model' => 'c3',
'items' => array( 'loginform_login',
'username_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'view-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'view_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'view-above-grid',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'view-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'view_back_list',
'view_close' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'hamburger' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c59' ),
array( 'cell' => 'c89' ),
array( 'cell' => 'c97' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c8' ),
array( 'cell' => 'c21' ),
array( 'cell' => 'c22' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c36' ),
array( 'cell' => 'c37' ),
array( 'cell' => 'c42' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c50' ),
array( 'cell' => 'c123' ),
array( 'cell' => 'c124' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c41' ),
array( 'cell' => 'c43' ),
array( 'cell' => 'c51' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c74' ),
array( 'cell' => 'c121' ),
array( 'cell' => 'c122' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c52' ),
array( 'cell' => 'c60' ),
array( 'cell' => 'c61' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c118' ),
array( 'cell' => 'c119' ),
array( 'cell' => 'c120' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c75' ),
array( 'cell' => 'c76' ),
array( 'cell' => 'c90' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ),
array( 'cell' => 'c116' ),
array( 'cell' => 'c117' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c1',
'colspan' => 3 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c145' ),
array( 'cell' => 'c146' ),
array( 'cell' => 'c147' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c91' ),
array( 'cell' => 'c92' ),
array( 'cell' => 'c93' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c94' ),
array( 'cell' => 'c95' ),
array( 'cell' => 'c96' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c98' ),
array( 'cell' => 'c99' ),
array( 'cell' => 'c100' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c153' ),
array( 'cell' => 'c154' ),
array( 'cell' => 'c155' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c7',
'colspan' => 3 ) ) ),
array( 'cells' => array( array( 'cell' => 'c6' ),
array( 'cell' => 'c148' ),
array( 'cell' => 'c149' ) ),
'section' => '' ) ),
'cells' => array( 'c' => array( 'model' => 'c3',
'items' => array(  ),
'persistent' => true ),
'c36' => array( 'model' => 'c3',
'items' => array( 'text1' ),
'background' => '#110ad6' ),
'c37' => array( 'model' => 'c3',
'items' => array(  ),
'background' => '#110ad6' ),
'c41' => array( 'model' => 'c3',
'items' => array( 'text' ),
'background' => '#110ad6' ),
'c50' => array( 'model' => 'c3',
'items' => array(  ),
'persistent' => true ),
'c74' => array( 'model' => 'c3',
'items' => array(  ),
'persistent' => true ),
'c8' => array( 'model' => 'c3',
'items' => array( 'text3' ),
'background' => '#110ad6' ),
'c21' => array( 'model' => 'c3',
'items' => array(  ),
'background' => '#110ad6' ),
'c22' => array( 'model' => 'c3',
'items' => array(  ),
'background' => '#110ad6' ),
'c42' => array( 'model' => 'c3',
'items' => array(  ),
'background' => '#110ad6' ),
'c43' => array( 'model' => 'c3',
'items' => array(  ),
'background' => '#110ad6' ),
'c51' => array( 'model' => 'c3',
'items' => array(  ),
'background' => '#110ad6' ),
'c52' => array( 'model' => 'c3',
'items' => array( 'text2' ),
'background' => '#110ad6' ),
'c60' => array( 'model' => 'c3',
'items' => array(  ),
'background' => '#110ad6' ),
'c61' => array( 'model' => 'c3',
'items' => array(  ),
'background' => '#110ad6' ),
'c75' => array( 'model' => 'c3',
'items' => array( 'text4' ),
'background' => '#110ad6' ),
'c76' => array( 'model' => 'c3',
'items' => array(  ),
'background' => '#110ad6' ),
'c90' => array( 'model' => 'c3',
'items' => array(  ),
'background' => '#110ad6' ),
'c91' => array( 'model' => 'c3',
'items' => array( 'text6' ),
'background' => '#110ad6' ),
'c92' => array( 'model' => 'c3',
'items' => array(  ),
'background' => '#110ad6' ),
'c93' => array( 'model' => 'c3',
'items' => array(  ),
'background' => '#110ad6' ),
'c94' => array( 'model' => 'c3',
'items' => array( 'text5' ),
'background' => '#110ad6' ),
'c95' => array( 'model' => 'c3',
'items' => array(  ),
'background' => '#110ad6' ),
'c96' => array( 'model' => 'c3',
'items' => array(  ),
'background' => '#110ad6' ),
'c59' => array( 'model' => 'c3',
'items' => array(  ),
'background' => '#fffbe1' ),
'c89' => array( 'model' => 'c3',
'items' => array(  ),
'background' => '#fffbe1' ),
'c97' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field3' ) ),
'c98' => array( 'model' => 'c3',
'items' => array(  ),
'persistent' => true ),
'c99' => array( 'model' => 'c3',
'items' => array(  ),
'persistent' => true ),
'c100' => array( 'model' => 'c3',
'items' => array(  ) ),
'c116' => array( 'model' => 'c3',
'items' => array(  ) ),
'c117' => array( 'model' => 'c3',
'items' => array(  ) ),
'c118' => array( 'model' => 'c3',
'items' => array(  ),
'persistent' => true ),
'c119' => array( 'model' => 'c3',
'items' => array(  ) ),
'c120' => array( 'model' => 'c3',
'items' => array(  ) ),
'c121' => array( 'model' => 'c3',
'items' => array(  ) ),
'c122' => array( 'model' => 'c3',
'items' => array(  ) ),
'c123' => array( 'model' => 'c3',
'items' => array(  ) ),
'c124' => array( 'model' => 'c3',
'items' => array(  ) ),
'c7' => array( 'model' => 'c3',
'items' => array( 'details_preview' ) ),
'c1' => array( 'model' => 'c3',
'items' => array( 'text7' ),
'background' => '#110ad6' ),
'c145' => array( 'model' => 'c3',
'items' => array(  ),
'persistent' => true ),
'c146' => array( 'model' => 'c3',
'items' => array(  ) ),
'c147' => array( 'model' => 'c3',
'items' => array(  ) ),
'c6' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field',
'integrated_edit_field4',
'integrated_edit_field7',
'integrated_edit_field10' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c148' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field1',
'integrated_edit_field5',
'integrated_edit_field8',
'integrated_edit_field11' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c149' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field2',
'integrated_edit_field6',
'integrated_edit_field9' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c153' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field83' ) ),
'c154' => array( 'model' => 'c3',
'items' => array(  ) ),
'c155' => array( 'model' => 'c3',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'columnCount' => 3,
'inlineLabels' => true,
'separateLabels' => false ) ),
'items' => array( 'view_header' => array( 'type' => 'view_header',
'title' => array( 'page' => 'volton_view_popup',
'table' => 'dbo.application',
'type' => 7 ) ),
'view_back_list' => array( 'type' => 'view_back_list' ),
'view_close' => array( 'type' => 'view_close' ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu' ),
'integrated_edit_field3' => array( 'field' => 'applicationStatusId',
'type' => 'integrated_edit_field',
'orientation' => 1,
'tooltip' => array( 'field' => 'applicationStatusId',
'table' => 'dbo.VoltonApplications',
'type' => 4 ) ),
'text7' => array( 'type' => 'text',
'label' => array( 'text' => 'ΣΤΟΙΧΕΙΑ ΠΑΡΟΧΗΣ (ΦΥΣΙΚΟ ΑΕΡΙΟ)',
'type' => 0 ),
'editedByRte' => false,
'bold' => true,
'font-size' => '16px',
'color' => '#ffffff' ),
'text5' => array( 'type' => 'text',
'label' => array( 'text' => 'ΔΙΚΑΙΟΛΟΓΗΤΙΚΑ',
'type' => 0 ),
'editedByRte' => false,
'color' => '#ffffff' ),
'text6' => array( 'type' => 'text',
'label' => array( 'text' => 'ΤΙΜΟΛΟΓΙΟ VOLTON',
'type' => 0 ),
'editedByRte' => false,
'color' => '#ffffff',
'bold' => true,
'font-size' => '16px' ),
'details_preview' => array( 'type' => 'details_preview',
'table' => 'dbo.internalComments',
'items' => array(  ),
'popup' => false,
'pageId' => 'list' ),
'text4' => array( 'type' => 'text',
'label' => array( 'text' => 'ΣΤΟΙΧΕΙΑ ΠΑΡΟΧΗΣ',
'type' => 0 ),
'editedByRte' => false,
'color' => '#ffffff',
'bold' => true,
'font-size' => '16px' ),
'text2' => array( 'type' => 'text',
'label' => array( 'text' => 'ΔΙΕΥΘΥΝΣΗ ΑΠΟΣΤΟΛΗΣ ΛΟΓΑΡΙΑΣΜΟΥ',
'type' => 0 ),
'editedByRte' => false,
'bold' => true,
'font-size' => '16px',
'color' => '#ffffff' ),
'text3' => array( 'type' => 'text',
'label' => array( 'text' => 'ΣΤΟΙΧΕΙΑ ΠΕΛΑΤΗ',
'type' => 0 ),
'editedByRte' => false,
'bold' => true,
'font-size' => '16px',
'color' => '#ffffff' ),
'hamburger' => array( 'type' => 'hamburger',
'items' => array(  ) ),
'text' => array( 'type' => 'text',
'label' => array( 'text' => 'ΥΠΕΥΘΥΝΟΣ ΕΠΙΚΟΙΝΩΝΙΑΣ',
'type' => 0 ),
'editedByRte' => false,
'bold' => true,
'font-size' => '16px',
'color' => '#ffffff' ),
'text1' => array( 'type' => 'text',
'label' => array( 'text' => 'ΝΟΜΙΜΟΣ ΕΚΠΡΟΣΩΠΟΣ',
'type' => 0 ),
'editedByRte' => false,
'bold' => true,
'font-size' => '16px',
'color' => '#ffffff' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'logout_link',
'adminarea_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => true ),
'logout_link' => array( 'type' => 'logout_link' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'integrated_edit_field8' => array( 'field' => 'applicationPhaseStatusId',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field7' => array( 'field' => 'forCount',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field6' => array( 'field' => 'lastStatusDate',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field5' => array( 'field' => 'agentApplicationStatus',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field4' => array( 'field' => 'callDate',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field2' => array( 'field' => 'agent',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field1' => array( 'field' => 'callphone',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field83' => array( 'field' => 'applicationStatusId',
'type' => 'integrated_edit_field',
'orientation' => 1,
'tooltip' => array( 'field' => 'applicationStatusId',
'table' => 'dbo.VoltonApplications',
'type' => 4 ) ),
'integrated_edit_field' => array( 'field' => 'id',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field9' => array( 'field' => 'dialerCampaign',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field10' => array( 'field' => 'dialerList',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field11' => array( 'field' => 'applicationAge',
'type' => 'integrated_edit_field',
'orientation' => 1 ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>