<?php
			$optionsArray = array( 'totals' => array( 'id' => array( 'totalsType' => '' ),
'code' => array( 'totalsType' => '' ),
'firstName' => array( 'totalsType' => '' ),
'lastName' => array( 'totalsType' => '' ),
'phone1' => array( 'totalsType' => '' ),
'phone1Type' => array( 'totalsType' => '' ),
'phone2' => array( 'totalsType' => '' ),
'phone2Type' => array( 'totalsType' => '' ),
'phone3' => array( 'totalsType' => '' ),
'phone3Type' => array( 'totalsType' => '' ),
'mobile1' => array( 'totalsType' => '' ),
'mobile2' => array( 'totalsType' => '' ),
'address' => array( 'totalsType' => '' ),
'postalCode' => array( 'totalsType' => '' ),
'dateInserted' => array( 'totalsType' => '' ),
'noCall' => array( 'totalsType' => '' ),
'noCallDate' => array( 'totalsType' => '' ),
'comments' => array( 'totalsType' => '' ),
'agentMessage' => array( 'totalsType' => '' ),
'isCompany' => array( 'totalsType' => '' ),
'name' => array( 'totalsType' => '' ),
'referenceCode' => array( 'totalsType' => '' ),
'area' => array( 'totalsType' => '' ),
'city' => array( 'totalsType' => '' ),
'region' => array( 'totalsType' => '' ),
'vatNumber' => array( 'totalsType' => '' ),
'taxOffice' => array( 'totalsType' => '' ),
'externalRefCode' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'id',
'firstName',
'lastName',
'phone1',
'phone1Type',
'phone2',
'phone2Type',
'phone3',
'phone3Type',
'mobile1',
'mobile2',
'address',
'postalCode',
'dateInserted',
'noCall',
'noCallDate',
'comments',
'agentMessage',
'isCompany',
'name',
'referenceCode',
'area',
'city',
'region',
'vatNumber',
'taxOffice',
'externalRefCode' ),
'exportFields' => array( 'id',
'firstName',
'lastName',
'phone1',
'phone1Type',
'phone2',
'phone2Type',
'phone3',
'phone3Type',
'mobile1',
'mobile2',
'address',
'postalCode',
'dateInserted',
'noCall',
'noCallDate',
'comments',
'agentMessage',
'isCompany',
'name',
'referenceCode',
'area',
'city',
'region',
'vatNumber',
'taxOffice',
'externalRefCode' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'id' => array( 'export_field' ),
'firstName' => array( 'export_field2' ),
'lastName' => array( 'export_field3' ),
'phone1' => array( 'export_field4' ),
'phone1Type' => array( 'export_field5' ),
'phone2' => array( 'export_field6' ),
'phone2Type' => array( 'export_field7' ),
'phone3' => array( 'export_field8' ),
'phone3Type' => array( 'export_field9' ),
'mobile1' => array( 'export_field10' ),
'mobile2' => array( 'export_field11' ),
'address' => array( 'export_field12' ),
'postalCode' => array( 'export_field13' ),
'dateInserted' => array( 'export_field14' ),
'noCall' => array( 'export_field15' ),
'noCallDate' => array( 'export_field16' ),
'comments' => array( 'export_field17' ),
'agentMessage' => array( 'export_field18' ),
'isCompany' => array( 'export_field19' ),
'name' => array( 'export_field20' ),
'referenceCode' => array( 'export_field21' ),
'area' => array( 'export_field22' ),
'city' => array( 'export_field23' ),
'region' => array( 'export_field24' ),
'vatNumber' => array( 'export_field25' ),
'taxOffice' => array( 'export_field26' ),
'externalRefCode' => array( 'export_field1' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field1' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field13' => 'grid',
'export_field14' => 'grid',
'export_field15' => 'grid',
'export_field16' => 'grid',
'export_field17' => 'grid',
'export_field18' => 'grid',
'export_field19' => 'grid',
'export_field20' => 'grid',
'export_field21' => 'grid',
'export_field22' => 'grid',
'export_field23' => 'grid',
'export_field24' => 'grid',
'export_field25' => 'grid',
'export_field26' => 'grid',
'export_field1' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field1' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field1' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'id',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'firstName',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'lastName',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'phone1',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'phone1Type',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'phone2',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'phone2Type',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'phone3',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'phone3Type',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'mobile1',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'mobile2',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'address',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'postalCode',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'dateInserted',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'noCall',
'type' => 'export_field' ),
'export_field16' => array( 'field' => 'noCallDate',
'type' => 'export_field' ),
'export_field17' => array( 'field' => 'comments',
'type' => 'export_field' ),
'export_field18' => array( 'field' => 'agentMessage',
'type' => 'export_field' ),
'export_field19' => array( 'field' => 'isCompany',
'type' => 'export_field' ),
'export_field20' => array( 'field' => 'name',
'type' => 'export_field' ),
'export_field21' => array( 'field' => 'referenceCode',
'type' => 'export_field' ),
'export_field22' => array( 'field' => 'area',
'type' => 'export_field' ),
'export_field23' => array( 'field' => 'city',
'type' => 'export_field' ),
'export_field24' => array( 'field' => 'region',
'type' => 'export_field' ),
'export_field25' => array( 'field' => 'vatNumber',
'type' => 'export_field' ),
'export_field26' => array( 'field' => 'taxOffice',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'externalRefCode',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 4,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>