<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'id',
'callid',
'applicantName',
'applicantIdNumber',
'applicantAddress',
'applicantPostalCode',
'applicantTaxRegistrationNumber',
'applicantTaxOffice',
'applicantEmail',
'applicantProfession',
'applicantKod',
'applicantGemi',
'contactName',
'contactPhone',
'contactMobile',
'contactEmail',
'applicantPhone',
'applicantMobile',
'legalName',
'legalIdNumber',
'mailAddress',
'mailPostalCode',
'powerAddress',
'powerOwnershipType',
'powerPostalCode',
'powerAgreedKw',
'powerSupplyNumber',
'powerMeterNumber',
'powerCurrentSupplier',
'powerCurrentDayMeter',
'powerCurrentNightMeter',
'powerActivationStatus',
'voltonPlan',
'voltonContractDuration',
'voltonWarrantyAmount',
'voltonWarrantyOnFirstBill',
'voltonOther',
'voltonComments',
'voltonAutoPayment',
'applicationType',
'applicantWorkPhone',
'document1',
'document2',
'document3',
'document4',
'document5',
'document6',
'document7',
'document8',
'document9',
'document10',
'document11',
'document12',
'document13',
'document14',
'document15',
'applicationStatusId',
'applicantArea',
'applicantCity',
'mailArea',
'mailCity',
'powerArea',
'powerCity',
'ngAddress',
'ngPostalCode',
'ngArea',
'ngCity',
'ngPressure',
'ngHourlyCapacity',
'ngHkasp',
'ngMeterNumber',
'ngMeterType',
'ngCurrentMeterValue',
'ngConnectionExists',
'ngSupplyIsNew',
'ngSupplyReactivation',
'applicationAgentStatus',
'applicationLastStatusDate',
'applicationContactMethod',
'applicationCourier',
'applicationCourierDate',
'applicationCourrierTimeFrom',
'applicationCourierTimeTo',
'applicationCourrierComments',
'dialerAgent',
'additionalServices' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'id' => array( 'integrated_search_field' ),
'callid' => array( 'integrated_search_field1' ),
'applicantName' => array( 'integrated_search_field3' ),
'applicantIdNumber' => array( 'integrated_search_field4' ),
'applicantAddress' => array( 'integrated_search_field5' ),
'applicantPostalCode' => array( 'integrated_search_field6' ),
'applicantTaxRegistrationNumber' => array( 'integrated_search_field7' ),
'applicantTaxOffice' => array( 'integrated_search_field8' ),
'applicantEmail' => array( 'integrated_search_field9' ),
'applicantProfession' => array( 'integrated_search_field10' ),
'applicantKod' => array( 'integrated_search_field11' ),
'applicantGemi' => array( 'integrated_search_field12' ),
'contactName' => array( 'integrated_search_field15' ),
'contactPhone' => array( 'integrated_search_field16' ),
'contactMobile' => array( 'integrated_search_field17' ),
'contactEmail' => array( 'integrated_search_field18' ),
'applicantPhone' => array( 'integrated_search_field13' ),
'applicantMobile' => array( 'integrated_search_field14' ),
'legalName' => array( 'integrated_search_field19' ),
'legalIdNumber' => array( 'integrated_search_field20' ),
'mailAddress' => array( 'integrated_search_field21' ),
'mailPostalCode' => array( 'integrated_search_field22' ),
'powerAddress' => array( 'integrated_search_field24' ),
'powerOwnershipType' => array( 'integrated_search_field25' ),
'powerPostalCode' => array( 'integrated_search_field26' ),
'powerAgreedKw' => array( 'integrated_search_field28' ),
'powerSupplyNumber' => array( 'integrated_search_field29' ),
'powerMeterNumber' => array( 'integrated_search_field30' ),
'powerCurrentSupplier' => array( 'integrated_search_field31' ),
'powerCurrentDayMeter' => array( 'integrated_search_field32' ),
'powerCurrentNightMeter' => array( 'integrated_search_field33' ),
'powerActivationStatus' => array( 'integrated_search_field34' ),
'voltonPlan' => array( 'integrated_search_field35' ),
'voltonContractDuration' => array( 'integrated_search_field36' ),
'voltonWarrantyAmount' => array( 'integrated_search_field37' ),
'voltonWarrantyOnFirstBill' => array( 'integrated_search_field38' ),
'voltonOther' => array( 'integrated_search_field39' ),
'voltonComments' => array( 'integrated_search_field40' ),
'voltonAutoPayment' => array( 'integrated_search_field44' ),
'applicationType' => array( 'integrated_search_field45' ),
'applicantWorkPhone' => array( 'integrated_search_field46' ),
'document1' => array( 'integrated_search_field47' ),
'document2' => array( 'integrated_search_field48' ),
'document3' => array( 'integrated_search_field49' ),
'document4' => array( 'integrated_search_field50' ),
'document5' => array( 'integrated_search_field51' ),
'document6' => array( 'integrated_search_field52' ),
'document7' => array( 'integrated_search_field53' ),
'document8' => array( 'integrated_search_field54' ),
'document9' => array( 'integrated_search_field55' ),
'document10' => array( 'integrated_search_field56' ),
'document11' => array( 'integrated_search_field57' ),
'document12' => array( 'integrated_search_field58' ),
'document13' => array( 'integrated_search_field59' ),
'document14' => array( 'integrated_search_field60' ),
'document15' => array( 'integrated_search_field61' ),
'applicationStatusId' => array( 'integrated_search_field2' ),
'applicantArea' => array( 'integrated_search_field23' ),
'applicantCity' => array( 'integrated_search_field27' ),
'mailArea' => array( 'integrated_search_field42' ),
'mailCity' => array( 'integrated_search_field43' ),
'powerArea' => array( 'integrated_search_field62' ),
'powerCity' => array( 'integrated_search_field63' ),
'ngAddress' => array( 'integrated_search_field41' ),
'ngPostalCode' => array( 'integrated_search_field64' ),
'ngArea' => array( 'integrated_search_field65' ),
'ngCity' => array( 'integrated_search_field66' ),
'ngPressure' => array( 'integrated_search_field67' ),
'ngHourlyCapacity' => array( 'integrated_search_field68' ),
'ngHkasp' => array( 'integrated_search_field69' ),
'ngMeterNumber' => array( 'integrated_search_field71' ),
'ngMeterType' => array( 'integrated_search_field72' ),
'ngCurrentMeterValue' => array( 'integrated_search_field73' ),
'ngConnectionExists' => array( 'integrated_search_field74' ),
'ngSupplyIsNew' => array( 'integrated_search_field75' ),
'ngSupplyReactivation' => array( 'integrated_search_field76' ),
'applicationAgentStatus' => array( 'integrated_search_field70' ),
'applicationLastStatusDate' => array( 'integrated_search_field77' ),
'applicationContactMethod' => array( 'integrated_search_field78' ),
'applicationCourier' => array( 'integrated_search_field79' ),
'applicationCourierDate' => array( 'integrated_search_field80' ),
'applicationCourrierTimeFrom' => array( 'integrated_search_field81' ),
'applicationCourierTimeTo' => array( 'integrated_search_field82' ),
'applicationCourrierComments' => array( 'integrated_search_field83' ),
'dialerAgent' => array( 'integrated_search_field84' ),
'additionalServices' => array( 'integrated_search_field85' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array( 'logo',
'menu',
'loginform_login',
'username_button' ),
'top' => array( 'search_header' ),
'above-grid' => array(  ),
'below-grid' => array( 'search_search',
'search_reset',
'search_back_list',
'search_cancel' ),
'grid' => array( 'integrated_search_field',
'integrated_search_field1',
'integrated_search_field3',
'integrated_search_field4',
'integrated_search_field5',
'integrated_search_field6',
'integrated_search_field7',
'integrated_search_field8',
'integrated_search_field9',
'integrated_search_field10',
'integrated_search_field11',
'integrated_search_field12',
'integrated_search_field15',
'integrated_search_field16',
'integrated_search_field17',
'integrated_search_field18',
'integrated_search_field13',
'integrated_search_field14',
'integrated_search_field19',
'integrated_search_field20',
'integrated_search_field21',
'integrated_search_field22',
'integrated_search_field24',
'integrated_search_field25',
'integrated_search_field26',
'integrated_search_field28',
'integrated_search_field29',
'integrated_search_field30',
'integrated_search_field31',
'integrated_search_field32',
'integrated_search_field33',
'integrated_search_field34',
'integrated_search_field35',
'integrated_search_field36',
'integrated_search_field37',
'integrated_search_field38',
'integrated_search_field39',
'integrated_search_field40',
'integrated_search_field44',
'integrated_search_field45',
'integrated_search_field46',
'integrated_search_field47',
'integrated_search_field48',
'integrated_search_field49',
'integrated_search_field50',
'integrated_search_field51',
'integrated_search_field52',
'integrated_search_field53',
'integrated_search_field54',
'integrated_search_field55',
'integrated_search_field56',
'integrated_search_field57',
'integrated_search_field58',
'integrated_search_field59',
'integrated_search_field60',
'integrated_search_field61',
'integrated_search_field2',
'integrated_search_field23',
'integrated_search_field27',
'integrated_search_field42',
'integrated_search_field43',
'integrated_search_field62',
'integrated_search_field63',
'integrated_search_field41',
'integrated_search_field64',
'integrated_search_field65',
'integrated_search_field66',
'integrated_search_field67',
'integrated_search_field68',
'integrated_search_field69',
'integrated_search_field71',
'integrated_search_field72',
'integrated_search_field73',
'integrated_search_field74',
'integrated_search_field75',
'integrated_search_field76',
'integrated_search_field70',
'integrated_search_field77',
'integrated_search_field78',
'integrated_search_field79',
'integrated_search_field80',
'integrated_search_field81',
'integrated_search_field82',
'integrated_search_field83',
'integrated_search_field84',
'integrated_search_field85' ) ),
'formXtTags' => array( 'above-grid' => array(  ) ),
'itemForms' => array( 'logo' => 'supertop',
'menu' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'search_header' => 'top',
'search_search' => 'below-grid',
'search_reset' => 'below-grid',
'search_back_list' => 'below-grid',
'search_cancel' => 'below-grid',
'integrated_search_field' => 'grid',
'integrated_search_field1' => 'grid',
'integrated_search_field3' => 'grid',
'integrated_search_field4' => 'grid',
'integrated_search_field5' => 'grid',
'integrated_search_field6' => 'grid',
'integrated_search_field7' => 'grid',
'integrated_search_field8' => 'grid',
'integrated_search_field9' => 'grid',
'integrated_search_field10' => 'grid',
'integrated_search_field11' => 'grid',
'integrated_search_field12' => 'grid',
'integrated_search_field15' => 'grid',
'integrated_search_field16' => 'grid',
'integrated_search_field17' => 'grid',
'integrated_search_field18' => 'grid',
'integrated_search_field13' => 'grid',
'integrated_search_field14' => 'grid',
'integrated_search_field19' => 'grid',
'integrated_search_field20' => 'grid',
'integrated_search_field21' => 'grid',
'integrated_search_field22' => 'grid',
'integrated_search_field24' => 'grid',
'integrated_search_field25' => 'grid',
'integrated_search_field26' => 'grid',
'integrated_search_field28' => 'grid',
'integrated_search_field29' => 'grid',
'integrated_search_field30' => 'grid',
'integrated_search_field31' => 'grid',
'integrated_search_field32' => 'grid',
'integrated_search_field33' => 'grid',
'integrated_search_field34' => 'grid',
'integrated_search_field35' => 'grid',
'integrated_search_field36' => 'grid',
'integrated_search_field37' => 'grid',
'integrated_search_field38' => 'grid',
'integrated_search_field39' => 'grid',
'integrated_search_field40' => 'grid',
'integrated_search_field44' => 'grid',
'integrated_search_field45' => 'grid',
'integrated_search_field46' => 'grid',
'integrated_search_field47' => 'grid',
'integrated_search_field48' => 'grid',
'integrated_search_field49' => 'grid',
'integrated_search_field50' => 'grid',
'integrated_search_field51' => 'grid',
'integrated_search_field52' => 'grid',
'integrated_search_field53' => 'grid',
'integrated_search_field54' => 'grid',
'integrated_search_field55' => 'grid',
'integrated_search_field56' => 'grid',
'integrated_search_field57' => 'grid',
'integrated_search_field58' => 'grid',
'integrated_search_field59' => 'grid',
'integrated_search_field60' => 'grid',
'integrated_search_field61' => 'grid',
'integrated_search_field2' => 'grid',
'integrated_search_field23' => 'grid',
'integrated_search_field27' => 'grid',
'integrated_search_field42' => 'grid',
'integrated_search_field43' => 'grid',
'integrated_search_field62' => 'grid',
'integrated_search_field63' => 'grid',
'integrated_search_field41' => 'grid',
'integrated_search_field64' => 'grid',
'integrated_search_field65' => 'grid',
'integrated_search_field66' => 'grid',
'integrated_search_field67' => 'grid',
'integrated_search_field68' => 'grid',
'integrated_search_field69' => 'grid',
'integrated_search_field71' => 'grid',
'integrated_search_field72' => 'grid',
'integrated_search_field73' => 'grid',
'integrated_search_field74' => 'grid',
'integrated_search_field75' => 'grid',
'integrated_search_field76' => 'grid',
'integrated_search_field70' => 'grid',
'integrated_search_field77' => 'grid',
'integrated_search_field78' => 'grid',
'integrated_search_field79' => 'grid',
'integrated_search_field80' => 'grid',
'integrated_search_field81' => 'grid',
'integrated_search_field82' => 'grid',
'integrated_search_field83' => 'grid',
'integrated_search_field84' => 'grid',
'integrated_search_field85' => 'grid' ),
'itemLocations' => array( 'integrated_search_field' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field1' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field3' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field4' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field5' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field6' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field7' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field8' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field9' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field10' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field11' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field12' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field15' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field16' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field17' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field18' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field13' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field14' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field19' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field20' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field21' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field22' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field24' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field25' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field26' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field28' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field29' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field30' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field31' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field32' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field33' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field34' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field35' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field36' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field37' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field38' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field39' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field40' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field44' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field45' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field46' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field47' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field48' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field49' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field50' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field51' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field52' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field53' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field54' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field55' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field56' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field57' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field58' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field59' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field60' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field61' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field2' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field23' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field27' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field42' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field43' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field62' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field63' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field41' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field64' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field65' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field66' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field67' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field68' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field69' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field71' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field72' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field73' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field74' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field75' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field76' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field70' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field77' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field78' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field79' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field80' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field81' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field82' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field83' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field84' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field85' => array( 'location' => 'grid',
'cellId' => 'c3' ) ),
'itemVisiblity' => array( 'menu' => 3,
'loginform_login' => 3,
'username_button' => 3 ) ),
'itemsByType' => array( 'search_header' => array( 'search_header' ),
'search_search' => array( 'search_search' ),
'search_reset' => array( 'search_reset' ),
'search_back_list' => array( 'search_back_list' ),
'search_cancel' => array( 'search_cancel' ),
'integrated_search_field' => array( 'integrated_search_field',
'integrated_search_field1',
'integrated_search_field3',
'integrated_search_field4',
'integrated_search_field5',
'integrated_search_field6',
'integrated_search_field7',
'integrated_search_field8',
'integrated_search_field9',
'integrated_search_field10',
'integrated_search_field11',
'integrated_search_field12',
'integrated_search_field15',
'integrated_search_field16',
'integrated_search_field17',
'integrated_search_field18',
'integrated_search_field13',
'integrated_search_field14',
'integrated_search_field19',
'integrated_search_field20',
'integrated_search_field21',
'integrated_search_field22',
'integrated_search_field24',
'integrated_search_field25',
'integrated_search_field26',
'integrated_search_field28',
'integrated_search_field29',
'integrated_search_field30',
'integrated_search_field31',
'integrated_search_field32',
'integrated_search_field33',
'integrated_search_field34',
'integrated_search_field35',
'integrated_search_field36',
'integrated_search_field37',
'integrated_search_field38',
'integrated_search_field39',
'integrated_search_field40',
'integrated_search_field44',
'integrated_search_field45',
'integrated_search_field46',
'integrated_search_field47',
'integrated_search_field48',
'integrated_search_field49',
'integrated_search_field50',
'integrated_search_field51',
'integrated_search_field52',
'integrated_search_field53',
'integrated_search_field54',
'integrated_search_field55',
'integrated_search_field56',
'integrated_search_field57',
'integrated_search_field58',
'integrated_search_field59',
'integrated_search_field60',
'integrated_search_field61',
'integrated_search_field2',
'integrated_search_field23',
'integrated_search_field27',
'integrated_search_field42',
'integrated_search_field43',
'integrated_search_field62',
'integrated_search_field63',
'integrated_search_field41',
'integrated_search_field64',
'integrated_search_field65',
'integrated_search_field66',
'integrated_search_field67',
'integrated_search_field68',
'integrated_search_field69',
'integrated_search_field71',
'integrated_search_field72',
'integrated_search_field73',
'integrated_search_field74',
'integrated_search_field75',
'integrated_search_field76',
'integrated_search_field70',
'integrated_search_field77',
'integrated_search_field78',
'integrated_search_field79',
'integrated_search_field80',
'integrated_search_field81',
'integrated_search_field82',
'integrated_search_field83',
'integrated_search_field84',
'integrated_search_field85' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'logout_link' => array( 'logout_link' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c3' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_search_field',
'integrated_search_field1',
'integrated_search_field3',
'integrated_search_field4',
'integrated_search_field5',
'integrated_search_field6',
'integrated_search_field7',
'integrated_search_field8',
'integrated_search_field9',
'integrated_search_field10',
'integrated_search_field11',
'integrated_search_field12',
'integrated_search_field15',
'integrated_search_field16',
'integrated_search_field17',
'integrated_search_field18',
'integrated_search_field13',
'integrated_search_field14',
'integrated_search_field19',
'integrated_search_field20',
'integrated_search_field21',
'integrated_search_field22',
'integrated_search_field24',
'integrated_search_field25',
'integrated_search_field26',
'integrated_search_field28',
'integrated_search_field29',
'integrated_search_field30',
'integrated_search_field31',
'integrated_search_field32',
'integrated_search_field33',
'integrated_search_field34',
'integrated_search_field35',
'integrated_search_field36',
'integrated_search_field37',
'integrated_search_field38',
'integrated_search_field39',
'integrated_search_field40',
'integrated_search_field44',
'integrated_search_field45',
'integrated_search_field46',
'integrated_search_field47',
'integrated_search_field48',
'integrated_search_field49',
'integrated_search_field50',
'integrated_search_field51',
'integrated_search_field52',
'integrated_search_field53',
'integrated_search_field54',
'integrated_search_field55',
'integrated_search_field56',
'integrated_search_field57',
'integrated_search_field58',
'integrated_search_field59',
'integrated_search_field60',
'integrated_search_field61',
'integrated_search_field2',
'integrated_search_field23',
'integrated_search_field27',
'integrated_search_field42',
'integrated_search_field43',
'integrated_search_field62',
'integrated_search_field63',
'integrated_search_field41',
'integrated_search_field64',
'integrated_search_field65',
'integrated_search_field66',
'integrated_search_field67',
'integrated_search_field68',
'integrated_search_field69',
'integrated_search_field71',
'integrated_search_field72',
'integrated_search_field73',
'integrated_search_field74',
'integrated_search_field75',
'integrated_search_field76',
'integrated_search_field70',
'integrated_search_field77',
'integrated_search_field78',
'integrated_search_field79',
'integrated_search_field80',
'integrated_search_field81',
'integrated_search_field82',
'integrated_search_field83',
'integrated_search_field84',
'integrated_search_field85' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ) ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'search',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'search',
'type' => 'search',
'layoutId' => 'topbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'topbar-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ),
array( 'cell' => 'c3' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'logo' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'menu' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c3' => array( 'model' => 'c3',
'items' => array( 'loginform_login',
'username_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'search-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'search_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'search-above-grid',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'search-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'search_search',
'search_reset',
'search_back_list',
'search_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-search',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c3' ) ),
'section' => '' ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array( 'integrated_search_field',
'integrated_search_field1',
'integrated_search_field3',
'integrated_search_field4',
'integrated_search_field5',
'integrated_search_field6',
'integrated_search_field7',
'integrated_search_field8',
'integrated_search_field9',
'integrated_search_field10',
'integrated_search_field11',
'integrated_search_field12',
'integrated_search_field15',
'integrated_search_field16',
'integrated_search_field17',
'integrated_search_field18',
'integrated_search_field13',
'integrated_search_field14',
'integrated_search_field19',
'integrated_search_field20',
'integrated_search_field21',
'integrated_search_field22',
'integrated_search_field24',
'integrated_search_field25',
'integrated_search_field26',
'integrated_search_field28',
'integrated_search_field29',
'integrated_search_field30',
'integrated_search_field31',
'integrated_search_field32',
'integrated_search_field33',
'integrated_search_field34',
'integrated_search_field35',
'integrated_search_field36',
'integrated_search_field37',
'integrated_search_field38',
'integrated_search_field39',
'integrated_search_field40',
'integrated_search_field44',
'integrated_search_field45',
'integrated_search_field46',
'integrated_search_field47',
'integrated_search_field48',
'integrated_search_field49',
'integrated_search_field50',
'integrated_search_field51',
'integrated_search_field52',
'integrated_search_field53',
'integrated_search_field54',
'integrated_search_field55',
'integrated_search_field56',
'integrated_search_field57',
'integrated_search_field58',
'integrated_search_field59',
'integrated_search_field60',
'integrated_search_field61',
'integrated_search_field2',
'integrated_search_field23',
'integrated_search_field27',
'integrated_search_field42',
'integrated_search_field43',
'integrated_search_field62',
'integrated_search_field63',
'integrated_search_field41',
'integrated_search_field64',
'integrated_search_field65',
'integrated_search_field66',
'integrated_search_field67',
'integrated_search_field68',
'integrated_search_field69',
'integrated_search_field71',
'integrated_search_field72',
'integrated_search_field73',
'integrated_search_field74',
'integrated_search_field75',
'integrated_search_field76',
'integrated_search_field70',
'integrated_search_field77',
'integrated_search_field78',
'integrated_search_field79',
'integrated_search_field80',
'integrated_search_field81',
'integrated_search_field82',
'integrated_search_field83',
'integrated_search_field84',
'integrated_search_field85' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'separateLabels' => false ) ),
'items' => array( 'search_header' => array( 'type' => 'search_header' ),
'search_search' => array( 'type' => 'search_search' ),
'search_reset' => array( 'type' => 'search_reset' ),
'search_back_list' => array( 'type' => 'search_back_list' ),
'search_cancel' => array( 'type' => 'search_cancel' ),
'integrated_search_field' => array( 'field' => 'id',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field1' => array( 'field' => 'callid',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field3' => array( 'field' => 'applicantName',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field4' => array( 'field' => 'applicantIdNumber',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field5' => array( 'field' => 'applicantAddress',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field6' => array( 'field' => 'applicantPostalCode',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field7' => array( 'field' => 'applicantTaxRegistrationNumber',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field8' => array( 'field' => 'applicantTaxOffice',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field9' => array( 'field' => 'applicantEmail',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field10' => array( 'field' => 'applicantProfession',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field11' => array( 'field' => 'applicantKod',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field12' => array( 'field' => 'applicantGemi',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field15' => array( 'field' => 'contactName',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field16' => array( 'field' => 'contactPhone',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field17' => array( 'field' => 'contactMobile',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field18' => array( 'field' => 'contactEmail',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field13' => array( 'field' => 'applicantPhone',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field14' => array( 'field' => 'applicantMobile',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field19' => array( 'field' => 'legalName',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field20' => array( 'field' => 'legalIdNumber',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field21' => array( 'field' => 'mailAddress',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field22' => array( 'field' => 'mailPostalCode',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field24' => array( 'field' => 'powerAddress',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field25' => array( 'field' => 'powerOwnershipType',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field26' => array( 'field' => 'powerPostalCode',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field28' => array( 'field' => 'powerAgreedKw',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field29' => array( 'field' => 'powerSupplyNumber',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field30' => array( 'field' => 'powerMeterNumber',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field31' => array( 'field' => 'powerCurrentSupplier',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field32' => array( 'field' => 'powerCurrentDayMeter',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field33' => array( 'field' => 'powerCurrentNightMeter',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field34' => array( 'field' => 'powerActivationStatus',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field35' => array( 'field' => 'voltonPlan',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field36' => array( 'field' => 'voltonContractDuration',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field37' => array( 'field' => 'voltonWarrantyAmount',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field38' => array( 'field' => 'voltonWarrantyOnFirstBill',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field39' => array( 'field' => 'voltonOther',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field40' => array( 'field' => 'voltonComments',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field44' => array( 'field' => 'voltonAutoPayment',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field45' => array( 'field' => 'applicationType',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field46' => array( 'field' => 'applicantWorkPhone',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field47' => array( 'field' => 'document1',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field48' => array( 'field' => 'document2',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field49' => array( 'field' => 'document3',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field50' => array( 'field' => 'document4',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field51' => array( 'field' => 'document5',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field52' => array( 'field' => 'document6',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field53' => array( 'field' => 'document7',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field54' => array( 'field' => 'document8',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field55' => array( 'field' => 'document9',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field56' => array( 'field' => 'document10',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field57' => array( 'field' => 'document11',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field58' => array( 'field' => 'document12',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field59' => array( 'field' => 'document13',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field60' => array( 'field' => 'document14',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field61' => array( 'field' => 'document15',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field2' => array( 'field' => 'applicationStatusId',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field23' => array( 'field' => 'applicantArea',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field27' => array( 'field' => 'applicantCity',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field42' => array( 'field' => 'mailArea',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field43' => array( 'field' => 'mailCity',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field62' => array( 'field' => 'powerArea',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field63' => array( 'field' => 'powerCity',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field41' => array( 'field' => 'ngAddress',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field64' => array( 'field' => 'ngPostalCode',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field65' => array( 'field' => 'ngArea',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field66' => array( 'field' => 'ngCity',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field67' => array( 'field' => 'ngPressure',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field68' => array( 'field' => 'ngHourlyCapacity',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field69' => array( 'field' => 'ngHkasp',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field71' => array( 'field' => 'ngMeterNumber',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field72' => array( 'field' => 'ngMeterType',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field73' => array( 'field' => 'ngCurrentMeterValue',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field74' => array( 'field' => 'ngConnectionExists',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field75' => array( 'field' => 'ngSupplyIsNew',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field76' => array( 'field' => 'ngSupplyReactivation',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field70' => array( 'field' => 'applicationAgentStatus',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field77' => array( 'field' => 'applicationLastStatusDate',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field78' => array( 'field' => 'applicationContactMethod',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field79' => array( 'field' => 'applicationCourier',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field80' => array( 'field' => 'applicationCourierDate',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field81' => array( 'field' => 'applicationCourrierTimeFrom',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field82' => array( 'field' => 'applicationCourierTimeTo',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field83' => array( 'field' => 'applicationCourrierComments',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field84' => array( 'field' => 'dialerAgent',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'logout_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login' ),
'logout_link' => array( 'type' => 'logout_link' ),
'integrated_search_field85' => array( 'field' => 'additionalServices',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>