<?php
			$optionsArray = array( 'list' => array( 'inlineAdd' => true,
'detailsAdd' => true,
'inlineEdit' => true,
'delete' => true,
'updateSelected' => false,
'addInPopup' => null,
'editInPopup' => null,
'viewInPopup' => null,
'clickSort' => false,
'sortDropdown' => false,
'showHideFields' => false,
'reorderFields' => false ),
'listSearch' => array( 'alwaysOnPanelFields' => array(  ),
'searchPanel' => false,
'fixedSearchPanel' => false,
'simpleSearchOptions' => false,
'searchSaving' => false ),
'totals' => array( 'id' => array( 'totalsType' => '' ),
'callphone' => array( 'totalsType' => '' ),
'agent' => array( 'totalsType' => '' ),
'dialerCampaign' => array( 'totalsType' => '' ),
'dialerList' => array( 'totalsType' => '' ),
'callDate' => array( 'totalsType' => '' ),
'agentApplicationStatus' => array( 'totalsType' => '' ),
'applicationStatusId' => array( 'totalsType' => '' ),
'applicationPhaseStatusId' => array( 'totalsType' => '' ),
'lastStatusDate' => array( 'totalsType' => '' ),
'applicationAge' => array( 'totalsType' => '' ),
'forCount' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'applicationStatusId' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'filterFields' => array(  ),
'inlineAddFields' => array( 'applicationStatusId' ),
'inlineEditFields' => array( 'applicationStatusId' ),
'fieldItems' => array( 'applicationStatusId' => array( 'simple_grid_field2',
'simple_grid_field66' ) ),
'hideEmptyFields' => array(  ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => true ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array( 'logo',
'menu',
'simple_search',
'list_options',
'loginform_login',
'username_button' ),
'left' => array( 'filter_panel' ),
'top' => array(  ),
'above-grid' => array( 'details_found',
'page_size',
'print_panel',
'image1',
'inline_add3',
'inline_save_all' ),
'below-grid' => array( 'inline_cancel_all1',
'delete1',
'pagination' ),
'grid' => array( 'grid_checkbox',
'grid_inline_edit',
'grid_inline_save',
'grid_inline_cancel',
'grid_copy',
'details_preview',
'text',
'text1',
'text6',
'text3',
'simple_grid_field66',
'simple_grid_field2',
'text2',
'text4',
'text5',
'image',
'text7',
'inline_add',
'delete' ) ),
'formXtTags' => array( 'top' => array(  ),
'below-grid' => array( 'cancelall_link',
'deleteselected_link',
'pagination' ) ),
'itemForms' => array( 'logo' => 'supertop',
'menu' => 'supertop',
'simple_search' => 'supertop',
'list_options' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'filter_panel' => 'left',
'details_found' => 'above-grid',
'page_size' => 'above-grid',
'print_panel' => 'above-grid',
'image1' => 'above-grid',
'inline_add3' => 'above-grid',
'inline_save_all' => 'above-grid',
'inline_cancel_all1' => 'below-grid',
'delete1' => 'below-grid',
'pagination' => 'below-grid',
'grid_checkbox' => 'grid',
'grid_inline_edit' => 'grid',
'grid_inline_save' => 'grid',
'grid_inline_cancel' => 'grid',
'grid_copy' => 'grid',
'details_preview' => 'grid',
'text' => 'grid',
'text1' => 'grid',
'text6' => 'grid',
'text3' => 'grid',
'simple_grid_field66' => 'grid',
'simple_grid_field2' => 'grid',
'text2' => 'grid',
'text4' => 'grid',
'text5' => 'grid',
'image' => 'grid',
'text7' => 'grid',
'inline_add' => 'grid',
'delete' => 'grid' ),
'itemLocations' => array( 'grid_checkbox' => array( 'location' => 'grid',
'cellId' => 'cell_top' ),
'grid_inline_edit' => array( 'location' => 'grid',
'cellId' => 'cell_top' ),
'grid_inline_save' => array( 'location' => 'grid',
'cellId' => 'cell_top' ),
'grid_inline_cancel' => array( 'location' => 'grid',
'cellId' => 'cell_top' ),
'grid_copy' => array( 'location' => 'grid',
'cellId' => 'cell_top' ),
'details_preview' => array( 'location' => 'grid',
'cellId' => 'cell_dpreview' ),
'text' => array( 'location' => 'grid',
'cellId' => 'cell_label' ),
'text1' => array( 'location' => 'grid',
'cellId' => 'cell_label16' ),
'text6' => array( 'location' => 'grid',
'cellId' => 'cell_label24' ),
'text3' => array( 'location' => 'grid',
'cellId' => 'cell_label44' ),
'simple_grid_field66' => array( 'location' => 'grid',
'cellId' => 'cell_field66' ),
'simple_grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field66' ),
'text2' => array( 'location' => 'grid',
'cellId' => 'cell_label39' ),
'text4' => array( 'location' => 'grid',
'cellId' => 'cell_label63' ),
'text5' => array( 'location' => 'grid',
'cellId' => 'cell_label147' ),
'image' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'text7' => array( 'location' => 'grid',
'cellId' => 'cell_label172' ),
'inline_add' => array( 'location' => 'grid',
'cellId' => 'cell_label18' ),
'delete' => array( 'location' => 'grid',
'cellId' => 'cell_label18' ) ),
'itemVisiblity' => array( 'menu' => 3,
'simple_search' => 3,
'list_options' => 3,
'loginform_login' => 3,
'username_button' => 3,
'filter_panel' => 3,
'print_panel' => 5 ) ),
'itemsByType' => array( 'page_size' => array( 'page_size' ),
'details_found' => array( 'details_found' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'simple_search' => array( 'simple_search' ),
'pagination' => array( 'pagination' ),
'grid_field' => array( 'simple_grid_field2' ),
'grid_field_label' => array( 'simple_grid_field66' ),
'image' => array( 'image1',
'image' ),
'grid_checkbox' => array( 'grid_checkbox' ),
'grid_inline_edit' => array( 'grid_inline_edit' ),
'grid_inline_save' => array( 'grid_inline_save' ),
'grid_inline_cancel' => array( 'grid_inline_cancel' ),
'text' => array( 'text',
'text3',
'text5',
'text1',
'text6',
'text2',
'text4',
'text7' ),
'list_options' => array( 'list_options' ),
'print_panel' => array( 'print_panel' ),
'print_scope' => array( 'print_scope' ),
'print_button' => array( 'print_button' ),
'print_records' => array( 'print_records' ),
'inline_save_all' => array( 'inline_save_all' ),
'edit_selected' => array( 'edit_selected' ),
'-' => array( '-',
'-1',
'-2',
'-3',
'-4',
'-5',
'-6' ),
'delete' => array( 'delete',
'delete1' ),
'delete_selected' => array( 'delete_selected' ),
'filter_panel' => array( 'filter_panel' ),
'inline_cancel_all' => array( 'inline_cancel_all1' ),
'grid_checkbox_head' => array( 'grid_checkbox_head' ),
'print_details' => array( 'print_details' ),
'details_preview' => array( 'details_preview' ),
'grid_copy' => array( 'grid_copy' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'logout_link' => array( 'logout_link' ),
'inline_add' => array( 'inline_add',
'inline_add3' ),
'export' => array( 'export' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'cell_top' => array( 'cols' => array( 0,
1,
2,
3,
4,
5,
6,
7 ),
'rows' => array( 0 ),
'tags' => array( 'checkbox_column',
'inlineedit_column',
'inline_save',
'inline_cancel',
'copy_column' ),
'items' => array( 'grid_checkbox',
'grid_inline_edit',
'grid_inline_save',
'grid_inline_cancel',
'grid_copy' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 0,
1,
2,
3,
4,
5,
6,
7 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'image' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'cell_field64' => array( 'cols' => array( 0,
1,
2,
3 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field66' => array( 'cols' => array( 4 ),
'rows' => array( 2 ),
'tags' => array( 'applicationStatusId_fieldheadercolumn',
'applicationStatusId_fieldcolumn' ),
'items' => array( 'simple_grid_field66',
'simple_grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field67' => array( 'cols' => array( 5 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field68' => array( 'cols' => array( 6 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field69' => array( 'cols' => array( 7 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label' => array( 'cols' => array( 0,
1,
2,
3 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'text' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'cell_label1' => array( 'cols' => array( 4 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field1' => array( 'cols' => array( 5 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label2' => array( 'cols' => array( 6 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field2' => array( 'cols' => array( 7 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label16' => array( 'cols' => array( 0,
1,
2,
3,
4,
5,
6,
7 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'text1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'cell_field104' => array( 'cols' => array( 0,
1,
2 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'cell_field105' => array( 'cols' => array( 3 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'cell_field106' => array( 'cols' => array( 4 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field107' => array( 'cols' => array( 5 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field108' => array( 'cols' => array( 6 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field109' => array( 'cols' => array( 7 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label24' => array( 'cols' => array( 0,
1,
2,
3,
4,
5,
6,
7 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array( 'text6' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'cell_label39' => array( 'cols' => array( 0,
1,
2,
3,
4,
5,
6,
7 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array( 'text2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'cell_label44' => array( 'cols' => array( 0,
1,
2,
3,
4,
5,
6,
7 ),
'rows' => array( 8 ),
'tags' => array(  ),
'items' => array( 'text3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'cell_label172' => array( 'cols' => array( 0,
1,
2,
3,
4,
5,
6,
7 ),
'rows' => array( 9 ),
'tags' => array(  ),
'items' => array( 'text7' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'cell_label63' => array( 'cols' => array( 0,
1,
2,
3,
4,
5,
6,
7 ),
'rows' => array( 10 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'cell_label87' => array( 'cols' => array( 0,
1,
2 ),
'rows' => array( 11 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label88' => array( 'cols' => array( 3 ),
'rows' => array( 11 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label89' => array( 'cols' => array( 4 ),
'rows' => array( 11 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label90' => array( 'cols' => array( 5 ),
'rows' => array( 11 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label91' => array( 'cols' => array( 6 ),
'rows' => array( 11 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label92' => array( 'cols' => array( 7 ),
'rows' => array( 11 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label147' => array( 'cols' => array( 0,
1,
2 ),
'rows' => array( 12 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'cell_label148' => array( 'cols' => array( 3 ),
'rows' => array( 12 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label149' => array( 'cols' => array( 4 ),
'rows' => array( 12 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label150' => array( 'cols' => array( 5 ),
'rows' => array( 12 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label151' => array( 'cols' => array( 6 ),
'rows' => array( 12 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label152' => array( 'cols' => array( 7 ),
'rows' => array( 12 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label185' => array( 'cols' => array( 0,
1,
2 ),
'rows' => array( 13 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label186' => array( 'cols' => array( 3 ),
'rows' => array( 13 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label187' => array( 'cols' => array( 4 ),
'rows' => array( 13 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label188' => array( 'cols' => array( 5 ),
'rows' => array( 13 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label189' => array( 'cols' => array( 6 ),
'rows' => array( 13 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label190' => array( 'cols' => array( 7 ),
'rows' => array( 13 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label18' => array( 'cols' => array( 0,
1,
2,
3 ),
'rows' => array( 14 ),
'tags' => array( 'inlineadd_link',
'deleteselected_link' ),
'items' => array( 'inline_add',
'delete' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label19' => array( 'cols' => array( 4 ),
'rows' => array( 14 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field18' => array( 'cols' => array( 5 ),
'rows' => array( 14 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label23' => array( 'cols' => array( 6 ),
'rows' => array( 14 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field19' => array( 'cols' => array( 7 ),
'rows' => array( 14 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label3' => array( 'cols' => array( 0 ),
'rows' => array( 15 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field3' => array( 'cols' => array( 1 ),
'rows' => array( 15 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label7' => array( 'cols' => array( 2 ),
'rows' => array( 15 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field7' => array( 'cols' => array( 3 ),
'rows' => array( 15 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label11' => array( 'cols' => array( 4 ),
'rows' => array( 15 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field11' => array( 'cols' => array( 5 ),
'rows' => array( 15 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label15' => array( 'cols' => array( 6 ),
'rows' => array( 15 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field15' => array( 'cols' => array( 7 ),
'rows' => array( 15 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label17' => array( 'cols' => array( 0 ),
'rows' => array( 16 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field16' => array( 'cols' => array( 1 ),
'rows' => array( 16 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label25' => array( 'cols' => array( 2 ),
'rows' => array( 16 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field17' => array( 'cols' => array( 3 ),
'rows' => array( 16 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label26' => array( 'cols' => array( 4 ),
'rows' => array( 16 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field23' => array( 'cols' => array( 5 ),
'rows' => array( 16 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label31' => array( 'cols' => array( 6 ),
'rows' => array( 16 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field24' => array( 'cols' => array( 7 ),
'rows' => array( 16 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_dpreview' => array( 'cols' => array( 0,
1,
2,
3,
4,
5,
6,
7 ),
'rows' => array( 17 ),
'tags' => array(  ),
'items' => array( 'details_preview' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 8,
'height' => 18 ) ) ),
'loginForm' => array( 'loginForm' => 1 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array( 'details_found' => array( 'tag' => 'DISPLAYING',
'type' => 2 ) ) ),
'gridType' => 2,
'recsPerRow' => 1,
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'list',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dataGrid' => array( 'groupFields' => array(  ) ) );
			$pageArray = array( 'id' => 'voltonInDetailAddList',
'type' => 'list',
'layoutId' => 'topbar',
'disabled' => 0,
'default' => 2,
'forms' => array( 'supertop' => array( 'modelId' => 'topbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'logo',
'menu' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'simple_search',
'list_options',
'loginform_login',
'username_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'list-vbar',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c2' => array( 'model' => 'c2',
'items' => array( 'filter_panel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'list-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c3' ) ),
'section' => '' ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'list-above-grid',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ),
array( 'cell' => 'c5' ) ) ),
array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c3' ),
array( 'cell' => 'c4' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'details_found',
'page_size',
'print_panel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c3' => array( 'model' => 'c3',
'items' => array( 'image1' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c4' => array( 'model' => 'c4',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array( 'inline_add3',
'inline_save_all' ) ),
'c5' => array( 'model' => 'c2',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'list-below-grid',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ) ) ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array( 'inline_cancel_all1',
'delete1',
'pagination' ),
'align' => 'left' ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'columns-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'cell_top',
'colspan' => 8 ) ),
'section' => 'head' ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_field',
'colspan' => 8 ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_field64',
'colspan' => 4 ),
array( 'cell' => 'cell_field66' ),
array( 'cell' => 'cell_field67' ),
array( 'cell' => 'cell_field68' ),
array( 'cell' => 'cell_field69' ) ) ),
array( 'cells' => array( array( 'cell' => 'cell_label',
'colspan' => 4 ),
array( 'cell' => 'cell_label1' ),
array( 'cell' => 'cell_field1' ),
array( 'cell' => 'cell_label2' ),
array( 'cell' => 'cell_field2' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label16',
'colspan' => 8 ) ),
'section' => 'body' ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_field104',
'colspan' => 3 ),
array( 'cell' => 'cell_field105' ),
array( 'cell' => 'cell_field106' ),
array( 'cell' => 'cell_field107' ),
array( 'cell' => 'cell_field108' ),
array( 'cell' => 'cell_field109' ) ) ),
array( 'cells' => array( array( 'cell' => 'cell_label24',
'colspan' => 8 ) ),
'section' => 'body' ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_label39',
'colspan' => 8 ) ) ),
array( 'cells' => array( array( 'cell' => 'cell_label44',
'colspan' => 8 ) ),
'section' => 'body' ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_label172',
'colspan' => 8 ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_label63',
'colspan' => 8 ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_label87',
'colspan' => 3 ),
array( 'cell' => 'cell_label88' ),
array( 'cell' => 'cell_label89' ),
array( 'cell' => 'cell_label90' ),
array( 'cell' => 'cell_label91' ),
array( 'cell' => 'cell_label92' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_label147',
'colspan' => 3 ),
array( 'cell' => 'cell_label148' ),
array( 'cell' => 'cell_label149' ),
array( 'cell' => 'cell_label150' ),
array( 'cell' => 'cell_label151' ),
array( 'cell' => 'cell_label152' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_label185',
'colspan' => 3 ),
array( 'cell' => 'cell_label186' ),
array( 'cell' => 'cell_label187' ),
array( 'cell' => 'cell_label188' ),
array( 'cell' => 'cell_label189' ),
array( 'cell' => 'cell_label190' ) ) ),
array( 'cells' => array( array( 'cell' => 'cell_label18',
'colspan' => 4 ),
array( 'cell' => 'cell_label19' ),
array( 'cell' => 'cell_field18' ),
array( 'cell' => 'cell_label23' ),
array( 'cell' => 'cell_field19' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label3' ),
array( 'cell' => 'cell_field3' ),
array( 'cell' => 'cell_label7' ),
array( 'cell' => 'cell_field7' ),
array( 'cell' => 'cell_label11' ),
array( 'cell' => 'cell_field11' ),
array( 'cell' => 'cell_label15' ),
array( 'cell' => 'cell_field15' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label17' ),
array( 'cell' => 'cell_field16' ),
array( 'cell' => 'cell_label25' ),
array( 'cell' => 'cell_field17' ),
array( 'cell' => 'cell_label26' ),
array( 'cell' => 'cell_field23' ),
array( 'cell' => 'cell_label31' ),
array( 'cell' => 'cell_field24' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_dpreview',
'colspan' => 8 ) ),
'section' => 'foot' ) ),
'cells' => array( 'cell_top' => array( 'model' => 'cell_top',
'items' => array( 'grid_checkbox',
'grid_inline_edit',
'grid_inline_save',
'grid_inline_cancel',
'grid_copy' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_dpreview' => array( 'model' => 'cell_dpreview',
'items' => array( 'details_preview' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'cell_label' => array( 'model' => 'cell_label',
'items' => array( 'text' ),
'background' => '#110ad6',
'align' => 'left',
'color' => '#ffffff',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_label1' => array( 'model' => 'cell_label',
'items' => array(  ),
'background' => '#110ad6',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_field1' => array( 'model' => 'cell_field',
'items' => array(  ),
'background' => '#110ad6',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_label2' => array( 'model' => 'cell_label',
'items' => array(  ),
'background' => '#110ad6',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_field2' => array( 'model' => 'cell_field',
'items' => array(  ),
'background' => '#110ad6',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_label16' => array( 'model' => 'cell_label',
'items' => array( 'text1' ),
'background' => '#110ad6',
'color' => '#ffffff',
'align' => 'left',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_label24' => array( 'model' => 'cell_label',
'items' => array( 'text6' ),
'align' => 'left',
'background' => '#110ad6',
'color' => '#ffffff',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_label44' => array( 'model' => 'cell_label',
'items' => array( 'text3' ),
'background' => '#110ad6',
'align' => 'left',
'color' => '#ffffff',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_field64' => array( 'model' => 'cell_label',
'items' => array(  ),
'orientation' => 'vertical',
'align' => 'center',
'background' => '#fbffc6',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_field66' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field66',
'simple_grid_field2' ),
'align' => 'center',
'orientation' => 'vertical',
'background' => '#fbffc6',
'border' => array( array( 'side' => '',
'width' => '0' ) ),
'field' => 'applicationStatusId',
'columnName' => 'field' ),
'cell_field68' => array( 'model' => 'cell_label',
'items' => array(  ),
'align' => 'center',
'orientation' => 'vertical',
'background' => '#fbffc6',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_field69' => array( 'model' => 'cell_field',
'items' => array(  ),
'background' => '#fbffc6',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_label39' => array( 'model' => 'cell_label',
'items' => array( 'text2' ),
'background' => '#110ad6',
'align' => 'left',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_field104' => array( 'model' => 'cell_label',
'items' => array(  ),
'persistent' => true,
'background' => '#f2fffe',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_field105' => array( 'model' => 'cell_field',
'items' => array(  ),
'persistent' => true,
'background' => '#f2fffe',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_field106' => array( 'model' => 'cell_label',
'items' => array(  ),
'background' => '#f2fffe',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_field107' => array( 'model' => 'cell_field',
'items' => array(  ),
'background' => '#f2fffe',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_field108' => array( 'model' => 'cell_label',
'items' => array(  ),
'background' => '#f2fffe',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_field109' => array( 'model' => 'cell_field',
'items' => array(  ),
'background' => '#f2fffe',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_label63' => array( 'model' => 'cell_label',
'items' => array( 'text4' ),
'persistent' => true,
'align' => 'left',
'background' => '#110ad6',
'color' => '#ffffff',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_label87' => array( 'model' => 'cell_label',
'items' => array(  ),
'background' => '#f2fffe',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_label88' => array( 'model' => 'cell_field',
'items' => array(  ),
'background' => '#f2fffe',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_label89' => array( 'model' => 'cell_label',
'items' => array(  ),
'background' => '#f2fffe',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_label90' => array( 'model' => 'cell_field',
'items' => array(  ),
'background' => '#f2fffe',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_label91' => array( 'model' => 'cell_label',
'items' => array(  ),
'background' => '#f2fffe',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_label92' => array( 'model' => 'cell_field',
'items' => array(  ),
'background' => '#f2fffe',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_label147' => array( 'model' => 'cell_label',
'items' => array( 'text5' ),
'persistent' => true,
'background' => '#110ad6',
'align' => 'left',
'color' => '#ffffff',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_label148' => array( 'model' => 'cell_field',
'items' => array(  ),
'background' => '#110ad6',
'color' => '#ffffff',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_label149' => array( 'model' => 'cell_label',
'items' => array(  ),
'background' => '#110ad6',
'color' => '#ffffff',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_label150' => array( 'model' => 'cell_field',
'items' => array(  ),
'background' => '#110ad6',
'color' => '#ffffff',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_label151' => array( 'model' => 'cell_label',
'items' => array(  ),
'background' => '#110ad6',
'color' => '#ffffff',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_label152' => array( 'model' => 'cell_field',
'items' => array(  ),
'background' => '#110ad6',
'color' => '#ffffff',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_field' => array( 'model' => 'cell_label',
'items' => array( 'image' ),
'align' => 'center',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_label172' => array( 'model' => 'cell_label',
'items' => array( 'text7' ),
'align' => 'left',
'background' => '#110ad6',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_label18' => array( 'model' => 'cell_label',
'items' => array( 'inline_add',
'delete' ),
'align' => 'center',
'background' => '#d8e4ff',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_label19' => array( 'model' => 'cell_label',
'items' => array(  ),
'align' => 'center',
'background' => '#d8e4ff',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_field18' => array( 'model' => 'cell_field',
'items' => array(  ),
'background' => '#d8e4ff',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_label23' => array( 'model' => 'cell_label',
'items' => array(  ),
'background' => '#d8e4ff',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_field19' => array( 'model' => 'cell_field',
'items' => array(  ),
'background' => '#d8e4ff',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_field67' => array( 'model' => 'cell_label',
'items' => array(  ),
'align' => 'center',
'orientation' => 'vertical',
'background' => '#fbffc6',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_label185' => array( 'model' => 'cell_label',
'items' => array(  ),
'background' => '#f2fffe',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_label186' => array( 'model' => 'cell_field',
'items' => array(  ),
'background' => '#f2fffe',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_label187' => array( 'model' => 'cell_label',
'items' => array(  ),
'background' => '#f2fffe',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_label188' => array( 'model' => 'cell_field',
'items' => array(  ),
'background' => '#f2fffe',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_label189' => array( 'model' => 'cell_label',
'items' => array(  ),
'background' => '#f2fffe',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_label190' => array( 'model' => 'cell_field',
'items' => array(  ),
'background' => '#f2fffe',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_label3' => array( 'model' => 'cell_label',
'items' => array(  ) ),
'cell_field3' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'cell_label7' => array( 'model' => 'cell_label',
'items' => array(  ) ),
'cell_field7' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'cell_label11' => array( 'model' => 'cell_label',
'items' => array(  ) ),
'cell_field11' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'cell_label15' => array( 'model' => 'cell_label',
'items' => array(  ) ),
'cell_field15' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'cell_label17' => array( 'model' => 'cell_label',
'items' => array(  ) ),
'cell_field16' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'cell_label25' => array( 'model' => 'cell_label',
'items' => array(  ) ),
'cell_field17' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'cell_label26' => array( 'model' => 'cell_label',
'items' => array(  ) ),
'cell_field23' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'cell_label31' => array( 'model' => 'cell_label',
'items' => array(  ) ),
'cell_field24' => array( 'model' => 'cell_field',
'items' => array(  ) ) ),
'deferredItems' => array( 'grid_checkbox_head' ),
'buildType' => 2,
'columnCount' => 4 ) ),
'items' => array( 'page_size' => array( 'type' => 'page_size' ),
'details_found' => array( 'type' => 'details_found' ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu' ),
'simple_search' => array( 'type' => 'simple_search' ),
'pagination' => array( 'type' => 'pagination' ),
'simple_grid_field2' => array( 'field' => 'applicationStatusId',
'type' => 'grid_field',
'clickSort' => false,
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field66' => array( 'type' => 'grid_field_label',
'field' => 'applicationStatusId',
'clickSort' => false ),
'image1' => array( 'type' => 'image',
'imagePath' => 'volton header.png',
'width' => '',
'height' => '' ),
'grid_checkbox' => array( 'type' => 'grid_checkbox' ),
'grid_inline_edit' => array( 'type' => 'grid_inline_edit' ),
'grid_inline_save' => array( 'type' => 'grid_inline_save' ),
'grid_inline_cancel' => array( 'type' => 'grid_inline_cancel' ),
'text' => array( 'type' => 'text',
'label' => array( 'text' => 'ΣΤΟΙΧΕΙΑ ΠΕΛΑΤΗ',
'type' => 0 ),
'editedByRte' => false ),
'text3' => array( 'type' => 'text',
'label' => array( 'text' => 'ΣΤΟΙΧΕΙΑ ΠΑΡΟΧΗΣ (ΡΕΥΜΑ)',
'type' => 0 ),
'editedByRte' => false ),
'image' => array( 'type' => 'image',
'imagePath' => 'volton header.png' ),
'list_options' => array( 'type' => 'list_options',
'items' => array( 'edit_selected',
'delete_selected',
'-6',
'export',
'-4',
'-5',
'-2',
'-3' ) ),
'print_panel' => array( 'type' => 'print_panel',
'items' => array( 'print_scope',
'print_details',
'print_records',
'print_button' ) ),
'print_scope' => array( 'type' => 'print_scope' ),
'print_button' => array( 'type' => 'print_button' ),
'print_records' => array( 'type' => 'print_records' ),
'inline_save_all' => array( 'type' => 'inline_save_all' ),
'edit_selected' => array( 'type' => 'edit_selected' ),
'-' => array( 'type' => '-' ),
'text5' => array( 'type' => 'text',
'label' => array( 'text' => 'ΔΙΚΑΙΟΛΟΓΗΤΙΚΑ',
'type' => 0 ),
'editedByRte' => false ),
'delete' => array( 'type' => 'delete',
'buttonSize' => 'large',
'buttonStyle' => 'danger' ),
'delete_selected' => array( 'type' => 'delete_selected' ),
'text1' => array( 'type' => 'text',
'label' => array( 'text' => 'ΣΤΟΙΧΕΙΑ ΝΟΜΙΜΟΥ ΕΚΠΡΟΣΩΠΟΥ',
'type' => 0 ),
'editedByRte' => false ),
'text6' => array( 'type' => 'text',
'label' => array( 'text' => 'ΣΤΟΙΧΕΙΑ ΥΠΕΥΘΥΝΟΥ ΕΠΙΚΟΙΝΩΝΙΑΣ',
'type' => 0 ),
'editedByRte' => false ),
'-1' => array( 'type' => '-' ),
'filter_panel' => array( 'type' => 'filter_panel',
'items' => array(  ) ),
'text2' => array( 'type' => 'text',
'label' => array( 'text' => 'ΔΙΕΥΘΥΝΣΗ ΑΠΟΣΤΟΛΗΣ ΛΟΓΑΡΙΑΣΜΟΥ',
'type' => 0 ),
'editedByRte' => false,
'color' => '#ffffff' ),
'text4' => array( 'type' => 'text',
'label' => array( 'text' => 'ΤΙΜΟΛΟΓΙΟ VOLTON',
'type' => 0 ),
'editedByRte' => false ),
'inline_cancel_all1' => array( 'type' => 'inline_cancel_all' ),
'delete1' => array( 'type' => 'delete' ),
'grid_checkbox_head' => array( 'type' => 'grid_checkbox_head' ),
'-2' => array( 'type' => '-' ),
'-3' => array( 'type' => '-' ),
'print_details' => array( 'type' => 'print_details',
'tables' => array( 'dbo.internalComments' => true ) ),
'details_preview' => array( 'type' => 'details_preview',
'table' => 'dbo.internalComments',
'items' => array(  ),
'popup' => true,
'hideEmptyPreview' => false,
'proceedLink' => false,
'pageId' => 'list' ),
'grid_copy' => array( 'type' => 'grid_copy' ),
'text7' => array( 'type' => 'text',
'label' => array( 'text' => 'ΣΤΟΙΧΕΙΑ ΠΑΡΟΧΗΣ (ΦΥΣΙΚΟ ΑΕΡΙΟ)',
'type' => 0 ),
'editedByRte' => false,
'color' => '#ffffff' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'logout_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => true ),
'logout_link' => array( 'type' => 'logout_link' ),
'inline_add' => array( 'type' => 'inline_add',
'label' => array( 'type' => 0,
'text' => 'Νέα Αίτηση' ),
'buttonSize' => 'large',
'buttonStyle' => 'success' ),
'inline_add3' => array( 'type' => 'inline_add',
'label' => array( 'type' => 0,
'text' => 'Νέα Αίτηση' ),
'buttonSize' => 'large',
'buttonStyle' => 'success' ),
'-4' => array( 'type' => '-' ),
'-5' => array( 'type' => '-' ),
'-6' => array( 'type' => '-' ),
'export' => array( 'type' => 'export' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>