<?php
			$optionsArray = array( 'pdf' => array( 'pdfView' => true,
'orientation' => 'portrait',
'scale' => 100 ),
'totals' => array( 'id' => array( 'totalsType' => '' ),
'callphone' => array( 'totalsType' => '' ),
'agent' => array( 'totalsType' => '' ),
'dialerCampaign' => array( 'totalsType' => '' ),
'dialerList' => array( 'totalsType' => '' ),
'callDate' => array( 'totalsType' => '' ),
'agentApplicationStatus' => array( 'totalsType' => '' ),
'applicationStatusId' => array( 'totalsType' => 'COUNT' ),
'applicationPhaseStatusId' => array( 'totalsType' => '' ),
'lastStatusDate' => array( 'totalsType' => '' ),
'applicationAge' => array( 'totalsType' => '' ),
'forCount' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'applicationStatusId',
'applicationPhaseStatusId',
'id',
'forCount',
'lastStatusDate',
'agentApplicationStatus',
'callDate',
'agent',
'callphone',
'dialerCampaign',
'dialerList',
'applicationAge' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'applicationStatusId' => array( 'simple_grid_field2',
'simple_grid_field66',
'grid_field_totals' ),
'applicationPhaseStatusId' => array( 'grid_field_label7',
'grid_field7' ),
'id' => array( 'grid_field_label6',
'grid_field6' ),
'forCount' => array( 'grid_field_label5',
'grid_field5' ),
'lastStatusDate' => array( 'grid_field_label4',
'grid_field4' ),
'agentApplicationStatus' => array( 'grid_field_label3',
'grid_field3' ),
'callDate' => array( 'grid_field_label2',
'grid_field2' ),
'agent' => array( 'grid_field_label1',
'grid_field1' ),
'callphone' => array( 'grid_field_label',
'grid_field' ),
'dialerCampaign' => array( 'grid_field8',
'grid_field_label8' ),
'dialerList' => array( 'grid_field9',
'grid_field_label9' ),
'applicationAge' => array( 'grid_field10',
'grid_field_label10' ) ),
'hideEmptyFields' => array(  ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'top' => array( 'print_header',
'print_subheader',
'master_info',
'print_pdf' ),
'above-grid' => array( 'print_pages',
'grid_field_totals' ),
'below-grid' => array(  ),
'grid' => array( 'details_preview',
'text',
'text1',
'text6',
'text3',
'simple_grid_field66',
'simple_grid_field2',
'text2',
'text4',
'text5',
'image',
'text7',
'grid_field_label4',
'grid_field4',
'grid_field_label5',
'grid_field5',
'grid_field_label6',
'grid_field6',
'grid_field_label7',
'grid_field7',
'grid_field_label',
'grid_field',
'grid_field_label1',
'grid_field1',
'grid_field_label2',
'grid_field2',
'grid_field_label3',
'grid_field3',
'grid_field_label8',
'grid_field8',
'grid_field_label9',
'grid_field9',
'grid_field_label10',
'grid_field10' ) ),
'formXtTags' => array( 'above-grid' => array( 'print_pages',
'applicationStatusId_fieldfootercolumn' ),
'below-grid' => array(  ) ),
'itemForms' => array( 'print_header' => 'top',
'print_subheader' => 'top',
'master_info' => 'top',
'print_pdf' => 'top',
'print_pages' => 'above-grid',
'grid_field_totals' => 'above-grid',
'details_preview' => 'grid',
'text' => 'grid',
'text1' => 'grid',
'text6' => 'grid',
'text3' => 'grid',
'simple_grid_field66' => 'grid',
'simple_grid_field2' => 'grid',
'text2' => 'grid',
'text4' => 'grid',
'text5' => 'grid',
'image' => 'grid',
'text7' => 'grid',
'grid_field_label4' => 'grid',
'grid_field4' => 'grid',
'grid_field_label5' => 'grid',
'grid_field5' => 'grid',
'grid_field_label6' => 'grid',
'grid_field6' => 'grid',
'grid_field_label7' => 'grid',
'grid_field7' => 'grid',
'grid_field_label' => 'grid',
'grid_field' => 'grid',
'grid_field_label1' => 'grid',
'grid_field1' => 'grid',
'grid_field_label2' => 'grid',
'grid_field2' => 'grid',
'grid_field_label3' => 'grid',
'grid_field3' => 'grid',
'grid_field_label8' => 'grid',
'grid_field8' => 'grid',
'grid_field_label9' => 'grid',
'grid_field9' => 'grid',
'grid_field_label10' => 'grid',
'grid_field10' => 'grid' ),
'itemLocations' => array( 'details_preview' => array( 'location' => 'grid',
'cellId' => 'cell_dpreview' ),
'text' => array( 'location' => 'grid',
'cellId' => 'cell_label' ),
'text1' => array( 'location' => 'grid',
'cellId' => 'cell_label16' ),
'text6' => array( 'location' => 'grid',
'cellId' => 'cell_label24' ),
'text3' => array( 'location' => 'grid',
'cellId' => 'cell_label44' ),
'simple_grid_field66' => array( 'location' => 'grid',
'cellId' => 'cell_field66' ),
'simple_grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field66' ),
'text2' => array( 'location' => 'grid',
'cellId' => 'cell_label39' ),
'text4' => array( 'location' => 'grid',
'cellId' => 'cell_label63' ),
'text5' => array( 'location' => 'grid',
'cellId' => 'cell_label147' ),
'image' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'text7' => array( 'location' => 'grid',
'cellId' => 'cell_label172' ),
'grid_field_label4' => array( 'location' => 'grid',
'cellId' => 'cell_label7' ),
'grid_field4' => array( 'location' => 'grid',
'cellId' => 'cell_field7' ),
'grid_field_label5' => array( 'location' => 'grid',
'cellId' => 'cell_label8' ),
'grid_field5' => array( 'location' => 'grid',
'cellId' => 'cell_field8' ),
'grid_field_label6' => array( 'location' => 'grid',
'cellId' => 'cell_label9' ),
'grid_field6' => array( 'location' => 'grid',
'cellId' => 'cell_field9' ),
'grid_field_label7' => array( 'location' => 'grid',
'cellId' => 'cell_label10' ),
'grid_field7' => array( 'location' => 'grid',
'cellId' => 'cell_field10' ),
'grid_field_label' => array( 'location' => 'grid',
'cellId' => 'cell_label3' ),
'grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field3' ),
'grid_field_label1' => array( 'location' => 'grid',
'cellId' => 'cell_label4' ),
'grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field4' ),
'grid_field_label2' => array( 'location' => 'grid',
'cellId' => 'cell_label5' ),
'grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field5' ),
'grid_field_label3' => array( 'location' => 'grid',
'cellId' => 'cell_label6' ),
'grid_field3' => array( 'location' => 'grid',
'cellId' => 'cell_field6' ),
'grid_field_label8' => array( 'location' => 'grid',
'cellId' => 'cell_label11' ),
'grid_field8' => array( 'location' => 'grid',
'cellId' => 'cell_field11' ),
'grid_field_label9' => array( 'location' => 'grid',
'cellId' => 'cell_label12' ),
'grid_field9' => array( 'location' => 'grid',
'cellId' => 'cell_field12' ),
'grid_field_label10' => array( 'location' => 'grid',
'cellId' => 'cell_label13' ),
'grid_field10' => array( 'location' => 'grid',
'cellId' => 'cell_field13' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'print_header' => array( 'print_header' ),
'print_subheader' => array( 'print_subheader' ),
'print_pages' => array( 'print_pages' ),
'master_info' => array( 'master_info' ),
'text' => array( 'text2',
'text3',
'text6',
'text1',
'text',
'text4',
'text5',
'text7' ),
'grid_field' => array( 'simple_grid_field2',
'grid_field7',
'grid_field6',
'grid_field5',
'grid_field4',
'grid_field3',
'grid_field2',
'grid_field1',
'grid_field',
'grid_field8',
'grid_field9',
'grid_field10' ),
'grid_field_label' => array( 'simple_grid_field66',
'grid_field_label7',
'grid_field_label6',
'grid_field_label5',
'grid_field_label4',
'grid_field_label3',
'grid_field_label2',
'grid_field_label1',
'grid_field_label',
'grid_field_label8',
'grid_field_label9',
'grid_field_label10' ),
'details_preview' => array( 'details_preview' ),
'image' => array( 'image' ),
'print_pdf' => array( 'print_pdf' ),
'grid_field_totals' => array( 'grid_field_totals' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'cell_top' => array( 'cols' => array( 0,
1,
2,
3,
4,
5,
6,
7 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 0,
1,
2,
3,
4,
5,
6,
7 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'image' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'cell_field64' => array( 'cols' => array( 0,
1,
2,
3 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field66' => array( 'cols' => array( 4 ),
'rows' => array( 2 ),
'tags' => array( 'applicationStatusId_fieldheadercolumn',
'applicationStatusId_fieldcolumn' ),
'items' => array( 'simple_grid_field66',
'simple_grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field67' => array( 'cols' => array( 5 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field68' => array( 'cols' => array( 6 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field69' => array( 'cols' => array( 7 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label' => array( 'cols' => array( 0,
1,
2,
3 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'text' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'cell_label1' => array( 'cols' => array( 4 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field1' => array( 'cols' => array( 5 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label2' => array( 'cols' => array( 6 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field2' => array( 'cols' => array( 7 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label16' => array( 'cols' => array( 0,
1,
2,
3,
4,
5,
6,
7 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'text1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'cell_field104' => array( 'cols' => array( 0,
1,
2 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'cell_field105' => array( 'cols' => array( 3 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'cell_field106' => array( 'cols' => array( 4 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field107' => array( 'cols' => array( 5 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field108' => array( 'cols' => array( 6 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field109' => array( 'cols' => array( 7 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label24' => array( 'cols' => array( 0,
1,
2,
3,
4,
5,
6,
7 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array( 'text6' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'cell_label39' => array( 'cols' => array( 0,
1,
2,
3,
4,
5,
6,
7 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array( 'text2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'cell_label44' => array( 'cols' => array( 0,
1,
2,
3,
4,
5,
6,
7 ),
'rows' => array( 8 ),
'tags' => array(  ),
'items' => array( 'text3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'cell_label172' => array( 'cols' => array( 0,
1,
2,
3,
4,
5,
6,
7 ),
'rows' => array( 9 ),
'tags' => array(  ),
'items' => array( 'text7' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'cell_label63' => array( 'cols' => array( 0,
1,
2,
3,
4,
5,
6,
7 ),
'rows' => array( 10 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'cell_label87' => array( 'cols' => array( 0,
1,
2 ),
'rows' => array( 11 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label88' => array( 'cols' => array( 3 ),
'rows' => array( 11 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label89' => array( 'cols' => array( 4 ),
'rows' => array( 11 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label90' => array( 'cols' => array( 5 ),
'rows' => array( 11 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label91' => array( 'cols' => array( 6 ),
'rows' => array( 11 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label92' => array( 'cols' => array( 7 ),
'rows' => array( 11 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label147' => array( 'cols' => array( 0,
1,
2 ),
'rows' => array( 12 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'cell_label148' => array( 'cols' => array( 3 ),
'rows' => array( 12 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label149' => array( 'cols' => array( 4 ),
'rows' => array( 12 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label150' => array( 'cols' => array( 5 ),
'rows' => array( 12 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label151' => array( 'cols' => array( 6 ),
'rows' => array( 12 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label152' => array( 'cols' => array( 7 ),
'rows' => array( 12 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label3' => array( 'cols' => array( 0 ),
'rows' => array( 13 ),
'tags' => array( 'callphone_fieldheadercolumn' ),
'items' => array( 'grid_field_label' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field3' => array( 'cols' => array( 1 ),
'rows' => array( 13 ),
'tags' => array( 'callphone_fieldcolumn' ),
'items' => array( 'grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label4' => array( 'cols' => array( 2 ),
'rows' => array( 13 ),
'tags' => array( 'agent_fieldheadercolumn' ),
'items' => array( 'grid_field_label1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field4' => array( 'cols' => array( 3 ),
'rows' => array( 13 ),
'tags' => array( 'agent_fieldcolumn' ),
'items' => array( 'grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label5' => array( 'cols' => array( 4 ),
'rows' => array( 13 ),
'tags' => array( 'callDate_fieldheadercolumn' ),
'items' => array( 'grid_field_label2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field5' => array( 'cols' => array( 5 ),
'rows' => array( 13 ),
'tags' => array( 'callDate_fieldcolumn' ),
'items' => array( 'grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label6' => array( 'cols' => array( 6 ),
'rows' => array( 13 ),
'tags' => array( 'agentApplicationStatus_fieldheadercolumn' ),
'items' => array( 'grid_field_label3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field6' => array( 'cols' => array( 7 ),
'rows' => array( 13 ),
'tags' => array( 'agentApplicationStatus_fieldcolumn' ),
'items' => array( 'grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label7' => array( 'cols' => array( 0 ),
'rows' => array( 14 ),
'tags' => array( 'lastStatusDate_fieldheadercolumn' ),
'items' => array( 'grid_field_label4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field7' => array( 'cols' => array( 1 ),
'rows' => array( 14 ),
'tags' => array( 'lastStatusDate_fieldcolumn' ),
'items' => array( 'grid_field4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label8' => array( 'cols' => array( 2 ),
'rows' => array( 14 ),
'tags' => array( 'forCount_fieldheadercolumn' ),
'items' => array( 'grid_field_label5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field8' => array( 'cols' => array( 3 ),
'rows' => array( 14 ),
'tags' => array( 'forCount_fieldcolumn' ),
'items' => array( 'grid_field5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label9' => array( 'cols' => array( 4 ),
'rows' => array( 14 ),
'tags' => array( 'id_fieldheadercolumn' ),
'items' => array( 'grid_field_label6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field9' => array( 'cols' => array( 5 ),
'rows' => array( 14 ),
'tags' => array( 'id_fieldcolumn' ),
'items' => array( 'grid_field6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label10' => array( 'cols' => array( 6 ),
'rows' => array( 14 ),
'tags' => array( 'applicationPhaseStatusId_fieldheadercolumn' ),
'items' => array( 'grid_field_label7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field10' => array( 'cols' => array( 7 ),
'rows' => array( 14 ),
'tags' => array( 'applicationPhaseStatusId_fieldcolumn' ),
'items' => array( 'grid_field7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label11' => array( 'cols' => array( 0 ),
'rows' => array( 15 ),
'tags' => array( 'dialerCampaign_fieldheadercolumn' ),
'items' => array( 'grid_field_label8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field11' => array( 'cols' => array( 1 ),
'rows' => array( 15 ),
'tags' => array( 'dialerCampaign_fieldcolumn' ),
'items' => array( 'grid_field8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label12' => array( 'cols' => array( 2 ),
'rows' => array( 15 ),
'tags' => array( 'dialerList_fieldheadercolumn' ),
'items' => array( 'grid_field_label9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field12' => array( 'cols' => array( 3 ),
'rows' => array( 15 ),
'tags' => array( 'dialerList_fieldcolumn' ),
'items' => array( 'grid_field9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label13' => array( 'cols' => array( 4 ),
'rows' => array( 15 ),
'tags' => array( 'applicationAge_fieldheadercolumn' ),
'items' => array( 'grid_field_label10' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field13' => array( 'cols' => array( 5 ),
'rows' => array( 15 ),
'tags' => array( 'applicationAge_fieldcolumn' ),
'items' => array( 'grid_field10' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label14' => array( 'cols' => array( 6 ),
'rows' => array( 15 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field14' => array( 'cols' => array( 7 ),
'rows' => array( 15 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_dpreview' => array( 'cols' => array( 0,
1,
2,
3,
4,
5,
6,
7 ),
'rows' => array( 16 ),
'tags' => array(  ),
'items' => array( 'details_preview' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 8,
'height' => 17 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array( 'print_pages' => array( 'tag' => 'PRINT_PAGES',
'type' => 2 ) ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'gridType' => 2,
'recsPerRow' => 1,
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'print',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dataGrid' => array( 'groupFields' => array(  ) ) );
			$pageArray = array( 'id' => 'print',
'type' => 'print',
'layoutId' => 'basic',
'disabled' => 0,
'default' => 0,
'forms' => array( 'top' => array( 'modelId' => 'print-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c2' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c4' ) ),
'section' => '' ) ),
'cells' => array( 'c2' => array( 'model' => 'c2',
'items' => array( 'print_header',
'print_subheader' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c4' => array( 'model' => 'c4',
'items' => array( 'master_info' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c1' => array( 'model' => 'c1',
'items' => array( 'print_pdf' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'print-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'print_pages',
'grid_field_totals' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'print-below-grid',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'columns-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'cell_top',
'colspan' => 8 ) ),
'section' => 'head' ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_field',
'colspan' => 8 ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_field64',
'colspan' => 4 ),
array( 'cell' => 'cell_field66' ),
array( 'cell' => 'cell_field67' ),
array( 'cell' => 'cell_field68' ),
array( 'cell' => 'cell_field69' ) ) ),
array( 'cells' => array( array( 'cell' => 'cell_label',
'colspan' => 4 ),
array( 'cell' => 'cell_label1' ),
array( 'cell' => 'cell_field1' ),
array( 'cell' => 'cell_label2' ),
array( 'cell' => 'cell_field2' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label16',
'colspan' => 8 ) ),
'section' => 'body' ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_field104',
'colspan' => 3 ),
array( 'cell' => 'cell_field105' ),
array( 'cell' => 'cell_field106' ),
array( 'cell' => 'cell_field107' ),
array( 'cell' => 'cell_field108' ),
array( 'cell' => 'cell_field109' ) ) ),
array( 'cells' => array( array( 'cell' => 'cell_label24',
'colspan' => 8 ) ),
'section' => 'body' ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_label39',
'colspan' => 8 ) ) ),
array( 'cells' => array( array( 'cell' => 'cell_label44',
'colspan' => 8 ) ),
'section' => 'body' ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_label172',
'colspan' => 8 ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_label63',
'colspan' => 8 ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_label87',
'colspan' => 3 ),
array( 'cell' => 'cell_label88' ),
array( 'cell' => 'cell_label89' ),
array( 'cell' => 'cell_label90' ),
array( 'cell' => 'cell_label91' ),
array( 'cell' => 'cell_label92' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_label147',
'colspan' => 3 ),
array( 'cell' => 'cell_label148' ),
array( 'cell' => 'cell_label149' ),
array( 'cell' => 'cell_label150' ),
array( 'cell' => 'cell_label151' ),
array( 'cell' => 'cell_label152' ) ) ),
array( 'cells' => array( array( 'cell' => 'cell_label3' ),
array( 'cell' => 'cell_field3' ),
array( 'cell' => 'cell_label4' ),
array( 'cell' => 'cell_field4' ),
array( 'cell' => 'cell_label5' ),
array( 'cell' => 'cell_field5' ),
array( 'cell' => 'cell_label6' ),
array( 'cell' => 'cell_field6' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label7' ),
array( 'cell' => 'cell_field7' ),
array( 'cell' => 'cell_label8' ),
array( 'cell' => 'cell_field8' ),
array( 'cell' => 'cell_label9' ),
array( 'cell' => 'cell_field9' ),
array( 'cell' => 'cell_label10' ),
array( 'cell' => 'cell_field10' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label11' ),
array( 'cell' => 'cell_field11' ),
array( 'cell' => 'cell_label12' ),
array( 'cell' => 'cell_field12' ),
array( 'cell' => 'cell_label13' ),
array( 'cell' => 'cell_field13' ),
array( 'cell' => 'cell_label14' ),
array( 'cell' => 'cell_field14' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_dpreview',
'colspan' => 8 ) ),
'section' => 'foot' ) ),
'cells' => array( 'cell_dpreview' => array( 'model' => 'cell_dpreview',
'items' => array( 'details_preview' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'cell_label' => array( 'model' => 'cell_label',
'items' => array( 'text' ),
'background' => '#110ad6',
'align' => 'left',
'color' => '#ffffff',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_label1' => array( 'model' => 'cell_label',
'items' => array(  ),
'background' => '#110ad6',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_field1' => array( 'model' => 'cell_field',
'items' => array(  ),
'background' => '#110ad6',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_label2' => array( 'model' => 'cell_label',
'items' => array(  ),
'background' => '#110ad6',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_field2' => array( 'model' => 'cell_field',
'items' => array(  ),
'background' => '#110ad6',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_label16' => array( 'model' => 'cell_label',
'items' => array( 'text1' ),
'background' => '#110ad6',
'color' => '#ffffff',
'align' => 'left',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_label24' => array( 'model' => 'cell_label',
'items' => array( 'text6' ),
'align' => 'left',
'background' => '#110ad6',
'color' => '#ffffff',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_label44' => array( 'model' => 'cell_label',
'items' => array( 'text3' ),
'background' => '#110ad6',
'align' => 'left',
'color' => '#ffffff',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_field64' => array( 'model' => 'cell_label',
'items' => array(  ),
'orientation' => 'vertical',
'align' => 'center',
'background' => '#fbffc6',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_field66' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field66',
'simple_grid_field2' ),
'align' => 'center',
'orientation' => 'vertical',
'background' => '#fbffc6',
'border' => array( array( 'side' => '',
'width' => '0' ) ),
'field' => 'applicationStatusId',
'columnName' => 'field' ),
'cell_field68' => array( 'model' => 'cell_label',
'items' => array(  ),
'align' => 'center',
'orientation' => 'vertical',
'background' => '#fbffc6',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_field69' => array( 'model' => 'cell_field',
'items' => array(  ),
'background' => '#fbffc6',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_label39' => array( 'model' => 'cell_label',
'items' => array( 'text2' ),
'background' => '#110ad6',
'align' => 'left',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_field104' => array( 'model' => 'cell_label',
'items' => array(  ),
'persistent' => true,
'background' => '#f2fffe',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_field105' => array( 'model' => 'cell_field',
'items' => array(  ),
'persistent' => true,
'background' => '#f2fffe',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_field106' => array( 'model' => 'cell_label',
'items' => array(  ),
'background' => '#f2fffe',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_field107' => array( 'model' => 'cell_field',
'items' => array(  ),
'background' => '#f2fffe',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_field108' => array( 'model' => 'cell_label',
'items' => array(  ),
'background' => '#f2fffe',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_field109' => array( 'model' => 'cell_field',
'items' => array(  ),
'background' => '#f2fffe',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_label63' => array( 'model' => 'cell_label',
'items' => array( 'text4' ),
'persistent' => true,
'align' => 'left',
'background' => '#110ad6',
'color' => '#ffffff',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_label87' => array( 'model' => 'cell_label',
'items' => array(  ),
'background' => '#f2fffe',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_label88' => array( 'model' => 'cell_field',
'items' => array(  ),
'background' => '#f2fffe',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_label89' => array( 'model' => 'cell_label',
'items' => array(  ),
'background' => '#f2fffe',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_label90' => array( 'model' => 'cell_field',
'items' => array(  ),
'background' => '#f2fffe',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_label91' => array( 'model' => 'cell_label',
'items' => array(  ),
'background' => '#f2fffe',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_label92' => array( 'model' => 'cell_field',
'items' => array(  ),
'background' => '#f2fffe',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_label147' => array( 'model' => 'cell_label',
'items' => array( 'text5' ),
'persistent' => true,
'background' => '#110ad6',
'align' => 'left',
'color' => '#ffffff',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_label148' => array( 'model' => 'cell_field',
'items' => array(  ),
'background' => '#110ad6',
'color' => '#ffffff',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_label149' => array( 'model' => 'cell_label',
'items' => array(  ),
'background' => '#110ad6',
'color' => '#ffffff',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_label150' => array( 'model' => 'cell_field',
'items' => array(  ),
'background' => '#110ad6',
'color' => '#ffffff',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_label151' => array( 'model' => 'cell_label',
'items' => array(  ),
'background' => '#110ad6',
'color' => '#ffffff',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_label152' => array( 'model' => 'cell_field',
'items' => array(  ),
'background' => '#110ad6',
'color' => '#ffffff',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_field' => array( 'model' => 'cell_label',
'items' => array( 'image' ),
'align' => 'center',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_label172' => array( 'model' => 'cell_label',
'items' => array( 'text7' ),
'align' => 'left',
'background' => '#110ad6',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_field67' => array( 'model' => 'cell_label',
'items' => array(  ),
'align' => 'center',
'orientation' => 'vertical',
'background' => '#fbffc6',
'border' => array( array( 'side' => '',
'width' => '0' ) ) ),
'cell_top' => array( 'model' => 'cell_top',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'cell_label7' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label4' ),
'field' => 'lastStatusDate',
'columnName' => 'field' ),
'cell_field7' => array( 'model' => 'cell_field',
'items' => array( 'grid_field4' ),
'field' => 'lastStatusDate',
'columnName' => 'field' ),
'cell_label8' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label5' ),
'field' => 'forCount',
'columnName' => 'field' ),
'cell_field8' => array( 'model' => 'cell_field',
'items' => array( 'grid_field5' ),
'field' => 'forCount',
'columnName' => 'field' ),
'cell_label9' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label6' ),
'field' => 'id',
'columnName' => 'field' ),
'cell_field9' => array( 'model' => 'cell_field',
'items' => array( 'grid_field6' ),
'field' => 'id',
'columnName' => 'field' ),
'cell_label10' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label7' ),
'field' => 'applicationPhaseStatusId',
'columnName' => 'field' ),
'cell_field10' => array( 'model' => 'cell_field',
'items' => array( 'grid_field7' ),
'field' => 'applicationPhaseStatusId',
'columnName' => 'field' ),
'cell_label3' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label' ),
'field' => 'callphone',
'columnName' => 'field' ),
'cell_field3' => array( 'model' => 'cell_field',
'items' => array( 'grid_field' ),
'field' => 'callphone',
'columnName' => 'field' ),
'cell_label4' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label1' ),
'field' => 'agent',
'columnName' => 'field' ),
'cell_field4' => array( 'model' => 'cell_field',
'items' => array( 'grid_field1' ),
'field' => 'agent',
'columnName' => 'field' ),
'cell_label5' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label2' ),
'field' => 'callDate',
'columnName' => 'field' ),
'cell_field5' => array( 'model' => 'cell_field',
'items' => array( 'grid_field2' ),
'field' => 'callDate',
'columnName' => 'field' ),
'cell_label6' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label3' ),
'field' => 'agentApplicationStatus',
'columnName' => 'field' ),
'cell_field6' => array( 'model' => 'cell_field',
'items' => array( 'grid_field3' ),
'field' => 'agentApplicationStatus',
'columnName' => 'field' ),
'cell_label11' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label8' ),
'field' => 'dialerCampaign',
'columnName' => 'field' ),
'cell_field11' => array( 'model' => 'cell_field',
'items' => array( 'grid_field8' ),
'field' => 'dialerCampaign',
'columnName' => 'field' ),
'cell_label12' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label9' ),
'field' => 'dialerList',
'columnName' => 'field' ),
'cell_field12' => array( 'model' => 'cell_field',
'items' => array( 'grid_field9' ),
'field' => 'dialerList',
'columnName' => 'field' ),
'cell_label13' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label10' ),
'field' => 'applicationAge',
'columnName' => 'field' ),
'cell_field13' => array( 'model' => 'cell_field',
'items' => array( 'grid_field10' ),
'field' => 'applicationAge',
'columnName' => 'field' ),
'cell_label14' => array( 'model' => 'cell_label',
'items' => array(  ) ),
'cell_field14' => array( 'model' => 'cell_field',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'buildType' => 2,
'columnCount' => 4 ) ),
'items' => array( 'print_header' => array( 'type' => 'print_header' ),
'print_subheader' => array( 'type' => 'print_subheader' ),
'print_pages' => array( 'type' => 'print_pages' ),
'master_info' => array( 'type' => 'master_info',
'tables' => array( 'dbo.Calls' => 'true',
'dbo.CallsBackofficeView' => 'true' ) ),
'text2' => array( 'type' => 'text',
'label' => array( 'text' => 'ΔΙΕΥΘΥΝΣΗ ΑΠΟΣΤΟΛΗΣ ΛΟΓΑΡΙΑΣΜΟΥ',
'type' => 0 ),
'editedByRte' => false,
'color' => '#ffffff' ),
'simple_grid_field2' => array( 'field' => 'applicationStatusId',
'type' => 'grid_field',
'clickSort' => false,
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field66' => array( 'type' => 'grid_field_label',
'field' => 'applicationStatusId',
'clickSort' => false ),
'text3' => array( 'type' => 'text',
'label' => array( 'text' => 'ΣΤΟΙΧΕΙΑ ΠΑΡΟΧΗΣ (ΡΕΥΜΑ)',
'type' => 0 ),
'editedByRte' => false ),
'text6' => array( 'type' => 'text',
'label' => array( 'text' => 'ΣΤΟΙΧΕΙΑ ΥΠΕΥΘΥΝΟΥ ΕΠΙΚΟΙΝΩΝΙΑΣ',
'type' => 0 ),
'editedByRte' => false ),
'text1' => array( 'type' => 'text',
'label' => array( 'text' => 'ΣΤΟΙΧΕΙΑ ΝΟΜΙΜΟΥ ΕΚΠΡΟΣΩΠΟΥ',
'type' => 0 ),
'editedByRte' => false ),
'text' => array( 'type' => 'text',
'label' => array( 'text' => 'ΣΤΟΙΧΕΙΑ ΠΕΛΑΤΗ',
'type' => 0 ),
'editedByRte' => false ),
'details_preview' => array( 'type' => 'details_preview',
'table' => 'dbo.internalComments',
'items' => array(  ),
'popup' => true,
'hideEmptyPreview' => false,
'proceedLink' => false,
'pageId' => 'list' ),
'text4' => array( 'type' => 'text',
'label' => array( 'text' => 'ΤΙΜΟΛΟΓΙΟ VOLTON',
'type' => 0 ),
'editedByRte' => false ),
'text5' => array( 'type' => 'text',
'label' => array( 'text' => 'ΔΙΚΑΙΟΛΟΓΗΤΙΚΑ',
'type' => 0 ),
'editedByRte' => false ),
'image' => array( 'type' => 'image',
'imagePath' => 'volton header.png' ),
'text7' => array( 'type' => 'text',
'label' => array( 'text' => 'ΣΤΟΙΧΕΙΑ ΠΑΡΟΧΗΣ (ΦΥΣΙΚΟ ΑΕΡΙΟ)',
'type' => 0 ),
'editedByRte' => false,
'color' => '#ffffff' ),
'grid_field_label7' => array( 'type' => 'grid_field_label',
'field' => 'applicationPhaseStatusId' ),
'grid_field7' => array( 'field' => 'applicationPhaseStatusId',
'type' => 'grid_field' ),
'grid_field_label6' => array( 'type' => 'grid_field_label',
'field' => 'id' ),
'grid_field6' => array( 'field' => 'id',
'type' => 'grid_field' ),
'print_pdf' => array( 'type' => 'print_pdf',
'targetPages' => array(  ),
'splitModes' => array(  ),
'scopes' => array(  ) ),
'grid_field_label5' => array( 'type' => 'grid_field_label',
'field' => 'forCount' ),
'grid_field5' => array( 'field' => 'forCount',
'type' => 'grid_field' ),
'grid_field_label4' => array( 'type' => 'grid_field_label',
'field' => 'lastStatusDate' ),
'grid_field4' => array( 'field' => 'lastStatusDate',
'type' => 'grid_field' ),
'grid_field_label3' => array( 'type' => 'grid_field_label',
'field' => 'agentApplicationStatus' ),
'grid_field3' => array( 'field' => 'agentApplicationStatus',
'type' => 'grid_field' ),
'grid_field_label2' => array( 'type' => 'grid_field_label',
'field' => 'callDate' ),
'grid_field2' => array( 'field' => 'callDate',
'type' => 'grid_field' ),
'grid_field_label1' => array( 'type' => 'grid_field_label',
'field' => 'agent' ),
'grid_field1' => array( 'field' => 'agent',
'type' => 'grid_field' ),
'grid_field_totals' => array( 'type' => 'grid_field_totals',
'field' => 'applicationStatusId',
'totals' => 'COUNT' ),
'grid_field_label' => array( 'type' => 'grid_field_label',
'field' => 'callphone' ),
'grid_field' => array( 'field' => 'callphone',
'type' => 'grid_field' ),
'grid_field8' => array( 'field' => 'dialerCampaign',
'type' => 'grid_field' ),
'grid_field_label8' => array( 'type' => 'grid_field_label',
'field' => 'dialerCampaign' ),
'grid_field9' => array( 'field' => 'dialerList',
'type' => 'grid_field' ),
'grid_field_label9' => array( 'type' => 'grid_field_label',
'field' => 'dialerList' ),
'grid_field10' => array( 'field' => 'applicationAge',
'type' => 'grid_field' ),
'grid_field_label10' => array( 'type' => 'grid_field_label',
'field' => 'applicationAge' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>