<?php
			$optionsArray = array( 'list' => array( 'inlineAdd' => false,
'detailsAdd' => false,
'inlineEdit' => false,
'delete' => false,
'updateSelected' => false,
'addInPopup' => null,
'editInPopup' => null,
'viewInPopup' => null,
'clickSort' => true,
'sortDropdown' => false,
'showHideFields' => true,
'reorderFields' => true ),
'listSearch' => array( 'alwaysOnPanelFields' => array(  ),
'searchPanel' => false,
'fixedSearchPanel' => false,
'simpleSearchOptions' => false,
'searchSaving' => false ),
'totals' => array( 'id' => array( 'totalsType' => '' ),
'callphone' => array( 'totalsType' => '' ),
'agent' => array( 'totalsType' => 'COUNT' ),
'dialerCampaign' => array( 'totalsType' => '' ),
'dialerList' => array( 'totalsType' => '' ),
'callDate' => array( 'totalsType' => '' ),
'agentApplicationStatus' => array( 'totalsType' => 'COUNT' ),
'applicationStatusId' => array( 'totalsType' => 'COUNT' ),
'applicationPhaseStatusId' => array( 'totalsType' => 'COUNT' ),
'lastStatusDate' => array( 'totalsType' => '' ),
'applicationAge' => array( 'totalsType' => 'COUNT' ),
'forCount' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'applicationStatusId',
'applicationAge',
'lastStatusDate',
'applicationPhaseStatusId',
'agentApplicationStatus',
'callDate',
'dialerList',
'dialerCampaign',
'agent',
'callphone' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'filterFields' => array( 'applicationStatusId',
'applicationAge',
'lastStatusDate',
'applicationPhaseStatusId',
'agentApplicationStatus',
'callDate',
'dialerList',
'dialerCampaign',
'agent' ),
'inlineAddFields' => array(  ),
'inlineEditFields' => array(  ),
'fieldItems' => array( 'applicationStatusId' => array( 'simple_grid_field2',
'simple_grid_field',
'simple_grid_field3' ),
'agentApplicationStatus' => array( 'grid_field_totals1',
'grid_field14',
'grid_field5' ),
'callDate' => array( 'grid_field10',
'grid_field4' ),
'applicationPhaseStatusId' => array( 'grid_field_totals3',
'grid_field6',
'grid_field15' ),
'agent' => array( 'grid_field11',
'grid_field1',
'grid_field_totals' ),
'callphone' => array( 'grid_field9',
'grid_field' ),
'applicationAge' => array( 'grid_field_totals2',
'grid_field8',
'grid_field17' ),
'dialerCampaign' => array( 'grid_field12',
'grid_field2' ),
'dialerList' => array( 'grid_field13',
'grid_field3' ),
'lastStatusDate' => array( 'grid_field7',
'grid_field16' ) ),
'hideEmptyFields' => array(  ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => true ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array( 'logo',
'menu',
'simple_search',
'list_options',
'loginform_login',
'username_button' ),
'left' => array( 'filter_panel' ),
'top' => array( 'master_info' ),
'above-grid' => array( 'details_found',
'page_size',
'print_panel',
'columns_control' ),
'below-grid' => array( 'pagination' ),
'grid' => array( 'grid_field9',
'grid_field',
'grid_field10',
'grid_field4',
'grid_field11',
'grid_field1',
'grid_field_totals',
'grid_field12',
'grid_field2',
'grid_field13',
'grid_field3',
'grid_field14',
'grid_field5',
'grid_field_totals1',
'simple_grid_field',
'simple_grid_field2',
'simple_grid_field3',
'grid_field15',
'grid_field6',
'grid_field_totals3',
'grid_field16',
'grid_field7',
'grid_field17',
'grid_field8',
'grid_field_totals2',
'details_preview',
'grid_checkbox_head',
'grid_checkbox',
'grid_alldetails_link' ) ),
'formXtTags' => array( 'top' => array( 'mastertable_block' ),
'below-grid' => array( 'pagination' ) ),
'itemForms' => array( 'logo' => 'supertop',
'menu' => 'supertop',
'simple_search' => 'supertop',
'list_options' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'filter_panel' => 'left',
'master_info' => 'top',
'details_found' => 'above-grid',
'page_size' => 'above-grid',
'print_panel' => 'above-grid',
'columns_control' => 'above-grid',
'pagination' => 'below-grid',
'grid_field9' => 'grid',
'grid_field' => 'grid',
'grid_field10' => 'grid',
'grid_field4' => 'grid',
'grid_field11' => 'grid',
'grid_field1' => 'grid',
'grid_field_totals' => 'grid',
'grid_field12' => 'grid',
'grid_field2' => 'grid',
'grid_field13' => 'grid',
'grid_field3' => 'grid',
'grid_field14' => 'grid',
'grid_field5' => 'grid',
'grid_field_totals1' => 'grid',
'simple_grid_field' => 'grid',
'simple_grid_field2' => 'grid',
'simple_grid_field3' => 'grid',
'grid_field15' => 'grid',
'grid_field6' => 'grid',
'grid_field_totals3' => 'grid',
'grid_field16' => 'grid',
'grid_field7' => 'grid',
'grid_field17' => 'grid',
'grid_field8' => 'grid',
'grid_field_totals2' => 'grid',
'details_preview' => 'grid',
'grid_checkbox_head' => 'grid',
'grid_checkbox' => 'grid',
'grid_alldetails_link' => 'grid' ),
'itemLocations' => array( 'grid_field9' => array( 'location' => 'grid',
'cellId' => 'headcell_field' ),
'grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'grid_field10' => array( 'location' => 'grid',
'cellId' => 'headcell_field1' ),
'grid_field4' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'grid_field11' => array( 'location' => 'grid',
'cellId' => 'headcell_field2' ),
'grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field2' ),
'grid_field_totals' => array( 'location' => 'grid',
'cellId' => 'footcell_field2' ),
'grid_field12' => array( 'location' => 'grid',
'cellId' => 'headcell_field3' ),
'grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field3' ),
'grid_field13' => array( 'location' => 'grid',
'cellId' => 'headcell_field4' ),
'grid_field3' => array( 'location' => 'grid',
'cellId' => 'cell_field4' ),
'grid_field14' => array( 'location' => 'grid',
'cellId' => 'headcell_field5' ),
'grid_field5' => array( 'location' => 'grid',
'cellId' => 'cell_field5' ),
'grid_field_totals1' => array( 'location' => 'grid',
'cellId' => 'footcell_field5' ),
'simple_grid_field' => array( 'location' => 'grid',
'cellId' => 'headcell_field6' ),
'simple_grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field6' ),
'simple_grid_field3' => array( 'location' => 'grid',
'cellId' => 'footcell_field6' ),
'grid_field15' => array( 'location' => 'grid',
'cellId' => 'headcell_field7' ),
'grid_field6' => array( 'location' => 'grid',
'cellId' => 'cell_field7' ),
'grid_field_totals3' => array( 'location' => 'grid',
'cellId' => 'footcell_field7' ),
'grid_field16' => array( 'location' => 'grid',
'cellId' => 'headcell_field8' ),
'grid_field7' => array( 'location' => 'grid',
'cellId' => 'cell_field8' ),
'grid_field17' => array( 'location' => 'grid',
'cellId' => 'headcell_field9' ),
'grid_field8' => array( 'location' => 'grid',
'cellId' => 'cell_field9' ),
'grid_field_totals2' => array( 'location' => 'grid',
'cellId' => 'footcell_field9' ),
'details_preview' => array( 'location' => 'grid',
'cellId' => 'cell_dpreview' ),
'grid_checkbox_head' => array( 'location' => 'grid',
'cellId' => 'headcell_checkbox' ),
'grid_checkbox' => array( 'location' => 'grid',
'cellId' => 'cell_checkbox' ),
'grid_alldetails_link' => array( 'location' => 'grid',
'cellId' => 'cell_details' ) ),
'itemVisiblity' => array( 'menu' => 3,
'simple_search' => 3,
'list_options' => 3,
'loginform_login' => 3,
'username_button' => 3,
'filter_panel' => 3,
'print_panel' => 5 ) ),
'itemsByType' => array( '-' => array( '-2',
'-',
'-1' ),
'details_found' => array( 'details_found' ),
'page_size' => array( 'page_size' ),
'print_panel' => array( 'print_panel' ),
'print_scope' => array( 'print_scope' ),
'print_records' => array( 'print_records' ),
'print_button' => array( 'print_button' ),
'pagination' => array( 'pagination' ),
'grid_field' => array( 'simple_grid_field2',
'grid_field8',
'grid_field7',
'grid_field6',
'grid_field5',
'grid_field4',
'grid_field3',
'grid_field2',
'grid_field1',
'grid_field' ),
'details_preview' => array( 'details_preview' ),
'grid_checkbox_head' => array( 'grid_checkbox_head' ),
'grid_checkbox' => array( 'grid_checkbox' ),
'grid_alldetails_link' => array( 'grid_alldetails_link' ),
'export_selected' => array( 'export_selected' ),
'export' => array( 'export' ),
'menu' => array( 'menu' ),
'simple_search' => array( 'simple_search' ),
'list_options' => array( 'list_options' ),
'logo' => array( 'logo' ),
'filter_panel' => array( 'filter_panel' ),
'filter_panel_field' => array( 'filter_panel_field',
'filter_panel_field8',
'filter_panel_field7',
'filter_panel_field6',
'filter_panel_field5',
'filter_panel_field4',
'filter_panel_field3',
'filter_panel_field2',
'filter_panel_field1' ),
'grid_field_totals' => array( 'grid_field_totals1',
'grid_field_totals3',
'grid_field_totals2',
'simple_grid_field3',
'grid_field_totals' ),
'grid_field_label' => array( 'grid_field10',
'grid_field11',
'grid_field9',
'grid_field12',
'grid_field13',
'grid_field14',
'simple_grid_field',
'grid_field15',
'grid_field16',
'grid_field17' ),
'username_button' => array( 'username_button' ),
'adminarea_link' => array( 'adminarea_link' ),
'loginform_login' => array( 'loginform_login' ),
'logout_link' => array( 'logout_link' ),
'columns_control' => array( 'columns_control' ),
'master_info' => array( 'master_info' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'headcell_checkbox' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array( 'checkbox_column' ),
'items' => array( 'grid_checkbox_head' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_details' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array( 'callphone_fieldheadercolumn' ),
'items' => array( 'grid_field9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field1' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array( 'callDate_fieldheadercolumn' ),
'items' => array( 'grid_field10' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field2' => array( 'cols' => array( 4 ),
'rows' => array( 0 ),
'tags' => array( 'agent_fieldheadercolumn' ),
'items' => array( 'grid_field11' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field3' => array( 'cols' => array( 5 ),
'rows' => array( 0 ),
'tags' => array( 'dialerCampaign_fieldheadercolumn' ),
'items' => array( 'grid_field12' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field4' => array( 'cols' => array( 6 ),
'rows' => array( 0 ),
'tags' => array( 'dialerList_fieldheadercolumn' ),
'items' => array( 'grid_field13' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field5' => array( 'cols' => array( 7 ),
'rows' => array( 0 ),
'tags' => array( 'agentApplicationStatus_fieldheadercolumn' ),
'items' => array( 'grid_field14' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field6' => array( 'cols' => array( 8 ),
'rows' => array( 0 ),
'tags' => array( 'applicationStatusId_fieldheadercolumn' ),
'items' => array( 'simple_grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field7' => array( 'cols' => array( 9 ),
'rows' => array( 0 ),
'tags' => array( 'applicationPhaseStatusId_fieldheadercolumn' ),
'items' => array( 'grid_field15' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field8' => array( 'cols' => array( 10 ),
'rows' => array( 0 ),
'tags' => array( 'lastStatusDate_fieldheadercolumn' ),
'items' => array( 'grid_field16' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field9' => array( 'cols' => array( 11 ),
'rows' => array( 0 ),
'tags' => array( 'applicationAge_fieldheadercolumn' ),
'items' => array( 'grid_field17' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_checkbox' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'checkbox_column' ),
'items' => array( 'grid_checkbox' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_details' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'grid_alldetails_link' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array( 'callphone_fieldcolumn' ),
'items' => array( 'grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field1' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array( 'callDate_fieldcolumn' ),
'items' => array( 'grid_field4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field2' => array( 'cols' => array( 4 ),
'rows' => array( 1 ),
'tags' => array( 'agent_fieldcolumn' ),
'items' => array( 'grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field3' => array( 'cols' => array( 5 ),
'rows' => array( 1 ),
'tags' => array( 'dialerCampaign_fieldcolumn' ),
'items' => array( 'grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field4' => array( 'cols' => array( 6 ),
'rows' => array( 1 ),
'tags' => array( 'dialerList_fieldcolumn' ),
'items' => array( 'grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field5' => array( 'cols' => array( 7 ),
'rows' => array( 1 ),
'tags' => array( 'agentApplicationStatus_fieldcolumn' ),
'items' => array( 'grid_field5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field6' => array( 'cols' => array( 8 ),
'rows' => array( 1 ),
'tags' => array( 'applicationStatusId_fieldcolumn' ),
'items' => array( 'simple_grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field7' => array( 'cols' => array( 9 ),
'rows' => array( 1 ),
'tags' => array( 'applicationPhaseStatusId_fieldcolumn' ),
'items' => array( 'grid_field6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field8' => array( 'cols' => array( 10 ),
'rows' => array( 1 ),
'tags' => array( 'lastStatusDate_fieldcolumn' ),
'items' => array( 'grid_field7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field9' => array( 'cols' => array( 11 ),
'rows' => array( 1 ),
'tags' => array( 'applicationAge_fieldcolumn' ),
'items' => array( 'grid_field8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_dpreview' => array( 'cols' => array( 0,
1,
2,
3,
4,
5,
6,
7,
8,
9,
10,
11 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'details_preview' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'footcell_checkbox' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_details' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field' => array( 'cols' => array( 2 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field1' => array( 'cols' => array( 3 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field2' => array( 'cols' => array( 4 ),
'rows' => array( 3 ),
'tags' => array( 'agent_fieldfootercolumn' ),
'items' => array( 'grid_field_totals' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field3' => array( 'cols' => array( 5 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field4' => array( 'cols' => array( 6 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field5' => array( 'cols' => array( 7 ),
'rows' => array( 3 ),
'tags' => array( 'agentApplicationStatus_fieldfootercolumn' ),
'items' => array( 'grid_field_totals1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field6' => array( 'cols' => array( 8 ),
'rows' => array( 3 ),
'tags' => array( 'applicationStatusId_fieldfootercolumn' ),
'items' => array( 'simple_grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field7' => array( 'cols' => array( 9 ),
'rows' => array( 3 ),
'tags' => array( 'applicationPhaseStatusId_fieldfootercolumn' ),
'items' => array( 'grid_field_totals3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field8' => array( 'cols' => array( 10 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field9' => array( 'cols' => array( 11 ),
'rows' => array( 3 ),
'tags' => array( 'applicationAge_fieldfootercolumn' ),
'items' => array( 'grid_field_totals2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 12,
'height' => 4 ) ) ),
'loginForm' => array( 'loginForm' => 1 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array( 'details_found' => array( 'tag' => 'DISPLAYING',
'type' => 2 ) ) ),
'gridType' => 0,
'recsPerRow' => 1,
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'list',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dataGrid' => array( 'groupFields' => array(  ) ) );
			$pageArray = array( 'id' => 'list',
'type' => 'list',
'layoutId' => 'topbar',
'disabled' => 0,
'default' => 2,
'forms' => array( 'supertop' => array( 'modelId' => 'topbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'logo',
'menu' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'simple_search',
'list_options',
'loginform_login',
'username_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'list-vbar',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c2' => array( 'model' => 'c2',
'items' => array( 'filter_panel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'list-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c3' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c3' => array( 'model' => 'c3',
'items' => array( 'master_info' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'list-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'details_found',
'page_size',
'print_panel',
'columns_control' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'list-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'pagination' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'horizontal-grid',
'grid' => array( array( 'section' => 'head',
'cells' => array( array( 'cell' => 'headcell_checkbox' ),
array( 'cell' => 'headcell_details' ),
array( 'cell' => 'headcell_field' ),
array( 'cell' => 'headcell_field1' ),
array( 'cell' => 'headcell_field2' ),
array( 'cell' => 'headcell_field3' ),
array( 'cell' => 'headcell_field4' ),
array( 'cell' => 'headcell_field5' ),
array( 'cell' => 'headcell_field6' ),
array( 'cell' => 'headcell_field7' ),
array( 'cell' => 'headcell_field8' ),
array( 'cell' => 'headcell_field9' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_checkbox' ),
array( 'cell' => 'cell_details' ),
array( 'cell' => 'cell_field' ),
array( 'cell' => 'cell_field1' ),
array( 'cell' => 'cell_field2' ),
array( 'cell' => 'cell_field3' ),
array( 'cell' => 'cell_field4' ),
array( 'cell' => 'cell_field5' ),
array( 'cell' => 'cell_field6' ),
array( 'cell' => 'cell_field7' ),
array( 'cell' => 'cell_field8' ),
array( 'cell' => 'cell_field9' ) ) ),
array( 'cells' => array( array( 'cell' => 'cell_dpreview',
'colspan' => 12 ) ),
'section' => 'body' ),
array( 'section' => 'foot',
'cells' => array( array( 'cell' => 'footcell_checkbox' ),
array( 'cell' => 'footcell_details' ),
array( 'cell' => 'footcell_field' ),
array( 'cell' => 'footcell_field1' ),
array( 'cell' => 'footcell_field2' ),
array( 'cell' => 'footcell_field3' ),
array( 'cell' => 'footcell_field4' ),
array( 'cell' => 'footcell_field5' ),
array( 'cell' => 'footcell_field6' ),
array( 'cell' => 'footcell_field7' ),
array( 'cell' => 'footcell_field8' ),
array( 'cell' => 'footcell_field9' ) ) ) ),
'cells' => array( 'headcell_field' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field9' ),
'field' => 'callphone',
'columnName' => 'field' ),
'cell_field' => array( 'model' => 'cell_field',
'items' => array( 'grid_field' ),
'field' => 'callphone',
'columnName' => 'field' ),
'footcell_field' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field1' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field10' ),
'field' => 'callDate',
'columnName' => 'field' ),
'cell_field1' => array( 'model' => 'cell_field',
'items' => array( 'grid_field4' ),
'field' => 'callDate',
'columnName' => 'field' ),
'footcell_field1' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field2' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field11' ),
'field' => 'agent',
'columnName' => 'field' ),
'cell_field2' => array( 'model' => 'cell_field',
'items' => array( 'grid_field1' ),
'field' => 'agent',
'columnName' => 'field' ),
'footcell_field2' => array( 'model' => 'footcell_field',
'items' => array( 'grid_field_totals' ),
'field' => 'agent',
'columnName' => 'field' ),
'headcell_field3' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field12' ),
'field' => 'dialerCampaign',
'columnName' => 'field' ),
'cell_field3' => array( 'model' => 'cell_field',
'items' => array( 'grid_field2' ),
'field' => 'dialerCampaign',
'columnName' => 'field' ),
'footcell_field3' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field4' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field13' ),
'field' => 'dialerList',
'columnName' => 'field' ),
'cell_field4' => array( 'model' => 'cell_field',
'items' => array( 'grid_field3' ),
'field' => 'dialerList',
'columnName' => 'field' ),
'footcell_field4' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field5' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field14' ),
'field' => 'agentApplicationStatus',
'columnName' => 'field' ),
'cell_field5' => array( 'model' => 'cell_field',
'items' => array( 'grid_field5' ),
'field' => 'agentApplicationStatus',
'columnName' => 'field' ),
'footcell_field5' => array( 'model' => 'footcell_field',
'items' => array( 'grid_field_totals1' ),
'field' => 'agentApplicationStatus',
'columnName' => 'field' ),
'headcell_field6' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field' ),
'field' => 'applicationStatusId',
'columnName' => 'field' ),
'cell_field6' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field2' ),
'field' => 'applicationStatusId',
'columnName' => 'field' ),
'footcell_field6' => array( 'model' => 'footcell_field',
'items' => array( 'simple_grid_field3' ),
'field' => 'applicationStatusId',
'columnName' => 'field' ),
'headcell_field7' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field15' ),
'field' => 'applicationPhaseStatusId',
'columnName' => 'field' ),
'cell_field7' => array( 'model' => 'cell_field',
'items' => array( 'grid_field6' ),
'field' => 'applicationPhaseStatusId',
'columnName' => 'field' ),
'footcell_field7' => array( 'model' => 'footcell_field',
'items' => array( 'grid_field_totals3' ),
'field' => 'applicationPhaseStatusId',
'columnName' => 'field' ),
'headcell_field8' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field16' ),
'field' => 'lastStatusDate',
'columnName' => 'field' ),
'cell_field8' => array( 'model' => 'cell_field',
'items' => array( 'grid_field7' ),
'field' => 'lastStatusDate',
'columnName' => 'field' ),
'footcell_field8' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field9' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field17' ),
'field' => 'applicationAge',
'columnName' => 'field' ),
'cell_field9' => array( 'model' => 'cell_field',
'items' => array( 'grid_field8' ),
'field' => 'applicationAge',
'columnName' => 'field' ),
'footcell_field9' => array( 'model' => 'footcell_field',
'items' => array( 'grid_field_totals2' ),
'field' => 'applicationAge',
'columnName' => 'field' ),
'cell_dpreview' => array( 'model' => 'cell_dpreview',
'items' => array( 'details_preview' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'headcell_checkbox' => array( 'model' => 'headcell_checkbox',
'items' => array( 'grid_checkbox_head' ),
'columnName' => 'checkbox' ),
'cell_checkbox' => array( 'model' => 'cell_checkbox',
'items' => array( 'grid_checkbox' ),
'columnName' => 'checkbox' ),
'footcell_checkbox' => array( 'model' => 'footcell_checkbox',
'items' => array(  ),
'columnName' => 'checkbox' ),
'headcell_details' => array( 'model' => 'headcell_details',
'items' => array(  ),
'columnName' => 'details' ),
'cell_details' => array( 'model' => 'cell_details',
'items' => array( 'grid_alldetails_link' ),
'columnName' => 'details' ),
'footcell_details' => array( 'model' => 'footcell_details',
'items' => array(  ),
'columnName' => 'details' ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( '-2' => array( 'type' => '-' ),
'details_found' => array( 'type' => 'details_found' ),
'page_size' => array( 'type' => 'page_size' ),
'print_panel' => array( 'type' => 'print_panel',
'items' => array( 'print_scope',
'print_records',
'print_button' ) ),
'print_scope' => array( 'type' => 'print_scope' ),
'print_records' => array( 'type' => 'print_records' ),
'print_button' => array( 'type' => 'print_button' ),
'pagination' => array( 'type' => 'pagination' ),
'simple_grid_field2' => array( 'field' => 'applicationStatusId',
'type' => 'grid_field',
'clickSort' => true,
'inlineAdd' => false,
'inlineEdit' => false ),
'details_preview' => array( 'type' => 'details_preview',
'table' => 'dbo.internalComments',
'items' => array(  ),
'popup' => false,
'hideEmptyPreview' => false,
'proceedLink' => false,
'pageId' => 'list' ),
'grid_checkbox_head' => array( 'type' => 'grid_checkbox_head' ),
'grid_checkbox' => array( 'type' => 'grid_checkbox' ),
'grid_alldetails_link' => array( 'type' => 'grid_alldetails_link' ),
'export_selected' => array( 'type' => 'export_selected' ),
'export' => array( 'type' => 'export' ),
'-' => array( 'type' => '-' ),
'menu' => array( 'type' => 'menu' ),
'simple_search' => array( 'type' => 'simple_search' ),
'list_options' => array( 'type' => 'list_options',
'items' => array( 'export_selected',
'-1',
'export' ) ),
'logo' => array( 'type' => 'logo' ),
'filter_panel' => array( 'type' => 'filter_panel',
'items' => array( 'filter_panel_field1',
'filter_panel_field2',
'filter_panel_field5',
'filter_panel_field3',
'filter_panel_field',
'filter_panel_field6',
'filter_panel_field4',
'filter_panel_field7',
'filter_panel_field8' ) ),
'filter_panel_field' => array( 'field' => 'applicationStatusId',
'type' => 'filter_panel_field' ),
'grid_field_totals1' => array( 'type' => 'grid_field_totals',
'field' => 'agentApplicationStatus',
'totals' => 'COUNT' ),
'-1' => array( 'type' => '-' ),
'grid_field10' => array( 'type' => 'grid_field_label',
'field' => 'callDate',
'clickSort' => true ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'logout_link',
'adminarea_link' ) ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => true ),
'logout_link' => array( 'type' => 'logout_link' ),
'columns_control' => array( 'type' => 'columns_control',
'showHide' => true,
'reorder' => true ),
'grid_field_totals3' => array( 'type' => 'grid_field_totals',
'field' => 'applicationPhaseStatusId',
'totals' => 'COUNT' ),
'grid_field11' => array( 'type' => 'grid_field_label',
'field' => 'agent',
'clickSort' => true ),
'grid_field9' => array( 'type' => 'grid_field_label',
'field' => 'callphone',
'clickSort' => true ),
'grid_field_totals2' => array( 'type' => 'grid_field_totals',
'field' => 'applicationAge',
'totals' => 'COUNT' ),
'grid_field12' => array( 'type' => 'grid_field_label',
'field' => 'dialerCampaign',
'clickSort' => true ),
'grid_field8' => array( 'field' => 'applicationAge',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'filter_panel_field8' => array( 'field' => 'applicationAge',
'type' => 'filter_panel_field' ),
'grid_field13' => array( 'type' => 'grid_field_label',
'field' => 'dialerList',
'clickSort' => true ),
'grid_field7' => array( 'field' => 'lastStatusDate',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'filter_panel_field7' => array( 'field' => 'lastStatusDate',
'type' => 'filter_panel_field' ),
'grid_field14' => array( 'type' => 'grid_field_label',
'field' => 'agentApplicationStatus',
'clickSort' => true ),
'grid_field6' => array( 'field' => 'applicationPhaseStatusId',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'filter_panel_field6' => array( 'field' => 'applicationPhaseStatusId',
'type' => 'filter_panel_field' ),
'simple_grid_field' => array( 'type' => 'grid_field_label',
'field' => 'applicationStatusId',
'clickSort' => true ),
'grid_field5' => array( 'field' => 'agentApplicationStatus',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'filter_panel_field5' => array( 'field' => 'agentApplicationStatus',
'type' => 'filter_panel_field' ),
'simple_grid_field3' => array( 'type' => 'grid_field_totals',
'field' => 'applicationStatusId',
'totals' => 'COUNT' ),
'grid_field4' => array( 'field' => 'callDate',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'filter_panel_field4' => array( 'field' => 'callDate',
'type' => 'filter_panel_field' ),
'grid_field15' => array( 'type' => 'grid_field_label',
'field' => 'applicationPhaseStatusId',
'clickSort' => true ),
'grid_field3' => array( 'field' => 'dialerList',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'filter_panel_field3' => array( 'field' => 'dialerList',
'type' => 'filter_panel_field' ),
'grid_field16' => array( 'type' => 'grid_field_label',
'field' => 'lastStatusDate',
'clickSort' => true ),
'grid_field2' => array( 'field' => 'dialerCampaign',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'filter_panel_field2' => array( 'field' => 'dialerCampaign',
'type' => 'filter_panel_field' ),
'grid_field17' => array( 'type' => 'grid_field_label',
'field' => 'applicationAge',
'clickSort' => true ),
'grid_field1' => array( 'field' => 'agent',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'filter_panel_field1' => array( 'field' => 'agent',
'type' => 'filter_panel_field' ),
'grid_field_totals' => array( 'type' => 'grid_field_totals',
'field' => 'agent',
'totals' => 'COUNT' ),
'grid_field' => array( 'field' => 'callphone',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'master_info' => array( 'type' => 'master_info',
'tables' => array( 'dbo.CallsBackofficeView' => 'true' ) ) ),
'dbProps' => array(  ),
'responsiveGrid' => false,
'version' => 4 );
		?>