<?php
			$optionsArray = array( 'details' => array( 'dbo.orderItems' => array( 'displayPreview' => 2,
'previewPageId' => '' ) ),
'captcha' => array( 'captcha' => false ),
'fields' => array( 'gridFields' => array( 'code',
'description',
'retailPrice',
'costPrice',
'details',
'photo',
'familyId',
'itemCustomerId',
'salesCategoryId',
'isPackage',
'itemWeight',
'itemVolume',
'itemCourierCost',
'thumbnail',
'salesComission',
'itemDiscount',
'itemShippingCost',
'defaultSalesQty',
'itemIsActive' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'code' => array( 'integrated_edit_field',
'edit_field_label' ),
'description' => array( 'integrated_edit_field1',
'edit_field_label1' ),
'retailPrice' => array( 'integrated_edit_field2' ),
'costPrice' => array( 'integrated_edit_field3' ),
'details' => array( 'integrated_edit_field4',
'edit_field_tooltip' ),
'photo' => array( 'integrated_edit_field5' ),
'familyId' => array( 'integrated_edit_field6' ),
'itemCustomerId' => array( 'integrated_edit_field7' ),
'salesCategoryId' => array( 'integrated_edit_field8' ),
'isPackage' => array( 'integrated_edit_field9' ),
'itemWeight' => array( 'integrated_edit_field10' ),
'itemVolume' => array( 'integrated_edit_field11' ),
'itemCourierCost' => array( 'integrated_edit_field12' ),
'thumbnail' => array( 'integrated_edit_field13' ),
'salesComission' => array( 'integrated_edit_field14' ),
'itemDiscount' => array( 'integrated_edit_field16' ),
'itemShippingCost' => array( 'integrated_edit_field17' ),
'defaultSalesQty' => array( 'integrated_edit_field18' ),
'itemIsActive' => array( 'integrated_edit_field15' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array( 'collapse_button',
'loginform_login',
'username_button' ),
'left' => array( 'logo1',
'expand_button',
'menu' ),
'top' => array( 'add_header' ),
'above-grid' => array( 'integrated_edit_field13',
'add_message' ),
'below-grid' => array( 'add_save',
'add_back_list',
'add_cancel' ),
'grid' => array( 'integrated_edit_field',
'integrated_edit_field9',
'integrated_edit_field2',
'integrated_edit_field16',
'integrated_edit_field18',
'integrated_edit_field17',
'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field3',
'integrated_edit_field6',
'integrated_edit_field8',
'integrated_edit_field12',
'integrated_edit_field7',
'integrated_edit_field14',
'integrated_edit_field4',
'edit_field_tooltip',
'integrated_edit_field5',
'integrated_edit_field1',
'edit_field_label',
'edit_field_label1',
'integrated_edit_field15' ) ),
'formXtTags' => array( 'above-grid' => array( 'thumbnail_fieldblock',
'message_block' ) ),
'itemForms' => array( 'collapse_button' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'logo1' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'add_header' => 'top',
'integrated_edit_field13' => 'above-grid',
'add_message' => 'above-grid',
'add_save' => 'below-grid',
'add_back_list' => 'below-grid',
'add_cancel' => 'below-grid',
'integrated_edit_field' => 'grid',
'integrated_edit_field9' => 'grid',
'integrated_edit_field2' => 'grid',
'integrated_edit_field16' => 'grid',
'integrated_edit_field18' => 'grid',
'integrated_edit_field17' => 'grid',
'integrated_edit_field10' => 'grid',
'integrated_edit_field11' => 'grid',
'integrated_edit_field3' => 'grid',
'integrated_edit_field6' => 'grid',
'integrated_edit_field8' => 'grid',
'integrated_edit_field12' => 'grid',
'integrated_edit_field7' => 'grid',
'integrated_edit_field14' => 'grid',
'integrated_edit_field4' => 'grid',
'edit_field_tooltip' => 'grid',
'integrated_edit_field5' => 'grid',
'integrated_edit_field1' => 'grid',
'edit_field_label' => 'grid',
'edit_field_label1' => 'grid',
'integrated_edit_field15' => 'grid' ),
'itemLocations' => array( 'integrated_edit_field' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field9' => array( 'location' => 'grid',
'cellId' => 'c' ),
'integrated_edit_field2' => array( 'location' => 'grid',
'cellId' => 'c5' ),
'integrated_edit_field16' => array( 'location' => 'grid',
'cellId' => 'c5' ),
'integrated_edit_field18' => array( 'location' => 'grid',
'cellId' => 'c6' ),
'integrated_edit_field17' => array( 'location' => 'grid',
'cellId' => 'c6' ),
'integrated_edit_field10' => array( 'location' => 'grid',
'cellId' => 'c7' ),
'integrated_edit_field11' => array( 'location' => 'grid',
'cellId' => 'c7' ),
'integrated_edit_field3' => array( 'location' => 'grid',
'cellId' => 'c11' ),
'integrated_edit_field6' => array( 'location' => 'grid',
'cellId' => 'c12' ),
'integrated_edit_field8' => array( 'location' => 'grid',
'cellId' => 'c13' ),
'integrated_edit_field12' => array( 'location' => 'grid',
'cellId' => 'c14' ),
'integrated_edit_field7' => array( 'location' => 'grid',
'cellId' => 'c15' ),
'integrated_edit_field14' => array( 'location' => 'grid',
'cellId' => 'c16' ),
'integrated_edit_field4' => array( 'location' => 'grid',
'cellId' => 'c17' ),
'edit_field_tooltip' => array( 'location' => 'grid',
'cellId' => 'c17' ),
'integrated_edit_field5' => array( 'location' => 'grid',
'cellId' => 'c18' ),
'integrated_edit_field1' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'edit_field_label' => array( 'location' => 'grid',
'cellId' => 'c4' ),
'edit_field_label1' => array( 'location' => 'grid',
'cellId' => 'c19' ),
'integrated_edit_field15' => array( 'location' => 'grid',
'cellId' => 'c2' ) ),
'itemVisiblity' => array( 'collapse_button' => 5,
'loginform_login' => 3,
'username_button' => 3,
'expand_button' => 5,
'menu' => 3 ) ),
'itemsByType' => array( 'add_header' => array( 'add_header' ),
'add_back_list' => array( 'add_back_list' ),
'add_cancel' => array( 'add_cancel' ),
'add_message' => array( 'add_message' ),
'add_save' => array( 'add_save' ),
'menu' => array( 'menu' ),
'collapse_button' => array( 'collapse_button' ),
'edit_field' => array( 'integrated_edit_field',
'integrated_edit_field1',
'integrated_edit_field4' ),
'integrated_edit_field' => array( 'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field8',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field12',
'integrated_edit_field13',
'integrated_edit_field14',
'integrated_edit_field16',
'integrated_edit_field17',
'integrated_edit_field18',
'integrated_edit_field15' ),
'logo' => array( 'logo1' ),
'edit_field_tooltip' => array( 'edit_field_tooltip' ),
'username_button' => array( 'username_button' ),
'adminarea_link' => array( 'adminarea_link' ),
'loginform_login' => array( 'loginform_login' ),
'logout_link' => array( 'logout_link' ),
'edit_field_label' => array( 'edit_field_label',
'edit_field_label1' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c4' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array( 'code_fieldblock' ),
'items' => array( 'edit_field_label' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field9' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field15' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c19' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'description_fieldblock' ),
'items' => array( 'edit_field_label1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c1' => array( 'cols' => array( 1,
2,
3 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c20' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field2',
'integrated_edit_field16' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field18',
'integrated_edit_field17' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 3 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field10',
'integrated_edit_field11' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c22' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c11' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c12' => array( 'cols' => array( 2 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field6' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c13' => array( 'cols' => array( 3 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field8' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c23' => array( 'cols' => array( 0 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c14' => array( 'cols' => array( 1 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field12' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c15' => array( 'cols' => array( 2 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field7' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c16' => array( 'cols' => array( 3 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field14' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c24' => array( 'cols' => array( 0 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c17' => array( 'cols' => array( 1,
2,
3 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field4',
'edit_field_tooltip' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c25' => array( 'cols' => array( 0 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c18' => array( 'cols' => array( 1,
2,
3 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field5' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 4,
'height' => 7 ) ) ),
'loginForm' => array( 'loginForm' => 1 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'add',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'add',
'type' => 'add',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'leftbar-top-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'collapse_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'loginform_login',
'username_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo1',
'expand_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'add-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'add-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field13',
'add_message' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'add-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add_save',
'add_back_list',
'add_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c4' ),
array( 'cell' => 'c3' ),
array( 'cell' => 'c' ),
array( 'cell' => 'c2' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c19' ),
array( 'cell' => 'c1',
'colspan' => 3 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c20' ),
array( 'cell' => 'c5' ),
array( 'cell' => 'c6' ),
array( 'cell' => 'c7' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c22' ),
array( 'cell' => 'c11' ),
array( 'cell' => 'c12' ),
array( 'cell' => 'c13' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c23' ),
array( 'cell' => 'c14' ),
array( 'cell' => 'c15' ),
array( 'cell' => 'c16' ) ) ),
array( 'cells' => array( array( 'cell' => 'c24' ),
array( 'cell' => 'c17',
'colspan' => 3 ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c25' ),
array( 'cell' => 'c18',
'colspan' => 3 ) ) ) ),
'cells' => array( 'c3' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field9' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'align' => 'left' ),
'c5' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field2',
'integrated_edit_field16' ) ),
'c6' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field18',
'integrated_edit_field17' ) ),
'c7' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field10',
'integrated_edit_field11' ) ),
'c11' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field3' ) ),
'c12' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field6' ) ),
'c13' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field8' ) ),
'c14' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field12' ) ),
'c15' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field7' ) ),
'c16' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field14' ) ),
'c17' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field4',
'edit_field_tooltip' ) ),
'c18' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field5' ) ),
'c1' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field1' ),
'align' => 'left' ),
'c4' => array( 'model' => 'c2',
'items' => array( 'edit_field_label' ),
'width' => '50px',
'align' => 'right' ),
'c19' => array( 'model' => 'c3',
'items' => array( 'edit_field_label1' ),
'align' => 'right' ),
'c20' => array( 'model' => 'c3',
'items' => array(  ) ),
'c22' => array( 'model' => 'c3',
'items' => array(  ) ),
'c23' => array( 'model' => 'c3',
'items' => array(  ) ),
'c24' => array( 'model' => 'c3',
'items' => array(  ) ),
'c25' => array( 'model' => 'c3',
'items' => array(  ) ),
'c2' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field15' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'align' => 'left' ) ),
'deferredItems' => array(  ),
'columnCount' => 3,
'inlineLabels' => true,
'separateLabels' => false ) ),
'items' => array( 'add_header' => array( 'type' => 'add_header' ),
'add_back_list' => array( 'type' => 'add_back_list' ),
'add_cancel' => array( 'type' => 'add_cancel' ),
'add_message' => array( 'type' => 'add_message' ),
'add_save' => array( 'type' => 'add_save' ),
'menu' => array( 'type' => 'menu' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'integrated_edit_field' => array( 'field' => 'code',
'type' => 'edit_field',
'orientation' => 1,
'joined' => false,
'separated' => true ),
'integrated_edit_field1' => array( 'field' => 'description',
'type' => 'edit_field',
'orientation' => 1,
'joined' => false,
'separated' => true ),
'integrated_edit_field2' => array( 'field' => 'retailPrice',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field3' => array( 'field' => 'costPrice',
'type' => 'integrated_edit_field',
'orientation' => 1,
'label' => array( 'field' => 'costPrice',
'table' => 'dbo.Items',
'type' => 3 ) ),
'integrated_edit_field4' => array( 'field' => 'details',
'type' => 'edit_field',
'orientation' => 1,
'joined' => false,
'separated' => true ),
'integrated_edit_field5' => array( 'field' => 'photo',
'type' => 'integrated_edit_field',
'orientation' => 1,
'label' => array( 'field' => 'photo',
'table' => 'dbo.Items',
'type' => 3 ) ),
'integrated_edit_field6' => array( 'field' => 'familyId',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field7' => array( 'field' => 'itemCustomerId',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field8' => array( 'field' => 'salesCategoryId',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field9' => array( 'field' => 'isPackage',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'logo1' => array( 'type' => 'logo' ),
'integrated_edit_field10' => array( 'field' => 'itemWeight',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field11' => array( 'field' => 'itemVolume',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field12' => array( 'field' => 'itemCourierCost',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field13' => array( 'field' => 'thumbnail',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field14' => array( 'field' => 'salesComission',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'edit_field_tooltip' => array( 'type' => 'edit_field_tooltip',
'field' => 'details',
'separated' => true,
'tooltip' => array( 'field' => 'details',
'table' => 'dbo.Items',
'type' => 4 ) ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'logout_link',
'adminarea_link' ) ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => true ),
'logout_link' => array( 'type' => 'logout_link' ),
'integrated_edit_field16' => array( 'field' => 'itemDiscount',
'type' => 'integrated_edit_field',
'orientation' => 1,
'label' => array( 'field' => 'itemDiscount',
'table' => 'dbo.Items',
'type' => 3 ) ),
'integrated_edit_field17' => array( 'field' => 'itemShippingCost',
'type' => 'integrated_edit_field',
'orientation' => 1,
'label' => array( 'field' => 'itemShippingCost',
'table' => 'dbo.Items',
'type' => 3 ) ),
'edit_field_label' => array( 'type' => 'edit_field_label',
'field' => 'code',
'separated' => true ),
'edit_field_label1' => array( 'type' => 'edit_field_label',
'field' => 'description',
'separated' => true ),
'integrated_edit_field18' => array( 'field' => 'defaultSalesQty',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field15' => array( 'field' => 'itemIsActive',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'expand_button' => array( 'type' => 'expand_button' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>