<?php
			$optionsArray = array( 'list' => array( 'inlineAdd' => true,
'detailsAdd' => true,
'inlineEdit' => true,
'delete' => true,
'updateSelected' => true,
'addInPopup' => false,
'editInPopup' => false,
'viewInPopup' => false,
'clickSort' => true,
'sortDropdown' => false,
'showHideFields' => false,
'reorderFields' => false ),
'allDetails' => array( 'linkType' => 0 ),
'details' => array( 'dbo.internalComments' => array( 'displayPreview' => 1,
'previewPageId' => 'list',
'showCount' => true,
'hideEmptyChild' => true,
'hideEmptyPreview' => false,
'showProceedLink' => true,
'printDetails' => true ) ),
'listSearch' => array( 'alwaysOnPanelFields' => array(  ),
'searchPanel' => true,
'fixedSearchPanel' => false,
'simpleSearchOptions' => false,
'searchSaving' => false ),
'totals' => array( 'id' => array( 'totalsType' => '' ),
'callid' => array( 'totalsType' => '' ),
'callDate' => array( 'totalsType' => '' ),
'callPhone' => array( 'totalsType' => '' ),
'applicationStatusId' => array( 'totalsType' => '' ),
'applicationPhase' => array( 'totalsType' => '' ),
'salesPhase' => array( 'totalsType' => '' ),
'applicationType' => array( 'totalsType' => '' ),
'applicantName' => array( 'totalsType' => '' ),
'applicantFirstName' => array( 'totalsType' => '' ),
'applicantBirthdate' => array( 'totalsType' => '' ),
'applicantProfession' => array( 'totalsType' => '' ),
'applicantIdNumber' => array( 'totalsType' => '' ),
'applicantAddress' => array( 'totalsType' => '' ),
'applicantPostalCode' => array( 'totalsType' => '' ),
'applicantArea' => array( 'totalsType' => '' ),
'applicantCity' => array( 'totalsType' => '' ),
'applicantTaxRegistrationNumber' => array( 'totalsType' => '' ),
'applicantTaxOffice' => array( 'totalsType' => '' ),
'applicantPhone' => array( 'totalsType' => '' ),
'applicantMobile' => array( 'totalsType' => '' ),
'applicantEmail' => array( 'totalsType' => '' ),
'standAloneProgram' => array( 'totalsType' => '' ),
'doublePlayProgram' => array( 'totalsType' => '' ),
'ProgramSpeed' => array( 'totalsType' => '' ),
'triplePlayProgram' => array( 'totalsType' => '' ),
'triplePlayProgramType' => array( 'totalsType' => '' ),
'additionalServiceInternet' => array( 'totalsType' => '' ),
'additionalServiceInternetSpeed' => array( 'totalsType' => '' ),
'additionalServiceInternationalCalls' => array( 'totalsType' => '' ),
'additionalServiceStaticIp' => array( 'totalsType' => '' ),
'additionalServiceStaticBlock8Ip' => array( 'totalsType' => '' ),
'additionalServiceSecondLine' => array( 'totalsType' => '' ),
'additionalServiceLandLine1000Minutes' => array( 'totalsType' => '' ),
'additionalServiceEquipment' => array( 'totalsType' => '' ),
'additionalServiceEquipmentInstallation' => array( 'totalsType' => '' ),
'adittionalServiceMobileNoLimit' => array( 'totalsType' => '' ),
'additionalServiceEONMultiScreen' => array( 'totalsType' => '' ),
'additionalServiceNovaMultiroom' => array( 'totalsType' => '' ),
'additionalServiceAdultPack' => array( 'totalsType' => '' ),
'portabilityIsNewLine' => array( 'totalsType' => '' ),
'portabilityOldNumber' => array( 'totalsType' => '' ),
'portabilityOldOwner' => array( 'totalsType' => '' ),
'portabilityActivationAddress' => array( 'totalsType' => '' ),
'portabilityActivationPostalCode' => array( 'totalsType' => '' ),
'portabilityActivationArea' => array( 'totalsType' => '' ),
'portabilityActivationCity' => array( 'totalsType' => '' ),
'portabilityPstnIsdn' => array( 'totalsType' => '' ),
'portabilityLine1PhoneNumber' => array( 'totalsType' => '' ),
'portabilityLine2PhoneNumber' => array( 'totalsType' => '' ),
'portabilityLine3PhoneNumber' => array( 'totalsType' => '' ),
'portabilityLine4PhoneNumber' => array( 'totalsType' => '' ),
'portabilityUsername1' => array( 'totalsType' => '' ),
'portabilityusername2' => array( 'totalsType' => '' ),
'documentIdPassport' => array( 'totalsType' => '' ),
'documentIdPassportPreviousOwner' => array( 'totalsType' => '' ),
'documentLastBill' => array( 'totalsType' => '' ),
'documentAddressValidation' => array( 'totalsType' => '' ),
'documentDeathCertificate' => array( 'totalsType' => '' ),
'documentAuthorization' => array( 'totalsType' => '' ),
'documentOther' => array( 'totalsType' => '' ),
'documentOtherType' => array( 'totalsType' => '' ),
'applicationAgentStatus' => array( 'totalsType' => '' ),
'applicationLastStatusDate' => array( 'totalsType' => '' ),
'applicationContactMethod' => array( 'totalsType' => '' ),
'applicationCourier' => array( 'totalsType' => '' ),
'applicationCourierDate' => array( 'totalsType' => '' ),
'applicationCourierTimeFrom' => array( 'totalsType' => '' ),
'applicationCourierTimeTo' => array( 'totalsType' => '' ),
'applicationCourierComments' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'applicationAgentStatus',
'salesPhase',
'applicationStatusId',
'applicationPhase',
'applicantName',
'applicantFirstName',
'applicantIdNumber',
'applicantAddress',
'applicantTaxRegistrationNumber',
'applicantPhone',
'applicantMobile',
'applicationContactMethod',
'applicationCourier',
'applicationCourierDate',
'id',
'callDate',
'callPhone',
'applicationLastStatusDate' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array( 'callDate',
'applicationLastStatusDate',
'callPhone' ),
'filterFields' => array(  ),
'inlineAddFields' => array( 'applicationAgentStatus',
'applicationStatusId',
'applicantName',
'applicantFirstName',
'applicantIdNumber',
'applicantAddress',
'applicantTaxRegistrationNumber',
'applicantPhone',
'applicantMobile',
'applicationContactMethod',
'applicationCourier',
'applicationCourierDate',
'applicationLastStatusDate' ),
'inlineEditFields' => array( 'applicationAgentStatus',
'applicationStatusId',
'applicantName',
'applicantFirstName',
'applicantIdNumber',
'applicantAddress',
'applicantTaxRegistrationNumber',
'applicantPhone',
'applicantMobile',
'applicationContactMethod',
'applicationCourier',
'applicationCourierDate',
'applicationLastStatusDate' ),
'fieldItems' => array( 'applicationAgentStatus' => array( 'grid_field1',
'grid_field' ),
'salesPhase' => array( 'grid_field20',
'grid_field21' ),
'applicationStatusId' => array( 'grid_field18',
'grid_field22' ),
'applicationPhase' => array( 'grid_field19',
'grid_field23' ),
'applicantName' => array( 'simple_grid_field4',
'simple_grid_field6' ),
'applicantFirstName' => array( 'simple_grid_field5',
'simple_grid_field7' ),
'applicantIdNumber' => array( 'simple_grid_field8',
'simple_grid_field10' ),
'applicantAddress' => array( 'simple_grid_field9',
'simple_grid_field11' ),
'applicantTaxRegistrationNumber' => array( 'simple_grid_field13',
'simple_grid_field14' ),
'applicantPhone' => array( 'simple_grid_field15',
'simple_grid_field17' ),
'applicantMobile' => array( 'simple_grid_field16',
'simple_grid_field18' ),
'applicationContactMethod' => array( 'grid_field5',
'grid_field8' ),
'applicationCourier' => array( 'grid_field6',
'grid_field9' ),
'applicationCourierDate' => array( 'grid_field7',
'grid_field10' ),
'id' => array( 'simple_grid_field',
'simple_grid_field12' ),
'callDate' => array( 'simple_grid_field1',
'simple_grid_field19' ),
'callPhone' => array( 'simple_grid_field2',
'simple_grid_field20' ),
'applicationLastStatusDate' => array( 'simple_grid_field3',
'simple_grid_field21' ) ),
'hideEmptyFields' => array(  ) ),
'pageLinks' => array( 'edit' => true,
'add' => true,
'view' => true,
'print' => true ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array( 'logo',
'menu',
'simple_search',
'list_options',
'loginform_login',
'username_button' ),
'left' => array( 'filter_panel',
'search_panel' ),
'top' => array( 'breadcrumb' ),
'above-grid' => array( 'add',
'inline_add',
'inline_save_all',
'inline_cancel_all',
'delete',
'update_selected',
'details_found',
'page_size',
'print_panel' ),
'below-grid' => array( 'pagination' ),
'grid' => array( 'grid_field',
'grid_field1',
'grid_field21',
'grid_field20',
'grid_field22',
'grid_field18',
'grid_field23',
'grid_field19',
'simple_grid_field6',
'simple_grid_field4',
'simple_grid_field7',
'simple_grid_field5',
'simple_grid_field10',
'simple_grid_field8',
'simple_grid_field11',
'simple_grid_field9',
'simple_grid_field14',
'simple_grid_field13',
'simple_grid_field17',
'simple_grid_field15',
'simple_grid_field18',
'simple_grid_field16',
'grid_field8',
'grid_field5',
'grid_field9',
'grid_field6',
'grid_field10',
'grid_field7',
'simple_grid_field12',
'simple_grid_field',
'simple_grid_field19',
'simple_grid_field1',
'simple_grid_field20',
'simple_grid_field2',
'simple_grid_field21',
'simple_grid_field3',
'details_preview',
'grid_checkbox_head',
'grid_checkbox',
'grid_edit',
'grid_inline_edit',
'grid_inline_save',
'grid_inline_cancel',
'grid_copy',
'grid_view',
'grid_alldetails_link',
'grid_details_link' ) ),
'formXtTags' => array( 'top' => array( 'breadcrumb' ),
'above-grid' => array( 'add_link',
'inlineadd_link',
'saveall_link',
'cancelall_link',
'deleteselected_link',
'updateselected_link',
'details_found',
'recsPerPage',
'print_friendly' ),
'below-grid' => array( 'pagination' ) ),
'itemForms' => array( 'logo' => 'supertop',
'menu' => 'supertop',
'simple_search' => 'supertop',
'list_options' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'filter_panel' => 'left',
'search_panel' => 'left',
'breadcrumb' => 'top',
'add' => 'above-grid',
'inline_add' => 'above-grid',
'inline_save_all' => 'above-grid',
'inline_cancel_all' => 'above-grid',
'delete' => 'above-grid',
'update_selected' => 'above-grid',
'details_found' => 'above-grid',
'page_size' => 'above-grid',
'print_panel' => 'above-grid',
'pagination' => 'below-grid',
'grid_field' => 'grid',
'grid_field1' => 'grid',
'grid_field21' => 'grid',
'grid_field20' => 'grid',
'grid_field22' => 'grid',
'grid_field18' => 'grid',
'grid_field23' => 'grid',
'grid_field19' => 'grid',
'simple_grid_field6' => 'grid',
'simple_grid_field4' => 'grid',
'simple_grid_field7' => 'grid',
'simple_grid_field5' => 'grid',
'simple_grid_field10' => 'grid',
'simple_grid_field8' => 'grid',
'simple_grid_field11' => 'grid',
'simple_grid_field9' => 'grid',
'simple_grid_field14' => 'grid',
'simple_grid_field13' => 'grid',
'simple_grid_field17' => 'grid',
'simple_grid_field15' => 'grid',
'simple_grid_field18' => 'grid',
'simple_grid_field16' => 'grid',
'grid_field8' => 'grid',
'grid_field5' => 'grid',
'grid_field9' => 'grid',
'grid_field6' => 'grid',
'grid_field10' => 'grid',
'grid_field7' => 'grid',
'simple_grid_field12' => 'grid',
'simple_grid_field' => 'grid',
'simple_grid_field19' => 'grid',
'simple_grid_field1' => 'grid',
'simple_grid_field20' => 'grid',
'simple_grid_field2' => 'grid',
'simple_grid_field21' => 'grid',
'simple_grid_field3' => 'grid',
'details_preview' => 'grid',
'grid_checkbox_head' => 'grid',
'grid_checkbox' => 'grid',
'grid_edit' => 'grid',
'grid_inline_edit' => 'grid',
'grid_inline_save' => 'grid',
'grid_inline_cancel' => 'grid',
'grid_copy' => 'grid',
'grid_view' => 'grid',
'grid_alldetails_link' => 'grid',
'grid_details_link' => 'grid' ),
'itemLocations' => array( 'grid_field' => array( 'location' => 'grid',
'cellId' => 'headcell_field' ),
'grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'grid_field21' => array( 'location' => 'grid',
'cellId' => 'headcell_field1' ),
'grid_field20' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'grid_field22' => array( 'location' => 'grid',
'cellId' => 'headcell_field2' ),
'grid_field18' => array( 'location' => 'grid',
'cellId' => 'cell_field2' ),
'grid_field23' => array( 'location' => 'grid',
'cellId' => 'headcell_field3' ),
'grid_field19' => array( 'location' => 'grid',
'cellId' => 'cell_field3' ),
'simple_grid_field6' => array( 'location' => 'grid',
'cellId' => 'headcell_field4' ),
'simple_grid_field4' => array( 'location' => 'grid',
'cellId' => 'cell_field4' ),
'simple_grid_field7' => array( 'location' => 'grid',
'cellId' => 'headcell_field5' ),
'simple_grid_field5' => array( 'location' => 'grid',
'cellId' => 'cell_field5' ),
'simple_grid_field10' => array( 'location' => 'grid',
'cellId' => 'headcell_field6' ),
'simple_grid_field8' => array( 'location' => 'grid',
'cellId' => 'cell_field6' ),
'simple_grid_field11' => array( 'location' => 'grid',
'cellId' => 'headcell_field7' ),
'simple_grid_field9' => array( 'location' => 'grid',
'cellId' => 'cell_field7' ),
'simple_grid_field14' => array( 'location' => 'grid',
'cellId' => 'headcell_field8' ),
'simple_grid_field13' => array( 'location' => 'grid',
'cellId' => 'cell_field8' ),
'simple_grid_field17' => array( 'location' => 'grid',
'cellId' => 'headcell_field9' ),
'simple_grid_field15' => array( 'location' => 'grid',
'cellId' => 'cell_field9' ),
'simple_grid_field18' => array( 'location' => 'grid',
'cellId' => 'headcell_field10' ),
'simple_grid_field16' => array( 'location' => 'grid',
'cellId' => 'cell_field10' ),
'grid_field8' => array( 'location' => 'grid',
'cellId' => 'headcell_field11' ),
'grid_field5' => array( 'location' => 'grid',
'cellId' => 'cell_field11' ),
'grid_field9' => array( 'location' => 'grid',
'cellId' => 'headcell_field12' ),
'grid_field6' => array( 'location' => 'grid',
'cellId' => 'cell_field12' ),
'grid_field10' => array( 'location' => 'grid',
'cellId' => 'headcell_field13' ),
'grid_field7' => array( 'location' => 'grid',
'cellId' => 'cell_field13' ),
'simple_grid_field12' => array( 'location' => 'grid',
'cellId' => 'headcell_field14' ),
'simple_grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field14' ),
'simple_grid_field19' => array( 'location' => 'grid',
'cellId' => 'headcell_field15' ),
'simple_grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field15' ),
'simple_grid_field20' => array( 'location' => 'grid',
'cellId' => 'headcell_field16' ),
'simple_grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field16' ),
'simple_grid_field21' => array( 'location' => 'grid',
'cellId' => 'headcell_field17' ),
'simple_grid_field3' => array( 'location' => 'grid',
'cellId' => 'cell_field17' ),
'details_preview' => array( 'location' => 'grid',
'cellId' => 'cell_dpreview' ),
'grid_checkbox_head' => array( 'location' => 'grid',
'cellId' => 'headcell_checkbox' ),
'grid_checkbox' => array( 'location' => 'grid',
'cellId' => 'cell_checkbox' ),
'grid_edit' => array( 'location' => 'grid',
'cellId' => 'cell_icons' ),
'grid_inline_edit' => array( 'location' => 'grid',
'cellId' => 'cell_icons' ),
'grid_inline_save' => array( 'location' => 'grid',
'cellId' => 'cell_icons' ),
'grid_inline_cancel' => array( 'location' => 'grid',
'cellId' => 'cell_icons' ),
'grid_copy' => array( 'location' => 'grid',
'cellId' => 'cell_icons' ),
'grid_view' => array( 'location' => 'grid',
'cellId' => 'cell_icons' ),
'grid_alldetails_link' => array( 'location' => 'grid',
'cellId' => 'cell_details' ),
'grid_details_link' => array( 'location' => 'grid',
'cellId' => 'cell_details' ) ),
'itemVisiblity' => array( 'menu' => 3,
'simple_search' => 3,
'list_options' => 3,
'loginform_login' => 3,
'username_button' => 3,
'filter_panel' => 3,
'search_panel' => 5,
'print_panel' => 5 ) ),
'itemsByType' => array( 'add' => array( 'add' ),
'inline_save_all' => array( 'inline_save_all' ),
'inline_cancel_all' => array( 'inline_cancel_all' ),
'delete' => array( 'delete' ),
'update_selected' => array( 'update_selected' ),
'details_found' => array( 'details_found' ),
'page_size' => array( 'page_size' ),
'print_panel' => array( 'print_panel' ),
'print_scope' => array( 'print_scope' ),
'print_records' => array( 'print_records' ),
'print_button' => array( 'print_button' ),
'pagination' => array( 'pagination' ),
'-' => array( '-5',
'-',
'-1',
'-2',
'-3',
'-4' ),
'advsearch_link' => array( 'advsearch_link' ),
'breadcrumb' => array( 'breadcrumb' ),
'edit_selected' => array( 'edit_selected' ),
'delete_selected' => array( 'delete_selected' ),
'menu' => array( 'menu' ),
'simple_search' => array( 'simple_search' ),
'list_options' => array( 'list_options' ),
'logo' => array( 'logo' ),
'filter_panel' => array( 'filter_panel' ),
'username_button' => array( 'username_button' ),
'adminarea_link' => array( 'adminarea_link' ),
'loginform_login' => array( 'loginform_login' ),
'logout_link' => array( 'logout_link' ),
'inline_add' => array( 'inline_add' ),
'export' => array( 'export' ),
'export_selected' => array( 'export_selected' ),
'print_details' => array( 'print_details' ),
'search_panel' => array( 'search_panel' ),
'search_panel_field' => array( 'search_panel_field',
'search_panel_field1',
'search_panel_field2' ),
'grid_field' => array( 'grid_field1',
'grid_field20',
'grid_field18',
'grid_field19',
'simple_grid_field4',
'simple_grid_field5',
'simple_grid_field8',
'simple_grid_field9',
'simple_grid_field13',
'simple_grid_field15',
'simple_grid_field16',
'grid_field5',
'grid_field6',
'grid_field7',
'simple_grid_field',
'simple_grid_field1',
'simple_grid_field2',
'simple_grid_field3' ),
'grid_field_label' => array( 'grid_field',
'grid_field21',
'grid_field22',
'grid_field23',
'simple_grid_field6',
'simple_grid_field7',
'simple_grid_field10',
'simple_grid_field11',
'simple_grid_field14',
'simple_grid_field17',
'simple_grid_field18',
'grid_field8',
'grid_field9',
'grid_field10',
'simple_grid_field12',
'simple_grid_field19',
'simple_grid_field20',
'simple_grid_field21' ),
'details_preview' => array( 'details_preview' ),
'grid_checkbox_head' => array( 'grid_checkbox_head' ),
'grid_edit' => array( 'grid_edit' ),
'grid_inline_edit' => array( 'grid_inline_edit' ),
'grid_inline_save' => array( 'grid_inline_save' ),
'grid_inline_cancel' => array( 'grid_inline_cancel' ),
'grid_copy' => array( 'grid_copy' ),
'grid_view' => array( 'grid_view' ),
'grid_checkbox' => array( 'grid_checkbox' ),
'grid_alldetails_link' => array( 'grid_alldetails_link' ),
'grid_details_link' => array( 'grid_details_link' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'headcell_icons' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_checkbox' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array( 'checkbox_column' ),
'items' => array( 'grid_checkbox_head' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_details' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array( 'applicationAgentStatus_fieldheadercolumn' ),
'items' => array( 'grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field1' => array( 'cols' => array( 4 ),
'rows' => array( 0 ),
'tags' => array( 'salesPhase_fieldheadercolumn' ),
'items' => array( 'grid_field21' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field2' => array( 'cols' => array( 5 ),
'rows' => array( 0 ),
'tags' => array( 'applicationStatusId_fieldheadercolumn' ),
'items' => array( 'grid_field22' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field3' => array( 'cols' => array( 6 ),
'rows' => array( 0 ),
'tags' => array( 'applicationPhase_fieldheadercolumn' ),
'items' => array( 'grid_field23' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field4' => array( 'cols' => array( 7 ),
'rows' => array( 0 ),
'tags' => array( 'applicantName_fieldheadercolumn' ),
'items' => array( 'simple_grid_field6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field5' => array( 'cols' => array( 8 ),
'rows' => array( 0 ),
'tags' => array( 'applicantFirstName_fieldheadercolumn' ),
'items' => array( 'simple_grid_field7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field6' => array( 'cols' => array( 9 ),
'rows' => array( 0 ),
'tags' => array( 'applicantIdNumber_fieldheadercolumn' ),
'items' => array( 'simple_grid_field10' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field7' => array( 'cols' => array( 10 ),
'rows' => array( 0 ),
'tags' => array( 'applicantAddress_fieldheadercolumn' ),
'items' => array( 'simple_grid_field11' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field8' => array( 'cols' => array( 11 ),
'rows' => array( 0 ),
'tags' => array( 'applicantTaxRegistrationNumber_fieldheadercolumn' ),
'items' => array( 'simple_grid_field14' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field9' => array( 'cols' => array( 12 ),
'rows' => array( 0 ),
'tags' => array( 'applicantPhone_fieldheadercolumn' ),
'items' => array( 'simple_grid_field17' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field10' => array( 'cols' => array( 13 ),
'rows' => array( 0 ),
'tags' => array( 'applicantMobile_fieldheadercolumn' ),
'items' => array( 'simple_grid_field18' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field11' => array( 'cols' => array( 14 ),
'rows' => array( 0 ),
'tags' => array( 'applicationContactMethod_fieldheadercolumn' ),
'items' => array( 'grid_field8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field12' => array( 'cols' => array( 15 ),
'rows' => array( 0 ),
'tags' => array( 'applicationCourier_fieldheadercolumn' ),
'items' => array( 'grid_field9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field13' => array( 'cols' => array( 16 ),
'rows' => array( 0 ),
'tags' => array( 'applicationCourierDate_fieldheadercolumn' ),
'items' => array( 'grid_field10' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field14' => array( 'cols' => array( 17 ),
'rows' => array( 0 ),
'tags' => array( 'id_fieldheadercolumn' ),
'items' => array( 'simple_grid_field12' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field15' => array( 'cols' => array( 18 ),
'rows' => array( 0 ),
'tags' => array( 'callDate_fieldheadercolumn' ),
'items' => array( 'simple_grid_field19' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field16' => array( 'cols' => array( 19 ),
'rows' => array( 0 ),
'tags' => array( 'callPhone_fieldheadercolumn' ),
'items' => array( 'simple_grid_field20' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field17' => array( 'cols' => array( 20 ),
'rows' => array( 0 ),
'tags' => array( 'applicationLastStatusDate_fieldheadercolumn' ),
'items' => array( 'simple_grid_field21' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_icons' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'edit_column',
'inlineedit_column',
'inline_save',
'inline_cancel',
'copy_column',
'view_column' ),
'items' => array( 'grid_edit',
'grid_inline_edit',
'grid_inline_save',
'grid_inline_cancel',
'grid_copy',
'grid_view' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_checkbox' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array( 'checkbox_column' ),
'items' => array( 'grid_checkbox' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_details' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'grid_alldetails_link',
'grid_details_link' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array( 'applicationAgentStatus_fieldcolumn' ),
'items' => array( 'grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field1' => array( 'cols' => array( 4 ),
'rows' => array( 1 ),
'tags' => array( 'salesPhase_fieldcolumn' ),
'items' => array( 'grid_field20' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field2' => array( 'cols' => array( 5 ),
'rows' => array( 1 ),
'tags' => array( 'applicationStatusId_fieldcolumn' ),
'items' => array( 'grid_field18' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field3' => array( 'cols' => array( 6 ),
'rows' => array( 1 ),
'tags' => array( 'applicationPhase_fieldcolumn' ),
'items' => array( 'grid_field19' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field4' => array( 'cols' => array( 7 ),
'rows' => array( 1 ),
'tags' => array( 'applicantName_fieldcolumn' ),
'items' => array( 'simple_grid_field4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field5' => array( 'cols' => array( 8 ),
'rows' => array( 1 ),
'tags' => array( 'applicantFirstName_fieldcolumn' ),
'items' => array( 'simple_grid_field5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field6' => array( 'cols' => array( 9 ),
'rows' => array( 1 ),
'tags' => array( 'applicantIdNumber_fieldcolumn' ),
'items' => array( 'simple_grid_field8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field7' => array( 'cols' => array( 10 ),
'rows' => array( 1 ),
'tags' => array( 'applicantAddress_fieldcolumn' ),
'items' => array( 'simple_grid_field9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field8' => array( 'cols' => array( 11 ),
'rows' => array( 1 ),
'tags' => array( 'applicantTaxRegistrationNumber_fieldcolumn' ),
'items' => array( 'simple_grid_field13' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field9' => array( 'cols' => array( 12 ),
'rows' => array( 1 ),
'tags' => array( 'applicantPhone_fieldcolumn' ),
'items' => array( 'simple_grid_field15' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field10' => array( 'cols' => array( 13 ),
'rows' => array( 1 ),
'tags' => array( 'applicantMobile_fieldcolumn' ),
'items' => array( 'simple_grid_field16' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field11' => array( 'cols' => array( 14 ),
'rows' => array( 1 ),
'tags' => array( 'applicationContactMethod_fieldcolumn' ),
'items' => array( 'grid_field5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field12' => array( 'cols' => array( 15 ),
'rows' => array( 1 ),
'tags' => array( 'applicationCourier_fieldcolumn' ),
'items' => array( 'grid_field6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field13' => array( 'cols' => array( 16 ),
'rows' => array( 1 ),
'tags' => array( 'applicationCourierDate_fieldcolumn' ),
'items' => array( 'grid_field7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field14' => array( 'cols' => array( 17 ),
'rows' => array( 1 ),
'tags' => array( 'id_fieldcolumn' ),
'items' => array( 'simple_grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field15' => array( 'cols' => array( 18 ),
'rows' => array( 1 ),
'tags' => array( 'callDate_fieldcolumn' ),
'items' => array( 'simple_grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field16' => array( 'cols' => array( 19 ),
'rows' => array( 1 ),
'tags' => array( 'callPhone_fieldcolumn' ),
'items' => array( 'simple_grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field17' => array( 'cols' => array( 20 ),
'rows' => array( 1 ),
'tags' => array( 'applicationLastStatusDate_fieldcolumn' ),
'items' => array( 'simple_grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_dpreview' => array( 'cols' => array( 0,
1,
2,
3,
4,
5,
6,
7,
8,
9,
10,
11,
12,
13,
14,
15,
16,
17,
18,
19,
20 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'details_preview' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'footcell_icons' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_checkbox' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_details' => array( 'cols' => array( 2 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field' => array( 'cols' => array( 3 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field1' => array( 'cols' => array( 4 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field2' => array( 'cols' => array( 5 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field3' => array( 'cols' => array( 6 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field4' => array( 'cols' => array( 7 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field5' => array( 'cols' => array( 8 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field6' => array( 'cols' => array( 9 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field7' => array( 'cols' => array( 10 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field8' => array( 'cols' => array( 11 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field9' => array( 'cols' => array( 12 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field10' => array( 'cols' => array( 13 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field11' => array( 'cols' => array( 14 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field12' => array( 'cols' => array( 15 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field13' => array( 'cols' => array( 16 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field14' => array( 'cols' => array( 17 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field15' => array( 'cols' => array( 18 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field16' => array( 'cols' => array( 19 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field17' => array( 'cols' => array( 20 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 21,
'height' => 4 ) ) ),
'loginForm' => array( 'loginForm' => 1 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array( 'details_found' => array( 'tag' => 'DISPLAYING',
'type' => 2 ) ) ),
'gridType' => 0,
'recsPerRow' => 1,
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'list',
'breadcrumb' => true ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dataGrid' => array( 'groupFields' => array(  ) ) );
			$pageArray = array( 'id' => 'list',
'type' => 'list',
'layoutId' => 'topbar',
'disabled' => 0,
'default' => 2,
'forms' => array( 'supertop' => array( 'modelId' => 'topbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'logo',
'menu' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'simple_search',
'list_options',
'loginform_login',
'username_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'list-vbar',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c2' => array( 'model' => 'c2',
'items' => array( 'filter_panel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c1' => array( 'model' => 'c1',
'items' => array( 'search_panel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'list-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'breadcrumb' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'list-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add',
'inline_add',
'inline_save_all',
'inline_cancel_all',
'delete',
'update_selected' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'details_found',
'page_size',
'print_panel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'list-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'pagination' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'horizontal-grid',
'grid' => array( array( 'section' => 'head',
'cells' => array( array( 'cell' => 'headcell_icons' ),
array( 'cell' => 'headcell_checkbox' ),
array( 'cell' => 'headcell_details' ),
array( 'cell' => 'headcell_field' ),
array( 'cell' => 'headcell_field1' ),
array( 'cell' => 'headcell_field2' ),
array( 'cell' => 'headcell_field3' ),
array( 'cell' => 'headcell_field4' ),
array( 'cell' => 'headcell_field5' ),
array( 'cell' => 'headcell_field6' ),
array( 'cell' => 'headcell_field7' ),
array( 'cell' => 'headcell_field8' ),
array( 'cell' => 'headcell_field9' ),
array( 'cell' => 'headcell_field10' ),
array( 'cell' => 'headcell_field11' ),
array( 'cell' => 'headcell_field12' ),
array( 'cell' => 'headcell_field13' ),
array( 'cell' => 'headcell_field14' ),
array( 'cell' => 'headcell_field15' ),
array( 'cell' => 'headcell_field16' ),
array( 'cell' => 'headcell_field17' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_icons' ),
array( 'cell' => 'cell_checkbox' ),
array( 'cell' => 'cell_details' ),
array( 'cell' => 'cell_field' ),
array( 'cell' => 'cell_field1' ),
array( 'cell' => 'cell_field2' ),
array( 'cell' => 'cell_field3' ),
array( 'cell' => 'cell_field4' ),
array( 'cell' => 'cell_field5' ),
array( 'cell' => 'cell_field6' ),
array( 'cell' => 'cell_field7' ),
array( 'cell' => 'cell_field8' ),
array( 'cell' => 'cell_field9' ),
array( 'cell' => 'cell_field10' ),
array( 'cell' => 'cell_field11' ),
array( 'cell' => 'cell_field12' ),
array( 'cell' => 'cell_field13' ),
array( 'cell' => 'cell_field14' ),
array( 'cell' => 'cell_field15' ),
array( 'cell' => 'cell_field16' ),
array( 'cell' => 'cell_field17' ) ) ),
array( 'cells' => array( array( 'cell' => 'cell_dpreview',
'colspan' => 21 ) ),
'section' => 'body' ),
array( 'section' => 'foot',
'cells' => array( array( 'cell' => 'footcell_icons' ),
array( 'cell' => 'footcell_checkbox' ),
array( 'cell' => 'footcell_details' ),
array( 'cell' => 'footcell_field' ),
array( 'cell' => 'footcell_field1' ),
array( 'cell' => 'footcell_field2' ),
array( 'cell' => 'footcell_field3' ),
array( 'cell' => 'footcell_field4' ),
array( 'cell' => 'footcell_field5' ),
array( 'cell' => 'footcell_field6' ),
array( 'cell' => 'footcell_field7' ),
array( 'cell' => 'footcell_field8' ),
array( 'cell' => 'footcell_field9' ),
array( 'cell' => 'footcell_field10' ),
array( 'cell' => 'footcell_field11' ),
array( 'cell' => 'footcell_field12' ),
array( 'cell' => 'footcell_field13' ),
array( 'cell' => 'footcell_field14' ),
array( 'cell' => 'footcell_field15' ),
array( 'cell' => 'footcell_field16' ),
array( 'cell' => 'footcell_field17' ) ) ) ),
'cells' => array( 'headcell_field' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field' ),
'field' => 'applicationAgentStatus',
'columnName' => 'field' ),
'cell_field' => array( 'model' => 'cell_field',
'items' => array( 'grid_field1' ),
'field' => 'applicationAgentStatus',
'columnName' => 'field' ),
'footcell_field' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field1' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field21' ),
'field' => 'salesPhase',
'columnName' => 'field' ),
'cell_field1' => array( 'model' => 'cell_field',
'items' => array( 'grid_field20' ),
'field' => 'salesPhase',
'columnName' => 'field' ),
'footcell_field1' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field2' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field22' ),
'field' => 'applicationStatusId',
'columnName' => 'field' ),
'cell_field2' => array( 'model' => 'cell_field',
'items' => array( 'grid_field18' ),
'field' => 'applicationStatusId',
'columnName' => 'field' ),
'footcell_field2' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field3' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field23' ),
'field' => 'applicationPhase',
'columnName' => 'field' ),
'cell_field3' => array( 'model' => 'cell_field',
'items' => array( 'grid_field19' ),
'field' => 'applicationPhase',
'columnName' => 'field' ),
'footcell_field3' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field4' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field6' ),
'field' => 'applicantName',
'columnName' => 'field' ),
'cell_field4' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field4' ),
'field' => 'applicantName',
'columnName' => 'field' ),
'footcell_field4' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field5' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field7' ),
'field' => 'applicantFirstName',
'columnName' => 'field' ),
'cell_field5' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field5' ),
'field' => 'applicantFirstName',
'columnName' => 'field' ),
'footcell_field5' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field6' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field10' ),
'field' => 'applicantIdNumber',
'columnName' => 'field' ),
'cell_field6' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field8' ),
'field' => 'applicantIdNumber',
'columnName' => 'field' ),
'footcell_field6' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field7' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field11' ),
'field' => 'applicantAddress',
'columnName' => 'field' ),
'cell_field7' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field9' ),
'field' => 'applicantAddress',
'columnName' => 'field' ),
'footcell_field7' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field8' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field14' ),
'field' => 'applicantTaxRegistrationNumber',
'columnName' => 'field' ),
'cell_field8' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field13' ),
'field' => 'applicantTaxRegistrationNumber',
'columnName' => 'field' ),
'footcell_field8' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field9' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field17' ),
'field' => 'applicantPhone',
'columnName' => 'field' ),
'cell_field9' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field15' ),
'field' => 'applicantPhone',
'columnName' => 'field' ),
'footcell_field9' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field10' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field18' ),
'field' => 'applicantMobile',
'columnName' => 'field' ),
'cell_field10' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field16' ),
'field' => 'applicantMobile',
'columnName' => 'field' ),
'footcell_field10' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field11' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field8' ),
'field' => 'applicationContactMethod',
'columnName' => 'field' ),
'cell_field11' => array( 'model' => 'cell_field',
'items' => array( 'grid_field5' ),
'field' => 'applicationContactMethod',
'columnName' => 'field' ),
'footcell_field11' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field12' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field9' ),
'field' => 'applicationCourier',
'columnName' => 'field' ),
'cell_field12' => array( 'model' => 'cell_field',
'items' => array( 'grid_field6' ),
'field' => 'applicationCourier',
'columnName' => 'field' ),
'footcell_field12' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field13' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field10' ),
'field' => 'applicationCourierDate',
'columnName' => 'field' ),
'cell_field13' => array( 'model' => 'cell_field',
'items' => array( 'grid_field7' ),
'field' => 'applicationCourierDate',
'columnName' => 'field' ),
'footcell_field13' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field14' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field12' ),
'field' => 'id',
'columnName' => 'field' ),
'cell_field14' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field' ),
'field' => 'id',
'columnName' => 'field' ),
'footcell_field14' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field15' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field19' ),
'field' => 'callDate',
'columnName' => 'field' ),
'cell_field15' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field1' ),
'field' => 'callDate',
'columnName' => 'field' ),
'footcell_field15' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field16' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field20' ),
'field' => 'callPhone',
'columnName' => 'field' ),
'cell_field16' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field2' ),
'field' => 'callPhone',
'columnName' => 'field' ),
'footcell_field16' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field17' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field21' ),
'field' => 'applicationLastStatusDate',
'columnName' => 'field' ),
'cell_field17' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field3' ),
'field' => 'applicationLastStatusDate',
'columnName' => 'field' ),
'footcell_field17' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'cell_dpreview' => array( 'model' => 'cell_dpreview',
'items' => array( 'details_preview' ) ),
'headcell_checkbox' => array( 'model' => 'headcell_checkbox',
'items' => array( 'grid_checkbox_head' ),
'columnName' => 'checkbox' ),
'cell_checkbox' => array( 'model' => 'cell_checkbox',
'items' => array( 'grid_checkbox' ),
'columnName' => 'checkbox' ),
'footcell_checkbox' => array( 'model' => 'footcell_checkbox',
'items' => array(  ),
'columnName' => 'checkbox' ),
'headcell_icons' => array( 'model' => 'headcell_icons',
'items' => array(  ),
'columnName' => 'list-icons' ),
'cell_icons' => array( 'model' => 'cell_icons',
'items' => array( 'grid_edit',
'grid_inline_edit',
'grid_inline_save',
'grid_inline_cancel',
'grid_copy',
'grid_view' ),
'columnName' => 'list-icons' ),
'footcell_icons' => array( 'model' => 'footcell_icons',
'items' => array(  ),
'columnName' => 'list-icons' ),
'headcell_details' => array( 'model' => 'headcell_details',
'items' => array(  ),
'columnName' => 'details' ),
'cell_details' => array( 'model' => 'cell_details',
'items' => array( 'grid_alldetails_link',
'grid_details_link' ),
'columnName' => 'details' ),
'footcell_details' => array( 'model' => 'footcell_details',
'items' => array(  ),
'columnName' => 'details' ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'add' => array( 'type' => 'add',
'popup' => false ),
'inline_save_all' => array( 'type' => 'inline_save_all' ),
'inline_cancel_all' => array( 'type' => 'inline_cancel_all' ),
'delete' => array( 'type' => 'delete' ),
'update_selected' => array( 'type' => 'update_selected',
'popup' => false ),
'details_found' => array( 'type' => 'details_found' ),
'page_size' => array( 'type' => 'page_size' ),
'print_panel' => array( 'type' => 'print_panel',
'items' => array( 'print_scope',
'print_details',
'print_records',
'print_button' ) ),
'print_scope' => array( 'type' => 'print_scope' ),
'print_records' => array( 'type' => 'print_records' ),
'print_button' => array( 'type' => 'print_button' ),
'pagination' => array( 'type' => 'pagination' ),
'-5' => array( 'type' => '-' ),
'advsearch_link' => array( 'type' => 'advsearch_link' ),
'breadcrumb' => array( 'type' => 'breadcrumb' ),
'edit_selected' => array( 'type' => 'edit_selected' ),
'delete_selected' => array( 'type' => 'delete_selected' ),
'-' => array( 'type' => '-' ),
'menu' => array( 'type' => 'menu' ),
'simple_search' => array( 'type' => 'simple_search' ),
'list_options' => array( 'type' => 'list_options',
'items' => array( 'edit_selected',
'export_selected',
'delete_selected',
'-5',
'advsearch_link',
'-4',
'export' ) ),
'logo' => array( 'type' => 'logo' ),
'filter_panel' => array( 'type' => 'filter_panel',
'items' => array(  ) ),
'-1' => array( 'type' => '-' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'logout_link',
'adminarea_link' ) ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => true ),
'logout_link' => array( 'type' => 'logout_link' ),
'inline_add' => array( 'type' => 'inline_add',
'label' => array( 'type' => 0,
'text' => 'Εισαγωγή (Πλέγμα)' ) ),
'export' => array( 'type' => 'export' ),
'-2' => array( 'type' => '-' ),
'export_selected' => array( 'type' => 'export_selected' ),
'print_details' => array( 'type' => 'print_details',
'tables' => array( 'dbo.internalComments' => true ) ),
'-3' => array( 'type' => '-' ),
'-4' => array( 'type' => '-' ),
'search_panel' => array( 'type' => 'search_panel',
'items' => array( 'search_panel_field',
'search_panel_field2',
'search_panel_field1' ) ),
'search_panel_field' => array( 'field' => 'callDate',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field1' => array( 'field' => 'callPhone',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field2' => array( 'field' => 'applicationLastStatusDate',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'grid_field1' => array( 'field' => 'applicationAgentStatus',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true,
'clickSort' => true ),
'grid_field' => array( 'type' => 'grid_field_label',
'field' => 'applicationAgentStatus',
'clickSort' => true ),
'grid_field20' => array( 'field' => 'salesPhase',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field21' => array( 'type' => 'grid_field_label',
'field' => 'salesPhase' ),
'grid_field18' => array( 'field' => 'applicationStatusId',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'grid_field22' => array( 'type' => 'grid_field_label',
'field' => 'applicationStatusId' ),
'grid_field19' => array( 'field' => 'applicationPhase',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field23' => array( 'type' => 'grid_field_label',
'field' => 'applicationPhase' ),
'simple_grid_field4' => array( 'field' => 'applicantName',
'type' => 'grid_field',
'clickSort' => true,
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field6' => array( 'type' => 'grid_field_label',
'field' => 'applicantName',
'clickSort' => true ),
'simple_grid_field5' => array( 'field' => 'applicantFirstName',
'type' => 'grid_field',
'clickSort' => true,
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field7' => array( 'type' => 'grid_field_label',
'field' => 'applicantFirstName',
'clickSort' => true ),
'simple_grid_field8' => array( 'field' => 'applicantIdNumber',
'type' => 'grid_field',
'clickSort' => true,
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field10' => array( 'type' => 'grid_field_label',
'field' => 'applicantIdNumber',
'clickSort' => true ),
'simple_grid_field9' => array( 'field' => 'applicantAddress',
'type' => 'grid_field',
'clickSort' => true,
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field11' => array( 'type' => 'grid_field_label',
'field' => 'applicantAddress',
'clickSort' => true ),
'simple_grid_field13' => array( 'field' => 'applicantTaxRegistrationNumber',
'type' => 'grid_field',
'clickSort' => true,
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field14' => array( 'type' => 'grid_field_label',
'field' => 'applicantTaxRegistrationNumber',
'clickSort' => true ),
'simple_grid_field15' => array( 'field' => 'applicantPhone',
'type' => 'grid_field',
'clickSort' => true,
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field17' => array( 'type' => 'grid_field_label',
'field' => 'applicantPhone',
'clickSort' => true ),
'simple_grid_field16' => array( 'field' => 'applicantMobile',
'type' => 'grid_field',
'clickSort' => true,
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field18' => array( 'type' => 'grid_field_label',
'field' => 'applicantMobile',
'clickSort' => true ),
'grid_field5' => array( 'field' => 'applicationContactMethod',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'grid_field8' => array( 'type' => 'grid_field_label',
'field' => 'applicationContactMethod' ),
'grid_field6' => array( 'field' => 'applicationCourier',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'grid_field9' => array( 'type' => 'grid_field_label',
'field' => 'applicationCourier' ),
'grid_field7' => array( 'field' => 'applicationCourierDate',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'grid_field10' => array( 'type' => 'grid_field_label',
'field' => 'applicationCourierDate' ),
'simple_grid_field' => array( 'field' => 'id',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field12' => array( 'type' => 'grid_field_label',
'field' => 'id' ),
'simple_grid_field1' => array( 'field' => 'callDate',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field19' => array( 'type' => 'grid_field_label',
'field' => 'callDate' ),
'simple_grid_field2' => array( 'field' => 'callPhone',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field20' => array( 'type' => 'grid_field_label',
'field' => 'callPhone' ),
'simple_grid_field3' => array( 'field' => 'applicationLastStatusDate',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field21' => array( 'type' => 'grid_field_label',
'field' => 'applicationLastStatusDate' ),
'details_preview' => array( 'type' => 'details_preview',
'table' => 'dbo.internalComments',
'items' => array(  ),
'popup' => false,
'hideEmptyPreview' => false,
'proceedLink' => true,
'pageId' => 'list' ),
'grid_checkbox_head' => array( 'type' => 'grid_checkbox_head' ),
'grid_edit' => array( 'type' => 'grid_edit',
'popup' => false ),
'grid_inline_edit' => array( 'type' => 'grid_inline_edit' ),
'grid_inline_save' => array( 'type' => 'grid_inline_save' ),
'grid_inline_cancel' => array( 'type' => 'grid_inline_cancel' ),
'grid_copy' => array( 'type' => 'grid_copy',
'popup' => false ),
'grid_view' => array( 'type' => 'grid_view',
'popup' => false ),
'grid_checkbox' => array( 'type' => 'grid_checkbox' ),
'grid_alldetails_link' => array( 'type' => 'grid_alldetails_link' ),
'grid_details_link' => array( 'type' => 'grid_details_link',
'table' => 'dbo.internalComments',
'badge' => true,
'showCount' => true,
'hideIfNone' => true ) ),
'dbProps' => array(  ),
'responsiveGrid' => false,
'version' => 4 );
		?>