<?php
			$optionsArray = array( 'list' => array( 'inlineAdd' => false,
'detailsAdd' => false,
'inlineEdit' => false,
'delete' => true,
'updateSelected' => true,
'addInPopup' => null,
'viewInPopup' => false,
'clickSort' => true,
'sortDropdown' => false,
'showHideFields' => false,
'reorderFields' => false ),
'listSearch' => array( 'alwaysOnPanelFields' => array(  ),
'searchPanel' => true,
'fixedSearchPanel' => false,
'simpleSearchOptions' => false,
'searchSaving' => false ),
'totals' => array( 'id' => array( 'totalsType' => '' ),
'callid' => array( 'totalsType' => '' ),
'callIdForDate' => array( 'totalsType' => '' ),
'applicationStatusId' => array( 'totalsType' => 'COUNT' ),
'lastStatusDate' => array( 'totalsType' => '' ),
'applicationAgentStatus' => array( 'totalsType' => '' ),
'applicationType' => array( 'totalsType' => '' ),
'applicantName' => array( 'totalsType' => '' ),
'applicantFirstName' => array( 'totalsType' => '' ),
'applicantBirthdate' => array( 'totalsType' => '' ),
'applicantProfession' => array( 'totalsType' => '' ),
'applicantIdNumber' => array( 'totalsType' => '' ),
'applicantAddress' => array( 'totalsType' => '' ),
'applicantPostalCode' => array( 'totalsType' => '' ),
'applicantArea' => array( 'totalsType' => '' ),
'applicantCity' => array( 'totalsType' => '' ),
'applicantTaxRegistrationNumber' => array( 'totalsType' => '' ),
'applicantTaxOffice' => array( 'totalsType' => '' ),
'applicantPhone' => array( 'totalsType' => '' ),
'applicantMobile' => array( 'totalsType' => '' ),
'applicantEmail' => array( 'totalsType' => '' ),
'standAloneProgram' => array( 'totalsType' => '' ),
'doublePlayProgram' => array( 'totalsType' => '' ),
'ProgramSpeed' => array( 'totalsType' => '' ),
'triplePlayProgram' => array( 'totalsType' => '' ),
'triplePlayProgramType' => array( 'totalsType' => '' ),
'additionalServiceInternet' => array( 'totalsType' => '' ),
'additionalServiceInternetSpeed' => array( 'totalsType' => '' ),
'additionalServiceInternationalCalls' => array( 'totalsType' => '' ),
'additionalServiceStaticIp' => array( 'totalsType' => '' ),
'additionalServiceStaticBlock8Ip' => array( 'totalsType' => '' ),
'additionalServiceSecondLine' => array( 'totalsType' => '' ),
'additionalServiceLandLine1000Minutes' => array( 'totalsType' => '' ),
'additionalServiceEquipment' => array( 'totalsType' => '' ),
'additionalServiceEquipmentInstallation' => array( 'totalsType' => '' ),
'portabilityIsNewLine' => array( 'totalsType' => '' ),
'portabilityOldNumber' => array( 'totalsType' => '' ),
'portabilityOldOwner' => array( 'totalsType' => '' ),
'portabilityActivationAddress' => array( 'totalsType' => '' ),
'portabilityActivationPostalCode' => array( 'totalsType' => '' ),
'portabilityActivationArea' => array( 'totalsType' => '' ),
'portabilityActivationCity' => array( 'totalsType' => '' ),
'portabilityPstnIsdn' => array( 'totalsType' => '' ),
'portabilityLine1PhoneNumber' => array( 'totalsType' => '' ),
'portabilityLine2PhoneNumber' => array( 'totalsType' => '' ),
'portabilityLine3PhoneNumber' => array( 'totalsType' => '' ),
'portabilityLine4PhoneNumber' => array( 'totalsType' => '' ),
'portabilityUsername1' => array( 'totalsType' => '' ),
'portabilityusername2' => array( 'totalsType' => '' ),
'documentIdPassport' => array( 'totalsType' => '' ),
'documentIdPassportPreviousOwner' => array( 'totalsType' => '' ),
'documentLastBill' => array( 'totalsType' => '' ),
'documentAddressValidation' => array( 'totalsType' => '' ),
'documentDeathCertificate' => array( 'totalsType' => '' ),
'documentAuthorization' => array( 'totalsType' => '' ),
'documentOther' => array( 'totalsType' => '' ),
'documentOtherType' => array( 'totalsType' => '' ),
'applicationContactMethod' => array( 'totalsType' => '' ),
'applicationCourier' => array( 'totalsType' => '' ),
'applicationCourierDate' => array( 'totalsType' => '' ),
'applicationCourierTimeFrom' => array( 'totalsType' => '' ),
'applicationCourierTimeTo' => array( 'totalsType' => '' ),
'applicationCourierComments' => array( 'totalsType' => '' ),
'dialerAgent' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'applicationStatusId',
'applicationType',
'applicantName',
'applicantFirstName',
'applicantAddress',
'applicantPostalCode',
'applicantArea',
'applicantCity',
'applicantTaxRegistrationNumber',
'applicantPhone',
'applicantMobile',
'applicantEmail',
'standAloneProgram',
'doublePlayProgram',
'triplePlayProgram',
'ProgramSpeed',
'triplePlayProgramType',
'additionalServiceInternet',
'additionalServiceInternetSpeed',
'additionalServiceStaticIp',
'additionalServiceStaticBlock8Ip',
'additionalServiceSecondLine',
'additionalServiceLandLine1000Minutes',
'additionalServiceEquipment',
'portabilityOldNumber',
'portabilityOldOwner',
'portabilityActivationAddress',
'portabilityActivationPostalCode',
'portabilityActivationArea',
'portabilityActivationCity',
'portabilityPstnIsdn',
'portabilityLine1PhoneNumber',
'applicantTaxOffice',
'applicationContactMethod',
'lastStatusDate',
'applicationCourier',
'applicationCourierDate',
'applicationCourierTimeFrom',
'applicationCourierTimeTo',
'callIdForDate',
'applicationCourierComments',
'applicationAgentStatus' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array( 'lastStatusDate',
'callIdForDate' ),
'filterFields' => array( 'applicationStatusId',
'standAloneProgram' ),
'inlineAddFields' => array(  ),
'inlineEditFields' => array(  ),
'fieldItems' => array( 'applicationStatusId' => array( 'simple_grid_field2',
'simple_grid_field',
'grid_field_totals' ),
'applicationType' => array( 'simple_grid_field3',
'simple_grid_field6' ),
'applicantName' => array( 'simple_grid_field4',
'simple_grid_field7' ),
'applicantFirstName' => array( 'simple_grid_field5',
'simple_grid_field14' ),
'applicantAddress' => array( 'simple_grid_field9',
'simple_grid_field55' ),
'applicantPostalCode' => array( 'simple_grid_field10',
'simple_grid_field56' ),
'applicantArea' => array( 'simple_grid_field11',
'simple_grid_field57' ),
'applicantCity' => array( 'simple_grid_field12',
'simple_grid_field58' ),
'applicantTaxRegistrationNumber' => array( 'simple_grid_field13',
'simple_grid_field59' ),
'applicantPhone' => array( 'simple_grid_field15',
'simple_grid_field60' ),
'applicantMobile' => array( 'simple_grid_field16',
'simple_grid_field61' ),
'applicantEmail' => array( 'simple_grid_field17',
'simple_grid_field62' ),
'standAloneProgram' => array( 'simple_grid_field18',
'simple_grid_field63' ),
'doublePlayProgram' => array( 'simple_grid_field19',
'simple_grid_field64' ),
'triplePlayProgram' => array( 'simple_grid_field21',
'simple_grid_field65' ),
'ProgramSpeed' => array( 'simple_grid_field20',
'simple_grid_field66' ),
'triplePlayProgramType' => array( 'simple_grid_field22',
'simple_grid_field67' ),
'additionalServiceInternet' => array( 'simple_grid_field23',
'simple_grid_field68' ),
'additionalServiceInternetSpeed' => array( 'simple_grid_field24',
'simple_grid_field69' ),
'additionalServiceStaticIp' => array( 'simple_grid_field26',
'simple_grid_field71' ),
'additionalServiceStaticBlock8Ip' => array( 'simple_grid_field27',
'simple_grid_field72' ),
'additionalServiceSecondLine' => array( 'simple_grid_field28',
'simple_grid_field73' ),
'additionalServiceLandLine1000Minutes' => array( 'simple_grid_field29',
'simple_grid_field74' ),
'additionalServiceEquipment' => array( 'simple_grid_field30',
'simple_grid_field75' ),
'portabilityOldNumber' => array( 'simple_grid_field33',
'simple_grid_field78' ),
'portabilityOldOwner' => array( 'simple_grid_field34',
'simple_grid_field79' ),
'portabilityActivationAddress' => array( 'simple_grid_field35',
'simple_grid_field80' ),
'portabilityActivationPostalCode' => array( 'simple_grid_field36',
'simple_grid_field81' ),
'portabilityActivationArea' => array( 'simple_grid_field37',
'simple_grid_field82' ),
'portabilityActivationCity' => array( 'simple_grid_field38',
'simple_grid_field83' ),
'portabilityPstnIsdn' => array( 'simple_grid_field39',
'simple_grid_field84' ),
'portabilityLine1PhoneNumber' => array( 'simple_grid_field40',
'simple_grid_field85' ),
'applicantTaxOffice' => array( 'grid_field',
'grid_field_label' ),
'lastStatusDate' => array( 'grid_field_label3',
'grid_field3' ),
'applicationContactMethod' => array( 'grid_field5',
'grid_field_label5' ),
'applicationCourier' => array( 'grid_field6',
'grid_field_label6' ),
'applicationCourierDate' => array( 'grid_field7',
'grid_field_label7' ),
'applicationCourierTimeFrom' => array( 'grid_field8',
'grid_field_label8' ),
'callIdForDate' => array( 'grid_field_label2',
'grid_field2' ),
'applicationCourierTimeTo' => array( 'grid_field9',
'grid_field_label9' ),
'applicationCourierComments' => array( 'grid_field10',
'grid_field_label10' ),
'applicationAgentStatus' => array( 'grid_field_label1',
'grid_field1' ) ),
'hideEmptyFields' => array(  ) ),
'pageLinks' => array( 'edit' => true,
'add' => false,
'view' => true,
'print' => true ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array( 'logo',
'menu',
'simple_search',
'list_options',
'loginform_login',
'username_button' ),
'left' => array( 'search_panel',
'filter_panel' ),
'top' => array(  ),
'above-grid' => array( 'delete',
'update_selected',
'details_found',
'page_size',
'print_panel' ),
'below-grid' => array( 'pagination' ),
'grid' => array( 'simple_grid_field',
'simple_grid_field2',
'grid_field_totals',
'simple_grid_field6',
'simple_grid_field3',
'simple_grid_field7',
'simple_grid_field4',
'simple_grid_field14',
'simple_grid_field5',
'simple_grid_field55',
'simple_grid_field9',
'simple_grid_field56',
'simple_grid_field10',
'simple_grid_field57',
'simple_grid_field11',
'simple_grid_field58',
'simple_grid_field12',
'simple_grid_field59',
'simple_grid_field13',
'simple_grid_field60',
'simple_grid_field15',
'simple_grid_field61',
'simple_grid_field16',
'simple_grid_field62',
'simple_grid_field17',
'simple_grid_field63',
'simple_grid_field18',
'simple_grid_field64',
'simple_grid_field19',
'simple_grid_field65',
'simple_grid_field21',
'simple_grid_field66',
'simple_grid_field20',
'simple_grid_field67',
'simple_grid_field22',
'simple_grid_field68',
'simple_grid_field23',
'simple_grid_field69',
'simple_grid_field24',
'simple_grid_field71',
'simple_grid_field26',
'simple_grid_field72',
'simple_grid_field27',
'simple_grid_field73',
'simple_grid_field28',
'simple_grid_field74',
'simple_grid_field29',
'simple_grid_field75',
'simple_grid_field30',
'simple_grid_field78',
'simple_grid_field33',
'simple_grid_field79',
'simple_grid_field34',
'simple_grid_field80',
'simple_grid_field35',
'simple_grid_field81',
'simple_grid_field36',
'simple_grid_field82',
'simple_grid_field37',
'simple_grid_field83',
'simple_grid_field38',
'simple_grid_field84',
'simple_grid_field39',
'simple_grid_field85',
'simple_grid_field40',
'details_preview',
'grid_edit',
'grid_view',
'grid_checkbox_head',
'grid_checkbox',
'grid_alldetails_link',
'grid_field_label',
'grid_field',
'grid_field_label3',
'grid_field3',
'grid_field_label2',
'grid_field2',
'grid_field_label5',
'grid_field5',
'grid_field_label6',
'grid_field6',
'grid_field_label7',
'grid_field7',
'grid_field_label8',
'grid_field8',
'grid_field_label9',
'grid_field9',
'grid_field_label10',
'grid_field10',
'grid_field_label1',
'grid_field1' ) ),
'formXtTags' => array( 'top' => array(  ),
'above-grid' => array( 'deleteselected_link',
'updateselected_link',
'details_found',
'recsPerPage',
'print_friendly' ),
'below-grid' => array( 'pagination' ) ),
'itemForms' => array( 'logo' => 'supertop',
'menu' => 'supertop',
'simple_search' => 'supertop',
'list_options' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'search_panel' => 'left',
'filter_panel' => 'left',
'delete' => 'above-grid',
'update_selected' => 'above-grid',
'details_found' => 'above-grid',
'page_size' => 'above-grid',
'print_panel' => 'above-grid',
'pagination' => 'below-grid',
'simple_grid_field' => 'grid',
'simple_grid_field2' => 'grid',
'grid_field_totals' => 'grid',
'simple_grid_field6' => 'grid',
'simple_grid_field3' => 'grid',
'simple_grid_field7' => 'grid',
'simple_grid_field4' => 'grid',
'simple_grid_field14' => 'grid',
'simple_grid_field5' => 'grid',
'simple_grid_field55' => 'grid',
'simple_grid_field9' => 'grid',
'simple_grid_field56' => 'grid',
'simple_grid_field10' => 'grid',
'simple_grid_field57' => 'grid',
'simple_grid_field11' => 'grid',
'simple_grid_field58' => 'grid',
'simple_grid_field12' => 'grid',
'simple_grid_field59' => 'grid',
'simple_grid_field13' => 'grid',
'simple_grid_field60' => 'grid',
'simple_grid_field15' => 'grid',
'simple_grid_field61' => 'grid',
'simple_grid_field16' => 'grid',
'simple_grid_field62' => 'grid',
'simple_grid_field17' => 'grid',
'simple_grid_field63' => 'grid',
'simple_grid_field18' => 'grid',
'simple_grid_field64' => 'grid',
'simple_grid_field19' => 'grid',
'simple_grid_field65' => 'grid',
'simple_grid_field21' => 'grid',
'simple_grid_field66' => 'grid',
'simple_grid_field20' => 'grid',
'simple_grid_field67' => 'grid',
'simple_grid_field22' => 'grid',
'simple_grid_field68' => 'grid',
'simple_grid_field23' => 'grid',
'simple_grid_field69' => 'grid',
'simple_grid_field24' => 'grid',
'simple_grid_field71' => 'grid',
'simple_grid_field26' => 'grid',
'simple_grid_field72' => 'grid',
'simple_grid_field27' => 'grid',
'simple_grid_field73' => 'grid',
'simple_grid_field28' => 'grid',
'simple_grid_field74' => 'grid',
'simple_grid_field29' => 'grid',
'simple_grid_field75' => 'grid',
'simple_grid_field30' => 'grid',
'simple_grid_field78' => 'grid',
'simple_grid_field33' => 'grid',
'simple_grid_field79' => 'grid',
'simple_grid_field34' => 'grid',
'simple_grid_field80' => 'grid',
'simple_grid_field35' => 'grid',
'simple_grid_field81' => 'grid',
'simple_grid_field36' => 'grid',
'simple_grid_field82' => 'grid',
'simple_grid_field37' => 'grid',
'simple_grid_field83' => 'grid',
'simple_grid_field38' => 'grid',
'simple_grid_field84' => 'grid',
'simple_grid_field39' => 'grid',
'simple_grid_field85' => 'grid',
'simple_grid_field40' => 'grid',
'details_preview' => 'grid',
'grid_edit' => 'grid',
'grid_view' => 'grid',
'grid_checkbox_head' => 'grid',
'grid_checkbox' => 'grid',
'grid_alldetails_link' => 'grid',
'grid_field_label' => 'grid',
'grid_field' => 'grid',
'grid_field_label3' => 'grid',
'grid_field3' => 'grid',
'grid_field_label2' => 'grid',
'grid_field2' => 'grid',
'grid_field_label5' => 'grid',
'grid_field5' => 'grid',
'grid_field_label6' => 'grid',
'grid_field6' => 'grid',
'grid_field_label7' => 'grid',
'grid_field7' => 'grid',
'grid_field_label8' => 'grid',
'grid_field8' => 'grid',
'grid_field_label9' => 'grid',
'grid_field9' => 'grid',
'grid_field_label10' => 'grid',
'grid_field10' => 'grid',
'grid_field_label1' => 'grid',
'grid_field1' => 'grid' ),
'itemLocations' => array( 'simple_grid_field' => array( 'location' => 'grid',
'cellId' => 'headcell_field' ),
'simple_grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'grid_field_totals' => array( 'location' => 'grid',
'cellId' => 'footcell_field' ),
'simple_grid_field6' => array( 'location' => 'grid',
'cellId' => 'headcell_field1' ),
'simple_grid_field3' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'simple_grid_field7' => array( 'location' => 'grid',
'cellId' => 'headcell_field2' ),
'simple_grid_field4' => array( 'location' => 'grid',
'cellId' => 'cell_field2' ),
'simple_grid_field14' => array( 'location' => 'grid',
'cellId' => 'headcell_field3' ),
'simple_grid_field5' => array( 'location' => 'grid',
'cellId' => 'cell_field3' ),
'simple_grid_field55' => array( 'location' => 'grid',
'cellId' => 'headcell_field5' ),
'simple_grid_field9' => array( 'location' => 'grid',
'cellId' => 'cell_field5' ),
'simple_grid_field56' => array( 'location' => 'grid',
'cellId' => 'headcell_field6' ),
'simple_grid_field10' => array( 'location' => 'grid',
'cellId' => 'cell_field6' ),
'simple_grid_field57' => array( 'location' => 'grid',
'cellId' => 'headcell_field7' ),
'simple_grid_field11' => array( 'location' => 'grid',
'cellId' => 'cell_field7' ),
'simple_grid_field58' => array( 'location' => 'grid',
'cellId' => 'headcell_field8' ),
'simple_grid_field12' => array( 'location' => 'grid',
'cellId' => 'cell_field8' ),
'simple_grid_field59' => array( 'location' => 'grid',
'cellId' => 'headcell_field9' ),
'simple_grid_field13' => array( 'location' => 'grid',
'cellId' => 'cell_field9' ),
'simple_grid_field60' => array( 'location' => 'grid',
'cellId' => 'headcell_field10' ),
'simple_grid_field15' => array( 'location' => 'grid',
'cellId' => 'cell_field10' ),
'simple_grid_field61' => array( 'location' => 'grid',
'cellId' => 'headcell_field11' ),
'simple_grid_field16' => array( 'location' => 'grid',
'cellId' => 'cell_field11' ),
'simple_grid_field62' => array( 'location' => 'grid',
'cellId' => 'headcell_field12' ),
'simple_grid_field17' => array( 'location' => 'grid',
'cellId' => 'cell_field12' ),
'simple_grid_field63' => array( 'location' => 'grid',
'cellId' => 'headcell_field13' ),
'simple_grid_field18' => array( 'location' => 'grid',
'cellId' => 'cell_field13' ),
'simple_grid_field64' => array( 'location' => 'grid',
'cellId' => 'headcell_field14' ),
'simple_grid_field19' => array( 'location' => 'grid',
'cellId' => 'cell_field14' ),
'simple_grid_field65' => array( 'location' => 'grid',
'cellId' => 'headcell_field15' ),
'simple_grid_field21' => array( 'location' => 'grid',
'cellId' => 'cell_field15' ),
'simple_grid_field66' => array( 'location' => 'grid',
'cellId' => 'headcell_field16' ),
'simple_grid_field20' => array( 'location' => 'grid',
'cellId' => 'cell_field16' ),
'simple_grid_field67' => array( 'location' => 'grid',
'cellId' => 'headcell_field17' ),
'simple_grid_field22' => array( 'location' => 'grid',
'cellId' => 'cell_field17' ),
'simple_grid_field68' => array( 'location' => 'grid',
'cellId' => 'headcell_field18' ),
'simple_grid_field23' => array( 'location' => 'grid',
'cellId' => 'cell_field18' ),
'simple_grid_field69' => array( 'location' => 'grid',
'cellId' => 'headcell_field19' ),
'simple_grid_field24' => array( 'location' => 'grid',
'cellId' => 'cell_field19' ),
'simple_grid_field71' => array( 'location' => 'grid',
'cellId' => 'headcell_field21' ),
'simple_grid_field26' => array( 'location' => 'grid',
'cellId' => 'cell_field21' ),
'simple_grid_field72' => array( 'location' => 'grid',
'cellId' => 'headcell_field22' ),
'simple_grid_field27' => array( 'location' => 'grid',
'cellId' => 'cell_field22' ),
'simple_grid_field73' => array( 'location' => 'grid',
'cellId' => 'headcell_field23' ),
'simple_grid_field28' => array( 'location' => 'grid',
'cellId' => 'cell_field23' ),
'simple_grid_field74' => array( 'location' => 'grid',
'cellId' => 'headcell_field24' ),
'simple_grid_field29' => array( 'location' => 'grid',
'cellId' => 'cell_field24' ),
'simple_grid_field75' => array( 'location' => 'grid',
'cellId' => 'headcell_field25' ),
'simple_grid_field30' => array( 'location' => 'grid',
'cellId' => 'cell_field25' ),
'simple_grid_field78' => array( 'location' => 'grid',
'cellId' => 'headcell_field28' ),
'simple_grid_field33' => array( 'location' => 'grid',
'cellId' => 'cell_field28' ),
'simple_grid_field79' => array( 'location' => 'grid',
'cellId' => 'headcell_field29' ),
'simple_grid_field34' => array( 'location' => 'grid',
'cellId' => 'cell_field29' ),
'simple_grid_field80' => array( 'location' => 'grid',
'cellId' => 'headcell_field30' ),
'simple_grid_field35' => array( 'location' => 'grid',
'cellId' => 'cell_field30' ),
'simple_grid_field81' => array( 'location' => 'grid',
'cellId' => 'headcell_field31' ),
'simple_grid_field36' => array( 'location' => 'grid',
'cellId' => 'cell_field31' ),
'simple_grid_field82' => array( 'location' => 'grid',
'cellId' => 'headcell_field32' ),
'simple_grid_field37' => array( 'location' => 'grid',
'cellId' => 'cell_field32' ),
'simple_grid_field83' => array( 'location' => 'grid',
'cellId' => 'headcell_field33' ),
'simple_grid_field38' => array( 'location' => 'grid',
'cellId' => 'cell_field33' ),
'simple_grid_field84' => array( 'location' => 'grid',
'cellId' => 'headcell_field34' ),
'simple_grid_field39' => array( 'location' => 'grid',
'cellId' => 'cell_field34' ),
'simple_grid_field85' => array( 'location' => 'grid',
'cellId' => 'headcell_field35' ),
'simple_grid_field40' => array( 'location' => 'grid',
'cellId' => 'cell_field35' ),
'details_preview' => array( 'location' => 'grid',
'cellId' => 'cell_dpreview' ),
'grid_edit' => array( 'location' => 'grid',
'cellId' => 'cell_icons' ),
'grid_view' => array( 'location' => 'grid',
'cellId' => 'cell_icons' ),
'grid_checkbox_head' => array( 'location' => 'grid',
'cellId' => 'headcell_checkbox' ),
'grid_checkbox' => array( 'location' => 'grid',
'cellId' => 'cell_checkbox' ),
'grid_alldetails_link' => array( 'location' => 'grid',
'cellId' => 'cell_details' ),
'grid_field_label' => array( 'location' => 'grid',
'cellId' => 'headcell_field49' ),
'grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field49' ),
'grid_field_label3' => array( 'location' => 'grid',
'cellId' => 'headcell_field26' ),
'grid_field3' => array( 'location' => 'grid',
'cellId' => 'cell_field26' ),
'grid_field_label2' => array( 'location' => 'grid',
'cellId' => 'headcell_field20' ),
'grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field20' ),
'grid_field_label5' => array( 'location' => 'grid',
'cellId' => 'headcell_field54' ),
'grid_field5' => array( 'location' => 'grid',
'cellId' => 'cell_field54' ),
'grid_field_label6' => array( 'location' => 'grid',
'cellId' => 'headcell_field55' ),
'grid_field6' => array( 'location' => 'grid',
'cellId' => 'cell_field55' ),
'grid_field_label7' => array( 'location' => 'grid',
'cellId' => 'headcell_field56' ),
'grid_field7' => array( 'location' => 'grid',
'cellId' => 'cell_field56' ),
'grid_field_label8' => array( 'location' => 'grid',
'cellId' => 'headcell_field57' ),
'grid_field8' => array( 'location' => 'grid',
'cellId' => 'cell_field57' ),
'grid_field_label9' => array( 'location' => 'grid',
'cellId' => 'headcell_field58' ),
'grid_field9' => array( 'location' => 'grid',
'cellId' => 'cell_field58' ),
'grid_field_label10' => array( 'location' => 'grid',
'cellId' => 'headcell_field59' ),
'grid_field10' => array( 'location' => 'grid',
'cellId' => 'cell_field59' ),
'grid_field_label1' => array( 'location' => 'grid',
'cellId' => 'headcell_field4' ),
'grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field4' ) ),
'itemVisiblity' => array( 'menu' => 3,
'simple_search' => 3,
'list_options' => 3,
'loginform_login' => 3,
'username_button' => 3,
'search_panel' => 5,
'filter_panel' => 3,
'print_panel' => 5 ) ),
'itemsByType' => array( 'details_found' => array( 'details_found' ),
'page_size' => array( 'page_size' ),
'print_panel' => array( 'print_panel' ),
'print_scope' => array( 'print_scope' ),
'print_records' => array( 'print_records' ),
'print_button' => array( 'print_button' ),
'pagination' => array( 'pagination' ),
'grid_field' => array( 'simple_grid_field2',
'simple_grid_field3',
'simple_grid_field4',
'simple_grid_field5',
'simple_grid_field9',
'simple_grid_field10',
'simple_grid_field11',
'simple_grid_field12',
'simple_grid_field13',
'simple_grid_field15',
'simple_grid_field16',
'simple_grid_field17',
'simple_grid_field18',
'simple_grid_field19',
'simple_grid_field21',
'simple_grid_field20',
'simple_grid_field22',
'simple_grid_field23',
'simple_grid_field24',
'simple_grid_field26',
'simple_grid_field27',
'simple_grid_field28',
'simple_grid_field29',
'simple_grid_field30',
'simple_grid_field33',
'simple_grid_field34',
'simple_grid_field35',
'simple_grid_field36',
'simple_grid_field37',
'simple_grid_field38',
'simple_grid_field39',
'simple_grid_field40',
'grid_field',
'grid_field5',
'grid_field3',
'grid_field6',
'grid_field7',
'grid_field8',
'grid_field9',
'grid_field2',
'grid_field10',
'grid_field1' ),
'delete' => array( 'delete' ),
'details_preview' => array( 'details_preview' ),
'grid_checkbox_head' => array( 'grid_checkbox_head' ),
'grid_checkbox' => array( 'grid_checkbox' ),
'grid_alldetails_link' => array( 'grid_alldetails_link' ),
'grid_view' => array( 'grid_view' ),
'-' => array( '-',
'-1',
'-3',
'-2' ),
'menu' => array( 'menu' ),
'simple_search' => array( 'simple_search' ),
'list_options' => array( 'list_options' ),
'logo' => array( 'logo' ),
'filter_panel' => array( 'filter_panel' ),
'filter_panel_field' => array( 'filter_panel_field',
'filter_panel_field1' ),
'grid_field_label' => array( 'simple_grid_field',
'simple_grid_field6',
'simple_grid_field7',
'simple_grid_field14',
'simple_grid_field55',
'simple_grid_field56',
'simple_grid_field57',
'simple_grid_field58',
'simple_grid_field59',
'simple_grid_field60',
'simple_grid_field61',
'simple_grid_field62',
'simple_grid_field63',
'simple_grid_field64',
'simple_grid_field65',
'simple_grid_field66',
'simple_grid_field67',
'simple_grid_field68',
'simple_grid_field69',
'simple_grid_field71',
'simple_grid_field72',
'simple_grid_field73',
'simple_grid_field74',
'simple_grid_field75',
'simple_grid_field78',
'simple_grid_field79',
'simple_grid_field80',
'simple_grid_field81',
'simple_grid_field82',
'simple_grid_field83',
'simple_grid_field84',
'simple_grid_field85',
'grid_field_label',
'grid_field_label3',
'grid_field_label5',
'grid_field_label6',
'grid_field_label7',
'grid_field_label8',
'grid_field_label2',
'grid_field_label9',
'grid_field_label10',
'grid_field_label1' ),
'delete_selected' => array( 'delete_selected' ),
'update_selected' => array( 'update_selected' ),
'export_selected' => array( 'export_selected' ),
'export' => array( 'export' ),
'grid_edit' => array( 'grid_edit' ),
'hide_search_panel' => array( 'hide_search_panel' ),
'show_search_panel' => array( 'show_search_panel' ),
'grid_field_totals' => array( 'grid_field_totals' ),
'username_button' => array( 'username_button' ),
'adminarea_link' => array( 'adminarea_link' ),
'loginform_login' => array( 'loginform_login' ),
'logout_link' => array( 'logout_link' ),
'search_panel_field' => array( 'search_panel_field1',
'search_panel_field' ),
'search_panel' => array( 'search_panel' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'headcell_icons' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_checkbox' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array( 'checkbox_column' ),
'items' => array( 'grid_checkbox_head' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_details' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array( 'applicationStatusId_fieldheadercolumn' ),
'items' => array( 'simple_grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field1' => array( 'cols' => array( 4 ),
'rows' => array( 0 ),
'tags' => array( 'applicationType_fieldheadercolumn' ),
'items' => array( 'simple_grid_field6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field2' => array( 'cols' => array( 5 ),
'rows' => array( 0 ),
'tags' => array( 'applicantName_fieldheadercolumn' ),
'items' => array( 'simple_grid_field7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field3' => array( 'cols' => array( 6 ),
'rows' => array( 0 ),
'tags' => array( 'applicantFirstName_fieldheadercolumn' ),
'items' => array( 'simple_grid_field14' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field5' => array( 'cols' => array( 7 ),
'rows' => array( 0 ),
'tags' => array( 'applicantAddress_fieldheadercolumn' ),
'items' => array( 'simple_grid_field55' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field6' => array( 'cols' => array( 8 ),
'rows' => array( 0 ),
'tags' => array( 'applicantPostalCode_fieldheadercolumn' ),
'items' => array( 'simple_grid_field56' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field7' => array( 'cols' => array( 9 ),
'rows' => array( 0 ),
'tags' => array( 'applicantArea_fieldheadercolumn' ),
'items' => array( 'simple_grid_field57' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field8' => array( 'cols' => array( 10 ),
'rows' => array( 0 ),
'tags' => array( 'applicantCity_fieldheadercolumn' ),
'items' => array( 'simple_grid_field58' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field9' => array( 'cols' => array( 11 ),
'rows' => array( 0 ),
'tags' => array( 'applicantTaxRegistrationNumber_fieldheadercolumn' ),
'items' => array( 'simple_grid_field59' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field10' => array( 'cols' => array( 12 ),
'rows' => array( 0 ),
'tags' => array( 'applicantPhone_fieldheadercolumn' ),
'items' => array( 'simple_grid_field60' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field11' => array( 'cols' => array( 13 ),
'rows' => array( 0 ),
'tags' => array( 'applicantMobile_fieldheadercolumn' ),
'items' => array( 'simple_grid_field61' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field12' => array( 'cols' => array( 14 ),
'rows' => array( 0 ),
'tags' => array( 'applicantEmail_fieldheadercolumn' ),
'items' => array( 'simple_grid_field62' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field13' => array( 'cols' => array( 15 ),
'rows' => array( 0 ),
'tags' => array( 'standAloneProgram_fieldheadercolumn' ),
'items' => array( 'simple_grid_field63' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field14' => array( 'cols' => array( 16 ),
'rows' => array( 0 ),
'tags' => array( 'doublePlayProgram_fieldheadercolumn' ),
'items' => array( 'simple_grid_field64' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field15' => array( 'cols' => array( 17 ),
'rows' => array( 0 ),
'tags' => array( 'triplePlayProgram_fieldheadercolumn' ),
'items' => array( 'simple_grid_field65' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field16' => array( 'cols' => array( 18 ),
'rows' => array( 0 ),
'tags' => array( 'ProgramSpeed_fieldheadercolumn' ),
'items' => array( 'simple_grid_field66' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field17' => array( 'cols' => array( 19 ),
'rows' => array( 0 ),
'tags' => array( 'triplePlayProgramType_fieldheadercolumn' ),
'items' => array( 'simple_grid_field67' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field18' => array( 'cols' => array( 20 ),
'rows' => array( 0 ),
'tags' => array( 'additionalServiceInternet_fieldheadercolumn' ),
'items' => array( 'simple_grid_field68' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field19' => array( 'cols' => array( 21 ),
'rows' => array( 0 ),
'tags' => array( 'additionalServiceInternetSpeed_fieldheadercolumn' ),
'items' => array( 'simple_grid_field69' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field21' => array( 'cols' => array( 22 ),
'rows' => array( 0 ),
'tags' => array( 'additionalServiceStaticIp_fieldheadercolumn' ),
'items' => array( 'simple_grid_field71' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field22' => array( 'cols' => array( 23 ),
'rows' => array( 0 ),
'tags' => array( 'additionalServiceStaticBlock8Ip_fieldheadercolumn' ),
'items' => array( 'simple_grid_field72' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field23' => array( 'cols' => array( 24 ),
'rows' => array( 0 ),
'tags' => array( 'additionalServiceSecondLine_fieldheadercolumn' ),
'items' => array( 'simple_grid_field73' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field24' => array( 'cols' => array( 25 ),
'rows' => array( 0 ),
'tags' => array( 'additionalServiceLandLine1000Minutes_fieldheadercolumn' ),
'items' => array( 'simple_grid_field74' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field25' => array( 'cols' => array( 26 ),
'rows' => array( 0 ),
'tags' => array( 'additionalServiceEquipment_fieldheadercolumn' ),
'items' => array( 'simple_grid_field75' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field28' => array( 'cols' => array( 27 ),
'rows' => array( 0 ),
'tags' => array( 'portabilityOldNumber_fieldheadercolumn' ),
'items' => array( 'simple_grid_field78' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field29' => array( 'cols' => array( 28 ),
'rows' => array( 0 ),
'tags' => array( 'portabilityOldOwner_fieldheadercolumn' ),
'items' => array( 'simple_grid_field79' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field30' => array( 'cols' => array( 29 ),
'rows' => array( 0 ),
'tags' => array( 'portabilityActivationAddress_fieldheadercolumn' ),
'items' => array( 'simple_grid_field80' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field31' => array( 'cols' => array( 30 ),
'rows' => array( 0 ),
'tags' => array( 'portabilityActivationPostalCode_fieldheadercolumn' ),
'items' => array( 'simple_grid_field81' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field32' => array( 'cols' => array( 31 ),
'rows' => array( 0 ),
'tags' => array( 'portabilityActivationArea_fieldheadercolumn' ),
'items' => array( 'simple_grid_field82' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field33' => array( 'cols' => array( 32 ),
'rows' => array( 0 ),
'tags' => array( 'portabilityActivationCity_fieldheadercolumn' ),
'items' => array( 'simple_grid_field83' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field34' => array( 'cols' => array( 33 ),
'rows' => array( 0 ),
'tags' => array( 'portabilityPstnIsdn_fieldheadercolumn' ),
'items' => array( 'simple_grid_field84' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field35' => array( 'cols' => array( 34 ),
'rows' => array( 0 ),
'tags' => array( 'portabilityLine1PhoneNumber_fieldheadercolumn' ),
'items' => array( 'simple_grid_field85' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field49' => array( 'cols' => array( 35 ),
'rows' => array( 0 ),
'tags' => array( 'applicantTaxOffice_fieldheadercolumn' ),
'items' => array( 'grid_field_label' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field54' => array( 'cols' => array( 36 ),
'rows' => array( 0 ),
'tags' => array( 'applicationContactMethod_fieldheadercolumn' ),
'items' => array( 'grid_field_label5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field55' => array( 'cols' => array( 37 ),
'rows' => array( 0 ),
'tags' => array( 'applicationCourier_fieldheadercolumn' ),
'items' => array( 'grid_field_label6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field56' => array( 'cols' => array( 38 ),
'rows' => array( 0 ),
'tags' => array( 'applicationCourierDate_fieldheadercolumn' ),
'items' => array( 'grid_field_label7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field57' => array( 'cols' => array( 39 ),
'rows' => array( 0 ),
'tags' => array( 'applicationCourierTimeFrom_fieldheadercolumn' ),
'items' => array( 'grid_field_label8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field58' => array( 'cols' => array( 40 ),
'rows' => array( 0 ),
'tags' => array( 'applicationCourierTimeTo_fieldheadercolumn' ),
'items' => array( 'grid_field_label9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field59' => array( 'cols' => array( 41 ),
'rows' => array( 0 ),
'tags' => array( 'applicationCourierComments_fieldheadercolumn' ),
'items' => array( 'grid_field_label10' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field4' => array( 'cols' => array( 42 ),
'rows' => array( 0 ),
'tags' => array( 'applicationAgentStatus_fieldheadercolumn' ),
'items' => array( 'grid_field_label1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field26' => array( 'cols' => array( 43 ),
'rows' => array( 0 ),
'tags' => array( 'lastStatusDate_fieldheadercolumn' ),
'items' => array( 'grid_field_label3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field20' => array( 'cols' => array( 44 ),
'rows' => array( 0 ),
'tags' => array( 'callIdForDate_fieldheadercolumn' ),
'items' => array( 'grid_field_label2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_icons' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'edit_column',
'view_column' ),
'items' => array( 'grid_edit',
'grid_view' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_checkbox' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array( 'checkbox_column' ),
'items' => array( 'grid_checkbox' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_details' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'grid_alldetails_link' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array( 'applicationStatusId_fieldcolumn' ),
'items' => array( 'simple_grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field1' => array( 'cols' => array( 4 ),
'rows' => array( 1 ),
'tags' => array( 'applicationType_fieldcolumn' ),
'items' => array( 'simple_grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field2' => array( 'cols' => array( 5 ),
'rows' => array( 1 ),
'tags' => array( 'applicantName_fieldcolumn' ),
'items' => array( 'simple_grid_field4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field3' => array( 'cols' => array( 6 ),
'rows' => array( 1 ),
'tags' => array( 'applicantFirstName_fieldcolumn' ),
'items' => array( 'simple_grid_field5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field5' => array( 'cols' => array( 7 ),
'rows' => array( 1 ),
'tags' => array( 'applicantAddress_fieldcolumn' ),
'items' => array( 'simple_grid_field9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field6' => array( 'cols' => array( 8 ),
'rows' => array( 1 ),
'tags' => array( 'applicantPostalCode_fieldcolumn' ),
'items' => array( 'simple_grid_field10' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field7' => array( 'cols' => array( 9 ),
'rows' => array( 1 ),
'tags' => array( 'applicantArea_fieldcolumn' ),
'items' => array( 'simple_grid_field11' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field8' => array( 'cols' => array( 10 ),
'rows' => array( 1 ),
'tags' => array( 'applicantCity_fieldcolumn' ),
'items' => array( 'simple_grid_field12' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field9' => array( 'cols' => array( 11 ),
'rows' => array( 1 ),
'tags' => array( 'applicantTaxRegistrationNumber_fieldcolumn' ),
'items' => array( 'simple_grid_field13' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field10' => array( 'cols' => array( 12 ),
'rows' => array( 1 ),
'tags' => array( 'applicantPhone_fieldcolumn' ),
'items' => array( 'simple_grid_field15' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field11' => array( 'cols' => array( 13 ),
'rows' => array( 1 ),
'tags' => array( 'applicantMobile_fieldcolumn' ),
'items' => array( 'simple_grid_field16' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field12' => array( 'cols' => array( 14 ),
'rows' => array( 1 ),
'tags' => array( 'applicantEmail_fieldcolumn' ),
'items' => array( 'simple_grid_field17' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field13' => array( 'cols' => array( 15 ),
'rows' => array( 1 ),
'tags' => array( 'standAloneProgram_fieldcolumn' ),
'items' => array( 'simple_grid_field18' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field14' => array( 'cols' => array( 16 ),
'rows' => array( 1 ),
'tags' => array( 'doublePlayProgram_fieldcolumn' ),
'items' => array( 'simple_grid_field19' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field15' => array( 'cols' => array( 17 ),
'rows' => array( 1 ),
'tags' => array( 'triplePlayProgram_fieldcolumn' ),
'items' => array( 'simple_grid_field21' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field16' => array( 'cols' => array( 18 ),
'rows' => array( 1 ),
'tags' => array( 'ProgramSpeed_fieldcolumn' ),
'items' => array( 'simple_grid_field20' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field17' => array( 'cols' => array( 19 ),
'rows' => array( 1 ),
'tags' => array( 'triplePlayProgramType_fieldcolumn' ),
'items' => array( 'simple_grid_field22' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field18' => array( 'cols' => array( 20 ),
'rows' => array( 1 ),
'tags' => array( 'additionalServiceInternet_fieldcolumn' ),
'items' => array( 'simple_grid_field23' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field19' => array( 'cols' => array( 21 ),
'rows' => array( 1 ),
'tags' => array( 'additionalServiceInternetSpeed_fieldcolumn' ),
'items' => array( 'simple_grid_field24' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field21' => array( 'cols' => array( 22 ),
'rows' => array( 1 ),
'tags' => array( 'additionalServiceStaticIp_fieldcolumn' ),
'items' => array( 'simple_grid_field26' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field22' => array( 'cols' => array( 23 ),
'rows' => array( 1 ),
'tags' => array( 'additionalServiceStaticBlock8Ip_fieldcolumn' ),
'items' => array( 'simple_grid_field27' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field23' => array( 'cols' => array( 24 ),
'rows' => array( 1 ),
'tags' => array( 'additionalServiceSecondLine_fieldcolumn' ),
'items' => array( 'simple_grid_field28' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field24' => array( 'cols' => array( 25 ),
'rows' => array( 1 ),
'tags' => array( 'additionalServiceLandLine1000Minutes_fieldcolumn' ),
'items' => array( 'simple_grid_field29' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field25' => array( 'cols' => array( 26 ),
'rows' => array( 1 ),
'tags' => array( 'additionalServiceEquipment_fieldcolumn' ),
'items' => array( 'simple_grid_field30' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field28' => array( 'cols' => array( 27 ),
'rows' => array( 1 ),
'tags' => array( 'portabilityOldNumber_fieldcolumn' ),
'items' => array( 'simple_grid_field33' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field29' => array( 'cols' => array( 28 ),
'rows' => array( 1 ),
'tags' => array( 'portabilityOldOwner_fieldcolumn' ),
'items' => array( 'simple_grid_field34' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field30' => array( 'cols' => array( 29 ),
'rows' => array( 1 ),
'tags' => array( 'portabilityActivationAddress_fieldcolumn' ),
'items' => array( 'simple_grid_field35' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field31' => array( 'cols' => array( 30 ),
'rows' => array( 1 ),
'tags' => array( 'portabilityActivationPostalCode_fieldcolumn' ),
'items' => array( 'simple_grid_field36' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field32' => array( 'cols' => array( 31 ),
'rows' => array( 1 ),
'tags' => array( 'portabilityActivationArea_fieldcolumn' ),
'items' => array( 'simple_grid_field37' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field33' => array( 'cols' => array( 32 ),
'rows' => array( 1 ),
'tags' => array( 'portabilityActivationCity_fieldcolumn' ),
'items' => array( 'simple_grid_field38' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field34' => array( 'cols' => array( 33 ),
'rows' => array( 1 ),
'tags' => array( 'portabilityPstnIsdn_fieldcolumn' ),
'items' => array( 'simple_grid_field39' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field35' => array( 'cols' => array( 34 ),
'rows' => array( 1 ),
'tags' => array( 'portabilityLine1PhoneNumber_fieldcolumn' ),
'items' => array( 'simple_grid_field40' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field49' => array( 'cols' => array( 35 ),
'rows' => array( 1 ),
'tags' => array( 'applicantTaxOffice_fieldcolumn' ),
'items' => array( 'grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field54' => array( 'cols' => array( 36 ),
'rows' => array( 1 ),
'tags' => array( 'applicationContactMethod_fieldcolumn' ),
'items' => array( 'grid_field5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field55' => array( 'cols' => array( 37 ),
'rows' => array( 1 ),
'tags' => array( 'applicationCourier_fieldcolumn' ),
'items' => array( 'grid_field6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field56' => array( 'cols' => array( 38 ),
'rows' => array( 1 ),
'tags' => array( 'applicationCourierDate_fieldcolumn' ),
'items' => array( 'grid_field7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field57' => array( 'cols' => array( 39 ),
'rows' => array( 1 ),
'tags' => array( 'applicationCourierTimeFrom_fieldcolumn' ),
'items' => array( 'grid_field8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field58' => array( 'cols' => array( 40 ),
'rows' => array( 1 ),
'tags' => array( 'applicationCourierTimeTo_fieldcolumn' ),
'items' => array( 'grid_field9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field59' => array( 'cols' => array( 41 ),
'rows' => array( 1 ),
'tags' => array( 'applicationCourierComments_fieldcolumn' ),
'items' => array( 'grid_field10' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field4' => array( 'cols' => array( 42 ),
'rows' => array( 1 ),
'tags' => array( 'applicationAgentStatus_fieldcolumn' ),
'items' => array( 'grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field26' => array( 'cols' => array( 43 ),
'rows' => array( 1 ),
'tags' => array( 'lastStatusDate_fieldcolumn' ),
'items' => array( 'grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field20' => array( 'cols' => array( 44 ),
'rows' => array( 1 ),
'tags' => array( 'callIdForDate_fieldcolumn' ),
'items' => array( 'grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_dpreview' => array( 'cols' => array( 0,
1,
2,
3,
4,
5,
6,
7,
8,
9,
10,
11,
12,
13,
14,
15,
16,
17,
18,
19,
20,
21,
22,
23,
24,
25,
26,
27,
28,
29,
30,
31,
32,
33,
34,
35,
36,
37,
38,
39,
40,
41,
42,
43,
44 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'details_preview' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'footcell_icons' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_checkbox' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_details' => array( 'cols' => array( 2 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field' => array( 'cols' => array( 3 ),
'rows' => array( 3 ),
'tags' => array( 'applicationStatusId_fieldfootercolumn' ),
'items' => array( 'grid_field_totals' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field1' => array( 'cols' => array( 4 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field2' => array( 'cols' => array( 5 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field3' => array( 'cols' => array( 6 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field5' => array( 'cols' => array( 7 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field6' => array( 'cols' => array( 8 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field7' => array( 'cols' => array( 9 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field8' => array( 'cols' => array( 10 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field9' => array( 'cols' => array( 11 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field10' => array( 'cols' => array( 12 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field11' => array( 'cols' => array( 13 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field12' => array( 'cols' => array( 14 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field13' => array( 'cols' => array( 15 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field14' => array( 'cols' => array( 16 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field15' => array( 'cols' => array( 17 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field16' => array( 'cols' => array( 18 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field17' => array( 'cols' => array( 19 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field18' => array( 'cols' => array( 20 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field19' => array( 'cols' => array( 21 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field21' => array( 'cols' => array( 22 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field22' => array( 'cols' => array( 23 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field23' => array( 'cols' => array( 24 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field24' => array( 'cols' => array( 25 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field25' => array( 'cols' => array( 26 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field28' => array( 'cols' => array( 27 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field29' => array( 'cols' => array( 28 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field30' => array( 'cols' => array( 29 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field31' => array( 'cols' => array( 30 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field32' => array( 'cols' => array( 31 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field33' => array( 'cols' => array( 32 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field34' => array( 'cols' => array( 33 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field35' => array( 'cols' => array( 34 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field49' => array( 'cols' => array( 35 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field54' => array( 'cols' => array( 36 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field55' => array( 'cols' => array( 37 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field56' => array( 'cols' => array( 38 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field57' => array( 'cols' => array( 39 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field58' => array( 'cols' => array( 40 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field59' => array( 'cols' => array( 41 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field4' => array( 'cols' => array( 42 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field26' => array( 'cols' => array( 43 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field20' => array( 'cols' => array( 44 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 45,
'height' => 4 ) ) ),
'loginForm' => array( 'loginForm' => 1 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array( 'details_found' => array( 'tag' => 'DISPLAYING',
'type' => 2 ) ) ),
'gridType' => 0,
'recsPerRow' => 1,
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'list',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dataGrid' => array( 'groupFields' => array(  ) ) );
			$pageArray = array( 'id' => 'list',
'type' => 'list',
'layoutId' => 'topbar',
'disabled' => 0,
'default' => 2,
'forms' => array( 'supertop' => array( 'modelId' => 'topbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'logo',
'menu' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'simple_search',
'list_options',
'loginform_login',
'username_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'list-vbar',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'search_panel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'filter_panel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'list-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'list-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'delete',
'update_selected' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'details_found',
'page_size',
'print_panel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'list-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'pagination' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'horizontal-grid',
'grid' => array( array( 'section' => 'head',
'cells' => array( array( 'cell' => 'headcell_icons' ),
array( 'cell' => 'headcell_checkbox' ),
array( 'cell' => 'headcell_details' ),
array( 'cell' => 'headcell_field' ),
array( 'cell' => 'headcell_field1' ),
array( 'cell' => 'headcell_field2' ),
array( 'cell' => 'headcell_field3' ),
array( 'cell' => 'headcell_field5' ),
array( 'cell' => 'headcell_field6' ),
array( 'cell' => 'headcell_field7' ),
array( 'cell' => 'headcell_field8' ),
array( 'cell' => 'headcell_field9' ),
array( 'cell' => 'headcell_field10' ),
array( 'cell' => 'headcell_field11' ),
array( 'cell' => 'headcell_field12' ),
array( 'cell' => 'headcell_field13' ),
array( 'cell' => 'headcell_field14' ),
array( 'cell' => 'headcell_field15' ),
array( 'cell' => 'headcell_field16' ),
array( 'cell' => 'headcell_field17' ),
array( 'cell' => 'headcell_field18' ),
array( 'cell' => 'headcell_field19' ),
array( 'cell' => 'headcell_field21' ),
array( 'cell' => 'headcell_field22' ),
array( 'cell' => 'headcell_field23' ),
array( 'cell' => 'headcell_field24' ),
array( 'cell' => 'headcell_field25' ),
array( 'cell' => 'headcell_field28' ),
array( 'cell' => 'headcell_field29' ),
array( 'cell' => 'headcell_field30' ),
array( 'cell' => 'headcell_field31' ),
array( 'cell' => 'headcell_field32' ),
array( 'cell' => 'headcell_field33' ),
array( 'cell' => 'headcell_field34' ),
array( 'cell' => 'headcell_field35' ),
array( 'cell' => 'headcell_field49' ),
array( 'cell' => 'headcell_field54' ),
array( 'cell' => 'headcell_field55' ),
array( 'cell' => 'headcell_field56' ),
array( 'cell' => 'headcell_field57' ),
array( 'cell' => 'headcell_field58' ),
array( 'cell' => 'headcell_field59' ),
array( 'cell' => 'headcell_field4' ),
array( 'cell' => 'headcell_field26' ),
array( 'cell' => 'headcell_field20' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_icons' ),
array( 'cell' => 'cell_checkbox' ),
array( 'cell' => 'cell_details' ),
array( 'cell' => 'cell_field' ),
array( 'cell' => 'cell_field1' ),
array( 'cell' => 'cell_field2' ),
array( 'cell' => 'cell_field3' ),
array( 'cell' => 'cell_field5' ),
array( 'cell' => 'cell_field6' ),
array( 'cell' => 'cell_field7' ),
array( 'cell' => 'cell_field8' ),
array( 'cell' => 'cell_field9' ),
array( 'cell' => 'cell_field10' ),
array( 'cell' => 'cell_field11' ),
array( 'cell' => 'cell_field12' ),
array( 'cell' => 'cell_field13' ),
array( 'cell' => 'cell_field14' ),
array( 'cell' => 'cell_field15' ),
array( 'cell' => 'cell_field16' ),
array( 'cell' => 'cell_field17' ),
array( 'cell' => 'cell_field18' ),
array( 'cell' => 'cell_field19' ),
array( 'cell' => 'cell_field21' ),
array( 'cell' => 'cell_field22' ),
array( 'cell' => 'cell_field23' ),
array( 'cell' => 'cell_field24' ),
array( 'cell' => 'cell_field25' ),
array( 'cell' => 'cell_field28' ),
array( 'cell' => 'cell_field29' ),
array( 'cell' => 'cell_field30' ),
array( 'cell' => 'cell_field31' ),
array( 'cell' => 'cell_field32' ),
array( 'cell' => 'cell_field33' ),
array( 'cell' => 'cell_field34' ),
array( 'cell' => 'cell_field35' ),
array( 'cell' => 'cell_field49' ),
array( 'cell' => 'cell_field54' ),
array( 'cell' => 'cell_field55' ),
array( 'cell' => 'cell_field56' ),
array( 'cell' => 'cell_field57' ),
array( 'cell' => 'cell_field58' ),
array( 'cell' => 'cell_field59' ),
array( 'cell' => 'cell_field4' ),
array( 'cell' => 'cell_field26' ),
array( 'cell' => 'cell_field20' ) ) ),
array( 'cells' => array( array( 'cell' => 'cell_dpreview',
'colspan' => 45 ) ),
'section' => 'body' ),
array( 'section' => 'foot',
'cells' => array( array( 'cell' => 'footcell_icons' ),
array( 'cell' => 'footcell_checkbox' ),
array( 'cell' => 'footcell_details' ),
array( 'cell' => 'footcell_field' ),
array( 'cell' => 'footcell_field1' ),
array( 'cell' => 'footcell_field2' ),
array( 'cell' => 'footcell_field3' ),
array( 'cell' => 'footcell_field5' ),
array( 'cell' => 'footcell_field6' ),
array( 'cell' => 'footcell_field7' ),
array( 'cell' => 'footcell_field8' ),
array( 'cell' => 'footcell_field9' ),
array( 'cell' => 'footcell_field10' ),
array( 'cell' => 'footcell_field11' ),
array( 'cell' => 'footcell_field12' ),
array( 'cell' => 'footcell_field13' ),
array( 'cell' => 'footcell_field14' ),
array( 'cell' => 'footcell_field15' ),
array( 'cell' => 'footcell_field16' ),
array( 'cell' => 'footcell_field17' ),
array( 'cell' => 'footcell_field18' ),
array( 'cell' => 'footcell_field19' ),
array( 'cell' => 'footcell_field21' ),
array( 'cell' => 'footcell_field22' ),
array( 'cell' => 'footcell_field23' ),
array( 'cell' => 'footcell_field24' ),
array( 'cell' => 'footcell_field25' ),
array( 'cell' => 'footcell_field28' ),
array( 'cell' => 'footcell_field29' ),
array( 'cell' => 'footcell_field30' ),
array( 'cell' => 'footcell_field31' ),
array( 'cell' => 'footcell_field32' ),
array( 'cell' => 'footcell_field33' ),
array( 'cell' => 'footcell_field34' ),
array( 'cell' => 'footcell_field35' ),
array( 'cell' => 'footcell_field49' ),
array( 'cell' => 'footcell_field54' ),
array( 'cell' => 'footcell_field55' ),
array( 'cell' => 'footcell_field56' ),
array( 'cell' => 'footcell_field57' ),
array( 'cell' => 'footcell_field58' ),
array( 'cell' => 'footcell_field59' ),
array( 'cell' => 'footcell_field4' ),
array( 'cell' => 'footcell_field26' ),
array( 'cell' => 'footcell_field20' ) ) ) ),
'cells' => array( 'headcell_field' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field' ),
'field' => 'applicationStatusId',
'columnName' => 'field' ),
'cell_field' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field2' ),
'field' => 'applicationStatusId',
'columnName' => 'field' ),
'footcell_field' => array( 'model' => 'footcell_field',
'items' => array( 'grid_field_totals' ),
'field' => 'applicationStatusId',
'columnName' => 'field' ),
'headcell_field1' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field6' ),
'field' => 'applicationType',
'columnName' => 'field' ),
'cell_field1' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field3' ),
'field' => 'applicationType',
'columnName' => 'field' ),
'footcell_field1' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field2' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field7' ),
'field' => 'applicantName',
'columnName' => 'field' ),
'cell_field2' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field4' ),
'field' => 'applicantName',
'columnName' => 'field' ),
'footcell_field2' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field3' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field14' ),
'field' => 'applicantFirstName',
'columnName' => 'field' ),
'cell_field3' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field5' ),
'field' => 'applicantFirstName',
'columnName' => 'field' ),
'footcell_field3' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field5' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field55' ),
'field' => 'applicantAddress',
'columnName' => 'field' ),
'cell_field5' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field9' ),
'field' => 'applicantAddress',
'columnName' => 'field' ),
'footcell_field5' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field6' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field56' ),
'field' => 'applicantPostalCode',
'columnName' => 'field' ),
'cell_field6' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field10' ),
'field' => 'applicantPostalCode',
'columnName' => 'field' ),
'footcell_field6' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field7' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field57' ),
'field' => 'applicantArea',
'columnName' => 'field' ),
'cell_field7' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field11' ),
'field' => 'applicantArea',
'columnName' => 'field' ),
'footcell_field7' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field8' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field58' ),
'field' => 'applicantCity',
'columnName' => 'field' ),
'cell_field8' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field12' ),
'field' => 'applicantCity',
'columnName' => 'field' ),
'footcell_field8' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field9' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field59' ),
'field' => 'applicantTaxRegistrationNumber',
'columnName' => 'field' ),
'cell_field9' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field13' ),
'field' => 'applicantTaxRegistrationNumber',
'columnName' => 'field' ),
'footcell_field9' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field10' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field60' ),
'field' => 'applicantPhone',
'columnName' => 'field' ),
'cell_field10' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field15' ),
'field' => 'applicantPhone',
'columnName' => 'field' ),
'footcell_field10' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field11' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field61' ),
'field' => 'applicantMobile',
'columnName' => 'field' ),
'cell_field11' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field16' ),
'field' => 'applicantMobile',
'columnName' => 'field' ),
'footcell_field11' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field12' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field62' ),
'field' => 'applicantEmail',
'columnName' => 'field' ),
'cell_field12' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field17' ),
'field' => 'applicantEmail',
'columnName' => 'field' ),
'footcell_field12' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field13' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field63' ),
'field' => 'standAloneProgram',
'columnName' => 'field' ),
'cell_field13' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field18' ),
'field' => 'standAloneProgram',
'columnName' => 'field' ),
'footcell_field13' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field14' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field64' ),
'field' => 'doublePlayProgram',
'columnName' => 'field' ),
'cell_field14' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field19' ),
'field' => 'doublePlayProgram',
'columnName' => 'field' ),
'footcell_field14' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field15' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field65' ),
'field' => 'triplePlayProgram',
'columnName' => 'field' ),
'cell_field15' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field21' ),
'field' => 'triplePlayProgram',
'columnName' => 'field' ),
'footcell_field15' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field16' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field66' ),
'field' => 'ProgramSpeed',
'columnName' => 'field' ),
'cell_field16' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field20' ),
'field' => 'ProgramSpeed',
'columnName' => 'field' ),
'footcell_field16' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field17' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field67' ),
'field' => 'triplePlayProgramType',
'columnName' => 'field' ),
'cell_field17' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field22' ),
'field' => 'triplePlayProgramType',
'columnName' => 'field' ),
'footcell_field17' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field18' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field68' ),
'field' => 'additionalServiceInternet',
'columnName' => 'field' ),
'cell_field18' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field23' ),
'field' => 'additionalServiceInternet',
'columnName' => 'field' ),
'footcell_field18' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field19' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field69' ),
'field' => 'additionalServiceInternetSpeed',
'columnName' => 'field' ),
'cell_field19' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field24' ),
'field' => 'additionalServiceInternetSpeed',
'columnName' => 'field' ),
'footcell_field19' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field21' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field71' ),
'field' => 'additionalServiceStaticIp',
'columnName' => 'field' ),
'cell_field21' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field26' ),
'field' => 'additionalServiceStaticIp',
'columnName' => 'field' ),
'footcell_field21' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field22' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field72' ),
'field' => 'additionalServiceStaticBlock8Ip',
'columnName' => 'field' ),
'cell_field22' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field27' ),
'field' => 'additionalServiceStaticBlock8Ip',
'columnName' => 'field' ),
'footcell_field22' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field23' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field73' ),
'field' => 'additionalServiceSecondLine',
'columnName' => 'field' ),
'cell_field23' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field28' ),
'field' => 'additionalServiceSecondLine',
'columnName' => 'field' ),
'footcell_field23' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field24' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field74' ),
'field' => 'additionalServiceLandLine1000Minutes',
'columnName' => 'field' ),
'cell_field24' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field29' ),
'field' => 'additionalServiceLandLine1000Minutes',
'columnName' => 'field' ),
'footcell_field24' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field25' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field75' ),
'field' => 'additionalServiceEquipment',
'columnName' => 'field' ),
'cell_field25' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field30' ),
'field' => 'additionalServiceEquipment',
'columnName' => 'field' ),
'footcell_field25' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field28' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field78' ),
'field' => 'portabilityOldNumber',
'columnName' => 'field' ),
'cell_field28' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field33' ),
'field' => 'portabilityOldNumber',
'columnName' => 'field' ),
'footcell_field28' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field29' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field79' ),
'field' => 'portabilityOldOwner',
'columnName' => 'field' ),
'cell_field29' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field34' ),
'field' => 'portabilityOldOwner',
'columnName' => 'field' ),
'footcell_field29' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field30' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field80' ),
'field' => 'portabilityActivationAddress',
'columnName' => 'field' ),
'cell_field30' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field35' ),
'field' => 'portabilityActivationAddress',
'columnName' => 'field' ),
'footcell_field30' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field31' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field81' ),
'field' => 'portabilityActivationPostalCode',
'columnName' => 'field' ),
'cell_field31' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field36' ),
'field' => 'portabilityActivationPostalCode',
'columnName' => 'field' ),
'footcell_field31' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field32' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field82' ),
'field' => 'portabilityActivationArea',
'columnName' => 'field' ),
'cell_field32' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field37' ),
'field' => 'portabilityActivationArea',
'columnName' => 'field' ),
'footcell_field32' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field33' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field83' ),
'field' => 'portabilityActivationCity',
'columnName' => 'field' ),
'cell_field33' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field38' ),
'field' => 'portabilityActivationCity',
'columnName' => 'field' ),
'footcell_field33' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field34' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field84' ),
'field' => 'portabilityPstnIsdn',
'columnName' => 'field' ),
'cell_field34' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field39' ),
'field' => 'portabilityPstnIsdn',
'columnName' => 'field' ),
'footcell_field34' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field35' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field85' ),
'field' => 'portabilityLine1PhoneNumber',
'columnName' => 'field' ),
'cell_field35' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field40' ),
'field' => 'portabilityLine1PhoneNumber',
'columnName' => 'field' ),
'footcell_field35' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'cell_dpreview' => array( 'model' => 'cell_dpreview',
'items' => array( 'details_preview' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'headcell_icons' => array( 'model' => 'headcell_icons',
'items' => array(  ),
'columnName' => 'list-icons' ),
'cell_icons' => array( 'model' => 'cell_icons',
'items' => array( 'grid_edit',
'grid_view' ),
'columnName' => 'list-icons' ),
'footcell_icons' => array( 'model' => 'footcell_icons',
'items' => array(  ),
'columnName' => 'list-icons' ),
'headcell_checkbox' => array( 'model' => 'headcell_checkbox',
'items' => array( 'grid_checkbox_head' ),
'columnName' => 'checkbox' ),
'cell_checkbox' => array( 'model' => 'cell_checkbox',
'items' => array( 'grid_checkbox' ),
'columnName' => 'checkbox' ),
'footcell_checkbox' => array( 'model' => 'footcell_checkbox',
'items' => array(  ),
'columnName' => 'checkbox' ),
'headcell_details' => array( 'model' => 'headcell_details',
'items' => array(  ),
'columnName' => 'details' ),
'cell_details' => array( 'model' => 'cell_details',
'items' => array( 'grid_alldetails_link' ),
'columnName' => 'details' ),
'footcell_details' => array( 'model' => 'footcell_details',
'items' => array(  ),
'columnName' => 'details' ),
'headcell_field49' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label' ),
'field' => 'applicantTaxOffice',
'columnName' => 'field' ),
'cell_field49' => array( 'model' => 'cell_field',
'items' => array( 'grid_field' ),
'field' => 'applicantTaxOffice',
'columnName' => 'field' ),
'footcell_field49' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field26' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label3' ),
'field' => 'lastStatusDate',
'columnName' => 'field' ),
'cell_field26' => array( 'model' => 'cell_field',
'items' => array( 'grid_field3' ),
'field' => 'lastStatusDate',
'columnName' => 'field' ),
'footcell_field26' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field20' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label2' ),
'field' => 'callIdForDate',
'columnName' => 'field' ),
'cell_field20' => array( 'model' => 'cell_field',
'items' => array( 'grid_field2' ),
'field' => 'callIdForDate',
'columnName' => 'field' ),
'footcell_field20' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field54' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label5' ),
'field' => 'applicationContactMethod',
'columnName' => 'field' ),
'cell_field54' => array( 'model' => 'cell_field',
'items' => array( 'grid_field5' ),
'field' => 'applicationContactMethod',
'columnName' => 'field' ),
'footcell_field54' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field55' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label6' ),
'field' => 'applicationCourier',
'columnName' => 'field' ),
'cell_field55' => array( 'model' => 'cell_field',
'items' => array( 'grid_field6' ),
'field' => 'applicationCourier',
'columnName' => 'field' ),
'footcell_field55' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field56' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label7' ),
'field' => 'applicationCourierDate',
'columnName' => 'field' ),
'cell_field56' => array( 'model' => 'cell_field',
'items' => array( 'grid_field7' ),
'field' => 'applicationCourierDate',
'columnName' => 'field' ),
'footcell_field56' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field57' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label8' ),
'field' => 'applicationCourierTimeFrom',
'columnName' => 'field' ),
'cell_field57' => array( 'model' => 'cell_field',
'items' => array( 'grid_field8' ),
'field' => 'applicationCourierTimeFrom',
'columnName' => 'field' ),
'footcell_field57' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field58' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label9' ),
'field' => 'applicationCourierTimeTo',
'columnName' => 'field' ),
'cell_field58' => array( 'model' => 'cell_field',
'items' => array( 'grid_field9' ),
'field' => 'applicationCourierTimeTo',
'columnName' => 'field' ),
'footcell_field58' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field59' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label10' ),
'field' => 'applicationCourierComments',
'columnName' => 'field' ),
'cell_field59' => array( 'model' => 'cell_field',
'items' => array( 'grid_field10' ),
'field' => 'applicationCourierComments',
'columnName' => 'field' ),
'footcell_field59' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field4' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label1' ),
'field' => 'applicationAgentStatus',
'columnName' => 'field' ),
'cell_field4' => array( 'model' => 'cell_field',
'items' => array( 'grid_field1' ),
'field' => 'applicationAgentStatus',
'columnName' => 'field' ),
'footcell_field4' => array( 'model' => 'footcell_field',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'details_found' => array( 'type' => 'details_found' ),
'page_size' => array( 'type' => 'page_size' ),
'print_panel' => array( 'type' => 'print_panel',
'items' => array( 'print_scope',
'print_records',
'print_button' ) ),
'print_scope' => array( 'type' => 'print_scope' ),
'print_records' => array( 'type' => 'print_records' ),
'print_button' => array( 'type' => 'print_button' ),
'pagination' => array( 'type' => 'pagination' ),
'simple_grid_field2' => array( 'field' => 'applicationStatusId',
'type' => 'grid_field',
'clickSort' => true,
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field3' => array( 'field' => 'applicationType',
'type' => 'grid_field',
'clickSort' => true,
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field4' => array( 'field' => 'applicantName',
'type' => 'grid_field',
'clickSort' => true,
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field5' => array( 'field' => 'applicantFirstName',
'type' => 'grid_field',
'clickSort' => true,
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field9' => array( 'field' => 'applicantAddress',
'type' => 'grid_field',
'clickSort' => true,
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field10' => array( 'field' => 'applicantPostalCode',
'type' => 'grid_field',
'clickSort' => true,
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field11' => array( 'field' => 'applicantArea',
'type' => 'grid_field',
'clickSort' => true,
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field12' => array( 'field' => 'applicantCity',
'type' => 'grid_field',
'clickSort' => true,
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field13' => array( 'field' => 'applicantTaxRegistrationNumber',
'type' => 'grid_field',
'clickSort' => true,
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field15' => array( 'field' => 'applicantPhone',
'type' => 'grid_field',
'clickSort' => true,
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field16' => array( 'field' => 'applicantMobile',
'type' => 'grid_field',
'clickSort' => true,
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field17' => array( 'field' => 'applicantEmail',
'type' => 'grid_field',
'clickSort' => true,
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field18' => array( 'field' => 'standAloneProgram',
'type' => 'grid_field',
'clickSort' => true,
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field19' => array( 'field' => 'doublePlayProgram',
'type' => 'grid_field',
'clickSort' => true,
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field21' => array( 'field' => 'triplePlayProgram',
'type' => 'grid_field',
'clickSort' => true,
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field20' => array( 'field' => 'ProgramSpeed',
'type' => 'grid_field',
'clickSort' => true,
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field22' => array( 'field' => 'triplePlayProgramType',
'type' => 'grid_field',
'clickSort' => true,
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field23' => array( 'field' => 'additionalServiceInternet',
'type' => 'grid_field',
'clickSort' => true,
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field24' => array( 'field' => 'additionalServiceInternetSpeed',
'type' => 'grid_field',
'clickSort' => true,
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field26' => array( 'field' => 'additionalServiceStaticIp',
'type' => 'grid_field',
'clickSort' => true,
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field27' => array( 'field' => 'additionalServiceStaticBlock8Ip',
'type' => 'grid_field',
'clickSort' => true,
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field28' => array( 'field' => 'additionalServiceSecondLine',
'type' => 'grid_field',
'clickSort' => true,
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field29' => array( 'field' => 'additionalServiceLandLine1000Minutes',
'type' => 'grid_field',
'clickSort' => true,
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field30' => array( 'field' => 'additionalServiceEquipment',
'type' => 'grid_field',
'clickSort' => true,
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field33' => array( 'field' => 'portabilityOldNumber',
'type' => 'grid_field',
'clickSort' => true,
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field34' => array( 'field' => 'portabilityOldOwner',
'type' => 'grid_field',
'clickSort' => true,
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field35' => array( 'field' => 'portabilityActivationAddress',
'type' => 'grid_field',
'clickSort' => true,
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field36' => array( 'field' => 'portabilityActivationPostalCode',
'type' => 'grid_field',
'clickSort' => true,
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field37' => array( 'field' => 'portabilityActivationArea',
'type' => 'grid_field',
'clickSort' => true,
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field38' => array( 'field' => 'portabilityActivationCity',
'type' => 'grid_field',
'clickSort' => true,
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field39' => array( 'field' => 'portabilityPstnIsdn',
'type' => 'grid_field',
'clickSort' => true,
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field40' => array( 'field' => 'portabilityLine1PhoneNumber',
'type' => 'grid_field',
'clickSort' => true,
'inlineAdd' => false,
'inlineEdit' => false ),
'delete' => array( 'type' => 'delete' ),
'details_preview' => array( 'type' => 'details_preview',
'table' => 'dbo.internalComments',
'items' => array(  ),
'popup' => false,
'hideEmptyPreview' => false,
'proceedLink' => false,
'pageId' => 'list' ),
'grid_checkbox_head' => array( 'type' => 'grid_checkbox_head' ),
'grid_checkbox' => array( 'type' => 'grid_checkbox' ),
'grid_alldetails_link' => array( 'type' => 'grid_alldetails_link' ),
'grid_view' => array( 'type' => 'grid_view',
'popup' => false ),
'-' => array( 'type' => '-' ),
'menu' => array( 'type' => 'menu' ),
'simple_search' => array( 'type' => 'simple_search' ),
'list_options' => array( 'type' => 'list_options',
'items' => array( 'export_selected',
'delete_selected',
'-3',
'show_search_panel',
'hide_search_panel',
'-2',
'export' ) ),
'logo' => array( 'type' => 'logo' ),
'filter_panel' => array( 'type' => 'filter_panel',
'items' => array( 'filter_panel_field',
'filter_panel_field1' ) ),
'filter_panel_field' => array( 'field' => 'applicationStatusId',
'type' => 'filter_panel_field' ),
'filter_panel_field1' => array( 'field' => 'standAloneProgram',
'type' => 'filter_panel_field' ),
'simple_grid_field' => array( 'type' => 'grid_field_label',
'field' => 'applicationStatusId',
'clickSort' => true ),
'simple_grid_field6' => array( 'type' => 'grid_field_label',
'field' => 'applicationType',
'clickSort' => true ),
'simple_grid_field7' => array( 'type' => 'grid_field_label',
'field' => 'applicantName',
'clickSort' => true ),
'simple_grid_field14' => array( 'type' => 'grid_field_label',
'field' => 'applicantFirstName',
'clickSort' => true ),
'simple_grid_field55' => array( 'type' => 'grid_field_label',
'field' => 'applicantAddress',
'clickSort' => true ),
'simple_grid_field56' => array( 'type' => 'grid_field_label',
'field' => 'applicantPostalCode',
'clickSort' => true ),
'simple_grid_field57' => array( 'type' => 'grid_field_label',
'field' => 'applicantArea',
'clickSort' => true ),
'simple_grid_field58' => array( 'type' => 'grid_field_label',
'field' => 'applicantCity',
'clickSort' => true ),
'simple_grid_field59' => array( 'type' => 'grid_field_label',
'field' => 'applicantTaxRegistrationNumber',
'clickSort' => true ),
'simple_grid_field60' => array( 'type' => 'grid_field_label',
'field' => 'applicantPhone',
'clickSort' => true ),
'simple_grid_field61' => array( 'type' => 'grid_field_label',
'field' => 'applicantMobile',
'clickSort' => true ),
'simple_grid_field62' => array( 'type' => 'grid_field_label',
'field' => 'applicantEmail',
'clickSort' => true ),
'simple_grid_field63' => array( 'type' => 'grid_field_label',
'field' => 'standAloneProgram',
'clickSort' => true ),
'simple_grid_field64' => array( 'type' => 'grid_field_label',
'field' => 'doublePlayProgram',
'clickSort' => true ),
'simple_grid_field65' => array( 'type' => 'grid_field_label',
'field' => 'triplePlayProgram',
'clickSort' => true ),
'simple_grid_field66' => array( 'type' => 'grid_field_label',
'field' => 'ProgramSpeed',
'clickSort' => true ),
'simple_grid_field67' => array( 'type' => 'grid_field_label',
'field' => 'triplePlayProgramType',
'clickSort' => true ),
'simple_grid_field68' => array( 'type' => 'grid_field_label',
'field' => 'additionalServiceInternet',
'clickSort' => true ),
'simple_grid_field69' => array( 'type' => 'grid_field_label',
'field' => 'additionalServiceInternetSpeed',
'clickSort' => true ),
'simple_grid_field71' => array( 'type' => 'grid_field_label',
'field' => 'additionalServiceStaticIp',
'clickSort' => true ),
'simple_grid_field72' => array( 'type' => 'grid_field_label',
'field' => 'additionalServiceStaticBlock8Ip',
'clickSort' => true ),
'simple_grid_field73' => array( 'type' => 'grid_field_label',
'field' => 'additionalServiceSecondLine',
'clickSort' => true ),
'simple_grid_field74' => array( 'type' => 'grid_field_label',
'field' => 'additionalServiceLandLine1000Minutes',
'clickSort' => true ),
'simple_grid_field75' => array( 'type' => 'grid_field_label',
'field' => 'additionalServiceEquipment',
'clickSort' => true ),
'simple_grid_field78' => array( 'type' => 'grid_field_label',
'field' => 'portabilityOldNumber',
'clickSort' => true ),
'simple_grid_field79' => array( 'type' => 'grid_field_label',
'field' => 'portabilityOldOwner',
'clickSort' => true ),
'simple_grid_field80' => array( 'type' => 'grid_field_label',
'field' => 'portabilityActivationAddress',
'clickSort' => true ),
'simple_grid_field81' => array( 'type' => 'grid_field_label',
'field' => 'portabilityActivationPostalCode',
'clickSort' => true ),
'simple_grid_field82' => array( 'type' => 'grid_field_label',
'field' => 'portabilityActivationArea',
'clickSort' => true ),
'simple_grid_field83' => array( 'type' => 'grid_field_label',
'field' => 'portabilityActivationCity',
'clickSort' => true ),
'simple_grid_field84' => array( 'type' => 'grid_field_label',
'field' => 'portabilityPstnIsdn',
'clickSort' => true ),
'simple_grid_field85' => array( 'type' => 'grid_field_label',
'field' => 'portabilityLine1PhoneNumber',
'clickSort' => true ),
'delete_selected' => array( 'type' => 'delete_selected' ),
'update_selected' => array( 'type' => 'update_selected' ),
'grid_field' => array( 'field' => 'applicantTaxOffice',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label' => array( 'type' => 'grid_field_label',
'field' => 'applicantTaxOffice',
'clickSort' => true ),
'-1' => array( 'type' => '-' ),
'-3' => array( 'type' => '-' ),
'export_selected' => array( 'type' => 'export_selected' ),
'-2' => array( 'type' => '-' ),
'export' => array( 'type' => 'export' ),
'grid_edit' => array( 'type' => 'grid_edit' ),
'hide_search_panel' => array( 'type' => 'hide_search_panel' ),
'show_search_panel' => array( 'type' => 'show_search_panel' ),
'grid_field_totals' => array( 'type' => 'grid_field_totals',
'field' => 'applicationStatusId',
'totals' => 'COUNT' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'logout_link',
'adminarea_link' ) ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => true ),
'logout_link' => array( 'type' => 'logout_link' ),
'search_panel_field1' => array( 'field' => 'lastStatusDate',
'type' => 'search_panel_field',
'required' => false ),
'grid_field_label3' => array( 'type' => 'grid_field_label',
'field' => 'lastStatusDate' ),
'grid_field5' => array( 'field' => 'applicationContactMethod',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label5' => array( 'type' => 'grid_field_label',
'field' => 'applicationContactMethod',
'clickSort' => true ),
'grid_field3' => array( 'field' => 'lastStatusDate',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field6' => array( 'field' => 'applicationCourier',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label6' => array( 'type' => 'grid_field_label',
'field' => 'applicationCourier',
'clickSort' => true ),
'search_panel_field' => array( 'field' => 'callIdForDate',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'grid_field7' => array( 'field' => 'applicationCourierDate',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label7' => array( 'type' => 'grid_field_label',
'field' => 'applicationCourierDate',
'clickSort' => true ),
'search_panel' => array( 'type' => 'search_panel',
'items' => array( 'search_panel_field1',
'search_panel_field' ),
'_flexiblePanel' => true ),
'grid_field8' => array( 'field' => 'applicationCourierTimeFrom',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label8' => array( 'type' => 'grid_field_label',
'field' => 'applicationCourierTimeFrom',
'clickSort' => true ),
'grid_field_label2' => array( 'type' => 'grid_field_label',
'field' => 'callIdForDate' ),
'grid_field9' => array( 'field' => 'applicationCourierTimeTo',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label9' => array( 'type' => 'grid_field_label',
'field' => 'applicationCourierTimeTo',
'clickSort' => true ),
'grid_field2' => array( 'field' => 'callIdForDate',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field10' => array( 'field' => 'applicationCourierComments',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label10' => array( 'type' => 'grid_field_label',
'field' => 'applicationCourierComments',
'clickSort' => true ),
'grid_field_label1' => array( 'type' => 'grid_field_label',
'field' => 'applicationAgentStatus' ),
'grid_field1' => array( 'field' => 'applicationAgentStatus',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ) ),
'dbProps' => array(  ),
'responsiveGrid' => false,
'version' => 4 );
		?>