<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'id',
'dialerPhone',
'dialerAgent',
'calldate',
'totalAppsQty',
'dialerCampaign',
'statusAppsCount',
'appStatusRatioInCall',
'dialerList',
'talkTime',
'typingTime',
'totalCallTime',
'callStatus',
'salesStatus',
'callClassificationID',
'callSubClassificationID' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'id' => array( 'import_field' ),
'dialerPhone' => array( 'import_field1' ),
'dialerAgent' => array( 'import_field2' ),
'calldate' => array( 'import_field3' ),
'totalAppsQty' => array( 'import_field4' ),
'dialerCampaign' => array( 'import_field5' ),
'statusAppsCount' => array( 'import_field6' ),
'appStatusRatioInCall' => array( 'import_field7' ),
'dialerList' => array( 'import_field8' ),
'talkTime' => array( 'import_field9' ),
'typingTime' => array( 'import_field10' ),
'totalCallTime' => array( 'import_field11' ),
'callStatus' => array( 'import_field12' ),
'salesStatus' => array( 'import_field13' ),
'callClassificationID' => array( 'import_field15' ),
'callSubClassificationID' => array( 'import_field16' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field1',
'import_field4',
'import_field6',
'import_field7',
'import_field2',
'import_field3',
'import_field5',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field15',
'import_field16' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field1' => 'grid',
'import_field4' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field5' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid',
'import_field13' => 'grid',
'import_field15' => 'grid',
'import_field16' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field15',
'import_field16' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field1',
'import_field4',
'import_field6',
'import_field7',
'import_field2',
'import_field3',
'import_field5',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field15',
'import_field16' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'id',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'dialerPhone',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'dialerAgent',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'calldate',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'totalAppsQty',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'dialerCampaign',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'statusAppsCount',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'appStatusRatioInCall',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'dialerList',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'talkTime',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'typingTime',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'totalCallTime',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'callStatus',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'salesStatus',
'type' => 'import_field' ),
'import_field15' => array( 'field' => 'callClassificationID',
'type' => 'import_field' ),
'import_field16' => array( 'field' => 'callSubClassificationID',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>