<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'dialerAgent',
'dialerPhone',
'calldate',
'denialReason',
'callStatus',
'dialerCampaign',
'dialerList',
'totalCallTime',
'novaTotalApps',
'voltonTotalApps' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'dialerAgent' => array( 'integrated_search_field1',
'search_field_label',
'search_field_options',
'search_field_between' ),
'dialerPhone' => array( 'integrated_search_field2',
'search_field_label1',
'search_field_options1',
'search_field_between1' ),
'calldate' => array( 'integrated_search_field3',
'search_field_label2',
'search_field_options2',
'search_field_between2' ),
'denialReason' => array( 'integrated_search_field4',
'search_field_label3',
'search_field_options3',
'search_field_between3' ),
'callStatus' => array( 'integrated_search_field6',
'search_field_label4',
'search_field_options4',
'search_field_between4' ),
'dialerCampaign' => array( 'integrated_search_field7',
'search_field_label6',
'search_field_options6',
'search_field_between6' ),
'dialerList' => array( 'integrated_search_field8',
'search_field_label5',
'search_field_options5',
'search_field_between5' ),
'totalCallTime' => array( 'integrated_search_field11',
'search_field_label7',
'search_field_options7',
'search_field_between7' ),
'novaTotalApps' => array( 'integrated_search_field12',
'search_field_label8',
'search_field_options8',
'search_field_between8' ),
'voltonTotalApps' => array( 'integrated_search_field13',
'search_field_label9',
'search_field_options9',
'search_field_between9' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array( 'logo',
'menu',
'loginform_login',
'username_button' ),
'top' => array( 'search_header' ),
'above-grid' => array(  ),
'below-grid' => array( 'search_search',
'search_reset',
'search_back_list',
'search_cancel' ),
'grid' => array( 'integrated_search_field1',
'search_field_between',
'integrated_search_field12',
'search_field_between8',
'integrated_search_field7',
'search_field_between6',
'integrated_search_field6',
'search_field_between4',
'integrated_search_field3',
'search_field_between2',
'integrated_search_field11',
'search_field_between7',
'search_field_label',
'search_field_label2',
'search_field_label4',
'search_field_label6',
'search_field_label7',
'search_field_label8',
'search_field_options',
'search_field_options2',
'search_field_options4',
'search_field_options6',
'search_field_options7',
'search_field_options8',
'integrated_search_field2',
'search_field_between1',
'integrated_search_field4',
'search_field_between3',
'integrated_search_field8',
'search_field_between5',
'integrated_search_field13',
'search_field_between9',
'search_field_options1',
'search_field_options3',
'search_field_options5',
'search_field_options9',
'search_field_label1',
'search_field_label3',
'search_field_label5',
'search_field_label9' ) ),
'formXtTags' => array( 'above-grid' => array(  ) ),
'itemForms' => array( 'logo' => 'supertop',
'menu' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'search_header' => 'top',
'search_search' => 'below-grid',
'search_reset' => 'below-grid',
'search_back_list' => 'below-grid',
'search_cancel' => 'below-grid',
'integrated_search_field1' => 'grid',
'search_field_between' => 'grid',
'integrated_search_field12' => 'grid',
'search_field_between8' => 'grid',
'integrated_search_field7' => 'grid',
'search_field_between6' => 'grid',
'integrated_search_field6' => 'grid',
'search_field_between4' => 'grid',
'integrated_search_field3' => 'grid',
'search_field_between2' => 'grid',
'integrated_search_field11' => 'grid',
'search_field_between7' => 'grid',
'search_field_label' => 'grid',
'search_field_label2' => 'grid',
'search_field_label4' => 'grid',
'search_field_label6' => 'grid',
'search_field_label7' => 'grid',
'search_field_label8' => 'grid',
'search_field_options' => 'grid',
'search_field_options2' => 'grid',
'search_field_options4' => 'grid',
'search_field_options6' => 'grid',
'search_field_options7' => 'grid',
'search_field_options8' => 'grid',
'integrated_search_field2' => 'grid',
'search_field_between1' => 'grid',
'integrated_search_field4' => 'grid',
'search_field_between3' => 'grid',
'integrated_search_field8' => 'grid',
'search_field_between5' => 'grid',
'integrated_search_field13' => 'grid',
'search_field_between9' => 'grid',
'search_field_options1' => 'grid',
'search_field_options3' => 'grid',
'search_field_options5' => 'grid',
'search_field_options9' => 'grid',
'search_field_label1' => 'grid',
'search_field_label3' => 'grid',
'search_field_label5' => 'grid',
'search_field_label9' => 'grid' ),
'itemLocations' => array( 'integrated_search_field1' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'search_field_between' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field12' => array( 'location' => 'grid',
'cellId' => 'c' ),
'search_field_between8' => array( 'location' => 'grid',
'cellId' => 'c' ),
'integrated_search_field7' => array( 'location' => 'grid',
'cellId' => 'c4' ),
'search_field_between6' => array( 'location' => 'grid',
'cellId' => 'c4' ),
'integrated_search_field6' => array( 'location' => 'grid',
'cellId' => 'c5' ),
'search_field_between4' => array( 'location' => 'grid',
'cellId' => 'c5' ),
'integrated_search_field3' => array( 'location' => 'grid',
'cellId' => 'c6' ),
'search_field_between2' => array( 'location' => 'grid',
'cellId' => 'c6' ),
'integrated_search_field11' => array( 'location' => 'grid',
'cellId' => 'c9' ),
'search_field_between7' => array( 'location' => 'grid',
'cellId' => 'c9' ),
'search_field_label' => array( 'location' => 'grid',
'cellId' => 'c18' ),
'search_field_label2' => array( 'location' => 'grid',
'cellId' => 'c20' ),
'search_field_label4' => array( 'location' => 'grid',
'cellId' => 'c21' ),
'search_field_label6' => array( 'location' => 'grid',
'cellId' => 'c23' ),
'search_field_label7' => array( 'location' => 'grid',
'cellId' => 'c25' ),
'search_field_label8' => array( 'location' => 'grid',
'cellId' => 'c27' ),
'search_field_options' => array( 'location' => 'grid',
'cellId' => 'c36' ),
'search_field_options2' => array( 'location' => 'grid',
'cellId' => 'c38' ),
'search_field_options4' => array( 'location' => 'grid',
'cellId' => 'c39' ),
'search_field_options6' => array( 'location' => 'grid',
'cellId' => 'c41' ),
'search_field_options7' => array( 'location' => 'grid',
'cellId' => 'c43' ),
'search_field_options8' => array( 'location' => 'grid',
'cellId' => 'c45' ),
'integrated_search_field2' => array( 'location' => 'grid',
'cellId' => 'c54' ),
'search_field_between1' => array( 'location' => 'grid',
'cellId' => 'c54' ),
'integrated_search_field4' => array( 'location' => 'grid',
'cellId' => 'c57' ),
'search_field_between3' => array( 'location' => 'grid',
'cellId' => 'c57' ),
'integrated_search_field8' => array( 'location' => 'grid',
'cellId' => 'c59' ),
'search_field_between5' => array( 'location' => 'grid',
'cellId' => 'c59' ),
'integrated_search_field13' => array( 'location' => 'grid',
'cellId' => 'c63' ),
'search_field_between9' => array( 'location' => 'grid',
'cellId' => 'c63' ),
'search_field_options1' => array( 'location' => 'grid',
'cellId' => 'c72' ),
'search_field_options3' => array( 'location' => 'grid',
'cellId' => 'c75' ),
'search_field_options5' => array( 'location' => 'grid',
'cellId' => 'c77' ),
'search_field_options9' => array( 'location' => 'grid',
'cellId' => 'c81' ),
'search_field_label1' => array( 'location' => 'grid',
'cellId' => 'c90' ),
'search_field_label3' => array( 'location' => 'grid',
'cellId' => 'c93' ),
'search_field_label5' => array( 'location' => 'grid',
'cellId' => 'c95' ),
'search_field_label9' => array( 'location' => 'grid',
'cellId' => 'c99' ) ),
'itemVisiblity' => array( 'menu' => 3,
'loginform_login' => 3,
'username_button' => 3 ) ),
'itemsByType' => array( 'search_header' => array( 'search_header' ),
'search_reset' => array( 'search_reset' ),
'search_back_list' => array( 'search_back_list' ),
'search_search' => array( 'search_search' ),
'search_cancel' => array( 'search_cancel' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'logout_link' => array( 'logout_link' ),
'adminarea_link' => array( 'adminarea_link' ),
'search_field' => array( 'integrated_search_field1',
'integrated_search_field2',
'integrated_search_field3',
'integrated_search_field4',
'integrated_search_field6',
'integrated_search_field7',
'integrated_search_field8',
'integrated_search_field11',
'integrated_search_field12',
'integrated_search_field13' ),
'search_field_label' => array( 'search_field_label',
'search_field_label1',
'search_field_label2',
'search_field_label3',
'search_field_label4',
'search_field_label5',
'search_field_label6',
'search_field_label7',
'search_field_label8',
'search_field_label9' ),
'search_field_options' => array( 'search_field_options',
'search_field_options1',
'search_field_options2',
'search_field_options3',
'search_field_options4',
'search_field_options5',
'search_field_options6',
'search_field_options7',
'search_field_options8',
'search_field_options9' ),
'search_field_between' => array( 'search_field_between',
'search_field_between1',
'search_field_between2',
'search_field_between3',
'search_field_between4',
'search_field_between5',
'search_field_between6',
'search_field_between7',
'search_field_between8',
'search_field_between9' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c18' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array( 'dialerAgent_fieldblock' ),
'items' => array( 'search_field_label' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c36' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'search_field_options' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_search_field1',
'search_field_between' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c90' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array( 'dialerPhone_fieldblock' ),
'items' => array( 'search_field_label1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c72' => array( 'cols' => array( 4 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'search_field_options1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c54' => array( 'cols' => array( 5 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_search_field2',
'search_field_between1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c19' => array( 'cols' => array( 0,
1,
2,
3,
4,
5 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c20' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array( 'calldate_fieldblock' ),
'items' => array( 'search_field_label2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c38' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'search_field_options2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_search_field3',
'search_field_between2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c92' => array( 'cols' => array( 3 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c74' => array( 'cols' => array( 4 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c56' => array( 'cols' => array( 5 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c21' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array( 'callStatus_fieldblock' ),
'items' => array( 'search_field_label4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c39' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'search_field_options4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 2 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_search_field6',
'search_field_between4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c93' => array( 'cols' => array( 3 ),
'rows' => array( 3 ),
'tags' => array( 'denialReason_fieldblock' ),
'items' => array( 'search_field_label3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c75' => array( 'cols' => array( 4 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'search_field_options3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c57' => array( 'cols' => array( 5 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_search_field4',
'search_field_between3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c22' => array( 'cols' => array( 0,
1,
2,
3,
4,
5 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c23' => array( 'cols' => array( 0 ),
'rows' => array( 5 ),
'tags' => array( 'dialerCampaign_fieldblock' ),
'items' => array( 'search_field_label6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c41' => array( 'cols' => array( 1 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'search_field_options6' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 2 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'integrated_search_field7',
'search_field_between6' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c95' => array( 'cols' => array( 3 ),
'rows' => array( 5 ),
'tags' => array( 'dialerList_fieldblock' ),
'items' => array( 'search_field_label5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c77' => array( 'cols' => array( 4 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'search_field_options5' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c59' => array( 'cols' => array( 5 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'integrated_search_field8',
'search_field_between5' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c24' => array( 'cols' => array( 0,
1,
2,
3,
4,
5 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c25' => array( 'cols' => array( 0 ),
'rows' => array( 7 ),
'tags' => array( 'totalCallTime_fieldblock' ),
'items' => array( 'search_field_label7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c43' => array( 'cols' => array( 1 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array( 'search_field_options7' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c9' => array( 'cols' => array( 2 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array( 'integrated_search_field11',
'search_field_between7' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c97' => array( 'cols' => array( 3 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c79' => array( 'cols' => array( 4 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c61' => array( 'cols' => array( 5 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c26' => array( 'cols' => array( 0,
1,
2,
3,
4,
5 ),
'rows' => array( 8 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c27' => array( 'cols' => array( 0 ),
'rows' => array( 9 ),
'tags' => array( 'novaTotalApps_fieldblock' ),
'items' => array( 'search_field_label8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c45' => array( 'cols' => array( 1 ),
'rows' => array( 9 ),
'tags' => array(  ),
'items' => array( 'search_field_options8' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 2 ),
'rows' => array( 9 ),
'tags' => array(  ),
'items' => array( 'integrated_search_field12',
'search_field_between8' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c99' => array( 'cols' => array( 3 ),
'rows' => array( 9 ),
'tags' => array( 'voltonTotalApps_fieldblock' ),
'items' => array( 'search_field_label9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c81' => array( 'cols' => array( 4 ),
'rows' => array( 9 ),
'tags' => array(  ),
'items' => array( 'search_field_options9' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c63' => array( 'cols' => array( 5 ),
'rows' => array( 9 ),
'tags' => array(  ),
'items' => array( 'integrated_search_field13',
'search_field_between9' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 6,
'height' => 10 ) ) ),
'loginForm' => array( 'loginForm' => 1 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'search',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'search',
'type' => 'search',
'layoutId' => 'topbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'topbar-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ),
array( 'cell' => 'c3' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'logo' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'menu' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c3' => array( 'model' => 'c3',
'items' => array( 'loginform_login',
'username_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'search-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'search_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'search-above-grid',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'search-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'search_search',
'search_reset',
'search_back_list',
'search_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-search',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c18' ),
array( 'cell' => 'c36' ),
array( 'cell' => 'c3' ),
array( 'cell' => 'c90' ),
array( 'cell' => 'c72' ),
array( 'cell' => 'c54' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c19',
'colspan' => 6 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c20' ),
array( 'cell' => 'c38' ),
array( 'cell' => 'c6' ),
array( 'cell' => 'c92' ),
array( 'cell' => 'c74' ),
array( 'cell' => 'c56' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c21' ),
array( 'cell' => 'c39' ),
array( 'cell' => 'c5' ),
array( 'cell' => 'c93' ),
array( 'cell' => 'c75' ),
array( 'cell' => 'c57' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c22',
'colspan' => 6 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c23' ),
array( 'cell' => 'c41' ),
array( 'cell' => 'c4' ),
array( 'cell' => 'c95' ),
array( 'cell' => 'c77' ),
array( 'cell' => 'c59' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c24',
'colspan' => 6 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c25' ),
array( 'cell' => 'c43' ),
array( 'cell' => 'c9' ),
array( 'cell' => 'c97' ),
array( 'cell' => 'c79' ),
array( 'cell' => 'c61' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c26',
'colspan' => 6 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c27' ),
array( 'cell' => 'c45' ),
array( 'cell' => 'c' ),
array( 'cell' => 'c99' ),
array( 'cell' => 'c81' ),
array( 'cell' => 'c63' ) ) ) ),
'cells' => array( 'c3' => array( 'model' => 'c5',
'items' => array( 'integrated_search_field1',
'search_field_between' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'width' => '180px' ),
'c' => array( 'model' => 'c5',
'items' => array( 'integrated_search_field12',
'search_field_between8' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'width' => '180px' ),
'c4' => array( 'model' => 'c5',
'items' => array( 'integrated_search_field7',
'search_field_between6' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'width' => '180px' ),
'c5' => array( 'model' => 'c5',
'items' => array( 'integrated_search_field6',
'search_field_between4' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'width' => '180px' ),
'c6' => array( 'model' => 'c5',
'items' => array( 'integrated_search_field3',
'search_field_between2' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'width' => '180px' ),
'c9' => array( 'model' => 'c5',
'items' => array( 'integrated_search_field11',
'search_field_between7' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'width' => '180px' ),
'c18' => array( 'model' => 'c3',
'items' => array( 'search_field_label' ),
'align' => 'right' ),
'c19' => array( 'model' => 'c3',
'items' => array(  ),
'persistent' => true ),
'c20' => array( 'model' => 'c3',
'items' => array( 'search_field_label2' ),
'align' => 'right' ),
'c21' => array( 'model' => 'c3',
'items' => array( 'search_field_label4' ),
'align' => 'right' ),
'c22' => array( 'model' => 'c3',
'items' => array(  ),
'persistent' => true ),
'c23' => array( 'model' => 'c3',
'items' => array( 'search_field_label6' ),
'align' => 'right' ),
'c24' => array( 'model' => 'c3',
'items' => array(  ),
'persistent' => true ),
'c25' => array( 'model' => 'c3',
'items' => array( 'search_field_label7' ),
'align' => 'right' ),
'c26' => array( 'model' => 'c3',
'items' => array(  ),
'persistent' => true ),
'c27' => array( 'model' => 'c3',
'items' => array( 'search_field_label8' ),
'align' => 'right' ),
'c36' => array( 'model' => 'c3',
'items' => array( 'search_field_options' ) ),
'c38' => array( 'model' => 'c3',
'items' => array( 'search_field_options2' ) ),
'c39' => array( 'model' => 'c3',
'items' => array( 'search_field_options4' ) ),
'c41' => array( 'model' => 'c3',
'items' => array( 'search_field_options6' ) ),
'c43' => array( 'model' => 'c3',
'items' => array( 'search_field_options7' ) ),
'c45' => array( 'model' => 'c3',
'items' => array( 'search_field_options8' ) ),
'c54' => array( 'model' => 'c5',
'items' => array( 'integrated_search_field2',
'search_field_between1' ),
'width' => '180px' ),
'c56' => array( 'model' => 'c3',
'items' => array(  ),
'width' => '180px' ),
'c57' => array( 'model' => 'c5',
'items' => array( 'integrated_search_field4',
'search_field_between3' ),
'width' => '180px' ),
'c59' => array( 'model' => 'c5',
'items' => array( 'integrated_search_field8',
'search_field_between5' ),
'width' => '180px' ),
'c61' => array( 'model' => 'c3',
'items' => array(  ),
'width' => '180px' ),
'c63' => array( 'model' => 'c5',
'items' => array( 'integrated_search_field13',
'search_field_between9' ),
'width' => '180px' ),
'c72' => array( 'model' => 'c5',
'items' => array( 'search_field_options1' ) ),
'c74' => array( 'model' => 'c3',
'items' => array(  ) ),
'c75' => array( 'model' => 'c3',
'items' => array( 'search_field_options3' ) ),
'c77' => array( 'model' => 'c3',
'items' => array( 'search_field_options5' ) ),
'c79' => array( 'model' => 'c3',
'items' => array(  ) ),
'c81' => array( 'model' => 'c3',
'items' => array( 'search_field_options9' ) ),
'c90' => array( 'model' => 'c5',
'items' => array( 'search_field_label1' ),
'align' => 'right' ),
'c92' => array( 'model' => 'c3',
'items' => array(  ),
'align' => 'right' ),
'c93' => array( 'model' => 'c3',
'items' => array( 'search_field_label3' ),
'align' => 'right' ),
'c95' => array( 'model' => 'c3',
'items' => array( 'search_field_label5' ),
'align' => 'right' ),
'c97' => array( 'model' => 'c3',
'items' => array(  ),
'align' => 'right' ),
'c99' => array( 'model' => 'c3',
'items' => array( 'search_field_label9' ),
'align' => 'right' ) ),
'deferredItems' => array(  ),
'separateLabels' => false ) ),
'items' => array( 'search_header' => array( 'type' => 'search_header' ),
'search_reset' => array( 'type' => 'search_reset' ),
'search_back_list' => array( 'type' => 'search_back_list' ),
'search_search' => array( 'type' => 'search_search' ),
'search_cancel' => array( 'type' => 'search_cancel' ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'logout_link',
'adminarea_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => true ),
'logout_link' => array( 'type' => 'logout_link' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'integrated_search_field1' => array( 'field' => 'dialerAgent',
'type' => 'search_field',
'orientation' => 0,
'required' => false,
'joined' => false,
'separated' => true ),
'integrated_search_field2' => array( 'field' => 'dialerPhone',
'type' => 'search_field',
'orientation' => 0,
'required' => false,
'joined' => false,
'separated' => true ),
'integrated_search_field3' => array( 'field' => 'calldate',
'type' => 'search_field',
'orientation' => 0,
'required' => false,
'joined' => false,
'separated' => true ),
'integrated_search_field4' => array( 'field' => 'denialReason',
'type' => 'search_field',
'orientation' => 0,
'required' => false,
'joined' => false,
'separated' => true ),
'integrated_search_field6' => array( 'field' => 'callStatus',
'type' => 'search_field',
'orientation' => 0,
'required' => false,
'joined' => false,
'separated' => true ),
'integrated_search_field7' => array( 'field' => 'dialerCampaign',
'type' => 'search_field',
'orientation' => 0,
'required' => false,
'joined' => false,
'separated' => true ),
'integrated_search_field8' => array( 'field' => 'dialerList',
'type' => 'search_field',
'orientation' => 0,
'required' => false,
'joined' => false,
'separated' => true ),
'integrated_search_field11' => array( 'field' => 'totalCallTime',
'type' => 'search_field',
'orientation' => 0,
'required' => false,
'joined' => false,
'separated' => true ),
'integrated_search_field12' => array( 'field' => 'novaTotalApps',
'type' => 'search_field',
'orientation' => 0,
'required' => false,
'joined' => false,
'separated' => true ),
'integrated_search_field13' => array( 'field' => 'voltonTotalApps',
'type' => 'search_field',
'orientation' => 0,
'required' => false,
'joined' => false,
'separated' => true ),
'search_field_label' => array( 'type' => 'search_field_label',
'field' => 'dialerAgent',
'separated' => true ),
'search_field_options' => array( 'type' => 'search_field_options',
'field' => 'dialerAgent',
'separated' => true ),
'search_field_between' => array( 'type' => 'search_field_between',
'field' => 'dialerAgent',
'separated' => true ),
'search_field_label1' => array( 'type' => 'search_field_label',
'field' => 'dialerPhone',
'separated' => true ),
'search_field_options1' => array( 'type' => 'search_field_options',
'field' => 'dialerPhone',
'separated' => true ),
'search_field_between1' => array( 'type' => 'search_field_between',
'field' => 'dialerPhone',
'separated' => true ),
'search_field_label2' => array( 'type' => 'search_field_label',
'field' => 'calldate',
'separated' => true ),
'search_field_options2' => array( 'type' => 'search_field_options',
'field' => 'calldate',
'separated' => true ),
'search_field_between2' => array( 'type' => 'search_field_between',
'field' => 'calldate',
'separated' => true ),
'search_field_label3' => array( 'type' => 'search_field_label',
'field' => 'denialReason',
'separated' => true ),
'search_field_options3' => array( 'type' => 'search_field_options',
'field' => 'denialReason',
'separated' => true ),
'search_field_between3' => array( 'type' => 'search_field_between',
'field' => 'denialReason',
'separated' => true ),
'search_field_label4' => array( 'type' => 'search_field_label',
'field' => 'callStatus',
'separated' => true ),
'search_field_options4' => array( 'type' => 'search_field_options',
'field' => 'callStatus',
'separated' => true ),
'search_field_between4' => array( 'type' => 'search_field_between',
'field' => 'callStatus',
'separated' => true ),
'search_field_label5' => array( 'type' => 'search_field_label',
'field' => 'dialerList',
'separated' => true ),
'search_field_options5' => array( 'type' => 'search_field_options',
'field' => 'dialerList',
'separated' => true ),
'search_field_between5' => array( 'type' => 'search_field_between',
'field' => 'dialerList',
'separated' => true ),
'search_field_label6' => array( 'type' => 'search_field_label',
'field' => 'dialerCampaign',
'separated' => true ),
'search_field_options6' => array( 'type' => 'search_field_options',
'field' => 'dialerCampaign',
'separated' => true ),
'search_field_between6' => array( 'type' => 'search_field_between',
'field' => 'dialerCampaign',
'separated' => true ),
'search_field_label7' => array( 'type' => 'search_field_label',
'field' => 'totalCallTime',
'separated' => true ),
'search_field_options7' => array( 'type' => 'search_field_options',
'field' => 'totalCallTime',
'separated' => true ),
'search_field_between7' => array( 'type' => 'search_field_between',
'field' => 'totalCallTime',
'separated' => true ),
'search_field_label8' => array( 'type' => 'search_field_label',
'field' => 'novaTotalApps',
'separated' => true ),
'search_field_options8' => array( 'type' => 'search_field_options',
'field' => 'novaTotalApps',
'separated' => true ),
'search_field_between8' => array( 'type' => 'search_field_between',
'field' => 'novaTotalApps',
'separated' => true ),
'search_field_label9' => array( 'type' => 'search_field_label',
'field' => 'voltonTotalApps',
'separated' => true ),
'search_field_options9' => array( 'type' => 'search_field_options',
'field' => 'voltonTotalApps',
'separated' => true ),
'search_field_between9' => array( 'type' => 'search_field_between',
'field' => 'voltonTotalApps',
'separated' => true ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>