<?php
			$optionsArray = array( 'pdf' => array( 'pdfView' => false ),
'fields' => array( 'gridFields' => array( 'totalCallsCount',
'statusCallsCount',
'statusCallsPcnt',
'totalTalkTime',
'statusTalkTime',
'statustalkTimePcnt',
'totalTypingTime',
'statusTypingTime',
'statusTypingTimePcnt',
'statusCallTime',
'totalCallTime',
'statusCallTimePcnt' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'totalCallsCount' => array( 'report_grid_field5' ),
'statusCallsCount' => array( 'report_grid_field6' ),
'statusCallsPcnt' => array( 'report_grid_field7' ),
'totalTalkTime' => array( 'report_grid_field8' ),
'statusTalkTime' => array( 'report_grid_field9' ),
'statustalkTimePcnt' => array( 'report_grid_field10' ),
'totalTypingTime' => array( 'report_grid_field11' ),
'statusTypingTime' => array( 'report_grid_field12' ),
'statusTypingTimePcnt' => array( 'report_grid_field13' ),
'statusCallTime' => array( 'report_grid_field15' ),
'callStatus' => array( 'report_group_field1' ),
'totalCallTime' => array( 'report_grid_field' ),
'statusCallTimePcnt' => array( 'report_grid_field1' ),
'agent' => array( 'report_group_field' ),
'dialerCampaign' => array( 'report_group_field2' ),
'dialerList' => array( 'report_group_field3' ),
'callDate' => array( 'report_group_field4' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'top' => array( 'print_header',
'print_subheader' ),
'above-grid' => array( 'print_pages' ),
'below-grid' => array(  ),
'grid' => array( 'report_group_field',
'report_group_field1',
'report_group_field2',
'report_group_field3',
'report_group_field4',
'report_grid_field5',
'report_grid_field6',
'report_grid_field7',
'report_grid_field8',
'report_grid_field9',
'report_grid_field10',
'report_grid_field11',
'report_grid_field12',
'report_grid_field13',
'report_grid_field15',
'report_grid_field',
'report_grid_field1' ) ),
'formXtTags' => array( 'above-grid' => array( 'print_pages' ),
'below-grid' => array(  ) ),
'itemForms' => array( 'print_header' => 'top',
'print_subheader' => 'top',
'print_pages' => 'above-grid',
'report_group_field' => 'grid',
'report_group_field1' => 'grid',
'report_group_field2' => 'grid',
'report_group_field3' => 'grid',
'report_group_field4' => 'grid',
'report_grid_field5' => 'grid',
'report_grid_field6' => 'grid',
'report_grid_field7' => 'grid',
'report_grid_field8' => 'grid',
'report_grid_field9' => 'grid',
'report_grid_field10' => 'grid',
'report_grid_field11' => 'grid',
'report_grid_field12' => 'grid',
'report_grid_field13' => 'grid',
'report_grid_field15' => 'grid',
'report_grid_field' => 'grid',
'report_grid_field1' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'print_header' => array( 'print_header' ),
'print_subheader' => array( 'print_subheader' ),
'print_pages' => array( 'print_pages' ),
'report_grid_field' => array( 'report_grid_field5',
'report_grid_field6',
'report_grid_field7',
'report_grid_field8',
'report_grid_field9',
'report_grid_field10',
'report_grid_field11',
'report_grid_field12',
'report_grid_field13',
'report_grid_field15',
'report_grid_field',
'report_grid_field1' ),
'report_group_field' => array( 'report_group_field1',
'report_group_field',
'report_group_field2',
'report_group_field3',
'report_group_field4' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array( 'print_pages' => array( 'tag' => 'PRINT_PAGES',
'type' => 2 ) ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'rprint',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'rprint',
'type' => 'rprint',
'layoutId' => 'basic',
'disabled' => 0,
'default' => 0,
'forms' => array( 'top' => array( 'modelId' => 'print-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c2' => array( 'model' => 'c2',
'items' => array( 'print_header',
'print_subheader' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'print-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'print_pages' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'print-below-grid',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'report-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'report_group_field',
'report_group_field1',
'report_group_field2',
'report_group_field3',
'report_group_field4' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'report_grid_field5',
'report_grid_field6',
'report_grid_field7',
'report_grid_field8',
'report_grid_field9',
'report_grid_field10',
'report_grid_field11',
'report_grid_field12',
'report_grid_field13',
'report_grid_field15',
'report_grid_field',
'report_grid_field1' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'print_header' => array( 'type' => 'print_header' ),
'print_subheader' => array( 'type' => 'print_subheader' ),
'print_pages' => array( 'type' => 'print_pages' ),
'report_grid_field5' => array( 'field' => 'totalCallsCount',
'type' => 'report_grid_field' ),
'report_grid_field6' => array( 'field' => 'statusCallsCount',
'type' => 'report_grid_field' ),
'report_grid_field7' => array( 'field' => 'statusCallsPcnt',
'type' => 'report_grid_field' ),
'report_grid_field8' => array( 'field' => 'totalTalkTime',
'type' => 'report_grid_field' ),
'report_grid_field9' => array( 'field' => 'statusTalkTime',
'type' => 'report_grid_field' ),
'report_grid_field10' => array( 'field' => 'statustalkTimePcnt',
'type' => 'report_grid_field' ),
'report_grid_field11' => array( 'field' => 'totalTypingTime',
'type' => 'report_grid_field' ),
'report_grid_field12' => array( 'field' => 'statusTypingTime',
'type' => 'report_grid_field' ),
'report_grid_field13' => array( 'field' => 'statusTypingTimePcnt',
'type' => 'report_grid_field' ),
'report_grid_field15' => array( 'field' => 'statusCallTime',
'type' => 'report_grid_field' ),
'report_group_field1' => array( 'field' => 'callStatus',
'type' => 'report_group_field' ),
'report_grid_field' => array( 'field' => 'totalCallTime',
'type' => 'report_grid_field' ),
'report_grid_field1' => array( 'field' => 'statusCallTimePcnt',
'type' => 'report_grid_field' ),
'report_group_field' => array( 'field' => 'agent',
'type' => 'report_group_field' ),
'report_group_field2' => array( 'field' => 'dialerCampaign',
'type' => 'report_group_field' ),
'report_group_field3' => array( 'field' => 'dialerList',
'type' => 'report_group_field' ),
'report_group_field4' => array( 'field' => 'callDate',
'type' => 'report_group_field' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>