<?php
			$optionsArray = array( 'captcha' => array( 'captcha' => false ),
'fields' => array( 'gridFields' => array( 'applicationType',
'applicationStatusId',
'applicantName',
'applicantAddress',
'applicantArea',
'applicantPhone',
'applicantProfession',
'applicantTaxRegistrationNumber',
'legalName',
'contactName',
'contactEmail',
'mailAddress',
'powerAddress',
'powerPostalCode',
'powerCurrentSupplier',
'powerSupplyNumber',
'voltonPlan',
'voltonWarrantyAmount',
'voltonAutoPayment',
'voltonComments',
'document1',
'document2',
'document3',
'document4',
'document5',
'powerActivationStatus',
'applicantIdNumber',
'applicantPostalCode',
'applicantCity',
'applicantWorkPhone',
'applicantEmail',
'applicantTaxOffice',
'legalIdNumber',
'contactPhone',
'mailPostalCode',
'powerAgreedKw',
'powerArea',
'powerMeterNumber',
'voltonContractDuration',
'voltonWarrantyOnFirstBill',
'voltonOther',
'document6',
'document7',
'document8',
'document9',
'document10',
'powerOwnershipType',
'applicantMobile',
'applicantGemi',
'applicantKod',
'contactMobile',
'mailArea',
'mailCity',
'powerCity',
'powerCurrentDayMeter',
'powerCurrentNightMeter',
'document11',
'document12',
'document13',
'document14',
'document15',
'ngAddress',
'ngPostalCode',
'ngArea',
'ngCity',
'ngPressure',
'ngHourlyCapacity',
'ngHkasp',
'ngMeterNumber',
'ngMeterType',
'ngCurrentMeterValue',
'ngConnectionExists',
'ngSupplyIsNew',
'ngSupplyReactivation',
'applicationAgentStatus',
'applicationLastStatusDate',
'id',
'dialerList',
'dialerAgent',
'dialerRecording',
'orderShipCompany',
'orderInvoiceRequired',
'callComments',
'internalCommunication',
'callGdprAcceptance',
'callGdprRecordingAcceptance',
'orderPaymentMethod',
'Expr2',
'contactZipCode',
'contactCity',
'ContactArea',
'contactGender',
'contactAge',
'crmUser',
'pauseAfterCall',
'dialerPhone',
'dialerCampaign',
'productFamilyId',
'contactMethod',
'courier',
'deliveryComments',
'courierDeliveryDate',
'courierTimeFrom',
'courierTimeTo' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'applicationType' => array( 'integrated_edit_field' ),
'applicationStatusId' => array( 'integrated_edit_field3' ),
'applicantName' => array( 'integrated_edit_field6' ),
'applicantAddress' => array( 'integrated_edit_field9' ),
'applicantArea' => array( 'integrated_edit_field12' ),
'applicantPhone' => array( 'integrated_edit_field15' ),
'applicantProfession' => array( 'integrated_edit_field18' ),
'applicantTaxRegistrationNumber' => array( 'integrated_edit_field21' ),
'legalName' => array( 'integrated_edit_field24' ),
'contactName' => array( 'integrated_edit_field27' ),
'contactEmail' => array( 'integrated_edit_field30' ),
'mailAddress' => array( 'integrated_edit_field33' ),
'powerAddress' => array( 'integrated_edit_field36' ),
'powerPostalCode' => array( 'integrated_edit_field39' ),
'powerCurrentSupplier' => array( 'integrated_edit_field42' ),
'powerSupplyNumber' => array( 'integrated_edit_field45' ),
'voltonPlan' => array( 'integrated_edit_field48' ),
'voltonWarrantyAmount' => array( 'integrated_edit_field51' ),
'voltonAutoPayment' => array( 'integrated_edit_field54' ),
'voltonComments' => array( 'integrated_edit_field57' ),
'document1' => array( 'integrated_edit_field60' ),
'document2' => array( 'integrated_edit_field1' ),
'document3' => array( 'integrated_edit_field4' ),
'document4' => array( 'integrated_edit_field7' ),
'document5' => array( 'integrated_edit_field10' ),
'powerActivationStatus' => array( 'integrated_edit_field13' ),
'applicantIdNumber' => array( 'integrated_edit_field16' ),
'applicantPostalCode' => array( 'integrated_edit_field19' ),
'applicantCity' => array( 'integrated_edit_field22' ),
'applicantWorkPhone' => array( 'integrated_edit_field25' ),
'applicantEmail' => array( 'integrated_edit_field28' ),
'applicantTaxOffice' => array( 'integrated_edit_field31' ),
'legalIdNumber' => array( 'integrated_edit_field34' ),
'contactPhone' => array( 'integrated_edit_field37' ),
'mailPostalCode' => array( 'integrated_edit_field40' ),
'powerAgreedKw' => array( 'integrated_edit_field43' ),
'powerArea' => array( 'integrated_edit_field46' ),
'powerMeterNumber' => array( 'integrated_edit_field49' ),
'voltonContractDuration' => array( 'integrated_edit_field52' ),
'voltonWarrantyOnFirstBill' => array( 'integrated_edit_field55' ),
'voltonOther' => array( 'integrated_edit_field58' ),
'document6' => array( 'integrated_edit_field2' ),
'document7' => array( 'integrated_edit_field5' ),
'document8' => array( 'integrated_edit_field8' ),
'document9' => array( 'integrated_edit_field11' ),
'document10' => array( 'integrated_edit_field14' ),
'powerOwnershipType' => array( 'integrated_edit_field17' ),
'applicantMobile' => array( 'integrated_edit_field20' ),
'applicantGemi' => array( 'integrated_edit_field23' ),
'applicantKod' => array( 'integrated_edit_field26' ),
'contactMobile' => array( 'integrated_edit_field29' ),
'mailArea' => array( 'integrated_edit_field32' ),
'mailCity' => array( 'integrated_edit_field35' ),
'powerCity' => array( 'integrated_edit_field38' ),
'powerCurrentDayMeter' => array( 'integrated_edit_field41' ),
'powerCurrentNightMeter' => array( 'integrated_edit_field44' ),
'document11' => array( 'integrated_edit_field47' ),
'document12' => array( 'integrated_edit_field50' ),
'document13' => array( 'integrated_edit_field53' ),
'document14' => array( 'integrated_edit_field56' ),
'document15' => array( 'integrated_edit_field59' ),
'ngAddress' => array( 'integrated_edit_field61' ),
'ngPostalCode' => array( 'integrated_edit_field62' ),
'ngArea' => array( 'integrated_edit_field63' ),
'ngCity' => array( 'integrated_edit_field64' ),
'ngPressure' => array( 'integrated_edit_field65' ),
'ngHourlyCapacity' => array( 'integrated_edit_field66' ),
'ngHkasp' => array( 'integrated_edit_field67' ),
'ngMeterNumber' => array( 'integrated_edit_field69' ),
'ngMeterType' => array( 'integrated_edit_field70' ),
'ngCurrentMeterValue' => array( 'integrated_edit_field71' ),
'ngConnectionExists' => array( 'integrated_edit_field72' ),
'ngSupplyIsNew' => array( 'integrated_edit_field73' ),
'ngSupplyReactivation' => array( 'integrated_edit_field74' ),
'applicationAgentStatus' => array( 'integrated_edit_field68' ),
'applicationLastStatusDate' => array( 'integrated_edit_field75' ),
'id' => array( 'integrated_edit_field76' ),
'dialerList' => array( 'integrated_edit_field77' ),
'dialerAgent' => array( 'integrated_edit_field78' ),
'dialerRecording' => array( 'integrated_edit_field79' ),
'orderShipCompany' => array( 'integrated_edit_field80' ),
'orderInvoiceRequired' => array( 'integrated_edit_field81' ),
'callComments' => array( 'integrated_edit_field82' ),
'internalCommunication' => array( 'integrated_edit_field83' ),
'callGdprAcceptance' => array( 'integrated_edit_field84' ),
'callGdprRecordingAcceptance' => array( 'integrated_edit_field85' ),
'orderPaymentMethod' => array( 'integrated_edit_field86' ),
'Expr2' => array( 'integrated_edit_field87' ),
'contactZipCode' => array( 'integrated_edit_field88' ),
'contactCity' => array( 'integrated_edit_field89' ),
'ContactArea' => array( 'integrated_edit_field90' ),
'contactGender' => array( 'integrated_edit_field91' ),
'contactAge' => array( 'integrated_edit_field92' ),
'crmUser' => array( 'integrated_edit_field93' ),
'pauseAfterCall' => array( 'integrated_edit_field94' ),
'dialerPhone' => array( 'integrated_edit_field95' ),
'dialerCampaign' => array( 'integrated_edit_field96' ),
'productFamilyId' => array( 'integrated_edit_field97' ),
'contactMethod' => array( 'integrated_edit_field98' ),
'courier' => array( 'integrated_edit_field99' ),
'deliveryComments' => array( 'integrated_edit_field100' ),
'courierDeliveryDate' => array( 'integrated_edit_field101' ),
'courierTimeFrom' => array( 'integrated_edit_field102' ),
'courierTimeTo' => array( 'integrated_edit_field103' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array( 'logo',
'menu',
'loginform_login',
'username_button' ),
'top' => array( 'image',
'add_header' ),
'above-grid' => array(  ),
'below-grid' => array( 'add_save',
'add_back_list',
'add_cancel' ),
'grid' => array( 'integrated_edit_field6',
'integrated_edit_field16',
'integrated_edit_field12',
'integrated_edit_field22',
'integrated_edit_field9',
'integrated_edit_field19',
'integrated_edit_field21',
'integrated_edit_field31',
'integrated_edit_field26',
'integrated_edit_field18',
'integrated_edit_field28',
'integrated_edit_field23',
'integrated_edit_field15',
'integrated_edit_field25',
'integrated_edit_field20',
'integrated_edit_field27',
'integrated_edit_field37',
'integrated_edit_field29',
'text1',
'integrated_edit_field24',
'integrated_edit_field34',
'text',
'integrated_edit_field30',
'integrated_edit_field33',
'integrated_edit_field40',
'integrated_edit_field32',
'integrated_edit_field35',
'integrated_edit_field36',
'integrated_edit_field43',
'integrated_edit_field17',
'integrated_edit_field45',
'integrated_edit_field49',
'integrated_edit_field41',
'integrated_edit_field42',
'integrated_edit_field13',
'integrated_edit_field39',
'integrated_edit_field46',
'integrated_edit_field38',
'integrated_edit_field48',
'integrated_edit_field52',
'integrated_edit_field44',
'integrated_edit_field57',
'integrated_edit_field54',
'integrated_edit_field51',
'integrated_edit_field55',
'integrated_edit_field58',
'text3',
'text2',
'text4',
'text6',
'text5',
'integrated_edit_field',
'integrated_edit_field3',
'integrated_edit_field68',
'integrated_edit_field10',
'integrated_edit_field14',
'integrated_edit_field59',
'integrated_edit_field7',
'integrated_edit_field11',
'integrated_edit_field56',
'integrated_edit_field4',
'integrated_edit_field8',
'integrated_edit_field53',
'integrated_edit_field1',
'integrated_edit_field5',
'integrated_edit_field50',
'integrated_edit_field60',
'integrated_edit_field2',
'integrated_edit_field47',
'details_preview',
'integrated_edit_field67',
'text7',
'integrated_edit_field66',
'integrated_edit_field65',
'integrated_edit_field64',
'integrated_edit_field63',
'integrated_edit_field61',
'integrated_edit_field62',
'integrated_edit_field69',
'integrated_edit_field70',
'integrated_edit_field71',
'integrated_edit_field72',
'integrated_edit_field73',
'integrated_edit_field74',
'integrated_edit_field75',
'integrated_edit_field78',
'integrated_edit_field81',
'integrated_edit_field84',
'integrated_edit_field87',
'integrated_edit_field90',
'integrated_edit_field93',
'integrated_edit_field96',
'integrated_edit_field99',
'integrated_edit_field102',
'integrated_edit_field76',
'integrated_edit_field79',
'integrated_edit_field82',
'integrated_edit_field85',
'integrated_edit_field88',
'integrated_edit_field91',
'integrated_edit_field94',
'integrated_edit_field97',
'integrated_edit_field100',
'integrated_edit_field103',
'integrated_edit_field77',
'integrated_edit_field80',
'integrated_edit_field83',
'integrated_edit_field86',
'integrated_edit_field89',
'integrated_edit_field92',
'integrated_edit_field95',
'integrated_edit_field98',
'integrated_edit_field101' ) ),
'formXtTags' => array( 'above-grid' => array(  ) ),
'itemForms' => array( 'logo' => 'supertop',
'menu' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'image' => 'top',
'add_header' => 'top',
'add_save' => 'below-grid',
'add_back_list' => 'below-grid',
'add_cancel' => 'below-grid',
'integrated_edit_field6' => 'grid',
'integrated_edit_field16' => 'grid',
'integrated_edit_field12' => 'grid',
'integrated_edit_field22' => 'grid',
'integrated_edit_field9' => 'grid',
'integrated_edit_field19' => 'grid',
'integrated_edit_field21' => 'grid',
'integrated_edit_field31' => 'grid',
'integrated_edit_field26' => 'grid',
'integrated_edit_field18' => 'grid',
'integrated_edit_field28' => 'grid',
'integrated_edit_field23' => 'grid',
'integrated_edit_field15' => 'grid',
'integrated_edit_field25' => 'grid',
'integrated_edit_field20' => 'grid',
'integrated_edit_field27' => 'grid',
'integrated_edit_field37' => 'grid',
'integrated_edit_field29' => 'grid',
'text1' => 'grid',
'integrated_edit_field24' => 'grid',
'integrated_edit_field34' => 'grid',
'text' => 'grid',
'integrated_edit_field30' => 'grid',
'integrated_edit_field33' => 'grid',
'integrated_edit_field40' => 'grid',
'integrated_edit_field32' => 'grid',
'integrated_edit_field35' => 'grid',
'integrated_edit_field36' => 'grid',
'integrated_edit_field43' => 'grid',
'integrated_edit_field17' => 'grid',
'integrated_edit_field45' => 'grid',
'integrated_edit_field49' => 'grid',
'integrated_edit_field41' => 'grid',
'integrated_edit_field42' => 'grid',
'integrated_edit_field13' => 'grid',
'integrated_edit_field39' => 'grid',
'integrated_edit_field46' => 'grid',
'integrated_edit_field38' => 'grid',
'integrated_edit_field48' => 'grid',
'integrated_edit_field52' => 'grid',
'integrated_edit_field44' => 'grid',
'integrated_edit_field57' => 'grid',
'integrated_edit_field54' => 'grid',
'integrated_edit_field51' => 'grid',
'integrated_edit_field55' => 'grid',
'integrated_edit_field58' => 'grid',
'text3' => 'grid',
'text2' => 'grid',
'text4' => 'grid',
'text6' => 'grid',
'text5' => 'grid',
'integrated_edit_field' => 'grid',
'integrated_edit_field3' => 'grid',
'integrated_edit_field68' => 'grid',
'integrated_edit_field10' => 'grid',
'integrated_edit_field14' => 'grid',
'integrated_edit_field59' => 'grid',
'integrated_edit_field7' => 'grid',
'integrated_edit_field11' => 'grid',
'integrated_edit_field56' => 'grid',
'integrated_edit_field4' => 'grid',
'integrated_edit_field8' => 'grid',
'integrated_edit_field53' => 'grid',
'integrated_edit_field1' => 'grid',
'integrated_edit_field5' => 'grid',
'integrated_edit_field50' => 'grid',
'integrated_edit_field60' => 'grid',
'integrated_edit_field2' => 'grid',
'integrated_edit_field47' => 'grid',
'details_preview' => 'grid',
'integrated_edit_field67' => 'grid',
'text7' => 'grid',
'integrated_edit_field66' => 'grid',
'integrated_edit_field65' => 'grid',
'integrated_edit_field64' => 'grid',
'integrated_edit_field63' => 'grid',
'integrated_edit_field61' => 'grid',
'integrated_edit_field62' => 'grid',
'integrated_edit_field69' => 'grid',
'integrated_edit_field70' => 'grid',
'integrated_edit_field71' => 'grid',
'integrated_edit_field72' => 'grid',
'integrated_edit_field73' => 'grid',
'integrated_edit_field74' => 'grid',
'integrated_edit_field75' => 'grid',
'integrated_edit_field78' => 'grid',
'integrated_edit_field81' => 'grid',
'integrated_edit_field84' => 'grid',
'integrated_edit_field87' => 'grid',
'integrated_edit_field90' => 'grid',
'integrated_edit_field93' => 'grid',
'integrated_edit_field96' => 'grid',
'integrated_edit_field99' => 'grid',
'integrated_edit_field102' => 'grid',
'integrated_edit_field76' => 'grid',
'integrated_edit_field79' => 'grid',
'integrated_edit_field82' => 'grid',
'integrated_edit_field85' => 'grid',
'integrated_edit_field88' => 'grid',
'integrated_edit_field91' => 'grid',
'integrated_edit_field94' => 'grid',
'integrated_edit_field97' => 'grid',
'integrated_edit_field100' => 'grid',
'integrated_edit_field103' => 'grid',
'integrated_edit_field77' => 'grid',
'integrated_edit_field80' => 'grid',
'integrated_edit_field83' => 'grid',
'integrated_edit_field86' => 'grid',
'integrated_edit_field89' => 'grid',
'integrated_edit_field92' => 'grid',
'integrated_edit_field95' => 'grid',
'integrated_edit_field98' => 'grid',
'integrated_edit_field101' => 'grid' ),
'itemLocations' => array( 'integrated_edit_field6' => array( 'location' => 'grid',
'cellId' => 'c11' ),
'integrated_edit_field16' => array( 'location' => 'grid',
'cellId' => 'c12' ),
'integrated_edit_field12' => array( 'location' => 'grid',
'cellId' => 'c14' ),
'integrated_edit_field22' => array( 'location' => 'grid',
'cellId' => 'c15' ),
'integrated_edit_field9' => array( 'location' => 'grid',
'cellId' => 'c17' ),
'integrated_edit_field19' => array( 'location' => 'grid',
'cellId' => 'c18' ),
'integrated_edit_field21' => array( 'location' => 'grid',
'cellId' => 'c23' ),
'integrated_edit_field31' => array( 'location' => 'grid',
'cellId' => 'c24' ),
'integrated_edit_field26' => array( 'location' => 'grid',
'cellId' => 'c25' ),
'integrated_edit_field18' => array( 'location' => 'grid',
'cellId' => 'c26' ),
'integrated_edit_field28' => array( 'location' => 'grid',
'cellId' => 'c27' ),
'integrated_edit_field23' => array( 'location' => 'grid',
'cellId' => 'c28' ),
'integrated_edit_field15' => array( 'location' => 'grid',
'cellId' => 'c29' ),
'integrated_edit_field25' => array( 'location' => 'grid',
'cellId' => 'c30' ),
'integrated_edit_field20' => array( 'location' => 'grid',
'cellId' => 'c31' ),
'integrated_edit_field27' => array( 'location' => 'grid',
'cellId' => 'c32' ),
'integrated_edit_field37' => array( 'location' => 'grid',
'cellId' => 'c33' ),
'integrated_edit_field29' => array( 'location' => 'grid',
'cellId' => 'c34' ),
'text1' => array( 'location' => 'grid',
'cellId' => 'c36' ),
'integrated_edit_field24' => array( 'location' => 'grid',
'cellId' => 'c38' ),
'integrated_edit_field34' => array( 'location' => 'grid',
'cellId' => 'c39' ),
'text' => array( 'location' => 'grid',
'cellId' => 'c41' ),
'integrated_edit_field30' => array( 'location' => 'grid',
'cellId' => 'c46' ),
'integrated_edit_field33' => array( 'location' => 'grid',
'cellId' => 'c47' ),
'integrated_edit_field40' => array( 'location' => 'grid',
'cellId' => 'c48' ),
'integrated_edit_field32' => array( 'location' => 'grid',
'cellId' => 'c49' ),
'integrated_edit_field35' => array( 'location' => 'grid',
'cellId' => 'c55' ),
'integrated_edit_field36' => array( 'location' => 'grid',
'cellId' => 'c56' ),
'integrated_edit_field43' => array( 'location' => 'grid',
'cellId' => 'c57' ),
'integrated_edit_field17' => array( 'location' => 'grid',
'cellId' => 'c58' ),
'integrated_edit_field45' => array( 'location' => 'grid',
'cellId' => 'c62' ),
'integrated_edit_field49' => array( 'location' => 'grid',
'cellId' => 'c63' ),
'integrated_edit_field41' => array( 'location' => 'grid',
'cellId' => 'c64' ),
'integrated_edit_field42' => array( 'location' => 'grid',
'cellId' => 'c65' ),
'integrated_edit_field13' => array( 'location' => 'grid',
'cellId' => 'c66' ),
'integrated_edit_field39' => array( 'location' => 'grid',
'cellId' => 'c68' ),
'integrated_edit_field46' => array( 'location' => 'grid',
'cellId' => 'c69' ),
'integrated_edit_field38' => array( 'location' => 'grid',
'cellId' => 'c70' ),
'integrated_edit_field48' => array( 'location' => 'grid',
'cellId' => 'c71' ),
'integrated_edit_field52' => array( 'location' => 'grid',
'cellId' => 'c72' ),
'integrated_edit_field44' => array( 'location' => 'grid',
'cellId' => 'c79' ),
'integrated_edit_field57' => array( 'location' => 'grid',
'cellId' => 'c80' ),
'integrated_edit_field54' => array( 'location' => 'grid',
'cellId' => 'c83' ),
'integrated_edit_field51' => array( 'location' => 'grid',
'cellId' => 'c86' ),
'integrated_edit_field55' => array( 'location' => 'grid',
'cellId' => 'c87' ),
'integrated_edit_field58' => array( 'location' => 'grid',
'cellId' => 'c88' ),
'text3' => array( 'location' => 'grid',
'cellId' => 'c8' ),
'text2' => array( 'location' => 'grid',
'cellId' => 'c52' ),
'text4' => array( 'location' => 'grid',
'cellId' => 'c75' ),
'text6' => array( 'location' => 'grid',
'cellId' => 'c91' ),
'text5' => array( 'location' => 'grid',
'cellId' => 'c94' ),
'integrated_edit_field' => array( 'location' => 'grid',
'cellId' => 'c59' ),
'integrated_edit_field3' => array( 'location' => 'grid',
'cellId' => 'c89' ),
'integrated_edit_field68' => array( 'location' => 'grid',
'cellId' => 'c97' ),
'integrated_edit_field10' => array( 'location' => 'grid',
'cellId' => 'c101' ),
'integrated_edit_field14' => array( 'location' => 'grid',
'cellId' => 'c102' ),
'integrated_edit_field59' => array( 'location' => 'grid',
'cellId' => 'c103' ),
'integrated_edit_field7' => array( 'location' => 'grid',
'cellId' => 'c104' ),
'integrated_edit_field11' => array( 'location' => 'grid',
'cellId' => 'c105' ),
'integrated_edit_field56' => array( 'location' => 'grid',
'cellId' => 'c106' ),
'integrated_edit_field4' => array( 'location' => 'grid',
'cellId' => 'c107' ),
'integrated_edit_field8' => array( 'location' => 'grid',
'cellId' => 'c108' ),
'integrated_edit_field53' => array( 'location' => 'grid',
'cellId' => 'c109' ),
'integrated_edit_field1' => array( 'location' => 'grid',
'cellId' => 'c110' ),
'integrated_edit_field5' => array( 'location' => 'grid',
'cellId' => 'c111' ),
'integrated_edit_field50' => array( 'location' => 'grid',
'cellId' => 'c112' ),
'integrated_edit_field60' => array( 'location' => 'grid',
'cellId' => 'c113' ),
'integrated_edit_field2' => array( 'location' => 'grid',
'cellId' => 'c114' ),
'integrated_edit_field47' => array( 'location' => 'grid',
'cellId' => 'c115' ),
'details_preview' => array( 'location' => 'grid',
'cellId' => 'c7' ),
'integrated_edit_field67' => array( 'location' => 'grid',
'cellId' => 'c9' ),
'text7' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_edit_field66' => array( 'location' => 'grid',
'cellId' => 'c35' ),
'integrated_edit_field65' => array( 'location' => 'grid',
'cellId' => 'c130' ),
'integrated_edit_field64' => array( 'location' => 'grid',
'cellId' => 'c133' ),
'integrated_edit_field63' => array( 'location' => 'grid',
'cellId' => 'c134' ),
'integrated_edit_field61' => array( 'location' => 'grid',
'cellId' => 'c136' ),
'integrated_edit_field62' => array( 'location' => 'grid',
'cellId' => 'c137' ),
'integrated_edit_field69' => array( 'location' => 'grid',
'cellId' => 'c139' ),
'integrated_edit_field70' => array( 'location' => 'grid',
'cellId' => 'c140' ),
'integrated_edit_field71' => array( 'location' => 'grid',
'cellId' => 'c141' ),
'integrated_edit_field72' => array( 'location' => 'grid',
'cellId' => 'c142' ),
'integrated_edit_field73' => array( 'location' => 'grid',
'cellId' => 'c143' ),
'integrated_edit_field74' => array( 'location' => 'grid',
'cellId' => 'c144' ),
'integrated_edit_field75' => array( 'location' => 'grid',
'cellId' => 'c6' ),
'integrated_edit_field78' => array( 'location' => 'grid',
'cellId' => 'c6' ),
'integrated_edit_field81' => array( 'location' => 'grid',
'cellId' => 'c6' ),
'integrated_edit_field84' => array( 'location' => 'grid',
'cellId' => 'c6' ),
'integrated_edit_field87' => array( 'location' => 'grid',
'cellId' => 'c6' ),
'integrated_edit_field90' => array( 'location' => 'grid',
'cellId' => 'c6' ),
'integrated_edit_field93' => array( 'location' => 'grid',
'cellId' => 'c6' ),
'integrated_edit_field96' => array( 'location' => 'grid',
'cellId' => 'c6' ),
'integrated_edit_field99' => array( 'location' => 'grid',
'cellId' => 'c6' ),
'integrated_edit_field102' => array( 'location' => 'grid',
'cellId' => 'c6' ),
'integrated_edit_field76' => array( 'location' => 'grid',
'cellId' => 'c148' ),
'integrated_edit_field79' => array( 'location' => 'grid',
'cellId' => 'c148' ),
'integrated_edit_field82' => array( 'location' => 'grid',
'cellId' => 'c148' ),
'integrated_edit_field85' => array( 'location' => 'grid',
'cellId' => 'c148' ),
'integrated_edit_field88' => array( 'location' => 'grid',
'cellId' => 'c148' ),
'integrated_edit_field91' => array( 'location' => 'grid',
'cellId' => 'c148' ),
'integrated_edit_field94' => array( 'location' => 'grid',
'cellId' => 'c148' ),
'integrated_edit_field97' => array( 'location' => 'grid',
'cellId' => 'c148' ),
'integrated_edit_field100' => array( 'location' => 'grid',
'cellId' => 'c148' ),
'integrated_edit_field103' => array( 'location' => 'grid',
'cellId' => 'c148' ),
'integrated_edit_field77' => array( 'location' => 'grid',
'cellId' => 'c149' ),
'integrated_edit_field80' => array( 'location' => 'grid',
'cellId' => 'c149' ),
'integrated_edit_field83' => array( 'location' => 'grid',
'cellId' => 'c149' ),
'integrated_edit_field86' => array( 'location' => 'grid',
'cellId' => 'c149' ),
'integrated_edit_field89' => array( 'location' => 'grid',
'cellId' => 'c149' ),
'integrated_edit_field92' => array( 'location' => 'grid',
'cellId' => 'c149' ),
'integrated_edit_field95' => array( 'location' => 'grid',
'cellId' => 'c149' ),
'integrated_edit_field98' => array( 'location' => 'grid',
'cellId' => 'c149' ),
'integrated_edit_field101' => array( 'location' => 'grid',
'cellId' => 'c149' ) ),
'itemVisiblity' => array( 'menu' => 3,
'loginform_login' => 3,
'username_button' => 3 ) ),
'itemsByType' => array( 'add_header' => array( 'add_header' ),
'image' => array( 'image' ),
'add_save' => array( 'add_save' ),
'add_back_list' => array( 'add_back_list' ),
'add_cancel' => array( 'add_cancel' ),
'details_preview' => array( 'details_preview' ),
'text' => array( 'text2',
'text',
'text1',
'text3',
'text4',
'text5',
'text6',
'text7' ),
'integrated_edit_field' => array( 'integrated_edit_field',
'integrated_edit_field3',
'integrated_edit_field6',
'integrated_edit_field9',
'integrated_edit_field12',
'integrated_edit_field15',
'integrated_edit_field18',
'integrated_edit_field21',
'integrated_edit_field24',
'integrated_edit_field27',
'integrated_edit_field30',
'integrated_edit_field33',
'integrated_edit_field36',
'integrated_edit_field39',
'integrated_edit_field42',
'integrated_edit_field45',
'integrated_edit_field48',
'integrated_edit_field51',
'integrated_edit_field54',
'integrated_edit_field57',
'integrated_edit_field60',
'integrated_edit_field1',
'integrated_edit_field4',
'integrated_edit_field7',
'integrated_edit_field10',
'integrated_edit_field13',
'integrated_edit_field16',
'integrated_edit_field19',
'integrated_edit_field22',
'integrated_edit_field25',
'integrated_edit_field28',
'integrated_edit_field31',
'integrated_edit_field34',
'integrated_edit_field37',
'integrated_edit_field40',
'integrated_edit_field43',
'integrated_edit_field46',
'integrated_edit_field49',
'integrated_edit_field52',
'integrated_edit_field55',
'integrated_edit_field58',
'integrated_edit_field2',
'integrated_edit_field5',
'integrated_edit_field8',
'integrated_edit_field11',
'integrated_edit_field14',
'integrated_edit_field17',
'integrated_edit_field20',
'integrated_edit_field23',
'integrated_edit_field26',
'integrated_edit_field29',
'integrated_edit_field32',
'integrated_edit_field35',
'integrated_edit_field38',
'integrated_edit_field41',
'integrated_edit_field44',
'integrated_edit_field47',
'integrated_edit_field50',
'integrated_edit_field53',
'integrated_edit_field56',
'integrated_edit_field59',
'integrated_edit_field61',
'integrated_edit_field62',
'integrated_edit_field63',
'integrated_edit_field64',
'integrated_edit_field65',
'integrated_edit_field66',
'integrated_edit_field67',
'integrated_edit_field69',
'integrated_edit_field70',
'integrated_edit_field71',
'integrated_edit_field72',
'integrated_edit_field73',
'integrated_edit_field74',
'integrated_edit_field68',
'integrated_edit_field75',
'integrated_edit_field76',
'integrated_edit_field77',
'integrated_edit_field78',
'integrated_edit_field79',
'integrated_edit_field80',
'integrated_edit_field81',
'integrated_edit_field82',
'integrated_edit_field83',
'integrated_edit_field84',
'integrated_edit_field85',
'integrated_edit_field86',
'integrated_edit_field87',
'integrated_edit_field88',
'integrated_edit_field89',
'integrated_edit_field90',
'integrated_edit_field91',
'integrated_edit_field92',
'integrated_edit_field93',
'integrated_edit_field94',
'integrated_edit_field95',
'integrated_edit_field96',
'integrated_edit_field97',
'integrated_edit_field98',
'integrated_edit_field99',
'integrated_edit_field100',
'integrated_edit_field101',
'integrated_edit_field102',
'integrated_edit_field103' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'logout_link' => array( 'logout_link' ),
'adminarea_link' => array( 'adminarea_link' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c59' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c89' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c97' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field68' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'text3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c21' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c22' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c11' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field6' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c12' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field16' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c13' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c17' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field9' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c18' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field19' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c19' => array( 'cols' => array( 2 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c14' => array( 'cols' => array( 0 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field12' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c15' => array( 'cols' => array( 1 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field22' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c16' => array( 'cols' => array( 2 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c29' => array( 'cols' => array( 0 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field15' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c30' => array( 'cols' => array( 1 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field25' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c31' => array( 'cols' => array( 2 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field20' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c26' => array( 'cols' => array( 0 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field18' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c27' => array( 'cols' => array( 1 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field28' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c28' => array( 'cols' => array( 2 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field23' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c23' => array( 'cols' => array( 0 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field21' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c24' => array( 'cols' => array( 1 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field31' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c25' => array( 'cols' => array( 2 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field26' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c36' => array( 'cols' => array( 0 ),
'rows' => array( 8 ),
'tags' => array(  ),
'items' => array( 'text1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c37' => array( 'cols' => array( 1 ),
'rows' => array( 8 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c42' => array( 'cols' => array( 2 ),
'rows' => array( 8 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c38' => array( 'cols' => array( 0 ),
'rows' => array( 9 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field24' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c39' => array( 'cols' => array( 1 ),
'rows' => array( 9 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field34' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c40' => array( 'cols' => array( 2 ),
'rows' => array( 9 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c50' => array( 'cols' => array( 0 ),
'rows' => array( 10 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c123' => array( 'cols' => array( 1 ),
'rows' => array( 10 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c124' => array( 'cols' => array( 2 ),
'rows' => array( 10 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c41' => array( 'cols' => array( 0 ),
'rows' => array( 11 ),
'tags' => array(  ),
'items' => array( 'text' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c43' => array( 'cols' => array( 1 ),
'rows' => array( 11 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c51' => array( 'cols' => array( 2 ),
'rows' => array( 11 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c32' => array( 'cols' => array( 0 ),
'rows' => array( 12 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field27' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c33' => array( 'cols' => array( 1 ),
'rows' => array( 12 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field37' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c34' => array( 'cols' => array( 2 ),
'rows' => array( 12 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field29' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c44' => array( 'cols' => array( 0 ),
'rows' => array( 13 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c45' => array( 'cols' => array( 1 ),
'rows' => array( 13 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c46' => array( 'cols' => array( 2 ),
'rows' => array( 13 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field30' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c74' => array( 'cols' => array( 0 ),
'rows' => array( 14 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c121' => array( 'cols' => array( 1 ),
'rows' => array( 14 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c122' => array( 'cols' => array( 2 ),
'rows' => array( 14 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c52' => array( 'cols' => array( 0 ),
'rows' => array( 15 ),
'tags' => array(  ),
'items' => array( 'text2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c60' => array( 'cols' => array( 1 ),
'rows' => array( 15 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c61' => array( 'cols' => array( 2 ),
'rows' => array( 15 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c47' => array( 'cols' => array( 0 ),
'rows' => array( 16 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field33' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c48' => array( 'cols' => array( 1 ),
'rows' => array( 16 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field40' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c49' => array( 'cols' => array( 2 ),
'rows' => array( 16 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field32' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c53' => array( 'cols' => array( 0 ),
'rows' => array( 17 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c54' => array( 'cols' => array( 1 ),
'rows' => array( 17 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c55' => array( 'cols' => array( 2 ),
'rows' => array( 17 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field35' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c118' => array( 'cols' => array( 0 ),
'rows' => array( 18 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c119' => array( 'cols' => array( 1 ),
'rows' => array( 18 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c120' => array( 'cols' => array( 2 ),
'rows' => array( 18 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c75' => array( 'cols' => array( 0 ),
'rows' => array( 19 ),
'tags' => array(  ),
'items' => array( 'text4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c76' => array( 'cols' => array( 1 ),
'rows' => array( 19 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c90' => array( 'cols' => array( 2 ),
'rows' => array( 19 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c56' => array( 'cols' => array( 0 ),
'rows' => array( 20 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field36' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c57' => array( 'cols' => array( 1 ),
'rows' => array( 20 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field43' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c58' => array( 'cols' => array( 2 ),
'rows' => array( 20 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field17' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c68' => array( 'cols' => array( 0 ),
'rows' => array( 21 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field39' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c69' => array( 'cols' => array( 1 ),
'rows' => array( 21 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field46' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c70' => array( 'cols' => array( 2 ),
'rows' => array( 21 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field38' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c65' => array( 'cols' => array( 0 ),
'rows' => array( 22 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field42' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c66' => array( 'cols' => array( 1 ),
'rows' => array( 22 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field13' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c67' => array( 'cols' => array( 2 ),
'rows' => array( 22 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c62' => array( 'cols' => array( 0 ),
'rows' => array( 23 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field45' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c63' => array( 'cols' => array( 1 ),
'rows' => array( 23 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field49' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c64' => array( 'cols' => array( 2 ),
'rows' => array( 23 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field41' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c77' => array( 'cols' => array( 0 ),
'rows' => array( 24 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c78' => array( 'cols' => array( 1 ),
'rows' => array( 24 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c79' => array( 'cols' => array( 2 ),
'rows' => array( 24 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field44' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 0 ),
'rows' => array( 25 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c116' => array( 'cols' => array( 1 ),
'rows' => array( 25 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c117' => array( 'cols' => array( 2 ),
'rows' => array( 25 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c1' => array( 'cols' => array( 0,
1,
2 ),
'rows' => array( 26 ),
'tags' => array(  ),
'items' => array( 'text7' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c136' => array( 'cols' => array( 0 ),
'rows' => array( 27 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field61' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c137' => array( 'cols' => array( 1 ),
'rows' => array( 27 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field62' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c138' => array( 'cols' => array( 2 ),
'rows' => array( 27 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c133' => array( 'cols' => array( 0 ),
'rows' => array( 28 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field64' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c134' => array( 'cols' => array( 1 ),
'rows' => array( 28 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field63' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c135' => array( 'cols' => array( 2 ),
'rows' => array( 28 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c130' => array( 'cols' => array( 0 ),
'rows' => array( 29 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field65' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c131' => array( 'cols' => array( 1 ),
'rows' => array( 29 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c132' => array( 'cols' => array( 2 ),
'rows' => array( 29 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c35' => array( 'cols' => array( 0 ),
'rows' => array( 30 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field66' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c128' => array( 'cols' => array( 1 ),
'rows' => array( 30 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c129' => array( 'cols' => array( 2 ),
'rows' => array( 30 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c9' => array( 'cols' => array( 0 ),
'rows' => array( 31 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field67' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c10' => array( 'cols' => array( 1 ),
'rows' => array( 31 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c20' => array( 'cols' => array( 2 ),
'rows' => array( 31 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c139' => array( 'cols' => array( 0 ),
'rows' => array( 32 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field69' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c140' => array( 'cols' => array( 1 ),
'rows' => array( 32 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field70' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c141' => array( 'cols' => array( 2 ),
'rows' => array( 32 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field71' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c142' => array( 'cols' => array( 0 ),
'rows' => array( 33 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c143' => array( 'cols' => array( 1 ),
'rows' => array( 33 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field73' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c144' => array( 'cols' => array( 2 ),
'rows' => array( 33 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field74' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c145' => array( 'cols' => array( 0 ),
'rows' => array( 34 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c146' => array( 'cols' => array( 1 ),
'rows' => array( 34 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c147' => array( 'cols' => array( 2 ),
'rows' => array( 34 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c91' => array( 'cols' => array( 0 ),
'rows' => array( 35 ),
'tags' => array(  ),
'items' => array( 'text6' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c92' => array( 'cols' => array( 1 ),
'rows' => array( 35 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c93' => array( 'cols' => array( 2 ),
'rows' => array( 35 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c71' => array( 'cols' => array( 0 ),
'rows' => array( 36 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field48' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c72' => array( 'cols' => array( 1 ),
'rows' => array( 36 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field52' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c73' => array( 'cols' => array( 2 ),
'rows' => array( 36 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c86' => array( 'cols' => array( 0 ),
'rows' => array( 37 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field51' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c87' => array( 'cols' => array( 1 ),
'rows' => array( 37 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field55' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c88' => array( 'cols' => array( 2 ),
'rows' => array( 37 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field58' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c83' => array( 'cols' => array( 0 ),
'rows' => array( 38 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field54' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c84' => array( 'cols' => array( 1 ),
'rows' => array( 38 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c85' => array( 'cols' => array( 2 ),
'rows' => array( 38 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c80' => array( 'cols' => array( 0 ),
'rows' => array( 39 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field57' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c81' => array( 'cols' => array( 1 ),
'rows' => array( 39 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c82' => array( 'cols' => array( 2 ),
'rows' => array( 39 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c94' => array( 'cols' => array( 0 ),
'rows' => array( 40 ),
'tags' => array(  ),
'items' => array( 'text5' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c95' => array( 'cols' => array( 1 ),
'rows' => array( 40 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c96' => array( 'cols' => array( 2 ),
'rows' => array( 40 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c113' => array( 'cols' => array( 0 ),
'rows' => array( 41 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field60' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c114' => array( 'cols' => array( 1 ),
'rows' => array( 41 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c115' => array( 'cols' => array( 2 ),
'rows' => array( 41 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field47' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c110' => array( 'cols' => array( 0 ),
'rows' => array( 42 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c111' => array( 'cols' => array( 1 ),
'rows' => array( 42 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field5' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c112' => array( 'cols' => array( 2 ),
'rows' => array( 42 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field50' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c107' => array( 'cols' => array( 0 ),
'rows' => array( 43 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c108' => array( 'cols' => array( 1 ),
'rows' => array( 43 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field8' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c109' => array( 'cols' => array( 2 ),
'rows' => array( 43 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field53' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c104' => array( 'cols' => array( 0 ),
'rows' => array( 44 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field7' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c105' => array( 'cols' => array( 1 ),
'rows' => array( 44 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field11' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c106' => array( 'cols' => array( 2 ),
'rows' => array( 44 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field56' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c101' => array( 'cols' => array( 0 ),
'rows' => array( 45 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field10' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c102' => array( 'cols' => array( 1 ),
'rows' => array( 45 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field14' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c103' => array( 'cols' => array( 2 ),
'rows' => array( 45 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field59' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c98' => array( 'cols' => array( 0 ),
'rows' => array( 46 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c99' => array( 'cols' => array( 1 ),
'rows' => array( 46 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c100' => array( 'cols' => array( 2 ),
'rows' => array( 46 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c125' => array( 'cols' => array( 0 ),
'rows' => array( 47 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c126' => array( 'cols' => array( 1 ),
'rows' => array( 47 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c127' => array( 'cols' => array( 2 ),
'rows' => array( 47 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 0 ),
'rows' => array( 48 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 1 ),
'rows' => array( 48 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 2 ),
'rows' => array( 48 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 0,
1,
2 ),
'rows' => array( 49 ),
'tags' => array(  ),
'items' => array( 'details_preview' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 0 ),
'rows' => array( 50 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field75',
'integrated_edit_field78',
'integrated_edit_field81',
'integrated_edit_field84',
'integrated_edit_field87',
'integrated_edit_field90',
'integrated_edit_field93',
'integrated_edit_field96',
'integrated_edit_field99',
'integrated_edit_field102' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c148' => array( 'cols' => array( 1 ),
'rows' => array( 50 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field76',
'integrated_edit_field79',
'integrated_edit_field82',
'integrated_edit_field85',
'integrated_edit_field88',
'integrated_edit_field91',
'integrated_edit_field94',
'integrated_edit_field97',
'integrated_edit_field100',
'integrated_edit_field103' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c149' => array( 'cols' => array( 2 ),
'rows' => array( 50 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field77',
'integrated_edit_field80',
'integrated_edit_field83',
'integrated_edit_field86',
'integrated_edit_field89',
'integrated_edit_field92',
'integrated_edit_field95',
'integrated_edit_field98',
'integrated_edit_field101' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 3,
'height' => 51 ) ) ),
'loginForm' => array( 'loginForm' => 1 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'add',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'add',
'type' => 'add',
'layoutId' => 'topbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'topbar-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ),
array( 'cell' => 'c3' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'logo' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'menu' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c3' => array( 'model' => 'c3',
'items' => array( 'loginform_login',
'username_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'add-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'image',
'add_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'add-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c5',
'colspan' => 1 ) ),
'section' => '' ) ),
'cells' => array( 'c5' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'background' => '#1309eb',
'color' => '#ffffff' ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'add-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add_save',
'add_back_list',
'add_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c59' ),
array( 'cell' => 'c89' ),
array( 'cell' => 'c97' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c8' ),
array( 'cell' => 'c21' ),
array( 'cell' => 'c22' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c11' ),
array( 'cell' => 'c12' ),
array( 'cell' => 'c13' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c17' ),
array( 'cell' => 'c18' ),
array( 'cell' => 'c19' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c14' ),
array( 'cell' => 'c15' ),
array( 'cell' => 'c16' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c29' ),
array( 'cell' => 'c30' ),
array( 'cell' => 'c31' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c26' ),
array( 'cell' => 'c27' ),
array( 'cell' => 'c28' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c23' ),
array( 'cell' => 'c24' ),
array( 'cell' => 'c25' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c36' ),
array( 'cell' => 'c37' ),
array( 'cell' => 'c42' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c38' ),
array( 'cell' => 'c39' ),
array( 'cell' => 'c40' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c50' ),
array( 'cell' => 'c123' ),
array( 'cell' => 'c124' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c41' ),
array( 'cell' => 'c43' ),
array( 'cell' => 'c51' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c32' ),
array( 'cell' => 'c33' ),
array( 'cell' => 'c34' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c44' ),
array( 'cell' => 'c45' ),
array( 'cell' => 'c46' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c74' ),
array( 'cell' => 'c121' ),
array( 'cell' => 'c122' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c52' ),
array( 'cell' => 'c60' ),
array( 'cell' => 'c61' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c47' ),
array( 'cell' => 'c48' ),
array( 'cell' => 'c49' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c53' ),
array( 'cell' => 'c54' ),
array( 'cell' => 'c55' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c118' ),
array( 'cell' => 'c119' ),
array( 'cell' => 'c120' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c75' ),
array( 'cell' => 'c76' ),
array( 'cell' => 'c90' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c56' ),
array( 'cell' => 'c57' ),
array( 'cell' => 'c58' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c68' ),
array( 'cell' => 'c69' ),
array( 'cell' => 'c70' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c65' ),
array( 'cell' => 'c66' ),
array( 'cell' => 'c67' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c62' ),
array( 'cell' => 'c63' ),
array( 'cell' => 'c64' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c77' ),
array( 'cell' => 'c78' ),
array( 'cell' => 'c79' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ),
array( 'cell' => 'c116' ),
array( 'cell' => 'c117' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c1',
'colspan' => 3 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c136' ),
array( 'cell' => 'c137' ),
array( 'cell' => 'c138' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c133' ),
array( 'cell' => 'c134' ),
array( 'cell' => 'c135' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c130' ),
array( 'cell' => 'c131' ),
array( 'cell' => 'c132' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c35' ),
array( 'cell' => 'c128' ),
array( 'cell' => 'c129' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c9' ),
array( 'cell' => 'c10' ),
array( 'cell' => 'c20' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c139' ),
array( 'cell' => 'c140' ),
array( 'cell' => 'c141' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c142' ),
array( 'cell' => 'c143' ),
array( 'cell' => 'c144' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c145' ),
array( 'cell' => 'c146' ),
array( 'cell' => 'c147' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c91' ),
array( 'cell' => 'c92' ),
array( 'cell' => 'c93' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c71' ),
array( 'cell' => 'c72' ),
array( 'cell' => 'c73' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c86' ),
array( 'cell' => 'c87' ),
array( 'cell' => 'c88' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c83' ),
array( 'cell' => 'c84' ),
array( 'cell' => 'c85' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c80' ),
array( 'cell' => 'c81' ),
array( 'cell' => 'c82' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c94' ),
array( 'cell' => 'c95' ),
array( 'cell' => 'c96' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c113' ),
array( 'cell' => 'c114' ),
array( 'cell' => 'c115' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c110' ),
array( 'cell' => 'c111' ),
array( 'cell' => 'c112' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c107' ),
array( 'cell' => 'c108' ),
array( 'cell' => 'c109' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c104' ),
array( 'cell' => 'c105' ),
array( 'cell' => 'c106' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c101' ),
array( 'cell' => 'c102' ),
array( 'cell' => 'c103' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c98' ),
array( 'cell' => 'c99' ),
array( 'cell' => 'c100' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c125' ),
array( 'cell' => 'c126' ),
array( 'cell' => 'c127' ) ) ),
array( 'cells' => array( array( 'cell' => 'c3' ),
array( 'cell' => 'c4' ),
array( 'cell' => 'c5' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c7',
'colspan' => 3 ) ) ),
array( 'cells' => array( array( 'cell' => 'c6' ),
array( 'cell' => 'c148' ),
array( 'cell' => 'c149' ) ),
'section' => '' ) ),
'cells' => array( 'c' => array( 'model' => 'c3',
'items' => array(  ),
'persistent' => true ),
'c11' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field6' ) ),
'c12' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field16' ) ),
'c13' => array( 'model' => 'c3',
'items' => array(  ) ),
'c14' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field12' ) ),
'c15' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field22' ) ),
'c16' => array( 'model' => 'c3',
'items' => array(  ) ),
'c17' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field9' ) ),
'c18' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field19' ) ),
'c19' => array( 'model' => 'c3',
'items' => array(  ) ),
'c23' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field21' ) ),
'c24' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field31' ) ),
'c25' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field26' ) ),
'c26' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field18' ) ),
'c27' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field28' ) ),
'c28' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field23' ) ),
'c29' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field15' ) ),
'c30' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field25' ) ),
'c31' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field20' ) ),
'c32' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field27' ) ),
'c33' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field37' ) ),
'c34' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field29' ) ),
'c36' => array( 'model' => 'c3',
'items' => array( 'text1' ),
'background' => '#110ad6' ),
'c37' => array( 'model' => 'c3',
'items' => array(  ),
'background' => '#110ad6' ),
'c38' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field24' ) ),
'c39' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field34' ) ),
'c40' => array( 'model' => 'c3',
'items' => array(  ) ),
'c41' => array( 'model' => 'c3',
'items' => array( 'text' ),
'background' => '#110ad6' ),
'c44' => array( 'model' => 'c3',
'items' => array(  ) ),
'c45' => array( 'model' => 'c3',
'items' => array(  ) ),
'c46' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field30' ) ),
'c47' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field33' ) ),
'c48' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field40' ) ),
'c49' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field32' ) ),
'c50' => array( 'model' => 'c3',
'items' => array(  ),
'persistent' => true ),
'c53' => array( 'model' => 'c3',
'items' => array(  ) ),
'c54' => array( 'model' => 'c3',
'items' => array(  ) ),
'c55' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field35' ) ),
'c56' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field36' ) ),
'c57' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field43' ) ),
'c58' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field17' ) ),
'c62' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field45' ) ),
'c63' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field49' ) ),
'c64' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field41' ) ),
'c65' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field42' ) ),
'c66' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field13' ) ),
'c67' => array( 'model' => 'c3',
'items' => array(  ) ),
'c68' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field39' ) ),
'c69' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field46' ) ),
'c70' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field38' ) ),
'c71' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field48' ) ),
'c72' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field52' ) ),
'c73' => array( 'model' => 'c3',
'items' => array(  ) ),
'c74' => array( 'model' => 'c3',
'items' => array(  ),
'persistent' => true ),
'c77' => array( 'model' => 'c3',
'items' => array(  ) ),
'c78' => array( 'model' => 'c3',
'items' => array(  ) ),
'c79' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field44' ) ),
'c80' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field57' ) ),
'c81' => array( 'model' => 'c3',
'items' => array(  ) ),
'c82' => array( 'model' => 'c3',
'items' => array(  ) ),
'c83' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field54' ) ),
'c84' => array( 'model' => 'c3',
'items' => array(  ) ),
'c85' => array( 'model' => 'c3',
'items' => array(  ) ),
'c86' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field51' ) ),
'c87' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field55' ) ),
'c88' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field58' ) ),
'c8' => array( 'model' => 'c3',
'items' => array( 'text3' ),
'background' => '#110ad6' ),
'c21' => array( 'model' => 'c3',
'items' => array(  ),
'background' => '#110ad6' ),
'c22' => array( 'model' => 'c3',
'items' => array(  ),
'background' => '#110ad6' ),
'c42' => array( 'model' => 'c3',
'items' => array(  ),
'background' => '#110ad6' ),
'c43' => array( 'model' => 'c3',
'items' => array(  ),
'background' => '#110ad6' ),
'c51' => array( 'model' => 'c3',
'items' => array(  ),
'background' => '#110ad6' ),
'c52' => array( 'model' => 'c3',
'items' => array( 'text2' ),
'background' => '#110ad6' ),
'c60' => array( 'model' => 'c3',
'items' => array(  ),
'background' => '#110ad6' ),
'c61' => array( 'model' => 'c3',
'items' => array(  ),
'background' => '#110ad6' ),
'c75' => array( 'model' => 'c3',
'items' => array( 'text4' ),
'background' => '#110ad6' ),
'c76' => array( 'model' => 'c3',
'items' => array(  ),
'background' => '#110ad6' ),
'c90' => array( 'model' => 'c3',
'items' => array(  ),
'background' => '#110ad6' ),
'c91' => array( 'model' => 'c3',
'items' => array( 'text6' ),
'background' => '#110ad6' ),
'c92' => array( 'model' => 'c3',
'items' => array(  ),
'background' => '#110ad6' ),
'c93' => array( 'model' => 'c3',
'items' => array(  ),
'background' => '#110ad6' ),
'c94' => array( 'model' => 'c3',
'items' => array( 'text5' ),
'background' => '#110ad6' ),
'c95' => array( 'model' => 'c3',
'items' => array(  ),
'background' => '#110ad6' ),
'c96' => array( 'model' => 'c3',
'items' => array(  ),
'background' => '#110ad6' ),
'c59' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field' ),
'background' => '#fffbe1' ),
'c89' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field3' ),
'background' => '#fffbe1' ),
'c97' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field68' ) ),
'c98' => array( 'model' => 'c3',
'items' => array(  ),
'persistent' => true ),
'c99' => array( 'model' => 'c3',
'items' => array(  ),
'persistent' => true ),
'c100' => array( 'model' => 'c3',
'items' => array(  ) ),
'c101' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field10' ) ),
'c102' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field14' ) ),
'c103' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field59' ) ),
'c104' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field7' ) ),
'c105' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field11' ) ),
'c106' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field56' ) ),
'c107' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field4' ) ),
'c108' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field8' ) ),
'c109' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field53' ) ),
'c110' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field1' ) ),
'c111' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field5' ) ),
'c112' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field50' ) ),
'c113' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field60' ) ),
'c114' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field2' ) ),
'c115' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field47' ) ),
'c116' => array( 'model' => 'c3',
'items' => array(  ) ),
'c117' => array( 'model' => 'c3',
'items' => array(  ) ),
'c118' => array( 'model' => 'c3',
'items' => array(  ),
'persistent' => true ),
'c119' => array( 'model' => 'c3',
'items' => array(  ) ),
'c120' => array( 'model' => 'c3',
'items' => array(  ) ),
'c121' => array( 'model' => 'c3',
'items' => array(  ) ),
'c122' => array( 'model' => 'c3',
'items' => array(  ) ),
'c123' => array( 'model' => 'c3',
'items' => array(  ) ),
'c124' => array( 'model' => 'c3',
'items' => array(  ) ),
'c3' => array( 'model' => 'c3',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c4' => array( 'model' => 'c3',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c5' => array( 'model' => 'c3',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c7' => array( 'model' => 'c3',
'items' => array( 'details_preview' ) ),
'c9' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field67' ) ),
'c10' => array( 'model' => 'c3',
'items' => array(  ) ),
'c125' => array( 'model' => 'c3',
'items' => array(  ) ),
'c126' => array( 'model' => 'c3',
'items' => array(  ) ),
'c127' => array( 'model' => 'c3',
'items' => array(  ) ),
'c1' => array( 'model' => 'c3',
'items' => array( 'text7' ),
'background' => '#110ad6' ),
'c20' => array( 'model' => 'c3',
'items' => array(  ) ),
'c35' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field66' ) ),
'c128' => array( 'model' => 'c3',
'items' => array(  ) ),
'c129' => array( 'model' => 'c3',
'items' => array(  ) ),
'c130' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field65' ) ),
'c131' => array( 'model' => 'c3',
'items' => array(  ) ),
'c132' => array( 'model' => 'c3',
'items' => array(  ) ),
'c133' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field64' ) ),
'c134' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field63' ) ),
'c135' => array( 'model' => 'c3',
'items' => array(  ) ),
'c136' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field61' ) ),
'c137' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field62' ) ),
'c138' => array( 'model' => 'c3',
'items' => array(  ) ),
'c139' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field69' ) ),
'c140' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field70' ) ),
'c141' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field71' ) ),
'c142' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field72' ),
'persistent' => true ),
'c143' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field73' ) ),
'c144' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field74' ) ),
'c145' => array( 'model' => 'c3',
'items' => array(  ),
'persistent' => true ),
'c146' => array( 'model' => 'c3',
'items' => array(  ) ),
'c147' => array( 'model' => 'c3',
'items' => array(  ) ),
'c6' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field75',
'integrated_edit_field78',
'integrated_edit_field81',
'integrated_edit_field84',
'integrated_edit_field87',
'integrated_edit_field90',
'integrated_edit_field93',
'integrated_edit_field96',
'integrated_edit_field99',
'integrated_edit_field102' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c148' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field76',
'integrated_edit_field79',
'integrated_edit_field82',
'integrated_edit_field85',
'integrated_edit_field88',
'integrated_edit_field91',
'integrated_edit_field94',
'integrated_edit_field97',
'integrated_edit_field100',
'integrated_edit_field103' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c149' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field77',
'integrated_edit_field80',
'integrated_edit_field83',
'integrated_edit_field86',
'integrated_edit_field89',
'integrated_edit_field92',
'integrated_edit_field95',
'integrated_edit_field98',
'integrated_edit_field101' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 3,
'inlineLabels' => true,
'separateLabels' => false ) ),
'items' => array( 'add_header' => array( 'type' => 'add_header',
'title' => array( 'page' => 'add',
'table' => 'dbo.application',
'type' => 7 ) ),
'image' => array( 'type' => 'image',
'imagePath' => 'volton logo.png',
'width' => '',
'height' => '',
'mobileDisplay' => '' ),
'add_save' => array( 'type' => 'add_save' ),
'add_back_list' => array( 'type' => 'add_back_list' ),
'add_cancel' => array( 'type' => 'add_cancel' ),
'details_preview' => array( 'type' => 'details_preview',
'table' => 'dbo.internalComments',
'items' => array(  ),
'popup' => false,
'pageId' => 'list' ),
'text2' => array( 'type' => 'text',
'label' => array( 'text' => 'ΔΙΕΥΘΥΝΣΗ ΑΠΟΣΤΟΛΗΣ ΛΟΓΑΡΙΑΣΜΟΥ',
'type' => 0 ),
'editedByRte' => false,
'bold' => true,
'font-size' => '16px',
'color' => '#ffffff' ),
'integrated_edit_field' => array( 'field' => 'applicationType',
'type' => 'integrated_edit_field',
'orientation' => 1,
'tooltip' => array( 'field' => 'applicationType',
'table' => 'dbo.VoltonApplications',
'type' => 4 ) ),
'integrated_edit_field3' => array( 'field' => 'applicationStatusId',
'type' => 'integrated_edit_field',
'orientation' => 1,
'tooltip' => array( 'field' => 'applicationStatusId',
'table' => 'dbo.VoltonApplications',
'type' => 4 ) ),
'integrated_edit_field6' => array( 'field' => 'applicantName',
'type' => 'integrated_edit_field',
'orientation' => 1,
'tooltip' => array( 'field' => 'applicantName',
'table' => 'dbo.VoltonApplications',
'type' => 4 ) ),
'integrated_edit_field9' => array( 'field' => 'applicantAddress',
'type' => 'integrated_edit_field',
'orientation' => 1,
'tooltip' => array( 'field' => 'applicantAddress',
'table' => 'dbo.VoltonApplications',
'type' => 4 ) ),
'integrated_edit_field12' => array( 'field' => 'applicantArea',
'type' => 'integrated_edit_field',
'orientation' => 1,
'tooltip' => array( 'field' => 'applicantArea',
'table' => 'dbo.VoltonApplications',
'type' => 4 ) ),
'integrated_edit_field15' => array( 'field' => 'applicantPhone',
'type' => 'integrated_edit_field',
'orientation' => 1,
'tooltip' => array( 'field' => 'applicantPhone',
'table' => 'dbo.VoltonApplications',
'type' => 4 ) ),
'integrated_edit_field18' => array( 'field' => 'applicantProfession',
'type' => 'integrated_edit_field',
'orientation' => 1,
'tooltip' => array( 'field' => 'applicantProfession',
'table' => 'dbo.VoltonApplications',
'type' => 4 ) ),
'integrated_edit_field21' => array( 'field' => 'applicantTaxRegistrationNumber',
'type' => 'integrated_edit_field',
'orientation' => 1,
'tooltip' => array( 'field' => 'applicantTaxRegistrationNumber',
'table' => 'dbo.VoltonApplications',
'type' => 4 ) ),
'integrated_edit_field24' => array( 'field' => 'legalName',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field27' => array( 'field' => 'contactName',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field30' => array( 'field' => 'contactEmail',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field33' => array( 'field' => 'mailAddress',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field36' => array( 'field' => 'powerAddress',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field39' => array( 'field' => 'powerPostalCode',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field42' => array( 'field' => 'powerCurrentSupplier',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field45' => array( 'field' => 'powerSupplyNumber',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field48' => array( 'field' => 'voltonPlan',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field51' => array( 'field' => 'voltonWarrantyAmount',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field54' => array( 'field' => 'voltonAutoPayment',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field57' => array( 'field' => 'voltonComments',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field60' => array( 'field' => 'document1',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'text' => array( 'type' => 'text',
'label' => array( 'text' => 'ΥΠΕΥΘΥΝΟΣ ΕΠΙΚΟΙΝΩΝΙΑΣ',
'type' => 0 ),
'editedByRte' => false,
'bold' => true,
'font-size' => '16px',
'color' => '#ffffff' ),
'integrated_edit_field1' => array( 'field' => 'document2',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field4' => array( 'field' => 'document3',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field7' => array( 'field' => 'document4',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field10' => array( 'field' => 'document5',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field13' => array( 'field' => 'powerActivationStatus',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field16' => array( 'field' => 'applicantIdNumber',
'type' => 'integrated_edit_field',
'orientation' => 1,
'tooltip' => array( 'field' => 'applicantIdNumber',
'table' => 'dbo.VoltonApplications',
'type' => 4 ) ),
'integrated_edit_field19' => array( 'field' => 'applicantPostalCode',
'type' => 'integrated_edit_field',
'orientation' => 1,
'tooltip' => array( 'field' => 'applicantPostalCode',
'table' => 'dbo.VoltonApplications',
'type' => 4 ) ),
'integrated_edit_field22' => array( 'field' => 'applicantCity',
'type' => 'integrated_edit_field',
'orientation' => 1,
'tooltip' => array( 'field' => 'applicantCity',
'table' => 'dbo.VoltonApplications',
'type' => 4 ) ),
'integrated_edit_field25' => array( 'field' => 'applicantWorkPhone',
'type' => 'integrated_edit_field',
'orientation' => 1,
'tooltip' => array( 'field' => 'applicantWorkPhone',
'table' => 'dbo.VoltonApplications',
'type' => 4 ) ),
'integrated_edit_field28' => array( 'field' => 'applicantEmail',
'type' => 'integrated_edit_field',
'orientation' => 1,
'tooltip' => array( 'field' => 'applicantEmail',
'table' => 'dbo.VoltonApplications',
'type' => 4 ) ),
'integrated_edit_field31' => array( 'field' => 'applicantTaxOffice',
'type' => 'integrated_edit_field',
'orientation' => 1,
'tooltip' => array( 'field' => 'applicantTaxOffice',
'table' => 'dbo.VoltonApplications',
'type' => 4 ) ),
'integrated_edit_field34' => array( 'field' => 'legalIdNumber',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field37' => array( 'field' => 'contactPhone',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field40' => array( 'field' => 'mailPostalCode',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field43' => array( 'field' => 'powerAgreedKw',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field46' => array( 'field' => 'powerArea',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field49' => array( 'field' => 'powerMeterNumber',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field52' => array( 'field' => 'voltonContractDuration',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field55' => array( 'field' => 'voltonWarrantyOnFirstBill',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field58' => array( 'field' => 'voltonOther',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'text1' => array( 'type' => 'text',
'label' => array( 'text' => 'ΝΟΜΙΜΟΣ ΕΚΠΡΟΣΩΠΟΣ',
'type' => 0 ),
'editedByRte' => false,
'bold' => true,
'font-size' => '16px',
'color' => '#ffffff' ),
'integrated_edit_field2' => array( 'field' => 'document6',
'type' => 'integrated_edit_field',
'orientation' => 1,
'nowrap' => true,
'joined' => true,
'separated' => false ),
'integrated_edit_field5' => array( 'field' => 'document7',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field8' => array( 'field' => 'document8',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field11' => array( 'field' => 'document9',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field14' => array( 'field' => 'document10',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field17' => array( 'field' => 'powerOwnershipType',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field20' => array( 'field' => 'applicantMobile',
'type' => 'integrated_edit_field',
'orientation' => 1,
'tooltip' => array( 'field' => 'applicantMobile',
'table' => 'dbo.VoltonApplications',
'type' => 4 ) ),
'integrated_edit_field23' => array( 'field' => 'applicantGemi',
'type' => 'integrated_edit_field',
'orientation' => 1,
'tooltip' => array( 'field' => 'applicantGemi',
'table' => 'dbo.VoltonApplications',
'type' => 4 ) ),
'integrated_edit_field26' => array( 'field' => 'applicantKod',
'type' => 'integrated_edit_field',
'orientation' => 1,
'tooltip' => array( 'field' => 'applicantKod',
'table' => 'dbo.VoltonApplications',
'type' => 4 ) ),
'integrated_edit_field29' => array( 'field' => 'contactMobile',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field32' => array( 'field' => 'mailArea',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field35' => array( 'field' => 'mailCity',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field38' => array( 'field' => 'powerCity',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field41' => array( 'field' => 'powerCurrentDayMeter',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field44' => array( 'field' => 'powerCurrentNightMeter',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field47' => array( 'field' => 'document11',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field50' => array( 'field' => 'document12',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field53' => array( 'field' => 'document13',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field56' => array( 'field' => 'document14',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field59' => array( 'field' => 'document15',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu' ),
'text3' => array( 'type' => 'text',
'label' => array( 'text' => 'ΣΤΟΙΧΕΙΑ ΠΕΛΑΤΗ',
'type' => 0 ),
'editedByRte' => false,
'bold' => true,
'font-size' => '16px',
'color' => '#ffffff' ),
'text4' => array( 'type' => 'text',
'label' => array( 'text' => 'ΣΤΟΙΧΕΙΑ ΠΑΡΟΧΗΣ',
'type' => 0 ),
'editedByRte' => false,
'color' => '#ffffff',
'bold' => true,
'font-size' => '16px' ),
'text5' => array( 'type' => 'text',
'label' => array( 'text' => 'ΔΙΚΑΙΟΛΟΓΗΤΙΚΑ',
'type' => 0 ),
'editedByRte' => false,
'color' => '#ffffff' ),
'text6' => array( 'type' => 'text',
'label' => array( 'text' => 'ΤΙΜΟΛΟΓΙΟ VOLTON',
'type' => 0 ),
'editedByRte' => false,
'color' => '#ffffff',
'bold' => true,
'font-size' => '16px' ),
'integrated_edit_field61' => array( 'field' => 'ngAddress',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field62' => array( 'field' => 'ngPostalCode',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field63' => array( 'field' => 'ngArea',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field64' => array( 'field' => 'ngCity',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field65' => array( 'field' => 'ngPressure',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field66' => array( 'field' => 'ngHourlyCapacity',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field67' => array( 'field' => 'ngHkasp',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field69' => array( 'field' => 'ngMeterNumber',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field70' => array( 'field' => 'ngMeterType',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field71' => array( 'field' => 'ngCurrentMeterValue',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field72' => array( 'field' => 'ngConnectionExists',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field73' => array( 'field' => 'ngSupplyIsNew',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field74' => array( 'field' => 'ngSupplyReactivation',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'logout_link',
'adminarea_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => true ),
'logout_link' => array( 'type' => 'logout_link' ),
'integrated_edit_field68' => array( 'field' => 'applicationAgentStatus',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'text7' => array( 'type' => 'text',
'label' => array( 'text' => 'ΣΤΟΙΧΕΙΑ ΠΑΡΟΧΗΣ (ΦΥΣΙΚΟ ΑΕΡΙΟ)',
'type' => 0 ),
'editedByRte' => false,
'bold' => true,
'font-size' => '16px',
'color' => '#ffffff' ),
'integrated_edit_field75' => array( 'field' => 'applicationLastStatusDate',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'integrated_edit_field76' => array( 'field' => 'id',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field77' => array( 'field' => 'dialerList',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field78' => array( 'field' => 'dialerAgent',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field79' => array( 'field' => 'dialerRecording',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field80' => array( 'field' => 'orderShipCompany',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field81' => array( 'field' => 'orderInvoiceRequired',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field82' => array( 'field' => 'callComments',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field83' => array( 'field' => 'internalCommunication',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field84' => array( 'field' => 'callGdprAcceptance',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field85' => array( 'field' => 'callGdprRecordingAcceptance',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field86' => array( 'field' => 'orderPaymentMethod',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field87' => array( 'field' => 'Expr2',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field88' => array( 'field' => 'contactZipCode',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field89' => array( 'field' => 'contactCity',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field90' => array( 'field' => 'ContactArea',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field91' => array( 'field' => 'contactGender',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field92' => array( 'field' => 'contactAge',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field93' => array( 'field' => 'crmUser',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field94' => array( 'field' => 'pauseAfterCall',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field95' => array( 'field' => 'dialerPhone',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field96' => array( 'field' => 'dialerCampaign',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field97' => array( 'field' => 'productFamilyId',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field98' => array( 'field' => 'contactMethod',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field99' => array( 'field' => 'courier',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field100' => array( 'field' => 'deliveryComments',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field101' => array( 'field' => 'courierDeliveryDate',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field102' => array( 'field' => 'courierTimeFrom',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field103' => array( 'field' => 'courierTimeTo',
'type' => 'integrated_edit_field',
'orientation' => 1 ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>