<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'applicationAgentStatus',
'applicationType',
'applicationStatusId',
'applicationLastStatusDate',
'applicantName',
'ngMeterType',
'applicantMobile',
'applicantWorkPhone',
'applicantIdNumber',
'applicantPhone',
'applicationContactMethod',
'powerMeterNumber',
'applicationCourier',
'applicationCourierDate',
'powerPostalCode',
'powerSupplyNumber',
'voltonPlan',
'powerAddress',
'applicantTaxRegistrationNumber',
'ngMeterNumber',
'ngAddress',
'ngPostalCode',
'callPhone',
'callDate',
'agent',
'applicationPhase',
'salesPhase' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'applicationType' => array( 'search_field_label1',
'integrated_search_field45',
'search_field_between1',
'search_field_options1' ),
'applicantName' => array( 'search_field_label5',
'integrated_search_field3',
'search_field_between5',
'search_field_options5' ),
'applicationContactMethod' => array( 'search_field_label34',
'search_field_options34',
'integrated_search_field78',
'search_field_between34' ),
'applicationAgentStatus' => array( 'search_field_label4',
'integrated_search_field70',
'search_field_between4',
'search_field_options4' ),
'applicationStatusId' => array( 'search_field_label2',
'integrated_search_field2',
'search_field_between2',
'search_field_options2' ),
'applicationLastStatusDate' => array( 'search_field_label3',
'integrated_search_field77',
'search_field_between3',
'search_field_options3' ),
'applicantIdNumber' => array( 'search_field_label7',
'search_field_between7',
'search_field_options7',
'integrated_search_field4' ),
'ngMeterType' => array( 'integrated_search_field72',
'search_field_between27',
'search_field_options27',
'search_field_label27' ),
'applicantMobile' => array( 'integrated_search_field14',
'search_field_label9',
'search_field_options9',
'search_field_between9' ),
'applicantWorkPhone' => array( 'integrated_search_field46',
'search_field_label8',
'search_field_options8',
'search_field_between8' ),
'applicantTaxRegistrationNumber' => array( 'search_field_label6',
'search_field_options6',
'search_field_between6',
'integrated_search_field7' ),
'applicantPhone' => array( 'integrated_search_field13',
'search_field_label16',
'search_field_options16',
'search_field_between16' ),
'ngAddress' => array( 'search_field_options15',
'search_field_label15',
'integrated_search_field41',
'search_field_between15' ),
'ngPostalCode' => array( 'search_field_options24',
'search_field_label24',
'integrated_search_field64',
'search_field_between24' ),
'powerMeterNumber' => array( 'integrated_search_field30',
'search_field_between14',
'search_field_options14',
'search_field_label14' ),
'applicationCourier' => array( 'search_field_options32',
'search_field_label32',
'integrated_search_field79',
'search_field_between32' ),
'applicationCourierDate' => array( 'search_field_options33',
'search_field_label33',
'integrated_search_field80',
'search_field_between33' ),
'powerPostalCode' => array( 'integrated_search_field26',
'search_field_label11',
'search_field_options11',
'search_field_between11' ),
'powerSupplyNumber' => array( 'integrated_search_field29',
'search_field_between13',
'search_field_options13',
'search_field_label13' ),
'voltonPlan' => array( 'integrated_search_field35',
'search_field_between12',
'search_field_label12',
'search_field_options12' ),
'powerAddress' => array( 'search_field_label10',
'search_field_options10',
'integrated_search_field24',
'search_field_between10' ),
'ngMeterNumber' => array( 'search_field_label28',
'search_field_options28',
'integrated_search_field71',
'search_field_between28' ),
'callPhone' => array( 'integrated_search_field',
'search_field_label36',
'search_field_options36',
'search_field_between36' ),
'callDate' => array( 'integrated_search_field1',
'search_field_label35',
'search_field_options35',
'search_field_between35' ),
'agent' => array( 'integrated_search_field5' ),
'applicationPhase' => array( 'integrated_search_field6' ),
'salesPhase' => array( 'integrated_search_field8' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array( 'logo',
'menu',
'loginform_login',
'username_button' ),
'top' => array( 'search_header',
'search_search1',
'search_reset1' ),
'above-grid' => array(  ),
'below-grid' => array( 'search_search',
'search_reset',
'search_back_list',
'search_cancel' ),
'grid' => array( 'integrated_search_field5',
'integrated_search_field6',
'integrated_search_field8',
'search_field_label35',
'search_field_label5',
'search_field_label34',
'search_field_options34',
'search_field_label36',
'search_field_options36',
'search_field_label8',
'search_field_label4',
'integrated_search_field70',
'search_field_between4',
'search_field_label2',
'search_field_label3',
'integrated_search_field1',
'search_field_between35',
'integrated_search_field2',
'search_field_between2',
'search_field_options2',
'integrated_search_field77',
'search_field_between3',
'search_field_options3',
'search_field_options35',
'search_field_label6',
'integrated_search_field3',
'search_field_between5',
'search_field_options5',
'integrated_search_field7',
'search_field_between6',
'search_field_options6',
'integrated_search_field72',
'search_field_between27',
'search_field_options4',
'integrated_search_field',
'search_field_between36',
'search_field_options16',
'search_field_label16',
'search_field_options8',
'integrated_search_field46',
'search_field_between8',
'search_field_options14',
'search_field_label14',
'search_field_label7',
'search_field_options7',
'integrated_search_field4',
'search_field_between7',
'integrated_search_field13',
'search_field_between16',
'search_field_label9',
'search_field_options9',
'integrated_search_field14',
'search_field_between9',
'integrated_search_field30',
'search_field_between14',
'integrated_search_field78',
'search_field_between34',
'search_field_options15',
'search_field_label15',
'search_field_options24',
'search_field_label24',
'search_field_options27',
'search_field_label27',
'search_field_options32',
'search_field_label32',
'integrated_search_field79',
'search_field_between32',
'search_field_options33',
'search_field_label33',
'integrated_search_field80',
'search_field_between33',
'text3',
'text1',
'text2',
'search_field_label11',
'search_field_options11',
'integrated_search_field26',
'search_field_between11',
'search_field_label13',
'search_field_options13',
'integrated_search_field29',
'search_field_between13',
'search_field_label10',
'search_field_options10',
'integrated_search_field24',
'search_field_between10',
'search_field_label12',
'search_field_options12',
'integrated_search_field35',
'search_field_between12',
'text',
'search_field_label28',
'search_field_options28',
'integrated_search_field71',
'search_field_between28',
'integrated_search_field41',
'search_field_between15',
'integrated_search_field64',
'search_field_between24',
'search_field_label1',
'search_field_options1',
'integrated_search_field45',
'search_field_between1' ) ),
'formXtTags' => array( 'above-grid' => array(  ) ),
'itemForms' => array( 'logo' => 'supertop',
'menu' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'search_header' => 'top',
'search_search1' => 'top',
'search_reset1' => 'top',
'search_search' => 'below-grid',
'search_reset' => 'below-grid',
'search_back_list' => 'below-grid',
'search_cancel' => 'below-grid',
'integrated_search_field5' => 'grid',
'integrated_search_field6' => 'grid',
'integrated_search_field8' => 'grid',
'search_field_label35' => 'grid',
'search_field_label5' => 'grid',
'search_field_label34' => 'grid',
'search_field_options34' => 'grid',
'search_field_label36' => 'grid',
'search_field_options36' => 'grid',
'search_field_label8' => 'grid',
'search_field_label4' => 'grid',
'integrated_search_field70' => 'grid',
'search_field_between4' => 'grid',
'search_field_label2' => 'grid',
'search_field_label3' => 'grid',
'integrated_search_field1' => 'grid',
'search_field_between35' => 'grid',
'integrated_search_field2' => 'grid',
'search_field_between2' => 'grid',
'search_field_options2' => 'grid',
'integrated_search_field77' => 'grid',
'search_field_between3' => 'grid',
'search_field_options3' => 'grid',
'search_field_options35' => 'grid',
'search_field_label6' => 'grid',
'integrated_search_field3' => 'grid',
'search_field_between5' => 'grid',
'search_field_options5' => 'grid',
'integrated_search_field7' => 'grid',
'search_field_between6' => 'grid',
'search_field_options6' => 'grid',
'integrated_search_field72' => 'grid',
'search_field_between27' => 'grid',
'search_field_options4' => 'grid',
'integrated_search_field' => 'grid',
'search_field_between36' => 'grid',
'search_field_options16' => 'grid',
'search_field_label16' => 'grid',
'search_field_options8' => 'grid',
'integrated_search_field46' => 'grid',
'search_field_between8' => 'grid',
'search_field_options14' => 'grid',
'search_field_label14' => 'grid',
'search_field_label7' => 'grid',
'search_field_options7' => 'grid',
'integrated_search_field4' => 'grid',
'search_field_between7' => 'grid',
'integrated_search_field13' => 'grid',
'search_field_between16' => 'grid',
'search_field_label9' => 'grid',
'search_field_options9' => 'grid',
'integrated_search_field14' => 'grid',
'search_field_between9' => 'grid',
'integrated_search_field30' => 'grid',
'search_field_between14' => 'grid',
'integrated_search_field78' => 'grid',
'search_field_between34' => 'grid',
'search_field_options15' => 'grid',
'search_field_label15' => 'grid',
'search_field_options24' => 'grid',
'search_field_label24' => 'grid',
'search_field_options27' => 'grid',
'search_field_label27' => 'grid',
'search_field_options32' => 'grid',
'search_field_label32' => 'grid',
'integrated_search_field79' => 'grid',
'search_field_between32' => 'grid',
'search_field_options33' => 'grid',
'search_field_label33' => 'grid',
'integrated_search_field80' => 'grid',
'search_field_between33' => 'grid',
'text3' => 'grid',
'text1' => 'grid',
'text2' => 'grid',
'search_field_label11' => 'grid',
'search_field_options11' => 'grid',
'integrated_search_field26' => 'grid',
'search_field_between11' => 'grid',
'search_field_label13' => 'grid',
'search_field_options13' => 'grid',
'integrated_search_field29' => 'grid',
'search_field_between13' => 'grid',
'search_field_label10' => 'grid',
'search_field_options10' => 'grid',
'integrated_search_field24' => 'grid',
'search_field_between10' => 'grid',
'search_field_label12' => 'grid',
'search_field_options12' => 'grid',
'integrated_search_field35' => 'grid',
'search_field_between12' => 'grid',
'text' => 'grid',
'search_field_label28' => 'grid',
'search_field_options28' => 'grid',
'integrated_search_field71' => 'grid',
'search_field_between28' => 'grid',
'integrated_search_field41' => 'grid',
'search_field_between15' => 'grid',
'integrated_search_field64' => 'grid',
'search_field_between24' => 'grid',
'search_field_label1' => 'grid',
'search_field_options1' => 'grid',
'integrated_search_field45' => 'grid',
'search_field_between1' => 'grid' ),
'itemLocations' => array( 'integrated_search_field5' => array( 'location' => 'grid',
'cellId' => 'c4' ),
'integrated_search_field6' => array( 'location' => 'grid',
'cellId' => 'c4' ),
'integrated_search_field8' => array( 'location' => 'grid',
'cellId' => 'c4' ),
'search_field_label35' => array( 'location' => 'grid',
'cellId' => 'c7' ),
'search_field_label5' => array( 'location' => 'grid',
'cellId' => 'c8' ),
'search_field_label34' => array( 'location' => 'grid',
'cellId' => 'c12' ),
'search_field_options34' => array( 'location' => 'grid',
'cellId' => 'c13' ),
'search_field_label36' => array( 'location' => 'grid',
'cellId' => 'c14' ),
'search_field_options36' => array( 'location' => 'grid',
'cellId' => 'c15' ),
'search_field_label8' => array( 'location' => 'grid',
'cellId' => 'c16' ),
'search_field_label4' => array( 'location' => 'grid',
'cellId' => 'c17' ),
'integrated_search_field70' => array( 'location' => 'grid',
'cellId' => 'c18' ),
'search_field_between4' => array( 'location' => 'grid',
'cellId' => 'c18' ),
'search_field_label2' => array( 'location' => 'grid',
'cellId' => 'c19' ),
'search_field_label3' => array( 'location' => 'grid',
'cellId' => 'c20' ),
'integrated_search_field1' => array( 'location' => 'grid',
'cellId' => 'c22' ),
'search_field_between35' => array( 'location' => 'grid',
'cellId' => 'c22' ),
'integrated_search_field2' => array( 'location' => 'grid',
'cellId' => 'c23' ),
'search_field_between2' => array( 'location' => 'grid',
'cellId' => 'c23' ),
'search_field_options2' => array( 'location' => 'grid',
'cellId' => 'c24' ),
'integrated_search_field77' => array( 'location' => 'grid',
'cellId' => 'c25' ),
'search_field_between3' => array( 'location' => 'grid',
'cellId' => 'c25' ),
'search_field_options3' => array( 'location' => 'grid',
'cellId' => 'c26' ),
'search_field_options35' => array( 'location' => 'grid',
'cellId' => 'c27' ),
'search_field_label6' => array( 'location' => 'grid',
'cellId' => 'c28' ),
'integrated_search_field3' => array( 'location' => 'grid',
'cellId' => 'c31' ),
'search_field_between5' => array( 'location' => 'grid',
'cellId' => 'c31' ),
'search_field_options5' => array( 'location' => 'grid',
'cellId' => 'c32' ),
'integrated_search_field7' => array( 'location' => 'grid',
'cellId' => 'c35' ),
'search_field_between6' => array( 'location' => 'grid',
'cellId' => 'c35' ),
'search_field_options6' => array( 'location' => 'grid',
'cellId' => 'c36' ),
'integrated_search_field72' => array( 'location' => 'grid',
'cellId' => 'c42' ),
'search_field_between27' => array( 'location' => 'grid',
'cellId' => 'c42' ),
'search_field_options4' => array( 'location' => 'grid',
'cellId' => 'c62' ),
'integrated_search_field' => array( 'location' => 'grid',
'cellId' => 'c63' ),
'search_field_between36' => array( 'location' => 'grid',
'cellId' => 'c63' ),
'search_field_options16' => array( 'location' => 'grid',
'cellId' => 'c68' ),
'search_field_label16' => array( 'location' => 'grid',
'cellId' => 'c69' ),
'search_field_options8' => array( 'location' => 'grid',
'cellId' => 'c70' ),
'integrated_search_field46' => array( 'location' => 'grid',
'cellId' => 'c71' ),
'search_field_between8' => array( 'location' => 'grid',
'cellId' => 'c71' ),
'search_field_options14' => array( 'location' => 'grid',
'cellId' => 'c76' ),
'search_field_label14' => array( 'location' => 'grid',
'cellId' => 'c77' ),
'search_field_label7' => array( 'location' => 'grid',
'cellId' => 'c80' ),
'search_field_options7' => array( 'location' => 'grid',
'cellId' => 'c81' ),
'integrated_search_field4' => array( 'location' => 'grid',
'cellId' => 'c82' ),
'search_field_between7' => array( 'location' => 'grid',
'cellId' => 'c82' ),
'integrated_search_field13' => array( 'location' => 'grid',
'cellId' => 'c87' ),
'search_field_between16' => array( 'location' => 'grid',
'cellId' => 'c87' ),
'search_field_label9' => array( 'location' => 'grid',
'cellId' => 'c90' ),
'search_field_options9' => array( 'location' => 'grid',
'cellId' => 'c92' ),
'integrated_search_field14' => array( 'location' => 'grid',
'cellId' => 'c93' ),
'search_field_between9' => array( 'location' => 'grid',
'cellId' => 'c93' ),
'integrated_search_field30' => array( 'location' => 'grid',
'cellId' => 'c91' ),
'search_field_between14' => array( 'location' => 'grid',
'cellId' => 'c91' ),
'integrated_search_field78' => array( 'location' => 'grid',
'cellId' => 'c34' ),
'search_field_between34' => array( 'location' => 'grid',
'cellId' => 'c34' ),
'search_field_options15' => array( 'location' => 'grid',
'cellId' => 'c61' ),
'search_field_label15' => array( 'location' => 'grid',
'cellId' => 'c67' ),
'search_field_options24' => array( 'location' => 'grid',
'cellId' => 'c78' ),
'search_field_label24' => array( 'location' => 'grid',
'cellId' => 'c79' ),
'search_field_options27' => array( 'location' => 'grid',
'cellId' => 'c2' ),
'search_field_label27' => array( 'location' => 'grid',
'cellId' => 'c89' ),
'search_field_options32' => array( 'location' => 'grid',
'cellId' => 'c109' ),
'search_field_label32' => array( 'location' => 'grid',
'cellId' => 'c110' ),
'integrated_search_field79' => array( 'location' => 'grid',
'cellId' => 'c111' ),
'search_field_between32' => array( 'location' => 'grid',
'cellId' => 'c111' ),
'search_field_options33' => array( 'location' => 'grid',
'cellId' => 'c112' ),
'search_field_label33' => array( 'location' => 'grid',
'cellId' => 'c113' ),
'integrated_search_field80' => array( 'location' => 'grid',
'cellId' => 'c114' ),
'search_field_between33' => array( 'location' => 'grid',
'cellId' => 'c114' ),
'text3' => array( 'location' => 'grid',
'cellId' => 'c118' ),
'text1' => array( 'location' => 'grid',
'cellId' => 'c119' ),
'text2' => array( 'location' => 'grid',
'cellId' => 'c130' ),
'search_field_label11' => array( 'location' => 'grid',
'cellId' => 'c49' ),
'search_field_options11' => array( 'location' => 'grid',
'cellId' => 'c143' ),
'integrated_search_field26' => array( 'location' => 'grid',
'cellId' => 'c144' ),
'search_field_between11' => array( 'location' => 'grid',
'cellId' => 'c144' ),
'search_field_label13' => array( 'location' => 'grid',
'cellId' => 'c145' ),
'search_field_options13' => array( 'location' => 'grid',
'cellId' => 'c146' ),
'integrated_search_field29' => array( 'location' => 'grid',
'cellId' => 'c147' ),
'search_field_between13' => array( 'location' => 'grid',
'cellId' => 'c147' ),
'search_field_label10' => array( 'location' => 'grid',
'cellId' => 'c142' ),
'search_field_options10' => array( 'location' => 'grid',
'cellId' => 'c149' ),
'integrated_search_field24' => array( 'location' => 'grid',
'cellId' => 'c150' ),
'search_field_between10' => array( 'location' => 'grid',
'cellId' => 'c150' ),
'search_field_label12' => array( 'location' => 'grid',
'cellId' => 'c151' ),
'search_field_options12' => array( 'location' => 'grid',
'cellId' => 'c152' ),
'integrated_search_field35' => array( 'location' => 'grid',
'cellId' => 'c153' ),
'search_field_between12' => array( 'location' => 'grid',
'cellId' => 'c153' ),
'text' => array( 'location' => 'grid',
'cellId' => 'c148' ),
'search_field_label28' => array( 'location' => 'grid',
'cellId' => 'c154' ),
'search_field_options28' => array( 'location' => 'grid',
'cellId' => 'c160' ),
'integrated_search_field71' => array( 'location' => 'grid',
'cellId' => 'c161' ),
'search_field_between28' => array( 'location' => 'grid',
'cellId' => 'c161' ),
'integrated_search_field41' => array( 'location' => 'grid',
'cellId' => 'c100' ),
'search_field_between15' => array( 'location' => 'grid',
'cellId' => 'c100' ),
'integrated_search_field64' => array( 'location' => 'grid',
'cellId' => 'c101' ),
'search_field_between24' => array( 'location' => 'grid',
'cellId' => 'c101' ),
'search_field_label1' => array( 'location' => 'grid',
'cellId' => 'c98' ),
'search_field_options1' => array( 'location' => 'grid',
'cellId' => 'c105' ),
'integrated_search_field45' => array( 'location' => 'grid',
'cellId' => 'c106' ),
'search_field_between1' => array( 'location' => 'grid',
'cellId' => 'c106' ) ),
'itemVisiblity' => array( 'menu' => 3,
'loginform_login' => 3,
'username_button' => 3 ) ),
'itemsByType' => array( 'search_header' => array( 'search_header' ),
'search_search' => array( 'search_search',
'search_search1' ),
'search_reset' => array( 'search_reset',
'search_reset1' ),
'search_back_list' => array( 'search_back_list' ),
'search_cancel' => array( 'search_cancel' ),
'search_field_label' => array( 'search_field_label1',
'search_field_label5',
'search_field_label34',
'search_field_label4',
'search_field_label2',
'search_field_label3',
'search_field_label7',
'search_field_label6',
'search_field_label15',
'search_field_label24',
'search_field_label27',
'search_field_label32',
'search_field_label33',
'search_field_label11',
'search_field_label14',
'search_field_label10',
'search_field_label28',
'search_field_label13',
'search_field_label12',
'search_field_label35',
'search_field_label36',
'search_field_label8',
'search_field_label9',
'search_field_label16' ),
'search_field_options' => array( 'search_field_options34',
'search_field_options2',
'search_field_options3',
'search_field_options1',
'search_field_options5',
'search_field_options7',
'search_field_options4',
'search_field_options6',
'search_field_options15',
'search_field_options24',
'search_field_options27',
'search_field_options32',
'search_field_options33',
'search_field_options11',
'search_field_options14',
'search_field_options13',
'search_field_options10',
'search_field_options28',
'search_field_options12',
'search_field_options35',
'search_field_options36',
'search_field_options8',
'search_field_options9',
'search_field_options16' ),
'search_field' => array( 'integrated_search_field70',
'integrated_search_field45',
'integrated_search_field2',
'integrated_search_field77',
'integrated_search_field3',
'integrated_search_field72',
'integrated_search_field14',
'integrated_search_field46',
'integrated_search_field4',
'integrated_search_field13',
'integrated_search_field78',
'integrated_search_field30',
'integrated_search_field79',
'integrated_search_field80',
'integrated_search_field26',
'integrated_search_field29',
'integrated_search_field35',
'integrated_search_field24',
'integrated_search_field7',
'integrated_search_field71',
'integrated_search_field41',
'integrated_search_field64',
'integrated_search_field',
'integrated_search_field1' ),
'search_field_between' => array( 'search_field_between4',
'search_field_between1',
'search_field_between2',
'search_field_between3',
'search_field_between5',
'search_field_between7',
'search_field_between27',
'search_field_between6',
'search_field_between34',
'search_field_between32',
'search_field_between33',
'search_field_between14',
'search_field_between11',
'search_field_between13',
'search_field_between10',
'search_field_between28',
'search_field_between12',
'search_field_between15',
'search_field_between24',
'search_field_between35',
'search_field_between36',
'search_field_between8',
'search_field_between9',
'search_field_between16' ),
'text' => array( 'text3',
'text1',
'text2',
'text' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'logout_link' => array( 'logout_link' ),
'integrated_search_field' => array( 'integrated_search_field5',
'integrated_search_field6',
'integrated_search_field8' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c14' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array( 'callPhone_fieldblock' ),
'items' => array( 'search_field_label36' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c15' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'search_field_options36' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c63' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_search_field',
'search_field_between36' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array( 'callDate_fieldblock' ),
'items' => array( 'search_field_label35' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c27' => array( 'cols' => array( 4 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'search_field_options35' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c22' => array( 'cols' => array( 5 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_search_field1',
'search_field_between35' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c58' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c59' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c60' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c98' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array( 'applicationType_fieldblock' ),
'items' => array( 'search_field_label1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c105' => array( 'cols' => array( 4 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'search_field_options1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c106' => array( 'cols' => array( 5 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_search_field45',
'search_field_between1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c17' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array( 'applicationAgentStatus_fieldblock' ),
'items' => array( 'search_field_label4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c62' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'search_field_options4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c18' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_search_field70',
'search_field_between4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c19' => array( 'cols' => array( 3 ),
'rows' => array( 2 ),
'tags' => array( 'applicationStatusId_fieldblock' ),
'items' => array( 'search_field_label2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c24' => array( 'cols' => array( 4 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'search_field_options2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c23' => array( 'cols' => array( 5 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_search_field2',
'search_field_between2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c117' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c116' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c115' => array( 'cols' => array( 2 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c20' => array( 'cols' => array( 3 ),
'rows' => array( 3 ),
'tags' => array( 'applicationLastStatusDate_fieldblock' ),
'items' => array( 'search_field_label3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c26' => array( 'cols' => array( 4 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'search_field_options3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c25' => array( 'cols' => array( 5 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_search_field77',
'search_field_between3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c118' => array( 'cols' => array( 0,
1 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'text3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c121' => array( 'cols' => array( 2 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c122' => array( 'cols' => array( 3 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c123' => array( 'cols' => array( 4 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c124' => array( 'cols' => array( 5 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 0 ),
'rows' => array( 5 ),
'tags' => array( 'applicantName_fieldblock' ),
'items' => array( 'search_field_label5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c32' => array( 'cols' => array( 1 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'search_field_options5' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c31' => array( 'cols' => array( 2 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'integrated_search_field3',
'search_field_between5' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c69' => array( 'cols' => array( 3 ),
'rows' => array( 5 ),
'tags' => array( 'applicantPhone_fieldblock' ),
'items' => array( 'search_field_label16' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c68' => array( 'cols' => array( 4 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'search_field_options16' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c87' => array( 'cols' => array( 5 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'integrated_search_field13',
'search_field_between16' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c80' => array( 'cols' => array( 0 ),
'rows' => array( 6 ),
'tags' => array( 'applicantIdNumber_fieldblock' ),
'items' => array( 'search_field_label7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c81' => array( 'cols' => array( 1 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array( 'search_field_options7' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c82' => array( 'cols' => array( 2 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array( 'integrated_search_field4',
'search_field_between7' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c90' => array( 'cols' => array( 3 ),
'rows' => array( 6 ),
'tags' => array( 'applicantMobile_fieldblock' ),
'items' => array( 'search_field_label9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c92' => array( 'cols' => array( 4 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array( 'search_field_options9' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c93' => array( 'cols' => array( 5 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array( 'integrated_search_field14',
'search_field_between9' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c28' => array( 'cols' => array( 0 ),
'rows' => array( 7 ),
'tags' => array( 'applicantTaxRegistrationNumber_fieldblock' ),
'items' => array( 'search_field_label6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c36' => array( 'cols' => array( 1 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array( 'search_field_options6' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c35' => array( 'cols' => array( 2 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array( 'integrated_search_field7',
'search_field_between6' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c16' => array( 'cols' => array( 3 ),
'rows' => array( 7 ),
'tags' => array( 'applicantWorkPhone_fieldblock' ),
'items' => array( 'search_field_label8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c70' => array( 'cols' => array( 4 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array( 'search_field_options8' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c71' => array( 'cols' => array( 5 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array( 'integrated_search_field46',
'search_field_between8' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c30' => array( 'cols' => array( 0 ),
'rows' => array( 8 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c40' => array( 'cols' => array( 1 ),
'rows' => array( 8 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c39' => array( 'cols' => array( 2 ),
'rows' => array( 8 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c65' => array( 'cols' => array( 3 ),
'rows' => array( 8 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c74' => array( 'cols' => array( 4 ),
'rows' => array( 8 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c75' => array( 'cols' => array( 5 ),
'rows' => array( 8 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c148' => array( 'cols' => array( 0 ),
'rows' => array( 9 ),
'tags' => array(  ),
'items' => array( 'text' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c155' => array( 'cols' => array( 1 ),
'rows' => array( 9 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c156' => array( 'cols' => array( 2 ),
'rows' => array( 9 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c157' => array( 'cols' => array( 3 ),
'rows' => array( 9 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c158' => array( 'cols' => array( 4 ),
'rows' => array( 9 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c159' => array( 'cols' => array( 5 ),
'rows' => array( 9 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c142' => array( 'cols' => array( 0 ),
'rows' => array( 10 ),
'tags' => array( 'powerAddress_fieldblock' ),
'items' => array( 'search_field_label10' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c149' => array( 'cols' => array( 1 ),
'rows' => array( 10 ),
'tags' => array(  ),
'items' => array( 'search_field_options10' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c150' => array( 'cols' => array( 2 ),
'rows' => array( 10 ),
'tags' => array(  ),
'items' => array( 'integrated_search_field24',
'search_field_between10' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c151' => array( 'cols' => array( 3 ),
'rows' => array( 10 ),
'tags' => array( 'voltonPlan_fieldblock' ),
'items' => array( 'search_field_label12' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c152' => array( 'cols' => array( 4 ),
'rows' => array( 10 ),
'tags' => array(  ),
'items' => array( 'search_field_options12' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c153' => array( 'cols' => array( 5 ),
'rows' => array( 10 ),
'tags' => array(  ),
'items' => array( 'integrated_search_field35',
'search_field_between12' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c49' => array( 'cols' => array( 0 ),
'rows' => array( 11 ),
'tags' => array( 'powerPostalCode_fieldblock' ),
'items' => array( 'search_field_label11' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c143' => array( 'cols' => array( 1 ),
'rows' => array( 11 ),
'tags' => array(  ),
'items' => array( 'search_field_options11' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c144' => array( 'cols' => array( 2 ),
'rows' => array( 11 ),
'tags' => array(  ),
'items' => array( 'integrated_search_field26',
'search_field_between11' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c145' => array( 'cols' => array( 3 ),
'rows' => array( 11 ),
'tags' => array( 'powerSupplyNumber_fieldblock' ),
'items' => array( 'search_field_label13' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c146' => array( 'cols' => array( 4 ),
'rows' => array( 11 ),
'tags' => array(  ),
'items' => array( 'search_field_options13' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c147' => array( 'cols' => array( 5 ),
'rows' => array( 11 ),
'tags' => array(  ),
'items' => array( 'integrated_search_field29',
'search_field_between13' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c33' => array( 'cols' => array( 0 ),
'rows' => array( 12 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c94' => array( 'cols' => array( 1 ),
'rows' => array( 12 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c66' => array( 'cols' => array( 2 ),
'rows' => array( 12 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c77' => array( 'cols' => array( 3 ),
'rows' => array( 12 ),
'tags' => array( 'powerMeterNumber_fieldblock' ),
'items' => array( 'search_field_label14' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c76' => array( 'cols' => array( 4 ),
'rows' => array( 12 ),
'tags' => array(  ),
'items' => array( 'search_field_options14' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c91' => array( 'cols' => array( 5 ),
'rows' => array( 12 ),
'tags' => array(  ),
'items' => array( 'integrated_search_field30',
'search_field_between14' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c21' => array( 'cols' => array( 0 ),
'rows' => array( 13 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c46' => array( 'cols' => array( 1 ),
'rows' => array( 13 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c47' => array( 'cols' => array( 2 ),
'rows' => array( 13 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c48' => array( 'cols' => array( 3 ),
'rows' => array( 13 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c54' => array( 'cols' => array( 4 ),
'rows' => array( 13 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c55' => array( 'cols' => array( 5 ),
'rows' => array( 13 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c119' => array( 'cols' => array( 0 ),
'rows' => array( 14 ),
'tags' => array(  ),
'items' => array( 'text1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c131' => array( 'cols' => array( 1 ),
'rows' => array( 14 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c132' => array( 'cols' => array( 2 ),
'rows' => array( 14 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c133' => array( 'cols' => array( 3 ),
'rows' => array( 14 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c134' => array( 'cols' => array( 4 ),
'rows' => array( 14 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c135' => array( 'cols' => array( 5 ),
'rows' => array( 14 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c67' => array( 'cols' => array( 0 ),
'rows' => array( 15 ),
'tags' => array( 'ngAddress_fieldblock' ),
'items' => array( 'search_field_label15' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c61' => array( 'cols' => array( 1 ),
'rows' => array( 15 ),
'tags' => array(  ),
'items' => array( 'search_field_options15' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c100' => array( 'cols' => array( 2 ),
'rows' => array( 15 ),
'tags' => array(  ),
'items' => array( 'integrated_search_field41',
'search_field_between15' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c89' => array( 'cols' => array( 3 ),
'rows' => array( 15 ),
'tags' => array( 'ngMeterType_fieldblock' ),
'items' => array( 'search_field_label27' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 4 ),
'rows' => array( 15 ),
'tags' => array(  ),
'items' => array( 'search_field_options27' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c42' => array( 'cols' => array( 5 ),
'rows' => array( 15 ),
'tags' => array(  ),
'items' => array( 'integrated_search_field72',
'search_field_between27' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c79' => array( 'cols' => array( 0 ),
'rows' => array( 16 ),
'tags' => array( 'ngPostalCode_fieldblock' ),
'items' => array( 'search_field_label24' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c78' => array( 'cols' => array( 1 ),
'rows' => array( 16 ),
'tags' => array(  ),
'items' => array( 'search_field_options24' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c101' => array( 'cols' => array( 2 ),
'rows' => array( 16 ),
'tags' => array(  ),
'items' => array( 'integrated_search_field64',
'search_field_between24' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c154' => array( 'cols' => array( 3 ),
'rows' => array( 16 ),
'tags' => array( 'ngMeterNumber_fieldblock' ),
'items' => array( 'search_field_label28' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c160' => array( 'cols' => array( 4 ),
'rows' => array( 16 ),
'tags' => array(  ),
'items' => array( 'search_field_options28' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c161' => array( 'cols' => array( 5 ),
'rows' => array( 16 ),
'tags' => array(  ),
'items' => array( 'integrated_search_field71',
'search_field_between28' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c88' => array( 'cols' => array( 0 ),
'rows' => array( 17 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c86' => array( 'cols' => array( 1 ),
'rows' => array( 17 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c104' => array( 'cols' => array( 2 ),
'rows' => array( 17 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c97' => array( 'cols' => array( 3 ),
'rows' => array( 17 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c99' => array( 'cols' => array( 4 ),
'rows' => array( 17 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c1' => array( 'cols' => array( 5 ),
'rows' => array( 17 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c130' => array( 'cols' => array( 0 ),
'rows' => array( 18 ),
'tags' => array(  ),
'items' => array( 'text2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c137' => array( 'cols' => array( 1,
2 ),
'rows' => array( 18 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c139' => array( 'cols' => array( 3 ),
'rows' => array( 18 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c140' => array( 'cols' => array( 4 ),
'rows' => array( 18 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c141' => array( 'cols' => array( 5 ),
'rows' => array( 18 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c12' => array( 'cols' => array( 0 ),
'rows' => array( 19 ),
'tags' => array( 'applicationContactMethod_fieldblock' ),
'items' => array( 'search_field_label34' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c13' => array( 'cols' => array( 1 ),
'rows' => array( 19 ),
'tags' => array(  ),
'items' => array( 'search_field_options34' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c34' => array( 'cols' => array( 2 ),
'rows' => array( 19 ),
'tags' => array(  ),
'items' => array( 'integrated_search_field78',
'search_field_between34' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c110' => array( 'cols' => array( 3 ),
'rows' => array( 19 ),
'tags' => array( 'applicationCourier_fieldblock' ),
'items' => array( 'search_field_label32' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c109' => array( 'cols' => array( 4 ),
'rows' => array( 19 ),
'tags' => array(  ),
'items' => array( 'search_field_options32' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c111' => array( 'cols' => array( 5 ),
'rows' => array( 19 ),
'tags' => array(  ),
'items' => array( 'integrated_search_field79',
'search_field_between32' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c41' => array( 'cols' => array( 0 ),
'rows' => array( 20 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c45' => array( 'cols' => array( 1,
2 ),
'rows' => array( 20 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c113' => array( 'cols' => array( 3 ),
'rows' => array( 20 ),
'tags' => array( 'applicationCourierDate_fieldblock' ),
'items' => array( 'search_field_label33' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c112' => array( 'cols' => array( 4 ),
'rows' => array( 20 ),
'tags' => array(  ),
'items' => array( 'search_field_options33' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c114' => array( 'cols' => array( 5 ),
'rows' => array( 20 ),
'tags' => array(  ),
'items' => array( 'integrated_search_field80',
'search_field_between33' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 0,
1,
2 ),
'rows' => array( 21 ),
'tags' => array(  ),
'items' => array( 'integrated_search_field5',
'integrated_search_field6',
'integrated_search_field8' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 3,
4,
5 ),
'rows' => array( 21 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 6,
'height' => 22 ) ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'search',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'search',
'type' => 'search',
'layoutId' => 'topbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'topbar-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ),
array( 'cell' => 'c3' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'logo' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'menu' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c3' => array( 'model' => 'c3',
'items' => array( 'loginform_login',
'username_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'search-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'search_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array( 'search_search1',
'search_reset1' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'align' => 'right' ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'search-above-grid',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'search-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'search_search',
'search_reset',
'search_back_list',
'search_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-search',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c14',
'colspan' => 1 ),
array( 'cell' => 'c15' ),
array( 'cell' => 'c63' ),
array( 'cell' => 'c7',
'colspan' => 1 ),
array( 'cell' => 'c27' ),
array( 'cell' => 'c22',
'colspan' => 1 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c58' ),
array( 'cell' => 'c59' ),
array( 'cell' => 'c60' ),
array( 'cell' => 'c98' ),
array( 'cell' => 'c105' ),
array( 'cell' => 'c106' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c17',
'colspan' => 1 ),
array( 'cell' => 'c62' ),
array( 'cell' => 'c18',
'colspan' => 1 ),
array( 'cell' => 'c19',
'colspan' => 1 ),
array( 'cell' => 'c24' ),
array( 'cell' => 'c23',
'colspan' => 1 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c117',
'colspan' => 1 ),
array( 'cell' => 'c116' ),
array( 'cell' => 'c115' ),
array( 'cell' => 'c20',
'colspan' => 1 ),
array( 'cell' => 'c26' ),
array( 'cell' => 'c25',
'colspan' => 1 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c118',
'colspan' => 2 ),
array( 'cell' => 'c121' ),
array( 'cell' => 'c122' ),
array( 'cell' => 'c123' ),
array( 'cell' => 'c124' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c8',
'colspan' => 1 ),
array( 'cell' => 'c32' ),
array( 'cell' => 'c31',
'colspan' => 1 ),
array( 'cell' => 'c69',
'colspan' => 1 ),
array( 'cell' => 'c68' ),
array( 'cell' => 'c87' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c80',
'colspan' => 1 ),
array( 'cell' => 'c81' ),
array( 'cell' => 'c82' ),
array( 'cell' => 'c90',
'colspan' => 1 ),
array( 'cell' => 'c92' ),
array( 'cell' => 'c93' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c28',
'colspan' => 1 ),
array( 'cell' => 'c36' ),
array( 'cell' => 'c35',
'colspan' => 1 ),
array( 'cell' => 'c16',
'colspan' => 1 ),
array( 'cell' => 'c70' ),
array( 'cell' => 'c71' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c30',
'colspan' => 1 ),
array( 'cell' => 'c40' ),
array( 'cell' => 'c39' ),
array( 'cell' => 'c65',
'colspan' => 1 ),
array( 'cell' => 'c74' ),
array( 'cell' => 'c75' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c148',
'colspan' => 1 ),
array( 'cell' => 'c155' ),
array( 'cell' => 'c156' ),
array( 'cell' => 'c157' ),
array( 'cell' => 'c158' ),
array( 'cell' => 'c159' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c142',
'colspan' => 1 ),
array( 'cell' => 'c149' ),
array( 'cell' => 'c150' ),
array( 'cell' => 'c151' ),
array( 'cell' => 'c152' ),
array( 'cell' => 'c153' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c49',
'colspan' => 1 ),
array( 'cell' => 'c143' ),
array( 'cell' => 'c144' ),
array( 'cell' => 'c145' ),
array( 'cell' => 'c146' ),
array( 'cell' => 'c147' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c33',
'colspan' => 1 ),
array( 'cell' => 'c94' ),
array( 'cell' => 'c66' ),
array( 'cell' => 'c77',
'colspan' => 1 ),
array( 'cell' => 'c76' ),
array( 'cell' => 'c91' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c21',
'colspan' => 1 ),
array( 'cell' => 'c46' ),
array( 'cell' => 'c47' ),
array( 'cell' => 'c48' ),
array( 'cell' => 'c54' ),
array( 'cell' => 'c55' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c119',
'colspan' => 1 ),
array( 'cell' => 'c131' ),
array( 'cell' => 'c132' ),
array( 'cell' => 'c133' ),
array( 'cell' => 'c134' ),
array( 'cell' => 'c135' ) ) ),
array( 'cells' => array( array( 'cell' => 'c67',
'colspan' => 1 ),
array( 'cell' => 'c61' ),
array( 'cell' => 'c100' ),
array( 'cell' => 'c89',
'colspan' => 1 ),
array( 'cell' => 'c2' ),
array( 'cell' => 'c42' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c79',
'colspan' => 1 ),
array( 'cell' => 'c78' ),
array( 'cell' => 'c101' ),
array( 'cell' => 'c154' ),
array( 'cell' => 'c160' ),
array( 'cell' => 'c161' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c88',
'colspan' => 1 ),
array( 'cell' => 'c86' ),
array( 'cell' => 'c104' ),
array( 'cell' => 'c97' ),
array( 'cell' => 'c99' ),
array( 'cell' => 'c1' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c130',
'colspan' => 1 ),
array( 'cell' => 'c137',
'colspan' => 2 ),
array( 'cell' => 'c139' ),
array( 'cell' => 'c140' ),
array( 'cell' => 'c141' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c12',
'colspan' => 1 ),
array( 'cell' => 'c13' ),
array( 'cell' => 'c34' ),
array( 'cell' => 'c110',
'colspan' => 1 ),
array( 'cell' => 'c109' ),
array( 'cell' => 'c111' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c41',
'colspan' => 1 ),
array( 'cell' => 'c45',
'colspan' => 2 ),
array( 'cell' => 'c113',
'colspan' => 1 ),
array( 'cell' => 'c112' ),
array( 'cell' => 'c114' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c4',
'colspan' => 3 ),
array( 'cell' => 'c5',
'colspan' => 3 ) ) ) ),
'cells' => array( 'c4' => array( 'model' => 'c3',
'items' => array( 'integrated_search_field5',
'integrated_search_field6',
'integrated_search_field8' ) ),
'c5' => array( 'model' => 'c3',
'items' => array(  ) ),
'c7' => array( 'model' => 'c5',
'items' => array( 'search_field_label35' ),
'width' => '80px',
'align' => 'right' ),
'c8' => array( 'model' => 'c5',
'items' => array( 'search_field_label5' ),
'width' => '80px',
'align' => 'right' ),
'c12' => array( 'model' => 'c5',
'items' => array( 'search_field_label34' ),
'width' => '80px',
'align' => 'right' ),
'c13' => array( 'model' => 'c5',
'items' => array( 'search_field_options34' ),
'width' => '150px',
'orientation' => 'vertical' ),
'c14' => array( 'model' => 'c5',
'items' => array( 'search_field_label36' ),
'width' => '80px',
'align' => 'right' ),
'c15' => array( 'model' => 'c5',
'items' => array( 'search_field_options36' ),
'width' => '50px' ),
'c16' => array( 'model' => 'c5',
'items' => array( 'search_field_label8' ),
'width' => '80px',
'align' => 'right' ),
'c17' => array( 'model' => 'c5',
'items' => array( 'search_field_label4' ),
'width' => '80px',
'align' => 'right' ),
'c18' => array( 'model' => 'c5',
'items' => array( 'integrated_search_field70',
'search_field_between4' ),
'width' => '150px',
'orientation' => 'vertical' ),
'c19' => array( 'model' => 'c5',
'items' => array( 'search_field_label2' ),
'width' => '80px',
'align' => 'right' ),
'c20' => array( 'model' => 'c5',
'items' => array( 'search_field_label3' ),
'width' => '80px',
'align' => 'right' ),
'c22' => array( 'model' => 'c5',
'items' => array( 'integrated_search_field1',
'search_field_between35' ),
'width' => '150px',
'orientation' => 'vertical' ),
'c23' => array( 'model' => 'c5',
'items' => array( 'integrated_search_field2',
'search_field_between2' ),
'width' => '150px',
'orientation' => 'vertical' ),
'c24' => array( 'model' => 'c5',
'items' => array( 'search_field_options2' ),
'width' => '50px' ),
'c25' => array( 'model' => 'c5',
'items' => array( 'integrated_search_field77',
'search_field_between3' ),
'width' => '150px',
'orientation' => 'vertical' ),
'c26' => array( 'model' => 'c5',
'items' => array( 'search_field_options3' ),
'width' => '50px' ),
'c27' => array( 'model' => 'c5',
'items' => array( 'search_field_options35' ),
'width' => '50px' ),
'c28' => array( 'model' => 'c5',
'items' => array( 'search_field_label6' ),
'width' => '80px',
'align' => 'right' ),
'c30' => array( 'model' => 'c5',
'items' => array(  ),
'width' => '80px',
'align' => 'right',
'persistent' => true ),
'c31' => array( 'model' => 'c5',
'items' => array( 'integrated_search_field3',
'search_field_between5' ),
'width' => '150px',
'orientation' => 'vertical' ),
'c32' => array( 'model' => 'c5',
'items' => array( 'search_field_options5' ),
'width' => '50px' ),
'c33' => array( 'model' => 'c5',
'items' => array(  ),
'persistent' => true,
'width' => '80px',
'align' => 'right' ),
'c35' => array( 'model' => 'c5',
'items' => array( 'integrated_search_field7',
'search_field_between6' ),
'width' => '150px',
'orientation' => 'vertical' ),
'c36' => array( 'model' => 'c5',
'items' => array( 'search_field_options6' ),
'width' => '50px' ),
'c39' => array( 'model' => 'c5',
'items' => array(  ),
'width' => '150px',
'orientation' => 'vertical',
'persistent' => true ),
'c40' => array( 'model' => 'c5',
'items' => array(  ),
'width' => '50px',
'persistent' => true ),
'c42' => array( 'model' => 'c5',
'items' => array( 'integrated_search_field72',
'search_field_between27' ),
'width' => '150px',
'orientation' => 'vertical' ),
'c62' => array( 'model' => 'c5',
'items' => array( 'search_field_options4' ),
'width' => '50px' ),
'c63' => array( 'model' => 'c5',
'items' => array( 'integrated_search_field',
'search_field_between36' ),
'width' => '150px',
'orientation' => 'vertical' ),
'c65' => array( 'model' => 'c5',
'items' => array(  ),
'width' => '80px',
'align' => 'right',
'persistent' => true ),
'c66' => array( 'model' => 'c5',
'items' => array(  ),
'persistent' => true,
'width' => '150px',
'orientation' => 'vertical' ),
'c68' => array( 'model' => 'c5',
'items' => array( 'search_field_options16' ),
'width' => '50px' ),
'c69' => array( 'model' => 'c5',
'items' => array( 'search_field_label16' ),
'width' => '80px',
'align' => 'right' ),
'c70' => array( 'model' => 'c5',
'items' => array( 'search_field_options8' ),
'width' => '50px' ),
'c71' => array( 'model' => 'c5',
'items' => array( 'integrated_search_field46',
'search_field_between8' ),
'width' => '150px',
'orientation' => 'vertical' ),
'c74' => array( 'model' => 'c5',
'items' => array(  ),
'width' => '50px',
'persistent' => true ),
'c75' => array( 'model' => 'c5',
'items' => array(  ),
'width' => '150px',
'orientation' => 'vertical',
'persistent' => true ),
'c76' => array( 'model' => 'c5',
'items' => array( 'search_field_options14' ),
'width' => '50px' ),
'c77' => array( 'model' => 'c5',
'items' => array( 'search_field_label14' ),
'width' => '80px',
'align' => 'right' ),
'c80' => array( 'model' => 'c5',
'items' => array( 'search_field_label7' ),
'width' => '80px',
'align' => 'right' ),
'c81' => array( 'model' => 'c5',
'items' => array( 'search_field_options7' ),
'width' => '50px' ),
'c82' => array( 'model' => 'c5',
'items' => array( 'integrated_search_field4',
'search_field_between7' ),
'width' => '150px',
'orientation' => 'vertical' ),
'c87' => array( 'model' => 'c5',
'items' => array( 'integrated_search_field13',
'search_field_between16' ),
'width' => '150px',
'orientation' => 'vertical' ),
'c90' => array( 'model' => 'c5',
'items' => array( 'search_field_label9' ),
'width' => '80px',
'align' => 'right' ),
'c92' => array( 'model' => 'c5',
'items' => array( 'search_field_options9' ),
'width' => '50px' ),
'c93' => array( 'model' => 'c5',
'items' => array( 'integrated_search_field14',
'search_field_between9' ),
'width' => '150px',
'orientation' => 'vertical' ),
'c91' => array( 'model' => 'c5',
'items' => array( 'integrated_search_field30',
'search_field_between14' ),
'width' => '150px',
'orientation' => 'vertical' ),
'c94' => array( 'model' => 'c5',
'items' => array(  ),
'persistent' => true,
'width' => '50px' ),
'c34' => array( 'model' => 'c5',
'items' => array( 'integrated_search_field78',
'search_field_between34' ),
'width' => '150px',
'orientation' => 'vertical' ),
'c61' => array( 'model' => 'c5',
'items' => array( 'search_field_options15' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'width' => '150px',
'orientation' => 'vertical' ),
'c67' => array( 'model' => 'c5',
'items' => array( 'search_field_label15' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'width' => '50px',
'align' => 'right' ),
'c78' => array( 'model' => 'c5',
'items' => array( 'search_field_options24' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'width' => '150px',
'orientation' => 'vertical' ),
'c79' => array( 'model' => 'c5',
'items' => array( 'search_field_label24' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'width' => '50px',
'align' => 'right' ),
'c86' => array( 'model' => 'c5',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'width' => '150px',
'orientation' => 'vertical',
'persistent' => true ),
'c88' => array( 'model' => 'c5',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'width' => '50px',
'align' => 'right',
'persistent' => true ),
'c2' => array( 'model' => 'c5',
'items' => array( 'search_field_options27' ),
'width' => '50px' ),
'c89' => array( 'model' => 'c5',
'items' => array( 'search_field_label27' ),
'width' => '80px',
'align' => 'right' ),
'c97' => array( 'model' => 'c5',
'items' => array(  ),
'width' => '80px',
'align' => 'right',
'persistent' => true ),
'c99' => array( 'model' => 'c5',
'items' => array(  ),
'width' => '50px',
'persistent' => true ),
'c109' => array( 'model' => 'c5',
'items' => array( 'search_field_options32' ),
'width' => '50px' ),
'c110' => array( 'model' => 'c5',
'items' => array( 'search_field_label32' ),
'width' => '80px',
'align' => 'right' ),
'c111' => array( 'model' => 'c5',
'items' => array( 'integrated_search_field79',
'search_field_between32' ),
'width' => '150px',
'orientation' => 'vertical' ),
'c112' => array( 'model' => 'c5',
'items' => array( 'search_field_options33' ),
'width' => '50px' ),
'c113' => array( 'model' => 'c5',
'items' => array( 'search_field_label33' ),
'width' => '80px',
'align' => 'right' ),
'c114' => array( 'model' => 'c5',
'items' => array( 'integrated_search_field80',
'search_field_between33' ),
'width' => '150px',
'orientation' => 'vertical' ),
'c115' => array( 'model' => 'c5',
'items' => array(  ),
'width' => '150px',
'orientation' => 'vertical',
'persistent' => true ),
'c116' => array( 'model' => 'c5',
'items' => array(  ),
'width' => '50px',
'persistent' => true ),
'c117' => array( 'model' => 'c5',
'items' => array(  ),
'width' => '80px',
'align' => 'right',
'persistent' => true ),
'c118' => array( 'model' => 'c5',
'items' => array( 'text3' ),
'width' => '80px',
'background' => '#e6f7ff' ),
'c121' => array( 'model' => 'c5',
'items' => array(  ),
'background' => '#e6f7ff' ),
'c122' => array( 'model' => 'c5',
'items' => array(  ),
'background' => '#e6f7ff' ),
'c123' => array( 'model' => 'c5',
'items' => array(  ),
'background' => '#e6f7ff' ),
'c124' => array( 'model' => 'c5',
'items' => array(  ),
'background' => '#e6f7ff' ),
'c119' => array( 'model' => 'c5',
'items' => array( 'text1' ),
'width' => '80px',
'background' => '#e6f7ff' ),
'c131' => array( 'model' => 'c5',
'items' => array(  ),
'background' => '#e6f7ff' ),
'c132' => array( 'model' => 'c5',
'items' => array(  ),
'background' => '#e6f7ff' ),
'c133' => array( 'model' => 'c5',
'items' => array(  ),
'background' => '#e6f7ff' ),
'c134' => array( 'model' => 'c5',
'items' => array(  ),
'background' => '#e6f7ff' ),
'c135' => array( 'model' => 'c5',
'items' => array(  ),
'orientation' => 'vertical',
'background' => '#e6f7ff' ),
'c130' => array( 'model' => 'c5',
'items' => array( 'text2' ),
'width' => '80px',
'background' => '#e6f7ff' ),
'c137' => array( 'model' => 'c5',
'items' => array(  ),
'background' => '#e6f7ff' ),
'c139' => array( 'model' => 'c5',
'items' => array(  ),
'background' => '#e6f7ff' ),
'c140' => array( 'model' => 'c5',
'items' => array(  ),
'background' => '#e6f7ff' ),
'c141' => array( 'model' => 'c5',
'items' => array(  ),
'orientation' => 'vertical',
'background' => '#e6f7ff' ),
'c41' => array( 'model' => 'c5',
'items' => array(  ),
'width' => '80px',
'align' => 'right' ),
'c45' => array( 'model' => 'c5',
'items' => array(  ),
'width' => '150px',
'orientation' => 'vertical' ),
'c49' => array( 'model' => 'c5',
'items' => array( 'search_field_label11' ),
'align' => 'right' ),
'c143' => array( 'model' => 'c5',
'items' => array( 'search_field_options11' ) ),
'c144' => array( 'model' => 'c5',
'items' => array( 'integrated_search_field26',
'search_field_between11' ) ),
'c145' => array( 'model' => 'c5',
'items' => array( 'search_field_label13' ),
'align' => 'right' ),
'c146' => array( 'model' => 'c5',
'items' => array( 'search_field_options13' ) ),
'c147' => array( 'model' => 'c5',
'items' => array( 'integrated_search_field29',
'search_field_between13' ),
'orientation' => 'vertical' ),
'c142' => array( 'model' => 'c5',
'items' => array( 'search_field_label10' ),
'align' => 'right' ),
'c149' => array( 'model' => 'c5',
'items' => array( 'search_field_options10' ) ),
'c150' => array( 'model' => 'c5',
'items' => array( 'integrated_search_field24',
'search_field_between10' ) ),
'c151' => array( 'model' => 'c5',
'items' => array( 'search_field_label12' ),
'align' => 'right' ),
'c152' => array( 'model' => 'c5',
'items' => array( 'search_field_options12' ) ),
'c153' => array( 'model' => 'c5',
'items' => array( 'integrated_search_field35',
'search_field_between12' ),
'orientation' => 'vertical' ),
'c148' => array( 'model' => 'c5',
'items' => array( 'text' ),
'background' => '#e6f7ff' ),
'c155' => array( 'model' => 'c5',
'items' => array(  ),
'background' => '#e6f7ff' ),
'c156' => array( 'model' => 'c5',
'items' => array(  ),
'background' => '#e6f7ff' ),
'c157' => array( 'model' => 'c5',
'items' => array(  ),
'background' => '#e6f7ff' ),
'c158' => array( 'model' => 'c5',
'items' => array(  ),
'background' => '#e6f7ff' ),
'c159' => array( 'model' => 'c5',
'items' => array(  ),
'orientation' => 'vertical',
'background' => '#e6f7ff' ),
'c154' => array( 'model' => 'c5',
'items' => array( 'search_field_label28' ),
'width' => '80px',
'align' => 'right' ),
'c160' => array( 'model' => 'c5',
'items' => array( 'search_field_options28' ),
'width' => '50px' ),
'c161' => array( 'model' => 'c5',
'items' => array( 'integrated_search_field71',
'search_field_between28' ),
'width' => '150px',
'orientation' => 'vertical' ),
'c1' => array( 'model' => 'c5',
'items' => array(  ),
'width' => '150px',
'orientation' => 'vertical',
'persistent' => true ),
'c21' => array( 'model' => 'c5',
'items' => array(  ),
'width' => '80px',
'persistent' => true ),
'c46' => array( 'model' => 'c5',
'items' => array(  ),
'persistent' => true ),
'c47' => array( 'model' => 'c5',
'items' => array(  ),
'persistent' => true ),
'c48' => array( 'model' => 'c5',
'items' => array(  ),
'align' => 'right',
'persistent' => true ),
'c54' => array( 'model' => 'c5',
'items' => array(  ),
'persistent' => true ),
'c55' => array( 'model' => 'c5',
'items' => array(  ),
'orientation' => 'vertical',
'persistent' => true ),
'c100' => array( 'model' => 'c5',
'items' => array( 'integrated_search_field41',
'search_field_between15' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'width' => '150px',
'orientation' => 'vertical' ),
'c101' => array( 'model' => 'c5',
'items' => array( 'integrated_search_field64',
'search_field_between24' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'width' => '150px',
'orientation' => 'vertical' ),
'c104' => array( 'model' => 'c5',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'width' => '150px',
'orientation' => 'vertical',
'persistent' => true ),
'c58' => array( 'model' => 'c5',
'items' => array(  ),
'align' => 'right' ),
'c59' => array( 'model' => 'c5',
'items' => array(  ) ),
'c60' => array( 'model' => 'c5',
'items' => array(  ),
'orientation' => 'vertical' ),
'c98' => array( 'model' => 'c5',
'items' => array( 'search_field_label1' ),
'align' => 'right' ),
'c105' => array( 'model' => 'c5',
'items' => array( 'search_field_options1' ) ),
'c106' => array( 'model' => 'c5',
'items' => array( 'integrated_search_field45',
'search_field_between1' ),
'orientation' => 'vertical' ) ),
'deferredItems' => array(  ),
'separateLabels' => false ) ),
'items' => array( 'search_header' => array( 'type' => 'search_header',
'title' => array( 'page' => 'search',
'table' => 'dbo.voltonApplicationsBackofficeView',
'type' => 7 ),
'bold' => true,
'color' => '#0c15eb' ),
'search_search' => array( 'type' => 'search_search' ),
'search_reset' => array( 'type' => 'search_reset',
'label' => array( 'type' => 0,
'text' => 'Καθαρισμός Πεδίων' ) ),
'search_back_list' => array( 'type' => 'search_back_list' ),
'search_cancel' => array( 'type' => 'search_cancel' ),
'search_field_label1' => array( 'type' => 'search_field_label',
'field' => 'applicationType',
'separated' => true ),
'search_field_label5' => array( 'type' => 'search_field_label',
'field' => 'applicantName',
'separated' => true ),
'search_field_label34' => array( 'type' => 'search_field_label',
'field' => 'applicationContactMethod',
'separated' => true ),
'search_field_options34' => array( 'type' => 'search_field_options',
'field' => 'applicationContactMethod',
'separated' => true ),
'search_field_label4' => array( 'type' => 'search_field_label',
'field' => 'applicationAgentStatus',
'separated' => true ),
'integrated_search_field70' => array( 'field' => 'applicationAgentStatus',
'type' => 'search_field',
'orientation' => 0,
'required' => false,
'joined' => false,
'separated' => true ),
'search_field_between4' => array( 'type' => 'search_field_between',
'field' => 'applicationAgentStatus',
'separated' => true ),
'search_field_label2' => array( 'type' => 'search_field_label',
'field' => 'applicationStatusId',
'separated' => true ),
'search_field_label3' => array( 'type' => 'search_field_label',
'field' => 'applicationLastStatusDate',
'separated' => true ),
'integrated_search_field45' => array( 'field' => 'applicationType',
'type' => 'search_field',
'orientation' => 0,
'required' => false,
'joined' => false,
'separated' => true ),
'search_field_between1' => array( 'type' => 'search_field_between',
'field' => 'applicationType',
'separated' => true ),
'integrated_search_field2' => array( 'field' => 'applicationStatusId',
'type' => 'search_field',
'orientation' => 0,
'required' => false,
'joined' => false,
'separated' => true ),
'search_field_between2' => array( 'type' => 'search_field_between',
'field' => 'applicationStatusId',
'separated' => true ),
'search_field_options2' => array( 'type' => 'search_field_options',
'field' => 'applicationStatusId',
'separated' => true ),
'integrated_search_field77' => array( 'field' => 'applicationLastStatusDate',
'type' => 'search_field',
'orientation' => 0,
'required' => false,
'joined' => false,
'separated' => true ),
'search_field_between3' => array( 'type' => 'search_field_between',
'field' => 'applicationLastStatusDate',
'separated' => true ),
'search_field_options3' => array( 'type' => 'search_field_options',
'field' => 'applicationLastStatusDate',
'separated' => true ),
'search_field_options1' => array( 'type' => 'search_field_options',
'field' => 'applicationType',
'separated' => true ),
'search_field_label7' => array( 'type' => 'search_field_label',
'field' => 'applicantIdNumber',
'separated' => true ),
'integrated_search_field3' => array( 'field' => 'applicantName',
'type' => 'search_field',
'orientation' => 0,
'required' => false,
'joined' => false,
'separated' => true ),
'search_field_between5' => array( 'type' => 'search_field_between',
'field' => 'applicantName',
'separated' => true ),
'search_field_options5' => array( 'type' => 'search_field_options',
'field' => 'applicantName',
'separated' => true ),
'search_field_between7' => array( 'type' => 'search_field_between',
'field' => 'applicantIdNumber',
'separated' => true ),
'search_field_options7' => array( 'type' => 'search_field_options',
'field' => 'applicantIdNumber',
'separated' => true ),
'integrated_search_field72' => array( 'field' => 'ngMeterType',
'type' => 'search_field',
'orientation' => 0,
'required' => false,
'joined' => false,
'separated' => true ),
'search_field_between27' => array( 'type' => 'search_field_between',
'field' => 'ngMeterType',
'separated' => true ),
'search_field_options4' => array( 'type' => 'search_field_options',
'field' => 'applicationAgentStatus',
'separated' => true ),
'integrated_search_field14' => array( 'field' => 'applicantMobile',
'type' => 'search_field',
'orientation' => 0,
'required' => false,
'joined' => false,
'separated' => true ),
'integrated_search_field46' => array( 'field' => 'applicantWorkPhone',
'type' => 'search_field',
'orientation' => 0,
'required' => false,
'joined' => false,
'separated' => true ),
'integrated_search_field4' => array( 'field' => 'applicantIdNumber',
'type' => 'search_field',
'orientation' => 0,
'required' => false,
'joined' => false,
'separated' => true ),
'search_field_label6' => array( 'type' => 'search_field_label',
'field' => 'applicantTaxRegistrationNumber',
'separated' => true ),
'search_field_options6' => array( 'type' => 'search_field_options',
'field' => 'applicantTaxRegistrationNumber',
'separated' => true ),
'search_field_between6' => array( 'type' => 'search_field_between',
'field' => 'applicantTaxRegistrationNumber',
'separated' => true ),
'integrated_search_field13' => array( 'field' => 'applicantPhone',
'type' => 'search_field',
'orientation' => 0,
'required' => false,
'joined' => false,
'separated' => true ),
'integrated_search_field78' => array( 'field' => 'applicationContactMethod',
'type' => 'search_field',
'orientation' => 0,
'required' => false,
'joined' => false,
'separated' => true ),
'search_field_between34' => array( 'type' => 'search_field_between',
'field' => 'applicationContactMethod',
'separated' => true ),
'search_field_options15' => array( 'type' => 'search_field_options',
'field' => 'ngAddress',
'separated' => true ),
'search_field_label15' => array( 'type' => 'search_field_label',
'field' => 'ngAddress',
'separated' => true ),
'search_field_options24' => array( 'type' => 'search_field_options',
'field' => 'ngPostalCode',
'separated' => true ),
'search_field_label24' => array( 'type' => 'search_field_label',
'field' => 'ngPostalCode',
'separated' => true ),
'search_field_options27' => array( 'type' => 'search_field_options',
'field' => 'ngMeterType',
'separated' => true ),
'search_field_label27' => array( 'type' => 'search_field_label',
'field' => 'ngMeterType',
'separated' => true ),
'integrated_search_field30' => array( 'field' => 'powerMeterNumber',
'type' => 'search_field',
'orientation' => 0,
'required' => false,
'joined' => false,
'separated' => true ),
'search_field_options32' => array( 'type' => 'search_field_options',
'field' => 'applicationCourier',
'separated' => true ),
'search_field_label32' => array( 'type' => 'search_field_label',
'field' => 'applicationCourier',
'separated' => true ),
'integrated_search_field79' => array( 'field' => 'applicationCourier',
'type' => 'search_field',
'orientation' => 0,
'required' => false,
'joined' => false,
'separated' => true ),
'search_field_between32' => array( 'type' => 'search_field_between',
'field' => 'applicationCourier',
'separated' => true ),
'search_field_options33' => array( 'type' => 'search_field_options',
'field' => 'applicationCourierDate',
'separated' => true ),
'search_field_label33' => array( 'type' => 'search_field_label',
'field' => 'applicationCourierDate',
'separated' => true ),
'integrated_search_field80' => array( 'field' => 'applicationCourierDate',
'type' => 'search_field',
'orientation' => 0,
'required' => false,
'joined' => false,
'separated' => true ),
'search_field_between33' => array( 'type' => 'search_field_between',
'field' => 'applicationCourierDate',
'separated' => true ),
'text3' => array( 'type' => 'text',
'label' => array( 'text' => 'ΣΤΟΙΧΕΙΑ ΑΙΤΟΥΝΤΟΣ',
'type' => 0 ),
'editedByRte' => false,
'bold' => true,
'font-size' => '16px' ),
'integrated_search_field26' => array( 'field' => 'powerPostalCode',
'type' => 'search_field',
'orientation' => 0,
'required' => false,
'joined' => false,
'separated' => true ),
'integrated_search_field29' => array( 'field' => 'powerSupplyNumber',
'type' => 'search_field',
'orientation' => 0,
'required' => false,
'joined' => false,
'separated' => true ),
'search_field_between14' => array( 'type' => 'search_field_between',
'field' => 'powerMeterNumber',
'separated' => true ),
'text1' => array( 'type' => 'text',
'label' => array( 'text' => 'ΦΥΣΙΚΟ ΑΕΡΙΟ',
'type' => 0 ),
'editedByRte' => false,
'bold' => true,
'font-size' => '16px' ),
'text2' => array( 'type' => 'text',
'label' => array( 'text' => 'ΔΙΚΑΙΟΛΟΓΗΤΙΚΑ',
'type' => 0 ),
'editedByRte' => false,
'bold' => true,
'font-size' => '16px' ),
'search_field_label11' => array( 'type' => 'search_field_label',
'field' => 'powerPostalCode',
'separated' => true ),
'search_field_options11' => array( 'type' => 'search_field_options',
'field' => 'powerPostalCode',
'separated' => true ),
'search_field_options14' => array( 'type' => 'search_field_options',
'field' => 'powerMeterNumber',
'separated' => true ),
'search_field_between11' => array( 'type' => 'search_field_between',
'field' => 'powerPostalCode',
'separated' => true ),
'search_field_label14' => array( 'type' => 'search_field_label',
'field' => 'powerMeterNumber',
'separated' => true ),
'search_field_between13' => array( 'type' => 'search_field_between',
'field' => 'powerSupplyNumber',
'separated' => true ),
'integrated_search_field35' => array( 'field' => 'voltonPlan',
'type' => 'search_field',
'orientation' => 0,
'required' => false,
'joined' => false,
'separated' => true ),
'search_field_options13' => array( 'type' => 'search_field_options',
'field' => 'powerSupplyNumber',
'separated' => true ),
'search_field_label10' => array( 'type' => 'search_field_label',
'field' => 'powerAddress',
'separated' => true ),
'search_field_options10' => array( 'type' => 'search_field_options',
'field' => 'powerAddress',
'separated' => true ),
'integrated_search_field24' => array( 'field' => 'powerAddress',
'type' => 'search_field',
'orientation' => 0,
'required' => false,
'joined' => false,
'separated' => true ),
'search_field_between10' => array( 'type' => 'search_field_between',
'field' => 'powerAddress',
'separated' => true ),
'integrated_search_field7' => array( 'field' => 'applicantTaxRegistrationNumber',
'type' => 'search_field',
'orientation' => 0,
'required' => false,
'joined' => false,
'separated' => true ),
'text' => array( 'type' => 'text',
'label' => array( 'text' => 'ΠΑΡΟΧΗ',
'type' => 0 ),
'editedByRte' => false,
'bold' => true,
'font-size' => '16px' ),
'search_field_label28' => array( 'type' => 'search_field_label',
'field' => 'ngMeterNumber',
'separated' => true ),
'search_field_options28' => array( 'type' => 'search_field_options',
'field' => 'ngMeterNumber',
'separated' => true ),
'integrated_search_field71' => array( 'field' => 'ngMeterNumber',
'type' => 'search_field',
'orientation' => 0,
'required' => false,
'joined' => false,
'separated' => true ),
'search_field_between28' => array( 'type' => 'search_field_between',
'field' => 'ngMeterNumber',
'separated' => true ),
'search_field_label13' => array( 'type' => 'search_field_label',
'field' => 'powerSupplyNumber',
'separated' => true ),
'search_field_between12' => array( 'type' => 'search_field_between',
'field' => 'voltonPlan',
'separated' => true ),
'search_field_label12' => array( 'type' => 'search_field_label',
'field' => 'voltonPlan',
'separated' => true ),
'search_field_options12' => array( 'type' => 'search_field_options',
'field' => 'voltonPlan',
'separated' => true ),
'integrated_search_field41' => array( 'field' => 'ngAddress',
'type' => 'search_field',
'orientation' => 0,
'required' => false,
'joined' => false,
'separated' => true ),
'search_field_between15' => array( 'type' => 'search_field_between',
'field' => 'ngAddress',
'separated' => true ),
'integrated_search_field64' => array( 'field' => 'ngPostalCode',
'type' => 'search_field',
'orientation' => 0,
'required' => false,
'joined' => false,
'separated' => true ),
'search_field_between24' => array( 'type' => 'search_field_between',
'field' => 'ngPostalCode',
'separated' => true ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'logout_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login' ),
'logout_link' => array( 'type' => 'logout_link' ),
'integrated_search_field' => array( 'field' => 'callPhone',
'type' => 'search_field',
'orientation' => 0,
'required' => false,
'label' => array( 'field' => 'callPhone',
'table' => 'dbo.voltonApplicationsBackofficeView',
'type' => 3 ),
'joined' => false,
'separated' => true ),
'integrated_search_field1' => array( 'field' => 'callDate',
'type' => 'search_field',
'orientation' => 0,
'required' => false,
'joined' => false,
'separated' => true ),
'search_field_label35' => array( 'type' => 'search_field_label',
'field' => 'callDate',
'separated' => true,
'label' => array( 'field' => 'callDate',
'table' => 'dbo.voltonApplicationsBackofficeView',
'type' => 3 ) ),
'search_field_options35' => array( 'type' => 'search_field_options',
'field' => 'callDate',
'separated' => true ),
'search_field_between35' => array( 'type' => 'search_field_between',
'field' => 'callDate',
'separated' => true ),
'search_field_label36' => array( 'type' => 'search_field_label',
'field' => 'callPhone',
'separated' => true ),
'search_field_options36' => array( 'type' => 'search_field_options',
'field' => 'callPhone',
'separated' => true ),
'search_field_between36' => array( 'type' => 'search_field_between',
'field' => 'callPhone',
'separated' => true ),
'search_search1' => array( 'type' => 'search_search' ),
'search_reset1' => array( 'type' => 'search_reset',
'label' => array( 'type' => 0,
'text' => 'Καθαρισμός Πεδίων' ) ),
'search_field_label8' => array( 'type' => 'search_field_label',
'field' => 'applicantWorkPhone',
'separated' => true ),
'search_field_options8' => array( 'type' => 'search_field_options',
'field' => 'applicantWorkPhone',
'separated' => true ),
'search_field_between8' => array( 'type' => 'search_field_between',
'field' => 'applicantWorkPhone',
'separated' => true ),
'search_field_label9' => array( 'type' => 'search_field_label',
'field' => 'applicantMobile',
'separated' => true ),
'search_field_options9' => array( 'type' => 'search_field_options',
'field' => 'applicantMobile',
'separated' => true ),
'search_field_between9' => array( 'type' => 'search_field_between',
'field' => 'applicantMobile',
'separated' => true ),
'search_field_label16' => array( 'type' => 'search_field_label',
'field' => 'applicantPhone',
'separated' => true ),
'search_field_options16' => array( 'type' => 'search_field_options',
'field' => 'applicantPhone',
'separated' => true ),
'search_field_between16' => array( 'type' => 'search_field_between',
'field' => 'applicantPhone',
'separated' => true ),
'integrated_search_field5' => array( 'field' => 'agent',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field6' => array( 'field' => 'applicationPhase',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field8' => array( 'field' => 'salesPhase',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>