<?php
			$optionsArray = array( 'captcha' => array( 'captcha' => false ),
'fields' => array( 'gridFields' => array( 'applicationStatusId',
'applicantName',
'applicantIdNumber',
'applicantAddress',
'applicantPostalCode',
'applicantTaxRegistrationNumber',
'applicantTaxOffice',
'applicantEmail',
'applicantProfession',
'applicantKod',
'applicantGemi',
'applicantPhone',
'applicantMobile',
'contactName',
'contactPhone',
'contactMobile',
'contactEmail',
'legalName',
'legalIdNumber',
'mailAddress',
'mailPostalCode',
'powerAddress',
'powerOwnershipType',
'powerPostalCode',
'powerAgreedKw',
'powerSupplyNumber',
'powerMeterNumber',
'powerCurrentSupplier',
'powerCurrentDayMeter',
'powerCurrentNightMeter',
'powerActivationStatus',
'voltonPlan',
'voltonContractDuration',
'voltonWarrantyAmount',
'voltonWarrantyOnFirstBill',
'voltonOther',
'voltonComments',
'voltonAutoPayment',
'applicationType',
'applicantWorkPhone',
'document1',
'document2',
'document3',
'document4',
'document5',
'document6',
'document7',
'document8',
'document9',
'document10',
'document11',
'document12',
'document13',
'document14',
'document15',
'applicantArea',
'applicantCity',
'mailArea',
'mailCity',
'powerArea',
'powerCity',
'ngAddress',
'ngPostalCode',
'ngArea',
'ngCity',
'ngPressure',
'ngHourlyCapacity',
'ngHkasp',
'ngMeterNumber',
'ngMeterType',
'ngCurrentMeterValue',
'ngConnectionExists',
'ngSupplyIsNew',
'ngSupplyReactivation',
'applicationAgentStatus',
'applicationLastStatusDate',
'dialerList',
'dialerAgent',
'dialerRecording',
'orderShipCompany',
'orderInvoiceRequired',
'callComments',
'internalCommunication',
'callGdprAcceptance',
'callGdprRecordingAcceptance',
'orderPaymentMethod',
'Expr2',
'contactZipCode',
'contactCity',
'ContactArea',
'contactGender',
'contactAge',
'crmUser',
'pauseAfterCall',
'dialerPhone',
'dialerCampaign',
'productFamilyId',
'contactMethod',
'courier',
'deliveryComments',
'courierDeliveryDate',
'courierTimeFrom',
'courierTimeTo' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'updateOnEditFields' => array( 'applicationStatusId',
'applicantName',
'applicantIdNumber',
'applicantAddress',
'applicantPostalCode',
'applicantTaxRegistrationNumber',
'applicantTaxOffice',
'applicantEmail',
'applicantProfession',
'applicantKod',
'applicantGemi',
'applicantPhone',
'applicantMobile',
'contactName',
'contactPhone',
'contactMobile',
'contactEmail',
'legalName',
'legalIdNumber',
'mailAddress',
'mailPostalCode',
'powerAddress',
'powerOwnershipType',
'powerPostalCode',
'powerAgreedKw',
'powerSupplyNumber',
'powerMeterNumber',
'powerCurrentSupplier',
'powerCurrentDayMeter',
'powerCurrentNightMeter',
'powerActivationStatus',
'voltonPlan',
'voltonContractDuration',
'voltonWarrantyAmount',
'voltonWarrantyOnFirstBill',
'voltonOther',
'voltonComments',
'voltonAutoPayment',
'applicationType',
'applicantWorkPhone',
'document1',
'document2',
'document3',
'document4',
'document5',
'document6',
'document7',
'document8',
'document9',
'document10',
'document11',
'document12',
'document13',
'document14',
'document15',
'applicantArea',
'applicantCity',
'mailArea',
'mailCity',
'powerArea',
'powerCity',
'ngAddress',
'ngPostalCode',
'ngArea',
'ngCity',
'ngPressure',
'ngHourlyCapacity',
'ngHkasp',
'ngMeterNumber',
'ngMeterType',
'ngCurrentMeterValue',
'ngConnectionExists',
'ngSupplyIsNew',
'ngSupplyReactivation',
'applicationAgentStatus',
'applicationLastStatusDate',
'dialerList',
'dialerAgent',
'dialerRecording',
'orderShipCompany',
'orderInvoiceRequired',
'callComments',
'internalCommunication',
'callGdprAcceptance',
'callGdprRecordingAcceptance',
'orderPaymentMethod',
'Expr2',
'contactZipCode',
'contactCity',
'ContactArea',
'contactGender',
'contactAge',
'crmUser',
'pauseAfterCall',
'dialerPhone',
'dialerCampaign',
'productFamilyId',
'contactMethod',
'courier',
'deliveryComments',
'courierDeliveryDate',
'courierTimeFrom',
'courierTimeTo' ),
'fieldItems' => array( 'applicationStatusId' => array( 'integrated_edit_field1' ),
'applicantName' => array( 'integrated_edit_field2' ),
'applicantIdNumber' => array( 'integrated_edit_field3' ),
'applicantAddress' => array( 'integrated_edit_field4' ),
'applicantPostalCode' => array( 'integrated_edit_field5' ),
'applicantTaxRegistrationNumber' => array( 'integrated_edit_field6' ),
'applicantTaxOffice' => array( 'integrated_edit_field7' ),
'applicantEmail' => array( 'integrated_edit_field8' ),
'applicantProfession' => array( 'integrated_edit_field9' ),
'applicantKod' => array( 'integrated_edit_field10' ),
'applicantGemi' => array( 'integrated_edit_field11' ),
'applicantPhone' => array( 'integrated_edit_field12' ),
'applicantMobile' => array( 'integrated_edit_field13' ),
'contactName' => array( 'integrated_edit_field14' ),
'contactPhone' => array( 'integrated_edit_field15' ),
'contactMobile' => array( 'integrated_edit_field16' ),
'contactEmail' => array( 'integrated_edit_field17' ),
'legalName' => array( 'integrated_edit_field18' ),
'legalIdNumber' => array( 'integrated_edit_field19' ),
'mailAddress' => array( 'integrated_edit_field20' ),
'mailPostalCode' => array( 'integrated_edit_field21' ),
'powerAddress' => array( 'integrated_edit_field23' ),
'powerOwnershipType' => array( 'integrated_edit_field24' ),
'powerPostalCode' => array( 'integrated_edit_field25' ),
'powerAgreedKw' => array( 'integrated_edit_field27' ),
'powerSupplyNumber' => array( 'integrated_edit_field28' ),
'powerMeterNumber' => array( 'integrated_edit_field29' ),
'powerCurrentSupplier' => array( 'integrated_edit_field30' ),
'powerCurrentDayMeter' => array( 'integrated_edit_field31' ),
'powerCurrentNightMeter' => array( 'integrated_edit_field32' ),
'powerActivationStatus' => array( 'integrated_edit_field33' ),
'voltonPlan' => array( 'integrated_edit_field34' ),
'voltonContractDuration' => array( 'integrated_edit_field35' ),
'voltonWarrantyAmount' => array( 'integrated_edit_field36' ),
'voltonWarrantyOnFirstBill' => array( 'integrated_edit_field37' ),
'voltonOther' => array( 'integrated_edit_field38' ),
'voltonComments' => array( 'integrated_edit_field39' ),
'voltonAutoPayment' => array( 'integrated_edit_field43' ),
'applicationType' => array( 'integrated_edit_field44' ),
'applicantWorkPhone' => array( 'integrated_edit_field45' ),
'document1' => array( 'integrated_edit_field46' ),
'document2' => array( 'integrated_edit_field47' ),
'document3' => array( 'integrated_edit_field48' ),
'document4' => array( 'integrated_edit_field49' ),
'document5' => array( 'integrated_edit_field50' ),
'document6' => array( 'integrated_edit_field51' ),
'document7' => array( 'integrated_edit_field52' ),
'document8' => array( 'integrated_edit_field53' ),
'document9' => array( 'integrated_edit_field54' ),
'document10' => array( 'integrated_edit_field55' ),
'document11' => array( 'integrated_edit_field56' ),
'document12' => array( 'integrated_edit_field57' ),
'document13' => array( 'integrated_edit_field58' ),
'document14' => array( 'integrated_edit_field59' ),
'document15' => array( 'integrated_edit_field60' ),
'applicantArea' => array( 'integrated_edit_field' ),
'applicantCity' => array( 'integrated_edit_field22' ),
'mailArea' => array( 'integrated_edit_field40' ),
'mailCity' => array( 'integrated_edit_field41' ),
'powerArea' => array( 'integrated_edit_field42' ),
'powerCity' => array( 'integrated_edit_field61' ),
'ngAddress' => array( 'integrated_edit_field26' ),
'ngPostalCode' => array( 'integrated_edit_field62' ),
'ngArea' => array( 'integrated_edit_field63' ),
'ngCity' => array( 'integrated_edit_field64' ),
'ngPressure' => array( 'integrated_edit_field65' ),
'ngHourlyCapacity' => array( 'integrated_edit_field66' ),
'ngHkasp' => array( 'integrated_edit_field67' ),
'ngMeterNumber' => array( 'integrated_edit_field69' ),
'ngMeterType' => array( 'integrated_edit_field70' ),
'ngCurrentMeterValue' => array( 'integrated_edit_field71' ),
'ngConnectionExists' => array( 'integrated_edit_field72' ),
'ngSupplyIsNew' => array( 'integrated_edit_field73' ),
'ngSupplyReactivation' => array( 'integrated_edit_field74' ),
'applicationAgentStatus' => array( 'integrated_edit_field68' ),
'applicationLastStatusDate' => array( 'integrated_edit_field75' ),
'dialerList' => array( 'integrated_edit_field77' ),
'dialerAgent' => array( 'integrated_edit_field78' ),
'dialerRecording' => array( 'integrated_edit_field79' ),
'orderShipCompany' => array( 'integrated_edit_field80' ),
'orderInvoiceRequired' => array( 'integrated_edit_field81' ),
'callComments' => array( 'integrated_edit_field82' ),
'internalCommunication' => array( 'integrated_edit_field83' ),
'callGdprAcceptance' => array( 'integrated_edit_field84' ),
'callGdprRecordingAcceptance' => array( 'integrated_edit_field85' ),
'orderPaymentMethod' => array( 'integrated_edit_field86' ),
'Expr2' => array( 'integrated_edit_field87' ),
'contactZipCode' => array( 'integrated_edit_field88' ),
'contactCity' => array( 'integrated_edit_field89' ),
'ContactArea' => array( 'integrated_edit_field90' ),
'contactGender' => array( 'integrated_edit_field91' ),
'contactAge' => array( 'integrated_edit_field92' ),
'crmUser' => array( 'integrated_edit_field93' ),
'pauseAfterCall' => array( 'integrated_edit_field94' ),
'dialerPhone' => array( 'integrated_edit_field95' ),
'dialerCampaign' => array( 'integrated_edit_field96' ),
'productFamilyId' => array( 'integrated_edit_field97' ),
'contactMethod' => array( 'integrated_edit_field98' ),
'courier' => array( 'integrated_edit_field99' ),
'deliveryComments' => array( 'integrated_edit_field100' ),
'courierDeliveryDate' => array( 'integrated_edit_field101' ),
'courierTimeFrom' => array( 'integrated_edit_field102' ),
'courierTimeTo' => array( 'integrated_edit_field103' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => true,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'top' => array( 'edit_header' ),
'above-grid' => array( 'edit_message' ),
'below-grid' => array( 'edit_save',
'update_records',
'edit_back_list',
'edit_close',
'hamburger' ),
'grid' => array( 'master_info',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field8',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field14',
'integrated_edit_field15',
'integrated_edit_field16',
'integrated_edit_field17',
'integrated_edit_field12',
'integrated_edit_field13',
'integrated_edit_field18',
'integrated_edit_field19',
'integrated_edit_field20',
'integrated_edit_field21',
'integrated_edit_field23',
'integrated_edit_field24',
'integrated_edit_field25',
'integrated_edit_field27',
'integrated_edit_field28',
'integrated_edit_field29',
'integrated_edit_field30',
'integrated_edit_field31',
'integrated_edit_field32',
'integrated_edit_field33',
'integrated_edit_field34',
'integrated_edit_field35',
'integrated_edit_field36',
'integrated_edit_field37',
'integrated_edit_field38',
'integrated_edit_field39',
'integrated_edit_field43',
'integrated_edit_field44',
'integrated_edit_field45',
'integrated_edit_field46',
'integrated_edit_field47',
'integrated_edit_field48',
'integrated_edit_field49',
'integrated_edit_field50',
'integrated_edit_field51',
'integrated_edit_field52',
'integrated_edit_field53',
'integrated_edit_field54',
'integrated_edit_field55',
'integrated_edit_field56',
'integrated_edit_field57',
'integrated_edit_field58',
'integrated_edit_field59',
'integrated_edit_field60',
'integrated_edit_field1',
'integrated_edit_field',
'integrated_edit_field22',
'integrated_edit_field40',
'integrated_edit_field41',
'integrated_edit_field42',
'integrated_edit_field61',
'details_preview',
'integrated_edit_field26',
'integrated_edit_field62',
'integrated_edit_field63',
'integrated_edit_field64',
'integrated_edit_field65',
'integrated_edit_field66',
'integrated_edit_field67',
'integrated_edit_field69',
'integrated_edit_field70',
'integrated_edit_field71',
'integrated_edit_field72',
'integrated_edit_field73',
'integrated_edit_field74',
'integrated_edit_field68',
'integrated_edit_field75',
'integrated_edit_field77',
'integrated_edit_field78',
'integrated_edit_field79',
'integrated_edit_field80',
'integrated_edit_field81',
'integrated_edit_field82',
'integrated_edit_field83',
'integrated_edit_field84',
'integrated_edit_field85',
'integrated_edit_field86',
'integrated_edit_field87',
'integrated_edit_field88',
'integrated_edit_field89',
'integrated_edit_field90',
'integrated_edit_field91',
'integrated_edit_field92',
'integrated_edit_field93',
'integrated_edit_field94',
'integrated_edit_field95',
'integrated_edit_field96',
'integrated_edit_field97',
'integrated_edit_field98',
'integrated_edit_field99',
'integrated_edit_field100',
'integrated_edit_field101',
'integrated_edit_field102',
'integrated_edit_field103' ) ),
'formXtTags' => array( 'above-grid' => array( 'message_block' ) ),
'itemForms' => array( 'edit_header' => 'top',
'edit_message' => 'above-grid',
'edit_save' => 'below-grid',
'update_records' => 'below-grid',
'edit_back_list' => 'below-grid',
'edit_close' => 'below-grid',
'hamburger' => 'below-grid',
'master_info' => 'grid',
'integrated_edit_field2' => 'grid',
'integrated_edit_field3' => 'grid',
'integrated_edit_field4' => 'grid',
'integrated_edit_field5' => 'grid',
'integrated_edit_field6' => 'grid',
'integrated_edit_field7' => 'grid',
'integrated_edit_field8' => 'grid',
'integrated_edit_field9' => 'grid',
'integrated_edit_field10' => 'grid',
'integrated_edit_field11' => 'grid',
'integrated_edit_field14' => 'grid',
'integrated_edit_field15' => 'grid',
'integrated_edit_field16' => 'grid',
'integrated_edit_field17' => 'grid',
'integrated_edit_field12' => 'grid',
'integrated_edit_field13' => 'grid',
'integrated_edit_field18' => 'grid',
'integrated_edit_field19' => 'grid',
'integrated_edit_field20' => 'grid',
'integrated_edit_field21' => 'grid',
'integrated_edit_field23' => 'grid',
'integrated_edit_field24' => 'grid',
'integrated_edit_field25' => 'grid',
'integrated_edit_field27' => 'grid',
'integrated_edit_field28' => 'grid',
'integrated_edit_field29' => 'grid',
'integrated_edit_field30' => 'grid',
'integrated_edit_field31' => 'grid',
'integrated_edit_field32' => 'grid',
'integrated_edit_field33' => 'grid',
'integrated_edit_field34' => 'grid',
'integrated_edit_field35' => 'grid',
'integrated_edit_field36' => 'grid',
'integrated_edit_field37' => 'grid',
'integrated_edit_field38' => 'grid',
'integrated_edit_field39' => 'grid',
'integrated_edit_field43' => 'grid',
'integrated_edit_field44' => 'grid',
'integrated_edit_field45' => 'grid',
'integrated_edit_field46' => 'grid',
'integrated_edit_field47' => 'grid',
'integrated_edit_field48' => 'grid',
'integrated_edit_field49' => 'grid',
'integrated_edit_field50' => 'grid',
'integrated_edit_field51' => 'grid',
'integrated_edit_field52' => 'grid',
'integrated_edit_field53' => 'grid',
'integrated_edit_field54' => 'grid',
'integrated_edit_field55' => 'grid',
'integrated_edit_field56' => 'grid',
'integrated_edit_field57' => 'grid',
'integrated_edit_field58' => 'grid',
'integrated_edit_field59' => 'grid',
'integrated_edit_field60' => 'grid',
'integrated_edit_field1' => 'grid',
'integrated_edit_field' => 'grid',
'integrated_edit_field22' => 'grid',
'integrated_edit_field40' => 'grid',
'integrated_edit_field41' => 'grid',
'integrated_edit_field42' => 'grid',
'integrated_edit_field61' => 'grid',
'details_preview' => 'grid',
'integrated_edit_field26' => 'grid',
'integrated_edit_field62' => 'grid',
'integrated_edit_field63' => 'grid',
'integrated_edit_field64' => 'grid',
'integrated_edit_field65' => 'grid',
'integrated_edit_field66' => 'grid',
'integrated_edit_field67' => 'grid',
'integrated_edit_field69' => 'grid',
'integrated_edit_field70' => 'grid',
'integrated_edit_field71' => 'grid',
'integrated_edit_field72' => 'grid',
'integrated_edit_field73' => 'grid',
'integrated_edit_field74' => 'grid',
'integrated_edit_field68' => 'grid',
'integrated_edit_field75' => 'grid',
'integrated_edit_field77' => 'grid',
'integrated_edit_field78' => 'grid',
'integrated_edit_field79' => 'grid',
'integrated_edit_field80' => 'grid',
'integrated_edit_field81' => 'grid',
'integrated_edit_field82' => 'grid',
'integrated_edit_field83' => 'grid',
'integrated_edit_field84' => 'grid',
'integrated_edit_field85' => 'grid',
'integrated_edit_field86' => 'grid',
'integrated_edit_field87' => 'grid',
'integrated_edit_field88' => 'grid',
'integrated_edit_field89' => 'grid',
'integrated_edit_field90' => 'grid',
'integrated_edit_field91' => 'grid',
'integrated_edit_field92' => 'grid',
'integrated_edit_field93' => 'grid',
'integrated_edit_field94' => 'grid',
'integrated_edit_field95' => 'grid',
'integrated_edit_field96' => 'grid',
'integrated_edit_field97' => 'grid',
'integrated_edit_field98' => 'grid',
'integrated_edit_field99' => 'grid',
'integrated_edit_field100' => 'grid',
'integrated_edit_field101' => 'grid',
'integrated_edit_field102' => 'grid',
'integrated_edit_field103' => 'grid' ),
'itemLocations' => array( 'master_info' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field2' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field3' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field4' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field5' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field6' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field7' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field8' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field9' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field10' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field11' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field14' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field15' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field16' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field17' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field12' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field13' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field18' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field19' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field20' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field21' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field23' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field24' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field25' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field27' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field28' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field29' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field30' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field31' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field32' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field33' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field34' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field35' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field36' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field37' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field38' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field39' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field43' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field44' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field45' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field46' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field47' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field48' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field49' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field50' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field51' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field52' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field53' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field54' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field55' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field56' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field57' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field58' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field59' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field60' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field1' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field22' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field40' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field41' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field42' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field61' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'details_preview' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field26' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field62' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field63' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field64' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field65' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field66' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field67' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field69' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field70' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field71' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field72' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field73' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field74' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field68' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field75' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field77' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field78' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field79' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field80' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field81' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field82' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field83' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field84' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field85' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field86' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field87' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field88' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field89' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field90' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field91' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field92' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field93' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field94' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field95' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field96' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field97' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field98' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field99' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field100' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field101' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field102' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field103' => array( 'location' => 'grid',
'cellId' => 'c3' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'edit_header' => array( 'edit_header' ),
'hamburger' => array( 'hamburger' ),
'edit_reset' => array( 'edit_reset' ),
'edit_message' => array( 'edit_message' ),
'edit_save' => array( 'edit_save' ),
'edit_back_list' => array( 'edit_back_list' ),
'edit_close' => array( 'edit_close' ),
'edit_view' => array( 'edit_view' ),
'integrated_edit_field' => array( 'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field8',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field12',
'integrated_edit_field13',
'integrated_edit_field14',
'integrated_edit_field15',
'integrated_edit_field16',
'integrated_edit_field17',
'integrated_edit_field18',
'integrated_edit_field19',
'integrated_edit_field20',
'integrated_edit_field21',
'integrated_edit_field23',
'integrated_edit_field24',
'integrated_edit_field25',
'integrated_edit_field27',
'integrated_edit_field28',
'integrated_edit_field29',
'integrated_edit_field30',
'integrated_edit_field31',
'integrated_edit_field32',
'integrated_edit_field33',
'integrated_edit_field34',
'integrated_edit_field35',
'integrated_edit_field36',
'integrated_edit_field37',
'integrated_edit_field38',
'integrated_edit_field39',
'integrated_edit_field43',
'integrated_edit_field44',
'integrated_edit_field45',
'integrated_edit_field46',
'integrated_edit_field47',
'integrated_edit_field48',
'integrated_edit_field49',
'integrated_edit_field50',
'integrated_edit_field51',
'integrated_edit_field52',
'integrated_edit_field53',
'integrated_edit_field54',
'integrated_edit_field55',
'integrated_edit_field56',
'integrated_edit_field57',
'integrated_edit_field58',
'integrated_edit_field59',
'integrated_edit_field60',
'integrated_edit_field',
'integrated_edit_field22',
'integrated_edit_field40',
'integrated_edit_field41',
'integrated_edit_field42',
'integrated_edit_field61',
'integrated_edit_field26',
'integrated_edit_field62',
'integrated_edit_field63',
'integrated_edit_field64',
'integrated_edit_field65',
'integrated_edit_field66',
'integrated_edit_field67',
'integrated_edit_field69',
'integrated_edit_field70',
'integrated_edit_field71',
'integrated_edit_field72',
'integrated_edit_field73',
'integrated_edit_field74',
'integrated_edit_field68',
'integrated_edit_field75',
'integrated_edit_field77',
'integrated_edit_field78',
'integrated_edit_field79',
'integrated_edit_field80',
'integrated_edit_field81',
'integrated_edit_field82',
'integrated_edit_field83',
'integrated_edit_field84',
'integrated_edit_field85',
'integrated_edit_field86',
'integrated_edit_field87',
'integrated_edit_field88',
'integrated_edit_field89',
'integrated_edit_field90',
'integrated_edit_field91',
'integrated_edit_field92',
'integrated_edit_field93',
'integrated_edit_field94',
'integrated_edit_field95',
'integrated_edit_field96',
'integrated_edit_field97',
'integrated_edit_field98',
'integrated_edit_field99',
'integrated_edit_field100',
'integrated_edit_field101',
'integrated_edit_field102',
'integrated_edit_field103' ),
'master_info' => array( 'master_info' ),
'details_preview' => array( 'details_preview' ),
'update_records' => array( 'update_records' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c3' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'master_info',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field8',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field14',
'integrated_edit_field15',
'integrated_edit_field16',
'integrated_edit_field17',
'integrated_edit_field12',
'integrated_edit_field13',
'integrated_edit_field18',
'integrated_edit_field19',
'integrated_edit_field20',
'integrated_edit_field21',
'integrated_edit_field23',
'integrated_edit_field24',
'integrated_edit_field25',
'integrated_edit_field27',
'integrated_edit_field28',
'integrated_edit_field29',
'integrated_edit_field30',
'integrated_edit_field31',
'integrated_edit_field32',
'integrated_edit_field33',
'integrated_edit_field34',
'integrated_edit_field35',
'integrated_edit_field36',
'integrated_edit_field37',
'integrated_edit_field38',
'integrated_edit_field39',
'integrated_edit_field43',
'integrated_edit_field44',
'integrated_edit_field45',
'integrated_edit_field46',
'integrated_edit_field47',
'integrated_edit_field48',
'integrated_edit_field49',
'integrated_edit_field50',
'integrated_edit_field51',
'integrated_edit_field52',
'integrated_edit_field53',
'integrated_edit_field54',
'integrated_edit_field55',
'integrated_edit_field56',
'integrated_edit_field57',
'integrated_edit_field58',
'integrated_edit_field59',
'integrated_edit_field60',
'integrated_edit_field1',
'integrated_edit_field',
'integrated_edit_field22',
'integrated_edit_field40',
'integrated_edit_field41',
'integrated_edit_field42',
'integrated_edit_field61',
'details_preview',
'integrated_edit_field26',
'integrated_edit_field62',
'integrated_edit_field63',
'integrated_edit_field64',
'integrated_edit_field65',
'integrated_edit_field66',
'integrated_edit_field67',
'integrated_edit_field69',
'integrated_edit_field70',
'integrated_edit_field71',
'integrated_edit_field72',
'integrated_edit_field73',
'integrated_edit_field74',
'integrated_edit_field68',
'integrated_edit_field75',
'integrated_edit_field77',
'integrated_edit_field78',
'integrated_edit_field79',
'integrated_edit_field80',
'integrated_edit_field81',
'integrated_edit_field82',
'integrated_edit_field83',
'integrated_edit_field84',
'integrated_edit_field85',
'integrated_edit_field86',
'integrated_edit_field87',
'integrated_edit_field88',
'integrated_edit_field89',
'integrated_edit_field90',
'integrated_edit_field91',
'integrated_edit_field92',
'integrated_edit_field93',
'integrated_edit_field94',
'integrated_edit_field95',
'integrated_edit_field96',
'integrated_edit_field97',
'integrated_edit_field98',
'integrated_edit_field99',
'integrated_edit_field100',
'integrated_edit_field101',
'integrated_edit_field102',
'integrated_edit_field103' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array( 'update_records' => array( 'tag' => 'UPDATE_N_RECORDS',
'type' => 2 ) ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'edit',
'breadcrumb' => false,
'nextPrev' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'edit' => array( 'updateSelected' => true ) );
			$pageArray = array( 'id' => 'edit',
'type' => 'edit',
'layoutId' => 'nomenu',
'disabled' => 0,
'default' => 0,
'forms' => array( 'top' => array( 'modelId' => 'edit-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'edit-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_message' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'edit-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_save',
'update_records',
'edit_back_list',
'edit_close' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'hamburger' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c3' ) ),
'section' => '' ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array( 'master_info',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field8',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field14',
'integrated_edit_field15',
'integrated_edit_field16',
'integrated_edit_field17',
'integrated_edit_field12',
'integrated_edit_field13',
'integrated_edit_field18',
'integrated_edit_field19',
'integrated_edit_field20',
'integrated_edit_field21',
'integrated_edit_field23',
'integrated_edit_field24',
'integrated_edit_field25',
'integrated_edit_field27',
'integrated_edit_field28',
'integrated_edit_field29',
'integrated_edit_field30',
'integrated_edit_field31',
'integrated_edit_field32',
'integrated_edit_field33',
'integrated_edit_field34',
'integrated_edit_field35',
'integrated_edit_field36',
'integrated_edit_field37',
'integrated_edit_field38',
'integrated_edit_field39',
'integrated_edit_field43',
'integrated_edit_field44',
'integrated_edit_field45',
'integrated_edit_field46',
'integrated_edit_field47',
'integrated_edit_field48',
'integrated_edit_field49',
'integrated_edit_field50',
'integrated_edit_field51',
'integrated_edit_field52',
'integrated_edit_field53',
'integrated_edit_field54',
'integrated_edit_field55',
'integrated_edit_field56',
'integrated_edit_field57',
'integrated_edit_field58',
'integrated_edit_field59',
'integrated_edit_field60',
'integrated_edit_field1',
'integrated_edit_field',
'integrated_edit_field22',
'integrated_edit_field40',
'integrated_edit_field41',
'integrated_edit_field42',
'integrated_edit_field61',
'details_preview',
'integrated_edit_field26',
'integrated_edit_field62',
'integrated_edit_field63',
'integrated_edit_field64',
'integrated_edit_field65',
'integrated_edit_field66',
'integrated_edit_field67',
'integrated_edit_field69',
'integrated_edit_field70',
'integrated_edit_field71',
'integrated_edit_field72',
'integrated_edit_field73',
'integrated_edit_field74',
'integrated_edit_field68',
'integrated_edit_field75',
'integrated_edit_field77',
'integrated_edit_field78',
'integrated_edit_field79',
'integrated_edit_field80',
'integrated_edit_field81',
'integrated_edit_field82',
'integrated_edit_field83',
'integrated_edit_field84',
'integrated_edit_field85',
'integrated_edit_field86',
'integrated_edit_field87',
'integrated_edit_field88',
'integrated_edit_field89',
'integrated_edit_field90',
'integrated_edit_field91',
'integrated_edit_field92',
'integrated_edit_field93',
'integrated_edit_field94',
'integrated_edit_field95',
'integrated_edit_field96',
'integrated_edit_field97',
'integrated_edit_field98',
'integrated_edit_field99',
'integrated_edit_field100',
'integrated_edit_field101',
'integrated_edit_field102',
'integrated_edit_field103' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'edit_header' => array( 'type' => 'edit_header' ),
'hamburger' => array( 'type' => 'hamburger',
'items' => array( 'edit_reset',
'edit_view' ) ),
'edit_reset' => array( 'type' => 'edit_reset' ),
'edit_message' => array( 'type' => 'edit_message' ),
'edit_save' => array( 'type' => 'edit_save' ),
'edit_back_list' => array( 'type' => 'edit_back_list' ),
'edit_close' => array( 'type' => 'edit_close' ),
'edit_view' => array( 'type' => 'edit_view' ),
'integrated_edit_field1' => array( 'field' => 'applicationStatusId',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'master_info' => array( 'type' => 'master_info',
'tables' => array( 'dbo.Calls' => 'true' ) ),
'integrated_edit_field2' => array( 'field' => 'applicantName',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field3' => array( 'field' => 'applicantIdNumber',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field4' => array( 'field' => 'applicantAddress',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field5' => array( 'field' => 'applicantPostalCode',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field6' => array( 'field' => 'applicantTaxRegistrationNumber',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field7' => array( 'field' => 'applicantTaxOffice',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field8' => array( 'field' => 'applicantEmail',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field9' => array( 'field' => 'applicantProfession',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field10' => array( 'field' => 'applicantKod',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field11' => array( 'field' => 'applicantGemi',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field12' => array( 'field' => 'applicantPhone',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field13' => array( 'field' => 'applicantMobile',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field14' => array( 'field' => 'contactName',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field15' => array( 'field' => 'contactPhone',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field16' => array( 'field' => 'contactMobile',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field17' => array( 'field' => 'contactEmail',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field18' => array( 'field' => 'legalName',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field19' => array( 'field' => 'legalIdNumber',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field20' => array( 'field' => 'mailAddress',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field21' => array( 'field' => 'mailPostalCode',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field23' => array( 'field' => 'powerAddress',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field24' => array( 'field' => 'powerOwnershipType',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field25' => array( 'field' => 'powerPostalCode',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field27' => array( 'field' => 'powerAgreedKw',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field28' => array( 'field' => 'powerSupplyNumber',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field29' => array( 'field' => 'powerMeterNumber',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field30' => array( 'field' => 'powerCurrentSupplier',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field31' => array( 'field' => 'powerCurrentDayMeter',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field32' => array( 'field' => 'powerCurrentNightMeter',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field33' => array( 'field' => 'powerActivationStatus',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field34' => array( 'field' => 'voltonPlan',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field35' => array( 'field' => 'voltonContractDuration',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field36' => array( 'field' => 'voltonWarrantyAmount',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field37' => array( 'field' => 'voltonWarrantyOnFirstBill',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field38' => array( 'field' => 'voltonOther',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field39' => array( 'field' => 'voltonComments',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field43' => array( 'field' => 'voltonAutoPayment',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field44' => array( 'field' => 'applicationType',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field45' => array( 'field' => 'applicantWorkPhone',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field46' => array( 'field' => 'document1',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field47' => array( 'field' => 'document2',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field48' => array( 'field' => 'document3',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field49' => array( 'field' => 'document4',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field50' => array( 'field' => 'document5',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field51' => array( 'field' => 'document6',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field52' => array( 'field' => 'document7',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field53' => array( 'field' => 'document8',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field54' => array( 'field' => 'document9',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field55' => array( 'field' => 'document10',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field56' => array( 'field' => 'document11',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field57' => array( 'field' => 'document12',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field58' => array( 'field' => 'document13',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field59' => array( 'field' => 'document14',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field60' => array( 'field' => 'document15',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field' => array( 'field' => 'applicantArea',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field22' => array( 'field' => 'applicantCity',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field40' => array( 'field' => 'mailArea',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field41' => array( 'field' => 'mailCity',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field42' => array( 'field' => 'powerArea',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field61' => array( 'field' => 'powerCity',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'details_preview' => array( 'type' => 'details_preview',
'table' => 'dbo.internalComments',
'items' => array(  ),
'popup' => false,
'pageId' => 'list' ),
'update_records' => array( 'type' => 'update_records' ),
'integrated_edit_field26' => array( 'field' => 'ngAddress',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field62' => array( 'field' => 'ngPostalCode',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field63' => array( 'field' => 'ngArea',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field64' => array( 'field' => 'ngCity',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field65' => array( 'field' => 'ngPressure',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field66' => array( 'field' => 'ngHourlyCapacity',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field67' => array( 'field' => 'ngHkasp',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field69' => array( 'field' => 'ngMeterNumber',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field70' => array( 'field' => 'ngMeterType',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field71' => array( 'field' => 'ngCurrentMeterValue',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field72' => array( 'field' => 'ngConnectionExists',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field73' => array( 'field' => 'ngSupplyIsNew',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field74' => array( 'field' => 'ngSupplyReactivation',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field68' => array( 'field' => 'applicationAgentStatus',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field75' => array( 'field' => 'applicationLastStatusDate',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field77' => array( 'field' => 'dialerList',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field78' => array( 'field' => 'dialerAgent',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field79' => array( 'field' => 'dialerRecording',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field80' => array( 'field' => 'orderShipCompany',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field81' => array( 'field' => 'orderInvoiceRequired',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field82' => array( 'field' => 'callComments',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field83' => array( 'field' => 'internalCommunication',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field84' => array( 'field' => 'callGdprAcceptance',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field85' => array( 'field' => 'callGdprRecordingAcceptance',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field86' => array( 'field' => 'orderPaymentMethod',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field87' => array( 'field' => 'Expr2',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field88' => array( 'field' => 'contactZipCode',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field89' => array( 'field' => 'contactCity',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field90' => array( 'field' => 'ContactArea',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field91' => array( 'field' => 'contactGender',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field92' => array( 'field' => 'contactAge',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field93' => array( 'field' => 'crmUser',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field94' => array( 'field' => 'pauseAfterCall',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field95' => array( 'field' => 'dialerPhone',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field96' => array( 'field' => 'dialerCampaign',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field97' => array( 'field' => 'productFamilyId',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field98' => array( 'field' => 'contactMethod',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field99' => array( 'field' => 'courier',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field100' => array( 'field' => 'deliveryComments',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field101' => array( 'field' => 'courierDeliveryDate',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field102' => array( 'field' => 'courierTimeFrom',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field103' => array( 'field' => 'courierTimeTo',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>