<?php
			$optionsArray = array( 'totals' => array( 'id' => array( 'totalsType' => '' ),
'callid' => array( 'totalsType' => '' ),
'applicationStatusId' => array( 'totalsType' => '' ),
'applicationType' => array( 'totalsType' => '' ),
'applicantName' => array( 'totalsType' => '' ),
'applicantIdNumber' => array( 'totalsType' => '' ),
'applicantAddress' => array( 'totalsType' => '' ),
'applicantPostalCode' => array( 'totalsType' => '' ),
'applicantArea' => array( 'totalsType' => '' ),
'applicantCity' => array( 'totalsType' => '' ),
'applicantTaxRegistrationNumber' => array( 'totalsType' => '' ),
'applicantTaxOffice' => array( 'totalsType' => '' ),
'applicantEmail' => array( 'totalsType' => '' ),
'applicantProfession' => array( 'totalsType' => '' ),
'applicantKod' => array( 'totalsType' => '' ),
'applicantGemi' => array( 'totalsType' => '' ),
'applicantPhone' => array( 'totalsType' => '' ),
'applicantWorkPhone' => array( 'totalsType' => '' ),
'applicantMobile' => array( 'totalsType' => '' ),
'contactName' => array( 'totalsType' => '' ),
'contactPhone' => array( 'totalsType' => '' ),
'contactMobile' => array( 'totalsType' => '' ),
'contactEmail' => array( 'totalsType' => '' ),
'legalName' => array( 'totalsType' => '' ),
'legalIdNumber' => array( 'totalsType' => '' ),
'mailAddress' => array( 'totalsType' => '' ),
'mailPostalCode' => array( 'totalsType' => '' ),
'mailArea' => array( 'totalsType' => '' ),
'mailCity' => array( 'totalsType' => '' ),
'powerAddress' => array( 'totalsType' => '' ),
'powerOwnershipType' => array( 'totalsType' => '' ),
'powerPostalCode' => array( 'totalsType' => '' ),
'powerArea' => array( 'totalsType' => '' ),
'powerCity' => array( 'totalsType' => '' ),
'powerAgreedKw' => array( 'totalsType' => '' ),
'powerSupplyNumber' => array( 'totalsType' => '' ),
'powerMeterNumber' => array( 'totalsType' => '' ),
'powerCurrentSupplier' => array( 'totalsType' => '' ),
'powerCurrentDayMeter' => array( 'totalsType' => '' ),
'powerCurrentNightMeter' => array( 'totalsType' => '' ),
'powerActivationStatus' => array( 'totalsType' => '' ),
'voltonPlan' => array( 'totalsType' => '' ),
'voltonContractDuration' => array( 'totalsType' => '' ),
'voltonWarrantyAmount' => array( 'totalsType' => '' ),
'voltonWarrantyOnFirstBill' => array( 'totalsType' => '' ),
'voltonOther' => array( 'totalsType' => '' ),
'voltonComments' => array( 'totalsType' => '' ),
'voltonAutoPayment' => array( 'totalsType' => '' ),
'document1' => array( 'totalsType' => '' ),
'document2' => array( 'totalsType' => '' ),
'document3' => array( 'totalsType' => '' ),
'document4' => array( 'totalsType' => '' ),
'document5' => array( 'totalsType' => '' ),
'document6' => array( 'totalsType' => '' ),
'document7' => array( 'totalsType' => '' ),
'document8' => array( 'totalsType' => '' ),
'document9' => array( 'totalsType' => '' ),
'document10' => array( 'totalsType' => '' ),
'document11' => array( 'totalsType' => '' ),
'document12' => array( 'totalsType' => '' ),
'document13' => array( 'totalsType' => '' ),
'document14' => array( 'totalsType' => '' ),
'document15' => array( 'totalsType' => '' ),
'ngAddress' => array( 'totalsType' => '' ),
'ngPostalCode' => array( 'totalsType' => '' ),
'ngArea' => array( 'totalsType' => '' ),
'ngCity' => array( 'totalsType' => '' ),
'ngPressure' => array( 'totalsType' => '' ),
'ngHourlyCapacity' => array( 'totalsType' => '' ),
'ngHkasp' => array( 'totalsType' => '' ),
'ngMeterNumber' => array( 'totalsType' => '' ),
'ngMeterType' => array( 'totalsType' => '' ),
'ngCurrentMeterValue' => array( 'totalsType' => '' ),
'ngConnectionExists' => array( 'totalsType' => '' ),
'ngSupplyIsNew' => array( 'totalsType' => '' ),
'ngSupplyReactivation' => array( 'totalsType' => '' ),
'applicationAgentStatus' => array( 'totalsType' => '' ),
'applicationLastStatusDate' => array( 'totalsType' => '' ),
'dialerList' => array( 'totalsType' => '' ),
'dialerAgent' => array( 'totalsType' => '' ),
'dialerRecording' => array( 'totalsType' => '' ),
'orderShipCompany' => array( 'totalsType' => '' ),
'orderInvoiceRequired' => array( 'totalsType' => '' ),
'callComments' => array( 'totalsType' => '' ),
'internalCommunication' => array( 'totalsType' => '' ),
'callGdprAcceptance' => array( 'totalsType' => '' ),
'callGdprRecordingAcceptance' => array( 'totalsType' => '' ),
'orderPaymentMethod' => array( 'totalsType' => '' ),
'Expr2' => array( 'totalsType' => '' ),
'contactZipCode' => array( 'totalsType' => '' ),
'contactCity' => array( 'totalsType' => '' ),
'ContactArea' => array( 'totalsType' => '' ),
'contactGender' => array( 'totalsType' => '' ),
'contactAge' => array( 'totalsType' => '' ),
'crmUser' => array( 'totalsType' => '' ),
'pauseAfterCall' => array( 'totalsType' => '' ),
'dialerPhone' => array( 'totalsType' => '' ),
'dialerCampaign' => array( 'totalsType' => '' ),
'productFamilyId' => array( 'totalsType' => '' ),
'contactMethod' => array( 'totalsType' => '' ),
'courier' => array( 'totalsType' => '' ),
'deliveryComments' => array( 'totalsType' => '' ),
'courierDeliveryDate' => array( 'totalsType' => '' ),
'courierTimeFrom' => array( 'totalsType' => '' ),
'courierTimeTo' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'applicantName',
'applicantIdNumber',
'applicantAddress',
'applicantPostalCode',
'applicantTaxRegistrationNumber',
'applicantTaxOffice',
'applicantEmail',
'applicantProfession',
'applicantKod',
'applicantGemi',
'applicantPhone',
'applicantMobile',
'contactName',
'contactPhone',
'contactMobile',
'contactEmail',
'legalName',
'legalIdNumber',
'mailAddress',
'mailPostalCode',
'powerAddress',
'powerOwnershipType',
'powerPostalCode',
'powerAgreedKw',
'powerSupplyNumber',
'powerMeterNumber',
'powerCurrentSupplier',
'powerCurrentDayMeter',
'powerCurrentNightMeter',
'powerActivationStatus',
'voltonPlan',
'voltonContractDuration',
'voltonWarrantyAmount',
'voltonWarrantyOnFirstBill',
'voltonOther',
'voltonComments',
'voltonAutoPayment',
'applicationType',
'applicantWorkPhone',
'document1',
'document2',
'document3',
'document4',
'document5',
'document6',
'document7',
'document8',
'document9',
'document10',
'document11',
'document12',
'document13',
'document14',
'document15',
'applicationStatusId',
'applicantArea',
'applicantCity',
'mailArea',
'mailCity',
'powerArea',
'powerCity',
'ngAddress',
'ngPostalCode',
'ngArea',
'ngCity',
'ngPressure',
'ngHourlyCapacity',
'ngHkasp',
'ngMeterNumber',
'ngMeterType',
'ngCurrentMeterValue',
'ngConnectionExists',
'ngSupplyIsNew',
'ngSupplyReactivation',
'applicationAgentStatus',
'applicationLastStatusDate',
'dialerList',
'dialerAgent',
'dialerRecording',
'orderShipCompany',
'orderInvoiceRequired',
'callComments',
'internalCommunication',
'callGdprAcceptance',
'callGdprRecordingAcceptance',
'orderPaymentMethod',
'Expr2',
'contactZipCode',
'contactCity',
'ContactArea',
'contactGender',
'contactAge',
'crmUser',
'pauseAfterCall',
'dialerPhone',
'dialerCampaign',
'productFamilyId',
'contactMethod',
'courier',
'deliveryComments',
'courierDeliveryDate',
'courierTimeFrom',
'courierTimeTo' ),
'exportFields' => array( 'applicantName',
'applicantIdNumber',
'applicantAddress',
'applicantPostalCode',
'applicantTaxRegistrationNumber',
'applicantTaxOffice',
'applicantEmail',
'applicantProfession',
'applicantKod',
'applicantGemi',
'contactName',
'contactPhone',
'contactMobile',
'contactEmail',
'applicantPhone',
'applicantMobile',
'legalName',
'legalIdNumber',
'mailAddress',
'mailPostalCode',
'powerAddress',
'powerOwnershipType',
'powerPostalCode',
'powerAgreedKw',
'powerSupplyNumber',
'powerMeterNumber',
'powerCurrentSupplier',
'powerCurrentDayMeter',
'powerCurrentNightMeter',
'powerActivationStatus',
'voltonPlan',
'voltonContractDuration',
'voltonWarrantyAmount',
'voltonWarrantyOnFirstBill',
'voltonOther',
'voltonComments',
'voltonAutoPayment',
'applicationType',
'applicantWorkPhone',
'document1',
'document2',
'document3',
'document4',
'document5',
'document6',
'document7',
'document8',
'document9',
'document10',
'document11',
'document12',
'document13',
'document14',
'document15',
'applicationStatusId',
'applicantArea',
'applicantCity',
'mailArea',
'mailCity',
'powerArea',
'powerCity',
'ngAddress',
'ngPostalCode',
'ngArea',
'ngCity',
'ngPressure',
'ngHourlyCapacity',
'ngHkasp',
'ngMeterNumber',
'ngMeterType',
'ngCurrentMeterValue',
'ngConnectionExists',
'ngSupplyIsNew',
'ngSupplyReactivation',
'applicationAgentStatus',
'applicationLastStatusDate',
'dialerList',
'dialerAgent',
'dialerRecording',
'orderShipCompany',
'orderInvoiceRequired',
'callComments',
'internalCommunication',
'callGdprAcceptance',
'callGdprRecordingAcceptance',
'orderPaymentMethod',
'Expr2',
'contactZipCode',
'contactCity',
'ContactArea',
'contactGender',
'contactAge',
'crmUser',
'pauseAfterCall',
'dialerPhone',
'dialerCampaign',
'productFamilyId',
'contactMethod',
'courier',
'deliveryComments',
'courierDeliveryDate',
'courierTimeFrom',
'courierTimeTo' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'applicantName' => array( 'export_field3' ),
'applicantIdNumber' => array( 'export_field4' ),
'applicantAddress' => array( 'export_field5' ),
'applicantPostalCode' => array( 'export_field6' ),
'applicantTaxRegistrationNumber' => array( 'export_field7' ),
'applicantTaxOffice' => array( 'export_field8' ),
'applicantEmail' => array( 'export_field9' ),
'applicantProfession' => array( 'export_field10' ),
'applicantKod' => array( 'export_field11' ),
'applicantGemi' => array( 'export_field12' ),
'applicantPhone' => array( 'export_field13' ),
'applicantMobile' => array( 'export_field14' ),
'contactName' => array( 'export_field15' ),
'contactPhone' => array( 'export_field16' ),
'contactMobile' => array( 'export_field17' ),
'contactEmail' => array( 'export_field18' ),
'legalName' => array( 'export_field19' ),
'legalIdNumber' => array( 'export_field20' ),
'mailAddress' => array( 'export_field21' ),
'mailPostalCode' => array( 'export_field22' ),
'powerAddress' => array( 'export_field24' ),
'powerOwnershipType' => array( 'export_field25' ),
'powerPostalCode' => array( 'export_field26' ),
'powerAgreedKw' => array( 'export_field28' ),
'powerSupplyNumber' => array( 'export_field29' ),
'powerMeterNumber' => array( 'export_field30' ),
'powerCurrentSupplier' => array( 'export_field31' ),
'powerCurrentDayMeter' => array( 'export_field32' ),
'powerCurrentNightMeter' => array( 'export_field33' ),
'powerActivationStatus' => array( 'export_field34' ),
'voltonPlan' => array( 'export_field35' ),
'voltonContractDuration' => array( 'export_field36' ),
'voltonWarrantyAmount' => array( 'export_field37' ),
'voltonWarrantyOnFirstBill' => array( 'export_field38' ),
'voltonOther' => array( 'export_field39' ),
'voltonComments' => array( 'export_field40' ),
'voltonAutoPayment' => array( 'export_field44' ),
'applicationType' => array( 'export_field45' ),
'applicantWorkPhone' => array( 'export_field46' ),
'document1' => array( 'export_field47' ),
'document2' => array( 'export_field48' ),
'document3' => array( 'export_field49' ),
'document4' => array( 'export_field50' ),
'document5' => array( 'export_field51' ),
'document6' => array( 'export_field52' ),
'document7' => array( 'export_field53' ),
'document8' => array( 'export_field54' ),
'document9' => array( 'export_field55' ),
'document10' => array( 'export_field56' ),
'document11' => array( 'export_field57' ),
'document12' => array( 'export_field58' ),
'document13' => array( 'export_field59' ),
'document14' => array( 'export_field60' ),
'document15' => array( 'export_field61' ),
'applicationStatusId' => array( 'export_field2' ),
'applicantArea' => array( 'export_field23' ),
'applicantCity' => array( 'export_field27' ),
'mailArea' => array( 'export_field41' ),
'mailCity' => array( 'export_field42' ),
'powerArea' => array( 'export_field43' ),
'powerCity' => array( 'export_field62' ),
'ngAddress' => array( 'export_field63' ),
'ngPostalCode' => array( 'export_field64' ),
'ngArea' => array( 'export_field65' ),
'ngCity' => array( 'export_field66' ),
'ngPressure' => array( 'export_field67' ),
'ngHourlyCapacity' => array( 'export_field68' ),
'ngHkasp' => array( 'export_field69' ),
'ngMeterNumber' => array( 'export_field70' ),
'ngMeterType' => array( 'export_field71' ),
'ngCurrentMeterValue' => array( 'export_field72' ),
'ngConnectionExists' => array( 'export_field73' ),
'ngSupplyIsNew' => array( 'export_field74' ),
'ngSupplyReactivation' => array( 'export_field75' ),
'applicationAgentStatus' => array( 'export_field76' ),
'applicationLastStatusDate' => array( 'export_field77' ),
'dialerList' => array( 'export_field78' ),
'dialerAgent' => array( 'export_field79' ),
'dialerRecording' => array( 'export_field80' ),
'orderShipCompany' => array( 'export_field81' ),
'orderInvoiceRequired' => array( 'export_field82' ),
'callComments' => array( 'export_field83' ),
'internalCommunication' => array( 'export_field84' ),
'callGdprAcceptance' => array( 'export_field85' ),
'callGdprRecordingAcceptance' => array( 'export_field86' ),
'orderPaymentMethod' => array( 'export_field87' ),
'Expr2' => array( 'export_field88' ),
'contactZipCode' => array( 'export_field89' ),
'contactCity' => array( 'export_field90' ),
'ContactArea' => array( 'export_field91' ),
'contactGender' => array( 'export_field92' ),
'contactAge' => array( 'export_field93' ),
'crmUser' => array( 'export_field94' ),
'pauseAfterCall' => array( 'export_field95' ),
'dialerPhone' => array( 'export_field96' ),
'dialerCampaign' => array( 'export_field97' ),
'productFamilyId' => array( 'export_field98' ),
'contactMethod' => array( 'export_field99' ),
'courier' => array( 'export_field100' ),
'deliveryComments' => array( 'export_field101' ),
'courierDeliveryDate' => array( 'export_field102' ),
'courierTimeFrom' => array( 'export_field103' ),
'courierTimeTo' => array( 'export_field104' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field13',
'export_field14',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field24',
'export_field25',
'export_field26',
'export_field28',
'export_field29',
'export_field30',
'export_field31',
'export_field32',
'export_field33',
'export_field34',
'export_field35',
'export_field36',
'export_field37',
'export_field38',
'export_field39',
'export_field40',
'export_field44',
'export_field45',
'export_field46',
'export_field47',
'export_field48',
'export_field49',
'export_field50',
'export_field51',
'export_field52',
'export_field53',
'export_field54',
'export_field55',
'export_field56',
'export_field57',
'export_field58',
'export_field59',
'export_field60',
'export_field61',
'export_field2',
'export_field23',
'export_field27',
'export_field41',
'export_field42',
'export_field43',
'export_field62',
'export_field63',
'export_field64',
'export_field65',
'export_field66',
'export_field67',
'export_field68',
'export_field69',
'export_field70',
'export_field71',
'export_field72',
'export_field73',
'export_field74',
'export_field75',
'export_field76',
'export_field77',
'export_field78',
'export_field79',
'export_field80',
'export_field81',
'export_field82',
'export_field83',
'export_field84',
'export_field85',
'export_field86',
'export_field87',
'export_field88',
'export_field89',
'export_field90',
'export_field91',
'export_field92',
'export_field93',
'export_field94',
'export_field95',
'export_field96',
'export_field97',
'export_field98',
'export_field99',
'export_field100',
'export_field101',
'export_field102',
'export_field103',
'export_field104' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field15' => 'grid',
'export_field16' => 'grid',
'export_field17' => 'grid',
'export_field18' => 'grid',
'export_field13' => 'grid',
'export_field14' => 'grid',
'export_field19' => 'grid',
'export_field20' => 'grid',
'export_field21' => 'grid',
'export_field22' => 'grid',
'export_field24' => 'grid',
'export_field25' => 'grid',
'export_field26' => 'grid',
'export_field28' => 'grid',
'export_field29' => 'grid',
'export_field30' => 'grid',
'export_field31' => 'grid',
'export_field32' => 'grid',
'export_field33' => 'grid',
'export_field34' => 'grid',
'export_field35' => 'grid',
'export_field36' => 'grid',
'export_field37' => 'grid',
'export_field38' => 'grid',
'export_field39' => 'grid',
'export_field40' => 'grid',
'export_field44' => 'grid',
'export_field45' => 'grid',
'export_field46' => 'grid',
'export_field47' => 'grid',
'export_field48' => 'grid',
'export_field49' => 'grid',
'export_field50' => 'grid',
'export_field51' => 'grid',
'export_field52' => 'grid',
'export_field53' => 'grid',
'export_field54' => 'grid',
'export_field55' => 'grid',
'export_field56' => 'grid',
'export_field57' => 'grid',
'export_field58' => 'grid',
'export_field59' => 'grid',
'export_field60' => 'grid',
'export_field61' => 'grid',
'export_field2' => 'grid',
'export_field23' => 'grid',
'export_field27' => 'grid',
'export_field41' => 'grid',
'export_field42' => 'grid',
'export_field43' => 'grid',
'export_field62' => 'grid',
'export_field63' => 'grid',
'export_field64' => 'grid',
'export_field65' => 'grid',
'export_field66' => 'grid',
'export_field67' => 'grid',
'export_field68' => 'grid',
'export_field69' => 'grid',
'export_field70' => 'grid',
'export_field71' => 'grid',
'export_field72' => 'grid',
'export_field73' => 'grid',
'export_field74' => 'grid',
'export_field75' => 'grid',
'export_field76' => 'grid',
'export_field77' => 'grid',
'export_field78' => 'grid',
'export_field79' => 'grid',
'export_field80' => 'grid',
'export_field81' => 'grid',
'export_field82' => 'grid',
'export_field83' => 'grid',
'export_field84' => 'grid',
'export_field85' => 'grid',
'export_field86' => 'grid',
'export_field87' => 'grid',
'export_field88' => 'grid',
'export_field89' => 'grid',
'export_field90' => 'grid',
'export_field91' => 'grid',
'export_field92' => 'grid',
'export_field93' => 'grid',
'export_field94' => 'grid',
'export_field95' => 'grid',
'export_field96' => 'grid',
'export_field97' => 'grid',
'export_field98' => 'grid',
'export_field99' => 'grid',
'export_field100' => 'grid',
'export_field101' => 'grid',
'export_field102' => 'grid',
'export_field103' => 'grid',
'export_field104' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field24',
'export_field25',
'export_field26',
'export_field28',
'export_field29',
'export_field30',
'export_field31',
'export_field32',
'export_field33',
'export_field34',
'export_field35',
'export_field36',
'export_field37',
'export_field38',
'export_field39',
'export_field40',
'export_field44',
'export_field45',
'export_field46',
'export_field47',
'export_field48',
'export_field49',
'export_field50',
'export_field51',
'export_field52',
'export_field53',
'export_field54',
'export_field55',
'export_field56',
'export_field57',
'export_field58',
'export_field59',
'export_field60',
'export_field61',
'export_field2',
'export_field23',
'export_field27',
'export_field41',
'export_field42',
'export_field43',
'export_field62',
'export_field63',
'export_field64',
'export_field65',
'export_field66',
'export_field67',
'export_field68',
'export_field69',
'export_field70',
'export_field71',
'export_field72',
'export_field73',
'export_field74',
'export_field75',
'export_field76',
'export_field77',
'export_field78',
'export_field79',
'export_field80',
'export_field81',
'export_field82',
'export_field83',
'export_field84',
'export_field85',
'export_field86',
'export_field87',
'export_field88',
'export_field89',
'export_field90',
'export_field91',
'export_field92',
'export_field93',
'export_field94',
'export_field95',
'export_field96',
'export_field97',
'export_field98',
'export_field99',
'export_field100',
'export_field101',
'export_field102',
'export_field103',
'export_field104' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field13',
'export_field14',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field24',
'export_field25',
'export_field26',
'export_field28',
'export_field29',
'export_field30',
'export_field31',
'export_field32',
'export_field33',
'export_field34',
'export_field35',
'export_field36',
'export_field37',
'export_field38',
'export_field39',
'export_field40',
'export_field44',
'export_field45',
'export_field46',
'export_field47',
'export_field48',
'export_field49',
'export_field50',
'export_field51',
'export_field52',
'export_field53',
'export_field54',
'export_field55',
'export_field56',
'export_field57',
'export_field58',
'export_field59',
'export_field60',
'export_field61',
'export_field2',
'export_field23',
'export_field27',
'export_field41',
'export_field42',
'export_field43',
'export_field62',
'export_field63',
'export_field64',
'export_field65',
'export_field66',
'export_field67',
'export_field68',
'export_field69',
'export_field70',
'export_field71',
'export_field72',
'export_field73',
'export_field74',
'export_field75',
'export_field76',
'export_field77',
'export_field78',
'export_field79',
'export_field80',
'export_field81',
'export_field82',
'export_field83',
'export_field84',
'export_field85',
'export_field86',
'export_field87',
'export_field88',
'export_field89',
'export_field90',
'export_field91',
'export_field92',
'export_field93',
'export_field94',
'export_field95',
'export_field96',
'export_field97',
'export_field98',
'export_field99',
'export_field100',
'export_field101',
'export_field102',
'export_field103',
'export_field104' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field3' => array( 'field' => 'applicantName',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'applicantIdNumber',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'applicantAddress',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'applicantPostalCode',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'applicantTaxRegistrationNumber',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'applicantTaxOffice',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'applicantEmail',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'applicantProfession',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'applicantKod',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'applicantGemi',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'applicantPhone',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'applicantMobile',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'contactName',
'type' => 'export_field' ),
'export_field16' => array( 'field' => 'contactPhone',
'type' => 'export_field' ),
'export_field17' => array( 'field' => 'contactMobile',
'type' => 'export_field' ),
'export_field18' => array( 'field' => 'contactEmail',
'type' => 'export_field' ),
'export_field19' => array( 'field' => 'legalName',
'type' => 'export_field' ),
'export_field20' => array( 'field' => 'legalIdNumber',
'type' => 'export_field' ),
'export_field21' => array( 'field' => 'mailAddress',
'type' => 'export_field' ),
'export_field22' => array( 'field' => 'mailPostalCode',
'type' => 'export_field' ),
'export_field24' => array( 'field' => 'powerAddress',
'type' => 'export_field' ),
'export_field25' => array( 'field' => 'powerOwnershipType',
'type' => 'export_field' ),
'export_field26' => array( 'field' => 'powerPostalCode',
'type' => 'export_field' ),
'export_field28' => array( 'field' => 'powerAgreedKw',
'type' => 'export_field' ),
'export_field29' => array( 'field' => 'powerSupplyNumber',
'type' => 'export_field' ),
'export_field30' => array( 'field' => 'powerMeterNumber',
'type' => 'export_field' ),
'export_field31' => array( 'field' => 'powerCurrentSupplier',
'type' => 'export_field' ),
'export_field32' => array( 'field' => 'powerCurrentDayMeter',
'type' => 'export_field' ),
'export_field33' => array( 'field' => 'powerCurrentNightMeter',
'type' => 'export_field' ),
'export_field34' => array( 'field' => 'powerActivationStatus',
'type' => 'export_field' ),
'export_field35' => array( 'field' => 'voltonPlan',
'type' => 'export_field' ),
'export_field36' => array( 'field' => 'voltonContractDuration',
'type' => 'export_field' ),
'export_field37' => array( 'field' => 'voltonWarrantyAmount',
'type' => 'export_field' ),
'export_field38' => array( 'field' => 'voltonWarrantyOnFirstBill',
'type' => 'export_field' ),
'export_field39' => array( 'field' => 'voltonOther',
'type' => 'export_field' ),
'export_field40' => array( 'field' => 'voltonComments',
'type' => 'export_field' ),
'export_field44' => array( 'field' => 'voltonAutoPayment',
'type' => 'export_field' ),
'export_field45' => array( 'field' => 'applicationType',
'type' => 'export_field' ),
'export_field46' => array( 'field' => 'applicantWorkPhone',
'type' => 'export_field' ),
'export_field47' => array( 'field' => 'document1',
'type' => 'export_field' ),
'export_field48' => array( 'field' => 'document2',
'type' => 'export_field' ),
'export_field49' => array( 'field' => 'document3',
'type' => 'export_field' ),
'export_field50' => array( 'field' => 'document4',
'type' => 'export_field' ),
'export_field51' => array( 'field' => 'document5',
'type' => 'export_field' ),
'export_field52' => array( 'field' => 'document6',
'type' => 'export_field' ),
'export_field53' => array( 'field' => 'document7',
'type' => 'export_field' ),
'export_field54' => array( 'field' => 'document8',
'type' => 'export_field' ),
'export_field55' => array( 'field' => 'document9',
'type' => 'export_field' ),
'export_field56' => array( 'field' => 'document10',
'type' => 'export_field' ),
'export_field57' => array( 'field' => 'document11',
'type' => 'export_field' ),
'export_field58' => array( 'field' => 'document12',
'type' => 'export_field' ),
'export_field59' => array( 'field' => 'document13',
'type' => 'export_field' ),
'export_field60' => array( 'field' => 'document14',
'type' => 'export_field' ),
'export_field61' => array( 'field' => 'document15',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'applicationStatusId',
'type' => 'export_field' ),
'export_field23' => array( 'field' => 'applicantArea',
'type' => 'export_field' ),
'export_field27' => array( 'field' => 'applicantCity',
'type' => 'export_field' ),
'export_field41' => array( 'field' => 'mailArea',
'type' => 'export_field' ),
'export_field42' => array( 'field' => 'mailCity',
'type' => 'export_field' ),
'export_field43' => array( 'field' => 'powerArea',
'type' => 'export_field' ),
'export_field62' => array( 'field' => 'powerCity',
'type' => 'export_field' ),
'export_field63' => array( 'field' => 'ngAddress',
'type' => 'export_field' ),
'export_field64' => array( 'field' => 'ngPostalCode',
'type' => 'export_field' ),
'export_field65' => array( 'field' => 'ngArea',
'type' => 'export_field' ),
'export_field66' => array( 'field' => 'ngCity',
'type' => 'export_field' ),
'export_field67' => array( 'field' => 'ngPressure',
'type' => 'export_field' ),
'export_field68' => array( 'field' => 'ngHourlyCapacity',
'type' => 'export_field' ),
'export_field69' => array( 'field' => 'ngHkasp',
'type' => 'export_field' ),
'export_field70' => array( 'field' => 'ngMeterNumber',
'type' => 'export_field' ),
'export_field71' => array( 'field' => 'ngMeterType',
'type' => 'export_field' ),
'export_field72' => array( 'field' => 'ngCurrentMeterValue',
'type' => 'export_field' ),
'export_field73' => array( 'field' => 'ngConnectionExists',
'type' => 'export_field' ),
'export_field74' => array( 'field' => 'ngSupplyIsNew',
'type' => 'export_field' ),
'export_field75' => array( 'field' => 'ngSupplyReactivation',
'type' => 'export_field' ),
'export_field76' => array( 'field' => 'applicationAgentStatus',
'type' => 'export_field' ),
'export_field77' => array( 'field' => 'applicationLastStatusDate',
'type' => 'export_field' ),
'export_field78' => array( 'field' => 'dialerList',
'type' => 'export_field' ),
'export_field79' => array( 'field' => 'dialerAgent',
'type' => 'export_field' ),
'export_field80' => array( 'field' => 'dialerRecording',
'type' => 'export_field' ),
'export_field81' => array( 'field' => 'orderShipCompany',
'type' => 'export_field' ),
'export_field82' => array( 'field' => 'orderInvoiceRequired',
'type' => 'export_field' ),
'export_field83' => array( 'field' => 'callComments',
'type' => 'export_field' ),
'export_field84' => array( 'field' => 'internalCommunication',
'type' => 'export_field' ),
'export_field85' => array( 'field' => 'callGdprAcceptance',
'type' => 'export_field' ),
'export_field86' => array( 'field' => 'callGdprRecordingAcceptance',
'type' => 'export_field' ),
'export_field87' => array( 'field' => 'orderPaymentMethod',
'type' => 'export_field' ),
'export_field88' => array( 'field' => 'Expr2',
'type' => 'export_field' ),
'export_field89' => array( 'field' => 'contactZipCode',
'type' => 'export_field' ),
'export_field90' => array( 'field' => 'contactCity',
'type' => 'export_field' ),
'export_field91' => array( 'field' => 'ContactArea',
'type' => 'export_field' ),
'export_field92' => array( 'field' => 'contactGender',
'type' => 'export_field' ),
'export_field93' => array( 'field' => 'contactAge',
'type' => 'export_field' ),
'export_field94' => array( 'field' => 'crmUser',
'type' => 'export_field' ),
'export_field95' => array( 'field' => 'pauseAfterCall',
'type' => 'export_field' ),
'export_field96' => array( 'field' => 'dialerPhone',
'type' => 'export_field' ),
'export_field97' => array( 'field' => 'dialerCampaign',
'type' => 'export_field' ),
'export_field98' => array( 'field' => 'productFamilyId',
'type' => 'export_field' ),
'export_field99' => array( 'field' => 'contactMethod',
'type' => 'export_field' ),
'export_field100' => array( 'field' => 'courier',
'type' => 'export_field' ),
'export_field101' => array( 'field' => 'deliveryComments',
'type' => 'export_field' ),
'export_field102' => array( 'field' => 'courierDeliveryDate',
'type' => 'export_field' ),
'export_field103' => array( 'field' => 'courierTimeFrom',
'type' => 'export_field' ),
'export_field104' => array( 'field' => 'courierTimeTo',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 4,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>