<?php
$dalTableCalls = array();
$dalTableCalls["id"] = array("type"=>3,"varname"=>"id", "name" => "id");
$dalTableCalls["contactId"] = array("type"=>3,"varname"=>"contactId", "name" => "contactId");
$dalTableCalls["callStart"] = array("type"=>135,"varname"=>"callStart", "name" => "callStart");
$dalTableCalls["callHangup"] = array("type"=>135,"varname"=>"callHangup", "name" => "callHangup");
$dalTableCalls["callEnd"] = array("type"=>135,"varname"=>"callEnd", "name" => "callEnd");
$dalTableCalls["talkTime"] = array("type"=>3,"varname"=>"talkTime", "name" => "talkTime");
$dalTableCalls["typingTime"] = array("type"=>3,"varname"=>"typingTime", "name" => "typingTime");
$dalTableCalls["totalCallTime"] = array("type"=>3,"varname"=>"totalCallTime", "name" => "totalCallTime");
$dalTableCalls["tvchannel"] = array("type"=>200,"varname"=>"tvchannel", "name" => "tvchannel");
$dalTableCalls["broadcast"] = array("type"=>200,"varname"=>"broadcast", "name" => "broadcast");
$dalTableCalls["seller"] = array("type"=>200,"varname"=>"seller", "name" => "seller");
$dalTableCalls["callStatusId"] = array("type"=>3,"varname"=>"callStatusId", "name" => "callStatusId");
$dalTableCalls["callDenialReasonID"] = array("type"=>3,"varname"=>"callDenialReasonID", "name" => "callDenialReasonID");
$dalTableCalls["callClassificationID"] = array("type"=>3,"varname"=>"callClassificationID", "name" => "callClassificationID");
$dalTableCalls["callSubClassificationID"] = array("type"=>3,"varname"=>"callSubClassificationID", "name" => "callSubClassificationID");
$dalTableCalls["remarks"] = array("type"=>200,"varname"=>"remarks", "name" => "remarks");
$dalTableCalls["redialDate"] = array("type"=>135,"varname"=>"redialDate", "name" => "redialDate");
$dalTableCalls["redialComments"] = array("type"=>200,"varname"=>"redialComments", "name" => "redialComments");
$dalTableCalls["redialIsPrivate"] = array("type"=>3,"varname"=>"redialIsPrivate", "name" => "redialIsPrivate");
$dalTableCalls["redialDone"] = array("type"=>3,"varname"=>"redialDone", "name" => "redialDone");
$dalTableCalls["contactMethod"] = array("type"=>200,"varname"=>"contactMethod", "name" => "contactMethod");
$dalTableCalls["courier"] = array("type"=>200,"varname"=>"courier", "name" => "courier");
$dalTableCalls["deliveryComments"] = array("type"=>200,"varname"=>"deliveryComments", "name" => "deliveryComments");
$dalTableCalls["courierDeliveryDate"] = array("type"=>135,"varname"=>"courierDeliveryDate", "name" => "courierDeliveryDate");
$dalTableCalls["courierTimeFrom"] = array("type"=>200,"varname"=>"courierTimeFrom", "name" => "courierTimeFrom");
$dalTableCalls["courierTimeTo"] = array("type"=>200,"varname"=>"courierTimeTo", "name" => "courierTimeTo");
$dalTableCalls["dialerPhone"] = array("type"=>200,"varname"=>"dialerPhone", "name" => "dialerPhone");
$dalTableCalls["dialerCallEpoch"] = array("type"=>14,"varname"=>"dialerCallEpoch", "name" => "dialerCallEpoch");
$dalTableCalls["dialerCampaign"] = array("type"=>200,"varname"=>"dialerCampaign", "name" => "dialerCampaign");
$dalTableCalls["dialerList"] = array("type"=>200,"varname"=>"dialerList", "name" => "dialerList");
$dalTableCalls["dialerLeadID"] = array("type"=>200,"varname"=>"dialerLeadID", "name" => "dialerLeadID");
$dalTableCalls["dialerAgent"] = array("type"=>200,"varname"=>"dialerAgent", "name" => "dialerAgent");
$dalTableCalls["dialerRecording"] = array("type"=>200,"varname"=>"dialerRecording", "name" => "dialerRecording");
$dalTableCalls["productFamilyId"] = array("type"=>3,"varname"=>"productFamilyId", "name" => "productFamilyId");
$dalTableCalls["orderShipCompany"] = array("type"=>3,"varname"=>"orderShipCompany", "name" => "orderShipCompany");
$dalTableCalls["orderInvoiceRequired"] = array("type"=>3,"varname"=>"orderInvoiceRequired", "name" => "orderInvoiceRequired");
$dalTableCalls["callComments"] = array("type"=>200,"varname"=>"callComments", "name" => "callComments");
$dalTableCalls["internalCommunication"] = array("type"=>3,"varname"=>"internalCommunication", "name" => "internalCommunication");
$dalTableCalls["callGdprAcceptance"] = array("type"=>3,"varname"=>"callGdprAcceptance", "name" => "callGdprAcceptance");
$dalTableCalls["callGdprRecordingAcceptance"] = array("type"=>3,"varname"=>"callGdprRecordingAcceptance", "name" => "callGdprRecordingAcceptance");
$dalTableCalls["orderPaymentMethod"] = array("type"=>3,"varname"=>"orderPaymentMethod", "name" => "orderPaymentMethod");
$dalTableCalls["contactName"] = array("type"=>200,"varname"=>"contactName", "name" => "contactName");
$dalTableCalls["contactZipCode"] = array("type"=>200,"varname"=>"contactZipCode", "name" => "contactZipCode");
$dalTableCalls["contactCity"] = array("type"=>200,"varname"=>"contactCity", "name" => "contactCity");
$dalTableCalls["ContactArea"] = array("type"=>200,"varname"=>"ContactArea", "name" => "ContactArea");
$dalTableCalls["contactGender"] = array("type"=>3,"varname"=>"contactGender", "name" => "contactGender");
$dalTableCalls["contactAge"] = array("type"=>3,"varname"=>"contactAge", "name" => "contactAge");
$dalTableCalls["crmUser"] = array("type"=>200,"varname"=>"crmUser", "name" => "crmUser");
$dalTableCalls["pauseAfterCall"] = array("type"=>200,"varname"=>"pauseAfterCall", "name" => "pauseAfterCall");
	$dalTableCalls["id"]["key"]=true;

$dal_info["CallCenter_at_10_41_2_31_dbo_Calls"] = &$dalTableCalls;
?>