<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_agentcallsview  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["ProcessValuesAdd"]=true;


		$this->events["AfterAdd"]=true;



	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Process record values
function ProcessValuesAdd(&$values, &$pageObject)
{

		if ($_GET['dialerAgent']=='') {
  $values['dialerAgent'] = "noDialerInfo";
} else
{
  $values['dialerAgent'] = $_GET['dialerAgent'];
};

if ($_GET['dialerPhone']=='') {
  $values['dialerPhone'] = "Άγνωστο";
} else
{
$values['dialerPhone'] = $_GET['dialerPhone'];
};

$values['dialerCampaign'] = $_GET['dialerCampaign'];
$values['dialerList'] = $_GET['dialerList'];
$values['dialerRecording'] = $_GET['dialerRecording'];
$values['dialerCallTime'] = $_GET['dialerCallTime'];
$values['dialerLeadID'] = $_GET['dialerLeadID'];
$values['contactId'] = $_GET['contactId'];
$values['dialerCallEpoch'] = $_GET['callEpoch'];
$values['tvchannel'] = $_GET['tvchannel'];
$values['broadcast'] = $_GET['broadcast'];
$values['seller'] = $_GET['seller'];
$values['callClassificationID'] = $_GET['callClassificationID'];
$values['callSubClassificationID'] = $_GET['callSubClassificationID'];
$values['callStatusId'] = 1014;

$agentApiUrl = "http://10.41.2.204/agc/api.php?source=crm&user=tsikasapi&pass=ggm&agent_user=";
$pageObject->setProxyValue('agentApiUrl',$agentApiUrl);

$userData = Security::getUserName();
$pageObject->setProxyValue('userData',$userData);


// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function ProcessValuesAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record added
function AfterAdd(&$values, &$keys, $inline, &$pageObject)
{

		
header("Location: upcomingcallsforredial_list.php");
exit();



;		
} // function AfterAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
